### PR TITLE
Resolve GPDB_12_MERGE_FIXME in cdbgroupingpaths.c: Compute aggregate hash table size and compare with work_mem.

### PR DESCRIPTION
**Pull request by Aegeaner**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by SmartKeyerror** [comment]
If I remember correctly, `work_mem` should have been removed by Greenplum? And we use `statement_mem` currently.

**Comment by Aegeaner** [comment]
> > 
> 
> Yes, the current code still use `work_mem` to compute some memory, but **it's not correct, we should clean all the codes that using `work_mem`**. The slack channel #greenplum-help-wanted-issue-chn had discussed this, you can find more detail information from that.

No matter. Moved to `maintenance_work_mem`.

**Comment by kainwen** [comment]
> > 
> 
> Yes, the current code still use `work_mem` to compute some memory, but **it's not correct, we should clean all the codes that using `work_mem`**. The slack channel #greenplum-help-wanted-issue-chn had discussed this, you can find more detail information from that.

This is planning stage and we do not use `statement_mem` either. 

It is a long hard issue how to estimate hash table during `creating path` stage.

Personally, I think we can just remove the fixme comments.

**Comment by Aegeaner** [comment]
> > > 
> > 
> > 
> > Yes, the current code still use `work_mem` to compute some memory, but **it's not correct, we should clean all the codes that using `work_mem`**. The slack channel #greenplum-help-wanted-issue-chn had discussed this, you can find more detail information from that.
> 
> This is planning stage and we do not use `statement_mem` either.
> 
> It is a long hard issue how to estimate hash table during `creating path` stage.
> 
> Personally, I think we can just remove the fixme comments.

The `work_mem` is confirmed deprecated, I will close this PR and submit a new one.

**Pull request closed without merging**
