### PR TITLE
WIP: ubuntu build clean up

### PR DESCRIPTION
**Pull request by d**
To reviewers: this is a work-in-progress, come back later

### CODE REVIEW

**Comment by ashwinstar** [comment]
Just curious why have it as PR then?

**Comment by d** [comment]
Ah just realized what we ship isn't really configured in the things I change ...

**Comment by danielgustafsson** [comment]
This is conflicting with master, do you intend to return to this PR?

**Comment by kmacoskey** [comment]
All of the CI code for Ubuntu 16 was completely removed (master, 6X_STABLE don't support Ubuntu 16):

https://github.com/greenplum-db/gpdb/commit/674380d64272faf48042387cc4c402ce0502ca4f

This PR is no longer valid.

**Pull request closed without merging**
