### PR TITLE
Remove gpsys1

### PR DESCRIPTION
**Pull request by tylarb**
I'm not quite sure of the purpose of this utility, nor, apparently, is
any readme or historical repo.

Apart from a small fix provided in
commit 71d67305fbbeaaa22c0090b33e64f6bdcf22436c,
there has been no modification to this file since at least 2008. More
importantly, I'm not quite sure of any reasonable use for this file. The
supported platforms are only linux, darwin, or sunos5, and the listed
use, of printing the memory size in bytes, is trivial on any of those
systems without resorting to some python script that wraps a command line
call.

Given that it hasn't been updated since 2008, it's still compatible with
some ancient version of python, which means that it's yet another file to
upgrade to python 3 - in this case, let's drop the program, rather than
bother upgrading it.

Authored-by: Tyler Ramer <tramer@pivotal.io>

### CODE REVIEW

**Comment by Eulerizeit** [comment]
Do you know if we ship this in 6.x?  If so we need to deprecate it there at a minimum.

**Comment by tylarb** [comment]
> Do you know if we ship this in 6.x? If so we need to deprecate it there at a minimum.

It looks to be documented, without a deprecation warning. I'll take care of this. 
https://gpdb.docs.pivotal.io/6-7/utility_guide/ref/gpsys.html

**Comment by mkiyama** [comment]
@tylarb 
Removing the xml doc file will break the GPDB doc build pipeline.
gpdb-doc/dita/utility_guide/ref/gpsys.xml

The docs team can handle the change to the docs files, and you can remove it from this PR.

cc: @dyozie

**Comment by tylarb** [comment]
@mkiyama Can you handle the deprecation notice in gpdb 6 docs as well? Thanks!

**Comment by mkiyama** [comment]
Yup, the docs team will handle the deprecation in 6 and removal in 7

**Pull request merged**
