### PR TITLE
Disallow Insert and Delete triggers on SplitUpdate

### PR DESCRIPTION
**Pull request by yanwr1**
Considering that the original command is UPDATE for a SplitUpdate, fire
INSERT and DELETE triggers may lead to the wrong action to be enforced.
And the triggers in GPDB may require cross segments data changes, disallow
the INSERT and DELETE triggers on a SplitUpdate.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by SmartKeyerror — APPROVED** [review]
GPDB is not support trigger, so we can just let this go.

**Comment by kainwen** [comment]
This is ready? Can we push it? @yanwr1

**Comment by yanwr1** [comment]
> This is ready? Can we push it? @yanwr1

If we don't need more reviewers, I can push it now.

**Comment by kainwen** [comment]
I think we can push this, thanks.

**Pull request merged**
