### PR TITLE
Fix NULL reference of stmt reported by coverity.

### PR DESCRIPTION
**Pull request by ashwinstar**

### CODE REVIEW

**Comment by asimrp** [comment]
There is another reference to stmt on line 1624 in the same function, that is protected by a NULL check already.  This change makes NULL checks consistent within the function.  +1 to push it.

**Comment by hlinnaka** [comment]
Sure, this change looks OK as far as it goes, but the fact that we haven't been able to reproduce it suggests that:

a) there are no regression tests covering this codepath, or
b) this is in fact dead code.

We need to figure out which is it. Or we remove the functionality altogether, in which case we don't need to care.

**Comment by ashwinstar** [comment]
On Fri, Nov 6, 2015 at 10:17 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> Sure, this change looks OK as far as it goes, but the fact that we haven't
> been able to reproduce it suggests that:
>
> a) there are no regression tests covering this codepath, or
>
Still everything else is green and I am able to run tests with this change,
cannot say if we have coverage for the same or not.
Not way to just grep around to find the same, as depends on data.

> b) this is in fact dead code.
>
> We need to figure out which is it. Or we remove the functionality
> altogether, in which case we don't need to care.
>
It's not dead code currently till ErrorTable functionality is not removed.

Case with no errors in loading file and not reusing any existing (error)
table produces the issue.
Something like

```
COPY h from 'input.tbl' WITH DELIMITER '|' LOG ERRORS INTO abcd SEGMENT
REJECT LIMIT 10 ROWS;
NOTICE:  Error table "abcd1" does not exist. Auto generating an error table
with the same name
WARNING:  The error table was created in the same transaction as this
operation. It will get dropped if transaction rolls back even if bad rows
are present
HINT:  To avoid this create the error table ahead of time using: CREATE
TABLE <name> (cmdtime timestamp with time zone, relname text, filename
text, linenum integer, bytenum integer, errmsg text, rawdata text, rawbytes
bytea)
NOTICE:  Dropping the auto-generated unused error table
```

Stack
```
2015-11-06 11:21:48.286307 PST,,,p90742,th0,,,2015-11-06 10:32:30
PST,0,con57,cmd20,seg-1,,,,,"PANIC","XX000","Unexpected internal error:
Master process received signal SIGBUS",,,,,,,0,,,,"1    0x5993c3 postgres
StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x204
2    0x486dc7 postgres CdbProgramErrorHandler + 0x13d
3    0x90764deb libsystem_platform.dylib _sigtramp + 0x2b
4    0xffffffff <symbol not found>
5    0x750634 postgres DropErrorTable + 0x15d
6    0x7501b2 postgres destroyCdbSreh + 0x70
7    0x1e5bd6 postgres DoCopyInternal + 0x2030
8    0x1e5e49 postgres DoCopy + 0xad
9    0x490aba postgres ProcessUtility + 0xdd1
10   0x48d4e6 postgres PortalRunUtility + 0x263
11   0x48d910 postgres PortalRunMulti + 0x30c
12   0x48ca22 postgres PortalRun + 0x3f3
13   0x483c26 postgres exec_simple_query + 0x9a1
```

Moving ahead to push this commit. Removal of ErrorTable can be prioritized
once confirmation is received from Ivan.

**Comment by hlinnaka** [comment]
On 11/06/2015 09:34 PM, Ashwin Agrawal wrote:
> On Fri, Nov 6, 2015 at 10:17 AM, Heikki Linnakangas <
> notifications@github.com> wrote:
>
>> Sure, this change looks OK as far as it goes, but the fact that we haven't
>> been able to reproduce it suggests that:
>>
>> a) there are no regression tests covering this codepath, or
>>
> Still everything else is green and I am able to run tests with this change,
> cannot say if we have coverage for the same or not.
> Not way to just grep around to find the same, as depends on data.

Clearly we don't have a test case that covers this codepath (i.e. 
DropErrorTable), or you would get a certain segfault. I spent a few 
minutes on tracing how you end up there, and came up with this test case:

echo > "/tmp/foo

In psql:

CREATE TABLE foo (id int4);

copy foo from '/tmp/foo' log errors into foobar segment reject limit 10;

It segfaults:

postgres=# copy foo from '/tmp/foo' log errors into foobar segment 
reject limit 10;
NOTICE:  Error table "foobar" does not exist. Auto generating an error 
table with the same name
WARNING:  The error table was created in the same transaction as this 
operation. It will get dropped if transaction rolls back even if bad 
rows are present
HINT:  To avoid this create the error table ahead of time using: CREATE 
TABLE <name> (cmdtime timestamp with time zone, relname text, filename 
text, linenum integer, bytenum integer, errmsg text, rawdata text, 
rawbytes bytea)
NOTICE:  Dropping the auto-generated unused error table
HINT:  Use KEEP in LOG INTO clause to force keeping the error table alive
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

- Heikki

**Comment by ashwinstar** [comment]
Missing how is it different than repro I already provided earlier
showcasing it segfaults and what your are trying to convey here.

**Comment by hlinnaka** [comment]
On 11/06/2015 11:21 PM, Ashwin Agrawal wrote:
> Missing how is it different than repro I already provided earlier
> showcasing it segfaults and what your are trying to convey here.

D'oh, I somehow missed that you had a repro in your earlier commit. 
Sorry for the noise. But please do include it in a regression test.

- Heikki

**Comment by ashwinstar** [comment]
Added the test.

**Comment by ashwinstar** [comment]
Pushed the code.

**Pull request closed without merging**
