### PR TITLE
Add test cases for updates of append-only tables.

### PR DESCRIPTION
**Pull request by hlinnaka**
Yes, append-only tables are not actually append-only in modern version of
GPDB, hence the oxymoronic name.

These tests are ported from Pivotal's TINC test suite which has not been
open sourced - we are porting tests out of the suite instead.

### CODE REVIEW

**Comment by hlinnaka** [comment]
These tests take almost two minutes on my laptop. Most of that is from the "index2" test case. So we'll probably have to do something about that.

But what do you think of this general approach to porting TINC tests? I've kept some of the directory structure.

The  original TINC "full" and "basic" test cases used gptorment to populate the tables. That seemd pointless to me, so I just put the corresponding INSERT statements in the .sql files. Does that look OK to you all? Am I correct that gptorment wasn't actually doing anything interesting in these cases?

**Comment by hlinnaka** [comment]
Also, the comments in outdatedindex and outdated_partialindex tests talk about testing crash recovery. But AFAICS, there is not crashes involved in these tests in TINC either. Perhaps we don't really need those tests in their current form and we should just remove them?

**Comment by ivannovick** [comment]
@GodenYao can you review this please?

**Comment by ashwinstar** [comment]
On Tue, Dec 29, 2015 at 12:19 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> These tests take almost two minutes on my laptop. Most of that is from the
> "index2" test case. So we'll probably have to do something about that.
>
> But what do you think of this general approach to porting TINC tests? I've
> kept some of the directory structure.
>
Looks great. These are simple just sql based test and can leverage
pg_regress. Only need to think with more and more test being moved should
it be all part of ICG or need different targets.

The original TINC "full" and "basic" test cases used gptorment to populate
> the tables. That seemd pointless to me, so I just put the corresponding
> INSERT statements in the .sql files. Does that look OK to you all? Am I
> correct that gptorment wasn't actually doing anything interesting in these
> cases?
>
Agree in this case gptorment use was not adding any value, as test results
are not dependent on concurrent insert to AO tables. Though not intentional
I think but tests were validating vacuum when multiple segfiles are present
for AO table due to gptorment use which gets lost now by movement to
sequential inserts.

**Comment by ashwinstar** [comment]
On Tue, Dec 29, 2015 at 12:21 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> Also, the comments in outdatedindex and outdated_partialindex tests talk
> about testing crash recovery. But AFAICS, there is not crashes involved in
> these tests in TINC either. Perhaps we don't really need those tests in
> their current form and we should just remove them?
>
Yes, looking at the test doesn't seem to be validating what the comment
intends. Seems okay to remove as normal index selects/deletes/updates etc
is verified in other tests.

**Comment by ashwinstar** [comment]
Looks good. Thank You.

**Comment by ashwinstar** [comment]
@hlinnaka Any plans to push this in, we might push in more test from uao based on same.

**Comment by hlinnaka** [comment]
On 10/02/16 00:38, Ashwin Agrawal wrote:
> @hlinnaka Any plans to push this in, we might push in more test from uao based on same.

Sorry, I haven't gotten around to it. I'm somewhat worried by the extra 
runtime this adds to the regression tests, I've been meaning to have 
another look if we can bring that down (hence PR #220, but that won't 
completely solve the issue either). But perhaps we should just push this 
now, and optimizer later. It's a bit lame excuse to not have tests 
because they would take too long..

If you want to build on top of this, would you like to take this over, 
instead of waiting for me to have sufficient round tuits?

- Heikki

**Comment by ashwinstar** [comment]
On Wed, Feb 10, 2016 at 12:54 PM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 10/02/16 00:38, Ashwin Agrawal wrote:
> > @hlinnaka Any plans to push this in, we might push in more test from uao
> based on same.
>
> Sorry, I haven't gotten around to it. I'm somewhat worried by the extra
> runtime this adds to the regression tests, I've been meaning to have
> another look if we can bring that down (hence PR #220, but that won't
> completely solve the issue either). But perhaps we should just push this
> now, and optimizer later. It's a bit lame excuse to not have tests
> because they would take too long..
>
> If you want to build on top of this, would you like to take this over,
> instead of waiting for me to have sufficient round tuits?


Yes, lets absorb this in its current form. We can optimize the same later
by improvements to product or refactoring the tests further.

**Comment by ivannovick** [comment]
Great! excited about this one

**Comment by hlinnaka** [comment]
Ashwin pushed this, closing. Thanks!

**Pull request closed without merging**
