### PR TITLE
Move subtransaction limit removal tests from TINC to ICG.

### PR DESCRIPTION
**Pull request by asimrp**
Some of the TINC tests under "limit_removal" heading were testing
subtransaction functionality but not limit remotal in particular.  Move them to
distributed_transactions.sql.  The limit in "limit removal" refers to the
in-progress subtransactions array SharedSnapshotSlot->subxids.  If the limit of
MaxGpSavePoints subtransactions is reached, the array is spilled over to disk.
More elaborate tests for this funcionality exist in TINC
(mpp/gpdb/tests/storage/sub_transaction_limit_removal).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@asimrp Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1410)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1410) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@asimrp Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1410)!

**Comment by ashwinstar** [comment]
How much runtime increases for distributed_transactions with the additions ? If its not much then +1 else better to have separate test for sub-transactions.

**Comment by asimrp** [comment]
The increase in distributed_transactions time is from 2.75 sec to 7.8 secs.  That's huge but in the same parallel group, we already have two tests taking more than 17 seconds to run.

**Comment by ashwinstar** [comment]
Seems fine then.

**Comment by asimrp** [comment]
Pushed to master: 1e612781056b30e343c936f310e71edd6ebb86ce

**Pull request closed without merging**
