### PR TITLE
add osx to tests

### PR DESCRIPTION
**Pull request by davecramer**

### CODE REVIEW

**Comment by xinzweb** [comment]
Need --pre to help install the psi on OSX.

**Comment by davecramer** [comment]
@xinzweb gpfdist.c:1843:11: error: 'BIO_new' is deprecated: first deprecated in OS X 10.7 [-Werror,-Wdeprecated-declarations]
                r->io = BIO_new(BIO_f_buffer());

Looks like a real error ??

**Comment by asimrp** [comment]
Found this note on developer.apple.com:

> Note: Although a version of OpenSSL libraries is included as part of OS X, the OpenSSL library does not guarantee binary compatibility across different versions of OpenSSL. For this reason, linking to the built-in copy of OpenSSL is deprecated as of OS X v10.7. If you want to use OpenSSL, provide your own copy of the library so that you can control precisely which version of OpenSSL your program is linked against.

https://developer.apple.com/library/prerelease/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/SecureNetworking/SecureNetworking.html

**Comment by xinzweb** [comment]
usually i just build with --disable-gpfdist on my OSX. Still need to fix it for all the dependencies.

**Comment by davecramer** [comment]
I see there is a PR https://github.com/greenplum-db/gpdb/pull/351

That intends to add gpfdist to core. Will this completely break OSX builds ?

Dave Cramer

**Comment by xinzweb** [comment]
So far, I haven't figured out a way to work around the `gpfdist` issue on OSX. If we want to bring the OSX up and want to treat it as first class developing environment, then we have to fix the `gpfdist` issue on OSX. 

Maybe remove the `-Werror` from the OSX flags. thoughts?

**Comment by davecramer** [comment]
If we expect travis to build it, it has to build without errors. Were you
able to fix the OpenSSL error ?

Dave Cramer

**Comment by xinzweb** [comment]
Since https://github.com/greenplum-db/gpdb/pull/367 is in, can you retry the this PR on Travis?

**Comment by xinzweb** [comment]
Re-triggered the build: https://travis-ci.org/greenplum-db/gpdb/jobs/108312612.

@davecramer do we need to rebase this fix, and then trigger again?

**Comment by xinzweb** [comment]
It's passed! +1. Please get this one in. Thanks.

**Comment by danielgustafsson** [comment]
Cool! .. :+1: on committing these squashed into one.

**Comment by davecramer** [comment]
closed via https://github.com/greenplum-db/gpdb/commit/15e6e8b938c176b572fc561ddb59da29e2d39428

**Pull request closed without merging**
