### PR TITLE
Remove gpexpand TINC tests

### PR DESCRIPTION
**Pull request by dkrieger-pvtl**
This removes gpexpand_1 and gpexpand_2 concourse jobs in favor of the gpexpand behave tests.

This PR is dependent on https://github.com/greenplum-db/gpdb/pull/6361/, and we only plan to merge after that PR is merged.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [x] Document changes
- [x] Communicate in the mailing list if needed
- [x] Pass `make installcheck`

### CODE REVIEW

**Comment by kmacoskey** [comment]
A reference to `gpexpand_1` for jobs that don't block release should be removed as well:
https://github.com/greenplum-db/gpdb/blob/master/concourse/pipelines/gen_pipeline.py#L63

**Comment by dkrieger-pvtl** [comment]
> A reference to `gpexpand_1` for jobs that don't block release should be removed as well:
> https://github.com/greenplum-db/gpdb/blob/master/concourse/pipelines/gen_pipeline.py#L63

Thanks, we made this change and re-pushed to the PR.  We also searched for ```expand_1``` and ```expand_2``` in this branch and didn't see any other references.

**Comment by asimrp** [comment]
If the tests are similar in 5X_STABLE, does it make sense to back patch this?

**Comment by dkrieger-pvtl** [comment]
> If the tests are similar in 5X_STABLE, does it make sense to back patch this?

I spoke with @jmcatamney and he said that we probably should...we'll take a note and consider doing this.

**Pull request merged**
