### PR TITLE
Remove the code to collect writer QE's transaction information from segments to dispatcher

### PR DESCRIPTION
**Pull request by eurekaka**

### CODE REVIEW

**Comment by asimrp** [comment]
Dispatcher no longer needs QE writer's transaction information?  The answer may be obvious but I haven't been following recent dispatcher changes too closely and couldn't guess it from the diff of this PR.

**Comment by eurekaka** [comment]
Yes, those information are not used among the code base now.

**Comment by hlinnaka** [comment]
Oh, that's great!

I'm curious, what was the transaction information used for before? What change made it obsolete?

**Comment by eurekaka** [comment]
The transaction information was used for dispatch agent code, and was not removed completely when deprecating dispatch agent.

**Comment by eurekaka** [comment]
Merged, thanks for reviewing.

**Pull request closed without merging**
