### PR TITLE
Backport interval type coerce bug fix

### PR DESCRIPTION
**Pull request by amosbird**
Currently `select interval '1' year` results in zero output, which breaks some tpch queries with filters like `l_shipdate >= date '1995-01-01' and l_shipdate < date '1995-01-01' + interval '1' year` and leads to `One-Time Filter: false`. This patch backports the upstream fix of such issue.

### CODE REVIEW

**Comment by hlinnaka** [comment]
So, this is a backport of upstream commit f867339c014, from PostgreSQL 8.4. Would be good to mention that in the commit message.

Commit f867339c014 contained more changes - do we need to include those as well? If not, why not? It also included new regression tests, it would be good to backport those as well.

I'm generally not in favor of cherry-picking misc upstream commits, but this one isn't too invasive, and it's coming soon in PostgreSQL 8.4 anyway, so I can hold my nose for this one.

**Comment by amosbird** [comment]
ah, I had a hard time finding the related commit. Thanks! It seems that the other parts are already backported. So this is a patch for that backport effort :smile:  About the regression test part, I cannot get the behavior of this,
```
SELECT interval '1' year;
 interval 
----------
 1 year   ---->   it's 365 days in this pr
(1 row)
```
I'm not sure what to go next.

**Comment by hlinnaka** [comment]
On 03/15/2017 02:39 PM, Amos Bird wrote:
> ah, I had a hard time finding the related commit. Thanks!

git blame is a good tool for that.

> It seems that the other parts are already backported. So this is a patch for that backport effort :smile:  About the regression test part, I cannot get the behavior of this,
> ```
> SELECT interval '1' year;
>  interval
> ----------
>  1 year   ---->   it's 365 days in this pr
> (1 row)
> ```
> I'm not sure what to go next.

Not sure, but I suspect some of the other parts are, in fact, not 
completely backported, then.

Oh, and if we backport commit f867339c01, I think we also need to 
backport commit 8487d1f2e1.

- Heikki

**Comment by ascherbaum-pivotal** [comment]
Going to merge this one, once CI is stable again.

@amosbird Any chance you can rebase that patch?

**Comment by hlinnaka** [comment]
I guess the ship has sailed for GPDB 5. Sorry :-(.

In GPDB 6, we will be merging with PostgreSQL 8.4, so we will get this as part of the merge anyway. That renders this separate PR obsolete. Closing.

**Pull request closed without merging**
