### PR TITLE
Reset file (unused by GPDB) to Postgres 8.3.23

### PR DESCRIPTION
**Pull request by cjcjameson**
- Only difference is `#if 0` / `#endif` around the whole file so that
it's clear to developer utilities that these aren't compiled in

Will reduce future merge conflicts significantly. Alternative to #2573

### CODE REVIEW

**Comment by Eulerizeit** [comment]
Aside from the if def do the changes make it the same as the PG version since we don't use it?

**Comment by hsyuan** [comment]
+1 on this.

**Comment by Chibin** [comment]
👍

**Comment by cjcjameson** [comment]
@danielgustafsson ooh, I see. Yea, that's a double-edged sword. Not having it in the makefile will add confusion for the merge-conflict resolver until they realize it's unused, but if we do put it there, it's confusing to the makefile reader/editor until they notice it's unused. Le sigh...

@Eulerizeit yep, as best I could

**Comment by Eulerizeit** [comment]
Awesome thank you.

-- Rob

**Pull request merged**
