### PR TITLE
Allow large Append-only table to have GIN index.

### PR DESCRIPTION
**Pull request by berlin-ab**
Adds a test for regression specified in #7222 and implements the suggested change.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Document changes
- [x] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by hlinnaka** [comment]
You'll also need to fix `decode_varbyte`, now that the encoded integer can be larger. And please explain this whole issue, and why GPDB differs from upstream, in the comments.

**Comment by berlin-ab** [comment]
> You'll also need to fix `decode_varbyte`, now that the encoded integer can be larger. And please explain this whole issue, and why GPDB differs from upstream, in the comments.

Thanks, will do.

**Comment by ivannovick** [comment]
thx for this, we definitely need to "Allow large Append-only table to have GIN index", since users will surely want to compress large text tables before using them for analytics

**Comment by berlin-ab** [comment]
Closed until we've patched `decode_varbyte`.

**Pull request closed without merging**
