### PR TITLE
Fix crash caused by accessing null Datum in class CConstraintInterval

### PR DESCRIPTION
**Pull request by junfx**

### CODE REVIEW

**Comment by chrishajas** [comment]
Thanks for the contribution! Can you add/is there a test case that shows this crash?

**Comment by junfx** [comment]
> 

Reproduce steps:
make create-demo-cluster
make installcheck

**Comment by kainwen** [comment]
> > 
> 
> Reproduce steps: make create-demo-cluster make installcheck

Hi @junfx Thanks a lot for you contribution.

We need to show what is the direct SQL to trigger this bug and also a test case is needed.

Would you please give a mini repro step to show the problem, and comments with brief analysis?

**Comment by junfx** [comment]
I tried but it is not that easy to reproduce. And a specific SQL is far far away from the buggy C statement. Look the `for` loop above, make sure it runs, or check `pprevdatum` before reading it.

**Comment by chrishajas** [comment]
Do you have the query or a core dump from the crash you can share? I've tried reproducing the query, but I can't find the case where we get into this scenario.

**Comment by chrishajas** [comment]
Hi @junfx, Do you have a core, stack trace, or any artifacts you can share from the crash? We haven't been able to reproduce this internally, and do run installcheck regularly and haven't seen this crash. We'd like to be confident that we're fixing the root cause rather than fixing a symptom since we don't expect these values to be null.

**Comment by chrishajas** [comment]
Closing this for now as we don't have enough information to reproduce or narrow down this potential issue. @junfx please re-open if you're able to share more information.

**Pull request closed without merging**
