### PR TITLE
Don't reuse AO block if the corresponding segment file was closed

### PR DESCRIPTION
**Pull request by adam8157**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Pass `make installcheck`

### CODE REVIEW

**Comment by ashwinstar** [comment]
I won't like to make this code change without test-case.

**Comment by hardikar** [comment]
@ashwinstar @d and I were able to find a repro.
I pushed the master version of the repro. You'll need to make tweaks to port it to 5X and 6X. Note that you *cannot* repro it using planner in 5X (and maybe 6X also, we didn't test it) because planner refuses to produce a Bitmap Index NLJ.

**Review by asimrp — COMMENTED** [review]
Would it make sense to use `table_rescan` table AM API here?  I tried  the following patch and it passes the test case:
```diff
--- a/src/backend/access/appendonly/appendonlyam.c                                                                                                                                                                                             
+++ b/src/backend/access/appendonly/appendonlyam.c                                                                                                                                                                                             
@@ -1825,6 +1825,13 @@ appendonly_rescan(TableScanDesc scan, ScanKey key,
                                                                                                                                                                                                                                               
        aoscan->aos_need_new_segfile = true;                                                                                                                                                                                                   
                                                                                                                                                                                                                                               
+       if (aoscan->aofetch && aoscan->aofetch->currentBlock.have)                                                                                                                                                                             
+       {                                                                                                                                                                                                                                      
+               aoscan->aofetch->currentBlock.have = false;                                                                                                                                                                                    
+               aoscan->aofetch->currentBlock.firstRowNum = 0;                                                                                                                                                                                 
+               aoscan->aofetch->currentBlock.lastRowNum = 0;                                                                                                                                                                                  
+       }                                                                                                                                                                                                                                      
+                                                                                                                                                                                                                                              
        /*                                                                                                                                                                                                                                     
         * reinitialize scan descriptor                                                                                                                                                                                                        
         */                                                                                                                                                                                                                                    
```

**Comment by adam8157** [comment]
Thanks to everyone involved, that repro is brilliant.

@asimrp I'd like to keep it similar to the `aocs` codes for now, probably will have another PR to address it, thanks.

**Pull request merged**
