### PR TITLE
remove deadcode according to cppcheck (7X)

### PR DESCRIPTION
**Pull request by hyongtao-db**
This commit removes some dead function in GPDB 7X according to C/CPP code static analysis tool `cppcheck`. We detect these functions are deadcode:
- memtuple_attisnull
- memtuple_copy
- memtuple_deform_misaligned
- memtuple_has_misaligned_attribute
- IsTransactionPreparing
- add_sort_cost
- plan_pushdown_tlist
- resolve_generic_type
- add_repeat_node
- contain_group_id
- reconstruct_group_clause

These functions became useless in postgres 12.12 and were totally removed in subsequent postgres versions.

Signed-off-by: Yongtao Huang <yongtaoh@vmware.com>
Co-author: Xing Guo <guxing@vmware.com>

### CODE REVIEW

**Review by kainwen — APPROVED** [review]

**Comment by higuoxing** [comment]
LGTM!

Seems that there're some other unused methods in `planmain.h`.

```
add_sort_cost
```

**Review by higuoxing — APPROVED** [review]

**Comment by kainwen** [comment]
> LGTM!
> 
> Seems that there're some other unused methods in `planmain.h`.
> 
> ```
> add_repeat_node
> contain_group_id
> reconstruct_group_clause
> add_sort_cost
> ```

Can we have some tools to automatically find the dead code:

* dead functions
* dead struct defs
* dead enum values
* ....

**Comment by hyongtao-db** [comment]
> LGTM!
> 
> Seems that there're some other unused methods in `planmain.h`.
> 
> ```
> add_repeat_node
> contain_group_id
> reconstruct_group_clause
> add_sort_cost
> ```

@higuoxing Thanks Xing Guo. Please let me check it. It would be great if some tools could automatically detect invalid functions hahaha.

**Comment by hyongtao-db** [comment]
I build gpdb by this configure: `./configure --with-perl --with-python --with-libxml --with-gssapi --with-openssl --enable-debug --prefix=/usr/local/gpdb CFLAGS='-Wunused' CXXFLAGS='-Wunused' CPPFLAGS='-Wunused'`. The parameter `-Wunused` help me find one useless parameter. BTW, with these parameters `-Werror -Wall -Wextra -Wpedantic`, I detected several `unused-parameter` of funciton. But I don't think it's a good idea to change these input of function rudely.

**Comment by hyongtao-db** [comment]
@kainwen Hi Zhenghua, I found a fantastic tool to deal with it, its name is `cppcheck`.

-- step one:
```
#!/usr/bin/env bash
set -e

cd /tmp
git clone https://github.com/danmar/cppcheck.git
cd cppcheck 
git checkout 2.7 
make MATCHCOMPILER=yes FILESDIR=/usr/share/cppcheck HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function" install
cd /tmp
rm -rf /tmp/cppcheck
ldconfig
cppcheck --version
```

-- step 2
```
cppcheck --enable=unusedFunction --force ./
```

**Pull request merged**
