### PR TITLE
WIP: enable hot standby mode on standby master

### PR DESCRIPTION
**Pull request by xiong-gang**
Enable hot standby mode on standby master gives standby master the ability to accept read-only queries.
I tried to copy the logical of 'known xids' in upstream to create the distributed snapshot on standby master, but the distributed transactions don't write xlog on abort, and they don't have sub-transactions, it looks simpler to me to just create the snapshot on master and send it to standby master on transaction commit.

### CODE REVIEW

**Comment by pivotal-mike** [comment]
Fails on PR pipeline:
--- /tmp/build/ef6a11cc/gpdb_src/src/test/walrep/expected/replication_views_mirrored.out	2018-09-26 10:37:45.483123961 +0000
+++ /tmp/build/ef6a11cc/gpdb_src/src/test/walrep/results/replication_views_mirrored.out	2018-09-26 10:37:45.483123961 +0000

@@ -20,6 +20,5 @@
              0 | walreceiver      | streaming | sync
              1 | walreceiver      | streaming | sync
              2 | walreceiver      | streaming | sync
-            -1 | walreceiver      | streaming | sync
-(4 rows)
+(3 rows)
```	
              0 | walreceiver      | streaming | sync
	
              1 | walreceiver      | streaming | sync
	
              2 | walreceiver      | streaming | sync
	
-            -1 | walreceiver      | streaming | sync
	
-(4 rows)
	
+(3 rows)
	
 
	

	
======================================================================
	

	

	
Traceback (most recent call last):
	
  File "gpdb_src/concourse/scripts/test_gpdb.py", line 94, in <module>
	
    sys.exit(main())
	
  File "gpdb_src/concourse/scripts/test_gpdb.py", line 89, in main
	
    copy_output()
	
  File "gpdb_src/concourse/scripts/test_gpdb.py", line 39, in copy_output
    shutil.copyfile("gpdb_src/src/test/regress/regression.diffs", "icg_output/regression.diffs")
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'gpdb_src/src/test/regress/regression.diffs'

**Comment by ashwinstar** [comment]
Would like to see features like these discussed on the mailing list first. Makes it easier to discuss the design and timing of things. Definitely opening WIP PRs is good for visibility but discussion on mailing list provides greater visibility and broader discussion, before diving into code technicalities.

So, please can you initiate mail with the details of the design and how its made to work in mpp environment.

I think enabling read-only queries to standby right now is not a good idea. We first need to get the wal replication code for the master to behave same as the segment. Main thing which needs to be modified it, if the connection between master and standby breaks, master continues forward without syncing things to standby. If this happens reading via standby will break things.

Also, how is locking taken care? While read is being performed via standby, if drop table is executed from master what happens.

How does GDD type cases handled when queries are split between master and standby?

**Comment by pivotal-mike** [comment]
Ashwin - can I ask you to repost this to the developers list?  Let’s just kick off the conversation instead of letting lie fallow here.

**Comment by xiong-gang** [comment]
Close this PR. Hot standby is tracking in the mail list. Also, create a separate PR https://github.com/greenplum-db/gpdb/pull/5898 for the 'latestCompletedDxid'.

**Pull request closed without merging**
