### PR TITLE
Orca: reinstate the retrieval of system column statistics

### PR DESCRIPTION
**Pull request by wangpanCN**
fix issue [17249](https://github.com/greenplum-db/gpdb/issues/17249)

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by gpopt** [comment]
Can we just revert the commit https://github.com/greenplum-db/gpdb/pull/14104/commits/475903e32f688ffc333e0a8cf5a46540dc1a56b0?

**Comment by wangpanCN** [comment]
> Can we just revert system column stats part of commit [475903e](https://github.com/greenplum-db/gpdb/commit/475903e32f688ffc333e0a8cf5a46540dc1a56b0)?

Looks good. But which branch contains this commit, I can`t revert it directly.

**Comment by gpopt** [comment]
https://github.com/greenplum-db/gpdb/pull/14104
It looks like we just need to bring back some of the removed code in above PR, not necessarily the revert, because the author squashed the commits.

**Comment by wangpanCN** [comment]
> #14104 It looks like we just need to bring back some of the removed code in above PR, not necessarily the revert, because the author squashed the commits.

I will try to do this. thank you

**Review by gpopt — APPROVED** [review]
+1

**Review by chrishajas — APPROVED** [review]
The change looks good. Can we also add a test case? Probably best as an MDP test, since we're strictly testing the cardinality change. See https://github.com/greenplum-db/gpdb/tree/main/src/backend/gporca#adding-tests for adding an mdp test

**Comment by chrishajas** [comment]
@wangpanCN I've added a test and fixed the ICW failures, along with a minor code fixup that was failing when this was rebased: https://github.com/chrishajas/gpdb/commit/9f865efac77648504cea50e3a4c84d3bd4b23e08 Feel free to cherry pick this commit to your PR and we can get this in.

**Comment by wangpanCN** [comment]
> @wangpanCN I've added a test and fixed the ICW failures, along with a minor code fixup that was failing when this was rebased: [chrishajas@9f865ef](https://github.com/chrishajas/gpdb/commit/9f865efac77648504cea50e3a4c84d3bd4b23e08) Feel free to cherry pick this commit to your PR and we can get this in.

ok

**Comment by chrishajas** [comment]
Last couple of things:
1) Can you ensure it passes the formatting (`src/tools/fmt fmt`)
```
--- a/src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
+++ b/src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
@@ -2139,8 +2139,8 @@ CTranslatorRelcacheToDXL::GenerateStatsForSystemCols(
                        {
                                is_col_stats_missing = false;
                                freq_remaining = CDouble(1.0);
-                               distinct_remaining =
-                                       CDouble(md_rel->IsPartitioned() ? md_rel->PartColumnCount() : 1);
+                               distinct_remaining = CDouble(
+                                       md_rel->IsPartitioned() ? md_rel->PartColumnCount() : 1);
                                break;
                        }
                        case SelfItemPointerAttributeNumber:  // ctid
diff --git a/src/include/gpopt/translate/CTranslatorRelcacheToDXL.h b/src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
index 42c3690f2e6..b060f4de44e 100644
--- a/src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
+++ b/src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
@@ -273,9 +273,10 @@ private:

        // generate statistics for the system level columns
        static CDXLColStats *GenerateStatsForSystemCols(
-               CMemoryPool *mp, const IMDRelation *md_rel, CMDIdColStats *mdid_col_stats,
-               CMDName *md_colname, IMDId *mdid_atttype, AttrNumber attrnum,
-               CDXLBucketArray *dxl_stats_bucket_array, CDouble rows);
+               CMemoryPool *mp, const IMDRelation *md_rel,
+               CMDIdColStats *mdid_col_stats, CMDName *md_colname, IMDId *mdid_atttype,
+               AttrNumber attrnum, CDXLBucketArray *dxl_stats_bucket_array,
+               CDouble rows);

        static IMdIdArray *RetrieveIndexPartitions(CMemoryPool *mp, OID rel_oid);

(END)
```

2) In the mdp that you added, can you include the setup and objective as a comment, similar to other mdps:
```
+  <dxl:Comment><![CDATA[
+       Objective: Orca should use more accurate statistics for gp_segment_id column rather than dummy statistics (40%)
+
+       create table foo;
+       insert into foo select 1 from generate_series(1,1000)i;
+       analyze foo
+
+       test2=# explain select * from foo where gp_segment_id=1;
+                                   QUERY PLAN
+       --------------------------------------------------------------------------------
+        Gather Motion 1:1  (slice1; segments: 1)  (cost=0.00..431.02 rows=334 width=4)
+          ->  Seq Scan on foo  (cost=0.00..431.02 rows=112 width=4)
+                Filter: (gp_segment_id = 1)
+        Optimizer: GPORCA
+       (4 rows)
+  ]]>
+  </dxl:Comment>
```

3) I'm seeing 2 more diffs in the tid icw output file that need to be updated:
```
--- a/src/test/regress/expected/tidscan_optimizer.out
+++ b/src/test/regress/expected/tidscan_optimizer.out
@@ -145,21 +145,18 @@ SET enable_hashjoin TO off;  -- otherwise hash join might win
 EXPLAIN (COSTS OFF)
 SELECT t1.ctid, t1.*, t2.ctid, t2.*
 FROM tidscan t1 JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
-                            QUERY PLAN
-------------------------------------------------------------------
+                          QUERY PLAN
+---------------------------------------------------------------
  Gather Motion 3:1  (slice1; segments: 3)
    ->  Hash Join
-         Hash Cond: (tidscan.ctid = tidscan_1.ctid)
-         ->  Redistribute Motion 3:3  (slice2; segments: 3)
-               Hash Key: tidscan.ctid
-               ->  Seq Scan on tidscan
-                     Filter: (id = 1)
+         Hash Cond: (t2.ctid = t1.ctid)
+         ->  Seq Scan on tidscan t2
          ->  Hash
-               ->  Redistribute Motion 3:3  (slice3; segments: 3)
-                     Hash Key: tidscan_1.ctid
-                     ->  Seq Scan on tidscan tidscan_1
+               ->  Broadcast Motion 3:3  (slice2; segments: 3)
+                     ->  Seq Scan on tidscan t1
+                           Filter: (id = 1)
  Optimizer: GPORCA
-(12 rows)
+(9 rows)

 SELECT t1.ctid, t1.*, t2.ctid, t2.*
 FROM tidscan t1 JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
@@ -171,21 +168,18 @@ FROM tidscan t1 JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
 EXPLAIN (COSTS OFF)
 SELECT t1.ctid, t1.*, t2.ctid, t2.*
 FROM tidscan t1 LEFT JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
-                            QUERY PLAN
-------------------------------------------------------------------
- Gather Motion 3:1  (slice1; segments: 3)
-   ->  Hash Left Join
-         Hash Cond: (tidscan.ctid = tidscan_1.ctid)
-         ->  Redistribute Motion 3:3  (slice2; segments: 3)
-               Hash Key: tidscan.ctid
-               ->  Seq Scan on tidscan
+                      QUERY PLAN
+------------------------------------------------------
+ Hash Right Join
+   Hash Cond: (t2.ctid = t1.ctid)
+   ->  Gather Motion 3:1  (slice1; segments: 3)
+         ->  Seq Scan on tidscan t2
+   ->  Hash
+         ->  Gather Motion 3:1  (slice2; segments: 3)
+               ->  Seq Scan on tidscan t1
                      Filter: (id = 1)
-         ->  Hash
-               ->  Redistribute Motion 3:3  (slice3; segments: 3)
-                     Hash Key: tidscan_1.ctid
-                     ->  Seq Scan on tidscan tidscan_1
  Optimizer: GPORCA
-(12 rows)
+(9 rows)

 SELECT t1.ctid, t1.*, t2.ctid, t2.*
 FROM tidscan t1 LEFT JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
 ```

**Comment by wangpanCN** [comment]
> Last couple of things:
> 
> 1. Can you ensure it passes the formatting (`src/tools/fmt fmt`)
> 
> ```
> --- a/src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
> +++ b/src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
> @@ -2139,8 +2139,8 @@ CTranslatorRelcacheToDXL::GenerateStatsForSystemCols(
>                         {
>                                 is_col_stats_missing = false;
>                                 freq_remaining = CDouble(1.0);
> -                               distinct_remaining =
> -                                       CDouble(md_rel->IsPartitioned() ? md_rel->PartColumnCount() : 1);
> +                               distinct_remaining = CDouble(
> +                                       md_rel->IsPartitioned() ? md_rel->PartColumnCount() : 1);
>                                 break;
>                         }
>                         case SelfItemPointerAttributeNumber:  // ctid
> diff --git a/src/include/gpopt/translate/CTranslatorRelcacheToDXL.h b/src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
> index 42c3690f2e6..b060f4de44e 100644
> --- a/src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
> +++ b/src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
> @@ -273,9 +273,10 @@ private:
> 
>         // generate statistics for the system level columns
>         static CDXLColStats *GenerateStatsForSystemCols(
> -               CMemoryPool *mp, const IMDRelation *md_rel, CMDIdColStats *mdid_col_stats,
> -               CMDName *md_colname, IMDId *mdid_atttype, AttrNumber attrnum,
> -               CDXLBucketArray *dxl_stats_bucket_array, CDouble rows);
> +               CMemoryPool *mp, const IMDRelation *md_rel,
> +               CMDIdColStats *mdid_col_stats, CMDName *md_colname, IMDId *mdid_atttype,
> +               AttrNumber attrnum, CDXLBucketArray *dxl_stats_bucket_array,
> +               CDouble rows);
> 
>         static IMdIdArray *RetrieveIndexPartitions(CMemoryPool *mp, OID rel_oid);
> 
> (END)
> ```
> 
> 2. In the mdp that you added, can you include the setup and objective as a comment, similar to other mdps:
> 
> ```
> +  <dxl:Comment><![CDATA[
> +       Objective: Orca should use more accurate statistics for gp_segment_id column rather than dummy statistics (40%)
> +
> +       create table foo;
> +       insert into foo select 1 from generate_series(1,1000)i;
> +       analyze foo
> +
> +       test2=# explain select * from foo where gp_segment_id=1;
> +                                   QUERY PLAN
> +       --------------------------------------------------------------------------------
> +        Gather Motion 1:1  (slice1; segments: 1)  (cost=0.00..431.02 rows=334 width=4)
> +          ->  Seq Scan on foo  (cost=0.00..431.02 rows=112 width=4)
> +                Filter: (gp_segment_id = 1)
> +        Optimizer: GPORCA
> +       (4 rows)
> +  ]]>
> +  </dxl:Comment>
> ```
> 
> 3. I'm seeing 2 more diffs in the tid icw output file that need to be updated:
> 
> ```
> --- a/src/test/regress/expected/tidscan_optimizer.out
> +++ b/src/test/regress/expected/tidscan_optimizer.out
> @@ -145,21 +145,18 @@ SET enable_hashjoin TO off;  -- otherwise hash join might win
>  EXPLAIN (COSTS OFF)
>  SELECT t1.ctid, t1.*, t2.ctid, t2.*
>  FROM tidscan t1 JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
> -                            QUERY PLAN
> -------------------------------------------------------------------
> +                          QUERY PLAN
> +---------------------------------------------------------------
>   Gather Motion 3:1  (slice1; segments: 3)
>     ->  Hash Join
> -         Hash Cond: (tidscan.ctid = tidscan_1.ctid)
> -         ->  Redistribute Motion 3:3  (slice2; segments: 3)
> -               Hash Key: tidscan.ctid
> -               ->  Seq Scan on tidscan
> -                     Filter: (id = 1)
> +         Hash Cond: (t2.ctid = t1.ctid)
> +         ->  Seq Scan on tidscan t2
>           ->  Hash
> -               ->  Redistribute Motion 3:3  (slice3; segments: 3)
> -                     Hash Key: tidscan_1.ctid
> -                     ->  Seq Scan on tidscan tidscan_1
> +               ->  Broadcast Motion 3:3  (slice2; segments: 3)
> +                     ->  Seq Scan on tidscan t1
> +                           Filter: (id = 1)
>   Optimizer: GPORCA
> -(12 rows)
> +(9 rows)
> 
>  SELECT t1.ctid, t1.*, t2.ctid, t2.*
>  FROM tidscan t1 JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
> @@ -171,21 +168,18 @@ FROM tidscan t1 JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
>  EXPLAIN (COSTS OFF)
>  SELECT t1.ctid, t1.*, t2.ctid, t2.*
>  FROM tidscan t1 LEFT JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
> -                            QUERY PLAN
> -------------------------------------------------------------------
> - Gather Motion 3:1  (slice1; segments: 3)
> -   ->  Hash Left Join
> -         Hash Cond: (tidscan.ctid = tidscan_1.ctid)
> -         ->  Redistribute Motion 3:3  (slice2; segments: 3)
> -               Hash Key: tidscan.ctid
> -               ->  Seq Scan on tidscan
> +                      QUERY PLAN
> +------------------------------------------------------
> + Hash Right Join
> +   Hash Cond: (t2.ctid = t1.ctid)
> +   ->  Gather Motion 3:1  (slice1; segments: 3)
> +         ->  Seq Scan on tidscan t2
> +   ->  Hash
> +         ->  Gather Motion 3:1  (slice2; segments: 3)
> +               ->  Seq Scan on tidscan t1
>                       Filter: (id = 1)
> -         ->  Hash
> -               ->  Redistribute Motion 3:3  (slice3; segments: 3)
> -                     Hash Key: tidscan_1.ctid
> -                     ->  Seq Scan on tidscan tidscan_1
>   Optimizer: GPORCA
> -(12 rows)
> +(9 rows)
> 
>  SELECT t1.ctid, t1.*, t2.ctid, t2.*
>  FROM tidscan t1 LEFT JOIN tidscan t2 ON t1.ctid = t2.ctid WHERE t1.id = 1;
> ```

done, thank you

**Comment by chrishajas** [comment]
Merged, thanks for your contribution!

**Pull request merged**
