### PR TITLE
Remove gpMgmt/bin/ext/Crypto dir

### PR DESCRIPTION
**Pull request by professor**
Authored-by: Todd Sedano <tsedano@pivotal.io>

### CODE REVIEW

**Comment by professor** [comment]
@danielgustafsson 

Are you referring to 
```
	if [ -e bin/ext/Crypto ]; then \
	    cp -rp bin/ext/Crypto $(DESTDIR)$(prefix)/lib/python ; \
	fi
```

That code should still work. When we install pycrypto, it ends up in the correct location. 

(In a separate PR, I'm attempting to use pip to install it and pip needs the destination directory not to exist for pycrypto.)

**Comment by Eulerizeit** [comment]
PIP requires Internet access which not customer clusters don't have.

Rob

**Comment by professor** [comment]
I think we're off topic. Pip can install local files, no internet is needed. We can leverage existing python tools instead of reinventing the wheel in makefiles.

**Comment by danielgustafsson** [comment]
> On 5 Jul 2018, at 18:49, Todd Sedano <notifications@github.com> wrote:
> 
> @danielgustafsson
> 
> Are you referring to
> 
> 	if [ -e bin/ext/Crypto ]; then \
> 	    cp -rp bin/ext/Crypto $(DESTDIR)$(prefix)/lib/python ; \
> 	fi
> 
> That code should still work. When we install pycrypto, it ends up in the correct location.

I don’t follow, why would we want a Makefile rule for copying a directory if it
exists, when we know we’ve deleted it?  If the user installs pycrypto on her
own then thats outside the scope for this Makefile?

**Pull request closed without merging**
