### PR TITLE
Reverting removal of Orca permission check introduced during 8.3. merge #121649891

### PR DESCRIPTION
**Pull request by vraghavan78**
In https://github.com/greenplum-db/gpdb/commit/1a8bd2e6ee66872dabdd1612c1afbdd0bd93c1b1
these functions were moved from parse_relation.c to execMain.c to mirror what is in Postgres. In doing so, the Orca permission was disabled. 

The reason for the Orca permission (which was removed during the 4.3 merge) was to address the following problem. When the legacy optimizer (planner) is used, the parsed query contains an RTE for the view, which is maintained all the way through planned statement. This entries is annotated as requiring SELECT permissions for the current user:

`{RTE :alias {ALIAS :aliasname *OLD* :colnames <>} :eref {ALIAS :aliasname *OLD* :colnames (\"a\" \"b\")} :rtekind 0 :relid 192628 :inh false :inFromCl false :requiredPerms 2 :checkAsUser 0 :forceDistRandom false :pseudocols <>}
`

In Orca, by design we only keep range table entries for the base tables in the planned statement, but not for the view itself. Since permissions are only checked during ExecutorStart, we lose track of the permissions required for the view and the select goes through successfully. We therefore need to check permissions before we go into optimization for all RTEs, including the ones not explicitly referred in the query, e.g. views.

Removal of the Orca permission check causes wrong result with Orca. Therefore I am reverting this part of the refactoring done during Postgres 8.3 merge.

@hlinnaka @danielgustafsson @d @oarap @hsyuan please take a look. I added a note to explain the underlying reasoning as well as added a test.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Thank you very much for the thorough explanation (here and in the code comment), I was following the code and tried to figure out why the permission check was required there but failed; now it makes sense.

Moving the functions back will inevitably create conflicts with upstream merges, leaving the code `#if 0`'ed out however runs the risk of merges being applied cleanly and the changes don't get brought over to `parse_relation.c` which is worse. I think the least bad option is to leave the function comment in place in `execMain.c` and suffix it with `GPDB: This function has been moved to parse_relation.c` such that any conflicts have a chance to hit roughly in the right place in `execMain.c` and the reason for the conflict is visible.

**Comment by hlinnaka** [comment]
On 21/06/16 10:02, Daniel Gustafsson wrote:
> Thank you very much for the thorough explanation (here and in the
> code comment), I was following the code and tried to figure out why
> the permission check was required there but failed; now it makes
> sense.

Yep.

It makes me a quite nervous. Doing things like permission checks 
differently than Postgres does seems like a recipe for subtle bugs. Can 
we change the ORCA translator library to keep the RTE entries around, 
like the Postgres planner does?

At first I thought we would have a problem if you do "PREPARE SELECT * 
FROM view" and "EXECUTE" in one session, and you revoke the permission 
to the view in another session between the PREPARE and EXECUTE. But it 
seems that plan cache invalidation saves the bacon in that case: 
revoking the permission triggers re-planning. Seems quite accidental, 
rather than by-design though.

But there are other cases where that's certainly wrong. See attached 
script, for example, which uses a prepared statement and SET ROLE. 
That's perhaps not the end of the world, but I think we should 
nevertheless fix it. It shouldn't be too hard to just refrain from 
removing the RTEs, for permission checking purposes.

> Moving the functions back will inevitably create conflicts with
> upstream merges, leaving the code `#if 0`'ed out however runs the
> risk of merges being applied cleanly and the changes don't get
> brought over to `parse_relation.c` which is worse. I think the least
> bad option is to leave the function comment in place in `execMain.c`
> and suffix it with `GPDB: This function has been moved to
> parse_relation.c` such that any conflicts have a chance to hit
> roughly in the right place in `execMain.c` and the reason for the
> conflict is visible.

Even if we need to still call ExecCheckRTPerms() from ORCA, I don't see 
any reason for moving it to a different file.

- Heikki

**Comment by danielgustafsson** [comment]
> On 21 Jun 2016, at 10:25, Heikki Linnakangas <notifications@github.com> wrote:
> 
> Even if we need to still call ExecCheckRTPerms() from ORCA, I don't see 
> any reason for moving it to a different file.

Well, that is a good point. I need more :coffee:.

**Comment by vraghavan78** [comment]
@hlinnaka I moved the functions back to execMain and made it non-static. W.r.t to the re-write of the how orca handles permission we can address that in another PR.

**Comment by danielgustafsson** [comment]
:+1:

**Pull request closed without merging**
