### PR TITLE
Optimize the cost model of multi-stage AGG

### PR DESCRIPTION
**Pull request by baobao0206**
There are some problems on the old multi-stage agg cost model:
1. We use global group number and global workmemmory to estimate
the number of spilled tuple. But the situation between the first
stage agg and the second stage agg is completely different.
Tuples are randomly distributed on the group key on first stage
agg. The number of groups on each segment is almost equal to the
number of global groups. But in second stage agg, Distribution key
is a subset of group key, so the number of groups on each segment
is equal to (number of global groups / segment number). So the lld
code can cause huge cost deviation.
2. Using ((group number + input rows) / 2) as spilled tupule is
3. Using global group number * 1.3 as the output rows of streaming
agg node is very wrong. The out put row of streaming agg node
should be group number * segment number * param.
too rough.
4. We use numGroups to estimate the initial size of the hash table
in exec node. But numGroups is global group number.

So we made the following changes:
1. Use a funtion 'groupNumberPerSegemnt' to estimate the group
number per segment on first stage agg. Use numGroups/segment number
as the group number per segment on second stage agg.
2. Use funtion 'spilledGroupNumber' to estimate spilled tuple number.
3. Use spilled tuple number * segment number as output tuple number
of streaming agg node.
4. Use numGroups as group number per segment.

Also, we have information on the number of tuples in top N groups. So we
can predict the maximum number of tuples in the biggest segment
when the skew occurs. When we can predict skew, enable the 1 phase agg.

Co-authored-by: Zhenghua Lyu <kainwen@gmail.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by baobao0206** [comment]
Back port from master 9936ca3bf141bed7f2677868d7cc85df9e06cf80

**Comment by ashwinstar** [comment]
Do we have TPC-DS run with this to know if causes regression for any query?

**Comment by baobao0206** [comment]
> Do we have TPC-DS run with this to know if causes regression for any query?

Let me ask @kainwen how to build a TPCDS cluster.

**Comment by baobao0206** [comment]
For this pr has been contained by https://github.com/greenplum-db/gpdb/pull/12351. Close it

**Pull request closed without merging**
