### PR TITLE
qp_derived_table fixes and cleanups

### PR DESCRIPTION
**Pull request by danielgustafsson**
This PR is the result of a small investigation into the `qp_derived_table` test to see if it could be made faster by simple tweaks. Turns out it kind-of-sort-of couldn't. See the post to the [gpdb-dev mailinglist](https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/fJOMBUn3CRU)  for the full explanation. As such, it contains two ~~three~~ parts which if this is to be merged should be squashed into a single commit, but to make it easier to look at I've kept them separated here:
 
1. Explicitly set the table distribution on the participating tables in the `qp_derived_table` test suite instead of relying on the default policy. All distributions set to match the default so no change in the test is induced, only output.

2. ~~The `qp_derived_table` test suite has quite a lot of large queries which with the ECHO 'queries' setting will generate a lot of work for the result differ which is quite pointless, we already know
what the query is from the SQL file. Set ECHO to 'none' and set back at the end of the test to cope with the ignoring of tables dropped.~~

3. Turns out that 47 of the 1000 queries got broken in the migration into ICG in subquery referencing. All the syntax errors are of the same kind: `SELECT ((SELECT 1) AS foo) AS bar;` The aliasing to foo is a syntax error. Queries fixed and the expected result updated with the actual query results.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Updated (and force pushed) to match the discussion on the mailinglist by reinstating the query output. Ping @hlinnaka

**Comment by hlinnaka** [comment]
LGTM now. I'd suggest not squashing the commits, I think it's clearer to have them separately, as in this PR.

**Comment by vraghavan78** [comment]
LGTM thanks @danielgustafsson

**Comment by danielgustafsson** [comment]
Pushed (as two separate commits) to master, thanks for review!

**Pull request closed without merging**
