### PR TITLE
Provide preliminary Travis CI support (#58).

### PR DESCRIPTION
**Pull request by edespino**

### CODE REVIEW

**Comment by hlinnaka** [comment]
I know nothing about travis-ca, so I don't feel qualified to comment on the contents of the file.

But it surely shouldn't do any harm, so no objections :-)

**Comment by danielgustafsson** [comment]
Based on my limited travis exposure, :+1:

**Comment by edespino** [comment]
Thanks ... it's coming in to master.

-=e

**Comment by edespino** [comment]
Pushed to master.

**Pull request closed without merging**
