### PR TITLE
DEFAULT paramters of UDF ported from PostgreSQL.

### PR DESCRIPTION
**Pull request by kuien**
Functions can be declared with parameters with default values or
expressions.  The default expressions are used as parameter value
if the parameter is not explicitly specified in a function call.
All parameters after a parameter with default value have to be
parameters with default values as well.

It allows user to invoke a UDF without setting all the parameters.
Two examples to demo its usage:

  CREATE FUNCTION dfunc1(text DEFAULT 'Hello', text DEFAULT 'World')
    RETURNS text AS $$
    SELECT $1 || ', ' || $2;
    $$ LANGUAGE SQL;
  SELECT dfunc1();  -- 'Hello, World'
  SELECT dfunc1('Hi');  -- 'Hi, World'
  SELECT dfunc1('Hi', 'Beijing');  -- 'Hi, Beijing'

  CREATE FUNCTION dfunc2(id int4, t timestamp DEFAULT now())
    RETURNS text AS $$
    SELECT 'Time for id:' || $1 || ' is ' || $2;
    $$ LANGUAGE SQL;
  SELECT dfunc2(24);  -- 'Time for id:24 is 2016-01-07 14:38'

NOTE: The default change set is ported from upstream, see original
commits below.

  commit 517ae4039ebe12806d76adfd3bc1fc6578fc8862
  Author: Tom Lane <tgl@sss.pgh.pa.us>
  Date:   Thu Dec 18 18:20:35 2008 +0000

  commit 455dffbb73f9875c39f2ab544420454168a8c68c
  Author: Peter Eisentraut <peter_e@gmx.net>
  Date:   Thu Dec 4 17:51:28 2008 +0000

### CODE REVIEW

**Comment by kuien** [comment]
@hlinnaka I am glad that you response quickly, :)

1. Do you mean the original commits I cited are not correct? I tried to retrieve the original ones and found these two.

  commit 517ae4039ebe12806d76adfd3bc1fc6578fc8862
  Author: Tom Lane tgl@sss.pgh.pa.us
  Date: Thu Dec 18 18:20:35 2008 +0000

  commit 455dffbb73f9875c39f2ab544420454168a8c68c
  Author: Peter Eisentraut peter_e@gmx.net
  Date: Thu Dec 4 17:51:28 2008 +0000

2. It is GREEN on my branch on pulse-releng server:
  http://pulse-releng.greenplum.com/browse/projects/GPDB-master-opt-l1_kuien/builds/66651/

My branch is rebased to the GPDB/master two days ago, may be not that fresh... I'll trigger it again.

**Comment by hlinnaka** [comment]
@kuien, can you have a look at pull request #208, please? It conflicts with this. I looked at FuncNameGetCandidates after applying this patch (#247), and it looks quite different from upstream version. Was there a reason for that? If not, I suggest that we push #208 first, and then rebase this patch over that. After #208, this patch only needs to touch FuncNameGetCandidates very lightly, to re-enable the stuff related to default parameters that I had to disable in #208.

In general, please pay attention to "git diff pgsql/REL8_4_STABLE" (or the commit, for those files and functions that you've backported. Make sure there are no unnecessary whitespace or comment differences. They will create merge conflicts in the future. Trivial ones, but better to get it right from the get-go.

**Comment by kuien** [comment]
@entong could you please have a look on Heikki's comment in file [src/backend/gpopt/gpdbwrappers.cpp ](https://github.com/kuien/gpdb/commit/9cec852e8bdd9e5c986ed1bd58cead24610ca1a4#commitcomment-15311437) ? What do you think from ORCA side?

**Comment by kuien** [comment]
@hlinnaka Yes, on this function, we opt the codes from PG 90600. I find it is much cleaner than #208, and I further find an issue in it (line 929: pfree(newResult);) on my vmware. 

I think you can merge firstly, then I adapt the patch to your version.

**Comment by hlinnaka** [comment]
On 07/01/16 12:54, Kuien Liu wrote:
> @hlinnaka Yes, on this function, we opt the codes from PG 90600. I find it is much cleaner than #208, and I further find an issue in it (line 929: pfree(newResult);) on my vmware.
>
> I think you can merge firstly, then I adapt the patch to your version.

Sorry, I'm confused. Did you mean that find the code cleaner *with* 
#208, or that you find the code cleaner *without* #208, i.e. as it is in 
#247.

Oh, you were able to reproduce a segfault or something, caused by the 
pfree-bug? Might be interesting to add a regression test for that.

I think we're in agreement on the plan, though:

1. I'll push #208.
2. You'll rebase #247 over that.

- Heikki

**Comment by kuien** [comment]
1. Sorry, I cite the wrong No., I mean I rebase to the gpdb/master, I found the codes of FuncnameGetCandidates () looks strange and has a bug (in #178). So I update it following pg9.6, :)

2. Yes, push #208 please, I'll rebase #247 after that. I browse through your patch, it's fixed already.

**Comment by hlinnaka** [comment]
Ok, great. I've pushed #208 now.

**Comment by ascherbaum-pivotal** [comment]
@danielgustafsson Is this something you are working on in the 8.3 Merge cycle? Or can - once merged - this be marked as done?

**Comment by hlinnaka** [comment]
On 08/01/16 02:24, Andreas Scherbaum wrote:
> @danielgustafsson Is this something you are working on in the 8.3 Merge cycle?

No, this is backported from 8.4. There are no changes to this area in 8.3.

> Or can - once merged - this be marked as done?

Yep.

- Heikki

**Comment by kuien** [comment]
I'll close this PR and re-submit one again, because I make some changes after rebase to latest master (with #208 and other commits) and push the source-codes incorrectly (with --force), :(

**Pull request closed without merging**
