### PR TITLE
gpAux/Makefile cleaning

### PR DESCRIPTION
**Pull request by danielgustafsson**
Just a few small cleanups in `gpAux/Makefile` to get us started, but there is loads still left to do.

### CODE REVIEW

**Comment by amilkh** [comment]
"Remove compiler versioncheck from gpAux" => will it be added to autoconf?

**Comment by bradfordboyle** [comment]
> "Remove compiler versioncheck from gpAux" => will it be added to autoconf?

I'm not sure if it needs to be. It was checking for version 3 of GCC which is 13 years old at this point.

**Comment by danielgustafsson** [comment]
> "Remove compiler versioncheck from gpAux" => will it be added to autoconf?

`config/c-compiler.m4` already checks for the C compiler being sufficient, if we need more checks then we'll add them there. In this case there is little to add, as the checks we have cover what we need.

**Comment by amilkh** [comment]
Thanks! please go ahead and merge if you feel confident

**Comment by danielgustafsson** [comment]
Pushed to master minus the patch for making gpAux/platform recursive as I instead opted for the solution in #8190 which removes gpAux/platform altogether. Thanks for review!

**Pull request closed without merging**
