### PR TITLE
Remove old bugbuster metadata_track suite

### PR DESCRIPTION
**Pull request by danielgustafsson**
The metadata_track suite was originally part of cdbfast, dating back around 10-11 years. It was later moved into bugbuster around six years ago, already then with doubts as to what it actually did. After the open sourcing we scrapped bugbuster, moving anything worthwhile (or just not analyzed for usefulness) into the normal regress schedule. This all according to the old proprietary issue tracker.

Looking at metadata_track, it's entirely duplicative only issuing lots of DDL already tested elsewhere without verifying the results, most likely since it was originally testing the metadata tracking of the operations. Since the latter part is no longer happening, remove metadata_track as the remaining value of this quite slow test (spending ~10-12 minutes serially in the pipeline) is highly debatable.

Does anyone see any remaining value in this suite? Looking over the code it runs I can't spot anything we aren't already testing elsewhere.

### CODE REVIEW

**Comment by jimmyyih** [comment]
That's interesting.  Metadata tracking is definitely still a thing.  It's tracked under `pg_stat_last_operation` catalog table.  There should be select queries against it in the test which seem to be missing.

**Comment by Eulerizeit** [comment]
On Mon, Apr 1, 2019 at 4:46 PM Jimmy Yih <notifications@github.com> wrote:

> That's interesting. Metadata tracking is definitely still a thing. It's
> tracked under pg_stat_last_operation catalog table. There should be
> select queries against it in the test which seem to be missing.
>

Is pg_stat_last_operation a Greenplum table with a Postgres name?

-- Rob

**Comment by jimmyyih** [comment]
@Eulerizeit Yes, `pg_stat_last_operation` is a Greenplum-specific table with a pg prefix.

**Comment by danielgustafsson** [comment]
There is a `pg_stat_last_operation` test is separate from this suite.

**Comment by danielgustafsson** [comment]
Also worth noting, when this file was first imported from cdbfast, any pg_stat_last_operation tests were already gone.

**Comment by jimmyyih** [comment]
Looking at the `pg_stat_last_operation` regress test, it's very underwhelming.  It seems like `metadata_track.sql` needs to be merged into `pg_stat_last_operation.sql` (while removing unnecessary stuff from `metadata_track.sql`).

**Comment by danielgustafsson** [comment]
> Looking at the `pg_stat_last_operation` regress test, it's very underwhelming. It seems like `metadata_track.sql` needs to be merged into `pg_stat_last_operation.sql` (while removing unnecessary stuff from `metadata_track.sql`).

I'm not sure we need to merge, but we do need to expand `pg_stat_last_operation.sql` a bit since it's currently not really doing anything at all, and contrary to the name it's not even testing `pg_stat_last_operation`. I guess I'll go do that since I touched the 💩

**Comment by danielgustafsson** [comment]
Ok, after reviewing what we had and what metadata_track did, I added a select few of the cases into pg_stat_last_operation to make it a bit more relevant. @jimmyyih what do you reckon about this version?

**Comment by danielgustafsson** [comment]
The `pg_stat_last_operation` test as in this patch runs in 1.78 seconds in a parallell group (up from 0.4 seconds) which is dominated by an 11 second test, the removed  `metadata_track` ran in 11.78 seconds in a single group.

**Comment by danielgustafsson** [comment]
I agree that there are improvements to be had, but I think that should revisit the pg_stat_last_shoperation tests too and I am a bit short on time to commit to that right now. Pushed to master to at least improve on the status quo, thanks for review!

**Pull request closed without merging**
