### PR TITLE
Add 2 catalog tables for resource group

### PR DESCRIPTION
**Pull request by xiong-gang**
Signed-off-by: Kenan Yao <kyao@pivotal.io>

### CODE REVIEW

**Comment by hlinnaka** [comment]
Why? This is just dead code, right?

**Comment by d** [comment]
Maybe it would be helpful to provide a bit more context on this PR to help reviewers get the bigger picture I suppose this patch is a part of? @eurekaka @xiong-gang

**Comment by schubert** [comment]
@hlinnaka @d so the idea here I believe is that we want to tackle RQ in 5.x but if we don't get the catalog changes in now we won't be able to address until 6.x.

We know it's "dead code" per-se but it's one of these situations where the upside in getting this in before a catalog freeze outweighs the downside of having to make everyone wait for 6.x for a better resource queue.

This does seem similar to situations like in PG where the basic foundational pieces are put in 1 version (like FDW in 8.4) but doesn't really get going until subsequent versions. 

It's not ideal but again, I think it's one of those cases where the pro's outweigh the cons. The only risk here is if we find out later that the design necessitates a different catalog change then this will indeed just be dead code and we remove. But that seems like a reasonable risk here.

@eurekaka @xiong-gang I assume you all have taken into account the feedback from the mailing list on RQ into this.

**Comment by yydzero** [comment]
@xiong-gang would be good to provide more context in commit messages and PR description, so that reviews understand the context.

**Comment by xiong-gang** [comment]
Thanks @schubert for the explanation.

Here's the what the catalog tables looks like.

```
test=# \d pg_resgroup
Table "pg_catalog.pg_resgroup"
 Column  | Type | Modifiers
---------+------+-----------
 rsgname | name | not null
 parent  | oid  | not null
Indexes:
    "pg_resgroup_rsgname_index" UNIQUE, btree (rsgname), tablespace "pg_global"

Tablespace: "pg_global"

test=# \d pg_resgroupcapability
Table "pg_catalog.pg_resgroupcapability"
    Column    |   Type   | Modifiers
--------------+----------+-----------
 resgroupid   | oid      | not null
 reslimittype | smallint | not null
 value        | text     |
Indexes:
    "pg_resgroupcapability_resgroupid_reslimittype_index" UNIQUE, btree (resgroupid, reslimittype), tablespace "pg_global"
    "pg_resgroupcapability_resgroupid_index" btree (resgroupid), tablespace "pg_global"

Tablespace: "pg_global"

test=# \d pg_authid
               Table "pg_catalog.pg_authid"
      Column       |           Type           | Modifiers
-------------------+--------------------------+-----------
 rolname           | name                     | not null
 rolsuper          | boolean                  | not null
 rolinherit        | boolean                  | not null
 rolcreaterole     | boolean                  | not null
 rolcreatedb       | boolean                  | not null
 rolcatupdate      | boolean                  | not null
 rolcanlogin       | boolean                  | not null
 rolconnlimit      | integer                  | not null
 rolpassword       | text                     |
 rolvaliduntil     | timestamp with time zone |
 rolconfig         | text[]                   |
 rolresqueue       | oid                      |
 rolcreaterextgpfd | boolean                  |
 rolcreaterexthttp | boolean                  |
 rolcreatewextgpfd | boolean                  |
 rolcreaterexthdfs | boolean                  |
 rolcreatewexthdfs | boolean                  |
 rolresgroup       | oid                      |
Indexes:
    "pg_authid_oid_index" UNIQUE, btree (oid), tablespace "pg_global"
    "pg_authid_rolname_index" UNIQUE, btree (rolname), tablespace "pg_global"
    "pg_authid_rolresgroup_index" btree (rolresgroup), tablespace "pg_global"
    "pg_authid_rolresqueue_index" btree (rolresqueue), tablespace "pg_global"
Triggers:
    pg_sync_pg_authid AFTER INSERT OR DELETE OR UPDATE ON pg_authid FOR EACH STATEMENT EXECUTE PROCEDURE flatfile_update_trigger()

Tablespace: "pg_global"

test=# select * from pg_resgroup
test-# ;
    rsgname    | parent
---------------+--------
 default_group |      0
 admin_group   |      0
(2 rows)

test=# select * from pg_resgroup
pg_resgroup            pg_resgroupcapability
test=# select * from pg_resgroupcapability ;
 resgroupid | reslimittype | value
------------+--------------+-------
       6437 |            1 | 20
       6437 |            2 | 0.3
       6437 |            3 | 0.3
       6438 |            1 | -1
       6438 |            2 | 0.1
       6438 |            3 | 0.1
(6 rows)

test=# select * from pg_resgroup, pg_resgroupcapability where pg_resgroup.oid=pg_resgroupcapability.resgroupid;
    rsgname    | parent | resgroupid | reslimittype | value
---------------+--------+------------+--------------+-------
 default_group |      0 |       6437 |            1 | 20
 default_group |      0 |       6437 |            2 | 0.3
 default_group |      0 |       6437 |            3 | 0.3
 admin_group   |      0 |       6438 |            1 | -1
 admin_group   |      0 |       6438 |            2 | 0.1
 admin_group   |      0 |       6438 |            3 | 0.1
(6 rows)
```

**Comment by xiong-gang** [comment]
Merged. Thanks for the review.

**Pull request merged**
