### PR TITLE
[6X] ORCA produces bogus plan for queries with CTE during handling distribution for Sequence children

### PR DESCRIPTION
**Pull request by RekGRpth**
this is backport of https://github.com/greenplum-db/gpdb/pull/14896

With some conditions ORCA generates `Redistribute Motion` from all segments to one segment or generates a plan which can't be executed by reason of inconsistency between CTE producers and consumers.
For example, run query with two CTEs one of which is inlined by filter
```sql
CREATE TABLE d (a int, b int, c int) DISTRIBUTED BY (a);
CREATE TABLE r (a int, b int, c char(255)) DISTRIBUTED REPLICATED;
INSERT INTO d SELECT 1, generate_series(1,10), 1;
INSERT INTO r SELECT 1, 2, generate_series(1,100);
EXPLAIN (ANALYZE off, COSTS off, VERBOSE off)
WITH e AS (
    SELECT DISTINCT b FROM d
), h AS (
    SELECT a FROM d JOIN e f USING (b) JOIN e USING (b)
) SELECT * FROM r JOIN h USING (a);
```
that gives bogus plan
```sql
 Gather Motion 1:1  (slice4; segments: 1)
   ->  Sequence
         ->  Shared Scan (share slice:id 4:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d_1.b
                           ->  Sort
                                 Sort Key: d_1.b
                                 ->  Redistribute Motion 3:1  (slice3; segments: 3)
                                       Hash Key: d_1.b
                                       ->  Seq Scan on d d_1
         ->  Hash Join
               Hash Cond: (r.a = d.a)
               ->  Seq Scan on r
               ->  Hash
                     ->  Broadcast Motion 3:1  (slice2; segments: 3)
                           ->  Hash Join
                                 Hash Cond: (d.b = share0_ref3.b)
                                 ->  Redistribute Motion 3:3  (slice1; segments: 3)
                                       Hash Key: d.b
                                       ->  Seq Scan on d
                                 ->  Hash
                                       ->  Hash Join
                                             Hash Cond: (share0_ref3.b = share0_ref2.b)
                                             ->  Shared Scan (share slice:id 2:0)
                                             ->  Hash
                                                   ->  Shared Scan (share slice:id 2:0)
 Optimizer: Pivotal Optimizer (GPORCA)
(28 rows)
```
In this plan `Shared Scan (share slice:id 4:0)` is CTE producer that's executed only on one segment (due to `Redistribute Motion 3:1  (slice3; segments: 3)` from all segments to one segments), but CTE consumers `Shared Scan (share slice:id 2:0)` are executed on all segments and then query hangs.
Or run query with two CTEs
```sql
CREATE TABLE d (a int, b int, c int) DISTRIBUTED BY (a);
CREATE TABLE r (a int, b int, c char(255)) DISTRIBUTED REPLICATED;
--INSERT INTO d SELECT 1, generate_series(1,10), 1;
--INSERT INTO r SELECT 1, 2, generate_series(1,100);
EXPLAIN (ANALYZE off, COSTS off, VERBOSE off)
WITH e AS (
    SELECT DISTINCT b FROM d
), h AS (
    SELECT a FROM d JOIN e f USING (b) JOIN e USING (b)
) SELECT * FROM r JOIN h USING (a) JOIN h i USING (a);
```
that gives bogus plan
```sql
 Gather Motion 1:1  (slice5; segments: 1)
   ->  Sequence
         ->  Shared Scan (share slice:id 5:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d_1.b
                           ->  Sort
                                 Sort Key: d_1.b
                                 ->  Redistribute Motion 3:1  (slice4; segments: 3)
                                       Hash Key: d_1.b
                                       ->  Seq Scan on d d_1
         ->  Sequence
               ->  Shared Scan (share slice:id 5:1)
                     ->  Materialize
                           ->  Hash Join
                                 Hash Cond: (d.b = share0_ref2.b)
                                 ->  Hash Join
                                       Hash Cond: (d.b = share0_ref3.b)
                                       ->  Redistribute Motion 3:1  (slice3; segments: 3)
                                             Hash Key: d.b
                                             ->  Seq Scan on d
                                       ->  Hash
                                             ->  Shared Scan (share slice:id 5:0)
                                 ->  Hash
                                       ->  Shared Scan (share slice:id 5:0)
               ->  Hash Join
                     Hash Cond: ((r.a = share1_ref3.a) AND (r.a = share1_ref2.a))
                     ->  Seq Scan on r
                     ->  Hash
                           ->  Broadcast Motion 3:1  (slice2; segments: 3)
                                 ->  Hash Join
                                       Hash Cond: (share1_ref3.a = share1_ref2.a)
                                       ->  Shared Scan (share slice:id 2:1)
                                       ->  Hash
                                             ->  Broadcast Motion 3:3  (slice1; segments: 3)
                                                   ->  Shared Scan (share slice:id 1:1)
 Optimizer: Pivotal Optimizer (GPORCA)
(37 rows)
```
In this plan `Shared Scan (share slice:id 5:0)` and `Shared Scan (share slice:id 5:1)` are CTE producers that are executed only on one segment (due to `Redistribute Motion 3:1  (slice4; segments: 3)` and `Redistribute Motion 3:1  (slice3; segments: 3)` from all segments to one segments), but CTE consumers `Shared Scan (share slice:id 5:0)` and `Shared Scan (share slice:id 2:1)` and `Shared Scan (share slice:id 1:1)` are executed on all segments and then query hangs.
We get Redistribute from all segments to one segments because the following. When translating expression to DXL, ORCA sets one segment for input array if strict or tainted replicated distribution detected. https://github.com/greenplum-db/gpdb/blob/5cc4a5981a8cd31747a1a1120b9676c6f8dc39c7/src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp#L8223-L8237 This one segment is used as output array for below motions including redistribute and broadcast.
Solution is do not allow replicated distribution when required distribution in sequence is singleton on master or non-singleton with not allowed replicated.
In case of inlining one CTE we also need to push down non-singleton with not allowed replicated through filter. Because filter is appeared when CTE may be inlined and inlining allowed or only one consumer exists for that CTE. https://github.com/greenplum-db/gpdb/blob/5cc4a5981a8cd31747a1a1120b9676c6f8dc39c7/src/backend/gporca/libgpopt/src/xforms/CXformCTEAnchor2TrivialSelect.cpp#L57-L61 In this case ORCA append logical select, https://github.com/greenplum-db/gpdb/blob/5cc4a5981a8cd31747a1a1120b9676c6f8dc39c7/src/backend/gporca/libgpopt/src/xforms/CXformCTEAnchor2TrivialSelect.cpp#L103-L105 which later is translated to filter. https://github.com/greenplum-db/gpdb/blob/5cc4a5981a8cd31747a1a1120b9676c6f8dc39c7/src/backend/gporca/libgpopt/src/xforms/CXformSelect2Filter.cpp#L94-L95
It is gives right plans.
For two CTEs one of which is inlined by filter
```sql
 Gather Motion 3:1  (slice4; segments: 3)
   ->  Sequence
         ->  Shared Scan (share slice:id 4:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d_1.b
                           ->  Sort
                                 Sort Key: d_1.b
                                 ->  Redistribute Motion 3:3  (slice3; segments: 3)
                                       Hash Key: d_1.b
                                       ->  Seq Scan on d d_1
         ->  Hash Join
               Hash Cond: (r.a = d.a)
               ->  Result
                     ->  Seq Scan on r
               ->  Hash
                     ->  Redistribute Motion 3:3  (slice2; segments: 3)
                           Hash Key: d.a
                           ->  Hash Join
                                 Hash Cond: (d.b = share0_ref3.b)
                                 ->  Redistribute Motion 3:3  (slice1; segments: 3)
                                       Hash Key: d.b
                                       ->  Seq Scan on d
                                 ->  Hash
                                       ->  Hash Join
                                             Hash Cond: (share0_ref3.b = share0_ref2.b)
                                             ->  Shared Scan (share slice:id 2:0)
                                             ->  Hash
                                                   ->  Shared Scan (share slice:id 2:0)
 Optimizer: Pivotal Optimizer (GPORCA)
(30 rows)
```
For two CTEs
```sql
 Gather Motion 3:1  (slice5; segments: 3)
   ->  Sequence
         ->  Shared Scan (share slice:id 5:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d_1.b
                           ->  Sort
                                 Sort Key: d_1.b
                                 ->  Redistribute Motion 3:3  (slice4; segments: 3)
                                       Hash Key: d_1.b
                                       ->  Seq Scan on d d_1
         ->  Sequence
               ->  Shared Scan (share slice:id 5:1)
                     ->  Materialize
                           ->  Hash Join
                                 Hash Cond: (d.b = share0_ref2.b)
                                 ->  Hash Join
                                       Hash Cond: (d.b = share0_ref3.b)
                                       ->  Redistribute Motion 3:3  (slice3; segments: 3)
                                             Hash Key: d.b
                                             ->  Seq Scan on d
                                       ->  Hash
                                             ->  Shared Scan (share slice:id 5:0)
                                 ->  Hash
                                       ->  Shared Scan (share slice:id 5:0)
               ->  Hash Join
                     Hash Cond: ((r.a = share1_ref3.a) AND (r.a = share1_ref2.a))
                     ->  Result
                           ->  Seq Scan on r
                     ->  Hash
                           ->  Redistribute Motion 3:3  (slice2; segments: 3)
                                 Hash Key: share1_ref3.a, share1_ref2.a
                                 ->  Hash Join
                                       Hash Cond: (share1_ref3.a = share1_ref2.a)
                                       ->  Shared Scan (share slice:id 2:1)
                                       ->  Hash
                                             ->  Broadcast Motion 3:3  (slice1; segments: 3)
                                                   ->  Shared Scan (share slice:id 1:1)
 Optimizer: Pivotal Optimizer (GPORCA)
(39 rows)
```
I commented inserts in case of two CTE, because with it we have [another bug](https://github.com/greenplum-db/gpdb/issues/15134)

### CODE REVIEW

**Comment by gpopt** [comment]
I don't think the test failure is related with your change, try to re-trigger it.
```
======================================================================
DIFF FILE: ../gpdb_src/src/test/isolation2/regression.diffs
----------------------------------------------------------------------

--- \/tmp\/build\/c7e122a2\/gpdb_src\/src\/test\/isolation2\/expected\/parallel_retrieve_cursor\/corner\.out	2023-03-03 12:09:36.237876616 +0000
+++ \/tmp\/build\/c7e122a2\/gpdb_src\/src\/test\/isolation2\/results\/parallel_retrieve_cursor\/corner\.out	2023-03-03 12:09:36.597911839 +0000
@@ -1902,7 +1902,7 @@
 1: DECLARE c22 PARALLEL RETRIEVE CURSOR WITHOUT HOLD FOR SELECT * FROM generate_series(1,10);
 DECLARE
 1: @post_run 'parse_endpoint_info 22 1 2 3 4' : SELECT endpointname,auth_token,hostname,port,state FROM gp_get_endpoints() WHERE cursorname='c22';
- endpoint_id22 | token_id | host_id | port_id | READY
+ endpoint_id22 | port_id 436c3d70f6add7ddc3f455e5103e | host_id | port_id | READY
 (1 row)
 1: SELECT * FROM gp_wait_parallel_retrieve_cursor('c22', 0);
  finished 
```

**Comment by RekGRpth** [comment]
> I don't think the test failure is related with your change, try to re-trigger it.

Thank You for response, how I can trigger?

**Comment by gpopt** [comment]
force push a commit, or add a new commit

**Comment by RekGRpth** [comment]
I added PR description

**Review by gpopt — APPROVED** [review]
+1

**Comment by gpopt** [comment]
Pushed to 6X_STABLE, thanks for your contribution, @RekGRpth!

**Pull request merged**
