### PR TITLE
Parse and check match commands in atmsort

### PR DESCRIPTION
**Pull request by danielgustafsson**
The start_matchignore and start_matchsubs could be closed by either
and only the closing command determined what the content was used
as. This could lead to subtle things as only a more-or-less silent
warning was issued in the diff. Instead parse the start_ and match
the end_ command to ensure they match and fail if they don't.

@hlinnaka I couldn't resist taking a stab at this.. =)

### CODE REVIEW

**Comment by hlinnaka** [comment]
Thanks for tackling this!

**Comment by danielgustafsson** [comment]
While a matter of taste, I think it's more "modern Perl" to use a hash for such associated key/value pairs. Taking this a bit further would be to avoid creating a large string of the expressions but instead push them onto a list to avoid the awkward split/n/ step. Thats for a rainy day though.

**Comment by hlinnaka** [comment]
On 03/10/2017 12:10 PM, Daniel Gustafsson wrote:
> While a matter of taste, I think it's more "modern Perl" to use a
> hash for such associated key/value pairs.

Ok.

- Heikki

**Comment by danielgustafsson** [comment]
Pushed to master, thanks!

**Pull request closed without merging**
