### PR TITLE
Remove workfile mgr dead code

### PR DESCRIPTION
**Pull request by hlinnaka**
@gcaragea, others, all this code can go away, right?

### CODE REVIEW

**Comment by gcaragea** [comment]
Thanks for the clean-up Heikki. Removing the workfile caching support from executor looks good. 

But I would like to keep the SharedCache code in, including the gclock replacement policy. Without the replacement policy, this is not usable as a cache. Since it comes with its own unit tests, its exercised code, and if at some point we need such a data structure we will have it.

**Comment by hlinnaka** [comment]
On 21/06/16 21:13, George Caragea wrote:
> Thanks for the clean-up Heikki. Removing the workfile caching support
> from executor looks good.
>
> But I would like to keep the SharedCache code in, including the
> gclock replacement policy. Without the replacement policy, this is
> not usable as a cache. Since it comes with its own unit tests, its
> exercised code, and if at some point we need such a data structure we
> will have it.

Meh. It's nothing special, as an implementation. And it's there in the 
git history, if someone really needs it. And I doubt we'll need it; I 
don't foresee us implementing a feature that would benefit from a shmem 
cache like that any time soon. And if we did, a simple LRU policy would 
probably suffice. Dead code has a maintenance cost, albeit small: 
newcomers will browse around and find it, and have to discover on their 
own that it's actually dead code.

- Heikki

**Comment by danielgustafsson** [comment]
:+1: on this, the code can always be resurrected from VCS history should we need it.

**Comment by danielgustafsson** [comment]
This was pushed in 846b6e5 such that we can close this PR right?

**Comment by hlinnaka** [comment]
Yes, quite right. Closed, thanks.

**Pull request closed without merging**
