### PR TITLE
Remove the notion that the server configuration can be changed using pgAdminIII

### PR DESCRIPTION
**Pull request by andreasscherbaum**
The "gpconfig" tool should be used instead

### CODE REVIEW

**Comment by ascherbaum-pivotal** [comment]
I'm not sure if I catched everything: could not figure out how the two links appear here:

https://gpdb.docs.pivotal.io/4370/admin_guide/access_db/topics/g-performing-administrative-tasks-with-pgadmin-iii.html

When I remove the file for the Server Configuration link, will this automatically remove the link from the page?

**Comment by dyozie** [comment]
@ascherbaum-pivotal - To remove this from the navigation as well, you also need to remove the file's reference from all .ditamap files.   In this case, `dita/admin_guide/access_db/access_db.ditamap`  The other thing to check for when removing a file would be XREFs to the file, but I didn't notice any in my search.

**Comment by dyozie** [comment]
Unrelated to these edits, @Eulerizeit has mentioned that pgAdminIII isn't really compatible with GPDB 5.0.0 and pgAdmin IV is needed.  Still waiting for that work to happen before updating the docs.

**Comment by Eulerizeit** [comment]
I don't know if pgAdmin3 is compatible or not. pgAdmin4 is currently
compatible with 5.0 but not yet on PivNet.

**Comment by andreasscherbaum** [comment]
I think by removing the documentation we should be fine.
Such a warning should rather go into pgAdminIII - but I suspect we won't get this change in. Development rather stopped lately.

**Comment by andreasscherbaum** [comment]
@dyozie I did check for other links, but did not know about access_db.ditamap. Updated this one as well in the last commit.

**Pull request merged**
