### PR TITLE
5X: gpstart: correctly display unavailable segments

### PR DESCRIPTION
**Pull request by jchampio**
_This is a backport of #8956 and #9164 to 5X_STABLE._

The second commit cherry-picks the new tests from 91381fe and d8e5947, with tweaks for the 5X versions of the catalog, gppylib, and behave. Some additional test infrastructure from 6X_STABLE has come along to support those new tests. The previously-inactive gpstart behave suite has been resurrected (though the DCA-specific tests have been commented out).

([pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/5X:invalid-segments))

### CODE REVIEW

**Comment by jchampio** [comment]
@mkiyama @dyozie @bharath1028 FYI

**Comment by kalensk** [comment]
Just to be clear 5X already had a gpstart.feature file with tests, but was not being run. This PR actually runs those tests and adds an additional test, while also commenting out the existing (DCA gpstart) tests that don't work. Is that correct?

**Comment by jchampio** [comment]
@kalensk Correct.

**Comment by jchampio** [comment]
Thanks for the review!

**Pull request merged**
