### PR TITLE
Implement ORCA metadata cache resetting in a simpler way

### PR DESCRIPTION
**Pull request by hlinnaka**
The first patch is simply a revert of pull request #130. The second patch implements the same functionality in a much simpler way, by using the existing syscache invalidation mechanism. This addresses my complaints on the design of pull request #130.

@gcaragea, any objections to this? This is much simpler than the committed version. Ideally, we wouldn't even need the hack for the magic "-1" catcache to catch all catalog table updates, and properly registered the callback for each individual cache (or at least one cache per catalog table we're interested in). But if you strongly resist the idea of adding a catalog cache for all of the needed catalog tables, I could live with this hack for now.

### CODE REVIEW

**Comment by gcaragea** [comment]
Sure, let me take a look and discuss with the team.

**Comment by gcaragea** [comment]
@hlinnaka Thanks for this rewrite. My team looked at it and we like the simplicity. 

The main comment we have is the potential overhead from generating multiple invalidation messages for a DDL or series of DDLs. 

Consider the following case: 
A transaction that runs 10 complex DDLs like CREATE TABLE that touches ~30 catalog tuples. This approach will generate 300 messages on the local message queue. At commit, these will be appended to the shared invalidation queue. 
Every other backend will then "Accept()" these messages and call the increment counter 300 times. 

We were wondering if there is a way to "compact" these messages into one (or a few), because they are basically idempotent. 

Any ideas on how to do this?

**Comment by hlinnaka** [comment]
On 16/12/15 02:05, George Caragea wrote:
> The main comment we have is the potential overhead from generating
> multiple invalidation messages for a DDL or series of DDLs.
>
> Consider the following case: A transaction that runs 10 complex DDLs
> like CREATE TABLE that touches ~30 catalog tuples. This approach will
> generate 300 messages on the local message queue. At commit, these
> will be appended to the shared invalidation queue. Every other
> backend will then "Accept()" these messages and call the increment
> counter 300 times.
>
> We were wondering if there is a way to "compact" these messages into
> one (or a few), because they are basically idempotent.

Two thoughts on that:

1. Most of the invalidations will be happening anyway. There's a catalog 
cache on most PostgreSQL catalog tables.

2. DDL is so expensive on GPDB anyway that I'm pretty sure that even if 
you fire hundreds of extra invalidation messages for a DDL command, you 
won't notice the difference.

That's just my gut feelings though, it would be a good idea to do some 
performance testing on that. If it turns out that it matters after all, 
we could add some kind of a compaction mechanism.

- Heikki

**Comment by hlinnaka** [comment]
On 16/12/15 02:18, Heikki Linnakangas wrote:
> 1. Most of the invalidations will be happening anyway. There's a catalog
> cache on most PostgreSQL catalog tables.

Oh, scratch that. The way I wrote this, there will indeed be an extra 
invalidation event for every change. So this will roughly double the 
number of invalidations.

> 2. DDL is so expensive on GPDB anyway that I'm pretty sure that even if
> you fire hundreds of extra invalidation messages for a DDL command, you
> won't notice the difference.

This still holds though.

However, I just opened pull request #181 that implements this in the way 
that we register separately for each catalog cache, which makes the 
point moot again.

- Heikki

**Comment by hlinnaka** [comment]
Closing this in favor of pull request #181.

**Pull request closed without merging**
