### PR TITLE
Orca build cleanup

### PR DESCRIPTION
**Pull request by hlinnaka**

### CODE REVIEW

**Comment by vraghavan78** [comment]
Is this all needed for enterprise build?

**Comment by vraghavan78** [comment]
@d @oarap @hsyuan can you take a look at this PR

**Comment by hlinnaka** [comment]
On 01/18/2017 03:51 AM, Venkatesh Raghavan wrote:
> Is this all needed for enterprise build?

Sorry, I don't understand the question. What is enterprise build? This 
does work when building with the gpAux/Makefile stuff, if that's what 
you meant. That's what the PR concourse job does too, and it's happy.

- Heikki

**Comment by edespino** [comment]
LGTM

**Comment by hsyuan** [comment]
LGTM

**Pull request merged**
