### PR TITLE
Fix misuse pointer of pointer in IndexScan_OpenIndexRelation

### PR DESCRIPTION
**Pull request by geekbosszhang**
Co-authored-by: Hao Wang <haowang@pivotal.io>
Co-authored-by: Wenlin Zhang <wzhang@pivotal.io>

### CODE REVIEW

**Comment by hlinnaka** [comment]
On 4 January 2019 13:16:05 EET, Tang Pengzhou <notifications@github.com> wrote:
>@pengzhout requested your review on: greenplum-db/gpdb#6613 Fix misuse
>pointer of pointer in IndexScan_OpenIndexRelation.

LGTM. It's pretty amazing that this has ever worked at all. Do we need new tests in this area?

- Heikki

**Comment by geekbosszhang** [comment]
Thanks for the review.

In partition_locking and partition_locking_optimizer test, it already covered the logic for dynamicScan. For planner, it should not place accessShareLock because it's not dynamicScan, but instead, in orca, it will have accessShareLock.

Currently, icw_planner jobs on 5X_STABLE CI are red because the bug surfaces after our last commit https://github.com/greenplum-db/gpdb/commit/1893d649be9567cab965260396b8a8a56052318d After this fix, the failing test for partition_locking should be passed and CI will be green.

**Comment by pengzhout** [comment]
shall we fix this in master too?

**Comment by magi345** [comment]
Thanks for review.
@pengzhout Master have merged a lot and no such code exists.
However, gpdb4 has the same bug I will raise it to PM.

**Pull request merged**
