### PR TITLE
Add support for piping COPY to/from an external program

### PR DESCRIPTION
**Pull request by adam8157**
commit 3d009e45bde2a2681826ef549637ada76508b597
    Author: Heikki Linnakangas <heikki.linnakangas@iki.fi>
    Date:   Wed Feb 27 18:17:21 2013 +0200

        Add support for piping COPY to/from an external program.

        This includes backend "COPY TO/FROM PROGRAM '...'" syntax, and corresponding
        psql \copy syntax. Like with reading/writing files, the backend version is
        superuser-only, and in the psql version, the program is run in the client.

        In the passing, the psql \copy STDIN/STDOUT syntax is subtly changed: if you
        the stdin/stdout is quoted, it's now interpreted as a filename. For example,
        "\copy foo from 'stdin'" now reads from a file called 'stdin', not from
        standard input. Before this, there was no way to specify a filename called
        stdin, stdout, pstdin or pstdout.

        This creates a new function in pgport, wait_result_to_str(), which can
        be used to convert the exit status of a process, as returned by wait(3),
        to a human-readable string.

        Etsuro Fujita, reviewed by Amit Kapila.

Signed-off-by: Adam Lee <ali@pivotal.io>
Signed-off-by: Ming LI <mli@apache.org>

### CODE REVIEW

**Comment by danielgustafsson** [comment]
I don't doubt the usefulness of this, but it would be good with an explanation of why we need it now as opposed to when we get it via merging.

**Comment by lij55** [comment]
Hi @danielgustafsson ,

We discussed with Heikki about this before. As customer is pushing this feature, the only walk around we could find is that we push it to 5.x and 4.x only. This is why is PR is not for master branch but 5X_STABLE branch.

We will try to find better solution on master when merge is ready later.

**Comment by danielgustafsson** [comment]
> On 07 Sep 2017, at 11:37, Jasper Li <notifications@github.com> wrote:
> 
> We discussed with Heikki about this before. As customer is pushing this feature,

Ok

> the only walk around we could find is that we push it to 5.x and 4.x only. This is why is PR is not for master branch but 5X_STABLE branch.

This I disagree with. Since this feature only comes in upstream 9.3 IIRC, it won’t be included in the 6.x merge cycle. Therefore I would argue it *has* to land in master first and then be backported to 5. 5X_STABLE should at all times be a subset of master, else we will end up in an unmanageable situation. Any commit to 5X_STABLE should always be a backport from master, regardless how trivial/invasive it is.

That being said, since you are modifying the CopyStmt, is this a compatible change for 5.x?

Note: I’m not arguing against/for backporting this, only how to do it.

**Comment by hlinnaka** [comment]
>  On 07 Sep 2017, at 11:37, Jasper Li ***@***.***> wrote:
>
>> We discussed with Heikki about this before. As customer is pushing this feature,
> Ok

And to be clear, I objected to this, and said that we should instead advise the customer how to use the existing functionality, with an EXECUTE-style external table, to do the same thing.

>> the only walk around we could find is that we push it to 5.x and 4.x only. This is why is PR is not for master branch but 5X_STABLE branch.
> This I disagree with. Since this feature only comes in upstream 9.3 IIRC, it won’t be included in the 6.x merge cycle. Therefore I would argue it *has* to land in master first and then be backported to 5. 5X_STABLE should at all times be a subset of master, else we will end up in an unmanageable situation. Any commit to 5X_STABLE should always be a backport from master, regardless how trivial/invasive it is.

Totally agreed.

> That being said, since you are modifying the CopyStmt, is this a compatible change for 5.x?

Hmm. I don't think CopyStmts can be stored in view definitions, so it's probably OK.

- Heikki

**Comment by lij55** [comment]
Then Let's focus on where to push this PR here.
Do you agree we push it to master here?

**Comment by danielgustafsson** [comment]
> On 07 Sep 2017, at 12:10, Jasper Li <notifications@github.com> wrote:
> 
> Then Let's focus on where to push this PR here.
> Do you agree we push it to master here?

*If* it’s pushed, it should be to master and from there to 5X_STABLE.

That being said I still think there needs to be more review on this PR before discussing pushing. A few question that comes to mind are: How will it handle if the program exists on some segments but not all? What if the program is installed in two different versions on the segments which are incompatible in such a way that data is corrupted? (we can’t protect against everything of course, but if we don’t discuss the potential footguns before merging a user is guaranteed to find them =)).

**Pull request closed without merging**
