### PR TITLE
Fix issue #74, make cluster in gpdemo failed(initdb failed on a 32-bi…

### PR DESCRIPTION
**Pull request by robertmu**
@hlinnaka 
Heikki suggested that we backport atomic operation from PostgreSQL 9.5 to
fix this.please review

### CODE REVIEW

**Comment by robertmu** [comment]
@hlinnaka 
I've removed the assembly from gp_atomic.h, replace GPDB-specific compare_and_swap_*,gp_atomic_add_* and with pg_atomic_* functions.Please review,Thanks for your advice and help

**Comment by ivannovick** [comment]
@robertmu good work!

**Comment by hlinnaka** [comment]
I was going to look at this now, but this conflicted with the committed pull request #130. That's very likely going to get reverted soon though, in favor of #175, so I'm not going to bother rebasing this for right now. The rebasing would be straightforward, but let's see what the resolution to #130/#175 is, and revisit this after that, hopefully by the end of the week. So just hold on tight :-).

**Comment by gcaragea** [comment]
This looks cool. @armenatzoglou @karthijrk @foyzur please also take a look, as it's a more portable solution to atomics that we used.

**Comment by karthijrk** [comment]
Over all design looks good to me as well +1.

Thanks,
Karthi

**Comment by hlinnaka** [comment]
Pushed (finally) with two trivial changes:

* I added a function prototype for the new test_atomic_ops() function in regress.c, to eliminate a compiler warning. (per comment, this is not needed in upstream, because the PG_FUNCTION_INFO_V1() macro includes the prototype since 9.4)

* I moved the 'lock' test case in serial_schedule to where it is in the upstream, to minimize diff.

Thanks for the patch!

**Pull request closed without merging**
