### PR TITLE
Push a stable centos6 gpdb artifact to S3 if ICW passes

### PR DESCRIPTION
**Pull request by lavjain**
Also merged UD group into ICW

### CODE REVIEW

**Comment by lavjain** [comment]
@pivotal-mike Different groups may have different definition of what is stable for their consumption. We can change the bucket folder to icw-passed instead of stable. This way at least PXF pipeline can pick the artifact rather than compiling GPDB for each run.

**Comment by lavjain** [comment]
@pivotal-mike `/gdb-5-concourse-builds/deliverables/` folder only contains greenplum-clients-6.0.0-alpha-xxx-aix7_ppc_64.zip. There are no centos6 artifacts

**Comment by denalex** [comment]
why don't we limit the change to only publishing icw_green artifact after icw_end gate so that other components' pipelines can consume that if they want to. 

If they want more tests to be passed in addition to icw suite, at the moment they would need to modify the pipeline and in the future we will hopefully agree what is the set of tests we need the gpdb artifact to pos to be considered worthy of being used by other component.

**Comment by lavjain** [comment]
Replaced by https://github.com/greenplum-db/gpdb/pull/4399

**Pull request closed without merging**
