### PR TITLE
Do not use immediate restart in instr_in_shmem_setup test

### PR DESCRIPTION
**Pull request by huansong**
There is nothing wrong with doing that for the test itself, but it has an implication to a bug #16120 where restarting w/o checkpoint can create orphaned files and results in the failure of test gp_check_fiels. While that issue is dealt with separately, for now turn the restart mode to fast to avoid the issue.

Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/regress-gpstop-ari

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by soumyadeep2007** [comment]
There is rampant use of `gpstop -ai` all throughout the tests (in some cases intentional like: `bitmap_index_crash`, but in most cases unnecessary like: `prepare_limit` and many resource group tests where we restart to simply load GUC changes). I imagine we will run into the same flake because of them?

**Comment by huansong** [comment]
@soumyadeep2007 I ignored `isolation2` tests for now because gp_check_files are not covering them (and it would be really hard to cover, given so many intentional crash/panic that we are doing in isolation2 that could create orphaned files... I don't see us do that anytime soon). 

In the regress tests there are just three tests with `gpstop -ai`: `instr_in_shmem_setup` and `resource_manager_restore_to_none`, `resource_manager_switch_to_queue`. I wasn't too sure about resource group so I left them untouched. But yes they can cause the same issue too. I'll add them if you think we should!

**Comment by soumyadeep2007** [comment]
> In the regress tests there are just three tests with gpstop -ai: instr_in_shmem_setup and resource_manager_restore_to_none, resource_manager_switch_to_queue. I wasn't too sure about resource group so I left them untouched (the only confirmed case was orphaned file created before instr_in_shmem_setup). But yes potentionally they can cause the same issue too. I'll add them if you think we should!

Yes, let's add those, dev pipeline should test the resource group tests. There is no need to do an immediate shutdown in any of those.

Also, I found `segspace_setup` and `segspace_cleanup`, which seems like dead test files, which has the same thing. They can also be removed as a separate commit.

**Comment by huansong** [comment]
> Yes, let's add those

> segspace_setup and segspace_cleanup, which seems like dead test files

Done & done

**Review by soumyadeep2007 — APPROVED** [review]
LGTM!

**Comment by QingMa-gp** [comment]
LGTM.

**Review by QingMa-gp — APPROVED** [review]

**Pull request merged**
