### PR TITLE
Move GPDB specific SQL tools from src/bin to contrib/gp_internal_tools

### PR DESCRIPTION
**Pull request by danielgustafsson**
The workfile_manager unittest code was previously included in all builds, this is however functionality which shouldn't be in prod installations. ~~Limit building and installation of the unittests to builds configured with `--enable-debug`. The cache_stats function is left in normal builds since it's not test related, there is no SQL file installed for it, but thats the case today as well.~~ 

This removes the unittest from the builtins header since it wont always be there, the src/bin component didn't however use that anyways but declares it locally anyways so seems a safe bet.

Also includes a commit cleaning up comments and spelling.

**PR Updated:** Read comment thread for current state.

### CODE REVIEW

**Comment by ashwinstar** [comment]
How do you test this then, as CI only builds optimized/enterprise builds?

**Comment by danielgustafsson** [comment]
> On 16 Mar 2017, at 15:20, Ashwin Agrawal <notifications@github.com> wrote:
> 
> How do you test this then, as CI only builds optimized/enterprise builds?

Well, consider this an opinion piece that there should be build using
debug/cassert too (not required for every commit but should be tested
occasionally) =)

**Comment by ashwinstar** [comment]
Why not move it to regress directory along with other tests ? I have no idea when and how this test is run, just a blind suggestion.

**Comment by Eulerizeit** [comment]
@schubert @pivotal-mike this fix will allow us to remove some potentially huge footguns. i.e. the ability for non-SU do blow up the entire DB.

**Comment by danielgustafsson** [comment]
Updated PR to move the unit test code to src/test/regress and hooked it up to ICW (which it previously wasn't). Also added a SQL file install the gp_workfile_mgr functions which were for actual production use but weren't exposed for installation.

**Comment by danielgustafsson** [comment]
Concourse happy. Since you had concerns about the previous approach @hlinnaka and @ashwinstar, how about this one?

**Comment by hlinnaka** [comment]
Works for me. This is a step forward, for sure.

I wonder if we need the remaining functions in src/bin/gp_workfile_mgr for anything? I.e. how about we don't create the install script for them, and instead, remove them altogether.

on a related note, src/bin is a pretty horrible location for those functions. If we do want to keep them, moving them to contrib/ would be appropriate. Or just make them proper built-in functions in the backend.

**Comment by danielgustafsson** [comment]
Since I have no idea of the usefulness of the functions, I moved them to contrib/ but left them out of the main set (for now). I agree that they don't belong in src/bin. @pivotal-mike @Eulerizeit do we know if anyone is particularly interested in these or is it fine to keep them along in contrib and if no hands are shown remove them in 6.0?

**Comment by pivotal-mike** [comment]
@danielgustafsson This is failing on gpinitsystem for the gpdemo build?  Do you want to try a gpdemo startup locally and resubmit if that works?

**Comment by danielgustafsson** [comment]
Turns out we install these functions in gp_toolkit, had missed that fact. Being in src/bin is still wrong and making a new contrib was also wrong. Moved them to contrib/gp_internal_tools since that's required by gp_toolkit anyways so we're at least not introducing anything new. In 6.0 we should revisit this and just make these normal backend functions but for 5.0 with the catalog frozen let's stick to the evil we know.

**Comment by danielgustafsson** [comment]
Ping, possible to get this reviewed to make it in before beta?

**Comment by pivotal-mike** [comment]
@asimrp @karthijrk Can we please have a quick look-see at this?

**Comment by danielgustafsson** [comment]
Pushed to master, thanks

**Pull request closed without merging**
