### PR TITLE
Remove unused ORCA tasks in concourse/tasks

### PR DESCRIPTION
**Pull request by amilkh**
Authored-by: Amil Khanzada <akhanzada@pivotal.io>

### CODE REVIEW

**Comment by bradfordboyle** [comment]
@chrishajas @asubramanya Are these files still being used? I cannot find any usage of them in:

- GPDB code
- GPDB CI
- gporca code
- gporca CI

[search query](https://github.com/search?q=build_gpdb_with_orca_gen_by_conan.yml)

It looks like they were deleted on [master](https://github.com/greenplum-db/gpdb/commit/0d8221a8e4b4dae4d7267863e1d50bfee524310b). Are they still needed on 5X_STABLE or can they be deleted?

**Comment by asubramanya** [comment]
@bradfordboyle Seems like `test_with_orca_conan.yml` is being used in `pr_pipeline.yml` on 5X_STABLE. I don't think we have a PR pipeline for 5X though so I think it should be OK to remove it.

**Comment by amilkh** [comment]
@asubramanya @chrishajas I've update the PR to remove these 4 files, if it looks OK, could you please approve?
Once this PR is merged, we will go ahead and delete the unused `gpdb/centos-gpdb-dev-conan` from DockerHub.

**Comment by bradfordboyle** [comment]
Do the removed task also exist on 6X_STABLE? If so, can we cherrypick this forward?

**Comment by amilkh** [comment]
> Do the removed task also exist on 6X_STABLE? If so, can we cherrypick this forward?
Good point! But, I think these files aren't on gpdb 6X_STABLE or master so no need.

**Pull request merged**
