### PR TITLE
docs: unhide gpmovemirrors in utility guide

### PR DESCRIPTION
**Pull request by mkiyama**
PR for 5X_STABLE only

### CODE REVIEW

**Comment by Eulerizeit** [comment]
I'd rather we didn't because it might be very different in 6.0 and this isn't something customers should do alone.

**Comment by mkiyama** [comment]
@skahler-pivotal 
@Eulerizeit  has a concern.

**Comment by dyozie** [comment]
We weren't really planning to carry this forward to 6.0.  But the gpdb-dev discussion seemed to conclude that gpmovemirrors was useful and already being used by customers (4.x/5.x).

**Comment by skahler-pivotal** [comment]
It's something we are including and packaging currently. We had talked about removing it, but we weren't ready to do that yet. Anything we bundle up and include we should probably be documenting where we can. @ivannovick had mentioned customers using it, if people are making use of it having some docs out there would be helpful.

**Comment by ivannovick** [comment]
+1 to @skahler-pivotal 's points.  Agreed

**Comment by Eulerizeit** [comment]
My thinking is 2 fold:
1. Just because you can do something doesn't mean it should be a supported documented feature
1. If we document this now it will make it harder to change it as we are currently in the process of poking at utilities. 

This isn't a hill I'm going to die on, just my opinion.

**Pull request merged**
