### PR TITLE
[6X backport] Fix locking bugs that could corrupt pg_control.

### PR DESCRIPTION
**Pull request by jimmyyih**
The redo routines for XLOG_CHECKPOINT_{ONLINE,SHUTDOWN} must acquire ControlFileLock before modifying ControlFile->checkPointCopy, or the checkpointer could write out a control file with a bad checksum.

Likewise, XLogReportParameters() must acquire ControlFileLock before modifying ControlFile and calling UpdateControlFile().

Back-patch to all supported releases.

Author: Nathan Bossart <bossartn@amazon.com>
Author: Fujii Masao <masao.fujii@oss.nttdata.com>
Reviewed-by: Fujii Masao <masao.fujii@oss.nttdata.com>
Reviewed-by: Michael Paquier <michael@paquier.xyz>
Reviewed-by: Thomas Munro <thomas.munro@gmail.com>
Discussion: https://postgr.es/m/70BF24D6-DC51-443F-B55A-95735803842A%40amazon.com

(cherry picked from Postgres commit 57cb8063089a7d6c54e27adfd5d028cc01f21536)

GPDB Merge Conflicts:
1. Minor conflict due to some inconsistent Checkpoint fields (nextXidEpoch and nextXid vs. nextFullXid). Just needed to wrap the ControlFileLock acquire and release around the correct areas relative to the original commit.

### CODE REVIEW

**Review by kaknikhil — APPROVED** [review]
LGTM. I also verified that these are the only places that were not holding the lock. 

It might help to briefly more about the sequence of events that led us to discovering the bug

**Comment by jimmyyih** [comment]
> It might help to briefly more about the sequence of events that led us to discovering the bug

It's as the PR states but I guess I can reword it a bit if it's confusing:
It is a locking bug where the startup process does not acquire a lock on the control file data when modifying it when replaying an online checkpoint record.  Because of this, the checkpointer process when creating a restart point (which will hold the ControlFileLock lwlock) would calculate a correct CRC32 checksum but then could flush inconsistent control file data.

**Comment by jimmyyih** [comment]
> > It is a locking bug where the startup process does not acquire a lock on the control file data when modifying it when replaying an online checkpoint record. Because of this, the checkpointer process when creating a restart point (which will hold the ControlFileLock lwlock) would calculate a correct CRC32 checksum but then could flush inconsistent control file data.
> 
> FWIW, the previous description wasn't confusing but adding this on top of what you already have adds a good deal of context for future reference

Sure.  Added to the commit message.

**Review by SunilS26 — APPROVED** [review]
LGTM!

**Pull request merged**
