### PR TITLE
updates to language create/alter/drop allowing db owners

### PR DESCRIPTION
**Pull request by lisakowen**
changes related to language registration and database ownership.

question:  createlang and droplang ref pages are currently aligned with the 8.3 postgres docs which do not include any statements at all about privileges required.  these pages identify the utilities as wrappers for the associated SQL command.  privileges are discussed on the SQL command page.  is that enough?

### CODE REVIEW

**Comment by mkiyama** [comment]
I would say follow the postgres model.

**Comment by danielgustafsson** [comment]
I think it's fine to just keep it on the SQL page.

**Comment by dyozie** [comment]
I'm confused about these edits - I thought the intended change was for `create language` (and `createlang`), etc. to be executable by the DB owner, *rather* than just by superusers.  Is that not the 8.3 behavior?

**Comment by lisakowen** [comment]
if i understand things correctly, pl/r and pl/python are untrusted languages.  and by default, a non-superuser database owner could not register those languages on a db.

**Comment by dyozie** [comment]
That makes sense - so I'd recommend editing the two sentences that begin "Only superusers..." to say "Because <pl*> is an untrusted language, only superusers..."

**Comment by lisakowen** [comment]
thanks for reviewing @dyozie, i've incorporated your comments.

**Pull request merged**
