### PR TITLE
(6x only) Fix memory corruption in shareinput_walker.

### PR DESCRIPTION
**Pull request by kainwen**
This part of code is introduced by b13d891311. We should not treat
SubPlan or List as Plan node and access and modify related Plan
fields, this will lead to memory corruption and PANIC.

-------------------

We only capture such bug once in pipeline. Not easy for me to add a steady reproduced test case.

### CODE REVIEW

**Comment by ashwinstar** [comment]
Please can you elaborate further under what conditions will someone be exposed to the bug like any usage of SubPlan manifests in issue?

**Comment by ashwinstar** [comment]
Ouch!!!

**Comment by ashwinstar** [comment]
So its all matter to timing (concurrent usage of this memory) if the memory pointed to by casting non-plan node types to plan node and assigning back `plan->lefttree` can impact things or not. Which makes it harder I guess to write any specific targeted test or reproduction, right?

**Comment by kainwen** [comment]
Close this. Since we have reverted https://github.com/greenplum-db/gpdb/commit/b13d891311af8f41b499fae0dbb08065b51148f9.

Later we should see how to bring it back correctly.

cc @InnerLife0 @Stolb27 I think this bug needs to be paid attention to it.

**Comment by InnerLife0** [comment]
@kainwen I see the reason of possible fault and have two questions.
1) Are there any logs or details about failed test?
2) Is current patch solution not working properly?

**Comment by kainwen** [comment]
> @kainwen I see the reason of possible fault and have two questions.
> 
> 1. Are there any logs or details about failed test?
> 2. Is current patch solution not working properly?

Hi @InnerLife0 

> 1. Are there any logs or details about failed test?

 This fail is caught by internal private pipeline and we local reproduce is with:

* start gpdb (6.22.1) (ship with metric collector)
* start gpcc 
* run `regress/sql/delete.sql` it will PANIC

Then for debug friendly, I compile a O0 binary postgres and replace with the one. And then use `rr record` to fully record a PANIC.

The `share_input_walker` write a bad value into a memorycontext's block thus corrupt. In my local PANIC case, it is walking the `append` node's appendplans, it is a LIST, but taken as plannode, and write a bad value to a block's meta data.

That block is a block in use, which hold the value of some other plannodes.

Later when we print the plan, it will palloc memory, and choose this block, due to wrong field of that block, it will write data to modify other plan node. (yes, palloc0, modify other plan node's content). This lead to later PANIC.

I will try to write a summary of the detailed steps and ask if I can share the rr record.

----------

>  2. Is current patch solution not working properly?

I test locally, the patch can fix the PANIC. Since we are releasing 6.22.2 soon, we choose a safer way: firstly revert the previous commit.

**Comment by InnerLife0** [comment]
> The `share_input_walker` write a bad value into a memorycontext's block thus corrupt. In my local PANIC case, it is walking the `append` node's appendplans, it is a LIST, but taken as plannode, and write a bad value to a block's meta data.

OK, it seems I understand it right. `Append` node is small enough so we can get some out-of-memory access errors, or corrupt some data like in your case.

> I test locally, the patch can fix the PANIC. Since we are releasing 6.22.2 soon, we choose a safer way: firstly revert the previous commit.

For now, we test our own version of patch. How to better provide it as our commit was reverted? Should we do a new PR with old version of patch + fix?

And thanks for sharing, @kainwen

**Comment by kainwen** [comment]
> OK, it seems I understand it right. Append node is small enough so we can get some out-of-memory access errors, or corrupt some data like in your case.

Seems not only for append node. TargetEntry, List may all write bad things to out-bound-memory. 

> For now, we test our own version of patch. How to better provide it as our commit was reverted? Should we do a new PR with old version of patch + fix?

I think it is a good idea to reopen a PR with fully fix.

**Comment by InnerLife0** [comment]
> Seems not only for append node. TargetEntry, List may all write bad things to out-bound-memory.

True, or any other "small" nodes.

> I think it is a good idea to reopen a PR with fully fix.

OK

**Comment by ashwinstar** [comment]
> > Seems not only for append node. TargetEntry, List may all write bad things to out-bound-memory.
> 
> 
> 
> True, or any other "small" nodes.
> 

Any non-plan node smaller (corrupts someone else's memory or even bigger (corrupts within struct) so just not good in-general.

**Comment by InnerLife0** [comment]
I'm glad to introduce [fixed version](https://github.com/greenplum-db/gpdb/pull/14696). Sorry for delay.

**Pull request closed without merging**
