### PR TITLE
gpexpand support readability

### PR DESCRIPTION
**Pull request by uglthinx**
Tables in the redistribution state during gpexpand cannot be read or written. For a 350GB column-stored table, the redistribution needs to last more than 1 hour. During this period, queries join with the table cannot be executed.

In addition, if a partition table including external table, gpexpand will fail. You need to manually delete the external table partition and restore the external table after the expansion is completed.

#### commit fix
- In the CTAS phase, the lock is reduced to Exclusive Lock to support table readability.
- Sink the expansion of the partition table to the leaf partition, which can be expanded in parallel, and the external table can be filtered.

It is necessary to ensure that the data can be read correctly during the redistribution, the inserted data will not be lost, and gpexpand can be retried if it fails.

See github issue: [#10114](https://github.com/greenplum-db/gpdb/issues/10114)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@uglthinx Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10324)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10324) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@uglthinx Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10324)!

**Comment by zhangh43** [comment]
Thanks for your contribution.
There is an open PR to fix the external table as a child partition issue. See #10325
As for your PR, please wait and someone will pick and review it.

**Comment by zhangh43** [comment]
Also there are some regression test failure, You could run the make installcheck-world locally and fix the test case firstly. 
```
--- \/tmp\/build\/b235ddbb\/gpdb_src\/src\/test\/regress\/expected\/expand_table_ao\.out	2020-06-18 10:06:47.371467044 +0000
+++ \/tmp\/build\/b235ddbb\/gpdb_src\/src\/test\/regress\/results\/expand_table_ao\.out	2020-06-18 10:06:47.447473305 +0000
@@ -707,19 +708,16 @@
 (7 rows)
 
 alter table part_t1_1_prt_other_b_2_prt_2_3_prt_others_d expand table;
-ERROR:  cannot expand leaf or interior partition "part_t1_1_prt_other_b_2_prt_2_3_prt_others_d"
-DETAIL:  root/leaf/interior partitions need to have same numsegments
-HINT:  use "ALTER TABLE part_t1 EXPAND TABLE" instead
 select gp_segment_id, * from part_t1_1_prt_other_b_2_prt_2_3_prt_others_d;
  gp_segment_id | a  | b | c | d | e 
 ---------------+----+---+---+---+---
-             0 |  9 | 0 | 1 | 4 | 0
              0 | 29 | 2 | 1 | 4 | 0
              0 | 45 | 0 | 1 | 0 | 0
              0 | 65 | 2 | 1 | 0 | 0
-             1 |  5 | 2 | 1 | 0 | 1
              1 | 69 | 0 | 1 | 4 | 1
              1 | 89 | 2 | 1 | 4 | 1
+             2 |  5 | 2 | 1 | 0 | 1
+             2 |  9 | 0 | 1 | 4 | 0
 (7 rows)
 
 -- try to expand root partition, should success

======================================================================

--- \/tmp\/build\/b235ddbb\/gpdb_src\/src\/test\/regress\/expected\/expand_table_aoco\.out	2020-06-18 10:06:47.779500656 +0000
+++ \/tmp\/build\/b235ddbb\/gpdb_src\/src\/test\/regress\/results\/expand_table_aoco\.out	2020-06-18 10:06:47.823504281 +0000
@@ -689,19 +690,16 @@
 (7 rows)
 
 alter table part_t1_1_prt_other_b_2_prt_2_3_prt_others_d expand table;
-ERROR:  cannot expand leaf or interior partition "part_t1_1_prt_other_b_2_prt_2_3_prt_others_d"
-DETAIL:  root/leaf/interior partitions need to have same numsegments
-HINT:  use "ALTER TABLE part_t1 EXPAND TABLE" instead
 select gp_segment_id, * from part_t1_1_prt_other_b_2_prt_2_3_prt_others_d;
  gp_segment_id | a  | b | c | d | e 
 ---------------+----+---+---+---+---
-             0 |  9 | 0 | 1 | 4 | 0
              0 | 29 | 2 | 1 | 4 | 0
              0 | 45 | 0 | 1 | 0 | 0
              0 | 65 | 2 | 1 | 0 | 0
-             1 |  5 | 2 | 1 | 0 | 1
              1 | 69 | 0 | 1 | 4 | 1
              1 | 89 | 2 | 1 | 4 | 1
+             2 |  5 | 2 | 1 | 0 | 1
+             2 |  9 | 0 | 1 | 4 | 0
 (7 rows)
 
 -- try to expand root partition, should success
```

**Comment by uglthinx** [comment]
hi @zhangh43 , the failed test case is due to gpexpand already supporting the expansion of the leaf partitions, but the expansion of the leaf partitions in the expand_table_ao.out/expand_table_aoco.out will expect `ERROR:  cannot expand leaf or interior partition...`, I change the case and all test pass.

> There is an open PR to fix the external table as a child partition issue. See #10325
The above fix also appeared in my PR, in different ways。 I list all leaf partitions and filter external tables, these tables will be expand by `ALTER TABLE leaf_prt_table EXPAND TABLE`, thanks to this feature, we can expand the leaf partitions seperately in parallel.

**Comment by tylarb** [comment]
@uglthinx  Can you open a PR against master with this as well? It would be better to submit the PR against master and then backport to 6X if possible - otherwise, the work may actually get dropped in 7.

**Comment by uglthinx** [comment]
> @uglthinx Can you open a PR against master with this as well? It would be better to submit the PR against master and then backport to 6X if possible - otherwise, the work may actually get dropped in 7.

Hi @tylarb , please see  #10492

**Comment by kainwen** [comment]
Close this since there is a duplicated one.

**Pull request closed without merging**
