### PR TITLE
Backport SSE4.2 Runtime Logic from PostgreSQL

### PR DESCRIPTION
**Pull request by film42**
While working on getting OSX to compile, @hlinnaka made a [good point](https://github.com/film42/gpdb/commit/053715778eb91923917fb0fe589aa3c1de3fceb0) that we should backport the logic of for enabling sse 4.2 instructions.

@hlinnaka mentioned 3 points to think about when enabling SSE 4.2 in his comment:
> a) always supports SSE 4.2
> b) doesn't support SSE 4.2, or
> c) SSE 4.2 support might or might not be available at runtime, and so we need to choose at runtime

Since it didn't feel right to bundle all of this into my "Get OSX compiling" PR, I opened a new based off of master, so my OSX changes aren't included.

This PR brings 9.5 PostgreSQL's configuration for SSE 4.2 into GPDB. So now you can specify:

1. `USE_SSE42_CRC32C=1` to explicitly compile with SSE4.2 support.
2. `USE_SSE42_CRC32C_WITH_RUNTIME_CHECK=1` to compile with SSE4.2 support, but build in a runtime check that falls back to `SLICING_BY_8_CRC32C`.
3. `USE_SLICING_BY_8_CRC32C=1` to only use `SLICING_BY_8_CRC32C`.
4. Lastly, GPDB has a built in 4th option that I don't know much about `crc32cSimple`, so I left it in. I don't have the means to test this.

What this doesn't do:
1. This doesn't change how GPDB is _using_ what's in master, it just sets up a bridge from the new way to the old way. I figured that migrating to the new way, and maybe even updating some of these methods belong in the next cut, but if you don't feel the same, just leave a comment.
2. Add a license to the top of the new files. There was a copyright to a developer before, but I'm not sure what to put there since this project has a new license. Ideas?
3. Test! I was having some trouble (before this change) getting the cluster test outlined in the README running on OSX, so I'll probably need to pull down one of the sandbox images and try that way. But, I wanted to get this up before that to make sure I'm headed down the right path.

I'm sure I did a million things wrong, I don't normally spend a lot of time in C, so don't hesitate to point out anything that looks funny.

### CODE REVIEW

**Comment by ivannovick** [comment]
Hi guys,

what is impact of SS3 logic?  How does it effect the end user?  Thx!

Ivan

**Comment by ashwinstar** [comment]
Greenplum already has and used SSE for crc for xlog, n/w IO, AO table checksums, and going forward for heap checksum etc... Even before postgres used SSE gpdb was using it.

The title of the patch is little misleading, it only pulls configuration flexibility to pick and choose during compiling from postgres. Since we were till now always compiling in controlled environment we always had SSE and didn't need this config option. Shouldn't have any functionality change, I am yet to review the patch though, will post review comments once there.

**Comment by ashwinstar** [comment]
Tip on Commit Message: When pulling patches from postgres better if original patch in postgres can be pulled and applied. More often if cannot be directly applied due to differences, worth mentioning within the commit message the original postgres commit message, for this case something like 

" Modified following patch from postgres 
commit 3dc2d62d0486325bf263655c2d9a96aee0b02abe
Author: Heikki Linnakangas <heikki.linnakangas@iki.fi>
Date:   Tue Apr 14 17:05:03 2015 +0300

    Use Intel SSE 4.2 CRC instructions where available.

    Modern x86 and x86-64 processors with SSE 4.2 support have special
    instructions, crc32b and crc32q, for calculating CRC-32C. They greatly
    speed up CRC calculation.

    Whether the instructions can be used or not depends on the compiler and the
    target architecture. If generation of SSE 4.2 instructions is allowed for
    the target (-msse4.2 flag on gcc and clang), use them. If they are not
    allowed by default, but the compiler supports the -msse4.2 flag to enable
    them, compile just the CRC-32C function with -msse4.2 flag, and check at
    runtime whether the processor we're running on supports it. If it doesn't,
    fall back to the slicing-by-8 algorithm. (With the common defaults on
    current operating systems, the runtime-check variant is what you get in
    practice.)

    Abhijit Menon-Sen, heavily modified by me, reviewed by Andres Freund.
"
Helps in long run, to cross reference.

**Comment by film42** [comment]
@ashwinstar thanks for the advice! Let me go ahead and update my commit messages with a reference to PostgreSQL's commits. The thing is, the change in `configure.in` was copied directly, and I grabbed some of the cpu check stuff for choosing at runtime, but the actual SSE code is the same as before; only the file structure was copied. Now though, we can pretty easily swap out GPDB's implementation for PostgreSQL's later on.

Anyways, I'll update the commit message with a reference because that does communicate a lot more than nothing at all :)

**Comment by film42** [comment]
@ashwinstar Done. I updated the patch with relevant commit messages. I also realized I had not updated the win32 config, so I went ahead and did that as well.

**Comment by hlinnaka** [comment]
Great, thanks! This is definitely going in the right direction. I think we should take this one step further:
* Pick all the new files, src/port/pg_crc32c_*.c and src/include/port/pg_crc32c.h from the upstream, without any modifications. This will make diffing and merging with upstream easier in the future.
* replace all references to the old crc32c() etc. functions with the PostgreSQL versions, i.e. COMP_CRC32C().

**Comment by film42** [comment]
@hlinnaka Perfect. I was worried about taking too big of an initial cut, but I'll keep the commit history clean so it will be easier to review. I'll get on it.

**Comment by film42** [comment]
Looks like I'm going to cleanup some merge conflicts, but I think I covered everything. I'm _trying_ to run the tests (and they seem to be running as well as master). Following the README did not work and I ended up using @hlinnaka 's approach. Here's master (without my commits) vs this branch. The same gp tests are failing: https://gist.github.com/film42/4513c96727ac7129526e

**Comment by hlinnaka** [comment]
Looks pretty good. The commit message of the first commit lists the same upstream commit twice. Also, the commit also includes the follow-up fixes from b4eb2d168d2c426978a02de8b9b6ccdb85e1b442; would be good to mention that in the commit message too.

There are some unrelated whitespace fixes in contrib/xlogdump. While probably a good idea per se (except maybe if it makes the diff against the upstream xlogdump utility larger, i.e. if the upstream has the same whitespace issues), would be good to do it in a separate commit.

Can you rebase this and squash the two commits into one, please? After that, and tidying up the commit message per above, I think this is read for merging.

**Comment by film42** [comment]
Fixed the white space issue, squashed and renamed the commits and rebased against master. The merge was not super simple so hopefully I didn't mess anything up. Travis is building so that's a pretty good sign :).

**Comment by hlinnaka** [comment]
Ok, pushed, with some further cleanups:

* You added a TODO comment wrt. using EQ_CRC32C() vs EQ_LEGACY_CRC32(). I resolved that by switching over to EQ_CRC32C(), in that place and many others. They both just do "(a) == (b)", so it doesn't make a difference to the compiled code, but for clarity we should try to use EQ_CRC32C() when comparing CRC-32C values.

* removed some whitespace changes

* I removed the code to handle legacy CRCs in WAL from xlogdump and xlogviewer, and also removed gpmodcontrol.c. I removed similar code from the backend and pg_resetxlog and pg_controldata earlier already, but missed these.

* Fixed some further whitespace issues

* Removed some unnecessary #includes.

* Updated the Makefile of pg_controldata and pg_resetxlog to not link in the legacy pg_crc.c code anymore. It's not needed. (these was more leftovers from my earlier removal of the legacy WAL CRC calculation).

Many thanks for the patch!

**Comment by film42** [comment]
@hlinnaka Thanks for all of your help! This was the biggest open source patch I've ever worked on, so I really appreciate you walking me through these changes. You made the experience super fun. Thanks again! :)

**Pull request closed without merging**
