### PR TITLE
Init plan with input param follow upstream execution flow

### PR DESCRIPTION
**Pull request by weinan003**
In gpdb, we pre-execute init plan in ExecutorStart to reduce slice number.
However, for some initplan, which require params from same level node,
should follow upstream execution flow.

To recognize this initplan's pattern, record `extParam` when creating
`subplan` object.

Fix issue: #6953

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by pengzhout** [comment]
Hi @weinan003, @paul-guo- mentioned in the issue that it might be related to the Lateral join, for example
```
select sub1.* from int8_tbl, lateral(select (select int8_tbl.q2) sub2) sub1;
```
it has almost the same plan as the test case added in this PR, it can be executed without this PR, can you help to dig more: is it related to lateral? and why lateral didn't fail when they have the same plan, is it possible to fix this as a later way? Thanks.

**Comment by weinan003** [comment]
> Hi @weinan003, @paul-guo- mentioned in the issue that it might be related to the Lateral join, for example
> 
> ```
> select sub1.* from int8_tbl, lateral(select (select int8_tbl.q2) sub2) sub1;
> ```
> 
> it has almost the same plan as the test case added in this PR, it can be executed without this PR, can you help to dig more: is it related to lateral? and why lateral didn't fail when they have the same plan, is it possible to fix this as a later way? Thanks.

I do not understand why this query can get the correct result yet. I believe the reason is relevant to `select int8_tbl.q2`
Because, I find out ```select * from int8_tbl, lateral(select (select int8_tbl) sub2) sub1;``` 
This query ought to be more like the issue one, and it will be failed as the same reason. 

However, maybe it is a new perspective to think about the crash reason. I will study your query and update later

**Comment by pengzhout** [comment]
Take another look, before processing an initplan, any PARAM that affects this plan should be evaluated firstly, otherwise, an initplan can not be pre-processed. extParam contains the dependency of PARAMs, if extParam is missing, ExecEvalParamExec(&isNull) on a not-evaluated PARAM will return a null datum, however, isNull is not set to false which is inconsistent, some operators can happen to handle the inconsistent (the lateral case), some cannot (you case).

**Comment by pengzhout** [comment]
so overall, I think your fix is doing the right thing to bring back the PARAM dependency.

**Comment by pengzhout** [comment]
@weinan003 do we need to consider query_level as old code logic did?

**Comment by weinan003** [comment]
> @weinan003 do we need to consider query_level as old code logic did?

You a right, I should remove uplevel params from `extParam`. A new commit attached

**Pull request merged**
