### PR TITLE
Cherry-pick Daniel Gustafsson commit to fix tablefunc extension build 

### PR DESCRIPTION
**Pull request by reshke**
The orig commit message follows: 

The tablefunc contrib module lacked the upstream Makefile and test- data. Re-add the upstream files and also add an variable output rule to the regress init_file to make it build and test green.

The extra REGRESS_OPTS flag added to the Makefile can be removed once we can add a single init_file handling for all PGXS modules, but the pipeline is currently not supporting that.

Reviewed-by: Hubert Zhang

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [x] Document changes
- [x] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [x] Review a PR in return to support the community

### CODE REVIEW

**Comment by soumyadeep2007** [comment]
@beeender will you be looking to help review this in this quarter?

**Comment by soumyadeep2007** [comment]
@liuxueyang  Can you review this sometime soon if you have some cycles to spare?

**Review by liuxueyang — APPROVED** [review]

**Comment by liuxueyang** [comment]
Please do not merge currently. I need to look into this extension a bit more.

**Comment by liuxueyang** [comment]
This extension provides some [UDFs](https://www.postgresql.org/docs/current/tablefunc.html) to produce "pivot table". I added `distributed by` when `CREATE TABLE` in the test case. And I think there are no other modifications needed for gpdb.

**Comment by liuxueyang** [comment]
LGTM

**Comment by kainwen** [comment]
@liuxueyang before pushing this, can you please help:

1. have rebase it in your local branch and test the full CI using dev pipeline
2. verify that the related test case of `tablefunc` will run

Thanks a lot!

**Comment by ashwinstar** [comment]
Yes, PR pipeline doesn't seem to run the tablefunc test. Maybe we need change to GNUMakefile.in as well?

**Comment by liuxueyang** [comment]
The regress test for `tablefunc` can be run currently. Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-lxueyang-rocky8/jobs/icw_planner_icproxy_rocky8/builds/1

**Pull request merged**
