### PR TITLE
Remove checkinc script and Makefile target

### PR DESCRIPTION
**Pull request by danielgustafsson**
The checkinc.py script was performing a check for the presence of
header files we're not shipping.  This was essentially guaranteed
to always pass as the code was able to compile, and has generally
provided little value.  Recent changes in macOS installations has
also made it fail with false positives, so finally remove it to
minimize developer time spent fighting quite useless tests.

Any checks for headers should be performed in autoconf before the
code is compiled, not during testing.

Discussion: https://github.com/greenplum-db/gpdb/issues/7961
https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/cCXsHwPr7GM/XbExPStmAgAJ

### CODE REVIEW

**Comment by danielgustafsson** [comment]
> On 1 Jul 2019, at 17:36, Ashwin Agrawal <notifications@github.com> wrote:
> 
> @ashwinstar approved this pull request.
> 
> LGTM. Not sure what failed in the pipeline.


The failure was unrelated to the change, it got stuck on the bitmap.h warning that I emailed gpdb-dev@ about (and which Georgios opened a PR for today)

**Comment by danielgustafsson** [comment]
Pushed to master, thanks!

**Comment by lavjain** [comment]
Can this PR be back-ported to 6X_STABLE as well as 5X_STABLE?

**Comment by danielgustafsson** [comment]
> On 1 Aug 2019, at 20:10, Lav Jain <notifications@github.com> wrote:
> 
> Can this PR be back-ported to 6X_STABLE as well as 5X_STABLE?

I don’t think that would be a big problem.

**Pull request closed without merging**
