### PR TITLE
Refactor s3ext codes

### PR DESCRIPTION
**Pull request by adam8157**
This refactor is done because of two major reasons:
1, s3ext download actual data from Amazon S3 server in unit tests before this, which took hours, that's not acceptable for fast feedback development.
2, it was not flexible, introducing new features would become difficult.

To fix it, refactor codes introduce google mock for unit tests, and separates functions into different classes, unifies them by the same interface, also it contains many misc optimizations. After this, we could easily add new features and get feedback very quickly.

### CODE REVIEW

**Comment by adam8157** [comment]
Thanks to @yydzero @kuien @HaozhouWang and @pf-qiu 's great works.

**Comment by danielgustafsson** [comment]
Google Test is available packaged, why vendor it into our tree rather than rely on it as on outside library?

**Comment by adam8157** [comment]
Is there a way to fix a git submodule to certain tag/commit?

Google Test and Mock don't provide branches, and their latest codes are not supported by our building toolchain.

**Comment by adam8157** [comment]
Pushed manually to keep commits separated.

**Comment by ashwinstar** [comment]
On Thu, Jun 23, 2016 at 5:55 AM, Adam Lee <notifications@github.com> wrote:

> Is there a way to fix a git submodule to certain tag/commit?
>
Sorry for being late to get to it. git submodule definitely just tracks *a*
commit so I believe something like *git checkout <specific_tag>* in the
submodule directory you wish to connect followed by *git add *should serve
the purpose ?

Google Test and Mock don't provide branches, and their latest codes are not
> supported by our building toolchain.
>

**Comment by adam8157** [comment]
Cool, thanks! Will do that once the commit to use is confirmed(a little tricky because googlemock were merged into googletest after it broke old g++)

**Pull request closed without merging**
