### PR TITLE
Use versioned_file for gp-internal-artifacts

### PR DESCRIPTION
**Pull request by bradfordboyle**
The build artifacts in gp-internal-artifacts are not immutable. If
`regexp` is used when fetching the resource, then new builds (with the
same version) are not detected. This means that fixes in the packaging
may not be correctly picked up by a pipeline.

Authored-by: Bradford D. Boyle <bboyle@pivotal.io>

### CODE REVIEW

**Comment by pivotal-ning-yu** [comment]
@zhangh43 FYI

**Comment by BaiShaoqi** [comment]
libquicklz, libquicklz-devel, sigar  does not bump their  version often, reasonable to make them get by version intead of regex. 
recently gp-releng change compiling code for libquicklz to add extra optimizer, but did not bump version, need this pr merge in to make the compiling extra optimizer effective in  pipeline, if I understand correctly in the case.

**Comment by zhangh43** [comment]
@bradfordboyle  please also backport to 6X. We need to test the new 6X release candidate.

**Comment by bradfordboyle** [comment]
> @bradfordboyle please also backport to 6X. We need to test the new 6X release candidate.

Here is the commit on 6X_STABLE: https://github.com/greenplum-db/gpdb/commit/4006565dacb7f60bf1e87cac1d7048dc112c4b4a

**Pull request merged**
