### PR TITLE
Support max_slot_wal_keep_size in Greenplum 7

### LINKED ISSUE #12007: Support max_slot_wal_keep_size GUC in Greenplum 7
This is a request for a feature that is already present in Greenplum 6: https://github.com/greenplum-db/gpdb/pull/11908.  It was pulled in from PostgreSQL 13.  Let's use this issue to track its development in Greenplum 7.

There should be a way to limit the WAL retained by a primary segment when its mirror falls behind or disconnects.

### PR DESCRIPTION
**Pull request by l-wang**
### The goal:

Support `max_slot_wal_keep_size` GUC in Greenplum 7. It should work the same way as in Postgres 13 where the feature was introduced.

Fixes #12007

Commits in this PR are divided into three categories:

### Cherry-picked the following upstream commits:
624e6d41a1039e5e409948b6a6d4f5a043ba0fa4 Introduce timed waits for condition variables.
c6550776394e25c1620bc8258427c8f1d448080d Allow users to limit storage reserved by replication slots
9e9abed746280086474e2191b8c399b5fd9b0678 Remove testing for precise LSN/reserved bytes in new TAP test
e083fa34ced0d53807a57482048bb4c135c3d006 Further stabilize results of 019_replslot_limit.pl.
1816a1c6ffe46782eee9a16a974b4aa3f4b8457b Fix checkpoint signalling
08aa3151e7308556130c644c237fa4b20dfd6eba Fix issues in invalidation of obsolete replication slots.
411493d701e2f97e778dc1ff14fb7169eea2e94c Add parens to ConvertToXSegs macro
12e52ba5a76e56aacdfbbb269e6b45c53d80c477 Save slot's restart_lsn when invalidated due to size
6f7a862bed3a49283c74c0adf207172002e3e03c Adjust max_slot_wal_keep_size behavior per review
3b4b541777f0b85df7626623ef78df0ea48ca5dc Persist slot invalidation correctly
c54b5891f415df36809de1aeb97e4574d5456d69 Morph pg_replication_slots.min_safe_lsn to safe_wal_size
794e8e32bb5ae1b38a90cbae2a88895633797599 Fix uninitialized value in segno calculation
46d2cffcf106b9a5b6d5b6c7ead38b5e88e7c2c4 Rename wal_keep_segments to wal_keep_size.
218b101008b533156d7e5832fe143d1e04a01301 Fix race condition in invalidating obsolete replication slots
866237a6fa01a128325df41ad39b41ea3363c9a9 Advance old-segment horizon properly after slot invalidation
568439ff0461336d8ec8770d664ca2e58477b43f Make new replication slot test code less racy
788e6b0fc881a36f5a13fb3af706ba6a63696469 Make new replication slot test code even less racy
4b134172649b9ef395f671e53e4913249966588b Close yet another race condition in replication slot test code
36eeb37cd611c0a0bfb5743d9ddbef8f04fc87f3 Ignore invalidated slots while computing oldest catalog Xmin

### Cherry-picked the following 6X_STABLE commits:
3b153496aed26689b313d8df8be847b2e8a47a25 Speed up max_slot_wal_keep_size isolation2 test (PS: for test only)
74a2cec7ed976c61ea8b6b2338c4491feb859a4e Do not remove WAL that is needed for database operation (PS: for code cleanup and test only)
0f2d65f497245eb00b5fc544cf609e79ddd75226 Confine Greenplum-specific WAL replication behavior to coordinator
e4ec851b151267fe3209af6804e438611836a875 Fix KeepLogSeg() unittest
0f9053f63ea4fa405f6ce07acbd26e15fc999b9f Avoid indefinite blockage in CI due to walsnd_skip_send fault
2493d6339499806a279b2fbfd3527df186ac9f47 Mirror is up only if it has received WAL

### Adjust tests for 7X:
03a14bb4ac346c7b274e94c14dd68f5237b35f62 Modify 019_replslot_limit.pl test for Greenplum (We need this due to Greenplum replication slot `restart_lsn` assignment variation introduced by commit 055c57dd7017059eb527a9e40e311897fca2cbc1)
0fcd40f2503c01aab829118ca25e2b009a068b8d Update max_slot_wal_keep_size test to accommodate 7X (post picking 6X commit 3b15349)
fdf82e7efecdeca5b1ea9efa9bf607971669cafe Update max_slot_wal_keep_size isoloation2 test to accommodate 7X (post picking 6X commit 93c579a4.)
(I plan to squash the above two commits but for now have them seperate for reviewers' convenience)

### Notes for reviewers:

- Catalog changes: two additional fields `wal_status` and `safe_wal_size` in built-in function `pg_get_replication_slots()` and system view `pg_replication_slots`. (`active_pid` is also new in 7X. It was introduced prior to this PR but 6X does not have it.)
- `wal_keep_segments` is renamed to `wal_keep_size` so that it has the same unit (default in MB) as `max_slot_wal_keep_size` (PG13 commit 46d2cffcf106b9a5b6d5b6c7ead38b5e88e7c2c4). This is different from 6X.
- Same as 6X, the GUC as of now is only applicable for primary/mirror pairs but not coordinator/standby pairs. (see 6X commit 0f2d65f) Once we have auto fail-over utility in-place (read: if we automate creating and managing an internal replication slot between coordinator and standby) we can get rid of this confinement. 
- 6X commit 74a2cec7ed976c61ea8b6b2338c4491feb859a4e was picked only for code cleanup and test coverage. The test behavior has changed because 7X no longer needs to keep additional PREPARE wal record.

### CODE REVIEW

**Comment by l-wang** [comment]
As I'm working through this, I noticed upstream renamed `wal_keep_segments` to `wal_keep_size` in commit https://github.com/postgres/postgres/commit/f5dff45962ec0a0daad443e45811d6c426be1237

As the commit message stated:
> max_slot_wal_keep_size that was added in v13 and wal_keep_segments are
the GUC parameters to specify how much WAL files to retain for
the standby servers. While max_slot_wal_keep_size accepts the number of
bytes of WAL files, wal_keep_segments accepts the number of WAL files.
This difference of setting units between those similar parameters could
be confusing to users.
>
> To alleviate this situation, this commit renames wal_keep_segments to
wal_keep_size, and make users specify the WAL size in it instead of
the number of WAL files.
>
>There was also the idea to rename max_slot_wal_keep_size to
max_slot_wal_keep_segments, in the discussion. But we have been moving
away from measuring in segments, for example, checkpoint_segments was
replaced by max_wal_size. So we concluded to rename wal_keep_segments
to wal_keep_size.
>
>Back-patch to v13 where max_slot_wal_keep_size was added.

I'm considering cherry-picking this commit as well. 

Pros:
- As stated in the above message having two GUCs using same unit makes more sense for users.
- Makes backporting easier because both GUCs are used in the same area of code and serves similar purposes
- Makes future merge easier

Cons:
- 6X we have only backported `max_slot_wal_keep_size` but did not rename `wal_keep_segments`. (Not sure if this is actually a con but 6X users need to be aware of this change after they upgrade to 7X)
- Greenplum modified default value for `wal_keep_segments` so we need to make sure doing the due diligence of making the same adjustments.

**Comment by soumyadeep2007** [comment]
> I'm considering cherry-picking this commit as well.
> 
> Pros:
> 
> * As stated in the above message having two GUCs using same unit makes more sense for users.
> * Makes backporting easier because both GUCs are used in the same area of code (AND TESTS) and serves similar purposes
> * Makes future merge easier
> 
> Cons:
> 
> * 6X we have only backported `max_slot_wal_keep_size` but did not rename `wal_keep_segments`. (Not sure if this is actually a con but 6X users need to be aware of this change after they upgrade to 7X)
> * Greenplum modified default value for `wal_keep_segments` so we need to make sure doing the due diligence of making the same adjustments.

Thanks for clearly articulating the pros and cons of the backport.  Here are my thoughts:
* `wal_keep_segments` isn't used a great deal by our customers. GPDB is more reliant on replication slots for reserving WAL and `wal_keep_segments` is the old way of doing reservation.
* We should do the name change and preserve the default value.
* Customers have to pay the upgrade cost some day anyway and there is not a lot of cost, given how it is used.

So, all in all I favor the backport of this commit since it adds consistency and makes our lives easier. We will have to ensure that docs gets udpated.

**Comment by l-wang** [comment]
> Thanks for clearly articulating the pros and cons of the backport. Here are my thoughts:
> 
> * `wal_keep_segments` isn't used a great deal by our customers. GPDB is more reliant on replication slots for reserving WAL and `wal_keep_segments` is the old way of doing reservation (predates replication slots).
> * We should do the name change and preserve the default value.
> * Customers have to pay the upgrade cost some day anyway and there is not a lot of cost, given how it is used.
> 
> So, all in all I favor the backport of this commit since it adds consistency and makes our lives easier. We will have to ensure that docs gets udpated.

Thank you @soumyadeep2007 for the input. I agree with you. I will include this commit in this PR.

**Comment by l-wang** [comment]
I'm looking into the test failure. We may need commit https://github.com/greenplum-db/gpdb/commit/0ed57a6817e236a52b80ca6d2ad4f4e6bf539643 after all.

**Comment by l-wang** [comment]
Apologies for the force push. I was hoping to trigger CI by resolving that catversion merge conflict, but looks like CI is still not triggered.

**Review by huansong — APPROVED** [review]
LGTM! Great thorough work.

**Comment by l-wang** [comment]
Thank you @huansong for reviewing!

**Pull request merged**
