### PR TITLE
Generic index apply transform for 6X

### PR DESCRIPTION
**Pull request by zellerh**
This is a backport of PR #10711.
 
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by chrishajas — APPROVED** [review]
LGTM. Also need to fix the comment syntax (same issue that occurred on master).

**Comment by d** [comment]
Hmm, did we run unit tests locally? It's failing in Concourse

**Comment by zellerh** [comment]
> Hmm, did we run unit tests locally? It's failing in Concourse

I ran ctest on the debug version, which passed. Looks like this is one of those rare cases that fail in the release build only. Hope to have a fix later today, so that I can re-submit the master PR. I'll keep this one on hold until the new master PR has been merged.

**Comment by zellerh** [comment]
Need to make modifications to the PR on the master branch. Closing this for now, will resubmit once the master PR is ok.

**Pull request closed without merging**
