### PR TITLE
Remove dead code from catalog.py

### PR DESCRIPTION
**Pull request by danielgustafsson**
While looking at other things, spotted that there were quite a few functions in catalog.py that were unused. Remove these, and also remove imports of gppylib.db.catalog when unused.

I'm far from a Python hacker so I might be off in the weeds completely here, clues are warmly welcomed.

### CODE REVIEW

**Comment by ashwinstar** [comment]
LGTM.

**Comment by ashwinstar** [comment]
Can we merge this in and close-out ?

**Comment by danielgustafsson** [comment]
It's on my TODO. I rebased it the other day but got stuck on other things.

**Comment by danielgustafsson** [comment]
Merged to master, thanks for review

**Pull request merged**
