### PR TITLE
Free disk space for truncated/dropped relations on commit

### PR DESCRIPTION
**Pull request by darthunix**
Originally the problem was detected on GPDB 6.15.0 with a mix usage of heap and AO/AOC tables. ETL process made intensive inserts in a highly skewed heap table with a final truncate command. Because of a big skew, the most of repeatedly inserted (about 100GB) data was located on a single segment and heap table blocks occupied all the shared buffers on that segment (default 125MB). In parallel another backend (AO backend) on the same segment executed a very long running slice with lots of hash aggregates populated from AO table with deleted rows. Because of deleted rows, AO backend had to validate tuples visibility with an auxiliary visibility map table and evict heap table's blocks to disk. As a result, AO backend's file descriptor cache contains all segment files descriptors of the heap table. When ETL backend truncates heap table it puts a system cache invalidation messages to shared memory and daisy chains an invalidation signal to the active backends. A backend invalidates a cache immediately if it is idle, otherwise backend waits till current command in transaction finishes. But our long running AO backend works on its command for hours and can't invalidate file descriptor cache - so, still holds all segment files descriptors.

Before this commit, "truncate" command shrank to a zero size only the first segment file before unlinking, but higher segments were unlinked without shrink. Because of such slow-running queries with stuck file descriptors, kernel can't free the space on disk immediately after successful unlink (waits till the file descriptor would be closed). As a result we can easily run out of disk space, when ETL repeats 100GB insert + truncate cycle. Surely, original problem has workarounds (replace heap with AO as the simplest one), but anyway, I believe this behaviour should be fixed.

Current PR is a backport of upstream PostgreSQL [commit](https://github.com/postgres/postgres/commit/9f35f943732eaf9121a107f54ea043925e9a5d7b). It should be backported to `6X_STABLE` as well.

### CODE REVIEW

**Comment by darthunix** [comment]
I am surprised that current PR doesn't run any CI tests (though I've made a force push to the branch). What is the reason for it?

**Comment by maksm90** [comment]
> Because of deleted rows, AO backend had to validate tuples visibility with an auxiliary visibility map table and evict heap table's blocks to disk. As a result, AO backend's file descriptor cache contains all segment files descriptors of the heap table.

This point looks not so evident. Could you confirm the this empirically, e.g, by `lsof` output from problem backends?

**Comment by darthunix** [comment]
@maksm90 ok, here is some information from internal JIRA ticket. An affected heap table owned relfilenode `337480361` and `337541414` (in fact `lsof` showed more relfilenodes, but I give here only these two for short). Both of these relfilenodes were unlinked in heap backend, but still occupy disk space as AO backend didn't close their file descriptors:
```
$ lsof -p 96677 | grep /data1/primary/gpseg6/base/
postgres 96677 gpadmin   26u   REG        8,4          0 6466659926 /data1/primary/gpseg6/base/760727/337480361 (deleted)
postgres 96677 gpadmin   27u   REG        8,4 1073741824 6443426966 /data1/primary/gpseg6/base/760727/337480361.1 (deleted)
postgres 96677 gpadmin   28u   REG        8,4 1073741824 6497588801 /data1/primary/gpseg6/base/760727/337480361.2 (deleted)
postgres 96677 gpadmin   29u   REG        8,4 1073741824 6513231960 /data1/primary/gpseg6/base/760727/337480361.3 (deleted)
...
postgres 96677 gpadmin   78u   REG        8,4  924221440 6523901158 /data1/primary/gpseg6/base/760727/337480361.50 (deleted)
...
postgres 96677 gpadmin  285u   REG        8,4          0 6450670968 /data1/primary/gpseg6/base/760727/337541414 (deleted)
postgres 96677 gpadmin  286u   REG        8,4 1073741824 6443136513 /data1/primary/gpseg6/base/760727/337541414.1 (deleted)
postgres 96677 gpadmin  287u   REG        8,4 1073741824 6527213314 /data1/primary/gpseg6/base/760727/337541414.2 (deleted)
...
postgres 96677 gpadmin  342u   REG        8,4 1073741824 6443412674 /data1/primary/gpseg6/base/760727/337541414.50 (deleted)
...

$ lsof -p 96677 | grep /data1/primary/gpseg6/base/ | grep deleted | wc -l
302
```
So, in a current example we have about 300GB of unlinked heap segments waiting AO backend to finish its command and invalidate cache.

I have also played with debugger on AO backend and detected the moment when we evicted heap table's block from shared buffers to load visibility map's block:
```
#0  mdwrite (reln=0x38b0f08, forknum=MAIN_FORKNUM, blocknum=202274, buffer=0x39fcff8 "}\344\001", skipFsync=0 '\000') at md.c:820
#1  0x0000000000a7d769 in smgrwrite (reln=<optimized out>, forknum=<optimized out>, blocknum=<optimized out>, buffer=<optimized out>, skipFsync=<optimized out>) at smgr.c:543
#2  0x0000000000a4c30b in FlushBuffer (buf=0x7f920fa07640, reln=<optimized out>) at bufmgr.c:2187
#3  0x0000000000a4ebba in BufferAlloc (foundPtr=<synthetic pointer>, strategy=<optimized out>, blockNum=<optimized out>, forkNum=<optimized out>, relpersistence=<optimized out>, smgr=<optimized out>) at bufmgr.c:814
#4  ReadBuffer_common (smgr=<optimized out>, relpersistence=<optimized out>, forkNum=forkNum@entry=MAIN_FORKNUM, blockNum=<optimized out>, blockNum@entry=1, mode=mode@entry=RBM_NORMAL, strategy=strategy@entry=0x0, hit=hit@entry=0x7ffd66efbc60 "") at bufmgr.c:426
#5  0x0000000000a4f576 in ReadBufferExtended (strategy=0x0, mode=RBM_NORMAL, blockNum=1, forkNum=MAIN_FORKNUM, reln=0x7f92d407e950) at bufmgr.c:339
#6  ReadBuffer (blockNum=1, reln=0x7f92d407e950) at bufmgr.c:271
#7  ReleaseAndReadBuffer (buffer=buffer@entry=43, relation=relation@entry=0x7f92d407e950, blockNum=1) at bufmgr.c:1206
#8  0x00000000007226ff in _bt_relandgetbuf (rel=rel@entry=0x7f92d407e950, obuf=43, blkno=blkno@entry=1, access=access@entry=1) at nbtpage.c:719
#9  0x00000000007277bd in _bt_search (rel=rel@entry=0x7f92d407e950, keysz=keysz@entry=2, scankey=0x7ffd66efbeb0, nextkey=1 '\001', bufP=bufP@entry=0x7ffd66efbda0, access=access@entry=1) at nbtsearch.c:131
#10 0x0000000000727fee in _bt_first (scan=scan@entry=0x3a0a768, dir=dir@entry=BackwardScanDirection) at nbtsearch.c:940
#11 0x0000000000726046 in btgettuple (fcinfo=<optimized out>) at nbtree.c:527
#12 0x0000000000beaff2 in FunctionCall2Coll (flinfo=flinfo@entry=0x3a1b7e8, collation=collation@entry=0, arg1=arg1@entry=60860264, arg2=arg2@entry=-1) at fmgr.c:1340
#13 0x000000000071e9e7 in index_getnext_tid (direction=BackwardScanDirection, scan=0x3a0a768) at indexam.c:462
#14 index_getnext (scan=scan@entry=0x3a0a768, direction=direction@entry=BackwardScanDirection) at indexam.c:602
#15 0x000000000078682a in AppendOnlyVisimapStore_GetNextTuple (visiMapStore=<optimized out>, scanDirection=BackwardScanDirection, indexScan=0x3a0a768) at appendonly_visimap_store.c:250
#16 AppendOnlyVisimapStore_GetNext (tupleTid=0x39e335a, visiMapEntry=0x39e3338, scanDirection=BackwardScanDirection, indexScan=0x3a0a768, visiMapStore=0x39e3368) at appendonly_visimap_store.c:280
#17 AppendOnlyVisimapStore_Find (visiMapStore=visiMapStore@entry=0x39e3368, segmentFileNum=1, firstRowNum=4751360, visiMapEntry=visiMapEntry@entry=0x39e3338) at appendonly_visimap_store.c:212
#18 0x0000000000784d61 in AppendOnlyVisimap_Find (aoTupleId=0x7ffd66efd600, visiMap=0x39e3330) at appendonly_visimap.c:169
#19 AppendOnlyVisimap_IsVisible (visiMap=visiMap@entry=0x39e3330, aoTupleId=aoTupleId@entry=0x7ffd66efd600) at appendonly_visimap.c:210
#20 0x0000000000789ac9 in aocs_getnext (scan=0x39e32b0, direction=<optimized out>, slot=slot@entry=0x39e3050) at aocsam.c:712
#21 0x00000000008ed48c in SeqNext (node=node@entry=0x39e3690) at nodeSeqscan.c:76
#22 0x00000000008cd7b6 in ExecScanFetch (recheckMtd=0x8ed430 <SeqRecheck>, accessMtd=0x8ed440 <SeqNext>, node=0x39e3690) at execScan.c:84
#23 ExecScan (node=0x39e3690, accessMtd=0x8ed440 <SeqNext>, recheckMtd=0x8ed430 <SeqRecheck>) at execScan.c:154
#24 0x00000000008ed4ef in ExecSeqScan (node=<optimized out>) at nodeSeqscan.c:130
#25 0x00000000008c0048 in ExecProcNode (node=node@entry=0x39e3690) at execProcnode.c:1001
#26 0x00000000008e10f3 in ExecHashJoinOuterGetTuple (hashvalue=0x7ffd66efd770, hjstate=0x39e0fe8, outerNode=0x39e3690) at nodeHashjoin.c:822
#27 ExecHashJoin_guts (node=node@entry=0x0) at nodeHashjoin.c:287
#28 ExecHashJoin (node=node@entry=0x39e0fe8) at nodeHashjoin.c:514
#29 0x00000000008bff28 in ExecProcNode (node=node@entry=0x39e0fe8) at execProcnode.c:1078
#30 0x00000000008fe0fc in execMotionSender (node=0x38e95b8) at nodeMotion.c:295
#31 ExecMotion (node=node@entry=0x38e95b8) at nodeMotion.c:252
#32 0x00000000008bfe88 in ExecProcNode (node=node@entry=0x38e95b8) at execProcnode.c:1121
#33 0x00000000008b7925 in ExecutePlan (estate=estate@entry=0x38e7de8, planstate=0x38e95b8, operation=operation@entry=CMD_SELECT, sendTuples=sendTuples@entry=0 '\000', numberTuples=numberTuples@entry=0, direction=direction@entry=ForwardScanDirection, 
    dest=dest@entry=0x7f920f0775f8) at execMain.c:2977
#34 0x00000000008b84aa in ExecutePlan (dest=0x7f920f0775f8, direction=ForwardScanDirection, numberTuples=0, sendTuples=0 '\000', operation=CMD_SELECT, planstate=<optimized out>, estate=0x38e7de8) at execMain.c:2943
#35 standard_ExecutorRun (queryDesc=0x38d8b58, direction=ForwardScanDirection, count=0) at execMain.c:935
#36 0x0000000000a87869 in ProcessQuery (portal=portal@entry=0x38e5dd8, stmt=stmt@entry=0x3772490, params=<optimized out>, dest=dest@entry=0x7f920f0775f8, completionTag=completionTag@entry=0x7ffd66efdca0 "", sourceText=<optimized out>) at pquery.c:288
#37 0x0000000000a87ced in PortalRunMulti (portal=portal@entry=0x38e5dd8, isTopLevel=isTopLevel@entry=1 '\001', dest=dest@entry=0x7f920f0775f8, altdest=altdest@entry=0x7f920f0775f8, completionTag=completionTag@entry=0x7ffd66efdca0 "") at pquery.c:1473
#38 0x0000000000a89181 in PortalRun (portal=<optimized out>, count=9223372036854775807, isTopLevel=<optimized out>, dest=0x7f920f0775f8, altdest=0x7f920f0775f8, completionTag=0x7ffd66efdca0 "") at pquery.c:1018
#39 0x0000000000a81938 in exec_mpp_query (
    query_string=0x38d2c44 "INSERT INTO reconciliation.commissions_details(operation_id,user_id,instrument,close_at,balance_currency,user_balance_type,commission_type,com_usd,com_local,com_usd_converted,exchange_diff,loaded_at,d"..., serializedQuerytree=<optimized out>, 
    serializedQuerytreelen=<optimized out>, serializedPlantree=<optimized out>, serializedPlantreelen=<optimized out>, serializedParams=<optimized out>, serializedParamslen=28, serializedQueryDispatchDesc=0x38d4637 "(\265/\375`UJ5k", serializedQueryDispatchDesclen=3440)
    at postgres.c:1367
#40 0x0000000000a86a0d in PostgresMain (argc=<optimized out>, argv=argv@entry=0x37c1498, dbname=0x37517e0 "reporting", username=<optimized out>) at postgres.c:5388
#41 0x00000000006c46d3 in BackendRun (port=0x3776cc0) at postmaster.c:4811
#42 BackendStartup (port=0x3776cc0) at postmaster.c:4468
#43 ServerLoop () at postmaster.c:1948
#44 0x0000000000a0dd17 in PostmasterMain (argc=argc@entry=5, argv=argv@entry=0x374f650) at postmaster.c:1518
#45 0x00000000006c96db in main (argc=5, argv=0x374f650) at main.c:245
```

**Review by zhangh43 — APPROVED** [review]
Understand the case. Thanks for the contribution:)
Upstream also back-ported this commit to all the supported versions. I think it's OK to merge it.

**Comment by ashwinstar** [comment]
Master branch version looks fine.
Need to be careful while back-porting this to GPDB6 as `mdunlink()` is used by heap/AO/AOCO there.

**Comment by darthunix** [comment]
@ashwinstar should we truncate AO/AOCO segment files before unlinking in `mdunlink_ao()` function as well? I  think it is possible that they can stuck in some backend's cache with long-running command as well.

**Comment by asimrp** [comment]
Thanks @darthunix for the detailed explanation and the back port. 

 > should we truncate AO/AOCO segment files before unlinking in mdunlink_ao() function as well? I think it is possible that they can stuck in some backend's cache with long-running command as well.

It is not easy to see how that can happen.  AO tables don't use shared buffers, so it is not possible for a backend to open an unrelated AO table's segment file just for the purpose of evicting it.  Ideally, if a backend process has a AO segment file open, it should also hold a lock on it, making concurrent unlink of the file impossible.  May be vacuum, which can drop a segment file that it thinks is no longer needed, could cause problems?

**Comment by darthunix** [comment]
> It is not easy to see how that can happen

But we can imagine a long living backend (`backend1`), processing multiple transactions through its lifetime. In the first transaction it can insert data to some AO segment. Then `backend1` commits this transaction and releases the lock, but its file cash still has the file descriptor of this segment. Then `backend1` executes some long running command (`pg_sleep()` or huge aggregate) and ignores cache invalidation messages from other backends. If some other backend (`backend2`) in parallel locks the same segment for insert, populates it with data and tries to unlink, we face the same problem, right?

**Comment by darthunix** [comment]
I have detected the same problem for AO/AOCO tables as well. Steps to reproduce on demo cluster
```
create function seg_sleep() returns void as $$select pg_sleep(1000000);$$ language sql execute on all segments;  
create table ta(a int) with (appendoptimized=true) distributed by (a);

1: select gp_segment_id, relfilenode from gp_dist_random('pg_class') where oid = 'ta'::regclass;
-- relfilenode = 16499
1: insert into ta values (1), (2), (5);
1: select seg_sleep();

% lsof -p 62588 | grep base | grep 16499
postgres 62588 darthunix    6u    REG                1,4       32           128608335 /Users/darthunix/git/gpdb_master/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/base/16384/16499.1
postgres 62588 darthunix    8u    REG                1,4       32           128608335 /Users/darthunix/git/gpdb_master/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/base/16384/16499.1

2: truncate ta;
2: checkpoint;

% lsof -p 62588 | grep base | grep 16499
postgres 62588 darthunix    6u    REG                1,4       32           128608335 /Users/darthunix/git/gpdb_master/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/base/16384/16499.1
postgres 62588 darthunix    8u    REG                1,4       32           128608335 /Users/darthunix/git/gpdb_master/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/base/16384/16499.1
```
After https://github.com/greenplum-db/gpdb/pull/11988/commits/c1c8837ab7ffae37d496d288df6b1afb8fbd2758 we get zero size file descriptors after truncate + checkpoint:
```
% lsof -p 62588 | grep base | grep 16499
postgres 62588 darthunix    6u    REG                1,4        0           128608335 /Users/darthunix/git/gpdb_master/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/base/16384/16499.1
postgres 62588 darthunix    8u    REG                1,4        0           128608335 /Users/darthunix/git/gpdb_master/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/base/16384/16499.1
```

**Comment by asimrp** [comment]
Thank you @darthunix for the explanation.  I was under the impression that once a file is closed by a process, it should not be listed in `lsof` output.  And indeed, `AppendOnlyStorageWrite_FlushAndCloseFile()` flushes the file but doesn't close it.  I wonder, if we fix this interface to close the file, would it solve the problem?
```diff
--- a/src/backend/cdb/cdbappendonlystoragewrite.c                                                                                                                                                                                              
+++ b/src/backend/cdb/cdbappendonlystoragewrite.c                                                                                                                                                                                              
@@ -503,6 +503,8 @@ AppendOnlyStorageWrite_FlushAndCloseFile(                                                                                                                                                                                  
                                                storageWrite->segmentFileName,                                                                                                                                                                 
                                                storageWrite->relationName)));                                                                                                                                                                 
                                                                                                                                                                                                                                               
+       FileClose(storageWrite->file);                                                                                                                                                                                                         
+                                                                                                                                                                                                                                              
        storageWrite->file = -1;                                                                                                                                                                                                               
        storageWrite->formatVersion = -1;                                                                                                                                                                                                      
```

**Comment by darthunix** [comment]
@asimrp thanks for this catch! Yes, after this fix we always close AO segment's file descriptor (as `AppendOnlyStorageWrite_FlushAndCloseFile()` declares in its comment and name) there is to problem with the cache invalidation. I have force pushed this fix as an additional commit.

**Comment by darthunix** [comment]
I was not able to reproduce a problem with `workfile_mgr_test` locally, so I'll force push the branch to rerun CI (may be a flacky testn?). 
```
DIFF FILE: ../gpdb_src/src/test/isolation2/regression.diffs
----------------------------------------------------------------------

diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /tmp/build/b235ddbb/gpdb_src/src/test/isolation2/expected/workfile_mgr_test.out /tmp/build/b235ddbb/gpdb_src/src/test/isolation2/results/workfile_mgr_test.out
--- /tmp/build/b235ddbb/gpdb_src/src/test/isolation2/expected/workfile_mgr_test.out	2021-05-19 10:22:09.724758797 +0000
+++ /tmp/build/b235ddbb/gpdb_src/src/test/isolation2/results/workfile_mgr_test.out	2021-05-19 10:22:09.748760791 +0000
@@ -300,9 +298,12 @@
 -- for workset lives across transaction, e.g. with hold cursor, proc exit will cleanup the workset
 3q: ... <quitting>
 4: select segid, prefix, size, operation, slice, numfiles from gp_workfile_mgr_cache_entries() order by (segid, prefix);
- segid | prefix              | size | operation         | slice | numfiles 
--------+---------------------+------+-------------------+-------+----------
- 0     | long_live_workset_1 | 0    | long_live_workset | 1     | 0        
- 1     | long_live_workset_1 | 0    | long_live_workset | 1     | 0        
- 2     | long_live_workset_1 | 0    | long_live_workset | 1     | 0        
-(3 rows)
+ segid | prefix               | size | operation          | slice | numfiles 
+-------+----------------------+------+--------------------+-------+----------
+ 0     | inter_xact_workset_2 | 0    | inter_xact_workset | 1     | 1        
+ 0     | long_live_workset_1  | 0    | long_live_workset  | 1     | 0        
+ 1     | inter_xact_workset_2 | 0    | inter_xact_workset | 1     | 1        
+ 1     | long_live_workset_1  | 0    | long_live_workset  | 1     | 0        
+ 2     | inter_xact_workset_2 | 0    | inter_xact_workset | 1     | 1        
+ 2     | long_live_workset_1  | 0    | long_live_workset  | 1     | 0        
+(6 rows)
```

**Comment by darthunix** [comment]
@asimrp @zhangh43 do you have any questions or remarks about current PR?

**Review by asimrp — APPROVED** [review]
Thank you @darthunix for the contribution.  LGTM :+1:

**Comment by asimrp** [comment]
Merged: 046838de5de..d3a4fa897ae.  Thank you @darthunix for your contribution.

**Pull request closed without merging**
