### PR TITLE
Isolation2 simplify sql helpers

### PR DESCRIPTION
**Pull request by ashwinstar**
Main aspect is run setup test internally as prerequisite for running test for isolation2.

This eliminates need to remember running setup for some tests which
depend on it. Plus, all the prerequisite functions can be combined in
setup and run once. Irrespective of way tests are triggered like via
schedule file or singleton, setup will be run and create the required
functions once automatically.

This is to simplify the flow and also experience to run single test when required easily.
In following PR, I wish to also internally populate `loadextension` and possibly `init_file_list` similarly. So, when running single test (at least for isolation2) can just do `./pg_isolation2_regress <test_name>` eliminating the need to pass `--init-file=./init_file_isolation2 --load-extension=gp_inject_fault` on command line (as got tired of typing it now). Would have liked to do it for regress as well but not all users of regress need `gp_inject_fault` extension. At least for `init_file` I still feel we should do it maybe even for regress.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by asimrp — APPROVED** [review]
Thank you for making it simpler to run a single isolation2 test!

Regarding the additional command line arguments to `pg_isolation2_regress`, an alternative to what you are suggesting is to define `installcheck-tests` target, similar to the one in `regress`.  My favourite way to run a single regress test is:
```
make -C src/test/regress installcheck-tests TESTS="test1 test2 ..."
```
It would be nice to have similar way of running isolation2 tests.

**Comment by asimrp** [comment]
If you want to run a bunch of tests, they can be put into a schedule file and the same `installcheck-tests` target can be used:
```
make -C src/test/regress installcheck-tests TESTS='--schedule=/tmp/my_schedule'
```

**Comment by paul-guo-** [comment]
`gp_management_utils_helpers.sql` and `server_helpers.sql` are not removed, now that the contents in the two files seem to be totally moved to `setup.sql`?

**Comment by ashwinstar** [comment]
> Thank you for making it simpler to run a single isolation2 test!
> 
> Regarding the additional command line arguments to `pg_isolation2_regress`, an alternative to what you are suggesting is to define `installcheck-tests` target, similar to the one in `regress`. My favourite way to run a single regress test is:
> 
> ```
> make -C src/test/regress installcheck-tests TESTS="test1 test2 ..."
> ```
> 
> It would be nice to have similar way of running isolation2 tests.

Interesting, good to learn that. Still looks need lot of typing and quoting :-) which I would prefer avoiding but don't see way for regress. Isolation2 based on what I proposed simplifies quite a lot, as known every invocation uses same arguments. Though for consistency of invocation across frameworks, maybe just go with the route you are suggesting seems even if can be simplified for just for isolation2.

**Pull request merged**
