### PR TITLE
WIP: Manage AO segments independently in QE nodes

### PR DESCRIPTION
**Pull request by asimrp**
This PR is in fact, PR #790, rebased on top of latest master and a few bugs fixed.  It is still very much a WIP.  We (@asubramanya, @ashwinstar, @xinzweb and myself) analyzed the original patch and found that in addition to get ICW green, some challenges with vacuum on append-optimized tables need to be tackled.  The main challenge here is to maintain correct visibility according to MVCC rules while vacuuming an append-optimized table.  Vacuum scans the AO visimap (`pg_aovisimap_<relid>`) heap table using SnapshotNow.  This might cause tuples which are still visible to an old running distributed xid but deemed invisible by vacuum through SnapshotNow to be removed, breaking MVCC.  To solve this, we thought of a couple of solutions.  One assumption we are making is `HeapTupleSatisifiesVacuum()` and `heap_freeze_tuple()` are aware of distributed snapshot.  They are not today (issue #801). 

## Upfront decision to compact + drop
At the beginning of compact phase, determine if the latest visimap entry for a dirty segment file is old enough so that it can be seen by all running transactions.  In other words, can the oldest running transaction as well as vacuum see the same tuples as visible in a dirty segment file.  If yes, then this segment file can be compacted and dropped.  If no, then give up and move on to another dirty segment file.  `heap_freeze_tuple()` may be used here on the latest visimap tuple with the oldest distributed xmin as cutoff_xid.  This solution has the advantage of avoiding to split vacuum into multiple steps coordinated by QD, as was being proposed in the gpdb-dev thread: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/49MW3tBoH8s/FzL3ascmAgAJ

We would like to mention another solution we thought of but soon realized that it is not possible without radically redesigning AO visimaps.

## Reconcile visimap
During compaction, use `HeapTupleSatisfiesVacuum()` to determine all the live tuples with pg_aovisimap for a segment file to be compacted.  All the rows from the dirty segment file deemed visible by the live visimap entires must be included in the new segment file.  But how will the visimap for the new segment file look like?  The fact that one tuple in pg_aovisimap records visibility of multiple row numbers in a segment file is causing problems here.  The new visimap entry cannot "un-merge" the visibility information that was merged for the dirty segment file.  An old snapshot acquired before vacuum started, when reaches a QE, it will see the effects of vacuum because vacuum used a local transaction.  And all tuples in the new segment file will be visible through the old snapshot, which is not correct.  So this solution is flawed unless each row in AO segment file follows MVCC semantics.

### CODE REVIEW

**Comment by asimrp** [comment]
@hlinnaka please note that I've closed your PR #790.  Your original patch is unchanged.  We have added a few commits on top of yours.

**Comment by asimrp** [comment]
We should note down some fixes to be done to get a green ICW run, of course, after vacuum is fixed to not remove AO rows needed by an older snapshot.

1. Try keeping segment file 0 empty always. DML/vacuum should always use segment file 1 onwards, even in utility mode. That should reduce diffs in ICW tests.
1. Answer file updates due to DML acquiring locks on QE and not on QD.
1. gp_toolkit change made by PR 790 to always obtain aoseg and visimap details from segments is causing diffs ICW (isolation2) tests. The change also causes gp_toolkit functions to fail in some cases. It may be easier to revert the gp_toolkit change and fix the tests that assume valid content in QD's aoseg/visimap tables.
1. The change to aoseg.c made by PR 790 doesn't seem right, see if it is really needed, revert otherwise.

**Comment by Eulerizeit** [comment]
What is happening with this PR?

**Comment by hlinnaka** [comment]
I just rebased this over master.

**Comment by pivotal-mike** [comment]
@hlinnaka @asimrp Are we close to seeing this land or should we close this?

**Comment by asimrp** [comment]
Addressing this before walrep is unlikely unless, of course, Heikki picks it up!

**Comment by asimrp** [comment]
The new rebased version of this change is merged as #9258, closing this one.

**Pull request closed without merging**
