### PR TITLE
Make postgres_fdw basically work after 12 merge

### PR DESCRIPTION
**Pull request by adam8157**
Fixes https://github.com/greenplum-db/gpdb/issues/11400, https://github.com/greenplum-db/gpdb/issues/11407, and https://github.com/greenplum-db/gpdb/issues/11523

It is covered by the current test cases already.

### CODE REVIEW

**Review by asimrp — APPROVED** [review]
Thanks for taking care of this.  Should `contrib/postgres_fdw` be added to `ICW_TARGETS` in top level make target, so that we catch regressions in future?

**Comment by asimrp** [comment]
Wait, when I got the following crash when running `make -C contrib/postgres_fdw installcheck`:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f02bc1dc859 in __GI_abort () at abort.c:79
#2  0x000055ac7b68d455 in ExceptionalCondition (conditionName=0x55ac7be29ec0 "!(cdbpathlocus_is_valid(locus) && cdbpathlocus_is_valid(subpath->locus))", errorType=0x55ac7be29eaa "FailedAssertion", fileName=0x55ac7be29ea0 "cdbpath.c", lin\
eNumber=165) at assert.c:44
#3  0x000055ac7b777fcb in cdbpath_create_motion_path (root=0x55ac841197c0, subpath=0x55ac83f7ed58, pathkeys=0x0, require_existing_order=false, locus=...) at cdbpath.c:165
#4  0x000055ac7b33cc67 in bring_to_singleQE (root=0x55ac841197c0, rel=0x55ac83f7e418) at allpaths.c:632
#5  0x000055ac7b33cfd9 in set_rel_pathlist (root=0x55ac841197c0, rel=0x55ac83f7e418, rti=1, rte=0x55ac841174f0) at allpaths.c:779
#6  0x000055ac7b33c63b in set_base_rel_pathlists (root=0x55ac841197c0) at allpaths.c:376
#7  0x000055ac7b33c385 in make_one_rel (root=0x55ac841197c0, joinlist=0x55ac83dbaf38) at allpaths.c:243
#8  0x000055ac7b3795b4 in query_planner (root=0x55ac841197c0, qp_callback=0x55ac7b380c66 <standard_qp_callback>, qp_extra=0x7ffc4227f010) at planmain.c:303
#9  0x000055ac7b37d9e0 in grouping_planner (root=0x55ac841197c0, inheritance_update=false, tuple_fraction=0) at planner.c:2471
#10 0x000055ac7b37b8d3 in subquery_planner (glob=0x55ac82a4bf20, parse=0x55ac84117608, parent_root=0x55ac8411d788, hasRecursion=false, tuple_fraction=0, config=0x55ac841197a0) at planner.c:1269
#11 0x000055ac7b33fb14 in set_subquery_pathlist (root=0x55ac8411d788, rel=0x55ac84117198, rti=2, rte=0x55ac840d4268) at allpaths.c:2553
#12 0x000055ac7b33c7b8 in set_rel_size (root=0x55ac8411d788, rel=0x55ac84117198, rti=2, rte=0x55ac840d4268) at allpaths.c:446
#13 0x000055ac7b33c570 in set_base_rel_sizes (root=0x55ac8411d788) at allpaths.c:344
#14 0x000055ac7b33c288 in make_one_rel (root=0x55ac8411d788, joinlist=0x55ac84117838) at allpaths.c:206
#15 0x000055ac7b3795b4 in query_planner (root=0x55ac8411d788, qp_callback=0x55ac7b380c66 <standard_qp_callback>, qp_extra=0x7ffc4227f590) at planmain.c:303
#16 0x000055ac7b37d9e0 in grouping_planner (root=0x55ac8411d788, inheritance_update=false, tuple_fraction=20) at planner.c:2471
#17 0x000055ac7b37b8d3 in subquery_planner (glob=0x55ac82a4bf20, parse=0x55ac840d3ba8, parent_root=0x0, hasRecursion=false, tuple_fraction=0, config=0x55ac83eefeb8) at planner.c:1269
#18 0x000055ac7b379e4e in standard_planner (parse=0x55ac840d3ba8, cursorOptions=256, boundParams=0x0) at planner.c:534
#19 0x000055ac7b37993d in planner (parse=0x55ac83df5248, cursorOptions=256, boundParams=0x0) at planner.c:326
#20 0x000055ac7b4c2059 in pg_plan_query (querytree=0x55ac83df5248, cursorOptions=256, boundParams=0x0) at postgres.c:1007
#21 0x000055ac7b12e1e0 in ExplainOneQuery (query=0x55ac83df5248, cursorOptions=256, into=0x0, es=0x55ac82971740, queryString=0x55ac827dc0c0 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1, LATERAL (SELECT DISTINC\
T t2.c1, t3.c1 FROM ft1 t2, ft2 t3 WHERE t2.c1 = t3.c1 AND t2.c2 = t1.c2) q ORDER BY t1.\"C 1\" OFFSET 10 LIMIT 1"..., params=0x0, queryEnv=0x0) at explain.c:453
#22 0x000055ac7b12dd93 in ExplainQuery (pstate=0x55ac82971890, stmt=0x55ac84176ed0, queryString=0x55ac827dc0c0 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1, LATERAL (SELECT DISTINCT t2.c1, t3.c1 FROM ft1 t2, f\
t2 t3 WHERE t2.c1 = t3.c1 AND t2.c2 = t1.c2) q ORDER BY t1.\"C 1\" OFFSET 10 LIMIT 1"..., params=0x0, queryEnv=0x0, dest=0x55ac829716a8) at explain.c:292
#23 0x000055ac7b4ce5ee in standard_ProcessUtility (pstmt=0x55ac84176fa0, queryString=0x55ac827dc0c0 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1, LATERAL (SELECT DISTINCT t2.c1, t3.c1 FROM ft1 t2, ft2 t3 WHERE\
 t2.c1 = t3.c1 AND t2.c2 = t1.c2) q ORDER BY t1.\"C 1\" OFFSET 10 LIMIT 1"..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55ac829716a8, completionTag=0x7ffc4227fc30 "") at utility.c:778
#24 0x000055ac7b4cda1c in ProcessUtility (pstmt=0x55ac84176fa0, queryString=0x55ac827dc0c0 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1, LATERAL (SELECT DISTINCT t2.c1, t3.c1 FROM ft1 t2, ft2 t3 WHERE t2.c1 = \
t3.c1 AND t2.c2 = t1.c2) q ORDER BY t1.\"C 1\" OFFSET 10 LIMIT 1"..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55ac829716a8, completionTag=0x7ffc4227fc30 "") at utility.c:381
#25 0x000055ac7b4cc678 in PortalRunUtility (portal=0x55ac828d3e00, pstmt=0x55ac84176fa0, isTopLevel=true, setHoldSnapshot=true, dest=0x55ac829716a8, completionTag=0x7ffc4227fc30 "") at pquery.c:1352
#26 0x000055ac7b4cc328 in FillPortalStore (portal=0x55ac828d3e00, isTopLevel=true) at pquery.c:1208
#27 0x000055ac7b4cbbc0 in PortalRun (portal=0x55ac828d3e00, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x55ac847f9d78, altdest=0x55ac847f9d78, completionTag=0x7ffc4227fe90 "") at pquery.c:935
#28 0x000055ac7b4c3b19 in exec_simple_query (query_string=0x55ac827dc0c0 "EXPLAIN (VERBOSE, COSTS OFF)\nSELECT t1.\"C 1\" FROM \"S 1\".\"T 1\" t1, LATERAL (SELECT DISTINCT t2.c1, t3.c1 FROM ft1 t2, ft2 t3 WHERE t2.c1 = t3.c1 AND t2.c2 = \
t1.c2) q ORDER BY t1.\"C 1\" OFFSET 10 LIMIT 1"...) at postgres.c:1895
#29 0x000055ac7b4c8d95 in PostgresMain (argc=1, argv=0x55ac8280e2c0, dbname=0x55ac827d8908 "contrib_regression", username=0x55ac8280dfd8 "apraveen") at postgres.c:5252
#30 0x000055ac7b3fac28 in BackendRun (port=0x55ac827fea80) at postmaster.c:4923
#31 0x000055ac7b3fa2be in BackendStartup (port=0x55ac827fea80) at postmaster.c:4608
#32 0x000055ac7b3f5c70 in ServerLoop () at postmaster.c:1964
#33 0x000055ac7b3f5234 in PostmasterMain (argc=7, argv=0x55ac827d6830) at postmaster.c:1589
#34 0x000055ac7b29f133 in main (argc=7, argv=0x55ac827d6830) at main.c:240
```

**Review by asimrp — CHANGES_REQUESTED** [review]
`make -C contrib/postgres_fdw` needs to pass...

**Comment by adam8157** [comment]
My thought is to take this as the first step, after this PR, the delegated team would go through a little easier, and the community users could give more feedback. It currently would not work at all.

Passing the cases would take lots of effort, we need a detailed feature scope and plan to enable it.

**Comment by asimrp** [comment]
Ok, I had no idea of how much effort is needed to fix the tests.  I agree that this can be tackled separately and we can merge this PR.  However, the assertion failure I reported seems to be related to the change introduced by this patch.  Does it make sense to fix it now?

**Comment by adam8157** [comment]
> Ok, I had no idea of how much effort is needed to fix the tests. I agree that this can be tackled separately and we can merge this PR. However, the assertion failure I reported seems to be related to the change introduced by this patch. Does it make sense to fix it now?

Sure, I'm running it now, to fix issues as I can, and leave the normal failed cases for later discussion (for instance, most of the UPDATEs will fail now because of the Greenplum architecture, we need to have a plan first)

**Comment by adam8157** [comment]
The assert failure is fixed and needs to be reviewed.

**Review by asimrp — APPROVED** [review]
Thank you for the fix.  Should we create an issue to enable installcheck on postgres_fdw?

**Comment by lij55** [comment]
Hi Adam,

I'm afraid this PR has some duplication and conflict with what dataflow team is working on. Could we catch up in advance before any further steps of this PR (and anything related with FDW)?
Thank you very much.

**Comment by adam8157** [comment]
@lij55 No problem, sorry I don't know someone is working on that, these issues are dangling for some time without response.

And I am waiting for approval from your team, would never revert a commit without her/his confirmation.

**Comment by adam8157** [comment]
Since other commits in this PR are already merged, I filed a new one https://github.com/greenplum-db/gpdb/pull/12285 to continue the discussion concentratedly.

**Pull request closed without merging**
