### PR TITLE
Handle distributed commit WAL records for various recovery features

### PR DESCRIPTION
**Pull request by jimmyyih**
To allow experimentation of various Postgres recovery features, we
must handle distributed commit WAL records similarly to commit and
commit prepared WAL records. This will allow the standby master
segment to utilize the recovery features. The mirror segments already
get handled since they use the regular commit and commit prepared WAL
records.

With this change, the standby master segment will be able to properly
output a value for a pg_last_xact_replay_timestamp() call (while in
hot standby), have delayed WAL replay, and use PITR/archive recovery
settings such as recovery_target_time and recovery_target_xid.

### CODE REVIEW

**Comment by asimrp** [comment]
+1 to the idea but I think `XLOG_XACT_DISTRIBUTED_FORGET` records should also be included in the change.

**Comment by jimmyyih** [comment]
I originally had `XLOG_XACT_DISTRIBUTED_FORGET` included as well but removed it after seeing that it didn't change anything.  The distributed forget records only contain the gxid.  The changes in this PR are mainly for transaction WAL records with local xid and timestamp.  Yes, the distributed forget record has local xid too but it's always the same as the distributed commit record so it would never be used (recovery_target_xid would stop at the distributed commit record).  For these recovery features, the distributed commit record is all that is needed.

If anything, `XLOG_XACT_DISTRIBUTED_FORGET` records could play a part if anyone ever decides to propose a `recovery_target_dxid` or `recovery_target_distributed_timestamp` recovery configuration.

**Review by paul-guo- — APPROVED** [review]

**Comment by asimrp** [comment]
Thank you for that explanation, makes sense to exclude distributed_forget record from this change.

**Comment by jimmyyih** [comment]
No problem.  Thanks for the comments and interest.

**Pull request merged**
