### PR TITLE
Fix explain analyze error handling

### PR DESCRIPTION
**Pull request by darthunix**
Error handling for explain analyze differed from a regular query. When we executed a plan slice and got an error in a case on a simple query we just cleanup and rethrew an exception out of `PG_TRY` block. But for explain analyze we tried to return stats to QD though it is possibly incorrect or even broken. It can cause different errors with stats packets during:

- serialization on QE (`InstrEndLoop called on running node`)
-  deserialization on QD (`Invalid execution statistics received stats node-count mismatch`)

Also in a case of a double fault an original error was overridden by a new one. It hid an original error from a user and this behavior differed from a simple query plan processing.

There is another possible solution: remove `PG_CATCH` block of code (to show the original error) and make some additional checks for stats data of `cdbexplain_sendExecStats` function. But it is still strange to return some non-finished stats in explain analyze while a real query fails on the same dataset.

It seems that this commit should be backported to all stable releases (5X and 6X)

### CODE REVIEW

**Comment by baobao0206** [comment]
Can you provide a case to show the difference before and after adding your patch.

**Comment by darthunix** [comment]
@baobao0206 sorry but I was not able to reproduce the problem. May be you have more information in `MPP-2140` task in internal Jira.

**Comment by darthunix** [comment]
@baobao0206 or you want to show an example of hiding a real message in a case if a double fault? This can be reproduced by fault injector, do you need it as an example?

**Comment by zhangh43** [comment]
@darthunix Thanks for your PR.

The code is also strange to me. When we have already encountered an error on QE, why do we still need to send instrument statistics back to QD through libpq? But this code exists for a long time, could you help to verify:
1. what's behavior on upstream(Postgres) when error happens in `explain analyze`. Will the result include partial instrument info?
2. we do need some test cases here. As you mentioned, we could use fault inject to do it. So please add test case for this PR. If you need any help on test case, please let me know.  

@magi345 FYI, is there any affect on GPCC side?

**Comment by darthunix** [comment]
@zhangh43 thanks for your review.

1. PostgreSQL [doesn't wrap](https://github.com/postgres/postgres/blob/7ce461560159948ba0c802c767e42c5f5ae08b4a/src/backend/executor/execMain.c#L364) `ExecutePlan` in `PG_TRY/PG_CATCH` macros - it is a GP specific behaviour ([explained](https://github.com/greenplum-db/gpdb/blob/f6ec65f7e9000716f84f4e58c8128b5aab07ee49/src/backend/executor/execMain.c#L771) in a comment below)
```
* Need a try/catch block here so that if an ereport is called from
* within ExecutePlan, we can clean up by calling CdbCheckDispatchResult.
* This cleans up the asynchronous commands running through the threads launched from
* CdbDispatchCommand.
```
2. I have added fault injector tests for a simple query and its `explain analyze` version to generate a double fault in executor. We can't add fault injector directly in `standard_ExecutorRun` as current commit removes the place to insert a second fault in `PG_CATCH` block. Instead faults were added to `ExecutePlan` and `cdbexplain_sendExecStats` functions.
I have tested fault injector tests with (original code) and without (current commit) `qExec` trying to resend stats to `qDisp` in a case of error.
   * Results without current commit (original code)
```sql
-- Simple query raising 'executor_pre_tuple_processed' error (no explain analyze)
adb=# select fault_exec_plan(false);
ERROR:  'executor_pre_tuple_processed' fault triggered
 fault_exec_plan 
-----------------
 
(1 row)

-- Explain analyze query masks 'send_exec_stats' error with 'send_exec_stats' one
adb=# select fault_exec_plan(true);
ERROR:  'send_exec_stats' fault triggered
 fault_exec_plan 
-----------------
 
(1 row)
```
* Results after commit: we always get an original error `executor_pre_tuple_processed`.

**Comment by zhangh43** [comment]
@darthunix  I planned to merge the PR, but it failed when I try to run make installcheck-world
The failed case are:
```
--- /home/huanzhang/workspace/gpdb/src/test/regress/expected/dispatch.out       2020-07-17 06:33:51.190249048 +0000
+++ /home/huanzhang/workspace/gpdb/src/test/regress/results/dispatch.out        2020-07-17 06:33:51.220249041 +0000
@@ -799,7 +798,6 @@
 (1 row)

 reset gp_cached_segworkers_threshold;
-
 --
 -- Test executor double fault
 -- check PG_TRY/PG_CATCH - we should always return an original error

======================================================================

--- /home/huanzhang/workspace/gpdb/src/test/regress/expected/workfile/hashjoin_spill.out        2020-07-17 06:34:15.526243605 +0000
+++ /home/huanzhang/workspace/gpdb/src/test/regress/results/workfile/hashjoin_spill.out 2020-07-17 06:34:15.530243604 +0000
@@ -47,39 +49,33 @@
 (1 row)

 select * from hashjoin_spill.is_workfile_created('explain (analyze, verbose) SELECT t1.* FROM test_hj_spill AS t1 RIGHT JOIN test_hj_spill AS
t2 ON t1.i1=t2.i2');
- is_workfile_created
----------------------
-{
-  'id' => 1,
-  'short' => '1'
-}
-GP_IGNORE:(1 row)
-
+ERROR:  spiexceptions.FaultInject: fault triggered, fault name:'send_exec_stats' fault type:'error'
+CONTEXT:  Traceback (most recent call last):
+  PL/Python function "is_workfile_created", line 6, in <module>
+    rv = plpy.execute(explain_query)
+PL/Python function "is_workfile_created"
```

Could you help to fix these test cases? For test 'hashjoin_spill', I think the reason of failure is that you failed to reset the injected fault in test 'dispatch'.
To reproduce this error in your local environment, one tip is to make parallel_schedule empty and only leave 'dispatch' and 'hashjoin_spill' test cases in greenplum_schedule.

**Comment by Stolb27** [comment]
@zhangh43, I pushed the fix for this issue. Problem was in order of re-raise exception and fault injector reset. Should I squash this changes?

**Comment by zhangh43** [comment]
> @zhangh43, I pushed the fix for this issue. Problem was in order of re-raise exception and fault injector reset. Should I squash this changes?

Giuhub could do squash when merge. I will run it in my dev pipeline line again. If it's green, I'll merge it.

**Comment by zhangh43** [comment]
Thanks the contribution @darthunix  and @Stolb27 .
Sorry @Stolb27 When I squashed the two commits using github, it lose the commit message and co-author information.

**Pull request merged**
