### PR TITLE
Close the db connection at the end.

### PR DESCRIPTION
**Pull request by laixiong**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@laixiong Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1525)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1525) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by hlinnaka** [comment]
Why? The program is just about to exit, which will close the connection anyway. I guess it's better to be tidy...

**Comment by pivotal-issuemaster** [comment]
@laixiong Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1525)!

**Comment by laixiong** [comment]
If we not close the connection ,the master logfile will log one message:
2017-01-07 11:00:56.983462 CST,"gpadmin","test",p16255,th2103408832,"192.168.19.42","32811",2017-01-07 11:00:56 CST,0,con34,cmd11,seg-1,,,,,"LOG","08P01","unexpected EOF on client connection",,,,,,"(null)",0,,"postgres.c",406,

**Comment by hlinnaka** [comment]
Ah, ok. That was changed in a later Postgres version IIRC, but we'll have to live with it for some time until we catch up.

- Heikki

On 7 January 2017 05:03:29 EET, laixiong <notifications@github.com> wrote:
>If we not close the connection ,the master logfile will log one
>message:
>2017-01-07 11:00:56.983462
>CST,"gpadmin","test",p16255,th2103408832,"192.168.19.42","32811",2017-01-07
>11:00:56 CST,0,con34,cmd11,seg-1,,,,,"LOG","08P01","unexpected EOF on
>client connection",,,,,,"(null)",0,,"postgres.c",406,
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/1525#issuecomment-271058405

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danielgustafsson** [comment]
:+1:, seems reasonable to avoid log message. Are you committing @hlinnaka or do you want me to pick it up?

**Comment by hlinnaka** [comment]
Pushed. Thanks for the patch, @laixiong!

**Pull request closed without merging**
