### PR TITLE
Fix orphaned share input scan QE process after OLAP grouping query

### PR DESCRIPTION
**Pull request by huor**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Looks good to me as far as this goes. It would be nice if the reader would give a notification when it aborts, so that the writer would wake up faster, but this check would make sense as a safeguard even if we had that.

**Comment by huor** [comment]
@hlinnaka , thanks for your feedback and comments. Please find my comments below:

1. The logging message has been rephrased based on your comments to reflect the nature of problem.

2. I totally agree with your that it would be better to add logic for reader so that it can send data-reading-done notification to writer if it is aware of that the transaction is aborting. However, if it just quit unexpectedly (i.e., core dump, killed), it get no chance to send notification to writer. So, current fix to add check in writer is a safeguard, not a perfect solution.

For a complete fix, I think we need to improve the reader/writer communication protocol to add error handling for variety of reader/writer failures. That can be an improvement in the future.

**Comment by huor** [comment]
@gpdbdreddbot , ICLA has been sent to gpdb-cla@pivotal.io, please check.

**Comment by huor** [comment]
Closing this pull request since https://github.com/greenplum-db/gpdb/pull/139 is a manual merge of multiple commits for the fix. It is easier for commitors to merge the fix to main stream.

**Pull request closed without merging**
