### PR TITLE
Fix a memory leak when copy data into partition table.

### LINKED ISSUE #4986: Memory leak when copy data into partition table
### Greenplum version or build

master branch

### OS version and uname -a

centos 7

### Expected behavior

COPY data into partition table successfully

### Actual behavior

Use out all memory on master node

### Step to reproduce the behavior

1) create a partition table
2) copy data into partition table

### Root cause

https://github.com/greenplum-db/gpdb/blob/660d009a30c3c9b114669fc014b178cfed8d4dfe/src/backend/commands/copy.c#L4031

```
GetDistributionPolicyForPartition(CopyState cstate, EState *estate,
                                  PartitionData *partitionData, HTAB *hashmap,
                                  Oid *p_attr_types,
                                  GetAttrContext *getAttrContext,
                                  MemoryContext ctxt)
...

	/* values_get_partition() calls palloc() */
	MemoryContext save_cxt = MemoryContextSwitchTo(ctxt);
	GpDistributionData *distData = palloc(sizeof(GpDistributionData));
	distData->p_attr_types = p_attr_types;
	resultRelInfo = values_get_partition(values_for_partition,
	                                     getAttrContext->nulls,
	                                     getAttrContext->tupDesc, estate);
	MemoryContextSwitchTo(save_cxt);
...
        return distData;
```

`part_distData` is allocated for every tuple but not allocated in per tuple memory context.

### Proposed fix

Either allocate `part_distData` in per tuple memory context or reuse it for every tuple. I prefer the latter.

### PR DESCRIPTION
**Pull request by wangzw**
fix #4986

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wangzw Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4987)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4987) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by yydzero** [comment]
Thanks @wangzw for contributing. Is there any way to add some test cases?

**Comment by wangzw** [comment]
No idea that how we test memory leak right now. It will not crash or return wrong answer. Even with limited memory in test case, we cannot tell the query fail due to memory leak or real need of such size of memory. It is also not possible to detect such memory leak in a memory context using tools like valgrind.

**Comment by yydzero** [comment]
@fanfuxiaoran @adam8157 would you please help to review this PR? Thanks!

**Comment by adam8157** [comment]
LGTM, please write a brief commit message of the root cause?

**Comment by adam8157** [comment]
During the merge, this issue was fixed. The memory is allocated before memory context switch now.

Check https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/copy.c#L6804

Closing this, will fix 5X_STABLE also, thanks Zhanwei.

**Pull request closed without merging**
