### PR TITLE
Remove unused MemoryAccounting_SaveToFile() function and related GUCs.

### PR DESCRIPTION
**Pull request by hlinnaka**
Not used for anything, AFAICS.

### CODE REVIEW

**Comment by chrishajas** [comment]
@hardikar, that removal was accidental (there was a backup utility called gp_dump that was intended to be removed).

**Comment by Eulerizeit** [comment]
Maybe a test might be appropriate here?

**Comment by d** [comment]
Looks like @hlinnaka found some dead code that should be resurrected. Should I close this PR @hardikar ?

**Comment by Eulerizeit** [comment]
@d I'd rather see this pushed and then a separate PR to restore it with tests and whatnot, otherwise it'll get dropped or broken again and no one will notice for 6 months again.

**Comment by ashwinstar** [comment]
On Thu, Sep 6, 2018 at 11:06 AM Shreedhar Hardikar <notifications@github.com>
wrote:

> There was a test suite of memory accounting tests that is currently
> disabled. It was removed from the code in b9b64ac
> <https://github.com/greenplum-db/gpdb/commit/b9b64ac73151fa488be65777d0c6dff4adfe44ea>;
> moved to isolation2 in 1ec6582
> <https://github.com/greenplum-db/gpdb/commit/1ec65820db45d6699e0dc793e1ce1289fe1210e0>
> and that was finally reverted.
>
How long back was it ? So, we lost the test coverage, how are we tracking
this and making sure its brought back.

**Comment by xinzweb** [comment]
Great discussion back in Sept. Any action item to bring the missing test back in place? @hardikar @hlinnaka @ashwinstar? @Eulerizeit if we already track it, maybe mark `ToDo` label it?

**Comment by hlinnaka** [comment]
Anyone care about this memory account dumping code anymore? What's the plan?

@vraghavan78, @hardikar, do you have a plan on what should happen here? We're getting close to the GPDB6 release, so this needs to be resolved one way or another. If I don't hear anything soon, I'll default to removing this as it's dead code as it stands.

**Comment by d** [comment]
I recall we wanted to resurrect the code, plus the call sites that were erroneously removed, plus the tests that exercise this code path

**Comment by hardikar** [comment]
Ideally, we should resurrect the code. It has been useful in the past.

**Comment by Eulerizeit** [comment]
@hlinnaka @baobao0206 agreed to step up and work on this.

**Comment by hlinnaka** [comment]
Closing this, since there are plans to resurrect and fix the memaccounting stuff some other way.

**Pull request closed without merging**
