### PR TITLE
WIP: Temporary fix for split update

### PR DESCRIPTION
**Pull request by zellerh**
This is a temporary fix for the below github issue https://github.com/greenplum-db/gpdb/issues/6488 to avoid wrong results in concurrent updates.

## Here are some reminders before you submit the pull request
- [] Add tests for the change
- [] Document changes
- [] Communicate in the mailing list if needed
- [] Pass `make installcheck`

### CODE REVIEW

**Comment by kainwen** [comment]
We should not add back the table-level lock.

A better method is to acquire the table-level lock only when updating hash columns. MPP team has tried the better method solution and then we think that might have a more elegant way to solve it. Maybe we can look into it later?

**Comment by vraghavan78** [comment]
@kainwen I am happy your MPP is working on it, but we should not let master be broken till then. So I vote removing it, it is just code, so when you have the fix re-revert this. How does that plan sound?

**Comment by hlinnaka** [comment]
I think we should fix this properly. Easier said than done, I know, but we shouldn't shun away from fixing things just because they're hard.

**Comment by vraghavan78** [comment]
Closing the PR since the consensus is to fix it sooner than later

**Pull request closed without merging**
