### PR TITLE
Change the OIDs of a few GPDB-added functions.

### PR DESCRIPTION
**Pull request by hlinnaka**
To avoid clashing with upstream functions with the same OIDs. We are about
to merge the Window Functions patch from upstream, and the new window
functions are clashing with these.

### CODE REVIEW

**Comment by hlinnaka** [comment]
On 11/22/2017 06:37 PM, Asim RP wrote:
> asimrp approved this pull request.
> 
> I don't see catalog version being bumped.  Is that intentional?

Well, we just usually don't bother with that. Previous discussion on that:

https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/ybFrXcIWNOQ/iOpE56zdAAAJ

I'm not against bumping it, but I think it's a lost cause. I'm happy to 
open the discussion again, and I can try to remember it in the future if 
we decide to try, but that's the policy we have now.

- Heikki

**Comment by d** [comment]
Back then I feel like most of my attention was on the "version" and less on "catversion".

Now that we're at it, let's at least be diligent at bumping the catalog version in one of the following forms:

1. As part of the PR: proposed cat version bump will be the day the PR was posted
1. Not as part of the code reviewed, but as part of the final push: the cat version bump will be the day the code is merged
1. As part of the PR, but adapted on the day of the merge

- Jesse

**Comment by hlinnaka** [comment]
On 11/22/2017 07:45 PM, Jesse Zhang wrote:
> Back then I feel like most of my attention was on the "version" and less on "catversion".
> 
> Now that we're at it, let's at least be diligent at bumping the catalog version in one of the following forms:
> 
> 1. As part of the PR: proposed cat version bump will be the day the PR was posted
> 1. Not as part of the code reviewed, but as part of the final push: the cat version bump will be the day the code is merged
> 1. As part of the PR, but adapted on the day of the merge

Ok, let's try to be diligent.

Pushed, with a catversion bump.

- Heikki

**Comment by asimrp** [comment]
Thank you for the pointer.  My concern was binary swap test will break but it is disabled on master to avoid the overhead of keeping it green with frequent catalog changes coming in from upstream.

**Pull request merged**
