### PR TITLE
docs - SQL reference page updates for postgres 8.4 merge

### PR DESCRIPTION
**Pull request by dyozie**
These changes are to bring the reference docs in-line with the 8.4 merge in [PR 3252](https://github.com/greenplum-db/gpdb/pull/3252).

- Adds RETURNING clause to INSERT and DELETE
- Updates wording around output columns and AS clause in SELECT

### CODE REVIEW

**Comment by dyozie** [comment]
Actually, a recent build of master shows that the RETURNING clause still isn't supported.  @hlinnaka - I'm not sure how important this is, but I guess some of the postgres merges are pulling in SGML changes that don't reflect the syntax that gpdb supports, as in [PR 3252](https://github.com/greenplum-db/gpdb/pull/3252).  This doesn't directly affect the Greenplum documentation since we don't build any of the .sgml files.  However, we do look at PRs that touch the .sgml for clues as to when doc changes might be needed.  Just something to consider...

**Comment by mkiyama** [comment]
@dyozie 
Does UPDATE also need to be updated?

**Comment by dyozie** [comment]
Looks like it gets the change also.

**Comment by xinzweb** [comment]
@dyozie anything remaining on this PR? Can we close it or merge it? Thanks.

**Comment by dyozie** [comment]
Looks like we have some limitations on RETURNING for INSERT with partitioned tables.  I'll add that change and then merge this PR.

**Comment by dyozie** [comment]
Correction - we'll handle the INSERT issue as a limitation if it exists past the first release tag of 6.x.  Merging this now, and can handle future changes (as for UPDATE additions) in a separate PR.

**Pull request merged**
