### PR TITLE
Move TINC storage basic/partition tests to ICW

### PR DESCRIPTION
**Pull request by danielgustafsson**
This moves the `basic/partition` storage tests from TINC into the `pg_regress` part of ICW. The tests were not moved wholesale but manually analyzed for existing coverage to avoid duplicating and thus adding extra runtime to ICW.

Commit 3359a90 contains a fix to allow ORCA plans with PartitionSelector nodes to handle hash subpartitions, a case which failed with one of the tests (works with postgres planner as it doesn't use PartitionSelector in `INSERT` plans). This patch will be opened as a separate PR, but is included here to give the tests contained a fighting chance of passing.

The commit message contains the reasoning but for ease of reading it has been copied here as well:

    * MPP-3379 was testing an ancient bug and MPP-3553 a hypothetical
      bug from before the current partition code was written. Combined
      the two since the added clause will still cover the ancient 3379
      issue and remove the other from Tinc.

    * MPP-3625 was mostly already covered by existing tests in partition
      and bfv_partition. Added a test for splitting a non-existing default
      as that was the only thing covered.

    * MPP-6297 is testing the pg_get_partition_def() function after the
      partition hierarchy has been amended via ALTER TABLE, which is
      already covered by the partition suite. Additionally it tested
      running pg_dump, which use pg_get_partition_def() heavily, and
      this is covered by our pg_upgrade tests.

    * MPP-6379 tested that partitions inherited unique indexes, the test
      was moved to the partition_indexing suite.

    * MPP-6489 tested ALTER TABLE .. SET DISTRIBUTED BY for subpartitions
      which didn't seem covered in ICW so moved to alter_distribution_policy
      suite

    * MPP-7661 tested for an old bug where pg_dump incorrectly handled
      partition hierarchies created with the EVERY syntax. pg_upgrade
      tests in ICW will run this test on hierarchies from the partition
      suites so remove.

    * MPP-7734 tested for excessive memory consumption in the case of a
      very deep partitioning hierarchy. The issue in question was fixed
      in 4.0 and the test clocks in at ~ 1.5 minutes, so remove the test
      to save time in the test pipeline. The test was more of a stress
      test than a regression test at this point, and while thats not of
      no importance, we should run stresstests deliberately and not
      accidentally.

    * MPP-6537/6538 tested that new partitions introduced in the hierarchy
      correctly inherited the original owner. Test moved to the partition
      suite.

    * MPP-7002 tested that splitting partitions worked after a column
      had been dropped. Since we had a similar test already in the
      partition suite, extend that test to also cover splitting.

    * MPP-7164 is testing for partition rank after DDL operations on the
      partition hierarchy. I can see that we are testing something along
      the lines of this in ICW so pulled it across. In the process, fixed
      the test to actually run the SQL properly and not error out on a
      syntax error. Also removed a duplicated file for setting up the views.

    * MPP-9548 tested for the case of insert data into a column which
      was dropped and then re-added. Since we already had that covered
      in the partition suite, simply extended the comment on that case
      and added another projection to really cover it completely.

    * MPP-7232 tests that pg_get_partition_def() supports renamed partitions
      correctly. Added to ICW but the pg_dump test removed.

    * MPP-17740 tested the .. WITH (tablename = <t> ..) syntax which we
      to some extent already covered, but added a separate case to test
      permutations of it.

    * MPP-18673 covers an old intermittent bug where concurrent sessions
      splitting partitions would corrupt the relcache. The test in Tinc
      didn't however run concurrently so the underlying bug wasn't being
      tested, so remove the test. If we want a similar test at some point
      it should be an isolationtester suite.

    * MPP-17761 tests an old bug where splitting an added CO partition
      failed. Since we didn't have much in terms of testing splitting
      CO, extended the block doing split testing with that.

    * MPP-17707-* were essentially the same test but with varying storage
      options. While a lot of this is covered elsehwere, these tests were
      really easy to read so rolled them all into a new suite called
      partition_storage.

    * MPP-12775 covered yet another split/exchange scenario. Added a
      short variant to the partition suite.

    * MPP-17110 tests for an old regression in attribute encoding for
      added columns in partitioning hierarchies. Removed the part of
      the test that checked compression ratio as AO compression should
      be tested elsewhere.

    * The partition_ddl2 test was moved over as partition_ddl more or
      less unchanged.

This also removes unused answer files `mpp8031.ans.orca` and `query99` for which there were no corresponding tests, as well as the data file used for copying data into the tests (a copy of which already exists in `src/test/regress/data`).

### CODE REVIEW

**Comment by jimmyyih** [comment]
Should the `selectHashPartition` commit be moved into its own separate PR (maybe also including the partition_ddl tests)?  It seems like it could be of interest of other developers but the title of this PR makes it to believe this is only doing test migration.

**Comment by danielgustafsson** [comment]
> On 03 Nov 2017, at 22:31, Jimmy Yih <notifications@github.com> wrote:
> 
> Should the selectHashPartition commit be moved into its own separate PR (maybe also including the partition_ddl tests)? It seems like it could be of interest of other developers but the title of this PR makes it to believe this is only doing test migration.

Absolutely, I think I mentioned that in a comment on the PR (if I did I meant to and forgot). I included it here to give it some mileage on the pipeline, but I will submit it, and a specialmade test, as a separate PR and remove it from ere before pushing.

**Comment by hlinnaka** [comment]
>  IMHO this is ready to be committed.

After fixing the regression failure in the `partition` test, of course. But that doesn't seem to be anything serious at a quick glance.

**Comment by hlinnaka** [comment]
Rebased and fixed expected output.

**Comment by hlinnaka** [comment]
Pushed!

> It may be worth wrapping the whole file within begin; ... end; to reduce 2PC overhead.

Yeah, perhaps. Then again, that adds a lot of noise, if one of the queries in the transaction block fails. I left it as it is for now, but we should definitely think of ways to make the tests run faster in general.

**Pull request merged**
