### PR TITLE
Add Zstandard compression option for append-optimized tables

### PR DESCRIPTION
**Pull request by leskin-in**
This is a backport of https://github.com/greenplum-db/gpdb/commit/724f9d27b160ec3f87a5ce95eecc605808be3ced.

Add a new compression option`zstd` for append-optimized tables. It is
generally faster than zlib or quicklz, and compresses better. Or at least
it can be faster or compress better, if not both at the same time, by
adjusting the compression level. A major advantage of Zstandard is the wide
range of tuning, to choose the trade-off between compression speed and
ratio.

Using the new option requires building the server with the `libzstd` library.
A new `--with-zstd` option is added for that. The default is to build without
libzstd, for now.

Original commit by Ivan Leskin, Dmitriy Pavlov, Anton Chevychalov and Heikki Linnakangas.

Also, added extra tests for `zstd` compression option for append-optimized column-oriented tables. However, they are not included in the current branch; they are available at https://github.com/leskin-in/gpdb/commit/7763898bdd0789893909dbca179dad3030f5de58. I am not sure those tests are quite suitable for GPDB `regression` test set, so it would be great if someone could review them.

### CODE REVIEW

**Comment by Eulerizeit** [comment]
@leskin-in thanks for this. Out of curiosity, have you looked into taking this beyond data storage compression in Master? We have had some discussion surrounding potentially leveraging zsdt for spill files, query plan compression and other places where zlib is currently used.

**Comment by Eulerizeit** [comment]
@leskin-in I completely agree. getting this in as proposed absolutely makes the most sense. I was mostly asking because we have discussed it internally and I think our conclusions are similar to yours.

**Comment by lisakowen** [comment]
hi @leskin-in .  can i ask how you build gpdb with zstandard compression?  i tried to build gpdb master branch today with zstandard compression enabled.  i finally got configure to work and the code to compile on a pivotaldata/gpdb-devel docker image after doing the following:
- yum install libzstd
- copying and linking various incantations of libzstd.so.N... to /lib64
- downloading zstd source and copying zstd.h to /usr/include
- adding --with-zstd to the ./configure
- removing -Werror=uninitialized from CFLAGS (unrelated to the zstd work)

i started the gpdemo and created a database.  when i tried to create a table with compresstype=zstd, i got the error "ERROR:  unknown compresstype "zstd"".  so, i must have missed a step or something.  or didn't actually link in the zstd library.  

do you have any idea as to what i might have done wrong?

thanks!

**Comment by leskin-in** [comment]
Hi @lisakowen! In order to build GPDB with zstd, you need to install the `libzstd-devel` library. It also adds `zstd.h` to your include directory.

**Comment by lisakowen** [comment]
@leskin-in - thanks for replying.  i did try to install that package, but got a "no package available"  notice.  hence the copying...  in which repo can i find the libzstd-devel package?  i must not have that repo registered/enabled.  i did find a site to download the libzstd-devel rpm ...

**Comment by leskin-in** [comment]
@lisakowen, it is in [EPEL](https://fedoraproject.org/wiki/EPEL). In short, you need to install the `epel-release` package first and it will make the necessary changes to use the EPEL repository, which contains `libzstd-devel`.

**Comment by lisakowen** [comment]
perfect.  THANK YOU, @leskin-in !

**Comment by ashwinstar** [comment]
Doesn't this need catalog change and hence cannot be back ported to 5.x ?

**Comment by leskin-in** [comment]
@ashwinstar, it does changes catalog. However, no other changes there are required in order for zstd to work, except for those in `pg_compression.h`, `pg_proc_gp.h`, `pg_proc.sql` (where new built-in compression functions are added) and in `zstd_compression.c` (where the compression is implemented).

Is there a policy that disallows to change catalog in 5X branches? I may have missed it.

**Comment by ashwinstar** [comment]
On Tue, Dec 26, 2017 at 11:23 AM, Ivan Leskin <notifications@github.com>
wrote:

> Is there a policy that disallows to change catalog in 5X branches? I may
> have missed it.
>
Yes, 5.x is freezed for catalog changes, as any further versions of 5.x
needs to be binary swappable. GPDB follows semantic versioning (
https://semver.org), so can only change the catalog in 6.0+ now not in 5.x.

**Comment by leskin-in** [comment]
As @ashwinstar said, this backport is not possible due to the semantic versioning. However, this feature (already present in the `master` branch) will be implemented in GPDB 6.0.

We will add the tests and README.md update to master branch soon.

**Pull request closed without merging**
