### PR TITLE
Ensure that gpfaultinjector is invoked correctly in ICG tests

### PR DESCRIPTION
**Pull request by armenatzoglou**
As per our discussion in https://github.com/greenplum-db/gpdb/issues/627, in this PR we move `gpfaultinjector` calls out of `---start_ignore` and `---end_ignore` blocks, to ensure that a fault has been injected successfully.

### CODE REVIEW

**Comment by armenatzoglou** [comment]
@ashwinstar @hlinnaka @karthijrk Please take a look when you have some time. Thanks

**Comment by armenatzoglou** [comment]
Although icg passes locally, it seems that query_finish_pending test is complaining. I will take a look asap.

**Comment by danielgustafsson** [comment]
Test failure aside, this seems like a very good diff. Thanks for tackling!

**Comment by hlinnaka** [comment]
Instead of using "grep" to suppress the extra output, how about making gpfaultinject less noisy to begin with?

**Comment by armenatzoglou** [comment]
@danielgustafsson @hlinnaka Thanks a lot for the feedback. We made gpfaultinjector less noise and fixed all tests.

**Pull request closed without merging**
