### PR TITLE
Move ORCA-debugging UDFs to a separate contrib module.

### PR DESCRIPTION
**Pull request by hlinnaka**
Some of the functions in funcs.cpp were only used by debugging/testing
code. They were included in the libgpoptudfs.so library, but it was built
in a strange way, from gpAux/Makefile. Move it to a contrib module, along
with the regression tests using it.

This commit leaves only the functions actually used by backend code in
funcs.cpp, and moves the debugging functions only used by the optional
UDFs into the contrib module.

NOTE: The regression tests don't actually work at the moment. But that's not
new, they didn't work before either. I don't have the patience to start
fixing them, so I'm just moving them to the new location in their current
form.

NOTE2: The new module is called orca_debug, but I think some test code
in GPORCA repository expects to find this in libgoptudfs.so. Will need
to fix the scripts there.

### CODE REVIEW

**Comment by hlinnaka** [comment]
BTW, this greatly reduces the amount of garbage printed out to stdout during the build. That's because the  makefile step to compile libgoptudfs.so was slightly broken:

```
## NOTE: The copyoptimizerlibs taret must be called after the
## clients and connectivity targets (above) so as to keep the
## optimizer libs out of their respective distributions.
make[1]: Entering directory `/tmp/build/f8c7ee08/gpdb_src/gpAux'
cd /tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel6_x86_64/lib64; tar cvf - * | (cd /usr/local/greenplum-db-devel/lib; tar xfp -)
/bin/bash: line 0: cd: /tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel6_x86_64/lib64: No such file or directory
...
```
Because the "cd" command failed, it then tars up, and untars every file in the build repository, and because of the verbose option, it prints a line for every single file. The difference is quite big, here are the sizes of the whole stdout, copy-pasted from the gpdb_pr pipeline, where 222 was the build with this PR:

~$ ls -l 221.txt 222.txt 
-rw-r--r-- 1 heikki heikki 4293047 Nov 14 13:03 221.txt
-rw-r--r-- 1 heikki heikki 3368286 Nov 14 13:03 222.txt

We could of course have just fixed that broken line in them makefile, but since this is such a bizarre way of building the functions anyway, let's fix it properly while we're at it.

**Comment by hlinnaka** [comment]
@xinzweb, can someone from the ORCA team have a look. please?

**Comment by hlinnaka** [comment]
Oh, just noticed that this also shrunk the final bin_gpdb.tar.gz file from 331.76 MB to 138.14 MB!

**Comment by vraghavan78** [comment]
@hlinnaka  331.76 MB -> 138.14 MB! Why? The thing that you removed should not have such a large impact. Thoughts?

**Comment by hlinnaka** [comment]
On 11/14/2016 11:43 PM, Venkatesh Raghavan wrote:
> @hlinnaka  331.76 MB -> 138.14 MB! Why? The thing that you removed should not have such a large impact. Thoughts?

It's because the broken copyoptimizerlibs step in gpAux/Makefile:

cd /tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel6_x86_64/lib64; tar cvf - 
| (cd /usr/local/greenplum-db-devel/lib; tar xfp -)


That was supposed to copy everything from 
/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel6_x86_64/lib64 to 
/usr/local/greenplum-db-devel/lib. But because the "cd" command fails, 
the current directory stays unchanged, and it copies everything from 
/tmp/build/f8c7ee08/gpdb_src/ instead. Oopsie..


- Heikki

**Comment by hlinnaka** [comment]
Thanks, pushed!

**Pull request closed without merging**
