### PR TITLE
build with orca

### PR DESCRIPTION
**Pull request by davecramer**
Just checking to see if this fails in travis

### CODE REVIEW

**Comment by davecramer** [comment]
@danielgustafsson any idea why configure doesn't complete here. I realize that it will require gporca will be required, but it doesn't even get that far ?

**Comment by danielgustafsson** [comment]
Well, it get's to where it's checking for GPOS which is a requirement for Orca. The failing line in autoconf is:
```
checking for gpos/_api.h... no
configure: error: GPOS header files are required for Pivotal Query Optimizer (orca)
```
Since GPOS et.al isn't available on Travis we need to run with `--disable-orca`. For it to work, Orca and the required libraries must be installed into the Travis container before the build. I don't see why that couldn't be done, no-one just spent the time to fix that yet (since Concourse is covering all the cases, Travis is more of a fast-turnaround compile check these days).

**Comment by davecramer** [comment]
@danielgustafsson I was more curious about https://travis-ci.org/greenplum-db/gpdb/builds/259844272#L1646

`include command not found` 

the thing is even with orca this fails

**Comment by danielgustafsson** [comment]
> On 03 Aug 2017, at 15:10, Dave Cramer <notifications@github.com> wrote:
> 
> @danielgustafsson I was more curious about https://travis-ci.org/greenplum-db/gpdb/builds/259844272#L1646
> 
> include command not found
> 
> the thing is even with orca this fails

Ah, thats a trivial syntax error which is fixed with https://github.com/greenplum-db/gpdb/pull/2659, it doesn’t affect building or autoconf though.

That being said, that PR has some weird side-effects that has blocked me from committing it.

**Comment by ashwinstar** [comment]
Seems nothing to be done here, was opened just for trying travis, closing the same.

**Pull request closed without merging**
