### PR TITLE
Unit test for lc_numeric instead of ICG

### PR DESCRIPTION
**Pull request by karthijrk**
This PR has two commits. 
1st commit will remove the lc_numeric_check icg. This is removed because some system missing the locale and we can also test this using unit test.
2nd commit add unit test to verify if lc_numeric_guc have appropriate setting (GUC_GPDB_ADDOPT) to verify if it can dispatch to QE process.

@armenatzoglou @gcaragea @foyzur Can you please take a look when you get chance.

### CODE REVIEW

**Comment by hlinnaka** [comment]
The new test seems pretty useless. It just checks that the flag is set. It doesn't check that it works correctly.

Do we have existing tests for dispatching GUCs in general? I'm not too worried about lc_numeric in particular. That was a simple bug-of-omission. Neither the lc_numeric_check nor the new unit test would catch a similar bug-of-omission for some other GUC. While it's of course possible that we would somehow accidentally remove the GUC_GPDB_ADDOPT from lc_numeric, it seems highly unlikely, and it doesn't seem any more likely to happen to lc_numeric than any of the other few dozen GUCs that are marked as GUC_GPDB_ADDOPT. What would be nice to have, however, is a regression test that tests that any GUCs that are marked as GUC_GPDB_ADDOPT are in fact dispatched correctly to segments. And for that, we wouldn't necessarily need to use lc_numeric, we could use any of the GUC_GPDB_ADDOPT gucs.

**Comment by ashwinstar** [comment]
Apart from checking if any of the GUC_GPDB_ADDOPT gets correctly dispatched
to segments,
seems important to brainstorm how can eliminate the need for manually
marking GUC with GUC_GPDB_ADDOPT.
Chances of that happening is super high and very tricky to catch.
Can we think on lines like any GUC with PGC_SUSET and PGC_USERSET should
always be GUC_GPDB_ADDOPT.


On Mon, May 9, 2016 at 2:30 PM, Heikki Linnakangas <notifications@github.com

**Comment by gcaragea** [comment]
I think unit testing the GUC dispatching mechanism is out of the scope of this fix. That mechanism has been in place for many years now and we have no reason to believe it is broken (to my knowledge).

**Comment by karthijrk** [comment]
I agree with @gcaragea. The guc's dispatch mechanism in place for many years and it is out of scope of this fix. 
I would like to keep this unit test. Reason is I learned that sometime back they removed this enum from certain gucs for performance reason and I don't want someone to remove this from lc_numeric for same or some other reason.

Coming to @ashwinstar point, I agree we need some better way to handle dispatching guc values than marking explicitly as GUC_GPDB_ADDOPT.

@foyzur @vraghavan78 @ashwinstar  Can you guys please work and see if we can come up with story for appropriate backlog ?

**Comment by ashwinstar** [comment]
Created issue (https://github.com/greenplum-db/gpdb/issues/743) to track if possibly can come-up with better way to handle dispatching guc values than marking explicitly as GUC_GPDB_ADDOPT.

**Comment by karthijrk** [comment]
Thanks @ashwinstar for creating an issue.

**Comment by karthijrk** [comment]
@hlinnaka Do you have any comments or concern based on my response?

**Comment by hlinnaka** [comment]
If you're worried that someone removes the flag to make things faster, perhaps just add a comment saying "please don't remove this or X won't work correctly". I still don't see the point of the mock test as proposed.

The original regression test was better in that it clearly demonstrates why the flag is needed, and would also fail if we had a bug where the GUC is not set correctly even though it's flagged. The only problem with it is that it depends on the specific locale. Is there any way to rewrite the original test in a more robust way? Instead of plain "SET lc_numeric = 'X'", perhaps write a little PL/pgSQL function that tries a whole bunch of different locales that use ',' as the decimal separator. And perhaps add an alternative expected output file for the case that no such locale is found, so that it still passes on such systems, even though it won't test anything useful in that case.

I totally agree with @ashwinstar that we should find a way to avoid future bugs-of-omission in this area; let's take that discussion to issue #743.

**Comment by hlinnaka** [comment]
(offtopic) I have a story related to decimal separators to tell. In my previous life, I used to work on a system that used a proprietary DBMS that shall not be named. The system dealt with price and product information for a supermarket chain, and sent prices of all the different products from a central database to the POS systems in the stores. One day, the users reported a funny problem: when you typed "2.99" in the application and clicked "save", and then reloaded the data, it came back as "2.00". Turns out that a particular version of the JDBC driver had a bug: if the server's locale was set to Finnish (or any other language that uses comma as decimal separator, I presume), it silently truncated decimal numbers on updates. That was a fun one to track down.

**Comment by karthijrk** [comment]
Thanks @hlinnaka for bring this again. 
I will not merge this unit test and add a comments on the guc. 
There is an issue created on how to handle GUC_Dispatch better and so I remove the existing non-portable icg test.

**Pull request closed without merging**
