### PR TITLE
add 'static' keyword in definition for some files under src/backend/cdb

### LINKED ISSUE #4884: consistent 'static' signature for some files under src/backend/cdb
eg: cdbgroup.c, cdbllize.c cdbmutate.c

Some functions have been declared as 'static', while lack of static keyword in definition, eg: make_subplan_tlist

### PR DESCRIPTION
**Pull request by krait007**
Under src/backend/cdb some functions have been declared as 'static', while lack of static keyword in definition, eg: cdbgroup.c  cdbheap.c
resolve #4884

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@krait007 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4895)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4895) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@krait007 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4895)!

**Comment by yydzero** [comment]
Thanks @krait007 for the contribution!

**Comment by yydzero** [comment]
Merge and closed

**Pull request merged**
