### PR TITLE
Update date ranges in admin guide to something more recent

### PR DESCRIPTION
**Pull request by andreasscherbaum**

### CODE REVIEW

**Comment by ascherbaum-pivotal** [comment]
@mkiyama Can you please have a look here?

The failing CI can't really be a problem, since CI is not checking the docs right now.

**Comment by mkiyama** [comment]
I'm not sure, but it looks like the an unrelated perfmon test failed for the build triggered by this PR.
As you said, I don't think a doc change can cause a build to fail.

I did notice that some of the file names in backup.xml are using the old format.
In the section "Restoring to a Different Greenplum System Configuration"

The new format uses the segment content ID. See the note at the end of this topic.
http://gpdb.docs.pivotal.io/43140/admin_guide/managing/backup-gpcrondump.html

**Comment by andreasscherbaum** [comment]
Can you open a separate PR/Issue for the filenames? This PR only deals with date updates.

If there are no objections, I will push this tomorrow.

**Comment by mkiyama** [comment]
ok

**Pull request merged**
