### PR TITLE
Move alert severity classification to callsite

### PR DESCRIPTION
**Pull request by danielgustafsson**
Alert sending was previously triggered by invoking `errSendAlert(true)` in the `ereport()` call. At the time of sending, the alerting code tried to figure out how important/interesting the error message in question was by string comparisons on the error message. This based was on a set of strings which were hard to keep in sync with the codebase, and rather suboptimal since the callsite where the error originated knows how severe the error in question is.

Convert `errSendAlert()` to take a severity level instead such that the callsite can instruct the alert sending code with how to handle the alert. All ereports that generated an alert have been updated to match the previous severity.

In the process, clean up style in a few `ereport()` calls, the alert code in general and avoid serializing the `elevel` in the syslog chunks (see separate commit for the latter one).

### CODE REVIEW

**Comment by ivannovick** [comment]
REALLY HAPPY to see this.  There is still some thinking left to do on how to rationalize this feature with PostgreSQL and also provide a similar functionality to what customers were given with this feature (SNMP alert).  Users feel its not customizable enough but also love thats all baked into the product without installing anything else.  We should have a discussion on the eventual state of send_alert

**Comment by danielgustafsson** [comment]
> On 06 Mar 2018, at 20:11, Ivan Novick <notifications@github.com> wrote:
> 
> REALLY HAPPY to see this. There is still some thinking left to do on how to rationalize this feature with PostgreSQL and also provide a similar functionality to what customers were given with this feature (SNMP alert). Users feel its not customizable enough but also love thats all baked into the product without installing anything else. We should have a discussion on the eventual state of send_alert

A deeper discussion on how it can be made more user friendly sounds like a good idea. This is intended to make it more predictable when an alert is sent and when not by removing the hardcoded heuristics in favor of simply telling send_alert at the time of logging.

**Comment by ivannovick** [comment]
understood

**Comment by ashwinstar** [comment]
@danielgustafsson seems good to get this in.

**Comment by danielgustafsson** [comment]
> On 22 Mar 2018, at 17:40, Ashwin Agrawal <notifications@github.com> wrote:
> 
> @danielgustafsson seems good to get this in.

There is a legitimate test failure that I need to fix first, I just haven’t had the time to address it yet. Will try and get to it soon.

**Comment by ashwinstar** [comment]
@danielgustafsson Welcome back, just wish to put this on top of your stack :-)

**Comment by danielgustafsson** [comment]
> On 14 May 2018, at 20:33, Ashwin Agrawal <notifications@github.com> wrote:
> 
> @danielgustafsson Welcome back, just wish to put this on top of your stack :-)

You’re too kind =) It’s good to be back, I’ll try to wrap this one up now.

**Comment by ashwinstar** [comment]
@danielgustafsson lets knock this off please.

**Comment by ashwinstar** [comment]
@danielgustafsson keeping this open for longer would result in unnecessary wastage of time resolving conflicts.

**Comment by danielgustafsson** [comment]
Closing this in favour of #6384

**Pull request closed without merging**
