### PR TITLE
Update gparray.py

### PR DESCRIPTION
**Pull request by water32**
Old code query instance's database data directory, one query per instance.
This will generate many logs to log file, example: gpstate
New code, query all data about database's data directory, map date to key -> array, then set to segments object.
So use one query replace many query avoid many times query in database.

### CODE REVIEW

**Comment by asimrp** [comment]
Good catch!  The benefit will be more apparent in large clusters, e.g. 500+ segments.  This PR reduces 500+ queries to 1, which is a great benefit.  👍

**Comment by andreasscherbaum** [comment]
Looks good.

Please let us know once you signed the CLA.
Thanks

**Comment by water32** [comment]
I have signed the CLA and have sent it to the CLA Email

**Comment by yydzero** [comment]
+1

**Comment by danielgustafsson** [comment]
Closing to get the bot to pick up CLA, will re-open again.

**Comment by danielgustafsson** [comment]
..and there was the CLA picked up, thanks for your contribution! @yydzero or @asimrp, can you help @water32 get this committed once you're happy with it?

**Comment by yydzero** [comment]
The check failed on OS-X, while I could not reproduce it on my local env. Will close and reopen it again so that travis will be retriggered.

**Comment by yydzero** [comment]
Merged and closed. Thanks water32.

**Pull request closed without merging**
