### PR TITLE
Make sure CallXactCallbacksOnce are executed during preparetransaction     as well.

### PR DESCRIPTION
**Pull request by karthijrk**
`BFZ` data structure uses `DataSource` context for its memory. `DataSource` Context is allocated on `TopTransactionMemoryContext`. If there are any unfreed `BFZ` data structure exist at the end of the transaction, we will clean up those using `CallXactCallbacksOnce` in `Commit / Abort` transaction.

**Problem** 
During PrepareTransaction we delete the `TopTransactionMemoryContext` and thereby `DataSourceContext`. This happens before we do the clean up for `BFZ` data structure. Later when we do the clean up in `CommitTransaction` for instance, we crash because we try to free `BFZ` data structure but `DataSourceContext` is freed already.

**Proposal in this PR**
We change `CallXactCallbacksOnce` to do the clean up in `PrepareTransaction` itself. This way we made sure that we delete the `BFZ` data structure before `TopTransactionMemoryContext / DataSource` context get deleted.

All of the registered callbacks are just for cleaning up temp files / data structures including `BFZ`. So it is ok to delete those files during `PrepareTransaction`. 

`CallXactCallbacksOnce`  can potentially call following callbacks as of now.
```
1. bfz_close_callback -- Clean up BFZ files
2. XCallBack_NTS -> ntuplestore_cleanup -- Clean up tuplestore data structure and workfiles.
3. XCallBack_ShareInput_FIFO -> shareinput_clean_lk_ctxt -- Clean up temporary fifo files.
```

@foyzur @armenatzoglou @hardikar @asimrp @hlinnaka Could you please take a look at this PR.

### CODE REVIEW

**Comment by hlinnaka** [comment]
We really should switch to using the ResourceOwner mechanism for this.

**Comment by karthijrk** [comment]
We are also thinking along this line and have a story in our backlog. https://www.pivotaltracker.com/story/show/134182959

For now, preferred to have a simple fix for the customer escalation and then refactor BFZ to use resource owner.

**Comment by hlinnaka** [comment]
On 12/07/2016 12:33 PM, Karthikeyan Jambu Rajaraman wrote:
> We are also thinking along this line and have a story in our backlog. https://www.pivotaltracker.com/story/show/134182959
>
> For now, preferred to have a simple fix for the customer escalation and then refactor BFZ to use resource owner.

*shrug*. Well, you tagged me, so I assume you wanted my opinion. In my 
opinion, this current mechanism is very error-prone, and you should do 
this refactoring now, to avoid yet more bugs like this.

- Heikki

**Comment by karthijrk** [comment]
@hlinnaka In the case of ResourceOwner, those clean up will still be called in PrepareTransaction right ?

**Comment by hlinnaka** [comment]
On 12/07/2016 12:49 PM, Karthikeyan Jambu Rajaraman wrote:
> @hlinnaka In the case of ResourceOwner, those clean up will still be called in PrepareTransaction right ?

Sure.

- Heikki

**Comment by karthijrk** [comment]
Thanks @hlinnaka for your inputs. I will close this PR without merging and see how we can leverage `ResourceOwner` .

**Pull request closed without merging**
