### PR TITLE
WIP: Make the GET DIAGNOSTICS counter 64 bit safe

### PR DESCRIPTION
**Pull request by andreasscherbaum**
Along the way update all places which work with the
number of tuples, one way or another.

### CODE REVIEW

**Comment by ivannovick** [comment]
is this a catalog change?  Very cool if we can get this highly requested capability merged in

**Comment by andreasscherbaum** [comment]
So far it's not a catalog change, at least I'm not aware that I changed anything which requries a catalog update. Did you spot something?

But it touches quite a few places.

**Comment by ivannovick** [comment]
@asimrp @yydzero @pivotal-mike can you help review?

**Comment by Eulerizeit** [comment]
Ivan,

As an FYI, we actually need a bit more than review on this, we need to
figure out a testing strategy that is feasible.

-- Rob

**Comment by ivannovick** [comment]
i see...

**Comment by ivannovick** [comment]
@schubert whats your thoughts on getting this merged?  It has been requested by a number of users(customers)....

**Comment by ashwinstar** [comment]
@andreasscherbaum Is anything happening here or things moved to https://github.com/greenplum-db/gpdb/pull/2679 and this can be closed out.

**Comment by andreasscherbaum** [comment]
This one can be closed, it's screwed.

**Pull request closed without merging**
