### PR TITLE
Remove 'Workfile caching' incomplete feature

### PR DESCRIPTION
**Pull request by gcaragea**
Workfile caching is an incomplete feature, which needs full versioning of metadata and data. Providing versioning is not currently on our roadmap, so removing this feature from the codebase until we revisit that.

### CODE REVIEW

**Comment by gcaragea** [comment]
@armenatzoglou @karthijrk please take a look.

**Comment by hlinnaka** [comment]
>  20 files changed, 111 insertions(+), 1193 deletions(-)

That's the kind of  patch I like :-). +1 from me

**Comment by hlinnaka** [comment]
The workfile manager is the only user of the src/backend/utils/cache/sharedcache.c facility. These patches don't remove all the calls to that facility, but I wonder if we could replace the remaining calls with a simple backend-local hash table? There is no need for any of the workfile information to live in shared memory after this, is there?

**Comment by gcaragea** [comment]
@hlinnaka I thought about that too. There are a number of views in gp_toolkit that access the sharedcache and list *all* the workfiles used in the system. So the information needs to be in shared memory for that to work. 
The middle ground could be to use a shared memory dynahash instead of the cache. How does that sound?

**Comment by hlinnaka** [comment]
On 18/12/15 23:54, George Caragea wrote:
> @hlinnaka I thought about that too. There are a number of views in gp_toolkit that access the sharedcache and list *all* the workfiles used in the system. So the information needs to be in shared memory for that to work.

Ok. Do people find those views useful? Could we remove them? You don't 
generally get very good visibility to what individual backends are 
doing, so I wonder how useful viewing just work files is.

> The middle ground could be to use a shared memory dynahash instead of the cache. How does that sound?

Ah yeah, that'd be better than having a whole separate implementation 
(hmm, I wonder why a shmem dynahash was not used in the first place).

- Heikki

**Comment by gcaragea** [comment]
On Fri, Dec 18, 2015 at 2:06 PM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 18/12/15 23:54, George Caragea wrote:
> > @hlinnaka I thought about that too. There are a number of views in
> gp_toolkit that access the sharedcache and list *all* the workfiles used in
> the system. So the information needs to be in shared memory for that to
> work.
>
> Ok. Do people find those views useful? Could we remove them? You don't
> generally get very good visibility to what individual backends are
> doing, so I wonder how useful viewing just work files is.
>
>
Last I heard, customers are using the views, and they are documented, so I
wouldn't remove them unless we had a very compelling reason. We also have
some GUCs to control the total amount of disk space allowed for spilling,
and those are definitely used by customers.



> > The middle ground could be to use a shared memory dynahash instead of
> the cache. How does that sound?
>
> Ah yeah, that'd be better than having a whole separate implementation
> (hmm, I wonder why a shmem dynahash was not used in the first place).
>
>

Using an actual cache vs dynahash was dictated by workfile caching
requirements. We wanted an eviction policy, as well as the ability to store
multiple entries with the same key (something dynahash doesn't have).

**Comment by karthijrk** [comment]
LGTM :+1:

**Comment by armenatzoglou** [comment]
LGTM

**Comment by gcaragea** [comment]
Pushed code. Closing.

**Pull request closed without merging**
