### PR TITLE
Remove useless 'initdb' bugbuster test

### PR DESCRIPTION
**Pull request by hlinnaka**
AFAICS, this test isn't accomplishing anything useful. All the output is ignored.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Agreed, :+1:

**Comment by ivannovick** [comment]
Hi Daniel, welcome to GPDB :)

**Comment by davecramer** [comment]
Hi Daniel,

Welcome. I gather you have officially started ?

Dave Cramer

**Comment by danielgustafsson** [comment]
Not just yet, in a couple of weeks.. but I couldn't stay away and let you have all the fun!

**Comment by hlinnaka** [comment]
Pushed.

**Pull request closed without merging**
