### PR TITLE
change vacuum to analyze, drop needless vacuum full

### PR DESCRIPTION
**Pull request by davecramer**

### CODE REVIEW

**Comment by Eulerizeit** [comment]
@asimrp or @slari-pivotal could you take a look at this please.

**Comment by davecramer** [comment]
The intention is to speed up the test. What does vacuum do in the
bitmap_index ?

Dave Cramer

**Comment by asimrp** [comment]
Sorry for the delayed response, how much speed up are we talking about here?  Vacuum and analyze take altogether different code paths.  Replacing one with another alters meaning of the test.

**Comment by davecramer** [comment]
vacuum full after inserting only does nothing,as does vacuum. Unless you
are actually testing some part of the code path?

Dave Cramer

**Comment by asimrp** [comment]
Yes, for AO, the tests using vacuum intend to test the AO specific vacuum code path.  I guess it's the same for bitmap index tests also.

**Comment by davecramer** [comment]
So if all you have done is insert, what is there to remove in AO or a
bitmap for that matter ?

Dave Cramer

**Comment by asimrp** [comment]
Agree, vacuum right after insert doesn't make sense.  It can be removed altogether.

**Comment by asimrp** [comment]
@davecramer many of the changes in this PR are not correct, in that they alter the meaning of the test.  Only those where vacuum is replaced with analyze right after insert may be correct.  But are we getting any significant performance gain with that?  If not, let's close this PR.

**Comment by pivotal-mike** [comment]
@asimrp @davecramer Are we OK to close this PR?

**Comment by asimrp** [comment]
I support closing this PR.

**Comment by ashwinstar** [comment]
Closing in current form doesn't seem we can get it in anyway, please feel free to submit modified PR.

**Pull request closed without merging**
