### PR TITLE
Save the complete slot data in ExecMaterializeSlot()

### LINKED ISSUE #8143: FDW panics if sends ctid queries to remote
### Greenplum version or build
```
PostgreSQL 9.4.20 (Greenplum Database 7.0.0-alpha.0+dev.198.g9a0d676208 build dev)
```

### Actual behavior
```
gpadmin=# SELECT ctid, * FROM ft1 LIMIT 1;
ERROR:  Unexpected internal error (execTuples.c:1524)  (seg0 slice1 10.152.10.181:40000 pid=22562) (execTuples.c:1524)
DETAIL:  FailedAssertion("!(((bool) (((const void*)(&(htup->t_self)) != ((void *)0)) && ((&(htup->t_self))->ip_posid != 0))))", File: "execTuples.c", Line: 1524)
HINT:  Process 22562 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
```
### Step to reproduce the behavior
1. set up a postgres_fdw foreign table
```
create table t1 (c1 int);
create extension postgres_fdw;
create server loopback foreign data wrapper postgres_fdw options (host '127.0.0.1', port '15432', dbname 'gpadmin');
create user mapping for gpadmin server loopback options (user 'gpadmin');
create foreign table ft1 (c1 int) server loopback options (schema_name 'public', table_name 't1');
```
2. select ctid from the foreign table
```
SELECT ctid, * FROM ft1 LIMIT 1;
```

### PR DESCRIPTION
**Pull request by adam8157**
ExecMaterializeSlot() transformed any tuple to a virtual tuple via
slot_getallattrs(), then form a heaptuple from it, ctid was lost here
since virtual tuples have no system columns.

This commit copies the entire htup directly if we have a regular
physical tuple but not locally palloc'd.

Fix #8143

### CODE REVIEW

**Comment by adam8157** [comment]
We also could set the ctid after like below, but the virtual tuple stage seems useless.

```
+       if (TupHasHeapTuple(slot) && ItemPointerIsValid(&(slot->PRIVATE_tts_heaptuple->t_self)))
+               htup->t_self = slot->PRIVATE_tts_heaptuple->t_self;
```

**Comment by hlinnaka** [comment]
Please note that ExecMaterializeSlot() is an upstream function. It'd be good to explain in a comment why it's different in GPDB. Also, please add a comment to explain that CTID must be preserved, otherwise someone might just remove the "else" block again, thinking that the slot_getallattrs() method will do the job just fine.

Also, can we have a test case included in the regression suite for this, please?

**Comment by adam8157** [comment]
Added some comments, but I still need some suggestions about why ExecMaterializeSlot() is different, my comments are probably not explaining well.

And the test case, for now, I suppose it's better to cover it by an FDW's case (postgres_fdw already covers).

**Comment by adam8157** [comment]
Only opened backporting PR for 6X: #8241

**Pull request merged**
