### PR TITLE
Update PyGreSQL from pre-release to 5.2.0

### PR DESCRIPTION
**Pull request by tylarb**
PyGreSQL 5.2.0 which contains the fixes submitted and referenced in commit
cb8d54a6b7872ad1be8bf3e1350aedf5edbe4a82 was released on June 21, 2020.

Update the build process to use this tagged release rather than a
pre-release hash

Authored-by: Tyler Ramer <tramer@vmware.com>

### CODE REVIEW

**Comment by tylarb** [comment]
psutil is updated as well in the pythonsrc/ext from PR https://github.com/greenplum-db/gpdb/pull/10339 

Until we get a better python dependency management, I'm afraid this kind of collision may happen when updating several libraries at once.

**Comment by ashwinstar** [comment]
So nice to see usage of latest released software :+1:

**Comment by tylarb** [comment]
1) Prior, pygresql was vendored in the greenplum-db/gpdb repo - see commit https://github.com/greenplum-db/gpdb/commit/f5758021be347aea069c3ef930bae6354a2dd8db where it was removed. 

2) I do not know where the licence is held for pygresql. @kmacoskey  might know more? 

3) per commit/PR https://github.com/greenplum-db/gpdb/pull/10310, we documented how to get pygresql - the update to 5.2.0 just fixes a small bug which we submitted a patch for, which is now in 5.2.0

**Comment by kmacoskey** [comment]
> 2). Do we need to add this license to the OSL process since we are now incorporating the distribution explicitly?

Eventually, yes. But that's a future problem when we get to distributions of Greenplum 7. It could potentially change depending on what the final runtime requirements and subsequent vendoring might look like once closer to a Greenplum 7 GA. In terms of how that would actually be included it is unlikely it would need to come from anything within https://github.com/greenplum-db/gpdb . The choice to vendor in a binary distribution being separated from any choice to vendor from a source code only perpsective.

**Pull request merged**
