### PR TITLE
replace pgsql-bugs@postgresql.org with bugs@greenplum.org

### PR DESCRIPTION
**Pull request by andreasscherbaum**
This patch touches all 3 files in the backend directory
which have the string pgsql-bugs@postgresql.org

### CODE REVIEW

**Comment by hlinnaka** [comment]
Can you squash all these changes to one, changing all the references in one go? There's not much point changing only some of them.

**Comment by andreasscherbaum** [comment]
I'm pretty sure some of them will fail, because the expected output changes.
Since we don't merge, one can always pick patches from several pull requests and commit them at once.

**Comment by ashwinstar** [comment]
On Wed, Nov 11, 2015 at 5:25 AM, Andreas Scherbaum <notifications@github.com
> wrote:

> I'm pretty sure some of them will fail, because the expected output
> changes.
>
If we are sure its going to fail the tests, then tests needs to be fixed as
well as part of same commit.

**Comment by andreasscherbaum** [comment]
@ashwinstar Oh, I totally agree. But the way to find out is by having the bot run all the tests for the pull request ;-)

**Comment by ashwinstar** [comment]
On Thu, Nov 12, 2015 at 10:57 AM, Andreas Scherbaum <
notifications@github.com> wrote:

> @ashwinstar <https://github.com/ashwinstar> Oh, I totally agree. But the
> way to find out is by having the bot run all the tests for the pull request
> ;-)
>
Does the bot run all the tests ?

**Comment by andreasscherbaum** [comment]
This is on my todo list to talk with Ed - next week.

**Comment by ashwinstar** [comment]
Confirmed with Ed, currently it just does build no test run.
Plus, even in future it maybe does installcheck and bugbuster, still these
should be run on laptop before submitting pull requests I believe.

**Pull request closed without merging**
