### PR TITLE
cdbfast gist_indexes test migration to ICG [#116157035]

### PR DESCRIPTION
**Pull request by oarap**
There are 4 different test suites for gist_indexes.
First suite is already in bugbuster and there was no need to migrate that suite.
Second suite is run in nested `for` loops for to test different WITH clauses. Therefore, to be able to test every condition, the tables are created differently and appended duplicated tests in the same file. 
Third and forth suite basically runs back to back queries.

### CODE REVIEW

**Comment by oarap** [comment]
@vraghavan78, @xinzweb, @hsyuan Could you please take a look at this PR?

**Comment by hsyuan** [comment]
+1

**Comment by xinzweb** [comment]
+1

**Comment by oarap** [comment]
merged, thanks.

**Pull request closed without merging**
