### PR TITLE
pg_dump: correct OID preassignment for AO tables and subpartitions

### PR DESCRIPTION
**Pull request by jchampio**
OID preassignment was missing for the AO auxiliary tables (segrel, blkdir, visimap) as well as for the `pg_type` entries of partition members. Add them back.

This fixes the pg_upgrade smoke tests for AO tables; the code that dropped them can now be removed.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
This now errored out on `old and new databases "dsp3" have a mismatched number of relations`, would the debugging commit you mentioned display the diff for that @jchampio ?

**Comment by jchampio** [comment]
@danielgustafsson So it does... I wonder why we can't reproduce that on my MacBook.
>would the debugging commit you mentioned display the diff for that @jchampio ?

Yes! I will pull that in.

**Comment by jchampio** [comment]
```
No match found in new cluster for old relation with OID 200912 in database "dsp3": "pg_toast.pg_toast_200910" which is the TOAST table for "public.alter_table_reorg_aoco"
No match found in new cluster for old relation with OID 200914 in database "dsp3": "pg_toast.pg_toast_200910_index" which is an index on "pg_toast.pg_toast_200910" which is the TOAST table for "public.alter_table_reorg_aoco"
```
Looks like a similar problem to the one that made us add [this line](https://github.com/greenplum-db/gpdb/blob/master/contrib/pg_upgrade/test_gpdb_pre.sql#L148) to the drop. I will add that to the list.

**Comment by danielgustafsson** [comment]
Adding that made it go one step further, which in this case means blowing up on many more of the same in the `regression` database.

**Comment by jchampio** [comment]
(For those following along, looks like we'll need to fix the missing-TOAST table problem at the same time as this bug, which means we'll probably need to modify this solution.)

**Comment by Eulerizeit** [comment]
Thanks for the heads up

**Comment by jchampio** [comment]
Thanks for the reviews! It's looking like this commit isn't enough -- it exacerbates the "missing table" problem in the new cluster, since the new AO aux tables aren't being correctly named -- and enough is changing in the followup commits that I'm going to close this and reopen a separate PR once we've solved both problems.

**Pull request closed without merging**
