### PR TITLE
Fix parser to understand case in group by

### PR DESCRIPTION
**Pull request by karthijrk**
Parser was complaining if there is ```case``` & ```when is not distinct from``` in ```group by```. This is fixed in this PR and added icg.

@foyzur @armenatzoglou @gcaragea @hardikar Please take a look when you get chance.

### CODE REVIEW

**Comment by vraghavan78** [comment]
LGTM

**Comment by karthijrk** [comment]
@yydzero I made a small change in parser. Could you or your team please take a look to see if they are fine as well.

**Comment by atris** [comment]
I am trying to understand the original problem here. Is the issue that we are scribbling on the original input?

**Comment by gcaragea** [comment]
On Thu, Jun 2, 2016 at 10:44 AM, Atri Sharma <notifications@github.com>
wrote:

> I am trying to understand the original problem here. Is the issue that we
> are scribbling on the original input?
>
>
Correct. We call isWhenIsNotDistinctFromExpr() a few times during parsing
(for whatever reason), so it seems to be wrong to modify it in place here,
as it will affect the result of this call.

**Comment by atris** [comment]
I see.
+1

**Comment by hlinnaka** [comment]
'case' regression test is inherited from upstream. Please put the new regression tests to 'case_gp' instead, to keep 'case' unmodified from upstream version.

The new comment seems a bit excessive, given that it's a common rule for all transform* functions that they mustn't modify the input.

Other than that, LGTM.

**Comment by karthijrk** [comment]
Oh, I didn't notice there is case_gp. Let me move the test to case_gp and push to master. Thanks all for the review.

**Pull request closed without merging**
