### PR TITLE
Tolerate EPERM return from sendto().

### PR DESCRIPTION
**Pull request by hlinnaka**
When running the regression tests on my laptop, I frequently got errors like this, during parallel groups where a lot of heavy queries are running at the same time:

```
! ERROR:  Interconnect error writing an outgoing packet: Operation not permitted
! DETAIL:  
! error during sendto() call (error:1).
! For Remote Connection: contentId=1 at 127.0.0.1:32779
```

I tracked that down to a local iptables based firewall (ufw). If I disabled iptables, the error goes away. The firewall rules allowed all traffic, but the mere presence of the firewall was enough to cause a problem.

It turns out that iptables can cause an EPERM to be returned from sendto(), if there is a lot of congestion. Our code treats that as a fatal error, even though it's really just a sign that there is congestion. To fix, don't give up on EPERM, but treat it the same as EAGAIN and keep trying (except that it is logged, to help debugging network issues).

A firewall is perhaps not a good idea for a production system, if you want to squeeze out every last drop of performance from the system. But it's very common in testing and development environments, and surely not unheard of in production either, so let's handle that gracefully.

I searched around a bit for previous reports of the same problem, and found MPP-22308. That ticket was logged in 2014, from a DCA stress test environment. They got the same error, and it was resolved by disabling the firewall. So this is real-world problem, not just on my laptop.

### CODE REVIEW

**Comment by ivannovick** [comment]
Yes this is a common problem found by users, and I think this fix/change is welcome.  (assuming it works)

Thx!

**Comment by danielgustafsson** [comment]
This seems reasonable, :+1: on getting it in. Do we run a risk of flooding the logs during congestion such that the loglevel should be set higher to avoid lots of IO?

Out of curiosity, if connection tracking is disabled for the ports in use by GPDB, does the error persist? If so then perhaps recommending that rather than turning firewalls of for production would be a good documentation addition.

**Comment by hlinnaka** [comment]
On 11/22/2016 08:35 AM, Daniel Gustafsson wrote:
> This seems reasonable, :+1: on getting it in. Do we run a risk of
> flooding the logs during congestion such that the loglevel should be
> set higher to avoid lots of IO?

I'm not 100% sure, but I think it's self-limiting. There is a "transmit 
window" of some sorts, so if there are too many  un-ACKed packets 
(because we failed to send the message in the first place), we will 
refrain from sending more. I guess we might print a lot of messages, but 
not an unbounded, 100% CPU sucking flood.

On my laptop, with this patch, I only see the messages very 
occasionally, never more than one at a time.

I considered adding logic to suppress the log message, if the previous 
sendto() call also failed with EPERM. But I couldn't figure out an easy 
way to implement that.

> Out of curiosity, if connection tracking is disabled for the ports in
> use by GPDB, does the error persist? If so then perhaps recommending
> that rather than turning firewalls of for production would be a good
> documentation addition.

At first, I tried doing "ufw disable", but that didn't help. Turns out 
that that only replaces the iptables rules with "allow anything". See 
attached. With no iptables rules at all, the errors did not occur. I'm 
not sure what exactly might be required to avoid the problem.

Hmm, now that I look at the iptables output, I notice that I also have 
Docker-related rules there. I installed docker only recently, and I seem 
to remember that "ufw disable" did help earlier when I had the same 
issue. Perhaps it's the Docker's "accept anything" ctstate rule that's 
causing the trouble this time.

- Heikki

$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ufw-before-logging-input  all  --  anywhere             anywhere            
ufw-before-input  all  --  anywhere             anywhere            
ufw-after-input  all  --  anywhere             anywhere            
ufw-after-logging-input  all  --  anywhere             anywhere            
ufw-reject-input  all  --  anywhere             anywhere            
ufw-track-input  all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ufw-before-logging-forward  all  --  anywhere             anywhere            
ufw-before-forward  all  --  anywhere             anywhere            
ufw-after-forward  all  --  anywhere             anywhere            
ufw-after-logging-forward  all  --  anywhere             anywhere            
ufw-reject-forward  all  --  anywhere             anywhere            
ufw-track-forward  all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ufw-before-logging-output  all  --  anywhere             anywhere            
ufw-before-output  all  --  anywhere             anywhere            
ufw-after-output  all  --  anywhere             anywhere            
ufw-after-logging-output  all  --  anywhere             anywhere            
ufw-reject-output  all  --  anywhere             anywhere            
ufw-track-output  all  --  anywhere             anywhere            

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain ufw-after-forward (1 references)
target     prot opt source               destination         

Chain ufw-after-input (1 references)
target     prot opt source               destination         

Chain ufw-after-logging-forward (1 references)
target     prot opt source               destination         

Chain ufw-after-logging-input (1 references)
target     prot opt source               destination         

Chain ufw-after-logging-output (1 references)
target     prot opt source               destination         

Chain ufw-after-output (1 references)
target     prot opt source               destination         

Chain ufw-before-forward (1 references)
target     prot opt source               destination         

Chain ufw-before-input (1 references)
target     prot opt source               destination         

Chain ufw-before-logging-forward (1 references)
target     prot opt source               destination         

Chain ufw-before-logging-input (1 references)
target     prot opt source               destination         

Chain ufw-before-logging-output (1 references)
target     prot opt source               destination         

Chain ufw-before-output (1 references)
target     prot opt source               destination         

Chain ufw-reject-forward (1 references)
target     prot opt source               destination         

Chain ufw-reject-input (1 references)
target     prot opt source               destination         

Chain ufw-reject-output (1 references)
target     prot opt source               destination         

Chain ufw-track-forward (1 references)
target     prot opt source               destination         

Chain ufw-track-input (1 references)
target     prot opt source               destination         

Chain ufw-track-output (1 references)
target     prot opt source               destination

**Comment by hlinnaka** [comment]
Ok, pushed.

**Pull request closed without merging**
