### PR TITLE
Remove all host all all entries in segment pg_hba.conf

### PR DESCRIPTION
**Pull request by Aegeaner**
Vulnerabilities exist due to pg_hba.conf file in all segment servers containing "host all all" entries. The master node doesn't have this issue.

The segments can communicate with each other normally under the `gpadmin` user or any other configured user for greenplum database, so it's safe to remove the `all` user entries to harden the cluster.

Users never touched pg_hba.conf file except allowed default installation configuration. They were generated by the management scripts.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by adam8157** [comment]
After this, there is no entry for other users in the segment's pg_hba.conf? And other users could query?

**Comment by SmartKeyerror** [comment]
IMO, I don't think it's reasonable that when we create a new role and need to change the segments' pg_hba.conf. Greenplum is a cluster, details of communication between the coordinator and segment should be shielded from the outside world.

**Comment by Aegeaner** [comment]
> IMO, I don't think it's reasonable that when we create a new role and need to change the segments' pg_hba.conf. Greenplum is a cluster, details of communication between the coordinator and segment should be shielded from the outside world.

This worry is not necessory since for internal communications, libpq short-circuited the authentication between QD and QE:

https://github.com/greenplum-db/gpdb/blob/d9eb9633cb046f34ba2a6f0dbbe1940c94bfd843/src/backend/libpq/auth.c#L647~L656

```
/*
	 * If this is a QD to QE connection, we might be able to short circuit
	 * client authentication.
	 */
	if (is_internal_gpdb_conn(port))
	{
		if (internal_client_authentication(port))
			return;

		/* Else, try the normal authentication */
	}
```
So it won't go to the following HBA authentication at:
https://github.com/greenplum-db/gpdb/blob/d9eb9633cb046f34ba2a6f0dbbe1940c94bfd843/src/backend/libpq/auth.c#L664

**Comment by interma** [comment]
> This worry is not necessory since for internal communications, libpq short-circuited the authentication between QD and QE:

So looks no need to keep "host all all ... trust" records in segment's pg_hba.conf? If remove all, need to care about if exists remote utility-mode psql connection in tests.

**Comment by adam8157** [comment]
So there are no vulnerabilities actually, or the user is supposed to isolate the network for the internal libpq vulnerabilities, I prefer to explain to whom it may concern.

**Pull request closed without merging**
