### PR TITLE
Change PORT_BASE semantics for demo cluster (6X_STABLE)

### PR DESCRIPTION
**Pull request by ashwinstar**
Backport from master, for 6X_STABLE setting `PORT_BASE = 6000`.

---
Previously, three different environment variables were required to
modify ports to be used by demo cluster. I think that's unnecessary
and such flexibility comes at greater cost for developers, instead
better to have only one environment variable to help provide the
flexibility. Hence, removing MASTER_PORT and STANDBY_PORT
variables. Now, only PORT_BASE is used. This becomes the starting port
number and master port number. All other required port numbers for
demo cluster are sequential to it, including standby port, followed by
primaries and mirrors.

Also, very often need to create demo cluster across different GPDB
versions. So, would be helpful to have PORT_BASE default set to not
conflict across different GPDB versions. Hence, using 7000 as this is
GPDB7 branch. For GPDB6 we can have it start at 6000 and GPDB5 at
5000. I think that makes it easy to remember as well and shorter to
type as well compared to 5 digits previously used :-)

Co-authored-by: Bhuvnesh Chaudhary <bhuvnesh2703@gmail.com>
(cherry picked from commit 704d2bdcab3b3ba413abb1aaebbb365e487ca79c)

### CODE REVIEW

**Comment by frankgh** [comment]
@oliverralbertini @denalex when this commit goes in, it will break our pipelines. Let's be on the lookout when this happens

**Comment by ashwinstar** [comment]
Just FYI, I am planning to commit this change on Monday. So, that it gives us enough time to react to possible changes as required.

**Comment by berlin-ab** [comment]
Looking forward to this :)

**Comment by ashwinstar** [comment]
Pipelines have been very shaky and hence didn't wish to take any chances in-middle of it for this. Will see how things are next week and commit if they are more stable.

**Pull request merged**
