### PR TITLE
docs - add content for new gp_resource_group_queuing_timeout guc

### PR DESCRIPTION
**Pull request by lisakowen**
in this PR:
- add reference for new guc gp_resource_group_queuing_timeout; add to appropriate guc category and subnavs
- update the main "using resource groups" topic to mention this new guc
- misc edit to a subtopic title on the using page

### CODE REVIEW

**Comment by gaos1** [comment]
LGTM. Thanks. cc @xiong-gang

**Comment by adam8157** [comment]
I see this doc on 5X, but the code change is not in https://github.com/greenplum-db/gpdb/pull/9847

@wuj21 @lisakowen What should we do? Revert the doc on 5X or merge the code into 5X?

**Comment by lisakowen** [comment]
thanks @adam8157 . not sure how we ended up with docs for the gp_resource_group_queuing_timeout guc in 5.x.  we can remove the docs.

**Comment by adam8157** [comment]
Please remove it from 5X, thanks.

**Pull request merged**
