### PR TITLE
Be more wary about NULL values for GUC string variables.

### PR DESCRIPTION
**Pull request by Aegeaner**
This PR cherry-picked two commits from upstream, about being more wary about NULL values for GUC string variables.

- Commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=0bc726d95a305ca923b1f284159f40f0d5cf5725
- Commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=7704a1a72e879daaefa1742916e01505edd2ce47
- Background issue reported: https://github.com/greenplum-db/gpdb/issues/16502
- Related PR: https://github.com/greenplum-db/gpdb/pull/16504
- Upstream discussion: https://www.postgresql.org/message-id/flat/CACpMh%2BAyDx5YUpPaAgzVwC1d8zfOL4JoD-uyFDnNSa1z0EsDQQ%40mail.gmail.com

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by higuoxing — APPROVED** [review]
LGTM!

**Comment by kainwen** [comment]
I think we need to keep author not changed. 


```
gpadmin@gpdev:~/workspace/gpdb$ git log
commit 85cae6cd8239f0fda2138d4087b9eee3704984f9 (HEAD -> guc_null_value)
Author: Tom Lane <tgl@sss.pgh.pa.us>
Date:   Thu Nov 2 11:53:36 2023 -0400

    Make GetConfigOption/GetConfigOptionResetString return "" for NULL.

    As per the preceding commit, GUC APIs generally expose NULL-valued
    string variables as empty strings.  Extend that policy to
    GetConfigOption() and GetConfigOptionResetString(), eliminating
    a crash hazard for unwary callers, as well as a fundamental
    ambiguity in GetConfigOption()'s API.

    No back-patch, since this is an API change and conceivably somebody
    somewhere is depending on this corner case.

    Xing Guo, Aleksander Alekseev, Tom Lane

    Discussion: https://postgr.es/m/CACpMh+AyDx5YUpPaAgzVwC1d8zfOL4JoD-uyFDnNSa1z0EsDQQ@mail.gmail.com

commit 09e143430d56da41d8343f7a9e50929a188276c4
Author: Jian Guo <gjian@vmware.com>
Date:   Fri Nov 3 05:04:49 2023 -0400

    Be more wary about NULL values for GUC string variables.

    get_explain_guc_options() crashed if a string GUC marked GUC_EXPLAIN
    has a NULL boot_val.  Nosing around found a couple of other places
    that seemed insufficiently cautious about NULL string values, although
    those are likely unreachable in practice.  Add some commentary
    defining the expectations for NULL values of string variables,
    in hopes of forestalling future additions of more such bugs.

    Xing Guo, Aleksander Alekseev, Tom Lane

    Upstream commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=7704a1a72e879daaefa1742916e01505edd2ce47
    Discussion: https://postgr.es/m/CACpMh+AyDx5YUpPaAgzVwC1d8zfOL4JoD-uyFDnNSa1z0EsDQQ@mail.gmail.com
```

**Comment by kainwen** [comment]
Question: are these two commits very clean cherry-pick or they have conflicts?

**Comment by Aegeaner** [comment]
> I think we need to keep author not changed.
> 
> ```
> gpadmin@gpdev:~/workspace/gpdb$ git log
> commit 85cae6cd8239f0fda2138d4087b9eee3704984f9 (HEAD -> guc_null_value)
> Author: Tom Lane <tgl@sss.pgh.pa.us>
> Date:   Thu Nov 2 11:53:36 2023 -0400
> 
>     Make GetConfigOption/GetConfigOptionResetString return "" for NULL.
> 
>     As per the preceding commit, GUC APIs generally expose NULL-valued
>     string variables as empty strings.  Extend that policy to
>     GetConfigOption() and GetConfigOptionResetString(), eliminating
>     a crash hazard for unwary callers, as well as a fundamental
>     ambiguity in GetConfigOption()'s API.
> 
>     No back-patch, since this is an API change and conceivably somebody
>     somewhere is depending on this corner case.
> 
>     Xing Guo, Aleksander Alekseev, Tom Lane
> 
>     Discussion: https://postgr.es/m/CACpMh+AyDx5YUpPaAgzVwC1d8zfOL4JoD-uyFDnNSa1z0EsDQQ@mail.gmail.com
> 
> commit 09e143430d56da41d8343f7a9e50929a188276c4
> Author: Jian Guo <gjian@vmware.com>
> Date:   Fri Nov 3 05:04:49 2023 -0400
> 
>     Be more wary about NULL values for GUC string variables.
> 
>     get_explain_guc_options() crashed if a string GUC marked GUC_EXPLAIN
>     has a NULL boot_val.  Nosing around found a couple of other places
>     that seemed insufficiently cautious about NULL string values, although
>     those are likely unreachable in practice.  Add some commentary
>     defining the expectations for NULL values of string variables,
>     in hopes of forestalling future additions of more such bugs.
> 
>     Xing Guo, Aleksander Alekseev, Tom Lane
> 
>     Upstream commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=7704a1a72e879daaefa1742916e01505edd2ce47
>     Discussion: https://postgr.es/m/CACpMh+AyDx5YUpPaAgzVwC1d8zfOL4JoD-uyFDnNSa1z0EsDQQ@mail.gmail.com
> ```

Restored original commit author info.

**Comment by Aegeaner** [comment]
> Question: are these two commits very clean cherry-pick or they have conflicts?

The  [`Be more wary about NULL values for GUC string variables`](https://github.com/greenplum-db/gpdb/pull/16694/commits/6650488de782e7974fac894a6e3d4ea952e1cc9e) commit have PG version gap with current gpdb code (e.g. Upstream introduced many unrelated utility methods which is not necessary for this change, and `is_guc_modified()` is a gpdb-specific method, etc.), and I have chosen to merged into it manually.

**Pull request merged**
