### PR TITLE
fixed an issue of AOCSFileSegInfo size calculation

### PR DESCRIPTION
**Pull request by jianlirong**
The Assert(VARSIZE(dv) <= aocs_vpinfo_size(nvp)) makes no sense. The Following SQL can break this assert:

create table myao_rollback(i int , j int) with (appendonly=true, orientation=column);
begin;
alter table myao_rollback add column k int default 0;
insert into myao_rollback select i , i + 10, i - 10 from generate_series(1,10) i;
rollback;
SELECT * FROM myao_rollback;

This is because for the insert operation, a new segno (here it is 1) is assigned, and there is a corresponding tuple inserted into pg_aoseg with xmin as FrozenTransactionId.

### CODE REVIEW

**Comment by ashwinstar** [comment]
This seems to point fix the issue/assert. But feel we should not fix the assert as it seems correct, seems need to fix the underlying cause breaking the assert here. Doesn't sound nice to leave behind trace of added column with increased vpinfo size in pg_aoseg. Mostly likely need to hunt down the rational for performing initial **frozen** insert into pg_aoseg table for every segfile followed by regular inserts to it.

**Comment by jianlirong** [comment]
@ashwinstar , I totally agreed with you on hunting down the rational for performing initial frozen insert into pg_aoseg table for every segfile followed by regular inserts to it. If what I remembered is correct, there was a thread in the dev email list discussing this issue. Besides, I think the corresponding tuple for each segment file in the gp_fastsequence was also inserted with xmin with FrozenTransactionId (expected the first two segnos, 0, 1). So, please take that into account when you guys are discussing the rational.

BTW, I have left Pivotal, and didn't work on the project full time any more. However, because the product (a cloud data warehouse) I am working on is based on the code base of Greenplum Database, I encountered various issues of the code base occasionally, just like this one, #1819 , and #1620 . From my perspective, I just wanted to find a quick fix and then move on, continuing working the cloud native features of our product, rather than the features of GPDB (please forgive my selfishness, :( ). 

I will leave the discussion about the rational of this issue to you guys. Happy hunting down!

**Comment by Eulerizeit** [comment]
@ashwinstar @jianlirong  can we close this PR?

**Comment by ashwinstar** [comment]
@Eulerizeit Lets create the issue to track it with repro stated and then PR can be closed as need different fix after above rational is found. Thanks @jianlirong for reporting the issue.

**Comment by ashwinstar** [comment]
Close PR as issue was created to track this #2567

**Pull request closed without merging**
