### PR TITLE
6x remove gphostcache

### PR DESCRIPTION
**Pull request by dkrieger-pvtl**
#11972 removed the gphostcache from gprecoverseg; this backports the 7X removal of gphostcache from about 1 year ago: f61d35cdeacc2f97e234648e06788207fb9e53fc.  

The cherry-pick was "almost clean", with only a few syntactic issues.  But the fixup contains new gphostcache changes that were not in the original commit.

[pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-cm-6X_remove_gphostcache)

### CODE REVIEW

**Comment by asimrp** [comment]
Travis failed with the following error.  Is it caused by the gphostcache removal?
```
20210524:15:35:43:024293 gpinitsystem:travis-job-c0d5ccb8-0d6a-49e7-8517-34ca5317c050:travis-[INFO]:-Waiting for parallel processes batch [1], please wait...
.The authenticity of host 'travis-job-c0d5ccb8-0d6a-49e7-8517-34ca5317c050 (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:x8YXf75UG4mPD2gW9WacK+vNmEqob8C+mPtkoHfI3SM.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'travis-job-c0d5ccb8-0d6a-49e7-8517-34ca5317c050 (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:x8YXf75UG4mPD2gW9WacK+vNmEqob8C+mPtkoHfI3SM.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'travis-job-c0d5ccb8-0d6a-49e7-8517-34ca5317c050 (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:x8YXf75UG4mPD2gW9WacK+vNmEqob8C+mPtkoHfI3SM.
Are you sure you want to continue connecting (yes/no)? 
    ...
[FATAL]:-Failed to process this batch of segments within 1800 seconds
```

**Comment by dkrieger-pvtl** [comment]
> Travis failed with the following error. Is it caused by the gphostcache removal?

The issue appears to be a build of a standard demo cluster, which I can do locally.  I'm looking into it....

**Comment by pobbatihari** [comment]
Hi David,
Pipeline shows some errors and looks quite old as well, can we trigger again this pipeline and see anymore issues/conflicts still exists with this PR.

**Comment by niralis13** [comment]
David has rotated off of the team. @jmcatamney Can you help here?

**Comment by kalensk** [comment]
This reason why this stalled is because we had trouble debugging and figuring out why the Travis pipeline failed. Maybe somebody can take up that work.

 Its easy to re-trigger the job. Just click details next to "Travis CI - Pull Request Action required after 41m — Build Errored" and click into the failed jobs and in the top right "restart jobs".

**Review by jmcatamney — APPROVED** [review]

**Pull request merged**
