### PR TITLE
Remove redundant tests with different datatypes.

### PR DESCRIPTION
**Pull request by hlinnaka**
Float8, time, timestamp, and timestamptz have the same typlen, typyval,
typtype, typalign and typstorage attributes as int8. It is therefore
sufficient to run these tests with int8.

Likewise, date has the same type attributes as int4, so the tests on int4
cover the same ground.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@vraghavan78, please have a look. In the other PR, you said you wanted to keep all the mpp21090_* tests, but I really don't think that's necessary, per the explanation here.

**Comment by bhuvnesh2703** [comment]
Just to confirm are you referring to the int4, int8 test in optimizer functional with respect to the test deleted for date, for example mpp21090_drop_midcol_dml_int4_heap.sql like tests will cover date and changedistpolicy_dml_pttab_int8_orca.sql like test to cover int8? because the test in regress for int4 and int8 appear to not cover changing, updating distribution policy etc.

**Comment by hlinnaka** [comment]
Yes, that's right, that's what I meant.

**Comment by bhuvnesh2703** [comment]
Thanks for confirming. LGTM.

**Comment by hlinnaka** [comment]
Pushed, thanks.

**Pull request closed without merging**
