### PR TITLE
First stab at making contrib/ run installcheck

### PR DESCRIPTION
**Pull request by danielgustafsson**
Our `contrib/` directory was quite out of sync with upstream, with lots of files missing and the Makefile targetlist far from complete. This brings in all the missing upstream files, and massages the expected output formats to enable `make installcheck` to pass for most of the modules that have tests.

The cube and earthdistance modules are disabled in the Makefile due to Greenplum having CUBE as a keyword; postgres_fdw and tsearch2 are disabled due to test failures which are beyond the scope of this PR to fix.

Furthermore it aligns citext with upstream since a workaround for distribution column is no longer needed; updates seg to not use V0 functions in order to make the tests pass (and shipping code in the repo we know is broken by design is pretty pointless).

### CODE REVIEW

**Comment by danielgustafsson** [comment]
It's recommended to look at the commits individually, as there are many introduced changes. Also, actually turning on make installcheck for contrib/ is left as an exercise for an upcoming PR.

**Comment by berlin-ab** [comment]
Are these commits that we can accept and merge one at a time, instead of bundling up in one big PR?

**Comment by Eulerizeit** [comment]
@wuj21 @zhangh43 y'all might wanna take a look at this. Daniel was trying to get the contrib modules in a neat state but not changing what we do or don't ship.

**Comment by zhangh43** [comment]
+1 to make contrib synced with upstream and run installcheck. In future we'll work on auto_explain feature.

**Comment by berlin-ab** [comment]
Awesome, it looks like parts of this are landing in other PRs. Nice work @danielgustafsson

**Comment by gfphoenix78** [comment]
@danielgustafsson Hi, Daniel, I just wonder what the status this PR is now. I see there are two makefiles related to modules under contrib/: GNUmakefile.in and contrib/Makefile. By checking the gpdb binary, I guess the file `GNUmakefile.in` is the winner. The following step is to make installcheck for modules under contrib/, right? We are waiting to make contrib/auto_explain enabled and add test cases for it.

**Comment by danielgustafsson** [comment]
This PR has now been completely split apart into multiple PRs to make it easier to review, thus I'm closing this one.

**Pull request closed without merging**
