### PR TITLE
removing/rewording interconnect docs as only UDPIFC is supported in 5…

### PR DESCRIPTION
**Pull request by dyozie**
….0.0

### CODE REVIEW

**Comment by Eulerizeit** [comment]
@yydzero this seems to imply we are dropping TCP. Is that true?

**Comment by schubert** [comment]
@ivannovick @yydzero AFAIK we are not and have not dropped TCP support. We considered it a year ago but did not after we discovered that the Azure environment basically depends on TCP because they rate-limit internal UDP traffic to 1 Gbps IIRC.

**Comment by ivannovick** [comment]
Hi all, sorry for confusion.  We still support TCP interconnect in 5.0.  Plus UDP-IFC.

**Comment by hlinnaka** [comment]
TCP support was removed in March 2016, by commit 870531c705973adad7005618a781cbef4da14937.

**Comment by hlinnaka** [comment]
I believe commit 70c6b0bb4f0288a39b607518a40aab2679793b06 was done to address the issues on Azure, although the commit message doesn't say anything about it.

**Comment by yydzero** [comment]
5.0 has removed TCP. 4.3 do have TCP for Azure support.  Include Simon. @gaos1 

@hlinnaka yes, https://github.com/greenplum-db/gpdb/commit/70c6b0bb4f0288a39b607518a40aab2679793b06 is used to address one Azure issue.

**Comment by dyozie** [comment]
@ivannovick @Eulerizeit - per the above comments, 5.0 no longer has TCP interconnect.  Are we ok with this or is there a plan to revert and restore support?

**Comment by schubert** [comment]
Either myself or @ivannovick will get back to you on that. Just hold this
PR for right now.

**Comment by schubert** [comment]
Assume it's going to be reverted. cc @ivannovick

**Pull request merged**
