### PR TITLE
Simplify the way gp_toolkit schema is installed

### PR DESCRIPTION
**Pull request by hlinnaka**
Use the standard initdb mechanism for it, instead of having bespoken code
in gpinitsystem.

Also remove the unnecessarily complicated logic to generate gp_toolkit.sql
from gp_toolkit.sql.in. All the JETPACK_* variables were constants, and
there is particular need in making the gp_toolkit functions relocatable to
different schemas or prefixes, so just hardcode them and remove the sed
magic.

Also remove compaction_info.sql. It was only needed for old in-place
upgrade from 4.3.x to 4.3.4.2, which is not relevant for master branch.

This has a small user-visible difference: gp_toolkit schema is now also
installed in template0.

### CODE REVIEW

**Comment by ivannovick** [comment]
+1 to the idea of making gptoolkit properly part of the catalog.

**Comment by danielgustafsson** [comment]
I might be missing something but what is replacing `%%JETPACK_VERSION%%` in `gp_toolkit.sql.in`?

**Comment by hlinnaka** [comment]
On 30/12/15 11:46, Daniel Gustafsson wrote:
> I might be missing something but what is replacing `%%JETPACK_VERSION%%` in `gp_toolkit.sql.in`?

Hmm, nothing, apparently. Good catch. I just took the version of 
gp_toolkit.sql that "make" produced from the gp_toolkit.sql.in file, and 
didn't notice that JETPACK_VERSION was not replaced with anything.

I looked at the binaries produced in the Pivotal buildfarm, and the same 
happens there. The gp_toolkit.sql file that is generated and installed, 
says literally:

> -- gp_toolkit %%JETPACK_VERSION%%

I've updated the pull request with a new patch version. I removed that 
dummy comment. While we're at it, I rewrote the file header of the 
gp_toolkit.sql file. It contained a legal blurp that didn't seem 
appropriate, so I replaced it with a header that looks more like the 
header in system_views.sql and information_schema.sql.

I also ran the regression tests with this and updated the expected 
output file of a couple of tests. Now that gp_toolkit is installed in 
template0, it appears in the regression database that pg_regress 
creates, and the views show up in a couple of queries used in the 
regression tests.

- Heikki

**Comment by danielgustafsson** [comment]
:+1:

**Comment by hlinnaka** [comment]
One more revision. Turns out that there is a bugbuster test case called "jetpack" that was testing gp_toolkit, but it didn't actually work previously, because gp_toolkit was not installed. The expected output contained just "relation not found" errors. Fixed that too.

**Comment by danielgustafsson** [comment]
An even nicer catch! =) :+1: on this revision.

I guess we at some point (not in this PR) can clean up many (all?) of the implicit `DROP ..;` statements in the tests since they are cleaned up anyways?

**Comment by hlinnaka** [comment]
On 30/12/15 16:15, Daniel Gustafsson wrote:
> I guess we at some point (not in this PR) can clean up many (all?) of the implicit `DROP ..;` statements in the tests since they are cleaned up anyways?

I've been removing them whenever I happen to bump into them. If you can 
think of a way to catch them in an automated way, that'd be cool. Also, 
there's a risk that a earlier/later test case creates a table with the 
same name, so that the DROP is actually required. But yeah, it might 
make sense to do a sweep of all of them.

- Heikki

**Comment by ivannovick** [comment]
we are supposed to call the functions like this after its installed:

select gp_toolkit.bloat_diag();

for example

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Pull request closed without merging**
