### PR TITLE
DEFAULT paramters of UDF ported from PostgreSQL 8.4

### PR DESCRIPTION
**Pull request by kuien**
Functions can be declared with parameters with default values or
expressions.  The default expressions are used as parameter value
if the parameter is not explicitly specified in a function call.
All parameters after a parameter with default value have to be
parameters with default values as well.

It allows user to invoke a UDF without setting all the parameters.
Two examples to demo its usage:

    CREATE FUNCTION dfunc1(text DEFAULT 'Hello', text DEFAULT 'World')
        RETURNS text AS $$
        SELECT $1 || ', ' || $2;
        $$ LANGUAGE SQL;
    SELECT dfunc1();  -- 'Hello, World'
    SELECT dfunc1('Hi');  -- 'Hi, World'
    SELECT dfunc1('Hi', 'Beijing');  -- 'Hi, Beijing'

    CREATE FUNCTION dfunc2(id int4, t timestamp DEFAULT now())
        RETURNS text AS $$
        SELECT 'Time for id:' || $1 || ' is ' || $2;
        $$ LANGUAGE SQL;
    SELECT dfunc2(24);  -- 'Time for id:24 is 2016-01-07 14:38'

NOTE: The default change set is ported from from PostgreSQL 8.4,
    original commits:
    '517ae4039ebe12806d76adfd3bc1fc6578fc8862'
    '455dffbb73f9875c39f2ab544420454168a8c68c'

### CODE REVIEW

**Comment by hlinnaka** [comment]
LGTM, after moving the parameterDefaults argument. Thanks!

**Comment by hlinnaka** [comment]
Closing, Kuien pushed this yesterday.

**Comment by liruto** [comment]
@hlinnaka Function's default parameter is expanded in plan generation phrase. So I have a question, how about ORCA? Is it need do something else or disable in this case?

**Comment by hlinnaka** [comment]
On 18/02/16 03:58, liruto wrote:
> @hlinnaka Function's default parameter is expanded in plan generation
> phrase. So I have a question, how about ORCA? Is it need do something
> else or disable in this case?

With ORCA, default parameters are expanded before the query is handed 
off to ORCA. See preprocess_query_optimizer().

- Heikki

**Comment by liruto** [comment]
Thanks, I see.
---原始邮件---
发件人:"Heikki Linnakangas"<notifications@github.com>
发送时间:2016年2月18日 星期四 下午8:2
收件人:"greenplum-db/gpdb"<gpdb@noreply.github.com>
抄送:"liruto"<liurong@upbase.com.cn>
主题:Re: [gpdb] DEFAULT paramters of UDF ported from PostgreSQL 8.4 (#302)
On 18/02/16 03:58, liruto wrote:
 > @hlinnaka Function's default parameter is expanded in plan generation
 > phrase. So I have a question, how about ORCA? Is it need do something
 > else or disable in this case?
 
 With ORCA, default parameters are expanded before the query is handed 
 off to ORCA. See preprocess_query_optimizer().
 
 - Heikki
 
&mdash;

**Pull request closed without merging**
