### PR TITLE
Set CurrentMemoryContext back correctly in cdbRelMaxSegSize()

### PR DESCRIPTION
**Pull request by pengzhout**
Within PG_CATCH() block, if you want to ignore some errors, you need to set
CurrentMemoryContext back to correct context, otherwise it will point to
ErrorContex which is not expected.

### CODE REVIEW

**Comment by hlinnaka** [comment]
1. Suppressing an ereport() like this is quite dangerous. Depending on where the error was thrown, you might still be holding LWlocks, or you might even have inserted rows in a table, without updating the indexes yet, so that the database is inconsistent unless you abort the transaction. PG_TRY/CATCH should only be used for closing resources etc., with PG_RE_THROW(), or with a subtransaction that you rollback in the CATCH-block.

2. cdbRelMaxSegSize() returns -1 on error. That is *not* a safe value. Looking at the call from tablecmds.c, for example, we will treat an error as the same as "the table is completely empty", and deduce that it's safe to alter the table's distribution key. The call in cdbcat.c closely avoids that mistake by checking for cdbRelMaxSegSize() != 0 rather than cdbRelMaxSegSize() > 0.

Since this function is used for important safety checks, rather than e.g. for planning estimates, I think we should remove the whole PG_TRY()/CATCH() block and let the error bubble up. Both callers of the function are doing DDL that will be dispatched to all the segments, so if there's e.g. a connectivity problem, the command is likely going to fail anyway.

**Comment by pengzhout** [comment]
Hi @hlinnaka, Agreed. I can't figure out why the error need to be downgraded here, this codes were introduced very early, so let's let the error bubble up.

**Comment by asimrp** [comment]
LGTM, not sure why we were demoting the error and moving on.

**Comment by pengzhout** [comment]
Thanks for the review, merged and closed.

**Pull request closed without merging**
