### PR TITLE
Add README comment about minimal lockfile version for Python module

### PR DESCRIPTION
**Pull request by andreasscherbaum**

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
Thanks to @jimmyyih we figured out a problem on Ubuntu 15.04. The "lockfile" version was 0.8.0 and this version does not have the "pidlockfile" function.

**Comment by davecramer** [comment]
I ran into this on amazon linux as well.

You need to actually upgrade pip to get the correct version

Dave Cramer

**Comment by andreasscherbaum** [comment]
Just upgrading this one module did the job for me.

**Comment by davecramer** [comment]
I couldn't upgrade the module without upgrading pip

Dave Cramer

**Comment by andreasscherbaum** [comment]
Might depend on the pip version as well. Can you add your version to the README? On the other hand, I seem to have two "pip" installed now:

ads@platin:~$ which pip
/usr/local/bin/pip

ads@platin:~$ pip --version
pip 7.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

ads@platin:~$ /usr/bin/pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)

What a mess ...

**Comment by davecramer** [comment]
pip --version
pip 7.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)

is what works for me. I would imagine your 1.5.6 is not working

Dave Cramer

**Pull request closed without merging**
