### PR TITLE
Fixed coverity issue about not freeing a variable

### PR DESCRIPTION
**Pull request by kaknikhil**
Fixed coverity issue in fstream.c about freeing a path variable. 

Authors : Nikhil Kak & Marbin Victor Tan

### CODE REVIEW

**Comment by kaknikhil** [comment]
pushed

**Comment by kaknikhil** [comment]
Thanks for the review .

**Comment by danielgustafsson** [comment]
Forgive my ignorance but what is `path2` used for in `glob_path()`?

**Comment by hlinnaka** [comment]
On 18/12/15 09:02, Daniel Gustafsson wrote:
> Forgive my ignorance but what is `path2` used for in `glob_path()`?

Hmm, good point. Looks like dead code to me too. It's allocated, and 
copied into, but never used for anything.

- Heikki

**Pull request closed without merging**
