### PR TITLE
pg_upgrade: forward port fast sequence fix

### PR DESCRIPTION
**Pull request by kyeap-vmware**
This is part of a series of commits to bring 6X and 7X pg_upgrade back
in sync with each other by forward porting pg_upgrade changes from the
6X branch to 7X. Our normal workflow is to make changes on 7X then
backport to 6X to keep the branches in sync. Due to time constraints,
this workflow was temporarily paused and 7X upkeep was deprioritized.
While fixes and optimizations have gone into 6X pg_upgrade, we have not
made the same changes to 7X pg_upgrade resulting a divergence.

At this point it is recognized that 6 > 7 is untested and not
functional. The fixes are brought in as is, with no changes or edits to
make 7X gpupgrade tests pass. Subsequent work will be done to to make 7x
pg_upgrade usable for upgrade from GPDB6 to GPDB7.

reference commit:
pg_upgrade: preserve gp_fastsequence to prevent duplicate ctids
https://github.com/greenplum-db/gpdb/commit/c90639e6e4

pipeline:
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/kyeap-fast-sequence-fport

### CODE REVIEW

**Review by bmdoil — COMMENTED** [review]
> This is a partial forward port of the two commits to fix xids on
    segments.

Can you clarify which parts of the c0b4d5bcca7 commit are not being forward ported? Is it a functional change or no? I'm guessing it's due to small difference in 5 and 6 like datminmxid?

I don't we need to explain the process details in the commit messages, just keep it to the changes in the commit. Can move that context to internal story and note that full testing will be added in a follow-up commit. We'll link back to this PR when tests are added for 6->7.

**Comment by kyeap-vmware** [comment]
> > Can you clarify which parts of the https://github.com/greenplum-db/gpdb/commit/c0b4d5bcca7a5936829a08c4cbb479f9ac7c78a4 commit are not being forward ported?

Good call. There was so much context I left out on why partial forward port.

**Review by bmdoil — APPROVED** [review]
LGTM

**Comment by kyeap-vmware** [comment]
Force push just re-orders the commits.

**Pull request merged**
