### PR TITLE
[7X][NFC] Fix mismatched types.

### PR DESCRIPTION
**Pull request by higuoxing**
This patch fixes several type mismatching issues.

1. The DistributedTransactionId is of type uint64, we shouldn't cast it to TransactionId which is of type uint32.

2. The Cost is of type Float8, we should use Float8GetDatum to cast it to Datum.

### CODE REVIEW

**Comment by kainwen** [comment]
Looks fine.
BTW, what is NFC?

**Comment by higuoxing** [comment]
> Looks fine. BTW, what is NFC?

It means "No Functional Change".

**Comment by kainwen** [comment]
Is is possible to also fix this? https://github.com/greenplum-db/gpdb/issues/17176

**Review by kainwen — APPROVED** [review]

**Comment by higuoxing** [comment]
> Is is possible to also fix this? #17176

Yes, I'm going to catch more unsafe conversion in a future PR.

**Pull request merged**
