### PR TITLE
udpifc: discard out-of-date rx-thread error

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
UDPIFC receives data in a rx thread, errors in this thread cannot be
raised directly, they are recorded in memory and the main thread is
responsible to raise it at some proper time.

It is possible for the rx thread to record an error after last TEARDOWN,
technically it should be counted for last query, but there was a bug
that the main thread raised it in next SETUP, so the new query failed
immediately due to out-of-date errors.

This is fixed by discarding any rx thread errors at beginning of SETUP.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [x] Pass `make installcheck`

### CODE REVIEW

**Comment by pengzhout** [comment]
please make sure newly added tests pass.

**Comment by pivotal-ning-yu** [comment]
Newly added test needs the GUC `gp_udpic_fault_inject_percent` which is only available in debugging build, so we can not enable this test in normal ICW pipelines, it can only run on the interconnect pipeline.  Force pushed the PR to disable this test in ICW.

**Comment by pivotal-ning-yu** [comment]
On Wed, Feb 13, 2019 at 3:27 PM Heikki Linnakangas <notifications@github.com>
wrote:

> *@hlinnaka* approved this pull request.
>
> Ah, does this explain the occasional "out of memory" errors on the
> pipeline? Nice!
>
Yes, this PR is exactly to fix that weird OOM. Thanks for the review.

**Comment by pivotal-ning-yu** [comment]
The PR pipeline is green now, however please note that the test will not be triggered by PR pipeline at all.  The test passed in my locally environment.

**Comment by pivotal-ning-yu** [comment]
Thanks for the review, I'll merge it now and keep an eye on the pipeline status.

**Pull request merged**
