### PR TITLE
Add Partitioned Indexes

### PR DESCRIPTION
**Pull request by kalensk**
Greenplum does not enforce constraint and index names to match which differs from upstream behavior. This presents a challenge when upgrading. Specifically in Greenplum, pg_dump’s generated DDL's are not specific enough to reproduce the old database catalog. See [proposal](https://docs.google.com/document/d/1E_pFWbzWOgBgHQIXX6yuOxZqMtTnpKbE51UUiAJaEI4/) for details.

This PR is a followup to https://github.com/greenplum-db/gpdb/pull/6877 in order to enforce constraint and index names to match in order to align with upstream and enable upgrading of Greenplum databases. This also sets us up to add `ALTER INDEX ... ATTACH PARTITION ...`.

```
This commit adds partitioned indexes from upstream Postgres. This commit is
mostly cherry-picked from Postgres 11 and bug fixes from Postgres 12.

Differences from upstream:
 - Postgres has two additional relkind's - RELKIND_PARTITIONED_TABLE and
   RELKIND_PARTITIONED_INDEX, which have no on disk storage. Greenplum does not
   have these additional relkinds. Thus, partitioned indexes have physical
   storage.
 - CREATE INDEX ON ONLY <table> DDL has not yet been implemented
 - ALTER INDEX ATTACH PARTITION DDL has not yet been implemented

Constraint changes:
 - Constraints and their backing index have the same names. Thus, partitions of
   a table no longer share the same constraint name, and are instead related to
   their parent via INTERNAL_AUTO dependencies.

Index changes:
 - Child partition indexes can no longer be directly dropped, and must be
   dropped from their root. This includes mid-level and leaf indexes.
 - Adding indexes to mid-level partitions cascade to their children.


These changes are mostly cherry-picked from:
commit 8b08f7d4820fd7a8ef6152a9dd8c6e3cb01e5f99
Author: Alvaro Herrera <alvherre@alvh.no-ip.org>
Date:   Fri Jan 19 11:49:22 2018 -0300

    Local partitioned indexes

    When CREATE INDEX is run on a partitioned table, create catalog entries
    for an index on the partitioned table (which is just a placeholder since
    the table proper has no data of its own), and recurse to create actual
    indexes on the existing partitions; create them in future partitions
    also.

    As a convenience gadget, if the new index definition matches some
    existing index in partitions, these are picked up and used instead of
    creating new ones.  Whichever way these indexes come about, they become
    attached to the index on the parent table and are dropped alongside it,
    and cannot be dropped on isolation unless they are detached first.

    To support pg_dump'ing these indexes, add commands
        CREATE INDEX ON ONLY <table>
    (which creates the index on the parent partitioned table, without
    recursing) and
        ALTER INDEX ATTACH PARTITION
    (which is used after the indexes have been created individually on each
    partition, to attach them to the parent index).  These reconstruct prior
    database state exactly.

    Reviewed-by: (in alphabetical order) Peter Eisentraut, Robert Haas, Amit
            Langote, Jesper Pedersen, Simon Riggs, David Rowley
    Discussion: https://postgr.es/m/20171113170646.gzweigyrgg6pwsg4@alvherre.pgsql

Changes were also cherry-picked from the following Postgres commits:
  eb7ed3f306 - Allow UNIQUE indexes on partitioned tables
  ae366aa577 - Detach constraints when partitions are detached
  19184fcc09 - Simplify coding to detach constraints when detaching partition
  c7d43c4d8a - Correct attach/detach logic for FKs in partitions
  17f206fbc8 - Set pg_class.relhassubclass for partitioned indexes

```

### CODE REVIEW

**Comment by guofengrichard** [comment]
Great! I was thinking to back-port the dependency part to fix issue #3750, and the PR does that. I have verified that issue being fixed by this PR. Thanks!

**Comment by kalensk** [comment]
This PR should fix Issue https://github.com/greenplum-db/gpdb/issues/2757.

**Comment by dkrieger-pvtl** [comment]
In terms of testing, we notice that there are no explicit tests for partitioned indices per se, just ones that test them implicitly via their use in index-backed constraints.  In addition, it appears we drop the tables in our pg_regress tests, so that our regression testing, which runs the tests into a database that is then upgraded, won't see them.  This is based on `src/test/regress/sql/index_constraint_naming_partition.sql`.

**Comment by dkrieger-pvtl** [comment]
Here is a case showing what appears to be anomalous behavior in the subsumption of an index on a partition table when an index is created on a ancestor partition table.

```
These examples reference src/test/regress/sql/index_constraint_naming_partition.sql.

0). base case

create a three-level partition table with an index on the root

foobar=# SELECT recreate_three_level_table();
foobar=# CREATE UNIQUE INDEX myidx_midlevel ON r USING btree(r_key);
foobar=# SELECT * FROM dependencies_show_for_idx();
           depname            |       refname        | deptype
------------------------------+----------------------+---------
 myidx_midlevel               | r                    | a
 r_1_prt_r1_2_prt_a_r_key_idx | r_1_prt_r1_2_prt_a   | I
 r_1_prt_r1_2_prt_a_r_key_idx | r_1_prt_r1_r_key_idx | I
 r_1_prt_r1_2_prt_b_r_key_idx | r_1_prt_r1_2_prt_b   | I
 r_1_prt_r1_2_prt_b_r_key_idx | r_1_prt_r1_r_key_idx | I
 r_1_prt_r1_r_key_idx         | myidx_midlevel       | I
 r_1_prt_r1_r_key_idx         | r_1_prt_r1           | I                      ----------------------------
 r_1_prt_r2_2_prt_a_r_key_idx | r_1_prt_r2_2_prt_a   | I
 r_1_prt_r2_2_prt_a_r_key_idx | r_1_prt_r2_r_key_idx | I
 r_1_prt_r2_2_prt_b_r_key_idx | r_1_prt_r2_2_prt_b   | I
 r_1_prt_r2_2_prt_b_r_key_idx | r_1_prt_r2_r_key_idx | I
 r_1_prt_r2_r_key_idx         | myidx_midlevel       | I
 r_1_prt_r2_r_key_idx         | r_1_prt_r2           | I
(13 rows)

1). similar to base case but first put an index on the middle table, rename it, 
and then add one to the root.  Note that the middle table's index is now 'a' and not 'I' on it's table.  

SELECT recreate_three_level_table(); 
CREATE UNIQUE INDEX myidx_midlevel ON r_1_prt_r1 USING btree(r_key);
alter index myidx_midlevel rename to myidx_midlevel_renamed;
CREATE UNIQUE INDEX myidx_midlevel ON r USING btree(r_key);

postgres=# SELECT * FROM dependencies_show_for_idx();
           depname            |        refname         | deptype
------------------------------+------------------------+---------
 myidx_midlevel               | r                      | a
 myidx_midlevel_renamed       | r_1_prt_r1             | a                        ---------------------------------------
 myidx_midlevel_renamed       | myidx_midlevel         | I
 r_1_prt_r1_2_prt_a_r_key_idx | r_1_prt_r1_2_prt_a     | I
 r_1_prt_r1_2_prt_a_r_key_idx | myidx_midlevel_renamed | I
 r_1_prt_r1_2_prt_b_r_key_idx | r_1_prt_r1_2_prt_b     | I
 r_1_prt_r1_2_prt_b_r_key_idx | myidx_midlevel_renamed | I
 r_1_prt_r2_2_prt_a_r_key_idx | r_1_prt_r2_2_prt_a     | I
 r_1_prt_r2_2_prt_a_r_key_idx | r_1_prt_r2_r_key_idx   | I
 r_1_prt_r2_2_prt_b_r_key_idx | r_1_prt_r2_2_prt_b     | I
 r_1_prt_r2_2_prt_b_r_key_idx | r_1_prt_r2_r_key_idx   | I
 r_1_prt_r2_r_key_idx         | r_1_prt_r2             | I
 r_1_prt_r2_r_key_idx         | myidx_midlevel         | I
(13 rows)
```

**Comment by tvesely** [comment]
Interesting find. This seems to be the same behavior as in the Postgres `master` branch.

Observe:

```
tvesely=# create index foo_1_prt_1_a_idx on  foo_1_prt_1 (a);
CREATE INDEX
tvesely=# create index joinme on  foo (a);
CREATE INDEX
tvesely=# select objid::regclass, refobjid::regclass, * from pg_depend where refobjid = 'foo_1_prt_1_a_idx'::regclass or objid= 'foo_1_prt_1_a_idx'::regclass;
       objid       |  refobjid   | classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype
-------------------+-------------+---------+-------+----------+------------+----------+-------------+---------
 foo_1_prt_1_a_idx | foo_1_prt_1 |    1259 | 16398 |        0 |       1259 |    16391 |           1 | a
 foo_1_prt_1_a_idx | joinme      |    1259 | 16398 |        0 |       1259 |    16399 |           0 | I
(2 rows)

tvesely=# drop index joinme;
DROP INDEX
tvesely=# create index joinme on  foo (a);
CREATE INDEX
tvesely=# select objid::regclass, refobjid::regclass, * from pg_depend where refobjid = 'foo_1_prt_1_a_idx'::regclass or objid= 'foo_1_prt_1_a_idx'::regclass;
       objid       |  refobjid   | classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype
-------------------+-------------+---------+-------+----------+------------+----------+-------------+---------
 foo_1_prt_1_a_idx | foo_1_prt_1 |    1259 | 16401 |        0 |       1259 |    16391 |           1 | I
 foo_1_prt_1_a_idx | joinme      |    1259 | 16401 |        0 |       1259 |    16400 |           0 | I
(2 rows)
```

If we are going to fix it, we should do it in upstream first, then backpatch the fixes.

**Comment by dkrieger-pvtl** [comment]
> Interesting find. This seems to be the same behavior as in the Postgres `master` branch.
> If we are going to fix it, we should do it in upstream first, then backpatch the fixes.

We were unable to find an anomalous behavior with this difference, but are concerned that there might be more complicated ways to arrange indices that do have an anomalous behavior.

**Comment by dkrieger-pvtl** [comment]
We wrote tests that validate the main new claims on this PR--namely, the behavior of partitioned indexes and their use of INTERNAL AUTO.  The tests also validate the use of INTERNAL AUTO for constraints.  These tests have been added to this PR.

**Comment by tvesely** [comment]
The latest test you added @dkrieger-pvtl @marksliva isn't constrained to the test's namespace, and so it is finding the `pg_depend` rules for every index in the `regression` database.

**Comment by danielgustafsson** [comment]
This is a very invasive change this close to cutting beta. What is the effect on 6.X if we don't merge this?

**Comment by danielgustafsson** [comment]
Also, please push a rebase to trigger the PR pipeline on this.

**Comment by skahler-pivotal** [comment]
@danielgustafsson I believe this solves a problem we have with have a reliable way to drive names and setup dependancies around constraints and solidifies indexes a bit. 

My primary goal for pushing on this has been that I feel if we don't have this in 6, we carry forward a very large piece of debt that will leave the 6 to 7 upgrade in the same boat we are for 5 to 6. I do agree these types of things should ideally be worked on much earlier in the cycle and hope to see some of the further work in this area carried on rather than set down.

**Comment by dkrieger-pvtl** [comment]
> The latest test you added @dkrieger-pvtl @marksliva isn't constrained to the test's namespace, and so it is finding the `pg_depend` rules for every index in the `regression` database.

We added a fixup commit to both restrict our results to the namespace of the partition test and to `ORDER BY` on all fields that show up in the final expected.out file to make sure the test doesn't have spurious diffs that might have been caused by future, unrelated changes.

**Pull request merged**
