### PR TITLE
Porting qp_functions & misc_jira_rio to ICG

### PR DESCRIPTION
**Pull request by karthijrk**
@armenatzoglou @foyzur @gcaragea @vraghavan78 Please take a look when you get chance.

### CODE REVIEW

**Comment by armenatzoglou** [comment]
Why do you have multiple tests, e.g., qp_misc_jiras_rio, qp_misc_rio_join_small, qp_misc_rio_plpython? Do we have to run them sequentially?

**Comment by karthijrk** [comment]
@armenatzoglou Good catch, It doesn't need to run sequentially. I separated while developing and forget to combine. I combined qp_misc_rio and qp_misc_rio_plpython and left qp_misc_rio_join_small. qp_misc_rio_join_small is just a single test and sql is very big so I kept it as separate sql for readability.

**Comment by armenatzoglou** [comment]
+1

**Comment by karthijrk** [comment]
Thanks all for the review. This is pushed into master

**Pull request closed without merging**
