### PR TITLE
Enable record array

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
Commit e3b01174 is back ported to support array of records like below query:

```sql
select array[row(1)];
```

Due to conflict of OIDs we made below changes to this commit:

* record_eq: 2981 => 5981
* record_ne: 2982 => 5982
* record_lt: 2983 => 5983
* record_gt: 2984 => 5984
* record_le: 2985 => 5985
* record_ge: 2986 => 5986
* btrecordcmp: 2987 => 5987
* record = record: 2988 => 5988
* record <> record: 2989 => 5989
* record < record: 2990 => 5990
* record > record: 2991 => 5991
* record <= record: 2992 => 5992
* record >= record: 2993 => 5993
* record_ops: 2994 => 5994

Additionally RECORDARRAYOID is 2287 in upstream PG, but it's 3287 in GPDB because 2287 was used by pg_total_relation_size in GPDB. So we make below swap to keep RECORDARRAYOID 2287:

* pg_total_relation_size: 2287 => 3287
* RECORDARRAYOID: 3287 => 2287

### CODE REVIEW

**Comment by pivotal-ning-yu** [comment]
In fact we also considered whether should keep the OIDs for record_*, etc. the same with upstream PG, the OIDs 2981~2993 in GPDB were as below:

* xmlexists: 2985
* xpath_exists: 2986
* xmlvalidate: 2987
* xml_is_well_formed: 2988
* xml_is_well_formed_content: 2989~2990
* interval_bound: 2991~2999

We could swap the 29?? OIDs with 59??, is this worthy to do? Comments are welcome.

**Comment by pivotal-ning-yu** [comment]
Also have to highlight that this PR is a catalog change.

**Comment by hlinnaka** [comment]
Or actually, I'd prefer to not backport the comparison functions, because of the OID conflicts. Yeah, we can resolve them, like you did here, but they will cause merge conflicts later, when we merge with 8.4. We can fix it then, but why create work for our future selves?

**Comment by hlinnaka** [comment]
Yeah, if we're going to keep the record comparison functions, it would be better to renumber the xml functions out of the way, and use the same oids as in the upstream for the record comparison functions.

**Comment by pivotal-ning-yu** [comment]
Thanks so much for the review, then I think we'd better remove the record comparison functions, besides the OID conflicts they are also causing test failures as some cases are expecting the record comparison to fail.

**Comment by pivotal-ning-yu** [comment]
A new commit was submitted to remove the record comparison functions.

**Comment by hlinnaka** [comment]
LGTM now, thanks!

On 1 April 2017 12:24:56 EEST, Ning Yu <notifications@github.com> wrote:
>A new commit was submitted to remove the record comparison functions.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/2143#issuecomment-290908391

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hlinnaka** [comment]
Thanks! In the future, please squash commits in a PR before pushing. That makes the git history nicer to read in the future.

**Comment by pivotal-ning-yu** [comment]
Thanks for the guide, I'll follow this policy in the future.

**Pull request merged**
