### PR TITLE
Make the 10 Gb optional

### PR DESCRIPTION
**Pull request by andreasscherbaum**

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
Looks like something terminated the CI tests.

**Comment by mkiyama** [comment]
@ivannovick 
A 10 GB (or faster) interconnect is required for Enterprise production systems, is that correct?

**Comment by ivannovick** [comment]
I guess not, but we can say A 10 GB (or faster) interconnect is **recommended** for Enterprise production systems

**Comment by andreasscherbaum** [comment]
Technically it works on whatever can transport your packages. So the 10 Gb are not a technical requirement, but rather a logical choice if you want to have a decent performance. If someone deploys 40GbE or 100GbE - fine.

But yes, the faster the better.

**Comment by mkiyama** [comment]
My concern was with customers running on older, slower hardware.

**Comment by andreasscherbaum** [comment]
I understand that. Still the 10 GB are not a technical requirement. Only the DCA was fixed to this speed.

**Comment by Eulerizeit** [comment]
On Tue, May 30, 2017 at 12:14 PM, Andreas Scherbaum <
notifications@github.com> wrote:

> I understand that. Still the 10 GB are not a technical requirement. Only
> the DCA was fixed to this speed.
>
I guess the ask is for a wording that makes it not a requirement rather
strongly suggested for a performant system.

i.e. technically not required but practically required.

**Comment by mkiyama** [comment]
For the enterprise version, I would request wording that sets customer expectations is supportable by GSS.
Thanks.

**Comment by andreasscherbaum** [comment]
#2528 makes changes to the same documents, let's approve and merge the other one first. Then I incorporate your wording suggestions.

**Comment by andreasscherbaum** [comment]
@mkiyama I changed the wording, does that fit better? It's what we used in #2528 as well.

**Pull request merged**
