### PR TITLE
Wraps main work for pg_upgrade test_gpdb.sh inside of a main function.

### PR DESCRIPTION
**Pull request by berlin-ab**
This should make refactoring into functions easier and help readability.

### CODE REVIEW

**Comment by berlin-ab** [comment]
This change looks like a lot of changes, but really is only indention and the addition of a wrapping function.

**Comment by jchampio** [comment]
> This should make refactoring into functions easier and help readability.

I'm skeptical. What makes refactoring easier with this change, and how is readability helped? I'm used to unindented code in Bash scripts being part of the main execution body. This adds another layer, but I'm not seeing how it helps with overall understanding of the code.

**Comment by berlin-ab** [comment]
Once wrapped in a main function, standard rules of function decomposition/refactoring apply and the size of the main function becomes more obvious (in my opinion). We would have the opportunity to create local variables and move away from global variable state when possible.

**Comment by jchampio** [comment]
> We would have the opportunity to create local variables

To me, that's definitely the most compelling argument for this. I feel like this is a simple enough change that it can wait for when we actually start using locals, but I'm not opposed to it if others feel it is useful now.

**Comment by berlin-ab** [comment]
Amended with improvements. Merging.

**Pull request merged**
