### PR TITLE
6X: Delay fsync ao mirror and primary 

### PR DESCRIPTION
**Pull request by asimrp**
Back port of PR #9172 on 6X.  I just want to run this through PR pipeline.

### CODE REVIEW

**Comment by asimrp** [comment]
Interesting failure on PR pipeline.  I can reproduce the failure if `uao_crash_compaction_column` test runs before the `fsync_ao` test.  Looking into it...

**Comment by asimrp** [comment]
The failure was due to a bug introduced by me in the logic used to decide when to forget an fsync request during WAL replay.  It's fixed now.  The PR pipeline is expected to be green.

**Comment by asimrp** [comment]
For some reason the automatic build in PR pripeline timed out during compile.  I've retriggered it here: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_pr_6x_stable/jobs/compile_and_test_gpdb/builds/381

**Comment by asimrp** [comment]
Some test failures still exist (e.g. fts_errors failing due to pg_basebackup failure).  I cannot relate them to the patch in any way, so let's ignore them.

This patch can be tested in two configurations:
1. Default configuration - `forward_ao_fsync_on_primary` is turned off.  This means that primary will not change its behavior - backends will continue to perform fsync for append-optimized table files at the end of insert.
2. Turn the GUC on so that backends running on primary will also forward fsync requests to the checkpointer:
```
gpconfig -c forward_ao_fsync_on_primary -v on --skipvalidation
gpstop -u
```

Note that in both the configurations, the replay process on mirror will not perform fsync.  It will  forward fsync requests to checkpointer.  This is the main change.  It is expected to fix mirror replay taking several times longer than the primary to complete.

**Comment by asimrp** [comment]
Thank you @kapustor and team for testing this patch in your environment.  Let me copy the results you've shared on slack https://greenplum.slack.com/archives/C6TQ7D43E/p1575627084094500?thread_ts=1573055686.025800&cid=C6TQ7D43E:

```
GP5,appendonly=true, orientation=row: 10 minutes, no extra WAL IO after queries finish
GP6.1.0 without fix,appendonly=true, orientation=row: 30 minites, WAL IO after queries finish for 5 hours
GP6.1.1 with fix,forward_ao_fsync_on_primary=off, appendonly=true, orientation=row: 25 minites, no extra WAL IO after queries finish
GP6.1.1 with fix,forward_ao_fsync_on_primary=on, appendonly=true, orientation=row: 24 minutes, no extra WAL IO after queries finish
GP6.1.1 with fix,forward_ao_fsync_on_primary=on, appendonly=true, orientation=column: 16 minutes, no extra WAL IO after queries finish
```

**Comment by asimrp** [comment]
Based on this, we have confirmation that the fix on the mirror side is definitely effective.  However, the forwarding of fsync to checkpointer on the primary side is not offering significant benefit.

**Comment by paul-guo-** [comment]
Great. For the primary side I think we will need to know about the additional bottleneck later (if have)  but skipping fsync is definitely beneficial in theory.

**Comment by asimrp** [comment]
Thanks again for verifying this fix.  It helped us decide that only mirror side fix is worth pursuing.  Let's get it in the right order - master first and then back port to 6X.  Closing this PR in favor of #9201

**Pull request closed without merging**
