### PR TITLE
5X Backport: Support FIPS mode operation in pgcrypto

### PR DESCRIPTION
**Pull request by danielgustafsson**
In Greenplum 4.3 there was a GUC in pgcrypto controlling FIPS mode
operation which was deprecated. This brings the GUC back, as there
has been requests from production instances.

To enable the GUC, Greenplum must be dynamically linked against an
OpenSSL installation which is compiled with the FIPS module (1.0.2
with FIPS 2.0 is tested and supported, no FIPS module exist for
later versions of OpenSSL as of yet). There is an additional strict
mode as well which requires both OpenSSL to be FIPS capable as well
as the operating system kernel to be running in FIPS mode (this is
only supported on Linux for now).

Some ciphers will be disallowed in this mode even though they are
defined as legal by FIPS-140 level 2, due to the fact that pgcrypto
is using the lowlevel API for these and this is not certified for
FIPS operation.

Backport from master PR.

### CODE REVIEW

**Comment by d** [comment]
I don't think the enum GUC api exists in Postgres 8.3 / Greenplum 5, we might have to emulate it by hand

**Comment by d** [comment]
I started reviewing this a couple hours ago, quick findings:

1. The patch from #8383 is not a directly applicable because of the enum GUC API (there's no merge conflict, but the cherry-picked code won't link properly)
1. Upstream commit 10a3b165a32 makes `pgp.h` a lot more pleasant to include
1. It's debatable, as a backpatch, how much fidelity of such a feature we should present to our users. We can narrow the off/on/strict to just off and strict, for example. Of course, we can always choose to emulate an enum GUC with a string and a bunch of tedious checks...

I've cherry-picked 10a3b165a32 on tip of the latest 5X_STABLE, and rebased your patch on top -- This still won't compile -- and pushed the result back onto this PR.

I don't have a strong feeling about which direction we should go about the point 3 above, with a slight preference for writing less code (narrowing the options).

Cheers,
Jesse

**Comment by d** [comment]
> 3\. just off and strict

To be clear, I wasn't suggesting we offer a boolean GUC where "on" precisely means "strict". I'm suggesting let's write less code, and pick a meaning for "on" and just use a boolean GUC and call it a day.

**Comment by BaiShaoqi** [comment]
config_enum_entry is introduced after postgres 8.4 by commit 
 https://github.com/greenplum-db/gpdb/commit/52a8d4f8f7e286482886861175312c1434b1d4fd, so also need backport when needed. 
But also need bump catalog version if backport the commit. maybe too much effort for such feature

**Comment by d** [comment]
> config_enum_entry is introduced after postgres 8.4 by commit
> [52a8d4f](https://github.com/greenplum-db/gpdb/commit/52a8d4f8f7e286482886861175312c1434b1d4fd), so also need backport when needed.
> But also need bump catalog version if backport the commit. maybe too much effort for such feature

Correct. Alas that's definitely out of the picture

**Comment by BaiShaoqi** [comment]
> > 3. just off and strict
> 
> To be clear, I wasn't suggesting we offer a boolean GUC where "on" precisely means "strict". I'm suggesting let's write less code, and pick a meaning for "on" and just use a boolean GUC and call it a day.

Daniel's idea about strict mode here may want to make sure certified cryptographic modules are used, or else some non-fips cipher and digest methods are used. 
But on mode only does not check.

**Comment by danielgustafsson** [comment]
Bleh, looking back it turns out that my test compilation was fat-fingered and only compiled 5X without the patch applied, no wonder that worked fine. I've updated the patch to remove the strict mode on 5X only to support it on 6X and onwards, it's not an interesting enough feature to bend over backwards to support when the underlying infrastructure isn't there.

**Pull request merged**
