### PR TITLE
6X Backport: Properly mark null return from combine functions

### PR DESCRIPTION
**Pull request by soumyadeep2007**
This is a backport of PR: #9946

### CODE REVIEW

**Comment by hlinnaka** [comment]
The concourse job failed, so probably needs a rebase, but aside from that, is this ready to go in?

**Comment by soumyadeep2007** [comment]
I remember that the test that we added in "Properly mark null return from combine functions" didn't work here (We needed a 2 stage agg for the combine fn and I think the 2 stage hash agg that we had to do a fair bit of coaxing-the-GUCs to get isn't appearing when we run our tests. Something is diff b/w 6x and master that is causing this, as the same test works on master) when I had submitted this backport. I guess we need to massage this again a bit. Tagging @d as he had context on this as well.

The other 2 commits are AOK to go in.

**Comment by JunfengYang** [comment]
I just update the test results, and the plan using two-stage agg with combine function, although the plan is different from master.

**Review by adam8157 — APPROVED** [review]
Nice to see this going in.

**Pull request merged**
