### PR TITLE
Add back global xaction info in one phase commit.

### PR DESCRIPTION
**Pull request by paul-guo-**
commit 4be677c7feb05a3dfcea9420b4ebeab4c0de6d4e removed that accidently.
This patch adds it back.

### CODE REVIEW

**Comment by paul-guo-** [comment]
@asimrp Thanks. distribTimeStamp and distribXid are used in pg_distributedlog writing code in this function also so we can not remove the local variables. As to the test, I thought a lot and tried some on last Friday, and found it is hard to find a way to test that since it seems there is no scenario that could be harmed by this info. I add that because this could mislead people when they debug related xlogs and also it could be a potential bug when working further on related features.

**Comment by paul-guo-** [comment]
One correction to commit message: commit b587100923e2963ee3c54a1db86a3f740be84b9b tends to add that info but the code is not right. It was not introduced by 4be677c.

**Comment by ashwinstar** [comment]
I thought test in `distributed_snapshot.sql` "Scenario3: Test the one-phase commit transactions don't break repeatable read isolation." was added to validate the distributed snapshot is being used and will also hence test that distributed ID is stamped with the local transaction ID for 1PC's too.

Is it really just info added for debugging and not really needed? I should in PR https://github.com/greenplum-db/gpdb/pull/7937 the conclusion was its required thing for correctness?

**Comment by paul-guo-** [comment]
@ashwinstar The Scenario3 test is for the corner case in the commit message of PR#7937. That patch in PR#7937 actually writes distributed id/timestamp info on primary directly but this patch is to add it in xlog also. There was a discussion about potential use of this in PR#7937 (gang reset + mirror failover) but that is not true in real scenario after investigation. It seems that there might be a scenario that could use this in the future: Previous query did not launch  qe process on a segment (e.g. direct dispatch on another segment) and then there is failover on that segment , then after failover we hope there is no gang reset (currently it will error out).

**Comment by ashwinstar** [comment]
Okay, got it. If no failover happens but just primary crashes and comes up after writing WAL record for the commit, even in that case the gang would reset? Otherwise that can be used to test the same.

**Comment by ashwinstar** [comment]
In general LGTM, so if not able to find the test, I am okay to push this in.

**Comment by paul-guo-** [comment]
@ashwinstar 

> Okay, got it. If no failover happens but just primary crashes and comes up after writing WAL record for the commit, even in that case the gang would reset? Otherwise that can be used to test the same.

For this case, no gang reset in that case. One case is that in final commit command, it will fail due to SyncRep complaint about dead Postmaster, see SyncRepWaitForLSN().

**Comment by paul-guo-** [comment]
Thanks for reviewing and discussing.

**Pull request merged**
