### PR TITLE
Remove unused package_tarball.bash/yml

### PR DESCRIPTION
**Pull request by amilkh**
References to this file also need to be removed in external
repositories, such as gporca.

Authored-by: Amil Khanzada <akhanzada@pivotal.io>

### CODE REVIEW

**Comment by amilkh** [comment]
Looks like there are no references in gporca?
https://github.com/greenplum-db/gporca/search?q=package_tarball&unscoped_q=package_tarball

**Comment by amilkh** [comment]
see also:
https://github.com/greenplum-db/gpdb/pull/8291
https://github.com/greenplum-db/gpdb/pull/8270

**Comment by chrishajas** [comment]
I think this may still be used in https://github.com/greenplum-db/gporca/blob/master/concourse/pipeline.yml#L542

**Comment by amilkh** [comment]
> I think this may still be used in https://github.com/greenplum-db/gporca/blob/master/concourse/pipeline.yml#L542

Good find! Could you please verify it doesn't break gporca team pipelines/workflow, remove it, then we could merge this PR?

**Comment by berlin-ab** [comment]
bump.

**Comment by tylarb** [comment]
Commit 40dead815da692ede58a6f6c491b4a0a1c7ff700 covers the scope of this PR and more. Closing as it's not longer in date.

**Pull request closed without merging**
