### PR TITLE
Support interval datetime

### PR DESCRIPTION
**Pull request by melanieplageman**
Merges in commits 70530c808bf8eaba2a41a28c9dc7b96dcc3b6c51 and f867339c0148381eb1d01f93ab5c79f9d10211de from Postgres to address github issues including https://github.com/greenplum-db/gpdb/issues/3023 and https://github.com/greenplum-db/gpdb/issues/3557

### CODE REVIEW

**Comment by hlinnaka** [comment]
We'll get these soon as part of the 8.4 merge anyway.

**Comment by vraghavan78** [comment]
Sounds good @hlinnaka this can go into GPDB 6 when it lands with the merge. But we would like to get it into GPDB 5 since it is a wrong behavior that we know off and not a lot of effort.

**Comment by melanieplageman** [comment]
Closing this pull request in order to open one against 5X_Stable

**Comment by Eulerizeit** [comment]
@melanieplageman can you push this through master first please.

**Pull request closed without merging**
