### PR TITLE
Add missing free call for component info structure

### PR DESCRIPTION
**Pull request by atris**

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Nice catch, :+1:. A similar leak seems to exist in `CreateFileSpace()` in `filespace.c` where `segments` is never freed, from a quick glance it seems we could free it in combination with `hash_destroy()`. See allocation at: https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/filespace.c#L173

**Comment by atris** [comment]
Ah, good catch.
I somehow missed it in my read through. Adding the fix.

**Comment by asimrp** [comment]
Both are good catches, :+1:

Could you please squash the two commits into one before push?

**Comment by atris** [comment]
Merged.Thanks for the review~

**Pull request closed without merging**
