### PR TITLE
docs - document the optimizer_cost_model guc

### PR DESCRIPTION
**Pull request by lisakowen**
add optimizer_cost_model to the guc reference.

will be backported to 6x and 5x.

### CODE REVIEW

**Review by dyozie — APPROVED** [review]
Looks good to me. But does this mean the resolved issue requires an undocumented setting, `OPTIMIZER_GPDB_EXPERIMENTAL` ?

**Comment by lisakowen** [comment]
@dyozie - no, i believe that `OPTIMIZER_GPDB_EXPERIMENTAL` is an internal constant that represents `experimental`.

**Review by vraghavan78 — APPROVED** [review]

**Review by zellerh — APPROVED** [review]
Thanks, LGTM, too.

**Comment by lisakowen** [comment]
thank you for reviewing this so quickly, @vraghavan78 and @zellerh !

**Pull request merged**
