### PR TITLE
Revert JSON OID's to match upstream

### PR DESCRIPTION
**Pull request by davecramer**
bump catalog version

### CODE REVIEW

**Comment by hlinnaka** [comment]
You'll need to adjust the argument/return types of json-related functions in pg_proc.h accordingly.

**Comment by hlinnaka** [comment]
Would be nice to also mention in the commit message why using the same OIDs as in upstream is a good idea, why we couldn't use them earlier and why we can now.

**Comment by davecramer** [comment]
it's probably going to be easier to do that when we squash the commits

**Comment by davecramer** [comment]
closed by https://github.com/greenplum-db/gpdb/commit/f2eabc1f3c328e9a08dd4a69cb1f609aa155bfee

**Pull request closed without merging**
