### PR TITLE
Attach a resource group even QD is in bypass mode

### PR DESCRIPTION
**Pull request by SmartKeyerror**
Currently, QD will not attach a resource group if QD is in bypass mode when it's already 
running in bypass mode, things will go wrong if we change role, just like:

```
CREATE RESOURCE GROUP rg_test_group WITH (cpu_max_percent=10, concurrency=5);
CREATE ROLE rg_test_role RESOURCE GROUP rg_test_group;

SET ROLE rg_test_role;
CREATE TABLE rg_test_group_table(a int);

-- Since rg_test_group_table is empty, the total cost of this SQL will be less than min_cost,
-- so it'll run in bypass mode
SELECT count(*) FROM rg_test_group_table;
SELECT is_session_in_group(pg_backend_pid(), 'rg_test_group');
RESET ROLE;

-- Still running in bypass mode, but the role is not rg_test_role
SELECT count(*) FROM rg_test_group_table;
SELECT is_session_in_group(pg_backend_pid(), 'admin_group');
DROP TABLE rg_test_group_table;
```

### CODE REVIEW

**Comment by haolinw** [comment]
I got the follow error:
```
>>> stdout = subprocess.run(["ssh", "{}".format("127.0.0.1"), "ps -ef | grep postgres | grep con{} | grep -v grep | awk '{{print $2}}'".format("con6")], capture_output=True, check=True).stdout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
>>>
```
Is that requiring higher python version(> 3.6) to run resgroup regression test ? If that's a mandatory requirement, need to add a comment with minimum required python version in resgroup_auxiliary_tool to be aware of that at least.

**Comment by SmartKeyerror** [comment]
The Python version of Greenplum 7 is required more than 3.6, and as I remember this is conventionally accepted since our pipeline is using Python 3.9 currently.

**Comment by haolinw** [comment]
> The Python version of Greenplum 7 is required more than 3.6, and as I remember this is conventionally accepted since our pipeline is using Python 3.9 currently.

Really? Any documentation about GP7 requiring which version of python ? My local env installed 3.6.8, and can run GP7 fine after I configured well, but hit this issue when I run single test manually. If having to install python3.9 to be able to run such tests successfully, it's obviously not same as GP7's compatibility.

**Comment by higuoxing** [comment]
Currently, on our CI (rocky8/rhel8/oel8), gpMgmt tools is using Python3.6 and PL/Python is using Python3.9. I think t makes sense to make PL/Python scripts compatible with Python3.6 since most of the time, there's only one Python installed on our dev machines/laptops.

**Comment by haolinw** [comment]
> Currently, on our CI (rocky8/rhel8/oel8), gpMgmt tools is using Python3.6 and PL/Python is using Python3.9. I think t makes sense to make PL/Python scripts compatible with Python3.6 since most of the time, there's only one Python installed on our dev machines/laptops.

Thanks for the info. Yes, that would be better to have only version of python installed in env, if that's feasible.

**Comment by haolinw** [comment]
Code looks fine and don't want to block by the common python version dependent issue around PL/Python the test scripts.

**Review by haolinw — APPROVED** [review]

**Pull request merged**
