### PR TITLE
Implement PXF Foreign Data Wrapper (6X_STABLE)

### PR DESCRIPTION
**Pull request by oliverralbertini**
This PR introduces a FDW implementation that can connect Greenplum with external data via the PXF service.

Currently this FDW can leverage Greenplum's parallel processing for reading data from external sources, but is limited to writing data to the external source on master only.

Unlike with external tables, PXF <-> Greenplum wire format is only CSV, this FDW does not use the old GreenplumWritable binary format.

COPY:

We externalized `BeginCopy()` in `src/backend/commands/copy.c`.

### CODE REVIEW

**Comment by hlinnaka** [comment]
For 6X? This is a huge change, surely we're not going to do it in a stable branch?

**Comment by Eulerizeit** [comment]
A few questions:

What is the user impact? Given this is a stable branch these changes should be seamless to end users. 

If the changes are seamless then what is the benefit of doing this in a stable branch? This is effectively rewriting an entire feature mid-cycle; understanding why is pretty important. 

Finally we need to recognize this is an ABI change and we need to agree that we are explicitly ok with that.

**Comment by oliverralbertini** [comment]
> For 6X? This is a huge change, surely we're not going to do it in a stable branch?

Need to clarify, the huge change you refer to is externalizing `BeginCopy()`?

If so, because that change is only needed for writing to foreign table with `pxf_fdw`, we can introduce a limited, read-only version of the extension. This way there is no change needed in `copy.{c,h}` in this PR, only on master.

**Comment by hlinnaka** [comment]
On 28/01/2020 21:25, Oliver Albertini wrote:
>     For 6X? This is a huge change, surely we're not going to do it in a
>     stable branch?
> 
> Need to clarify, the huge change you refer to is externalizing 
> |BeginCopy()|?

No, I'm talking about the whole PXF FDW module that this introduces. 
It's a whole new feature, with ~8000 additional lines of code.

Furthermore, this isn't complete. The grand plan with the PXF FDW is to 
get rid of the external protocol, currently in gpcontrib/pxf. We haven't 
figured out how to do the mapping from CREATE EXTERNAL TABLE into the 
corresponding foreign table objects yet, even on master. Trying to do 
that in a stable version raises a whole new set of questions: if we 
start mapping CREATE EXTERNAL TABLE to foreign tables, will we still 
need to dump them using the CREATE EXTERNAL TABLE command, so that you 
can also downgrade?

Alternatively, we could maintain both gpcontrib/pxf and the new FDW side 
by side. But that seems silly. We want to reduce our maintenance burden, 
and that would have the opposite effect.

The point of a stable release is that it's *stable*.

- Heikki

**Comment by oliverralbertini** [comment]
> No, I'm talking about the whole PXF FDW module that this introduces. It's a whole new feature, with ~8000 additional lines of code. Furthermore, this isn't complete. The grand plan with the PXF FDW is to get rid of the external protocol, currently in gpcontrib/pxf. We haven't figured out how to do the mapping from CREATE EXTERNAL TABLE into the corresponding foreign table objects yet, even on master. Trying to do that in a stable version raises a whole new set of questions: if we start mapping CREATE EXTERNAL TABLE to foreign tables, will we still need to dump them using the CREATE EXTERNAL TABLE command, so that you can also downgrade? Alternatively, we could maintain both gpcontrib/pxf and the new FDW side by side. But that seems silly. We want to reduce our maintenance burden, and that would have the opposite effect. The point of a stable release is that it's *stable*. - Heikki

Thanks for explaining. For what it's worth, 8k LOC is what the git diff says, but [cloc](http://cloc.sourceforge.net/) says it's about half that when excluding comments and blank lines:
```
$ cloc contrib/pxf_fdw/
      38 text files.
classified 38 files
      35 unique files.                              
Counting:  7
Counting:  1
Counting:  8
Counting:  5
      17 files ignored.

github.com/AlDanial/cloc v 1.76  T=1.03 s (20.3 files/s, 6929.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                8            773           1163           3430
SQL                              5            177            489            484
C/C++ Header                     6             86            293            218
make                             1              5              1             16
Markdown                         1              6              0             13
-------------------------------------------------------------------------------
SUM:                            21           1047           1946           4161
-------------------------------------------------------------------------------
```

But we agree that supporting both frameworks in 6X_STABLE is not desirable. Closing this PR for now.

**Pull request closed without merging**
