### PR TITLE
Refactor GFile to make it more modular.

### PR DESCRIPTION
**Pull request by karthijrk**
In this PR,  we enhanced gfile and workfile so 
1. `Buffile` and `BFZ` uses same mechanism (`ResourceOwner`) for resource cleanup.  
2. `BFZ` also uses the same mechanism (gfile) as rest of the system for zlib compression.
3. Fix the memory leak due to 1. 
4. Addressed the concerns raised from [gpdb-dev mailing list](https://groups.google.com/a/greenplum.org/forum/#!searchin/gpdb-dev/Refactor$20GFile$20to$20leverage$20Zlib$20$2B$20Postgres$27s$20File$20for$20work$20file%7Csort:relevance/gpdb-dev/eC-dRi-pUJU/rPsqb-hOAgAJ). 

Commit 1 - Partially revert the redundant `zlib` code from workfile (compress_zlib.c) and leverage `gfile` for the same similar to how it was before (https://github.com/greenplum-db/gpdb/commit/6c5eba7ca87e4020d8cb643cfa8f98c2382a032b). 

Commit 2. File access interface can take either C's file_descriptor or Postgres's File to access the file. Workfile uses Postgres's File so we use the same mechanism for cleanup. This will address the concerns mentioned in PR https://github.com/greenplum-db/gpdb/pull/1437.

Commit 3. Removed workfile from using TopMemory Context to fix the memory leak. With this, Memory context will take care of workfile data structure, resource owner will handle the file and counter will be handled by workset or used_segspace_not_in_workfile_set.

Commit 4: Enhance `gfile` to take allocator when it gets constructed. Also 
Enhance `bfz` to use `palloc` on `CurrentMemoryContext` instead of using `DataSourceContext`.

Commit 5: Enhanced `gfile` to have error code so the caller can get more error detail.

Commit 6: Added bunch of test for workfile.

Commit 7: Added necessary comments.

@foyzur @hardikar @armenatzoglou @hlinnaka @danielgustafsson  Please have a look when you get chance.

### CODE REVIEW

**Comment by hlinnaka** [comment]
FWIW, I still disagree with making compress_zlib.c to use gfile.

This is a superset of PR #1464, and we seem to be in agreement on that part. The only thing that held back pushing that was the lack of regression tests, so I copied over the regression tests from this PR to PR #1464. That one is now ready to be pushed.

Let's PR #1464 in, and rebase this PR over that. Then we can focus the discussion on the controversial parts of this PR.

**Comment by Eulerizeit** [comment]
@hlinnaka as I understand it the goal of this PR is to make a single clean mechanism for both gfile and zlib.  Is there a reason to disagree with that?

**Comment by hlinnaka** [comment]
On 01/20/2017 09:53 PM, Robert Eckhardt wrote:
> @hlinnaka as I understand it the goal of this PR is to make a single
> clean mechanism for both gfile and zlib.  Is there a reason to
> disagree with that?

gfile.c is an exceptional file, in that it needs to work in both backend 
code and frontend code. Forcing compress_zlib.c into the same mold is 
not an improvement. Overall, it makes things more complicated, not less.

The benefit is that it saves some code in compress_zlib.c, the code to 
call the zlib library. But the zlib library's interface is fairly 
straightforward and well documented, so there's no particular need to 
hide that away behind another abstraction.

If we wanted to do something here, I would actually suggest making two 
copies of gfile.c: one "gfile.c" for frontend use (gpfdist), and another 
for backend use. They could then diverge, so that the backend file could 
take advantage of all the backend facilities for memory management, 
resource cleanup on abort, and error reporting. That interface could be 
used by the compress_zlib.c, and fileam.c, in the server. And the 
frontend version would only need to worry about the needs of gpfdist.

I wouldn't put that very high on a priority list, either, though. Would 
be nice, but there's no particular urgency.


Another argument I've heard for this is that, by using the same module 
for the compression, we could a number of compression algorithms for 
workfiles, all the ones that are supported by gfile.c (zlib and bzip2, 
ATM). I don't buy that argument, because again the needs are quite 
different. Workfiles can benefit from compression, but they are 
typically written once and read once or a few times, and then deleted. 
We have full control over the creation of the files, we never need to 
read files created by the users, or need to be able to read files 
created with a different version. The optimal algorithm should therefore 
be fast at compressing and decompressing, and compression ratio is not 
as important. With those design criteria, we should pick one algorithm 
that is fast, and not bother with supporting multiple algorithms. And 
the optimal algorithm is almost certainly not zlib or bzip2, but 
something like LZO or Snappy.

- Heikki

**Comment by karthijrk** [comment]
I disagree. It's not about saving a number of lines of code. It's about maintainability particularly if there is a bug in one of those two. Also, gfile is used by fileam (assume related to external table) which depends on backend code. IMHO it doesn't make sense to have two different zlib code for two consumers(workfile, fileam) which also depend on Postgres backend. Like I mentioned in the gdb-dev mailing list, there is a significant code difference in code between gfile & compress_zlib for same Zlib compression. 

In this PR, I addressed the concerns for memory management and error handling as well. The only other concern left is about complexity. Is there any particular thing that you felt more complex that need more comments or more simplification. In my opinion, refactor is fairly simple using common software patterns. 

Also, I will agree with having own `gfile` for `gpfdist`. But that is of low priority in my opinion and this PR does the job of removing redundant code and ease the maintainability. As of now, I would consider this option as out of scope for this PR.

**Comment by karthijrk** [comment]
@hlinnaka It seems like we have an agreement that workfile wants to use `zlib` that relies on Postgres backend. But what about the external table which is using GFile? What's your thought?

**Comment by hlinnaka** [comment]
On 01/31/2017 10:20 PM, Karthikeyan Jambu Rajaraman wrote:
> @hlinnaka It seems like we have an agreement that workfile wants to
> use `zlib` that relies on Postgres backend. But what about the
> external table which is using GFile? What's your thought?

Yeah, would be good for external tables to also not rely on the current 
gfile.c code. That's a somewhat bigger change, though.

- Heikki

**Comment by karthijrk** [comment]
@hlinnaka  I reviewed the PR #1464 and it looks good to me. 

Foyzur is on vacation. Not sure if he has some comments. So I will keep this PR open until next week. I still prefer the refactor for GFile but if there are no other comments I will close this PR next week.

Given the PR#1464 already fix the memory leak and also the test is ported, commit 3, 6, and 7 are not needed.

**Comment by karthijrk** [comment]
I will close this PR as we didn't get consensus. We can reopen this if needed in future.

**Pull request closed without merging**
