### PR TITLE
Move Tinc BFV CTE, Joins tests to installcheck-good

### PR DESCRIPTION
**Pull request by hsyuan**

### CODE REVIEW

**Comment by hlinnaka** [comment]
What does "BFV" stand for?

**Comment by jimmyyih** [comment]
I think it stands for Bug Fix Verification?

**Comment by hsyuan** [comment]
Sorry for the confusion. It stands for "Bug Fix Verification".

Thanks~
Haisheng Yuan

**Comment by hsyuan** [comment]
Pushed to master https://github.com/greenplum-db/gpdb/commit/0168ad4c567675dffc22d956ae75ee8f3a7b19fa

**Pull request closed without merging**
