### PR TITLE
Docs: new reference page for system catalog functions

### PR DESCRIPTION
**Pull request by mperezfuster**
This PR:

- Creates a new documentation reference page for System Catalog Functions.
- Creates a sub-menu for Statistics Functions.
- Adds the function `pg_stat_get_backend_subxact` to the list under Statistics Functions.

Question:
- Should we also add `gp_get_suboverflowed_backends` to the list? Is this a wrapper of `pg_stat_get_backend_subxact`? I can see that the system view `gp_suboverflowed_backend` exists. What is the relationship among them all?

Review site:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-catfunct/greenplum-database/ref_guide-system_catalogs-catalog_ref-functions.html

### CODE REVIEW

**Review by huansong — COMMENTED** [review]
> Should we also add gp_get_suboverflowed_backends to the list? Is this a wrapper of pg_stat_get_backend_subxact? I can see that the system view gp_suboverflowed_backend exists. What is the relationship among them all?

Yes we should add `gp_get_suboverflowed_backends`, it prints only the backend PIDs that are subxact-overflowed. It is different than `pg_stat_get_backend_subxact` and provides more pointed output, so is useful to include.

And the `gp_suboverflowed_backend` view is a cluster-wide wrapper of `gp_get_suboverflowed_backends`. We should include it in the system view page (https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-catfunct/greenplum-database/ref_guide-system_catalogs-catalog_ref-views.html).

**Comment by mperezfuster** [comment]
> > Should we also add gp_get_suboverflowed_backends to the list? Is this a wrapper of pg_stat_get_backend_subxact? I can see that the system view gp_suboverflowed_backend exists. What is the relationship among them all?
> 
> Yes we should add `gp_get_suboverflowed_backends`, it prints only the backend PIDs that are subxact-overflowed. It is different than `pg_stat_get_backend_subxact` and provides more pointed output, so is useful to include.
> 
> And the `gp_suboverflowed_backend` view is a cluster-wide wrapper of `gp_get_suboverflowed_backends`. We should include it in the system view page (https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-catfunct/greenplum-database/ref_guide-system_catalogs-catalog_ref-views.html).

Thanks @huansong can you please help providing a short description of the function and the argument types?
Something similar to what we added for the function `pg_stat_get_backend_subxact`.

Regarding the view `gp_suboverflowed_backend`, it is already documented under system views (see below). I was just wondering if we had to mention any links between function and view. 

```
## <a id="gp_suboverflowed_backend"></a>gp_suboverflowed_backend

The `gp_suboverflowed_backend` view allows administrators to identify sessions in which a backend has subtransaction overflows, which can cause query performance degradation in the system, including catalog queries.

|column|type|description|
|------|----|----------|
|`segid`|integer|The id of the segment containing the suboverflowed backend.|
|`pids`|integer[]|A list of the pids of all suboverflowed backends on this segment.|

For more information on handling suboverflowed backends to prevent performance issues, see [Checking for and Terminating Overflowed Backends](../../admin_guide/managing/monitor.html#overflowed_backends).
```

**Comment by huansong** [comment]
Sure. Here's a draft for `gp_get_suboverflowed_backends` (there's no arguments):
```
### <a id="gp_get_suboverflowed_backends"></a>gp_get_suboverflowed_backends

`gp_get_suboverflowed_backends()` return type is `integer[]`.

Returns an array of integers which indicate the pids of all suboverflowed backends on the running segment. For cluster-wide view of the suboverflowed backends on every segment, you can use view `gp_get_suboverflowed_backend`.
```

> Regarding the view gp_suboverflowed_backend, it is already documented under system views (see below)

I see. Yes I think it would be helpful to provide a link in the description of `gp_get_suboverflowed_backends()` to link to the view `gp_get_suboverflowed_backend`. We don't need the other way around I think.

**Review by huansong — APPROVED** [review]
LGTM!

**Pull request merged**
