### PR TITLE
Move uao isolation tinc tests

### PR DESCRIPTION
**Pull request by hlinnaka**
This creates a new test suite, src/test/isolation2, which is much like the upstream one in src/test/isolation, but the Python isolation test runner, copied from TINC. Move the UAO isolation tests to the new test suite.

The UAOCS tests could and should be moved too. Or better, we should run this same test suite also with column-oriented tables, by setting gp_default_storage_options='orientation=column'. But I'll leave that for a follow-up patch.

### CODE REVIEW

**Comment by ashwinstar** [comment]
For max_concurrency test will atleast need 128 max_connections currently ICW runs with 50.

**Comment by Eulerizeit** [comment]
Can we GUC that test or could we change what ICW uses?

-- Rob

**Comment by ashwinstar** [comment]
Surprised to see you using Python test framework file from TINC ;-) plus didn't loose out drop table statements from tests.

Excellent move though.

While at it if wish can carry these along and that would remove all traces of isolation tests from TINC, first mission accomplished
```
./catalog/drop_rename/test_drop_rename.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
./catalog/mpp24606/test_mpp24606.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
./catalog/mpp25160/test_mpp25160.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
./dispatch/queryfinish/test_queryfinish.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
./queries/basic/rsq_mpp6144/test_rsqmpp6144.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
./storage/uao/uao_udf/test_uao_udf.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
./storage/vacuum/reindex/test_reindex.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
```

**Comment by hlinnaka** [comment]
On 02/17/2017 08:09 PM, Ashwin Agrawal wrote:
> For max_concurrency test will atleast need 128 max_connections currently ICW runs with 50.

Yeah, so it seems..

We could simply bump up max_connections, I suppose. Although, in the 
long run, we will need to be able to run test suites with different 
server settings. The "segspace" tests in the main regression suite 
already do that in a quite hacky way: the segspace_setup test sets a GUC 
in the config file with gpconfig and restarts the server. Then the 
actual segspace test runs. And finally, the segspace_end test resets the 
GUC and reboots the server again. That's why those tests altogether take 
about 1.5 minutes, which is a significant chunk of the overall 14 
minutes runtime of ICW on concourse.

Sooner or later, we need to bite the bullet and make "make check" and 
"make check-world" work. Those targets should set up a test cluster, 
with something like gpdemo, and run the tests against the that cluster. 
The different test suites could then set up a cluster with different 
settings.

- Heikki

**Comment by hlinnaka** [comment]
On 02/17/2017 08:20 PM, Ashwin Agrawal wrote:
> Surprised to see you using Python test framework file from TINC ;-) plus didn't loose out drop table statements from tests.

Heh, I was tempted to rewrite the same functionality in C :-). But I 
don't actually have anything against simple little python scripts like 
this, or python in general. The single .py file is quite manageable, now 
that it doesn't depend on the whole TINC framework.

> While at it if wish can carry these along and that would remove all traces of isolation tests from TINC, first mission accomplished
> ```
> ./catalog/drop_rename/test_drop_rename.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
> ./catalog/mpp24606/test_mpp24606.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
> ./catalog/mpp25160/test_mpp25160.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
> ./dispatch/queryfinish/test_queryfinish.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
> ./queries/basic/rsq_mpp6144/test_rsqmpp6144.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
> ./storage/uao/uao_udf/test_uao_udf.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
> ./storage/vacuum/reindex/test_reindex.py:from mpp.gpdb.tests.storage.lib.sql_isolation_testcase import SQLIsolationTestCase
> ```

Ah, we're tantalizingly close. Nice, I didn't realize that. I have the 
cs-uao concourse job in my cross-sight. After removing these isolation 
test cases, and the UML-DML test cases (PR #1778), there is very little 
of that left.

- Heikki

**Comment by ashwinstar** [comment]
On Fri, Feb 17, 2017 at 11:23 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 02/17/2017 08:09 PM, Ashwin Agrawal wrote:
> > For max_concurrency test will atleast need 128 max_connections currently
> ICW runs with 50.
>
> Yeah, so it seems..
>
> We could simply bump up max_connections, I suppose. Although, in the
> long run, we will need to be able to run test suites with different
> server settings. The "segspace" tests in the main regression suite
> already do that in a quite hacky way: the segspace_setup test sets a GUC
> in the config file with gpconfig and restarts the server. Then the
> actual segspace test runs. And finally, the segspace_end test resets the
> GUC and reboots the server again. That's why those tests altogether take
> about 1.5 minutes, which is a significant chunk of the overall 14
> minutes runtime of ICW on concourse.
>
> Sooner or later, we need to bite the bullet and make "make check" and
> "make check-world" work. Those targets should set up a test cluster,
> with something like gpdemo, and run the tests against the that cluster.
> The different test suites could then set up a cluster with different
> settings.
>

So, if wish to go route of increasing max connection for ICW in concourse
can do `export DEFAULT_QD_MAX_CONNECT=<something maybe 150>`
in ic_gpdb.bash before `make cluster` step.

**Comment by hlinnaka** [comment]
Oh, I just noticed that it's a bit silly that these tests require the 'setup' step, to install the gp_ao* functions. It's silly because all of those functions are already in gp_toolkit, eg. gp_toolkit.__gp_aovisimap().

I'm going to adjust these tests to leave contrib/gp_internal_tools alone, and just use the functions in gp_toolkit. Having a contrib module just to contain those wrappers is quite silly, why don't we just have the functions directly in the backend? But I'm not going to go down that rabbit hole right now.

**Comment by hlinnaka** [comment]
On 02/17/2017 10:08 PM, Ashwin Agrawal wrote:
> So, if wish to go route of increasing max connection for ICW in concourse
> can do `export DEFAULT_QD_MAX_CONNECT=<something maybe 150>`
> in ic_gpdb.bash before `make cluster` step.

Thanks, I did that for now.

- Heikki

**Comment by ashwinstar** [comment]
👍 Lets go.

**Comment by hlinnaka** [comment]
Thanks, pushed!

**Pull request closed without merging**
