### PR TITLE
Fix several compile warnings.

### PR DESCRIPTION
**Pull request by avamingli**
See issue https://github.com/greenplum-db/gpdb/issues/15551.

Authored-by: Zhang Mingli avamingli@gmail.com

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by hyongtao-db** [comment]
Hi, 
Thanks for your contribution. Seems this problem is solved in [pr 15512](https://github.com/greenplum-db/gpdb/pull/15512).

**Comment by avamingli** [comment]
> Hi, Thanks for your contribution. Seems this problem is solved in [pr 15512](https://github.com/greenplum-db/gpdb/pull/15512).

Oh, that is.

Shall we fix the warning in show_sort_info too?

```shell
explain.c: In function ‘show_sort_info’:
explain.c:3462:44: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 3462 |                                 sortMethod = tuplesort_method_name(sinstrument->sortMethod);
      |                                            ^
explain.c:3464:43: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 3464 |                                 spaceType = tuplesort_space_type_name(sinstrument->spaceType);
      |                                           ^
```

**Comment by hyongtao-db** [comment]
> Shall we fix the warning in show_sort_info too?

Yes. Thanks a lot.

**Comment by avamingli** [comment]
> > Shall we fix the warning in show_sort_info too?
> 
> Yes. Thanks a lot.

updated, remove duplicated fix with #15512 , keep fix for show_sort_info part.

**Pull request merged**
