### PR TITLE
Remove PartOidExpr, it's not used in GPDB.

### PR DESCRIPTION
**Pull request by hlinnaka**
The target lists of DML nodes that ORCA generates includes a column for the
target partition OID. It can then be referenced by PartOidExprs. ORCA uses
these to allow sorting the tuples by partition, before inserting them to the
underlying table. That feature is used by HAWQ, where grouping tuples that
go to the same output partition is cheaper.

Since commit adfad60883, which removed the gp_parquet_insert_sort GUC, we
don't do that in GPDB, however. GPDB can hold multiple result relations open
at the same time, so there is no performance benefit to grouping the tuples
first (or at least not enough benefit to counterbalance the cost of a sort).

So remove the now unused support for PartOidExpr in the executor.

### CODE REVIEW

**Comment by hlinnaka** [comment]
See the side-discussion on this at PR #2076

**Comment by hsyuan** [comment]
We have to remove PartOid in Orca to make this patch work as expected. Currently, Orca still generated PartOid dxl node in DXL, if the translator can't find the PartOid handler, Orca will fall back to planner. Or we can simply add a dummy handler for `PartOid`.

**Comment by vraghavan78** [comment]
@hlinnaka, can this wait till @foyzur has a chance to look at it. Thanks!

**Comment by foyzur** [comment]
@hlinnaka you need to remove acceptedLeafOid PartitionSelectorState. Other than that LGTM.

**Comment by vraghavan78** [comment]
Orca change may require fixing a lot of minidump files. QO team can do that. Please go with the dummy function option @hsyuan suggested.

**Comment by ascherbaum-pivotal** [comment]
What can we do with this PR?

Any suggestions from the Orca team?

**Comment by bhuvnesh2703** [comment]
@andreasscherbaum We have a corresponding ORCA PR   https://github.com/greenplum-db/gporca/pull/186 open for review.. Once thats approved, we will merge both in. Thanks

**Comment by vraghavan78** [comment]
@andreasscherbaum this is blocked on me. I just haven't had the bandwidth. I will get to it this week in reviewing it.

**Pull request merged**
