### PR TITLE
Remove primary_mirror_mode stuff.

### PR DESCRIPTION
**Pull request by hlinnaka**
Revert the state machine and other logic in postmaster.c the way it is in
upstream. Remove some GUCs related to mirrored and non-mirrored mode. Remove
the -M, -x and -y postmaster options, and change management scripts to not
pass those options.

### CODE REVIEW

**Comment by hlinnaka** [comment]
This is a rebased version of PR #4264.

**Comment by hlinnaka** [comment]
I cannot get the concourse CI page for this to open. It seems to get stuck in an infinite loop. So I don't know what's broken. @pivotal-mike, can you help?

**Comment by hlinnaka** [comment]
Added a bunch of commits to fix various bugs in postmaster.c. I'll squash them before pushing.

**Comment by ashwinstar** [comment]
MU_check is failing with 
```
======================================================================
ERROR: Test Suite Name|programs.test.unit.test_cluster_clsrecoversegment|Test Case Name|test_check_segment_state_ready_for_recovery_ignores_initial_stderr_warnings|Test Details|
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/build/edb35eda/gpdb_src/gpMgmt/bin/pythonSrc/ext/install/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/tmp/build/edb35eda/gpdb_src/gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment.py", line 136, in test_check_segment_state_ready_for_recovery_ignores_initial_stderr_warnings
    segmentStates = self.subject.check_segment_state_ready_for_recovery(segmentList, dbsMap)
  File "/tmp/build/edb35eda/gpdb_src/gpMgmt/bin/gppylib/programs/clsRecoverSegment.py", line 623, in check_segment_state_ready_for_recovery
    cmd = gp.SendFilerepTransitionStatusMessage(name="Get segment status information"
AttributeError: 'module' object has no attribute 'SendFilerepTransitionStatusMessage'
```
maybe remove those tests as relates to gprecoverseg.

**Comment by hlinnaka** [comment]
Thanks Ashwin! And the concourse link works now, too. Maybe there were so much stuff failing before, that something was overloaded, but after the latest bug fixes in the branch, it now doesn't fail so badly?

**Comment by ashwinstar** [comment]
Also `gpstate -a` fails on this branch, seems will need changes as feel was using `primary_mirror_mode.c` to get status from primaries.

**Comment by ashwinstar** [comment]
`gpfaultinjector` will not work and hence all the tests using the same need to start using the new extension.

**Comment by hlinnaka** [comment]
Ok, I don't know how to take this further. As @ashwinstar noted, gprecoverseg tests are failing. I believe gprecoverseg is doomed, it's going to need a major rewrite. But maybe we want to keep the UI? Should I expand this and remove all traces of gprecoverseg, or what should we do?

Can someone who has a plan on Management Utils pick this up, please?

**Comment by Eulerizeit** [comment]
ignore the gprecoverseg tests. All of that code is being rewritten.

**Comment by hlinnaka** [comment]
On 17/01/18 17:37, Robert Eckhardt wrote:
> ignore the gprecoverseg tests. All of that code is being rewritten.

I'm going to need help to ignore them, then :-). Remove them altogether, 
or is there a way to disable them, or?

- Heikki

**Comment by Eulerizeit** [comment]
They should be paused, I'm not sure why they are running at all.

-- Rob

**Comment by ashwinstar** [comment]
@hlinnaka, just FYI @asimrp is working on removing `gpfaultinjector` calls from all tests and instead use the fault injector extension. That should help make progress to fix many currently failing tests.

**Comment by asimrp** [comment]
We plan to fix remaining issues in the new PR #4364.  Closing this one.

**Pull request closed without merging**
