### PR TITLE
[Bakcport to 6X] GPORCA: map DATE type values to LINT # of days instead of DOUBLE mcsecs

### PR DESCRIPTION
**Pull request by maksm90**
Backport to 6X from PR https://github.com/greenplum-db/gpdb/pull/11349

### CODE REVIEW

**Comment by maksm90** [comment]
Could anyone print the fail reason out on concourse-ci?

**Comment by asimrp** [comment]
@maksm90 the compilation job failed because the GPORCA unit test "gporca_test_CICGTest" failed:

```
Test project /tmp/build/1bbb0505/gpdb_src/src/backend/gporca/build
        Start 101: gporca_test_CICGTest
166/167 Test #101: gporca_test_CICGTest ..............................***Failed   10.49 sec
2021-02-12 21:40:27:335573 UTC,THD000,TRACE,"opening file ../data/dxl/metadata/md.xml",
2021-02-12 21:40:27:399848 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/OneSegmentGather.mdp",
2021-02-12 21:40:27:406118 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/OneSegmentGather.mdp",
2021-02-12 21:40:27:411474 UTC,THD000,TRACE,"opening file ../data/dxl/minidump/OneSegmentGather.mdp",
2021-02-12 21:40:27:441169 UTC,THD000,TRACE,"[OPT]: Number of plan alternatives: 12",
2021-02-12 21:40:27:443386 UTC,THD000,TRACE,"timer:Minidump: 26ms",
2021-02-12 21:40:27:443729 UTC,THD000,TRACE,"timer:Minidump: 37ms",
2021-02-12 21:40:27:444142 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/CTEWithOuterReferences.mdp",
2021-02-12 21:40:27:446867 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/CTEWithOuterReferences.mdp",
2021-02-12 21:40:27:449501 UTC,THD000,TRACE,"opening file ../data/dxl/minidump/CTEWithOuterReferences.mdp",
2021-02-12 21:40:27:460867 UTC,THD000,NOTICE,"Operator CTE with outer references not supported",
2021-02-12 21:40:27:463046 UTC,THD000,TRACE,"timer:Minidump: 10ms",
2021-02-12 21:40:27:463087 UTC,THD000,TRACE,"timer:Minidump: 16ms",
2021-02-12 21:40:27:463226 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/CTEMisAlignedProducerConsumer.mdp",
2021-02-12 21:40:27:469084 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/CTEMisAlignedProducerConsumer.mdp",
2021-02-12 21:40:27:474725 UTC,THD000,TRACE,"opening file ../data/dxl/minidump/CTEMisAlignedProducerConsumer.mdp",
2021-02-12 21:40:27:512745 UTC,THD000,ERROR,"CTE Producer-Consumer execution locality mismatch for CTE id 30151728",
2021-02-12 21:40:27:515322 UTC,THD000,ERROR,"CTE Producer-Consumer execution locality mismatch for CTE id 30151728",
2021-02-12 21:40:27:517882 UTC,THD000,TRACE,"timer:Minidump: 36ms",
2021-02-12 21:40:27:517962 UTC,THD000,TRACE,"timer:Minidump: 48ms",
2021-02-12 21:40:27:522027 UTC,THD000,TRACE,"timer:CICGTest::EresUnittest_RunUnsupportedMinidumpTests: 122ms",
2021-02-12 21:40:27:522037 UTC,THD000,TRACE,"Unittest CICGTest::EresUnittest_RunUnsupportedMinidumpTests...OK.",
2021-02-12 21:40:27:522169 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/Negative-IndexApply1.mdp",
2021-02-12 21:40:27:528958 UTC,THD000,TRACE,"opening file ../data/dxl/minidump/Negative-IndexApply1.mdp",
2021-02-12 21:40:27:550774 UTC,THD000,ERROR,"No plan has been computed for required properties",
2021-02-12 21:40:27:551037 UTC,THD000,ERROR,"No plan has been computed for required properties",
2021-02-12 21:40:27:551238 UTC,THD000,TRACE,"timer:Minidump: 14ms",
2021-02-12 21:40:27:551327 UTC,THD000,TRACE,"timer:Minidump: 29ms",
2021-02-12 21:40:27:551369 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/Negative-IndexApply2.mdp",
2021-02-12 21:40:27:559133 UTC,THD000,TRACE,"opening file ../data/dxl/minidump/Negative-IndexApply2.mdp",
2021-02-12 21:40:27:584487 UTC,THD000,ERROR,"No plan has been computed for required properties",
2021-02-12 21:40:27:584726 UTC,THD000,ERROR,"No plan has been computed for required properties",
    ...
2021-02-12 21:40:37:728389 UTC,THD000,TRACE,"Unittest CICGTest...*** FAILED ***.",
2021-02-12 21:40:37:728393 UTC,THD000,TRACE,"timer:total test run time: 10328ms",
2021-02-12 21:40:37:728396 UTC,THD000,TRACE,"Tests succeeded: 0",
2021-02-12 21:40:37:728399 UTC,THD000,TRACE,"Tests failed:    1",

```

**Comment by maksm90** [comment]
Hi, @asimrp! Thanks for sharing the log output from `ctest` but on my local installation I don't encounter with any fails and error lines posted above doesn't refer to failed cases. Could you share the log line with pattern `FAILED` or all log lines under `CICGTest` test suite?

**Comment by asimrp** [comment]
Apologies for posting an insufficient snippet, the output is too big and cumbersome to copy and paste.  Let me post another snippet, hopefully with some clues this time: 
```
2021-02-12 21:40:31:281224 UTC,THD000,TRACE,"IsRunning test with EXHAUSTIVE SEARCH:",
2021-02-12 21:40:31:282711 UTC,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/TPCH-Q5.mdp",
2021-02-12 21:40:31:328223 UTC,THD000,ERROR,"Missing attribute value for attribute LintValue in element ConstValue",
2021-02-12 21:40:31:328625 UTC,THD000,TRACE,"timer:CICGTest::EresUnittest_RunMinidumpTests: 3740ms",
2021-02-12 21:40:31:328630 UTC,THD000,TRACE,"Unittest CICGTest::EresUnittest_RunMinidumpTests...*** FAILED ***.",
```

**Comment by maksm90** [comment]
@asimrp thanks, you hits the spot! I have missed test case inside `TPCH-Q5.mdp` that is accessible in non-debug build.

**Review by zellerh — APPROVED** [review]
The port looks good to me.

**Pull request merged**
