### PR TITLE
Move some GPDB-specific code out of smgr.c and md.c.

### PR DESCRIPTION
**Pull request by hlinnaka**
For clarity, and to make merging easier.

The code to manage the hash table of "pending fsyncs" for append-only
tables is moved to smgr_ao.c. One notable change here is that the
pendingDeletesPerformed flag is removed. It was used to track whether there
are any pending deletes, or any pending AO table syncs, but we might as well
check the pending delete list and the pending syncs hash table directly,
it's hardly any slower than checking a separate boolean.

There are still plenty of GPDB changes in smgr.c, but this is a good step
forward.

### CODE REVIEW

**Comment by ashwinstar** [comment]
>> "pending fsyncs" for append-only tables

I need to look into, curious what's that, there shouldn't be anything like fsync AO.

**Comment by ashwinstar** [comment]
Its RESYNC EOFs tracking for incremental recovery of segment, not FYSNC :-)

**Comment by hlinnaka** [comment]
Oh, ok . I thought it was about fsyncs. So it's something mirroring related? Would be good to write a paragraph or two at the top of smgr_ao.c to explain what the "resync EOFs" are. I can write it, but I don't know myself so you'll need to enlighten me first :-).

**Comment by Eulerizeit** [comment]
@asimrp @ashwinstar  This PR is currently part of the iteration 4 fork we are working on. As that work is coming to a close we'd like to make sure we continue the conversation on this PR. The goal is for us to not 'sneak' anything in even by accident.

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Pull request merged**
