### PR TITLE
[7X] Don't initialize ORCA on query executors

### PR DESCRIPTION
**Pull request by RekGRpth**
Currently, the ORCA optimizer is initialized unconditionally in all backends. But we can reduce memory consumption by avoiding ORCA initialization on query executors where ORCA is never used.
This can be done using the Gp_role variable, which is set to GP_ROLE_EXECUTE on the executors, and this happens before ORCA is initialized.

### CODE REVIEW

**Review by gpopt — APPROVED** [review]
+1

**Comment by kainwen** [comment]
@gpopt Can the team help build a full dev pipeline to verify this?

**Comment by pobbatihari** [comment]
@RekGRpth, Could you please rebase the branch with the latest main? We are currently facing some issues to run pipeline on this branch, and rebasing might help resolve them.

**Review by chrishajas — APPROVED** [review]
Looks good, thanks!

**Comment by chrishajas** [comment]
I remember having some discussions before around initializing Orca on segments, but didn't remember the full context. Here's a small discussion from another PR, https://github.com/greenplum-db/gpdb/pull/12524, but even here we don't have a solid reason beyond "defensive purposes", so I'd support merging this and backporting.

**Comment by chrishajas** [comment]
Merged, thanks!

**Pull request merged**
