### PR TITLE
Stop using strxfrm() for string sorting.

### PR DESCRIPTION
**Pull request by hlinnaka**
strxfrm() is buggy on some platforms and locales. We found this out the
hard way in the PostgreSQL community, when we tried to use strxfrm() for
string sorting in PostgreSQL 9.5. We've been doing it on Greenplum,
anyway, but it's just as buggy for Greenplum as it was for PostgreSQL 9.5.

Fixes https://github.com/greenplum-db/gpdb/issues/6586

Discussion: https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/MUplsaJHLg0

### CODE REVIEW

**Comment by hlinnaka** [comment]
Some performance testing of this would be nice. Although, I don't think we have much choice, even if this causes a noticeable slowdown..

**Comment by vraghavan78** [comment]
Can we have a test with the Russian locale?

**Comment by berlin-ab** [comment]
Looks like we still need to introduce a test using `ru_RU.utf8` for sort ordering. I did a quick search in our codebase for reference to that character encoding and it is not referenced anywhere, and we've not introduced it as a part of this PR.

**Comment by berlin-ab** [comment]
Let's revisit this soon. It looks like it was useful for @leskin-in at @arenadata

**Comment by berlin-ab** [comment]
It's time to revisit this. Would someone take a moment to follow up on this?

**Comment by darthunix** [comment]
I want to resurrect this PR as the problem still exists in all `GPDB` branches: `5X`, `6X` and `master`. @hlinnaka can you take a look at https://github.com/arenadata/gpdb/commit/30b93fd69dbc53ffeb9599e07dfea043ca6571fd? An origin https://github.com/hlinnaka/gpdb/commit/650713814992bedf51b358d2b0b41d6745ef1ec5 have been rebased to current master, a `default` condition have been preserved according to @leskin-in [suggestion](https://github.com/greenplum-db/gpdb/pull/6927#discussion_r255458295) and a sorting test have been added.
It would be nice if we finally merge this PR.

**Comment by hlinnaka** [comment]
This was fixed by https://github.com/greenplum-db/gpdb/pull/10502. Closing.

**Pull request closed without merging**
