### PR TITLE
Fix the cs_storage tests

### PR DESCRIPTION
**Pull request by asubramanya**
This patch updates the sql and answer files for the vacuum_xid_limits,
ctlog and queryfinish tests

### CODE REVIEW

**Comment by asimrp** [comment]
Why did uaocs_catalog_tables fail?  Is your branch not rebased off latest master?

**Comment by asubramanya** [comment]
@asimrp Seems like it wasn't rebased. I have rebased to the latest master now.

**Comment by asimrp** [comment]
LGTM

**Comment by asubramanya** [comment]
Thanks for review. Pushed: bdc45d9a7e2efa3cc5a07150444ec785c4eb1ad9

**Comment by danielgustafsson** [comment]
Closing this PR as the code was pushed.

**Pull request closed without merging**
