### PR TITLE
Update config.guess and config.sub

### PR DESCRIPTION
**Pull request by oflebbe**
Compiling greenplum with Apache Bigtop on PowerPC fails.
See for instance in https://ci.bigtop.apache.org/job/Bigtop-trunk-packages/COMPONENTS=gpdb,OS=fedora-25-ppc64le/16/console

Updated config.guess and config.sub as documented in
> https://www.gnu.org/software/automake/manual/html_node/Auxiliary-Programs.html#Auxiliary-Programs

Error message is:

> ./configure --prefix=/usr/lib/gpdb
>checking build system type... config/config.guess: unable to guess system type
>
>This script, last modified 2011-05-11, has failed to recognize
>the operating system you are using. It is advised that you
>download the most up to date version of the config scripts from
>
 > http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
>and
 > http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
>
>If the version you run (config/config.guess) is already up to date, please
>send the following data and any information you think might be
>pertinent to <config-patches@gnu.org> in order to provide the needed
>information to handle your system.
>
>config.guess timestamp = 2011-05-11

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@oflebbe Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1554)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1554) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@oflebbe Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1554)!

**Comment by hlinnaka** [comment]
+1. As a data point, PostgreSQL has updated these files too.

**Comment by schubert** [comment]
+1 This looks fine to me but @CyrusWadia & @davidschachner have the last word.

Any concerns we should have about updating autoconf (dev only build scripts) files from GPL 2 to GPL 3?

**Comment by schubert** [comment]
We are good to go @danielgustafsson

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Pull request closed without merging**
