### PR TITLE
Bump up sequence default catch

### PR DESCRIPTION
**Pull request by weinan003**
After a few performance test, if sequence default catch is 1 which
same as upstream, the sequence server is slow down our query execution.

```
demo=# alter sequence  sq1  cache  1;
ALTER SEQUENCE
Time: 8.195 ms
demo=# insert into tbl_xulie2 select nextval('sq1'), i::text from generate_series(1, 100000)i ;
INSERT 0 100000
Time: 17515.052 ms
demo=# alter sequence  sq1  cache  20;
ALTER SEQUENCE
Time: 5.449 ms
demo=# insert into tbl_xulie2 select nextval('sq1'), i::text from generate_series(1, 100000)i ;
INSERT 0 100000
Time: 4869.909 ms
```

Since every sequence number must apply from QD sequence server. Bump up default catch from 1 to 20.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by JunfengYang** [comment]
Why we choose `20`?

**Comment by weinan003** [comment]
> Why we choose `20`?

It is an empiric value

**Comment by asimrp** [comment]
To reduce the diff in test output, my suggestion is to change the sequence cache size to 1 before running tests.  This is important for tests that are inherited from upstream.

Does it make sense to identify specific bottlenecks, if any, (e.g. using perf) in the execution of `insert into tbl_xulie2 select nextval('sq1'), i::text from generate_series(1, 100000)i ;`?

**Comment by weinan003** [comment]
> To reduce the diff in test output, my suggestion is to change the sequence cache size to 1 before running tests. This is important for tests that are inherited from upstream.

Sounds good

> Does it make sense to identify specific bottlenecks, if any, (e.g. using perf) in the execution of `insert into tbl_xulie2 select nextval('sq1'), i::text from generate_series(1, 100000)i ;`?

emm... It is one case for sequence cache. We also collect some results from customers.

**Review by asimrp — APPROVED** [review]
The test diff looks much smaller, thank you!

**Comment by asimrp** [comment]
Note that the PR pipeline has failed!

**Comment by asimrp** [comment]
> Just far stretched thought, can GPCC maybe someway emit the recommendation based on insert pattern to table (singleton or bulk number of rows) and sequence usage what cache value would be good to use for gaining better performance.

@funcode does that proposal from Ashwin sound interesting for GPCC?

**Comment by paul-guo-** [comment]
The idea is part of "autonomous database". Long ago heard about the related discussion from GPCC. I think it's on their list.

**Comment by funcode** [comment]
@ashwinstar @asimrp Thanks for the proposal! Recommendations on performance tuning is on our long-term roadmap.

**Pull request merged**
