### PR TITLE
Remove use of xml type in regression test

### PR DESCRIPTION
**Pull request by danielgustafsson**
The xml type is not a default built-in type, but requires the server to be compiled with `--with-libxml`. Since the type doesn't seem to do much in this test, remove it to avoid failing tests in environments not compiled with libxml support.

I am typically not building with XML support and having ICW fail on non-XML testsuites is annoying.

### CODE REVIEW

**Comment by Eulerizeit** [comment]
Do we have any tests the do text XML support than run only when you compile `--with-libxml`?

**Comment by danielgustafsson** [comment]
> On 15 Nov 2018, at 01:36, Robert Eckhardt <notifications@github.com> wrote:
> 
> Do we have any tests the do text XML support than run only when you compile --with-libxml?

No, the xml tests are executed regardless (I lost that patchbattle a long time ago - I’d still like to make the xml tests only run but by putting them in their own schedule and running that conditionally via inspecting options in the makefile), but at least when they fail in a non-XML build it’s obvious whats going on.

**Comment by Eulerizeit** [comment]
> I’d still like to make the xml tests only run but by putting them in their own schedule and running that conditionally via inspecting options in the makefile), but at least when they fail in a non-XML build it’s obvious whats going on.

That sounds like a tomorrow problem. @tvesely @kmacoskey @pivotal-mike  FYI since we talked about ordering tests like this at some point.

**Comment by d** [comment]
LGTM :shipit:

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review!

**Pull request closed without merging**
