### PR TITLE
Remove deprecated analytical functions

### PR DESCRIPTION
**Pull request by danielgustafsson**
Most of the builtin analytical functions added in Greenplum have been deprecated in favour of the corresponding functionality in MADLib. The deprecation notice was committed in a61bf8b, code as
well as tests are removed here. The sum(array[]) function require the matrix_add() backend code and thus it remains.

This removes matrix_add(), matrix_multiply(), matrix_transpose(), pinv(), mregr_coef(), mregr_r2(), mregr_pvalues(), mregr_tstats(), nb_classify() and nb_probabilities().

Ping @ivannovick, @Eulerizeit

### CODE REVIEW

**Comment by Eulerizeit** [comment]
@iyerr3 @ivannovick should we also be removing the sum(array[]) function? is that in MADlib as well?

**Comment by iyerr3** [comment]
MADlib does provide a `sum(anyarray)` function but IMO that is a useful enough function to keep in GPDB. Of course, if parity with postgres is the objective then it's better to remove it.

**Comment by danielgustafsson** [comment]
Keeping `sum()` for arrays is not likely to cause any problems for merging upstream so I'm fine with keeping it.

**Comment by pivotal-mike** [comment]
+1

**Comment by danielgustafsson** [comment]
Pushed to master, thanks

**Pull request merged**
