### PR TITLE
Change default prefix: /usr/local/gpdb

### PR DESCRIPTION
**Pull request by edespino**
Change Greenplum's default prefix to /usr/local/gpsql.  This avoids
confusion and conflicts with the default PostgreSQL
directory (/usr/local/pgsql).

NOTE: PostgreSQL legacy behavior (src/Makefile.global.in) If the prefix
contains the string "pgsql" or "postgres", the directory normally
populated at $GPHOME/share/postgresql will instead use $GPHOME/share.
This will cause issues for several Greenpum utilities expecting files to
be located in $GPHOME/share/postgresql (example: gpinitsystem reference
$GPHOME/share/postgresql/gp_toolkit.sql).

### CODE REVIEW

**Comment by edespino** [comment]
This change addresses issue #22.

**Comment by hlinnaka** [comment]
Hmm, /usr/local/gpsql is visually very close to /usr/local/pgsql. And I don't think we use the abbreviation "gpsql" anywhere else. How about /usr/local/greenplum or /usr/local/gpdb?

Which directory does the binary installers install to by default?

**Comment by hlinnaka** [comment]
PS. check the Author-field in the commit, it says "GPDB dev engineer"

**Comment by davecramer** [comment]
I'd prefer gpdb as well

**Comment by ddanese** [comment]
would it be feasible to do /usr/local/gpdb-x.x.x including the version number? Typical installations, prior to open sourcing, used this to allow for db upgrades and parallel versions for regression testing.

**Comment by edespino** [comment]
@hlinnaka & @davecramer I definitely like the /usr/local/gpdb suggestion.  I will update accordingly.

@hlinnaka - Thanks for pointing out the Author-Field.  I will be committing as this change as me and not "GPDB dev engineer" (an artifact in my VM environment).

@ddanese - Nothing prevents a user from running configure with a prefix that has any value (including version string) they desire.  Most open source projects that I have used do not embed a version string in the default prefix.

**Comment by hlinnaka** [comment]
@edespino, have you got plans to update/push this soon? I'd like to clear the queue of old pull requests..

**Comment by edespino** [comment]
Pushed to master.

**Pull request closed without merging**
