### PR TITLE
fix to ao vacuum deadlock

### PR DESCRIPTION
**Pull request by bucklerjj**
When a vacuum of a partitioned append-optimized table runs concurrent to inserts, it is possible to get an undetected deadlock.  This can occur during the drop phase because the vacuum is acquiring an AccessExclusiveLock lock at the partition level while the insert starts with RowExclusiveLock at the table level.  Then the insert tries to acquire an AccessShareLock lock at the partition level on the master and blocks.  Meanwhile, the vacuum is trying to acquire an AccessExclusiveLock on the segments.  At that point we have a distributed deadlock.

Given the current locking approach, I don't think the vacuum can start locking at the partition level.  I wrote a patch for vacuum.c that acquires a table level lockon the master during the drop phase before acquiring the partition level lock.  This more closely mimics the behavior of the insert.

The test script will deadlock about half the time on my system.  It is rather dependent on timing.  In particular, the second set of inserts need to start a bit after the vacuum.  If you don't see the issue, try increasing the number of rows in the first insert into the ao_deadlock table.

test script:

#!/bin/ksh

time $GPHOME/bin/psql -d gp_dev1 <<EOF

drop table ao_deadlock;
create table ao_deadlock
(c1 int not null,
c2 int not null,
c3 int not null)
with (appendonly=true, orientation=column, compresstype=zlib)
distributed by (c2)
partition by list (c3) ( partition c3_0 values (0), partition c3_1 values (1))
;

insert into ao_deadlock select a.c1, 1, 0 from generate_series(1, 20000000) a(c1);

delete 
from ao_deadlock a
where random() < 0.5 
;

EOF

time $GPHOME/bin/psql -d gp_dev1 <<EOF &
set trace_locks=on;
vacuum ao_deadlock;
EOF

sleep 1

time $GPHOME/bin/psql -d gp_dev1 <<EOF &
set trace_locks=on;
insert into ao_deadlock select a.c1, 1, 0 from generate_series(1, 1000000) a(c1);
insert into ao_deadlock select a.c1, 1, 0 from generate_series(1, 1000000) a(c1);
insert into ao_deadlock select a.c1, 1, 0 from generate_series(1, 1000000) a(c1);
EOF

wait

insert waiting on master:
```
gpadmin@stdwfprfw02:/opt/gpadmin/gp_dev3/work>lock.ksh
 usename | procpid | sess_id |           relname           | database | relation | pid  |        mode         | granted 
---------+---------+---------+-----------------------------+----------+----------+------+---------------------+---------
 gpadmin |    1833 |       8 | ao_deadlock_1_prt_c3_0      |    16384 |    18649 | 1833 | AccessExclusiveLock | t
 gpadmin |    1833 |       8 | ao_deadlock_1_prt_c3_0      |    16384 |    18649 | 1833 | AccessShareLock     | t
 gpadmin |    1833 |       8 |                             |          |          | 1833 | ExclusiveLock       | t
 gpadmin |    1863 |       9 | ao_deadlock                 |    16384 |    18619 | 1863 | RowExclusiveLock    | t
 gpadmin |    1863 |       9 | ao_deadlock_1_prt_c3_0      |    16384 |    18649 | 1863 | AccessShareLock     | f
 gpadmin |    1863 |       9 |                             |          |          | 1863 | ExclusiveLock       | t
 gpadmin |    2184 |      14 | pg_authid                   |        0 |     1260 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_authid_oid_index         |        0 |     2677 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_authid_rolname_index     |        0 |     2676 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_authid_rolresqueue_index |        0 |     6029 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_class                    |    16384 |     1259 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_class_oid_index          |    16384 |     2662 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_class_relname_nsp_index  |    16384 |     2663 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_database                 |        0 |     1262 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_database_datname_index   |        0 |     2671 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_database_oid_index       |        0 |     2672 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_locks                    |    16384 |    11326 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 | pg_stat_activity            |    16384 |    11394 | 2184 | AccessShareLock     | t
 gpadmin |    2184 |      14 |                             |          |          | 2184 | ExclusiveLock       | t
(19 rows)
```

vacuum waiting on segment:
```
 usename | procpid | sess_id |           relname           | database | relation | pid  |        mode         | granted 
---------+---------+---------+-----------------------------+----------+----------+------+---------------------+---------
 gpadmin |    1840 |       8 | ao_deadlock_1_prt_c3_0      |    16384 |    18649 | 1840 | AccessExclusiveLock | f
 gpadmin |    1840 |       8 |                             |          |          | 1840 | ExclusiveLock       | t
 gpadmin |    1870 |       9 | ao_deadlock                 |    16384 |    18619 | 1870 | RowExclusiveLock    | t
 gpadmin |    1870 |       9 | ao_deadlock_1_prt_c3_0      |    16384 |    18649 | 1870 | AccessExclusiveLock | t
 gpadmin |    1870 |       9 | ao_deadlock_1_prt_c3_0      |    16384 |    18649 | 1870 | RowExclusiveLock    | t
 gpadmin |    1870 |       9 |                             |          |          | 1870 | ExclusiveLock       | t
 gpadmin |    2232 |      13 | pg_authid                   |        0 |     1260 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_authid_oid_index         |        0 |     2677 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_authid_rolname_index     |        0 |     2676 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_authid_rolresqueue_index |        0 |     6029 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_class                    |    16384 |     1259 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_class_oid_index          |    16384 |     2662 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_class_relname_nsp_index  |    16384 |     2663 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_database                 |        0 |     1262 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_database_datname_index   |        0 |     2671 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_database_oid_index       |        0 |     2672 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_locks                    |    16384 |    11326 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 | pg_stat_activity            |    16384 |    11394 | 2232 | AccessShareLock     | t
 gpadmin |    2232 |      13 |                             |          |          | 2232 | ExclusiveLock       | t
(19 rows)
```

### CODE REVIEW

**Comment by asimrp** [comment]
Thank you @bucklerjj, that's quite a deadlock.  To clarify slightly, the `AcessExclusiveLock` that vacuum (session 8) is waiting on is of type appendonly segment file lock.  Where as the `AccessShareLock` that insert (session 9) is waiting on on master is of type relation.

I need to go through insert flow to understand this better.  My confusion is why is insert acquiring `AccessShareLock` on the partition on master **after** acquiring `AccessExclusiveLock` on the segment file for that partition on segment.

**Comment by ashwinstar** [comment]
The `AccessShareLock` is taken in case of partition tables very late during 'mppExecutorFinishup' on master based on results from QEs. Only AO/CO tables for which tuples were modified, counts get updated on master after acquiring this lock post performing the work on QEs. For non-partition table `AccessShareLock` is not acquired, already held `RowExclusiveLock` on table protects us.

@bucklerjj My current thinkings is acquiring 'AccessExclusiveLock' on parent seems too restrictive. We allow VACUUM and other operations on child partition level. Concurrent VACUUM on two child partition table would also have contention which they do not currently. Plus do not know if any other operation apart from VACUUM faces similar issue.

Will need more thought but seems better to take `AccessShareLock` on table by insert on master before going to segment and acquiring `AccessExclusiveLock` on segment file. If this becomes tricky to do or more operations like update/delete behave similar to insert then we need to stick with your proposal.

**Comment by ascherbaum-pivotal** [comment]
This PR is open for quite a while now. Is there an update available?

**Comment by ascherbaum-pivotal** [comment]
@asimrp @ashwinstar Did you find time to look at this PR? Would like to see it closed.

**Comment by ascherbaum-pivotal** [comment]
@bucklerjj Can you please provide an update on this PR? Do you still plan to work on this?

**Pull request closed without merging**
