### PR TITLE
Speed up gpinitsystem slightly.

### PR DESCRIPTION
**Pull request by hlinnaka**
* Remove an unnecessary sleep 2
* Perform the lookup of master hostname only once

### CODE REVIEW

**Comment by ivannovick** [comment]
LGTM, one of the main reason its slower is because of lack of parallelism in the segment creat

**Comment by hlinnaka** [comment]
Umm, you didn't actually mean to close this, I presume? Reopened

**Comment by ivannovick** [comment]
yeah that was a fit finger, sorry.  The change looks good, and i also was going to mention that we don't use threads/parallel initialization of the segments, so it can take a long time to run gpinitsystem on bigger clusters.  Fixing that is on a todo list.

**Comment by hlinnaka** [comment]
Sure. This patch reduces the time to initialize the small gpdemo cluster from about 1:30 minutes to 1:00 minutes, on my laptop. Which is a nice little speedup, and makes the code more readable IMHO anyway. On bigger clusters, the time to run initdb in all the segments would dominate, however.

**Comment by asimrp** [comment]
I love it!  Thanks!

**Comment by jimmyyih** [comment]
Looks good.  Let's get this in!

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Pull request closed without merging**
