### PR TITLE
Move gpdb union tests to union_gp.sql

### PR DESCRIPTION
**Pull request by hsyuan**
Put these tests into 'union_gp' rather than 'union' test. 'union' is from upstream, and minimize changes there to make diffing/merging easier.

### CODE REVIEW

**Comment by xinzweb** [comment]
LGTM

**Comment by hsyuan** [comment]
Pushed to https://github.com/greenplum-db/gpdb/commit/c2b0ffc5b3abb149a4bb65fc2293584fdb8b7529

**Comment by hlinnaka** [comment]
Can you also take out the "set optimizer=on" from the test, please? We run all regression tests with optimizer=on and optimizer=off in the buildfarm anyway, so forcing it on only reduces test coverage. Also, the test is now failing when you build without ORCA, as "set optimizer=on" gives an error.

**Comment by hsyuan** [comment]
Sorry about that, will remove it.

**Pull request closed without merging**
