### PR TITLE
Elide explicit motion if no motion above result relation

### PR DESCRIPTION
**Pull request by kainwen**
Delete or Update statement may add motions above result relation
to determine whether the tuple is to delete or update. For example,

```
-- t1 distributed by (b), t2 distributed by(a)
delete from t1 using t2 where t1.b = t2.a;
```

The above sql might add motion above t1 (the result relation) when creating the
t1 join t2 plan.

ExecDelete or ExecUpdate use ctid to find the tuple and ctid only make sense
in its original segment. So greenplum will add explicit redistributed motion to
send back each tuple and then do delete or update.

Previously, the condition to add explicit redistributed motion is that no motions in
the subplan of modify table. This can be improved: if no motion is added above the
result relations, then we could elide this motion.

------------------------------

I build a dev pipeline to check it. Current test cases have some case on update | delete with motions.

I will try to add more cases if needed (after the full dev pipeline finishes).

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by pengzhout** [comment]
Strange, cannot reproduce in my environment.

**Comment by pengzhout** [comment]
> Strange, cannot reproduce in my environment.

The example might be incorrect, understood what is the PR for?

**Comment by pengzhout** [comment]
Hi @kainwen do you think whether bellow EXPLICT motion can be removed or not?

```
drop table t1;
drop table t2;
drop table t3;
create table t1 (a int, b int) distributed by (b);
create table t2 (a int, b int) distributed by (a);
create table t3 (a int, b int) distributed by (b);

insert into t1 values (1, 1);
insert into t2 values (1, 1);
insert into t3 values (1, 1);

set allow_system_table_mods=true;
update pg_class set relpages = 10000 where relname='t2';
update pg_class set reltuples = 100000000 where relname='t2';
update pg_class set relpages = 100000000 where relname='t3';
update pg_class set reltuples = 100000 where relname='t3';
```
explain (costs off) delete from t1 using t2, t3 where t1.a = t2.a and t1.b = t3.b;
```
 Delete on t1
   ->  Explicit Redistribute Motion 3:3  (slice3; segments: 3)
         ->  Hash Join
               Hash Cond: (t3.b = t1.b)
               ->  Seq Scan on t3
               ->  Hash
                     ->  Redistribute Motion 3:3  (slice2; segments: 3)
                           Hash Key: t1.b 
                           ->  Hash Join
                                 Hash Cond: (t2.a = t1.a)
                                 ->  Seq Scan on t2
                                 ->  Hash
                                       ->  Redistribute Motion 3:3  (slice1; segments: 3)
                                             Hash Key: t1.a
                                             ->  Seq Scan on t1
 Optimizer: Postgres query optimizer
(16 rows)
```

I am curious why don't we compare the target locus with the subplan's locus, if they are equal, we can remove the EXPLICT motion. 

As the plan shows, redisributed on t1.b are equal to explict redistributed motion on t1.gp_segment_id.
```
                   ->  Redistribute Motion 3:3  (slice2; segments: 3)
                           Hash Key: t1.b 
is equal to:
                   -> Explicit Redistribute Motion 3:3  (slice3; segments: 3) with 


```

**Comment by hlinnaka** [comment]
I think you're onto something here, even though this needs a bit more work.

In a nutshell, we're trying to determine if there are any Motions between the explicit motion and the scan of the base relation. Another way to phrase that question: Is the Explicit Motion and the scan of the base relation in the same slice? As it turns out, we're already tracking that information in the Paths. There's a field,`Path->sameslice_relids` for exactly that! We can use that, to elide the Explicit Motion earlier, when we're creating the Paths, and avoid all this logic in createplan.c to elide it.

I wrote a prototype patch for that: https://github.com/hlinnaka/gpdb/tree/rm_motion_check-2. It seems to work, but I didn't run the full regression test suite on that, and it might need some new tests too. If that approach works, it will actually simplify things. Please take a look, and feel free to pick it up and finish it into a PR!

**Comment by kainwen** [comment]
> Hi @kainwen do you think whether bellow EXPLICT motion can be removed or not?
> 
> ```
> drop table t1;
> drop table t2;
> drop table t3;
> create table t1 (a int, b int) distributed by (b);
> create table t2 (a int, b int) distributed by (a);
> create table t3 (a int, b int) distributed by (b);
> 
> insert into t1 values (1, 1);
> insert into t2 values (1, 1);
> insert into t3 values (1, 1);
> 
> set allow_system_table_mods=true;
> update pg_class set relpages = 10000 where relname='t2';
> update pg_class set reltuples = 100000000 where relname='t2';
> update pg_class set relpages = 100000000 where relname='t3';
> update pg_class set reltuples = 100000 where relname='t3';
> ```
> 
> explain (costs off) delete from t1 using t2, t3 where t1.a = t2.a and t1.b = t3.b;
> 
> ```
>  Delete on t1
>    ->  Explicit Redistribute Motion 3:3  (slice3; segments: 3)
>          ->  Hash Join
>                Hash Cond: (t3.b = t1.b)
>                ->  Seq Scan on t3
>                ->  Hash
>                      ->  Redistribute Motion 3:3  (slice2; segments: 3)
>                            Hash Key: t1.b 
>                            ->  Hash Join
>                                  Hash Cond: (t2.a = t1.a)
>                                  ->  Seq Scan on t2
>                                  ->  Hash
>                                        ->  Redistribute Motion 3:3  (slice1; segments: 3)
>                                              Hash Key: t1.a
>                                              ->  Seq Scan on t1
>  Optimizer: Postgres query optimizer
> (16 rows)
> ```
> 
> I am curious why don't we compare the target locus with the subplan's locus, if they are equal, we can remove the EXPLICT motion.
> 
> As the plan shows, redisributed on t1.b are equal to explict redistributed motion on t1.gp_segment_id.
> 
> ```
>                    ->  Redistribute Motion 3:3  (slice2; segments: 3)
>                            Hash Key: t1.b 
> is equal to:
>                    -> Explicit Redistribute Motion 3:3  (slice3; segments: 3) with 
> ```

```sql
-- t1, t2 is randomly distributed
delete from t1 using t2 where t2.c = t1.c;
```

If we choose to broadcast t1, and join with t2, then the join's locus is strewn and the target locus is also strewn. For this case we cannot simply check locus equility.

But if we choose to broadcast t2, no motion above t1, then things seems good we can remove the motion.

For hash distributed table, I think your conclusion is right and can be proved mathematically.

**Comment by kainwen** [comment]
> I think you're onto something here, even though this needs a bit more work.
> 
> In a nutshell, we're trying to determine if there are any Motions between the explicit motion and the scan of the base relation. Another way to phrase that question: Is the Explicit Motion and the scan of the base relation in the same slice? As it turns out, we're already tracking that information in the Paths. There's a field,`Path->sameslice_relids` for exactly that! We can use that, to elide the Explicit Motion earlier, when we're creating the Paths, and avoid all this logic in createplan.c to elide it.
> 
> I wrote a prototype patch for that: [hlinnaka@82a3e29](https://github.com/hlinnaka/gpdb/commit/82a3e2942219df9235205eb66c2e4ac13bb20c8a). It seems to work, but I didn't run the full regression test suite on that, and it might need some new tests too. If that approach works, it will actually simplify things. Please take a look, and feel free to pick it up and finish it into a PR!

Thanks @hlinnaka , your code is much simpler and clearer.

After looking into @pengzhout 's comments,  https://github.com/greenplum-db/gpdb/pull/9171#issuecomment-561990521, combining your idea with his idea, 
I come to an algorithm:

1. use @hlinnaka 's patch to remove this motion at early stage
2. if we have motions above result relations, we may even wonder, whether they finally send back the tuples:
    a. If the targetlocus is strewn(result relation is randomly distributed), then we have to add explicit motion
    b. if targetlocus is equal to the subplan's locus, then we does not need such motion
    c. otherwise, we have to add the motion.

Does above conclusion make sense for you? @pengzhout @hlinnaka 

Thanks.

**Comment by kainwen** [comment]
Open a new pr: https://github.com/greenplum-db/gpdb/pull/9183

Close this. Thanks for the idea!

**Pull request closed without merging**
