### PR TITLE
Re-add upstream versioning variables

### PR DESCRIPTION
**Pull request by danielgustafsson**
In commit 0de5fc631364045f59ecb7a4b40dd453995 I renamed the upstream
version variables MAJORVERSION and VERSION to PG_ counterparts, to
clarify issues around Greenplum/PostgreSQL versioning at the time.
This has however been shown to cause issues when compiling extensions
which interrogate these variables during building.

Reported in https://github.com/greenplum-db/gpdb/issues/7916

### CODE REVIEW

**Comment by hlinnaka** [comment]
Thanks! Maybe add a comment explaining why we have both [MAJOR]VERSION and PG_[MAJOR]VERSION?

**Comment by danielgustafsson** [comment]
> On 13 Jun 2019, at 12:24, Heikki Linnakangas <notifications@github.com> wrote:
> 
> Thanks! Maybe add a comment explaining why we have both [MAJOR]VERSION and PG_[MAJOR]VERSION?

Good point, will include that when I push.

**Comment by danielgustafsson** [comment]
Force-pushed a rebase to try and get the CI to pick it up

**Comment by danielgustafsson** [comment]
I am going to consider the pipeline error unrelated and push this tomorrow

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review!

**Comment by gaos1** [comment]
@danielgustafsson is it possible to backport the fix to 6 so that the issue #7916 can be avoided for 6 users?

**Pull request closed without merging**
