### PR TITLE
New Greenplum Server Master CI build.

### PR DESCRIPTION
**Pull request by berlin-ab**
I'd like to propose a new master CI build for the `greenplum-db/gpdb` repository.

The goal is to keep things simple.  It runs `installcheck-world` against the latest master and reports pass or fail. 

It can be extended later to hook into a delivery pipeline of downstream packaging and release pipelines, but it is not intended for those purposes now.

This can also be a public pipeline, as it does not contain any credentials and relies only on public Docker images.

### CODE REVIEW

**Comment by Eulerizeit** [comment]
What if any testing do we need that doesn't fall inside this pipeline?

**Comment by danielgustafsson** [comment]
Is this intended to be a new master pipeline, replace the existing master pipeline, or none of the above?

**Comment by berlin-ab** [comment]
This commit leaves the existing release pipeline untouched.

**Comment by berlin-ab** [comment]
> What if any testing do we need that doesn't fall inside this pipeline?
> 
> Also, are there any default configure flags we want to explicitly disable?

I think we can start to trim down the pipeline configure flags once we have this up and running.

**Pull request merged**
