### PR TITLE
Modify guc gp_segment_connect_timeout to align with value 180s

### PR DESCRIPTION
**Pull request by ginobiliwang**
The guc gp_segment_connect_timeout's default value is 180s which is not aligned with 600s as in document.  

```
[gpadmin@smdw ~]$ gpconfig -s gp_segment_connect_timeout
Values on all segments are consistent
GUC          : gp_segment_connect_timeout
Master  value: 10min
Segment value: 10min
[gpadmin@smdw ~]$
[gpadmin@smdw ~]$
[gpadmin@smdw ~]$ gpconfig -r gp_segment_connect_timeout
20190826:03:08:04:025915 gpconfig:smdw:gpadmin-[INFO]:-completed successfully with parameters '-r gp_segment_connect_timeout'
[gpadmin@smdw ~]$
[gpadmin@smdw ~]$ gpstop -u
20190826:03:08:15:025976 gpstop:smdw:gpadmin-[INFO]:-Starting gpstop with args: -u
20190826:03:08:15:025976 gpstop:smdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20190826:03:08:15:025976 gpstop:smdw:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20190826:03:08:15:025976 gpstop:smdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20190826:03:08:15:025976 gpstop:smdw:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.0.0-beta.6 build commit:96e65e566023a5f84d7846f51174474188a63755'
20190826:03:08:15:025976 gpstop:smdw:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@smdw ~]$
[gpadmin@smdw ~]$
[gpadmin@smdw ~]$ gpconfig -s gp_segment_connect_timeout
Values on all segments are consistent
GUC          : gp_segment_connect_timeout
Master  value: 3min
Segment value: 3min
[gpadmin@smdw ~]$
```

This PR has made the default and init value aligned with value in document and changed place to declare this variable.

### CODE REVIEW

**Comment by paul-guo-** [comment]
I feel like we should modify document instead given we did not seem to hear any complaint about the guc value?

**Comment by ginobiliwang** [comment]
Hi @paul-guo- , i have got your point.  
Actually, if customer does not reset the value for default, he would use the initial value in postgresql.conf.sample, which is 600s.

Another thing is, the place where variable "gp_segment_connect_timeout"  has been declared is not appropriate, i have changed it from "cdbconn.c" to "cdbvars.c".

Anyway, if you consider 180 as empirical constant,  it is Ok for me to change documentation for value "180".

**Comment by paul-guo-** [comment]
It looks like 180s is enough for most cases. We can just modify the document.
I agree with your change in postgresql.conf.sample, and the variable definition place but better put the comment of the variable at the end, following the convention.

**Comment by ginobiliwang** [comment]
ok, cool. Let me shoot another commit for the above.

**Comment by paul-guo-** [comment]
Thanks. @dyozie for the document part.

**Comment by ginobiliwang** [comment]
@dyozie  & @paul-guo- , can you help review the latest commit to see if it is good to merge ?

**Pull request merged**
