### PR TITLE
Fixes readme confusion over steps for mac vs linux

### PR DESCRIPTION
**Pull request by l-wang**
Signed-off-by: John Gaskin <johntgaskin@gmail.com>
Signed-off-by: Todd Sedano <tsedano@pivotal.io>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@l-wang Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2767)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2767) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by hsyuan** [comment]
@l-wang Please sign the CLA.

**Comment by pivotal-issuemaster** [comment]
@l-wang Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2767)!

**Comment by andreasscherbaum** [comment]
+1

**Pull request merged**
