### PR TITLE
Fix isolation2 test for ic_proxy env

### PR DESCRIPTION
**Pull request by divyeshddv**
Make recoverseg use udpifc to avoid hangs in ic_proxy envs due to change in dbid in recoverseg_from_file

Remove icproxy_setup.bash as it is no longer needed.

Co-authored-by: Soumyadeep Chakraborty <soumyadeepc@vmware.com>

### CODE REVIEW

**Comment by divyeshddv** [comment]
Dev pipelines are green: 
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-ic_proxy_test_fix_3
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-ic_proxy_test_fix_3_without_asserts

**Review by soumyadeep2007 — APPROVED** [review]
LGTM!

**Comment by soumyadeep2007** [comment]
> It introduced another failure: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE/jobs/gprecoverseg_rhel8/builds/380

This failure is unrelated and is possibly a known flake. Also, the changes in this PR did not touch gprecoverseg

**Comment by divyeshddv** [comment]
Looks like an unrelated recurring flake. Can we rerun the job?

**Comment by divyeshddv** [comment]
> It does't seem like a flakey test, it has been failed 3 times: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE/jobs/gpmovemirrors_ubuntu18/builds/1624 https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE/jobs/gpmovemirrors_ubuntu18/builds/1623 https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE/jobs/gpmovemirrors_ubuntu18/builds/1622

These are flakes and are unrelated to the PR. Maybe we can bring these flakes up to the CM team 
if you look at 1623, concourse cluster test failed while demo cluster passed.
for 1622 and 1624, concourse cluster tests worked fine while demo cluster tests failed

**Comment by gpopt** [comment]
> These are flakes and are unrelated to the PR. Maybe we can bring these flakes up to the CM team

Sounds good.

**Comment by gpopt** [comment]
@ashwinstar @khuddlefish FYI, the flakey test might need CM team to take a look.

**Pull request merged**
