### PR TITLE
Implement direct dispatch for IS NULL.

### PR DESCRIPTION
**Pull request by hlinnaka**
Perhaps not super interesting, but it's straightforward to implement, and
ORCA was already doing it.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Pushed, thanks for the review!

**Comment by ivannovick** [comment]
That's actually a cool user facing feature if i understand correctly.   

How can we describe to users which queries will fall in this category and be covered under direct dispatch?  I am assuming not all IS NULL queries can be covered without dispatching to all segments?

@dyozie @mkiyama

**Comment by hlinnaka** [comment]
On 27/12/2018 01:57, Ivan Novick wrote:
> That's actually a cool user facing feature if i understand correctly.
> 
> How can we describe to users which queries will fall in this category 
> and be covered under direct dispatch? I am assuming not all IS NULL 
> queries can be covered without dispatching to all segments?

In a nutshell, a query with "x IS NULL" is now direct dispatched under 
the same circumstances as "x = <constant>".

- Heikki

**Comment by ivannovick** [comment]
That sounds good, cheers

**Pull request merged**
