### PR TITLE
Make the macro of FAULT_INJECTOR configurable

### PR DESCRIPTION
**Pull request by gfphoenix78**
Definition FAULT_INJECTOR is hardcoded in a header(pg_config_manual.h) file.
Fault injector is useful, but it may introduce some issues in production
stage, like runtime cost, security problems. It's better to enable this
feature in development and disable it in release.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by gfphoenix78** [comment]
> Considering the other developer options in autoconf, it's a bit odd to have this enabled by default when assertions and debugging are off by default.
Yes, assertion is disabled by default, but FAULT_INJECTOR is defined to 1 by default. Besides this PR, I plan to open another PR to disable fault-injector in release pipeline.

**Comment by danielgustafsson** [comment]
> Yes, assertion is disabled by default, but FAULT_INJECTOR is defined to 1 by default. Besides this PR, I plan to open another PR to disable fault-injector in release pipeline.

I don't think we need to concern ourselves with what we currently have, but rather what we want to have longer term. My preference is to mimic the behavior of other developer options but that's a strong opinion very loosely held.

**Comment by asimrp** [comment]
I agree with @danielgustafsson, `--enable-faultinjector` is consistent with other developer options such as `--enable-cassert` and `--enable-debug`.  Can we please flip the change to disable by default @gfphoenix78?  Another advantage by keeping faultinjector disabled by default is no change is needed to release pipeline.  Only the CI pipelines need to be modified to enable faultinjector and that can a commit in this PR.

**Comment by gfphoenix78** [comment]
Sounds good!

**Comment by ashwinstar** [comment]
@gfphoenix78 what's remaining to get this to finish line?

**Comment by gfphoenix78** [comment]
> @gfphoenix78 what's remaining to get this to finish line?

I'm waiting for this PR(https://github.com/greenplum-db/gpdb/pull/10825) to be merged.

**Comment by ashwinstar** [comment]
> > @gfphoenix78 what's remaining to get this to finish line?
> 
> I'm waiting for this PR(#10825) to be merged.

What’s the connection or dependency?

**Comment by gfphoenix78** [comment]
> > > @gfphoenix78 what's remaining to get this to finish line?
> > 
> > 
> > I'm waiting for this PR(#10825) to be merged.
> 
> What’s the connection or dependency?

Reordering of the test cases breaks some failures. In master branch, I observed additional(nearly 10) failures in the prod pipeline after merging the patch to master, even if the pr pipeline was all green. I'm not sure about the root cause, but willing to wait for the PR(#10825) to catch the errors by an inconsistent system.

**Comment by ashwinstar** [comment]
Merged the cluster validation check at part of https://github.com/greenplum-db/gpdb/pull/11055. I think this PR should be unblocked now and taken to completion when possible as seems we are almost standing on finish line for this.

**Comment by asimrp** [comment]
I've picked this one up.  The method used in current patch to identify tests using fault injectors makes sense.  However, the tinkering of schedule files using `sed` to exclude them is not reliable.  My preference is to leverage the `--exclude-tests` feature instead.  If fault injectors are not enabled, set `--exclude-tests` to all tests that use faults.  Alternatively, introduce a new option `--exclude-file` to specify one test per line that need to be excluded when running a schedule.

**Comment by asimrp** [comment]
Closing in favor of #11112

**Pull request closed without merging**
