### PR TITLE
Test gp-orafunk should use orafunc.sql in the install directory

### PR DESCRIPTION
**Pull request by xiong-gang**
Signed-off-by: Adam Lee <ali@pivotal.io>

### CODE REVIEW

**Comment by xiong-gang** [comment]
@jimmyyih Could you help review it?

**Comment by hsyuan** [comment]
+1

**Comment by kuien** [comment]
+1 better than re-install it again.

**Comment by danielgustafsson** [comment]
Being able to run tests *before* installing is generally what we would like to move towards, any reason to require installation?

**Comment by adam8157** [comment]
@danielgustafsson *before* installing? What is being tested then?

That dependency target was added by us about two days ago, which requires compiling than only binary and source, is inconvenient for CI, so we think it's better to use installed files.

**Comment by jimmyyih** [comment]
+1 from me although I don't know if the path given is good or not.  Running make in gpAux vs. running make in top-level directory can give different install paths but extensions might be different.

**Comment by danielgustafsson** [comment]
@adam8157 the binaries are tested in the compiled locations, or temporary paths during testing, before being installed. Compare `make check` in upstream which runs all the tests before installation to ensure that the installed binaries work as expected.

**Comment by adam8157** [comment]
On Mon, Oct 24, 2016 at 11:56:24PM -0700, Daniel Gustafsson wrote:
> [1]@adam8157 the binaries are tested in the compiled locations, or temporary
> paths during testing, before being installed. Compare make check in upstream
> which runs all the tests before installation to ensure that the installed
> binaries work as expected.

Thanks, I see. This patch should be OK since it uses binary directory
actually.

**Pull request merged**
