### PR TITLE
    Vagrant CentOs VM with GPORCA support [#114923155]

### PR DESCRIPTION
**Pull request by xinzweb**
- Change the current vagrant to clone the GPDB inside and run it, to avoid confusion between host and guest environment.
- Change the VM size to 8GB and 4 cpus to better compile and test performance
- At the end of the vagrant the GPDB will up and running with gpdemo (3 seg and 3 mirrors)
- use `vagrant up gpdb` to build GPDB with GPORCA using option --enable-orca
- use `vagrant up gpdb-without-gporca` to build GPDB without GPORCA

### CODE REVIEW

**Comment by xinzweb** [comment]
@oarap @d @jfrank-pivotal @pateljm

**Comment by hsyuan** [comment]
+1

**Comment by davecramer** [comment]
While I see nothing technically wrong with this PR, I think we have to step back a bit. What are the purposes of these vagrant files ?
Why do you not want to share the filesystem ? 
I'm also concerned a bit about using 4 CPU's. That might be more than some folks want to give to the vagrant, again why ?

**Comment by 0x0FFF** [comment]
Regarding the amount of RAM and CPU - this should be adjusted locally, 8GB and 4 cores is not the thing that would fit all
Regarding making "git clone" inside of vagrant script - I'm against it, at least it should be a non-default option
Plus I don't like cross-repo dependencies like cloning Orca and GPOS from the script in GPDB repo. Maybe we should follow Postgres steps and not have vagrant with its scripting in main repo, but rather create a separate one for it?

**Comment by xinzweb** [comment]
@davecramer 
- First, there is no reason to have separate cloning for host vs. guest on Centos. However, as an OSX developer running Vagrant, people often got confused on the mixed files of host and guest. Hence, this fix totally separates the host from guest. It's just one extra minute to sync the new clone of GPDB inside the Vagrant VM.

- Second, the purpose of this Vagrant setup is to have GPDB with GPORCA setup in 10 minutes.  Currently, some developers spend days trying to figure out all of the proper dependencies and get everything to compile and run in their environment. Vagrant provides consistent developing environment for people who want to contribute to the code base without having to battle with all of the setup issues. Once they do `vagrant up`, all they have to do is `vagrant ssh` to the box and start coding (and contribute back to community, rather than spending their energy trying to figure out why it doesn't work on their systems).

- The CPU/RAM allocation in this Vagrantfile works very well to get a speed-up for the compilation as well as running all the ICG tests inside the guest system. Developers can always lower those settings in their own repo if their system can't handle the performance requirements of hosting it.

@0x0FFF 
- 8GB and 4CPU are for the developer wants to run those ICG tests on the guest system. They can definitely try to scale down to a smaller version. Usually with smaller VM, I see a lot more errors like `ERROR:  failed to acquire resources on one or more segments`. The size here is targeted to reach a reasonably stable VM configuration, so that people won't be wondering about why this ERROR happened. Again, we are talking about a CLUSTER here, which is way bigger than a single PostgreSql instance and thus needs more computing resources.

- It's understandable the basic Vagrant workflow is to share the repository with the host so that we don't have to re-sync and people can use their favorite development environment on the host. However, as I mentioned before, this caused more trouble if people want to build both on their native environment and on the host environment (maybe they shouldn't do that), especially when the host and guest are very different (like a OSX vs. CentOs, or any Win32 system).

- It's a good question of whether to separate it out of the GPDB repo especially for the GPORCA one. However, the idea here is to have people easily bring up a GPDB developing environment with GPORCA. That's crucial for both the GPDB and GPORCA communities. The size impact on the GPDB repo is very small.  Now, the Vagrant VM will just include more dependencies on GPORCA. It's similar to `yum install`, but at this moment, GPORCA doesn't have a  packaged release yet (but that's coming soon).

- As whether we should separate the Vagrant from the main repo, I am against it.  If you separate it, then it won't be maintained consistently with the GPDB repo, and eventually, it will be out of date, and harder for people to find etc. For example, Apache HAWQ has separate repo for dockers images, which is hard to discover (through links of readme to wiki to private repo etc.) and not guaranteed to be compatible with the head of the main repo, and I want GPDB to have a much smoother story for developer boostrapping using a Vagrant configuration that's guaranteed to be consistent with the code.

Hope those clarified the intent behind this PR. Thanks.

**Comment by jfrank-pivotal** [comment]
+1

I'm very happy to see this after all the issues I've witnessed with getting developers up and running on such varied environments.  I'm not concerned about needy the RAM/CPU specs; anyone who's choosing to use this to build and run a GPDB cluster is probably going to have the technical wherewithal to update the Vagrantfile to reduce the system load if it becomes necessary.

I see why the cross-repo dependencies are a cause for concern, but I think it's more important that the Vagrantfile stays versioned with the code that it most depends on.

**Comment by hlinnaka** [comment]
On 18/03/16 20:11, Xin Zhang wrote:
> - Second, the purpose of this Vagrant setup is to have GPDB with
> GPORCA setup in 10 minutes.  Currently, some developers spend days
> trying to figure out all of the proper dependencies and get
> everything to compile and run in their environment. Vagrant provides
> consistent developing environment for people who want to contribute
> to the code base without having to battle with all of the setup
> issues. Once they do `vagrant up`, all they have to do is `vagrant
> ssh` to the box and start coding (and contribute back to community,
> rather than spending their energy trying to figure out why it doesn't
> work on their systems).

I have nothing against adding Vagrant files if people find them useful, 
but as a solution to the problem that GPDB+ORCA is difficult to build, 
it's just a bandaid. We need to make building that combination simpler.

- Heikki

**Comment by 0x0FFF** [comment]
@xinzweb, @hlinnaka 
I agree with Heiki, and I'm still against this patch. It is good for testing, to have a GPDB repo cloned inside of VM. But what about developers? I'm developing code in my private repo and open pull requests to GPDB from there. These Vagrant scripts would clone the main GPDB repo into the VM and build it. It means that for development purposes I have to change the scripts to checkout my own repo. On top of this, as a developer working with code, having a repo inside of Vagrant VM means I have to either use vim/emacs (as by default GUI is not installed in CentOS VM), or develop locally and commit my changes to remote repository before running the tests in Vagrant environment (where I would have to make a pull), which is ridiculous.
In my opinion this bandaid make things worse

**Comment by danielgustafsson** [comment]
I agree with @0x0FFF that cloning inside the VM breaks not only how I do development but also the disposable VM aspect of Vagrant.

**Comment by xinzweb** [comment]
@danielgustafsson and @0x0FFF thanks for the comment. 

If the only concern is to have the host share the folder with the Vagrant VM, I have no issue to blend it in.

@hlinnaka, yes the current GPORCA doesn't have a release story yet, hence, this is a bandaid to easily create a canonical environment to build GPDB with GPORCA.

Let me work on another patch to have the Vagrant VM share the file with host. Thanks.

**Comment by 0x0FFF** [comment]
@xinzweb the idea here is to share GPDB code with the host system, to be able to make changes in Mac and build inside of Vagrant. It is not that important for ORCA, but in my understanding ORCA should be shared too as if you are debugging an issue with ORCA you will most likely want to make some changes to its code, and doing it inside the non-shared VM directory is not a good option

**Pull request merged**
