### PR TITLE
Reduce memory consumption of text_position() functions.

### PR DESCRIPTION
**Pull request by hlinnaka**
Instead of allocating one huge buffer to hold the 'haystack' input,
allocate a smaller buffer, and convert the input in smaller chunks,
filling the small buffer whenever it fills up.

Reducing memory consumption is always nice, but in particular, this allows
using these functions with inputs larger than 1/4 GB, when UTF-8 or other
multibyte encoding is used.

This affects all the functions that use the internal text_position
functions: string_to_array(text, text), replace(text, text), and strpos().

GPDB 5 used to have a more hacked version of the text_position()
functions, for the same reason, but those hacks got reverted during the
PostgreSQL 8.4 - 9.2 merges. Things brings back the same user-visible
behavior, in a less invasive way that will hopefully survive future
merges better. (Also, the old implementation only had special handling
for string_to_array(); the other functions still failed with large inputs.)

### CODE REVIEW

**Comment by Eulerizeit** [comment]
@hlinnaka what is left to get this PR in? 

Has this / should this be proposed upstream?

**Comment by Eulerizeit** [comment]
@hlinnaka Can you rebase this and get it committed? Is there anything we need to do to help? 

From the other PR Jimmy linked the following discussion. I'm not sure if it is relevant. 
https://groups.google.com/a/greenplum.org/forum/#!msg/gpdb-dev/Fiv2a0FJ1rE/p5LwT7PyCAAJ

**Comment by d** [comment]
David (@dgkimura ) and I glanced through the test, and it doesn't seem it would break even without this patch.

The code looks correct though.

**Comment by hlinnaka** [comment]
For the upstream, I think we should do a somewhat different patch. This patch is "optimized" to minimize the changes vs. upstream, which tends to help with the merges. For the upstream, we should integrate the logic into the `text_position_next` function. And for upstream, I'd like to do some performance testing, to check if there some performance impact. Just dealing with large arrays might not be a good enough reason to do this in the upstream, especially if there's a performance loss, but if this happens to make it faster, too, then that'd be good.

I worked on this a while ago, and wrote a patch that I think would be good for upstream (after some cleanup of comments and debugging code). But before I got around to performance testing it, I got distracted by something shiny. Here: https://github.com/hlinnaka/postgres/tree/reduce-text_position-memory-usage. It's on my long todo list to finish that up and post to pgsql-hackers. If someone else wants to pick that up before I get around to it, feel free.

**Comment by Eulerizeit** [comment]
@hlinnaka I think this made it into the upstream. Can we grab what we need to grab and get this committed please?

**Comment by hlinnaka** [comment]
I committed a patch to upstream now, to fix this. Opened PR https://github.com/greenplum-db/gpdb/pull/6817 with the upstream fix. Closing this PR, in favor of that.

**Pull request closed without merging**
