### PR TITLE
Remove slow CTAS from gp_create_table to speed up test

### PR DESCRIPTION
**Pull request by danielgustafsson**
The `gp_create_table` suite tests that the maximum number of columns can be specified as a distribution clause (well, it really tests that CREATE TABLE allows the maximum number of columns since that check applies first), and then tests to CTAS from the resulting table. There is no reason to believe that there is a difference between CTAS with 1600 columns and CTAS with fewer columns (unless I'm missing something). Remove this case to speed up the test significantly and also adjust the DROP TABLE clauses to match reality. This shaves off ~ 66% of the test suite time for me.

### CODE REVIEW

**Comment by hlinnaka** [comment]
How much is 66% in absolute terms?

**Comment by danielgustafsson** [comment]
> On 30 Mar 2017, at 10:30, Heikki Linnakangas <notifications@github.com> wrote:
> 
> How much is 66% in absolute terms?

It went from ~21 seconds down to ~7 seconds for me.

**Comment by danielgustafsson** [comment]
Red pipeline run due to network errors..

**Comment by danielgustafsson** [comment]
Pushed to master, thanks!

**Pull request closed without merging**
