### PR TITLE
Fix fts_recovery_in_progress test failure because pg_rewind runs befo…

### PR DESCRIPTION
**Pull request by paul-guo-**
…re timeline id bumping after mirror promotion.

This issue was actually seen on PG upstream and was fixed by Heikki in
pg_rewind test case. In gpdb, we are much more automatically using pg_rewind
via gprecoverseg, so we'd better fix that in our own code (gprecoverseg or
pg_rewind). On gpdb, after mirror promotion via fts, the time is possibly not
short before a correct timeline id is flushed into the pg_control file. For
such case, if we do incremental recovery via gprecoverseg, it will succeed but
the target node (new mirror) is still not functional.

commit 484a848a73fc5a76c16bc73626b290154b6a57b4
Author: Heikki Linnakangas <heikki.linnakangas@iki.fi>
Date:   Thu Apr 30 21:57:18 2015 -0700

    Fix pg_rewind regression failure after "fast promotion"

    pg_rewind looks at the control file to determine the server's timeline. If
    the standby performs a "fast promotion", the timeline ID in the control
    file is not updated until the next checkpoint. The startup process requests
    a checkpoint immediately after promotion, so this is unlikely to be an
    issue in the real world, but the regression suite ran pg_rewind so quickly
    after promotion that the checkpoint had not yet completed.

    Reported by Stephen Frost

### CODE REVIEW

**Comment by ashwinstar** [comment]
I think we can close this and not commit. Don't think we should see the issue either as promotion and someone running gprecoverseg will take time to at least complete writing the pg_controlfile.

**Comment by paul-guo-** [comment]
Thanks. I'm almost 100% able to reproduce this issue in a local centos6 dev environment. Just run
```
./pg_regress --init-file=./init_file fts_recovery_in_progress
```
in a brand new demo-cluster.

pg_controlfile could be updated in a lot of code path, but not each code updates timeline id. I traced the code path in one failed cases, the timeline id is updated at the end of  StartupXLOG() which calls `RequestCheckpoint(CHECKPOINT_FORCE);` to send a signal to request checkpoint and thus the final checkpoint could be late during testing.

**Comment by ashwinstar** [comment]
>> pg_controlfile could be updated in a lot of code path, but not each code updates timeline id. I traced the code path in one failed cases, the timeline id is updated at the end of StartupXLOG() which calls RequestCheckpoint(CHECKPOINT_FORCE); to send a signal to request checkpoint and thus the final checkpoint could be late during testing.

Okay, so its mostly to do with fast promotion. Otherwise we would have called `RequestCheckpoint()` with `CHECKPOINT_WAIT` from `StartupXLOG()`.

I generally wish to keep utilities very light weight as far as possible and not carry any such inteligent code or points which can fail and confuse. It's not clear what error pops-up if this condition is hit during `pg_rewind`. Is it possible for `pg_rewind` to retry on that error? If not go ahead to commit the patch.

**Comment by paul-guo-** [comment]
For such case, pg_rewind will soon quit without error, reporting "no rewind is needed" since source and target have same timeline id at that time, also "gpreverseg -a" will succeed but actually the cluster is still broken. I'm not sure whether running "gpreverseg -a" again could fix the cluster (I could try later) but in any case this will confuse users.

**Comment by paul-guo-** [comment]
Just had a quick try. It still fails (cluster is not recovered) after running "gprecoverseg -a" after "successful" "gprecoverseg -a" (no rewind is needed but previous primary fails to start). "gprecoverseg -aF" will succeed.

**Comment by ashwinstar** [comment]
On Wed, Dec 26, 2018 at 7:56 PM Paul Guo <notifications@github.com> wrote:

> Just had a quick try. It still fails (cluster is not recovered) after
> running "gprecoverseg -a" after "successful" "gprecoverseg -a" (no rewind
> is needed but previous primary fails to start). "gprecoverseg -aF" will
> succeed.
>
Sorry, I am having difficulty understanding this. What is the failure and
why for the second run of gprecoverseg, please can you elaborate on that ?

**Comment by paul-guo-** [comment]
There are two gprecoverseg calls in `fts_recovery_in_progress.sql`. First one is "gprecoverseg -av" and later one is "gprecoverseg -arv". The test fails due to the first one - this is what the patch is trying to fix. Let's just talk about the first gprecoverseg call. What I did is to rerun "recoverseg -av" after "gprecoverseg -av" fails in the test case, hoping to succeed in the 2nd try, but until I manually removed recovery.conf from the directory of the old primary, rerunning "recoverseg -a" would not succeed. This is definitely not convenient for users. That means if users hit the issue ("gprecoverseg -a" reports a false positive), they need some manual work without this patch.

**Comment by ashwinstar** [comment]
Thanks for the explanation @paul-guo-. Seems still mentions the symptom though and not full cause for the failure. Why the presence of `recovery.conf` file cause the failure and absence makes it go though.
Asking questions mostly to really get to bottom of issue in general (instead of point fixing just this case) to know what other conditions can lead us to same state where rerunning gprecoverseg will not work.

**Comment by paul-guo-** [comment]
@ashwinstar 

That failure was easily rootcaused by checking the gprecoverseg log and pg_logs. gprecoverseg reports no rewind is done because there is no timeline id difference between target (down primary) and source (running old mirror) and pg_rewind writes a recover.conf for the target, but apparently, soon the source increases its timeline id by 1 and thus the recovery is incomplete.

**Comment by paul-guo-** [comment]
Running the 2nd 'recoverseg -av' generates a fatal message on old primary. This does not seem to be expected but this is a separate issue. I'll look at this later.

```
2019-01-03 11:30:40.299531 CST,,,p6719,th269080512,,,,0,,,seg0,,,,,"FATAL","XX000","requested timeline 6 is not a child of this server's history (xlog.c:6760)","Latest checkpoint is at 0/C214C38 on timeline 5, but in the history of the requested timeline, the server forked off from that timeline at 0/C214C38.","Process 6719 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.",,,,,0,,"xlog.c",6760,"Stack trace:
1    0xadc40f postgres errstart (elog.c:557)
2    0x557018 postgres StartupXLOG (xlog.c:6752)
3    0x8df627 postgres StartupProcessMain (startup.c:248)
4    0x5adbea postgres AuxiliaryProcessMain (bootstrap.c:434)
5    0x8de694 postgres <symbol not found> (postmaster.c:6040)
6    0x8d85ed postgres PostmasterMain (postmaster.c:1536)
7    0x7d33e3 postgres <symbol not found> (main.c:264)
8    0x3397e1ed5d libc.so.6 __libc_start_main + 0xfd
9    0x48f339 postgres <symbol not found> + 0x48f339
"
```

To answer another question from @ashwinstar, after removing recovery.conf,  pg_rewind is retrigged by gpactiveseg (See python code SegmentRewind). I'm wondering whether we want a parameter to force pg_rewind for out-of-sync mirror/primary pair even there exists a recovery.conf in case we encounter similar bugs in production.

**Comment by paul-guo-** [comment]
"gprecoverseg -a" will skip pg_rewind if there exist recovery.conf on the down node. This code was added when Jimmy and I added the support of incremental recovery using pg_rewind.

```
         rewind_cmd = '[ -f %s/recovery.conf ] || PGOPTIONS="-c gp_session_role=utility" $GPHOME/bin/pg_rewind --write-recovery-conf --source-server="%s" --target-pgdata=%s' % (target_datadir, source_server, target_datadir)
```
This is actually reasonable, but I'm wondering we should also force to call pg_rewind in any case after removing recovery.conf to give a chance of 2nd try in case of previous case I mentioned, this of course will fix the previous case but when I tried that for another scenario (mirror down so no need of pg_rewind), but I saw gprecoverseg failure with pg_log:

```
2019-01-04 18:30:49.637951 CST,,,p30940,th664733632,,,,0,,,seg0,,,,,"LOG","00000","invalid record length at 0/C023AD8",,,,,,,0,,"xlog.c",4271,
```

**Comment by ashwinstar** [comment]
Thanks @paul-guo- for all the investigation on the issue. :+1: for merging this in which I will go ahead and do now.

**Pull request merged**
