### PR TITLE
Remove unused "ltrace" code.

### PR DESCRIPTION
**Pull request by hlinnaka**
Although I'm not too familiar with SystemTap, I'm pretty sure that recent
versions can do user space tracing better. I don't think anyone is using
these hacks anymore, so remove them.

### CODE REVIEW

**Comment by tvesely** [comment]
I have used this several times to assist with troubleshooting/debugging, and there isn't really a replacement for these tools should we remove them. 

Is the intention to remove this implementation of ltrace and then add an upstream implementation later?

**Comment by hlinnaka** [comment]
On 09/12/2017 09:49 PM, Taylor Vesely wrote:
> I have used this several times to assist with
> troubleshooting/debugging, and there isn't really a replacement for
> these tools should we remove them.

Ok. Do you compile specifically with ENABLE_LTRACE, and set the 
gp_ltrace_flag GUC? Or do you just use ltrace in general?

> Is the intention to remove this implementation of ltrace and then add
> an upstream implementation later?

There is nothing similar coming up from the upstream later, AFAIK. I 
think the reason is that ltrace doesn't need help from the code anymore, 
you can use it on an unmodified binary. Although I must admit I've never 
used it myself.

- Heikki

**Comment by tvesely** [comment]
It sounds like we can use the dtrace tracepoints in Linux, so I have no objection to removing this code.

+1

**Comment by hlinnaka** [comment]
Ok, pushed, thanks!

**Pull request merged**
