### PR TITLE
Revert "Fix data lost due to incorrect sharedsnapshot."

### PR DESCRIPTION
**Pull request by adam8157**
This reverts commit 1beead0c0f49d3456a810a33780b1fb51e0576c9, it
reserves too much shared memory.

```
>>> p SharedSnapshotShmemSize()
$2 = 422752408
```

### CODE REVIEW

**Comment by adam8157** [comment]
Reference:
https://github.com/greenplum-db/gpdb/issues/17275
https://github.com/greenplum-db/gpdb/pull/17327

**Comment by adam8157** [comment]
Instead of pre-allocating the possible max size array in shared memory, we should perhaps let the process pass an actual size array of XIPs and sub-XIPs (via DSM?).

**Comment by kainwen** [comment]
> This reverts commit [1beead0](https://github.com/greenplum-db/gpdb/commit/1beead0c0f49d3456a810a33780b1fb51e0576c9), it reserves too much shared memory.
> 
> ```
> >>> p SharedSnapshotShmemSize()
> $2 = 422752408
> ```

Without the patch, what is the value?

**Review by kainwen — APPROVED** [review]

**Comment by SmartKeyerror** [comment]
Why did we need to revert it? Just because it pre-allocates such enormous memory? I don't think it's reasonable to
just revert the patch simply, cause `GetMaxSnapshotSubxidCount()` is not only used in this patch, when we get snapshot,
we will allocate such memory if `snapshot->subxip` is NULL:

```
if (snapshot->subxip == NULL)
{
snapshot->subxip = (TransactionId *)
	malloc(GetMaxSnapshotSubxidCount() * sizeof(TransactionId));
if (snapshot->subxip == NULL)
	ereport(ERROR,
			(errcode(ERRCODE_OUT_OF_MEMORY),
				errmsg("out of memory")));
}
```

So if this could lead to the "OOM issue", why don't we refactor that code too?

**Comment by kainwen** [comment]
> Why did we need to revert it? Just because it pre-allocates such enormous memory? I don't think it's reasonable to just revert the patch simply, cause `GetMaxSnapshotSubxidCount()` is not only used in this patch, when we get snapshot, we will allocate such memory if `snapshot->subxip` is NULL:
> 
> ```
> if (snapshot->subxip == NULL)
> {
>         snapshot->subxip = (TransactionId *)
> 	        malloc(GetMaxSnapshotSubxidCount() * sizeof(TransactionId));
>         if (snapshot->subxip == NULL)
> 	        ereport(ERROR,
> 			        (errcode(ERRCODE_OUT_OF_MEMORY),
> 				        errmsg("out of memory")));
> }
> ```
> 
> So if this could lead to the "OOM issue", why don't we refactor that code too?

Revert is the 1st step to make the CI green. Otherwise, other teams' PR might be blocked (how other people can tell the red CI is due to previous problems or its own problem?).

Re-commit this is simple, cherry pick the old commit, and then refine or fix, then review it again.

**Comment by SmartKeyerror** [comment]
> Revert is the 1st step to make the CI green. Otherwise, other teams' PR might be blocked (how other people can tell the red CI is due to previous problems or its own problem?).

Got it, thanks for the explanation.

**Comment by adam8157** [comment]
> > This reverts commit [1beead0](https://github.com/greenplum-db/gpdb/commit/1beead0c0f49d3456a810a33780b1fb51e0576c9), it reserves too much shared memory.
> > ```
> > >>> p SharedSnapshotShmemSize()
> > $2 = 422752408
> > ```
> 
> Without the patch, what is the value?

```
>>> p SharedSnapshotShmemSize()
$1 = 8740888
```

**Pull request merged**
