### PR TITLE
Support for variadic parameters for UDF.

### PR DESCRIPTION
**Pull request by macroyuyang**
User could use VARIADIC to specify parameter list when defining UDF
if they want to use variadic parameters. It is easier for user to write
only one variadic function instead of same name function with different
parameters. An example for using variadic:
create function concat(text, variadic anyarray) returns text as $$
  select array_to_string($2, $1);
$$ language sql immutable strict;

select concat('%', 1, 2, 3, 4, 5);

### CODE REVIEW

**Comment by yydzero** [comment]
@hlinnaka Do we still use tidycat.pl to generate data like gpdb/gpMgmt/bin/gppylib/data/5.0.json?

**Comment by yydzero** [comment]
Please add test cases.

**Comment by hlinnaka** [comment]
On 11/12/2015 08:47 AM, Yandong Yao wrote:
> @hlinnaka Do we still use tidycat.pl to generate data like gpdb/gpMgmt/bin/gppylib/data/5.0.json?

Good question... I'm not sure what that file is needed for. The server 
doesn't need it for anything, but I think gpcheckcat still does. That's 
probably the only user of that data that's left though. And I'm pretty 
sure that doesn't need all the data in it either.

So I think we should refactor gpcheckcat to not require that json file, 
or at least refactor the way that file is created, so that it wouldn't 
depend on the whole tidycat contraption.

- Heikki

**Comment by hlinnaka** [comment]
Since this is a backport of a feature from PostgreSQL 9.4, please quote the corresponding upstream commit or commits in the commit message.

**Comment by hlinnaka** [comment]
To see how badly this conflicts with my pull request #52, I did a rebase of this over that. It wasn't too bad. pg_proc.h has a lot of conflicts, but they're straightforward to resolve by hand. For all the DATA rows, take the version from #52. Then run 'make', and the process_col_defaults.pl script will complain about all the rows that are in the "long format", i.e. they also have the GPDB-added columns listed in the DATA row. For each of those, just add '0' for the provariadic column.

**Comment by hlinnaka** [comment]
Oh, I also moved provariadic from the end of the table, to the location it's in in the upstream. I think that's nicer, so that we don't need to move it later when we merge with 8.4. (It would also make sense to have all gpdb-added or backported columns at the end, but we haven't done that for other columns.)

That revealed a couple of bugs: one in my process_col_defaults.pl script in pull request #52 - it didn't sort columns numerically. I pushed a fix to that pull request. Another bug was in this patch: in hiddencat.c, a couple of fake pg_proc rows are constructed programmatically. The new provariadic column was not being initialized in those fake rows. That happened to work when the column was at the end, presumably because the memory happened to be zeros, but failed more loudly when I moved the column.

**Comment by hlinnaka** [comment]
I pushed pull request #52 now. Please just let me know if you need help with rebasing this.

**Comment by ivannovick** [comment]
Max did this get merged?

**Comment by macroyuyang** [comment]
Yes. Have merged into master.

**Comment by ivannovick** [comment]
@macroyuyang GREAT!!!

**Pull request closed without merging**
