### PR TITLE
Remove unused file load.sql

### PR DESCRIPTION
**Pull request by hsyuan**
Through the file content we know it uses personal absolute path, which
can't be used by others. DisableXform/EnableXform are already built-in
functions if GPDB is built with Orca. So we can safely delete this file.

### CODE REVIEW

**Comment by hsyuan** [comment]
@vraghavan78 @d @oarap @cramja 
Please take a look.

**Comment by cramja** [comment]
+1

Just curious, how did you find this?
I ran grep, but didn't find any direct usages, which makes sense given the hard coded paths.

```bash
[gpdb: mspehlmann{master}]$ grep -rin load.sql .
Binary file ./.git/index matches
Binary file ./.git/objects/pack/pack-d7d1998d0132c0644b02ed42e28eb05a5676e83e.pack matches
./gpAux/releng/bin/orca_installer_hdr.sh:80:LOAD_ORCA_SQL=${GPHOME}/share/orca/load.sql.in
./gpMgmt/bin/gpload.py:2611:        sql = self.getconfig('gpload:sql', list, default=None)
./gpMgmt/bin/gpload.py:2615:            before   = self.getconfig('gpload:sql:before', unicode, default=None)
./gpMgmt/bin/gpload.py:2616:            after    = self.getconfig('gpload:sql:after', unicode, default=None)
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/filerep_end_to_end/test_filerep_e2e.py:25:This test suite leverages scenario framework to run the workload(sqls)
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurr_alter_vacuum/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurr_droptab_vacuum/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurr_ins_vacuum/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurr_upd_savepoint/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurr_upd_vacuum/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurr_vacuum_vacuum/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurrentupdate/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurrentupdate_del/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurrentupdate_del_rollback/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readcommit/readcommit_concurrentupdate_rollback/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readserial/readserial_concurr_alter_vacuum/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readserial/readserial_concurr_ins_vacuum/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readserial/readserial_concurr_upd_savepoint/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readserial/readserial_concurr_upd_vacuum/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readserial/readserial_concurrent_del_ins/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readserial/readserial_concurrent_upd_ins/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readserial/readserial_concurrentdelete/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/uao/uaocs_mvcc/readserial/readserial_concurrentupdate/runsql.py:24:class RunWorkload(SQLTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/walrepl/basebackup/switch/runsql.py:21:class RunWorkload(SQLConcurrencyTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/walrepl/crash/__init__.py:276:       dir5 = os.path.join(cur_path, 'dml', 'sql','insert_with_gpload.sql.in')
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/walrepl/crash/__init__.py:277:       dir6 = os.path.join(cur_path, 'dml', 'sql','insert_with_gpload.sql')
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/walrepl/load/sql/runsql.py:21:class RunWorkload(SQLConcurrencyTestCase):
./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/walrepl/load/test_load.py:43:        test_case_list1.append('mpp.gpdb.tests.storage.walrepl.load.sql.runsql.RunWorkload')
```

**Comment by Eulerizeit** [comment]
Out of curiosity, are we always to assume GPDB is built with ORCA? As it sits now I thought ORCA was outside the required server build and it could or could not be built on top.

**Comment by hsyuan** [comment]
Correct.
We don't always assume that GPDB is built with Orca.
Orca is optional when building GPDB.

The removed file is generated by Orca, and it contains hard-coded path, not
usable to anyone.

Thanks~
Haisheng Yuan

**Pull request merged**
