### PR TITLE
Add assertion when do subtraction on memory usage in resource group.

### PR DESCRIPTION
**Pull request by guofengrichard**

### CODE REVIEW

**Comment by eurekaka** [comment]
Please add some comments to explain the motivation, thanks

**Comment by pivotal-ning-yu** [comment]
Will it be better to use int instead of uint for the usages?

**Comment by guofengrichard** [comment]
There is no too much difference using uint or int.  So I prefer to keep it as it is before.

**Comment by yydzero** [comment]
+1 for add more description in PR description and commit message.

Shall we add test cases or there is cases already covered this change?

**Comment by guofengrichard** [comment]
That makes sense. I will add more comments.

**Comment by guofengrichard** [comment]
This PR is to only refine the subtraction on memory usage. This is no behavior or logic change.So the existing test cases will cover this change.

**Pull request merged**
