### PR TITLE
Fix bin_gpdb_centos6_icw_green resource

### PR DESCRIPTION
**Pull request by frankgh**
Fixes the bin_gpdb_centos6_icw_green resource versioned_file path. It is currently incorrectly storing artifacts in gpdb_branch_master

### CODE REVIEW

**Comment by bradfordboyle** [comment]
LGTM. Do we need approval from MergeIt?

**Comment by frankgh** [comment]
@bradfordboyle what is MergeIt?

**Comment by Eulerizeit** [comment]
Note for reviewers. This PR is specific to 6.x stable fixing the blob we are pointing to.

**Comment by benchristel** [comment]
MergeIt is the meeting where product managers decide what goes into the `*_STABLE` branches.

I very much hope we don't need to go through a week-long approval process to fix our own CI. Let's merge this and if anyone has a problem with it, they can talk to me about it.

**Comment by Eulerizeit** [comment]
On Wed, Mar 27, 2019 at 12:59 PM Ben Christel <notifications@github.com> wrote:
>
> MergeIt is the meeting where product managers decide what goes into the *_STABLE branches.
>
> I very much hope we don't need to go through a week-long approval process to fix our own CI. Let's merge this and if anyone has a problem with it, they can talk to me about it.

Can we have discussions about internal processes outside of public forums.

-- Rob

**Pull request merged**
