### PR TITLE
Turn on optimizer_force_multistage_agg by default for ORCA

### PR DESCRIPTION
**Pull request by pobbatihari**
Default setting for the guc optimizer_force_multistage_agg has turned on
for GP7

Co-authored-by:Dev Swaroop Chattopadhyay <cdev@vmware.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by gpopt** [comment]
Still some test failures. Please take a look.

**Review by gpopt — APPROVED** [review]
+1

**Review by vraghavan78 — APPROVED** [review]

**Review by dgkimura — COMMENTED** [review]
Could you add a little more detail into the commit message regarding the rationale for this change?  Right now I don't quite understand why we want to force multi-stage aggregate if plan exists.  It kinda feels to me that that means plan is not being costed correctly?  Also, did you try running perf pipeline with this change?

**Comment by vraghavan78** [comment]
> Could you add a little more detail into the commit message regarding the rationale for this change? Right now I don't quite understand why we want to force multi-stage aggregate if plan exists. It kinda feels to me that that means plan is not being costed correctly? Also, did you try running perf pipeline with this change?

@dgkimura for most cases, the aggregate always happens on the top of the query. As you go higher in the query tree, the cardinality is always incorrect immaterial of how good the cardinality estimation of an individual step is. The cumulative error in estimation will fool optimizer's cost model to pick single stage aggregation. Therefore, in an MPP system multi-stage aggregate is always better. For extremely short running query while the delta difference may be large by forcing multi-stage aggregate but the absolute execution time is less than a sec.

**Comment by vraghavan78** [comment]
> Could you add a little more detail into the commit message regarding the rationale for this change? Right now I don't quite understand why we want to force multi-stage aggregate if plan exists. It kinda feels to me that that means plan is not being costed correctly? Also, did you try running perf pipeline with this change?

Context: On GP5 this GUC was set to true. But HTAP work on GP6 made some folks want the cost model to decide. This however has proven to be a wrong decision as observed in our customer environments. TPC-X benchmarks are not affected by this change.

**Pull request merged**
