### PR TITLE
add gp version to pg_config

### PR DESCRIPTION
**Pull request by Sasasu**
Some [extension development framework](https://github.com/tcdi/pgrx/issues/1179) need to read pg_config at compile time to determine the Postgresql version.

We have an ABI incompatibility with Postgresql, but the output of pg_config is identical.

 Modify the output of pg_config to allow such tools to determine the version of gp before compiling.

```
~/GPDB/gpdb_7X sa/gp_config ❯ ../install_7x/bin/pg_config                                                                                                                                                      15s ⎈ default 18:38:39
BINDIR = /home/sa/GPDB/install_7x/bin
DOCDIR = /home/sa/GPDB/install_7x/share/doc/postgresql
HTMLDIR = /home/sa/GPDB/install_7x/share/doc/postgresql
INCLUDEDIR = /home/sa/GPDB/install_7x/include
PKGINCLUDEDIR = /home/sa/GPDB/install_7x/include/postgresql
INCLUDEDIR-SERVER = /home/sa/GPDB/install_7x/include/postgresql/server
LIBDIR = /home/sa/GPDB/install_7x/lib
PKGLIBDIR = /home/sa/GPDB/install_7x/lib/postgresql
LOCALEDIR = /home/sa/GPDB/install_7x/share/locale
MANDIR = /home/sa/GPDB/install_7x/share/man
SHAREDIR = /home/sa/GPDB/install_7x/share/postgresql
SYSCONFDIR = /home/sa/GPDB/install_7x/etc/postgresql
PGXS = /home/sa/GPDB/install_7x/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/home/sa/GPDB/install_7x' '--with-python' '--enable-cassert' '--enable-debug' 'CFLAGS=-ggdb -fno-inline -O0 -g3' '--disable-orca' '--disable-gpcloud' '--with-openssl' '--with-uuid=e2fs' '--disable-debug-extensions' 'CC=/usr/bin/clang' 'CXX=/usr/bin/clang++'
CC = /usr/bin/clang
CPPFLAGS = -D_GNU_SOURCE
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-but-set-variable -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -g -ggdb -fno-inline -O0 -g3  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/sa/GPDB/install_7x/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lnuma -lbz2 -lrt -lssl -lcrypto -lz -lreadline -lcrypt -lm  -lcurl -lzstd
VERSION = PostgreSQL 12.12
GP_VERSION = Greenplum 7.0.0-beta.4+dev.83.g81a762b664 build dev
```

### CODE REVIEW

**Review by beeender — COMMENTED** [review]
Shall we add a `--gp_version` option?

**Comment by beeender** [comment]
The changes look good to me. Let's hold the merging for a while to see if there are more things needed by pgrx

**Review by higuoxing — APPROVED** [review]

**Comment by beeender** [comment]
> Suggestion to change flag name to gp-version. This will make it consistent with other similar flags, such as here: 

A bit messy, it has both `_` and `-` in the option names

one `-`:
`includedir-server`

three `_`:
`ldflags_ex`
`ldflags_sl`
`cflags_sl`

**Comment by kmacoskey** [comment]
Not surprising that upstream is inconsistent. Maybe they had some reason for it. 

We have a choice of which thing to be consistent with.

**Comment by beeender** [comment]
> ising that upstream is inconsistent. Maybe they had some reason for it.
> 
> We have a choice of which thing to be consistent with.

Like other dir thing, `docdir`/`bindir`/etc, without `_`/`-` looks better.

Let's just use `--gpversion`? @kmacoskey

**Comment by kainwen** [comment]
Some background on this PR: (cc @ashwinstar @kmacoskey )

1. `postgresml` (written in rust) depends on `pgrx`
2. To compile `pgrx`, it needs to invoke `pg_config` to get the postgres version to decide compile configs because different version of Postgres' ABI is not the same
3. We want to support `postgresml` in Greenplum, we need to compile `pgrx` and so we need some way to decide Greenplum version
4. Extension team think it is better to have a gpversion output similar to pgversion (Yes, hard code Pgversion = 12 also can resolve the issue for this case becasue we know GP7's kernel version is PG12, but that is not beautiful)
5. so we have this PR.

**Comment by Sasasu** [comment]
I vote for GP_VERSION. the document from PostgreSQL about pg_config: `Print the value of the <name> macro that was used for building PostgreSQL`
our macro is `GP_VERSION` so use `gp_version` is the consistent.

`--includedir-server` (72e7f0d48af42dee5014d012baf832119ca01df9) is older than `--ldflags_ex` (cbd015d71829e825cefde48bf71786d5eb177b94) so I think when PostgreSQL adds more options, they will use `_`

**Pull request merged**
