### PR TITLE
Put hyperloglog extention in a separate schema

### PR DESCRIPTION
**Pull request by oarap**
Having hyperloglog extension in the public schema is causing backup and restore tests to fail. This PR basically puts the hyperloglog extension into a separate schema called `gp_hyperloglog`.
Signed-off-by: Abhijit Subramanya <asubramanya@pivotal.io>

### CODE REVIEW

**Comment by danielgustafsson** [comment]
What is the error? Moving schema has the smell of papering over another error..

**Comment by chrishajas** [comment]
I'm fairly sure this exposed an issue in gpbackup with object extension membership. I don't think putting it into another schema will fix anything, we'll fix gpbackup.

I'm not sure if extensions typically create a schema and place objects in that schema or if they just put objects in the public schema (or if it really even matters). 

Either way, the root cause of this is a gpbackup bug and whether an extension puts its objects in a custom schema or the public schema shouldn't matter from a backup/restore perspective.

**Comment by khuddlefish** [comment]
@chrishajas I'm not sure that's true. Let's talk about it offline.

**Comment by oarap** [comment]
I created another PR with deduplication of hyperloglog code: https://github.com/greenplum-db/gpdb/pull/5213

So, closing this without merging.

**Pull request closed without merging**
