### PR TITLE
Renamed `typname` or other variant to `typeName`.

### PR DESCRIPTION
**Pull request by karthijrk**
This way we are consistent now with the upstream Postgres.

### CODE REVIEW

**Comment by xinzweb** [comment]
+1

**Comment by hsyuan** [comment]
Catalog table `pg_type` has a field called `typname`, will it be affected?

**Comment by hsyuan** [comment]
OK verified, `FormData_pg_type` still use `typname`.

**Comment by karthijrk** [comment]
I don't think we want to change catalog at this point. Agree?

**Comment by hsyuan** [comment]
Correct.

~ ~ ~
Haisheng Yuan

**Pull request merged**
