### PR TITLE
Introduce guc to generate plans that avoid skew with aggregates and bump ORCA version to v3.17.0

### PR DESCRIPTION
**Pull request by zellerh**
This patch introduces a guc `optimizer_force_agg_skew_avoidance` which
can be used to avoid plans which generate a lot of skew when aggregates
are used in the query. The default value of this guc is true.

Co-authored-by: Abhijit Subramanya <asubramanya@pivotal.io>
Co-authored-by: Hans Zeller <hzeller@pivotal.io>

## Here are some reminders before you submit the pull request
- [] Add tests for the change
- [] Document changes
- [] Communicate in the mailing list if needed
- [] Pass `make installcheck`

### CODE REVIEW

**Comment by Eulerizeit** [comment]
Um, adding GUCs to a Stable release can make the cluster panic if there is a downgrade. I know Simon was asking about this earlier and I don't recall the outcome of that discussion. 

I'm generally opposed.

**Comment by pivotal-ning-yu** [comment]
I have similar concern with @Eulerizeit , we should avoid adding new GUCs to 5X.

FYI, the previous discussion on adding GUCs in 5X is here:
https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/RP5Bd2XsMMA/fCOHHUTPCAAJ

The decision at that time was to keep gpconfig reporting ERROR instead of WARNING on unknown GUCs.

**Comment by vraghavan78** [comment]
While I understand the concern, it is very hard not to develop knobs for users to make GPDB performant. As far this GUC is concerned, we expect a vast majority of the customers to not change it. For the small chance the customer needs to change it there could have issue. I have raised your concern to several stakeholders and the consensus was to allow adding some targeted knobs.

**Comment by zellerh** [comment]
Looking at it with high availability in mind: By generating an error, we are purposely making gpstart fail in a downgrade situation, when the customer is probably stressed out. To make matters worse, we are not giving a good error message, instead we make the operation hang (at least for a few minutes). Is that really a good idea?

**Comment by pivotal-ning-yu** [comment]
On Tue, Dec 18, 2018 at 1:01 PM Venkatesh Raghavan <notifications@github.com>
wrote:

> While I understand the concern, it is very hard not to develop knobs for
> users to make GPDB performant. As far this GUC is concerned, we expect a
> vast majority of the customers to not change it. For the small chance the
> customer needs to change it there could have issue. I have raised your
> concern to several stakeholders and the consensus was to allow adding some
> targeted knobs.
>

Yes I understand the need to adding new GUCs.  Personally I'm curious about
the our policy and definition on stable releases, from what I know we are
preventing all unnecessary changes to 4X & 5X, feature changes are
disallowed, even bug fixes need to go through a workflow to get a green
light.  In such a case how should we balance the risk on downgrade
blockers, I guess we should make the decision with care.

**Pull request merged**
