### PR TITLE
Fix bug: alter partitioned table set distributed by will crash.

### PR DESCRIPTION
**Pull request by xiong-gang**
Alter partitioned table set distributed by will dispatch information
from QD to QEs, the information is not correctly coded and decoded on
both sides when:
1. reorganize = false.
2. table have index.
3. partition table have "with" option.

### CODE REVIEW

**Comment by xiong-gang** [comment]
This fix is already in 4.3.6.2.

**Comment by hlinnaka** [comment]
The 2nd patch (query cancel one) looks good to me, but please check spelling of the commit message.

**Comment by yydzero** [comment]
@xiong-gang please review comments, adjust if needed. Thanks!

**Comment by xiong-gang** [comment]
Add comments and changed the commit message.
Thanks.

**Pull request closed without merging**
