### PR TITLE
Enable gpinitsystem to report unknown long options (arguments)

### PR DESCRIPTION
**Pull request by Chibin**
This addresses issue #1071

### CODE REVIEW

**Comment by Chibin** [comment]
@andreasscherbaum Please let me know if this is acceptable. 
Thank you.

**Comment by pivotal-issuemaster** [comment]
@Chibin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1077) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Chibin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1077)!

**Comment by pivotal-issuemaster** [comment]
@Chibin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1077)!

**Comment by pivotal-mike** [comment]
@Chibin I think this one needs to be rebased due to pipeline changes

**Comment by royc1** [comment]
Branch has been rebased against latest master.
Pushed to master

**Pull request closed without merging**
