### PR TITLE
Added missing developer GUCs and commented out macros

### PR DESCRIPTION
**Pull request by t1mursadykov**
There are some developer GUCs which are not represented in both `unsync_guc_name.h` and `sync_guc_name.h`:
1. `log_btree_build_stats`
2. `optimize_bounded_sort`
3. `trace_syncscan`
4. `wal_debug`

As a consequence, GPDB fails if the `BTREE_BUILD_STATS`, `DEBUG_BOUNDED_SORT`, `TRACE_SYNCSCAN` and `WAL_DEBUG` macros was defined when it was compiled. Also the first two macro definitions are not represented in `pg_config_manual.h`. The current patch eliminates this defect.

## Steps to reproduce

1. Uncomment or define one of `BTREE_BUILD_STATS`, `DEBUG_BOUNDED_SORT`, `TRACE_SYNCSCAN` and `WAL_DEBUG` macros.
2. Recompile greenplum
3. Initdb or run on already setup data directory

## Error
Error when gpdb builded with uncommented `TRACE_SYNCSCAN` macro:
```
FATAL:  (XX000) predefined guc name: trace_syncscan contain neither sync_guc_names_array nor unsync_guc_names_array
```

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by ashwinstar — APPROVED** [review]
:+1: LGTM thank you.

Though for many GUCs maybe we need to scan and really see if they should be in `unsync_guc_name.h` or not like `wal_debug` or `log_btree_build_stats` . If we wish to enable better to enable the same for full cluster and why not sync the value to segments.

**Comment by t1mursadykov** [comment]
@ashwinstar Which GUC do you think should be synchronized?

**Comment by t1mursadykov** [comment]
I propose to add `trace_syncscan` and `optimize_bounded_sort` variables to `sync_guc_name.h`.

**Comment by asimrp** [comment]
All debug GUCs should be synchronized.  E.g. WAL_DEBUG is relevant on coordinator as well as segments.

**Comment by t1mursadykov** [comment]
I moved all the added GUCs to `sync_guc_name.h`

**Comment by t1mursadykov** [comment]
@ashwinstar, is there anything else that should be done for this PR to be merged?

**Comment by asimrp** [comment]
Merged to master as b990d89418ff2ae30285f490a7ccf4b3d72fd497.  Thank you @t1mursadykov for the contribution.

**Pull request closed without merging**
