### PR TITLE
copy from on segment should not check random distributing policy

### PR DESCRIPTION
**Pull request by fanfuxiaoran**
Copy from on segment will not check distribution policy

when the table is distributed randomly .

Signed-off-by: Xiaoran Wang <xiwang@pivotal.io>

### CODE REVIEW

**Comment by adam8157** [comment]
How about just skip the GetTargetSeg() if distributed randomly?

**Comment by fanfuxiaoran** [comment]
The table distributed randomly also need target segId returned by
GetTargetSeg().

**Comment by adam8157** [comment]
Why is that? `if (is_check_distkey && distData->p_nattrs > 0) { calc target_seg...}` won't work?

**Comment by fanfuxiaoran** [comment]
I misunderstand it .  There is no need to call GetTargeSeg when distributed
randomly. I will update the pr.

**Pull request merged**
