### PR TITLE
gporca: Use portable way to get frame address.

### PR DESCRIPTION
**Pull request by amitdkhan-pg**
GPOS_ASMFP() used x86_64 assembly instructions to get current frame
address. This obviously doesn't compile on other architectures like
ARM64. So instead use __builtin_frame_address(), which is available
in gcc and presumably clang. Since gcc and clang are the two most
common compilers, and since we don't want to support GPORCA on exotic
architectures and compilers, don't bother to use any other way to get
the frame address.

Let configure fail if __builtin_frame_address() is not found, but
don't do this check if gporca is disabled.

GPORCA's CStackDescriptor::Backtrace() uses frame address. But there
is also gp_backtrace() in the backend code that has similar
functionality. This commit does not merge these two places. But it
prepares the infrastructure to do the merge, including a new macro
HAVE__BUILTIN_FRAME_ADDRESS defined in pg_config.h.

Discussion:
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/FgaR_4sGYrk

### CODE REVIEW

**Comment by hlinnaka** [comment]
I think you forgot to `git add configure.in`. The `configure` file in the PR doesn't match what autoconf produces from `configure.in`. There's a check for "enable_orca" in the `configure` file, but not in `configure.in`.

**Comment by amitdkhan-pg** [comment]
Oh, that was silly of me. I had observed that there is already a difference in checked-in configure and the configure generated by autoconf, so I thought we could do some small changes in configure by-hand, always leavng some hand-footprint in configure. So I had done some enable_orca-related changes and some more changes manually.  I am about to push a commit that does the correction.

**Comment by hlinnaka** [comment]
Squashed and pushed (commit 7c1891fb1a827542c0aa7a60e99e14086a6663ce). Thanks, Amit!

**Comment by d** [comment]
OMG thank you Amit! I was thinking about doing a patch _exactly_ along the same line. In fact I wouldn't even test for compiler support for this intrinsic given that this is a _really_ old intrinsic that has such wide support. But thank you Amit this is great

**Comment by amitdkhan-pg** [comment]
Jesse, Thanks. Yeah, I understand we don't bother about other compilers such as AIX or HP native compilers. That's why we decided not to add any other native ways to get frame address. Ruling that out in configure was just for fast identification of this lack of support for energetic users who try to compiler greenplum on such platforms

Thanks Heikki for driving this commit !

**Comment by lij55** [comment]
Hi all, 

GP6 has the same issue so is there any plan to back port it to GP6?

**Pull request closed without merging**
