### PR TITLE
Remove Master/Standby SyncRepWait Greenplum hack

### PR DESCRIPTION
**Pull request by BaiShaoqi**
When the standby master is unavailable, the master will not block on commits
even though we enable synchronous replication. This is because we have a
Greenplum hack which checks if the WAL stream with the standby master is
valid. If the stream is invalid, the master will quickly skip the SyncRepWait
and continue on its commit.

Remove this hack in order to make Master/Standby and Primary/Mirror WAL
replication more similar.

Co-authored-by: Shaoqi Bai <sbai@pivotal.io>

### CODE REVIEW

**Comment by hlinnaka** [comment]
I'm totally in favor of doing this, but:  Why is it suddenly OK to remove this? Why was it needed in the first place?

**Comment by BaiShaoqi** [comment]
> I'm totally in favor of doing this, but: Why is it suddenly OK to remove this? Why was it needed in the first place?

Thanks for your confirmation. I'm relieved now.

I have no idea about the two 'Why's you ask. Rob may know everthing under the change.

**Comment by asimrp** [comment]
@hlinnaka the QD specific deviation from upstream predates `synchronous_standby_names` GUC.  At the time, there was no easy way to let master move forward if a standby goes down.  With this patch, the workflow is: when a standby goes out of sync, master blocks all commits.  A DBA needs to intervene and set `synchronous_standby_names` to empty string.  This helps the DBA to make note of the fact that master has moved ahead of standby and that if the master also goes down, the standby is not ready for promotion.

**Comment by Eulerizeit** [comment]
@asimrp @hlinnaka primarily this PR was so that Simon and team could look at code instead of us trying to hand wave and try to explain.

**Comment by BaiShaoqi** [comment]
> I'm wondering if an isolation2 test can be added to demonstrate that master blocks commits and setting synchronous_standby_names="" makes the master move forward. The setting of the GUC must be done by the test. The test may leverage the newly available ALTER SYSTEM command to set the GUC. Existing test for reference: https://github.com/greenplum-db/gpdb/blob/master/src/test/isolation2/sql/segwalrep/commit_blocking.sql

Yes, Asim. I'll try to add a test to demonstrate.

Thanks for the link you gave me, it is a good example to refer.

**Comment by BaiShaoqi** [comment]
because I have no permission to push a commit to jimmy's branch, so I recreate another https://github.com/greenplum-db/gpdb/pull/6261

**Pull request closed without merging**
