### PR TITLE
Split WindowSpec into separate before and after parse-analysis structs.

### PR DESCRIPTION
**Pull request by hlinnaka**
In the upstream, two different structs are used to represent a window
definition. WindowDef in the grammar, which is transformed into
WindowClause during parse analysis. In GPDB, we've been using the same
struct, WindowSpec, in both stages. Split it up, to match the upstream.

The representation of the window frame, i.e. "ROWS/RANGE BETWEEN ..." was
different between the upstream implementation and the GPDB one. We now use
the upstream frameOptions+startOffset+endOffset representation in raw
WindowDef parse node, but it's still converted to the WindowFrame
representation for the later stages, so WindowClause still uses that. I
will switch over the rest of the codebase to the upstream representation as
a separate patch.

One notable difference is that the old WindowSpec.winspec field corresponds
to the winref field in WindowDef andWindowClause, except that the new
'winref' is 1-based, while the old field was 0-based.

### CODE REVIEW

**Comment by hlinnaka** [comment]
The second commit is the main one to focus on in this PR. It depends on the first commit, but there is already a separate PR for that (PR #3171).

**Comment by hlinnaka** [comment]
PR #3171 was merged, so just the main commit left in this PR.

**Comment by hlinnaka** [comment]
So, the new tests added in PR #3183 revealed that this isn't quite ready yet. There are a few regression failures like this now:
```
  select pg_get_viewdef('v4');
! ERROR:  internal error (ruleutils.c:5536)
```
That's straightforward to fix; I already have a follow-up patch in the works that refactors the view deparsing code to match the upstream, which also seems to fix this.

But there's also one more interesting case:
```
  create view v11 as
    select avg(a) over (w rows between 1 preceding and 1 following)
    from testtab window w as (order by a rows between unbounded preceding and unbounded following);
+ ERROR:  cannot copy window "w" because it has a frame clause
+ LINE 2:   select avg(a) over (w rows between 1 preceding and 1 follo...
+                              ^
```
This is also not allowed in PostgreSQL, but before this PR, it's been accepted in GPDB. I'll investigate that a bit..

**Comment by hlinnaka** [comment]
Added a second commit to fix the deparsing errors. Posted to gpdb-dev about the second issue: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/8iBxrYAZmB8/3-dTqIgvAwAJ.

**Comment by hlinnaka** [comment]
Ok, committed finally, phew.

Since I didn't get any replies so far,I made an executive decision and started rejecting that case that I brought up at https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/8iBxrYAZmB8/3-dTqIgvAwAJ. @mkiyama, if you're collecting incompatibilities between GPDB 5 and GPDB 6, that should go to that list.

**Comment by mkiyama** [comment]
\+ @dyozie 
@hlinnaka 
Here is a draft of the change. 
Please let me know if any changes are required.

Also, is this going in 5.0.0 GA or a later release?
___
In a Greenplum Database 5.0.0, a SELECT command a named WINDOW clause cannot contain a ROWS or RANGE clause if the named window is used in the OVER() expression of a window function such as rank() or avg(). 

Greenplum Database 5.0.0 returns an error. In previous Greenplum Database releases, this was allowed.
___

**Comment by hlinnaka** [comment]
On 09/12/2017 02:09 AM, Mel Kiyama wrote:
> Here is a draft of the change.
 >
> Please let me know if any changes are required.
> 
> Also, is this going in 5.0.0 GA or a later release?

No, only in GPDB 6. No change in GPDB 5 yet.

> ___
> In a Greenplum Database 5.0.0, a SELECT command a named WINDOW clause cannot contain a ROWS or RANGE clause if the named window is used in the OVER() expression of a window function such as rank() or avg().
> 
> Greenplum Database 5.0.0 returns an error. In previous Greenplum Database releases, this was allowed.
> ___

Wording sounds good. I think you're missing a word from the sentence, 
though: "a SELECT command *with* a named WINDOW clause ....". And 6.0.0 
instead of 5.0.0.

Thanks!

- Heikki

**Pull request merged**
