### PR TITLE
Add client and loader support for aix7_ppc_64 platform

### PR DESCRIPTION
**Pull request by yuanzhao**
1. Add dependency packages to Ivy
2. Modify set_bld_arch.sh to correctly recongize aix7
3. Disable unsupported python libraries on aix7.
4. Disable gpmapreduce for aix7
5. Set ADDON_DIR for aix7
   Signed-off-by: Peifeng Qiu pqiu@pivotal.io

### CODE REVIEW

**Comment by lij55** [comment]
Hi @pivotal-mike ,
Please help to review this PR. Thanks.
We could provide the AIX binary for 5.0 GA

**Comment by Eulerizeit** [comment]
Jasper,

Mike is on vacation til the end of this week I think.

Rob

**Comment by lij55** [comment]
ohhh, thanks, rob.

**Comment by pf-qiu** [comment]
If nobody objects, we plan to merge this tomorrow, thanks.

**Pull request merged**
