### PR TITLE
Fixed #21:Replace ed with sed in ED_PG_CONF function

### LINKED ISSUE #21: Replace "ed" dependency used by gpinitsystem and gpcreateseg.sh
Currently used by gpinitsystem and gpcreateseg.sh and defined in the function "ED_PG_CONF" (defined  in gpMgmt/bin/lib/gp_bash_functions.sh), replace the use of "ed" (line-oriented text editor) with a more readily available package (example: sed).

If "ed" is not available, one will see somewhat messages similar to "[WARN]:-Failed to replace #port in */postgresql.conf".  One needs to hunt around to actually see that "ed" is missing from the runtime environment.

### PR DESCRIPTION
**Pull request by robertmu**
Replace ed with sed in ED_PG_CONF function

### CODE REVIEW

**Comment by ivannovick** [comment]
Hi @robertmu thx for submitting this!  We have wanted to do it for a long time but have not had a chance.  I hope we get some positive reviews from other developers on the code review and can merge it in.  --- Ivan Novick, PM for GPDB @ Pivotal.

**Comment by edespino** [comment]
@robertmu, What do you think about adding the following to go along with your initial change (patch attached):

* function renaming: ED_PG_CONF --> SED_PG_CONF
* tmp file renaming: sed_text.$$ --> sed_text.$$
* variable renaming: ED_HOST --> SED_HOST

[0001-Additional-renames-ED-SED.patch.txt](https://github.com/greenplum-db/gpdb/files/29549/0001-Additional-renames-ED-SED.patch.txt)

**Comment by robertmu** [comment]
Hi @edespino.Change have been completed by you opinion

**Comment by edespino** [comment]
@robertmu - Looks good.

**Comment by edespino** [comment]
Prior to checking in the change, I tested this on the Greenplum internal build farm.  The OSX 10.8.5 (Greenplum buildfarm) platform encountered the following error with the new sed command:

```11/9/15 9:59:34 PM PST: sed: 1: "/Volumes/data/pulse2-ag ...": extra characters at the end of d command```

**Comment by edespino** [comment]
Merged into master.

**Pull request closed without merging**
