### PR TITLE
Avoid further planning in case of result relation was pruned

### PR DESCRIPTION
**Pull request by Stolb27**
A result relation is a target relation for DML operations
in the appropriate queries. If the result relation is a member
of the join tree and is excluded by query predicates, such query
won't modify any tuples. So we could avoid spending resources
for planning remaining join tree relations, especially complex
sub queries. This gives a nice performance gain when planning
DML queries to tables with many leaf tables in the inheritance tree
(i.e. partitioned too). Because Postgres builds a separate plan for
each child relation first according to inheritance_planner function
logic.

There are several iterations to refactor this logic in the upstream
Postgres:

1. Plan Update/Delete query as SELECT query first to collect
    list of affected children [[1]](https://www.postgresql.org/message-id/9d7c5112-cb99-6a47-d3be-cf1ee6862a1d@lab.ntt.co.jp).
2. Rework Modify Table node to handle tuples from any child
    relation [[2]](https://www.postgresql.org/message-id/CA+HiwqHpHdqdDn48yCEhynnniahH78rwcrv1rEX65-fsZGBOLQ@mail.gmail.com)

So upstream Postgres and gpdb master is not interested in this patch.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by kainwen** [comment]
Seem reasonable. Thanks. Will take more time to review next week.

**Comment by kainwen** [comment]
Hi I have several questions and comments:

1. without this PR, I also get the same plan on 6X for the case of this PR (I reduce some columns), so what issue is this PR solving? (Surely, I hit OOM when use the complete SQL of your case's). Paste at the end of this comment.
2. this test case `set optimizer = off`, this is not necessary we should test also under ORCA even the code change is for planner.
3. we do not need a new test file, I think we can just put it in `regress/partition_pruning`.


```
gpadmin=# CREATE TABLE t_part1 (
    key1 int, update_me int, dummy1 int
)
DISTRIBUTED BY (key1)
PARTITION BY RANGE (key1) (start (1) end (100) every (1));
CREATE TABLE
gpadmin=# explain (costs off)
update t_part1 trg
set update_me = src.update_me
from (
      select
      r.key1,
      r.update_me as update_me,
      row_number() over() rn
      from t_part1 r
      where r.key1 = 2
) src
where  trg.key1 = src.key1
        and trg.key1 = 2;
                                        QUERY PLAN
-------------------------------------------------------------------------------------------
 Update on t_part1_1_prt_2 trg
   ->  Explicit Redistribute Motion 3:3  (slice3; segments: 3)
         ->  Nested Loop
               ->  Seq Scan on t_part1_1_prt_2 trg
                     Filter: (key1 = 2)
               ->  Materialize
                     ->  Redistribute Motion 1:3  (slice2; segments: 1)
                           Hash Key: src.key1
                           ->  Subquery Scan on src
                                 Filter: (src.key1 = 2)
                                 ->  WindowAgg
                                       ->  Gather Motion 3:1  (slice1; segments: 3)
                                             ->  Result
                                                   ->  Append
                                                         ->  Seq Scan on t_part1_1_prt_2 r
                                                               Filter: (key1 = 2)
 Optimizer: Postgres query optimizer
(17 rows)

gpadmin=# select version();
                                                                                                            version

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------
 PostgreSQL 9.4.26 (Greenplum Database 6.20.3+dev.167.g561cedf53d build dev) on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit compiled on Jun 20 2022 15:3
3:11 (with assert checking)
(1 row)


gpadmin@zlyu:~/workspace/gpdb$ git show 561cedf53d
commit 561cedf53d02e264c4a037683f4b55dccc586d5c (HEAD -> 6X_STABLE, upstream/6X_STABLE)
Author: David Kimura <dkimura@vmware.com>
Date:   Thu Jun 16 14:00:06 2022 -0700

    [ORCA] Fix memory leaks in translator (#13683)

    Found while rebasing Jesse's WIP refcount branch that is attempting to
```

**Comment by Stolb27** [comment]
@kainwen, 

> without this PR, I also get the same plan on 6X for the case of this PR (I reduce some columns), so what issue is this PR solving? (Surely, I hit OOM when use the complete SQL of your case's). Paste at the end of this comment.

All unaffected partitions are pruned correctly on the current 6X_STABLE branch. So plan don't have to be changed by this patch. But currently, Postgres planner spends resources to build a whole DML query plan for each partition (`inheritance_planner()`). gpdb generates all access paths for each jointree member first, in spite of query predicates. One of sub-queries may be a complex sub-query, as in the provided test case. Planning such sub-queries may consume significant amount of memory and I didn't find possibility to free it in case of the current partition was pruned because planner copies objects intensively and store them in the global memory context. Test case without modification consumes over 8Gb memory during planning phase. But we know that 

> the UPDATE/DELETE target can never be the nullable side of an outer join

So, I've tried to interrupt sub query planning as early as possible in case of pruning result relation.

> this test case set optimizer = off, this is not necessary we should test also under ORCA even the code change is for planner.

I tried to decrease patch footprint. I'll add output for ORCA.

> we do not need a new test file, I think we can just put it in regress/partition_pruning.

I didn't decide to place test to partition_pruning because there are no tests for DML partition pruning and this patch decrease resource consumption but not query plan. I'll move test case if it is more correct place.

**Comment by Stolb27** [comment]
@kainwen, thank you. I've moved test to the regress/partition_pruning and added output for ORCA optimizer.

**Pull request merged**
