### PR TITLE
Remove unsupported OS-es from ivy.xml

### PR DESCRIPTION
**Pull request by adam8157**

### CODE REVIEW

**Comment by jimmyyih** [comment]
We can probably remove OSX as well.  We no longer build OSX enterprise builds in any CI.

**Comment by adam8157** [comment]
Let's merge this and decide whether to remove macOS later. @ryantang

**Comment by danielgustafsson** [comment]
+1 on removing macOS

**Comment by cjcjameson** [comment]
@adam8157 We still have references to AIX etc. in the codebase in a variety of places -- not just the ivy.xml. Shall we do the full job of cleaning it up at this time? Does this belong in a separate issue / PR?

**Comment by adam8157** [comment]
@cjcjameson this story was only to remove OS-es from ivy.xml.

Cc @ryantang for your other questions.

**Comment by danielgustafsson** [comment]
Some of the references are probably inherited from upstream and should be left in place to be removed by the merge process (to avoid unnecessary merge conflicts).

**Pull request merged**
