### PR TITLE
Handle sort query finish pending updated

### PR DESCRIPTION
**Pull request by armenatzoglou**
My previous commit (3d0a480616d63518b84bd93d67d68791d101a7fe), which was solving the issue described in https://github.com/greenplum-db/gpdb/pull/276, was braking some ICG tests in some operating systems and we reverted it. This is a complete fix, tested under multiple operating systems.

### CODE REVIEW

**Comment by armenatzoglou** [comment]
@foyzur @gcaragea Please take a look when you have time. Thanks

**Comment by gcaragea** [comment]
Looks good, the additional check in the rescan method makes sense. 
:+1:

**Comment by ivannovick** [comment]
very cool!  nice work

**Comment by vraghavan78** [comment]
+1

**Comment by armenatzoglou** [comment]
Pushed to master. Thanks a lot for your review.

**Pull request closed without merging**
