### PR TITLE
Refactor gpmon counters

### PR DESCRIPTION
**Pull request by hlinnaka**
Refactor the way gpmon counters are updated in the executor, to reduce our diff footprint vs. upstream.

See commit messages.

### CODE REVIEW

**Comment by hlinnaka** [comment]
I ran the gpperfmon behave test on my laptop with this, and it passed. So I guess this is at least not completely broken. I'm not sure if that test tests "rows skew" thing. This changes the computation of the "rows skew" to use the rows-out -counters instead of the in-counters. I believe that is just as good, but would be good to have a test for it.

I've been having in mind that we should clean up these counters for a long time, but PR #3523 reminded me again that we really should. My plan is to get this PR committed first, and after that I would be fairly confident that the gpmon counters in PR #3523 work too.

**Comment by cjcjameson** [comment]
@hlinnaka Thanks! We might also take a look, right @skahler-pivotal @Chibin ?

**Comment by Chibin** [comment]
> @hlinnaka Thanks! We might also take a look, right @skahler-pivotal @Chibin ?

Yes, noted it to @skahler-pivotal

**Comment by hlinnaka** [comment]
Ping? I would really appreciate some review on this.

**Comment by Chibin** [comment]
> Ping? I would really appreciate some review on this.

Yep, reviewing it! :)

**Comment by hlinnaka** [comment]
Rebased, no real changes.

**Comment by skahler-pivotal** [comment]
Will working off of rows_out potentially mask skew and not let us see that it exists? By using rows_in we see what every process will need to handle and therefore know how much work each one will need to do. How do we look at the result of the work and understand how much lifting it took to get there?

**Comment by Eulerizeit** [comment]
@skahler-pivotal @Chibin for some context; this PR needs to go in before https://github.com/greenplum-db/gpdb/pull/3523.

**Comment by hlinnaka** [comment]
On 11/01/2017 06:38 PM, Scott Kahler wrote:
> Will working off of rows_out potentially mask skew and not let us see
> that it exists? By using rows_in we see what every process will need
> to handle and therefore know how much work each one will need to do.

I don't think think it makes any difference. A row in of one Plan node 
is always a row out of the node below. So the ratio of rows processed 
between segments should be the same, whether you measure rows in or out.

> How do we look at the result of the work and understand how much
> lifting it took to get there?
I'm not sure I understand the question. I did try to divide the work 
into commits in a logical way, and explain what each commit does in the 
commit message. Is there something more I can do to help with the review?

- Heikki

**Comment by hlinnaka** [comment]
On 11/01/2017 08:40 PM, Heikki Linnakangas wrote:
> On 11/01/2017 06:38 PM, Scott Kahler wrote:
>> Will working off of rows_out potentially mask skew and not let us see
>> that it exists? By using rows_in we see what every process will need
>> to handle and therefore know how much work each one will need to do.
> 
> I don't think think it makes any difference. A row in of one Plan node
> is always a row out of the node below. So the ratio of rows processed
> between segments should be the same, whether you measure rows in or out.

To elaborate on that: Currently, the rows-in counters are incremented 
after calling ExecProcNode(), which pulls a tuple from the child node. 
So I believe that doesn't count a tuple that is read from disk, e.g. in 
a SeqScan, but filtered out at the SeqScan node itself, before bubbling 
it up. It would be good to take such rows into account when calculating 
the skew, but this PR doesn't make that any worse, because they're 
currently not counted, anyway.

- Heikki

**Comment by skahler-pivotal** [comment]
On Wed, Nov 1, 2017 at 2:10 PM, Heikki Linnakangas <notifications@github.com
> wrote:

> On 11/01/2017 08:40 PM, Heikki Linnakangas wrote:
> > On 11/01/2017 06:38 PM, Scott Kahler wrote:
> >> Will working off of rows_out potentially mask skew and not let us see
> >> that it exists? By using rows_in we see what every process will need
> >> to handle and therefore know how much work each one will need to do.
> >
> > I don't think think it makes any difference. A row in of one Plan node
> > is always a row out of the node below. So the ratio of rows processed
> > between segments should be the same, whether you measure rows in or out.
>
> To elaborate on that: Currently, the rows-in counters are incremented
> after calling ExecProcNode(), which pulls a tuple from the child node.
> So I believe that doesn't count a tuple that is read from disk, e.g. in
> a SeqScan, but filtered out at the SeqScan node itself, before bubbling
> it up. It would be good to take such rows into account when calculating
> the skew, but this PR doesn't make that any worse, because they're
> currently not counted, anyway.
>
>
To clarify if we have an Aggregate node we would need to look back to the
previous node in order to figure out if the aggregate would be potentially
skewing. We would look at something like previous Redistribute and look for
skew in it's output, correct. The assumption there being that the
Redistribute would accurately display if it is pushing a majority of
results to a specific Aggregate node on a specific segment.

Note the earlier comment on lifting had nothing to do with the PRs, they
make sense. The comment was around not being able to look at a node to know
what work it is doing you could only drive that by looking at the previous
node.

-- 

Scott Kahler | Pivotal, Greenplum Product Management  | skahler@pivotal.io
| 816.237.0610

**Comment by Chibin** [comment]
I don't see any particular issues. I am currently looking through parts of the executor code to understand the flow. 

The main question I'm trying to figure out the moment is... is there at any point where a node would not go through the ExecProcNode? For example, something directly calling nodeAgg/nodeAppend, etc.

From what I see, ExecProcNode is the generic node that will redirect to the other types of executors (not sure if I'm using the right word), and every new tuple will need to go through this function.

Also, does MultiExecProcNode ever come into play when counting the amount of rows?

**Comment by hlinnaka** [comment]
On 11/02/2017 02:28 AM, Marbin Tan wrote:
> The main question I'm trying to figure out the moment is... is there
> at any point where a node would not go through the ExecProcNode? For
> example, something directly calling nodeAgg/nodeAppend, etc.

I don't think there is. The code in an executor node cannot generally 
assume that a child node is of a particular type. A few exceptions come 
to mind:

* In a hash join, one side of the join is a Hash node.

* ShareInputScan assumes that the child is a Materialize or a Sort node.

* PR #3523 changes the way Dynamic Index Scans work, so that the Dynamic 
Index Scan node constructs an Index Scan node on the fly for each partition.

I don't believe this PR changes anything for those cases, though.

> From what I see, ExecProcNode is the generic node that will redirect
> to the other types of executors (not sure if I'm using the right
> word), and every new tuple will need to go through this function.

Yep.

> Also, does MultiExecProcNode ever come into play when counting the
> amount of rows?

Hmm, don't think so. I don' see any Gpmon_Incr_Rows_Out/In() calls in 
the MultiExec functions. Whether there should, I don't know, but this PR 
doesn't change that.

- Heikki

**Comment by hlinnaka** [comment]
@skahler-pivotal, @Chibin, did you have any further comments, or is this ready to be pushed?

**Comment by skahler-pivotal** [comment]
@hlinnaka we are good at this point 👍

**Comment by hlinnaka** [comment]
Pushed, thanks for the review!

**Pull request merged**
