### PR TITLE
Have "configure" fail if GPOPT/GPOS header files are not present (#20).

### PR DESCRIPTION
**Pull request by edespino**
This issue (#20) was originally reported by Tim Morley (@phoccer).

### CODE REVIEW

**Comment by hlinnaka** [comment]
Looks good as far as it goes. To actually build with ORCA, you'll need the shared libraries too, not just the headers. But there's no hurry to expand this until those libraries are open sourced too.

**Comment by edespino** [comment]
Pushed to master.

**Comment by hlinnaka** [comment]
This commit turned out to be a few bricks shy of a load, causing configure to fail. Ed reverted it, hence I'm reopening this.

```
checking for struct sockcred... no
checking for struct option... yes
checking for z_streamp... no
configure: error: zlib version is too old
Use --without-zlib to disable zlib support.
src/Makefile.global:590: recipe for target 'config.status' failed
make: *** [config.status] Error 1
```

The root cause of this was the same that I happened to bump into in July in PostgreSQL, see this commit:

```
commit 01051a9879fcd353eaf0d3788a911e774b52798c
Author: Heikki Linnakangas <heikki.linnakangas@iki.fi>
Date:   Thu Jul 9 11:38:34 2015 +0300

    Use AS_IF rather than plain shell "if" in pthread-check.
    
    Autoconf generates additional code for the first AC_CHECK_HEADERS call in
    the script. If the first call is within an if-block, the additional code is
    put inside the if-block too, even though it is needed by subsequent
    AC_CHECK_HEADERS checks and should always be executed. When I moved the
    pthread-related checks earlier in the script, the pthread.h test inside
    the block became the very first AC_CHECK_HEADERS call in the script,
    triggering that problem.
    
    To fix, use AS_IF instead of plain shell if. AS_IF knows about that issue,
    and makes sure the additional code is always executed. To be completely
    safe from this issue (and others), we should always be using AS_IF instead
    of plain if, but that seems like excessive caution given that this is the
    first time we have trouble like this. Plain if-then is more readable than
    AS_IF.
    
    This should fix compilation with --disable-thread-safety, and hopefully the
    buildfarm failure on forgmouth, related to mingw standard headers, too.
    I backpatched the previous fixes to 9.5, but it's starting to look like
    these changes are too fiddly to backpatch, so commit this to master only,
    and revert all the pthread-related configure changes in 9.5.
```

In a nutshell, the first AC_CHECK_HEADERS call in the configure script must not be in a "if test" block. Must use autoconf's AS_IF instead.

**Comment by hlinnaka** [comment]
Looks like github won't let me reopen this pull request after all, but re-opened the issue anyway.

**Pull request closed without merging**
