### PR TITLE
Error on "SET optimizer=on" if server is built without ORCA.

### PR DESCRIPTION
**Pull request by hlinnaka**
Also, rephrase the message you get from enable_xform() etc. functions, if
the server has been built without ORCA.

Add alternative expected output files to make the regression tests pass
without --enable-orca.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@edespino, others, does this look reasonable to silence the regression test failures when building without ORCA. I just added alternative output files

I also turned "SET optimizer=on" to an error, if the server has been built without ORCA. For precedence, "ssl=on" or "debug_assertions=on" also throw similar errors, if the server is built without those features.

**Comment by entong** [comment]
Looks ok except that 'ORCA' is just a code name. We do not own the 'Orca' trademark. The official name is 'Pivotal Query Optimizer'. This is the current message on Apache HAWQ:
Error: Pivotal Query Optimizer not supported by this build.
I think "Server has been compiled without Pivotal Query Optimizer" is fine.

**Comment by edespino** [comment]
FYI: We currently use the "configure" option named "--enable_orca" when building with it.  Should the value change? (--enable_optimizer???)

**Comment by hlinnaka** [comment]
> FYI: We currently use the "configure" option named "--enable_orca"
> when building with it.  Should the value change?
> (--enable_optimizer???)

Hmm. I find calling it just "optimizer" hugely confusing, because the 
Postgres planner is also called an optimizer. Yeah, we also have a GUC 
called "optimizer", but that's also super-confusing. Any better suggestions?

I'm not too worried about the lack of trademark on ORCA. As long as 
no-one else is using ORCA as a trademark for something similar, that's OK.

Whatever we choose now, we'll probably need to change this when we know 
what the thing will be called when it's open sourced. Perhaps we should 
just leave it alone until we know better.

- Heikki

**Comment by ivannovick** [comment]
+1 to leave it alone

**Comment by biouxtai** [comment]
what about --enable_pqo?

Naming it directly after the new PQO should help disambiguate the flag as well as remove the trademarked name.

**Comment by entong** [comment]
What does the naming convention 'blah_1.out' do in the expected output folder?

**Comment by hlinnaka** [comment]
Same as in upstream: for test case called "blah", pg_regress will first compare the output with "blah.out", then "blah_1".out, then "blah_2.out" and so forth. If it matches any of the outputs, the test passes

**Comment by hlinnaka** [comment]
I pushed this now as it is. We can rename the --enable-orca option and mentions of ORCA in error messages etc., but unless there's some big hurry, let's do it after ORCA is open sourced, and we know what it's going to be called.

**Pull request closed without merging**
