### PR TITLE
Remove dead AppendOnlyScan and AOCSScan node types.

### PR DESCRIPTION
**Pull request by hlinnaka**
Once upon a time, they were used for the equivalent of a SeqScan, on
append-only and AOCS tables. These days, a TableScan node is used to
represent that, regardless of the type of table.

Also remove the correspondingly dead AppendOnlyPath and AOCSPath nodes.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
This looks sane to me. I assume this code was intended to diverge from tablescans, do you know if there were ever any ideas for optimizations on AO/AOCS tablescans that were attempted?

**Comment by hlinnaka** [comment]
I don't know the history very well. I think they used to be separate node types, but were later merged to TableScan, but I don't know why they were separate originally nor why they were merged.

(feel free to push this while I'm away, if you have the time)

On 22 June 2016 09:43:44 EEST, Daniel Gustafsson <notifications@github.com> wrote:
>This looks sane to me. I assume this code was intended to diverge from
>tablescans, do you know if there were ever any ideas for optimizations
>on AO/AOCS tablescans that were attempted?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/862#issuecomment-227657275

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danielgustafsson** [comment]
> On 22 Jun 2016, at 09:29, Heikki Linnakangas <notifications@github.com> wrote:
> 
> (feel free to push this while I'm away, if you have the time)

Will do, enjoy the sun!

**Comment by danielgustafsson** [comment]
Looking a bit closer to get it ready for commit I think this patch needs a little more massage before it goes in. Please see the patch in my fork: https://github.com/danielgustafsson/gpdb/commit/ad0ecad97810093bb88f2a5c52c279ef89cd9d80, which applies on top of this branch.

**Comment by danielgustafsson** [comment]
Also, there are a few errors in ICG like these in co_nestloop_idxscan, bfv_index and gp_optimizer. As I understand the patch the actual underlying functionality for scanning the relations hasn't changed, merely the `EXPLAIN` output.

```diff
*** ./expected/co_nestloop_idxscan_1.out    Tue Jun 28 12:20:35 2016
--- ./results/co_nestloop_idxscan.out   Tue Jun 28 12:20:35 2016
***************
*** 21,27 ****
          {
            'id' => 3,
            'parent' => 2,
!           'short' => 'Append-only Columnar Scan on foo f'
          },
          {
            'child' => [
--- 21,27 ----
          {
            'id' => 3,
            'parent' => 2,
!           'short' => 'Seq Scan on foo f'
          },
          {
            'child' => [
```

**Comment by ashwinstar** [comment]
Seems more work needed before can be pushed-in, wish to close and re-open when ready ?

**Comment by ashwinstar** [comment]
Seems some more work is needed to get it ready, wish to close and re-open when ready ?

**Comment by hlinnaka** [comment]
Yeah, I guess. Closed.

**Pull request closed without merging**
