### PR TITLE
This fixes the case where VACUUM FULL on an appendonly table would ca…

### PR DESCRIPTION
**Pull request by asubramanya**
…use its

auxiliary tables to not get shrunk and generate a notice to the user.

The AppendOnlyCompaction_IsRelationEmpty() function incorrectly assumed that
the column number for tupcount column was the same in pg_aoseg and pg_aocsseg
tables. This cause it to incorrectly return true even when the CO relation was
not empty. This method is used in vacuum to determine if the auxiliary
relations need to be vacuumed. Due to the bug, vacuum would update the
pg_aocsseg relation and vacuum it within the same transaction and hence
generate the NOTICE that it can't shrink the relation because transaction is
already in progress and would not shrink the relation.

Also make sure that we do a vacuum on the auxiliary relations only in two cases :-
1. Vacuum cleanup phase
2. Relation is empty and we are in prepare phase
Otherwise we will end up with the same issue above if some of the segments have
zero rows

As a part of the test changes we have decided to only ignore some of the NOTICE
statements and check for the rest of them.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Can you split this into two patches, please? One to change the NOTICE handling in the test cases, and then fix the bug and add the test case for that one in second commit. Changing the NOTICE handling is a sensible thing to do independently of the bug fix, and would be nice to review that separately.

In init_file, would be good to have some comments on each of the mangled NOTICEs, noting where they come from and why they need to be mangled/ignored.

**Comment by asubramanya** [comment]
I've split this into two separate commits.

**Comment by hlinnaka** [comment]
Please go through all the replacements in init_file. For each one, see if it's really needed, and what for. Remove the unneeded ones, and for the ones that are still needed, add a brief comment explaining what it's for.

At a quick glance, I'm pretty sure the "bleat .*" rule really shouldn't be there, for example..

**Comment by asubramanya** [comment]
@hlinnaka I have updated the init_file.

The `bleat()` function is used in the polymorphism.sql tests. It is invoked for each row of the int4_tbl as follows
```
select f1, sql_if(f1 > 0, bleat(f1), bleat(f1 + 1)) from int4_tbl;
```
. The issue is that the NOTICEs which are generated by this function are generated in a different order. We could add an order by clause to order the rows, but I checked the upstream postgres tests and they don't add a group by clause either.

**Comment by hlinnaka** [comment]
Ping? Are you working on this?

**Comment by asubramanya** [comment]
@hlinnaka I have opened a new pull request for this #147 . I am closing this one.

**Pull request closed without merging**
