### PR TITLE
Reduce noise during compilation in CI with -s.

### PR DESCRIPTION
**Pull request by ashwinstar**

### CODE REVIEW

**Comment by ashwinstar** [comment]
Deferred from adding `--quit` for configure as felt maybe it would be of interest to refer, but would like to know opinions and can silence that too if felt like.

**Comment by hlinnaka** [comment]
+1 on "make -s", but -0.5 on silencing configure output. It's not that much output, and it's nice to be able to look at the configure output to see what options were chosen.

**Comment by ashwinstar** [comment]
One more option to seek feedback would be should I do it in Makefile itself by default instead of just CI script (something maybe like using `.SILENT` thing) ? Then laptop or CI we get the benefit everywhere by default. Easily can provide option to override if need be like `VERBOSE=1` to the complete details.

**Comment by hlinnaka** [comment]
On 08/12/17 11:29, Ashwin Agrawal wrote:
> One more option to seek feedback would be should I do it in Makefile
> itself by default instead of just CI script (something maybe like
> using `.SILENT` thing) ? Then laptop or CI we get the benefit
> everywhere by default. Easily can provide option to override if need
> be like `VERBOSE=1` to the complete details.

I would prefer to keep the Makefiles unmodified. I always type "make -s" 
out of habit, anyway. Or you can do "export MAKEFLAGS=-s".

- Heikki

**Pull request merged**
