### PR TITLE
Fix detoasting of values in printtup().

### PR DESCRIPTION
**Pull request by hlinnaka**
There used to be an unconditional call to detoast the value earlier in the
function, as hinted by the comments, but that was removed in PostgreSQL 9.4
by commit b006f4ddb9. We need to deal with toasted values here now.

Fixes github issue https://github.com/greenplum-db/gpdb/issues/6081.

### CODE REVIEW

**Comment by hlinnaka** [comment]
On 28/10/2018 22:27, Daniel Gustafsson wrote:
> danielgustafsson commented on this pull request.
> 
> 
> 
>> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +123456789012345678901234567890123456789012345678901234567890123456789012345
> +$embeddedtext$::text;
> +$function$;
> +-- Check that it's detoasted correctly when it's sent to the client, in
> +-- printtup()
> +select prosrc from pg_proc where proname = 'function_with_long_body';
> 
> Rather than echoing the entire long prosrc into the answer file once more, can we `select md5(prosrc) = <known hash> ..`?

Unfortunately not. The bug was in printtup(), the function that's used 
to send the value on the wire for the client. We must retrieve the 
actual value to the client to tickle the codepath.

We could perhaps redirect it to a file with psql commands, something 
like "\o /tmp/long_prosrc", and then read it back in with COPY. But that 
starts to get complicated...

- Heikki

**Comment by danielgustafsson** [comment]
> On 28 Oct 2018, at 22:45, Heikki Linnakangas <notifications@github.com> wrote:

> Unfortunately not. The bug was in printtup(), the function that's used 
> to send the value on the wire for the client. We must retrieve the 
> actual value to the client to tickle the codepath.

Gotcha.

> We could perhaps redirect it to a file with psql commands, something 
> like "\o /tmp/long_prosrc", and then read it back in with COPY. But that 
> starts to get complicated…

Yeah, the cost of that complexity is far greater than carrying this diff.

**Comment by pivotal-ning-yu** [comment]
Cool, looks great, thank you.

**Comment by asimrp** [comment]
> Unfortunately not. The bug was in printtup(), the function that's used
to send the value on the wire for the client. We must retrieve the
actual value to the client to tickle the codepath.

An alternative is to write an isolation2 test to connect to a segment in utility mode and select a large text datum from a user table.  I think `printtup()` will be invoked in that case.

**Comment by danielgustafsson** [comment]
> On 29 Oct 2018, at 20:28, Heikki Linnakangas <notifications@github.com> wrote:
> 
> On 29/10/2018 21:16, Asim RP wrote:
> >> Unfortunately not. The bug was in printtup(), the function that's
> >> used
> > to send the value on the wire for the client. We must retrieve the 
> > actual value to the client to tickle the codepath.
> > 
> > An alternative is to write an isolation2 test to connect to a segment
> > in utility mode and select a large text datum from a user table. I
> > think `printtup()` will be invoked in that case.
> 
> Yes, but that doesn't help with Daniel's complaint that the SQL and the 
> expected output are huge. We'd still need a huge datum to trigger 
> toasting. Or ALTER TABLE to force a smaller value to be toasted. But I 
> feel that starts to also get more complicated…

Yeah, I don’t think it’s worth complicating this. The only reasonably trivial way I can see to reduce the footprint would be to use a matchsubs rule in atmsort with a count in the regex, but that also hardly seems worth it.

**Pull request merged**
