### PR TITLE
Remove incorrect assumption that reindex cannot happen within a

### LINKED ISSUE #567: Assertion failure on reindex within transaction
postgres=# create table bar(id int4 primary key);
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "bar_pkey" for table "bar"
CREATE TABLE
postgres=# begin;
BEGIN
postgres=# reindex table bar;
FATAL:  Unexpected internal error (indexcmds.c:1653)
DETAIL:  FailedAssertion("!(!IsTransactionOrTransactionBlock())", File: "indexcmds.c", Line: 1653)
HINT:  Process 18515 will wait for gp_debug_linger=120 seconds before termination.

The qp_gist_indexes4 regression test also triggers that, when you run installcheck-good with assertions enabled.

### PR DESCRIPTION
**Pull request by asimrp**
transaction block.

ReindexRelationList is a GPDB specific function that wraps each
reindex table operation within a separate transaction.  If the table
being reindexed is a partitioned table, each partition is reindexed in
a separate transaction.  Now that we have removed the assertion,
refactor this function to commit and start top level transcation,
rather than leaving this burden on callers.

Fixes #567.

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
I like it. I assume you don't gain much performance, but you save a number transaction IDs?

**Comment by asimrp** [comment]
@andreasscherbaum no transaction is being saved.  The code is only refactored so that commit and start of a transaction is inside `ReindexRelationList()` rather than around every call to this function.

**Comment by ashwinstar** [comment]
Looks good and much cleaner.

**Comment by asimrp** [comment]
Thank you Heikki for reporting the bug.  Pushed to master.

**Pull request closed without merging**
