### PR TITLE
Stablize regression tests of dispatcher.

### PR DESCRIPTION
**Pull request by eurekaka**
Signed-off-by: Pengzhou Tang <ptang@pivotal.io>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@eurekaka Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1409)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1409) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@eurekaka Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1409)!

**Comment by pengzhout** [comment]
LGTM, thanks

**Comment by xiong-gang** [comment]
+1

**Comment by eurekaka** [comment]
Merged, thanks for the review.

**Pull request closed without merging**
