### PR TITLE
[6X] Allow non-standby mode in recovery.conf

### PR DESCRIPTION
**Pull request by usernamedt**
Hi!

GP 6X now has the PITR available thanks to [this PR](https://github.com/greenplum-db/gpdb/pull/12076). However,  Greenplum cluster forbids a restore from a physical backup, because `standby_mode = off` setting is not allowed. Full details are in [this issue](https://github.com/greenplum-db/gpdb/issues/12419).

I propose to restore [the original](https://github.com/postgres/postgres/blob/ed3e1663c031e82def8c50ef31ee704777059459/src/backend/access/transam/xlog.c#L5302) Postgres `restore_command` behavior, i.e. allow the `standby_mode = off` in recovery.conf.

Thanks!

### CODE REVIEW

**Review by ashwinstar — COMMENTED** [review]
LGTM. I see no problem with making this change, though would like to see test excising the code path under change to make sure it works and continues to work. Can you please add one?

**Comment by usernamedt** [comment]
> LGTM. I see no problem with making this change, though would like to see test excising the code path under change to make sure it works and continues to work. Can you please add one?

Sure, I'll do it shortly.

**Comment by usernamedt** [comment]
I included the `recovery` tests folder to the Makefile and added the new test `src/test/recovery/t/101_non_standby_recovery.pl`.

The existing `010_logical_decoding_timelines.pl` test seems to be not working so I removed it. 

Can someone please share the Concourse CI error? I don't have access to it.

**Comment by soumyadeep2007** [comment]
Note: this does not need to go into master as this was already fixed for master in [commit](https://github.com/greenplum-db/gpdb/commit/77761627c31e22f0ec21208b7cfa39aafdbba535#diff-c1cb3ab2a19606390c1a7ed00ffe5a45531702ca5faf999d401c548f8951c65bR5431-R5432):

**Comment by usernamedt** [comment]
> @usernamedt Thank you for your continued contributions!
> 
> I have polished the test a little, squashed the commits and expanded on the commit message. This looks ready to go in now, once we have a green pipeline. I will chat with the necessary stakeholders to prioritize merging this.

That's great, thanks!

**Pull request merged**
