### PR TITLE
Fix interconnect hung issue

### PR DESCRIPTION
**Pull request by pengzhout**
We hit interconnect hung issue many times in many cases, all have
    the same pattern: the downstream interconnect motion senders keep
    sending the tuples and they are blind to the fact that upstream
    nodes have finished and quitted the execution earlier, the QD
    then get enough tuples and wait all QEs to quit which cause a
    deadlock.

    Many nodes may quit execution earlier, eg, LIMIT, HashJoin, Nest
    Loop, to resolve the hung issue, they need to stop the interconnect
    stream explicitly by calling ExecSquelchNode(), however, we cannot
    do that for rescan cases in which data might lose, eg, commit
    2c011ce4c. For rescan cases, we tried using QueryFinishPending to
    stop the senders in commit 02213a731 and let senders check this
    flag and quit, that commit has its own problem, firstly, QueryFini
    shPending can only set by QD, it doesn't work for INSERT or UPDATE
    cases, secondly, that commit only let the senders detect the flag
    and quit the loop in a rude way (without sending the EOS to its
    receiver), the receiver may still be stuck inreceiving tuples.

    This commit revert the QueryFinishPending method firstly.

    To resolve the hung issue, we move TeardownInterconnect to the
    ahead of cdbdisp_checkDispatchResult so it guarantees to stop
    the interconnect stream before waiting and checking the status
    of QEs.

    For UDPIFC, TeardownInterconnect() remove the ic entries, any
    packets for this interconnect context will be treated as 'past'
    packets and be acked with STOP flag.

    For TCP, TeardownInterconnect() close all connection with its
    children, the children will treat any readable data in the
    connection as a STOP message include the closure operation.

    A test case is not included, both commit 2c011ce4c and 02213a731
    contain one.

### CODE REVIEW

**Comment by pengzhout** [comment]
There is one problem, following commit 76cbfcdf3a0dff3f029ca079701418b861ce86c8 always call ExecShutdownNode() after ExecutePlan()'s loop, so for query like: fetch 3 from cursor1, we might shutdown the interconnect too eailer, need to verify this problem.

**Comment by pengzhout** [comment]
> There is one problem, following commit 76cbfcdf3a0dff3f029ca079701418b861ce86c8 always call ExecShutdownNode() after ExecutePlan()'s loop, so for query like: fetch 3 from cursor1, we might shutdown the interconnect too eailer, need to verify this problem.

Recheck all the following commits about ExecShutdownNode() since 9.6, the API seems to be specially designed for the parallel mechanism, we better not mess the interconnect with it up, it can work in the current version, but once we merge to a higher version, it must be a problem.

I want to follow the idea that shutdown the interconnect when a plan is really finished (no more tuples needed from interconnect), I might need to implement a similar function (ExecSquelchNode cannot descend into motion sometimes) and put it in the proper place or I am thinking tearing down interconnect before checking the dispatching results.

**Comment by pengzhout** [comment]
As mentioned in the other day, using ExecShutdownNode() to stop interconnect is not a good idea, I try to resolve interconnect hung issue by move TeardownInterconnect to the ahead of cdbdisp_checkDispatchResult so it guarantees to stop the interconnect stream before waiting and checking the status of QEs.

force updated the patch

**Comment by baobao0206** [comment]
If we call 'TeardownInterconnect' in QD, QD will send stop message to QEs. But if the QE hang in 'receiveChunksUDPIFC', sending a stop message still can not resolve the hang issue.

**Comment by pengzhout** [comment]
On Wed, Apr 1, 2020 at 5:51 PM Jinbao Chen <notifications@github.com> wrote:

> If we call 'TeardownInterconnect' in QD, QD will send stop message to QEs.
> But if the QE hang in 'receiveChunksUDPIFC', sending a stop message still
> can not resolve the hang issue.
>

We need to know that the downstream senders will not always starve the
upstream receivers unless there are some bugs somewhere.

**Comment by pengzhout** [comment]
The senders get enough tuples or get no more tuples, it will end the stream
and let the receivers known.

**Comment by pengzhout** [comment]
Thanks for the review, merged.

**Pull request merged**
