### PR TITLE
Retry monitoring pulse if there's a hiccup

### PR DESCRIPTION
**Pull request by cjcjameson**
There's retry logic within the monitoring pulse script, but we still
occasionally get hiccups (just network because the monitoring lasts for
a while).

Signed-off-by: Marbin Tan <mtan@pivotal.io>

### CODE REVIEW

**Comment by cjcjameson** [comment]
This would have helped https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/gpdb_master/jobs/MU_gpexpand/builds/23 not error out.

No demo pipeline because there isn't much to see. [Here's the docs about the feature](http://concourse.ci/retry-step.html); we've tested that the pipeline can be set successfully

**Comment by ashwinstar** [comment]
Would be helpful to have more clear explanation in commit message why this is needed or better than just increasing retry time-out in current pulse-scripts.

**Comment by cjcjameson** [comment]
@tom-meyer @schubert I don't recall quite well enough -- do you remember why having the retry logic both in the pulse scripts and `attempts: 2` is helpful?

**Comment by ashwinstar** [comment]
Anything happening here further ?

**Comment by schubert** [comment]
The retry logic in the pulse scripts is because we get intermittent network
hiccups between pulse and AWS but everything is fine if we just try again
shortly to fetch log details. No sense in restarting a multi-hour job
because of that. The concourse retry's are a second safety net although we
likely shouldn't do that and just depend on the pulse scripts to retry only
for network blips.

**Comment by cjcjameson** [comment]
I think the particular issue we saw might have been a Garden (underlying container) hiccup, rather than a pure networking hiccup, so having the retry at a different level might be better.

However, this hasn't come up in the past 2 weeks, and you're right that we could just increase the value here to cover most cases: https://github.com/greenplum-db/gpdb/blob/master/ci/pulse/api/lib/pulse_proxy.rb#L6

I'm ambivalent. Closing; we can re-open if necessary. The pipeline file would need to be updated anyway (it's no longer easily rebase-able), so if we want to rekindle this idea, we should just reimplement it.

**Comment by cjcjameson** [comment]
The following "orange" failures might have a good cause, related to known turbulence in the concourse system or a pipeline change. But I think having the `attempts: 2` would actually recover gracefully from this sort of turbulence, so I'm reopening.

https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/gpdb_master/jobs/MU_gptransfer-5x-to-5x/builds/143
https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/gpdb_master/jobs/MU_backup-restore/builds/77
https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/gpdb_master/jobs/cs-walrepl-multinode/builds/173

**Comment by ashwinstar** [comment]
Okay lets have it if helps cut turbulence, doesn't harm anyways.

**Pull request merged**
