### PR TITLE
Enable -Werror=uninitialized

### PR DESCRIPTION
**Pull request by dsharp-pivotal**

### CODE REVIEW

**Comment by dsharp-pivotal** [comment]
This warning is apparently still present in vacuum.c, which I missed in local testing.

**Comment by amilkh** [comment]
+1 as this is super valuable (although my opinion might have less weight on the technical side as I'm not familiar with the touched files)

**Comment by hlinnaka** [comment]
Huh, why do we have both `acx_pthread.m4` and `ax_pthread.m4`?

I'm not sure this is worth the trouble. You get different compiler warnings depending on compiler versions,  optimization level, and compiler options.

Can we all just be vigilant on not introducing new compiler warnings?

**Comment by dsharp-pivotal** [comment]
On Tue, Nov 14, 2017 at 9:44 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> Huh, why do we have both acx_pthread.m4 and ax_pthread.m4?
>
Yeah, not sure. Only ACX_PTHREAD is used, too. I just changed both for
consistency.

> I'm not sure this is worth the trouble. You get different compiler
> warnings depending on compiler versions, optimization level, and compiler
> options.
>
> Can we all just be vigilant on not introducing new compiler warnings?
>

Evidence points to "no", since there are warnings.

**Comment by amilkh** [comment]
+1 again. Paired with David, he explained it to me technically, and it looks good!

We also added some commits to fix some maybe-uninitialized warnings that started appearing in Travis and Concourse.

**Comment by ashwinstar** [comment]
This commit 3002f7fe5e40b3e4dafdc5becdec19b33d33a700 portrays a example of the concern. As these warnings are not seen by most of the folks and is specifically been seen with `GCC 6.2.0` as commit mentions.

So, for solving such kind of warnings if don't have easy local environment where it happens becomes very tricky to fix and holds up CI.

**Comment by jchampio** [comment]
> So, for solving such kind of warnings if don't have easy local environment where it happens becomes very tricky to fix and holds up CI.

Agreed, but holding up the CI is a feature of `-Werror`, not a bug. This correctly puts the pain where it's supposed to be -- it's hard to reproduce CI failures, and the cost of failures is high, so let's fix *those* things -- instead of just ignoring warnings. Otherwise we all wait until someone feels like doing a "cleanup warning" sweep. :grin:

**Comment by dsharp-pivotal** [comment]
On Tue, Nov 14, 2017 at 11:36 AM, Ashwin Agrawal <notifications@github.com>
wrote:

> This commit 3002f7f
> <https://github.com/greenplum-db/gpdb/commit/3002f7fe5e40b3e4dafdc5becdec19b33d33a700>
> portrays a example of the concern. As these warnings are not seen by most
> of the folks and is specifically been seen with GCC 6.2.0 as commit
> mentions.
>
> So, for solving such kind of warnings if don't have easy local environment
> where it happens becomes very tricky to fix and holds up CI.
>
In that case in particular, the warning seems, afaict, to be an actual
problem, though: xrecoff and xlogid are indeed only set if type is 'w'. So
holding up CI might the right thing to do.

If a dev's local env doesn't show the warning, that doesn't mean the
problem doesn't need to be addressed. The warning can usually be addressed
by looking at the error message on CI as well. But it's true that they
won't be able to verify the fix without sending it to CI or setting up
their local environment to match.

In general, I've found that warnings indicate actual problems worth fixing
(usually involving undefined behavior or undefined values), so treating
them as errors means the code gets better.

**Comment by ashwinstar** [comment]
On Tue, Nov 14, 2017 at 11:51 AM, David Sharp <notifications@github.com>
wrote:

>
> In general, I've found that warnings indicate actual problems worth fixing
> (usually involving undefined behavior or undefined values), so treating
> them as errors means the code gets better.
>

No way denying that fact and we are in agreement on it. I had cleaned-up
whole bunch of warnings myself in past to help building clean and spot any
new ones if introduced.

Just wish to surface concerns to see we can address them someway. Like
similar to ERRORS which are consistent across compilers and never had
issues with not hitting them locally but only on CI. Is there some
recommendations / possibilities where a warning on CI can be replicated in
local env irrespective of env / compiler and verified with ease when needed.

**Comment by amilkh** [comment]
> Is there some recommendations / possibilities where a warning on CI can be replicated in
local env irrespective of env / compiler and verified with ease when needed.

@ashwinstar I guess the closest way is to do `fly hijack` into the container (although only Pivotal employees are allowed to do this). I think if this becomes a big issue, people will voice their concerns and we can solve it then, if they have trouble to use the same compilers.

**Comment by ashwinstar** [comment]
On Tue, Nov 14, 2017 at 1:51 PM, Amil Khanzada <notifications@github.com>
wrote:

> Is there some recommendations / possibilities where a warning on CI can be
> replicated in
> local env irrespective of env / compiler and verified with ease when
> needed.
>
> @ashwinstar <https://github.com/ashwinstar> I guess the closest way is to
> do fly hijack into the container (although only Pivotal employees are
> allowed to do this). I think if this becomes a big issue, people will voice
> their concerns and we can solve it then, if they have trouble to use the
> same compilers.
>

Sure we have already seen one side of the coin, lets flip it and try how
other side feels. If painful can be revisited. +1 go for it.

**Comment by d** [comment]
> Is there some
> recommendations / possibilities where a warning on CI can be replicated in
> local env irrespective of env / compiler and verified with ease when needed.

Ashwin and I spoke offline, for posterity, here's my answer:
There's a best-effort thing that I do, which is to run the compiler from the _same release series_ ("major version" in GCC-speak, e.g. 4.8 and 4.9 are considered two release series, but 7.0 and 7.1 are considered within the same release series). For example, on macOS with homebrew:

```
brew install gcc@6
./configure CC='ccache gcc-6' CXX='ccache g++-6'
make
```

Would give me the same (mostly) warnings as CI today.

Similar things can be done on other OS, e.g. `pkg install lang/gcc6`

**Comment by amilkh** [comment]
Looks like only Travis warnings turned errors are stopping us from merging this PR.
It's running with `gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4` and `./configure --with-openssl --with-ldap --with-libcurl --prefix=${TRAVIS_BUILD_DIR}/gpsql --with-apr-config=${TRAVIS_BUILD_DIR}/tools/bin/apr-1-config --disable-orca --disable-gpcloud --enable-pxf` and thus generating `-Werror=maybe-uninitialized`s that the newer version of gcc used by Concourse (6.2.0) is smart enough to infer otherwise.

Any idea how hard it would be to upgrade Travis's gcc version?
@edespino @kmacoskey 

Also, here is a link to the out-of-date wiki page:
https://github.com/greenplum-db/gpdb/wiki/Travis-Continuous-Integration-(CI)

**Comment by dsharp-pivotal** [comment]
I added a commit to update the GCC version we use on Travis, so now it's passing on Travis, and should pass again on Concourse (though it's flaking now). If there are no objections, I'll push this.

**Comment by amilkh** [comment]
With some commits merged from Postgres 8.4, Concourse has started failing on compiling gpdb with `-Werror=uninitialized`. This is good and bad news because we are now exposing "bad" code with `maybe-uninitialized` warnings in upstream Postgres code.

**1. dbcommands.c**
The warning/error: https://travis-ci.org/greenplum-db/gpdb/builds/305400210#L2535
The fix:
```diff
@@ createdb(CreatedbStmt *stmt)
    int         src_encoding;
-   char       *src_collate;
-   char       *src_ctype;
+   char       *src_collate = NULL;
+   char       *src_ctype = NULL;
    bool        src_istemplate;
```
Latest upstream code (never fixed!):
https://github.com/postgres/postgres/blob/master/src/backend/commands/dbcommands.c#L106

**2. pg_dumpall.c**
The warning/error: https://travis-ci.org/greenplum-db/gpdb/builds/305996095#L3786
The fix:
```diff
@@ dumpCreateDB(PGconn *conn)
 {
    PQExpBuffer buf = createPQExpBuffer();
-   PGresult   *res;
+   PGresult   *res = NULL;
    int         i;
```
Latest upstream code (never fixed!):
https://github.com/postgres/postgres/blob/master/src/bin/pg_dump/pg_dumpall.c#L1323

What do you guys suggest? A few options I see:
1. Fix the warnings. This means that every time we cherry-pick newer upstream commits, there will be merge conflicts. Bad news for the Postgres Merge team: @jchampio @hlinnaka @danielgustafsson 
2. Don't fix and somehow exclude `maybe-uninitialized` warnings from upstream Postgres from breaking our build. David said this is likely not possible.
3. Fix in gpdb and attempt to do so also in upstream Postgres code 😈 
4. Drop this PR entirely and compile gpdb without `-Werror=uninitialized` :(

**Comment by jchampio** [comment]
The second case is 100% a mismerge by me; there's nothing to fix upstream because upstream has never had that missing code path. It's looking like the first case might be a mismerge as well?

We don't want to initialize to `NULL` (there should be code down below that performs the initialization), but in any case this pretty much proves that `-Werror=uninitialized` is helpful/necessary. Option 1 all the way, and I will see if I can fix these two pieces today. Thanks!

**Comment by hlinnaka** [comment]
On 11/23/2017 12:30 AM, Amil Khanzada wrote:
> With some commits merged from Postgres 8.4, Concourse has started failing on compiling gpdb with `-Werror=uninitialized`. This is good and bad news because we are now exposing "bad" code with `maybe-uninitialized` warnings in upstream Postgres code.
> 
> **1. dbcommands.c**
> The warning/error: https://travis-ci.org/greenplum-db/gpdb/builds/305400210#L2535
> The fix:
> ```diff
> @@ createdb(CreatedbStmt *stmt)
>      int         src_encoding;
> -   char       *src_collate;
> -   char       *src_ctype;
> +   char       *src_collate = NULL;
> +   char       *src_ctype = NULL;
>      bool        src_istemplate;
> ```
> Latest upstream code (never fixed!):
> https://github.com/postgres/postgres/blob/master/src/backend/commands/dbcommands.c#L106

The get_dbinfo() call always fills in src_collate and src_ctype, or it 
returns false. And if it returns false, we throw an error here. There is 
no bug here.

- Heikki

**Comment by jchampio** [comment]
> The get_dbinfo() call always fills in src_collate and src_ctype, or it
returns false. And if it returns false, we throw an error here.

Whoops, that's what I get for skimming. Maybe the compiler can't figure out the pg_unreachable? In that case, maybe a longer conversation is in order once everyone's back after holiday.

My personal preference is still to fix warnings; I think the advantage of catching mistakes outweighs the merge hazards we will end up adding.

**Comment by amilkh** [comment]
Nice! Let's do fix it in gpdb. Sounds like it's the compiler not being
smart enough.

Jacob, if you have a proposed fix, please jot it down and we can push it to
the branch next week.

2017年11月22日水曜日、Jacob Champion<notifications@github.com>さんは書きました:

**Comment by amilkh** [comment]
Btw, do note that Concourse also build failed on those warnings (on a
previous run of the PR pipeline for this PR), not just Travis, so gcc
version upgrading again on Travis won't help.

2017年11月22日水曜日、Amil Khanzada<akhanzada@pivotal.io>さんは書きました:

**Comment by dsharp-pivotal** [comment]
I suspect it's not the PG_UNREACHABLE, but that it is unable to connect the return value of get_db_info() to the initialization of src_ctype. We may never know without a gcc expert.

@jchampio Everything went green with the changes we have. Do you still want to fix the warnings you were talking about in a different way?

**Comment by jchampio** [comment]
@dsharp-pivotal The second issue (pg_dumpall.c) needs to be solved via #3962, which I can merge once the master pipeline is feeling better. I have no particular opinion on the first warning.

**Comment by amilkh** [comment]
@jchampio @asimrp @hlinnaka we've fixed the warning for **1. dbcommands.c** on the gpdb side and finally merged this!
https://github.com/greenplum-db/gpdb/pull/3871/commits/1cf2972d59fea7917d66135b8ca1ad17521ed7a3

@hlinnaka do you think it's possible to make the same change to dbcommands.c on upstream Postgres code? I'd love to be a part of that process!

**Comment by hlinnaka** [comment]
On 30/11/17 02:53, Amil Khanzada wrote:
> @hlinnaka do you think it's possible to make the same change to
> dbcommands.c on upstream Postgres code? I'd love to be a part of that
> process!
Do you see those warnings on Postgres master? If you do, sure, send a 
patch to pgsql-hackers.

- Heikki

**Comment by amilkh** [comment]
Note that merging this PR had caused compilation to start failing on GPDB builds without `--disable-gpcloud` in their `./configure`. The below PR fixes this:
https://github.com/greenplum-db/gpdb/pull/4018

Also see discussion on gpdb-dev:
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/Ne_fAPXc5rw

**Pull request merged**
