### PR TITLE
pgstattuple: support auxiliary system heap relations to be as input arguments for bloat estimation functions

### PR DESCRIPTION
**Pull request by maksm90**
## Problem description
By now auxiliary system relations of appendonly table such as block directory, aosegments and visibility map are not supported by bloat estimation functions `pgstattuple()` and `pgstattuple_approx()` of `pgstattuple` extension despite of they are regular heap relations. This is because those relations have relkind value different from regular `RELKIND_RELATION` value. As a consequence, there is no way to precisely estimate bloat for those relations. The problem deteriorates further by fact that the planner statistics isn't gathered for those relations that makes it impossible to estimate bloating via `gp_toolkit.gp_bloat_expected_pages` view.

The current fix eliminates this defect. But the local execution of `pgstattuple` function call is meant in current version of patch. To execute it cluster-wide it's necessary to use `gp_dist_random('gp_id')` call, e.g., the `pgstattuple` call for block directory relation might be following:
```
select gp_segment_id, (pgstattuple('<blkdir_relation>')).*
from gp_dist_random('gp_id');
```
In general, there no problem to add new functions that encapsulate the query above and thereby support distributed execution of functions in `pgstattuple` extension. But I would like to get feedback about necessity of these new functions.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by zhangh43** [comment]
Thanks for the contribution!

**Comment by ashwinstar** [comment]
This PR in current state seems is applicable for 6X_STABLE. For master branch will have to rebase and modify it slightly to match current code.

**Comment by maksm90** [comment]
@ashwinstar , thanks for the note.
I have rebased patch and fixed output in expected file pulled out from vanilla PostgreSQL related with `block_size` value to pass regression test.

**Comment by asimrp** [comment]
Would it be better to use the `table_beginscan_analyze()`, `table_scan_analyze_next_block()` and `table_scan_analyze_next_tuple()` interface to collect dead and live rows?

**Comment by maksm90** [comment]
Hi @asimrp 

> Would it be better to use the table_beginscan_analyze(), table_scan_analyze_next_block() and table_scan_analyze_next_tuple() interface to collect dead and live rows?

Do you mean the counting of live and dead rows under iterative `table_scan_analyze_next_tuple` calls that values further passes to stats collector [under `do_analyze_rel`](https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/analyze.c#L976-L977)?
But the problem of this solution is the auxiliary relations of AO table are not subject of analyze routine. And statistics gathered by `analyze` is not precise and comprehensive compared to results from functions of `pgstattuple` extension.

**Comment by asimrp** [comment]
What makes me uncomfortable about current patch is the fact that more code that caters to all relations (pgstat contrib module) needs to be aware of AO-specific relkinds.  If it is easy enough to avoid it, great!  If not, I'm fine with merging the current patch because the problem I'm trying to highlight is beyond the scope of this patch.

Code outside the append-optimized table AM implementation should treat the auxiliary tables as simply relations with RELKIND_RELATION.  Otherwise, things get difficult to maintain as well as comprehend.  E.g. consider `RELKIND_HAS_STORAGE` macro.  It should return true for aoseg, aoblckdir and aovisimap tables but currently it doesn't. There ought to be a better way to identify auxiliary tables than having to define new relkinds.  Additional context: @gkokolatos originally brought this problem to my attention when we were working merging table AM API from PostgreSQL v12 into Greenplum.

**Comment by asimrp** [comment]
Thank you @maksm90 for entertaining my suggestion and you are right, `do_analyze_rel` doesn't directly fit in.  What I had in mind is to change `pgstat_heap()` to something like this:
```C
    scan = table_beginscan_analyze(rel);
    slot = table_slot_create(rel, NULL);

    nblocks = hscan->rs_nblocks;    /* # blocks to be scanned */

    /* scan the relation one block at a time */
    while (block < nblocks)
    {
        CHECK_FOR_INTERRUPTS();

	if (table_scan_analyze_next_block(scan, block, NULL))
        {
            while (table_scan_analyze_next_tuple(scan,
                                                 OldestXmin,
                                                 &stat.tuple_count,
                                                 &stat.dead_tuple_count,
                                                 slot))
            {
                /* live tuple is returned in slot, compute its length */
            }

            /*                                                                                                                                                                                                                                
             * table AM API should provide a way to get free space in current                                                                                                                                                                 
             * block, pgstat contrib module shouldn't do any arithmetic based                                                                                                                                                                 
             * on PageHeader.                                                                                                                                                                                                                 
             */
        }
        block++;
    }

    table_endscan(scan);
```

**Comment by ashwinstar** [comment]
Just to clarify, @asimrp proposal is just how `pgstattuple` extension can be simplified or optimized and adopted to Table AM interface to be usable for non-heap AMs. It still doesn't help to address the reality of being not usable for auxiliary AO tables as they are heap tables still just due to different relkind extension can't be used.
Without changing auxiliary AO relations relkind and making them same as regular heap tables I don't see a way of avoiding this patch.

**Comment by maksm90** [comment]
@asimrp @ashwinstar , thanks for your useful notes.

> What makes me uncomfortable about current patch is the fact that more code that caters to all relations (pgstat contrib module) needs to be aware of AO-specific relkinds. 

Yes, agreed. Moreover, the `pgstattuple` extension is not a single place that requires to propagate check on AO-specific relkinds to achieve more full integration of auxiliary AO relations with functionality available for regular heap tables.

> Code outside the append-optimized table AM implementation should treat the auxiliary tables as simply relations with RELKIND_RELATION. Otherwise, things get difficult to maintain as well as comprehend. E.g. consider RELKIND_HAS_STORAGE macro. It should return true for aoseg, aoblckdir and aovisimap tables but currently it doesn't. There ought to be a better way to identify auxiliary tables than having to define new relkinds.

Unfortunately we are not able to avoid the rewriting of code fragments with check on RELKIND_RELATION to incorporate auxiliary AO relations into functionality. What we might to do is to specify the macros to check relation on having heap storage - smth like this:
```C
#define RELKIND_IS_HEAP(relkind) \
	((relkind) == RELKIND_RELATION || \
	 (relkind) == RELKIND_AOSEGMENTS || \
	 (relkind) == RELKIND_AOVISIMAP || \
	 (relkind) == RELKIND_AOBLOCKDIR)

#define RELKIND_IS_HEAP_CASE  RELKIND_RELATION:\
  case RELKIND_AOSEGMENTS: \
  case RELKIND_AOVISIMAP: \
  case RELKIND_AOBLOCKDIR
```

> Just to clarify, @asimrp proposal is just how pgstattuple extension can be simplified or optimized and adopted to Table AM interface to be usable for non-heap AMs.

Yes, I see. And I suppose it would be elegant solution for `pgstattuple` extension to count statistics for relations with any type of storage. But this change significantly divorces implementation of this extension with vanilla PostgreSQL one and IMO have to be proposed to and applied by PostgreSQL community.
Maybe it's reasonable to consider the current version of patch to 6X_STABLE branch but this one with table AM calls - to master branch via discussion with PostgreSQL community?

**Review by asimrp — APPROVED** [review]
I agree, there is not better alternative, let's merge this simple patch and see if pgstattuple can be made to use table AM API more effectively, by pursuing a patch upstream.

**Comment by maksm90** [comment]
> What we might to do is to specify the macros to check relation on having heap storage - smth like this:
#define RELKIND_IS_HEAP(relkind) \
	((relkind) == RELKIND_RELATION || \
	 (relkind) == RELKIND_AOSEGMENTS || \
	 (relkind) == RELKIND_AOVISIMAP || \
	 (relkind) == RELKIND_AOBLOCKDIR)

Upd: there is macro that determines whether relation is based on heap storage:
- in [6X_STABLE](https://github.com/greenplum-db/gpdb/blob/6.11.2/src/include/utils/rel.h#L341-L346) based on GPDB-specific `relstorage` attribute of `pg_class`
- in [master](https://github.com/greenplum-db/gpdb/blob/19cd1cf4b68faff2e29bc2fa884c480e4644cdb4/src/include/utils/rel.h#L408-L409) based on OID of AM handler.

> let's merge this simple patch and see if pgstattuple can be made to use table AM API more effectively, by pursuing a patch upstream.

Do you intend to merge the current version of patch to master or 6X_STABLE? If second option that I need to rebase this patch so it's applied.

I find useful to use the following macro:
```C
#define RELKIND_IS_HEAP  RELKIND_RELATION:\
  case RELKIND_AOSEGMENTS: \
  case RELKIND_AOVISIMAP: \
  case RELKIND_AOBLOCKDIR
```
in switch-case constructions in which RELKIND_RELATION macro was involved. @asimrp what do you think to add this macro to final patch?

**Comment by asimrp** [comment]
The fix is needed for both the branches - master and 6X.

Regarding the proposed macro RELKIND_IS_HEAP, defining it in the contrib module may be ok, if it improves readability, but I would refrain from defining it in backend and rather have the AO-specific relkinds removed.

**Comment by maksm90** [comment]
> The fix is needed for both the branches - master and 6X.

OK, I'll start a new PR to backport the patch to 6X.

> Regarding the proposed macro RELKIND_IS_HEAP, defining it in the contrib module may be ok, if it improves readability, but I would refrain from defining it in backend and rather have the AO-specific relkinds removed.

OK. It's just that I intended to add this macro into common `src/backend/catalog/pg_class_d.h` header file (near the macro definition of `RELKIND_HAS_STORAGE` because semantically they are close) to further use it in all future places where necessary to add AO-specific relkinds in switch-case statement.

**Comment by asimrp** [comment]
> OK, I'll start a new PR to backport the patch to 6X.

Great!  Thank you.

> It's just that I intended to add this macro into common src/backend/catalog/pg_class_d.h header file

Let's refrain from that change now and change it the right way once and for all when we get to it.

**Comment by ashwinstar** [comment]
Pushed to master via commit e595fc33a257b1ac48242b7fe66495cbb68e8dc7

**Pull request closed without merging**
