### PR TITLE
Fix memtuple forming bug when null-saved size is larger than 32763 bytes

### PR DESCRIPTION
**Pull request by pengzhout**
compute_null_save() is used to compute how many bytes a tuple saved by using
nullbitmap, formerly the return value is short type and can be easily overflowed
which will corrupt memtuples and cause sigsegv.

### CODE REVIEW

**Comment by yydzero** [comment]
could we add test case to protect this issue?

**Comment by armenatzoglou** [comment]
Great work! I agree with @yydzero, can you please add an icg test? Other than that, it LGTM.

**Comment by foyzur** [comment]
LGTM, would like some tests as @yydzero and @armenatzoglou mentioned.

**Comment by pengzhout** [comment]
@asimrp Hi asim, each element of nullsaves array represent  4 columns can save, the maximun bytes a column can save is 8 bytes which means the max vaule of nullsaves element is 32 bytes, so short type is enough for nullsaves.

**Comment by asimrp** [comment]
Got it, thank you for the explanation.

**Comment by pengzhout** [comment]
added a ICG case

**Comment by pengzhout** [comment]
Thanks for review, pushed

**Pull request closed without merging**
