### PR TITLE
Updatable cursor support

### PR DESCRIPTION
**Pull request by litzell**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@litzell Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1677)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1677) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by mkiyama** [comment]
Couple of questions
This should also have mention in the release notes. Is that different commit?
Is an example a separate commit?

**Comment by pivotal-issuemaster** [comment]
@litzell Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1677)!

**Comment by dyozie** [comment]
@litzell - could you rebase your fork to update this PR?

**Pull request closed without merging**
