### PR TITLE
First shot at merging SPI 64 bit changes for pl/Perl

### PR DESCRIPTION
**Pull request by andreasscherbaum**
Still needs testing

### CODE REVIEW

**Comment by ashwinstar** [comment]
@andreasscherbaum can we bring all these SPI 64 bit PRs to completion, seems 3 of them dangling right now ?

**Comment by ivannovick** [comment]
+1 would be nice to get this done

On 1/20/18, Ashwin Agrawal <notifications@github.com> wrote:
> @andreasscherbaum can we bring all these SPI 64 bit PRs to completion, seems
> 3 of them dangling right now ?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/greenplum-db/gpdb/pull/4153#issuecomment-359199520


-- 
Ivan Novick, Product Manager Pivotal Greenplum
inovick@pivotal.io --  (Mobile) 408-230-6491
https://www.youtube.com/GreenplumDatabase

**Comment by andreasscherbaum** [comment]
It's thee different languages. So 3 different PR.
Yes, I'm working on it, bit busy right now :-(

**Comment by andreasscherbaum** [comment]
It turns out that Perl can't handle 64 bit. The internally used av_extend() function is limited to 32 bit, and the PR makes an effort to ensure that the error is handled properly. Upstream works the same way, and I don't expect any users to reach this limit anytime soon. The existing users who ran into this problem all use pl/pgSQL.

This leaves two questions:
1): Should this case be tested?
2): Should this be documented, and if yes, where?

**Pull request closed without merging**
