### PR TITLE
Remove obsolete internal functions to avoid oid conflict with FDW.

### PR DESCRIPTION
**Pull request by yydzero**
commit 2cf8afe5d11377faaf5721b2c2f0089436abf704
Author: Peter Eisentraut <peter_e@gmx.net>
Date:   Sun Oct 5 17:33:17 2008 +0000

    Remove obsolete internal functions istrue, isfalse, isnottrue, isnotfalse,
    nullvalue, nonvalue.  A long time ago, these were used to implement the SQL
    constructs IS TRUE, etc.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
:-1: ..since this is an upstream commit, where possible please use `git cherry-pick <sha1>` and resolve the conflicts rather than re-doing the commit with the commit message included. This commit only has trivial conflicts so we should take it like that since preserving history will make the merge easier.

**Comment by yydzero** [comment]
Initially I tried to use cherry-pick, while there are many strange stupid changes in pg_proc and another file which make me frustrated, so changed to this way.

if this is not suitable way for upstream merge, i will try cherry-pick again, and try to resolve above issue ...

**Comment by danielgustafsson** [comment]
Yes please, that is much appreciated.

**Comment by hlinnaka** [comment]
FWIW, I actually prefer rewriting the commit message like @yydzero did here. It makes it more clear who did the backporting, and when. It also gives you the chance to add comments of your own, explaining possible differences from the original commit, and why it was backported.

**Comment by hlinnaka** [comment]
Putting the discussion on the commit message style aside, +1 for doing this.

**Comment by danielgustafsson** [comment]
> On 08 Nov 2016, at 12:59, Heikki Linnakangas <notifications@github.com> wrote:
> 
> FWIW, I actually prefer rewriting the commit message like @yydzero did here. It makes it more clear who did the backporting, and when. It also gives you the chance to add comments of your own, explaining possible differences from the original commit, and why it was backported.

Thinking about this I come down on the my perceived difference between a backport and a cherry-pick:

When an upstream commit applies with no, or only superficial/trivial, conflicts then I consider it a cherry-pick and prefer to get the original author and commitmessage (as per git cherry-pick).

When an explanation of a difference in implementation is warranted (or just a good idea to clarify something), I consider it a backport which in itself is a separate piece of work from the original commit. In this case I agree that it should be a rewritten commit with the original commit sha and message quoted in the commit message.

**Comment by danielgustafsson** [comment]
> On 08 Nov 2016, at 13:02, Heikki Linnakangas <notifications@github.com> wrote:
> 
> Putting the discussion on the commit message style aside, +1 for doing this.

Here we are absolutely in agreement, +1 on this change.

**Comment by yydzero** [comment]
Thanks for review, merged.

**Pull request merged**
