### PR TITLE
Allow more types of index scan on ao tables

### PR DESCRIPTION
**Pull request by fanfuxiaoran**
Considering the cost of random page access on an ao table is high, an ao table supports only two types of index scan on it - index_only and bitmap  index.

That kind of makes sense，but restricts the planner from using index scan on ao tables to achieve better performance. For example, can not support using ivfflat index to do approximate nearest neighbor search on ao tables, which can have better performance than seq scan in some situations

Adding additional cost for ao tables' random page scan when calculating index path cost and removing the restriction of index type on ao tables to solve above issue.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by kainwen** [comment]
Seems we have opened a too wide door. Refer to previous closed PR: https://github.com/greenplum-db/gpdb/pull/5450
it was reviewed by many engineers and got approved but finally decided not to merge due to cost model.

AO|AOCS (especially with compression) is very bad for randomly scan. We need to consider all these things.

**Comment by fanfuxiaoran** [comment]
> 



> Seems we have opened a too wide door. Refer to previous closed PR: #5450 it was reviewed by many engineers and got approved but finally decided not to merge due to cost model.
> 
> AO|AOCS (especially with compression) is very bad for randomly scan. We need to consider all these things.

Thanks for your comment which is quiet helpful to us.  We will catch up on the previous pr and dig into that.

**Comment by fanfuxiaoran** [comment]
> Just to start with we may open the door only for indexes which don't support bitmap index scan (having `amgetbitmap = NULL`) for now (like ivfflat from pgvector). 

@ashwinstar Thanks for your suggestion, that's a great idea to only support the index on ao tables that does not support bitmaps index.

>Till support for bitmap index scan is added for these indexes.

  But I'm not sure that the index such ivfflat can support the bitmap index as it is only used for `order by ` queries .

**Comment by fanfuxiaoran** [comment]
Have discussed this with @soumyadeep2007, and it seems that it is not necessary to change the cost model in this pr as it aims to enable indexes in pgvector such as ivfflat.  Have opened another pr for it [https://github.com/greenplum-db/gpdb/pull/16231].  In terms of the cost model for AO tables, will be discussed and optimized in the future.

**Pull request closed without merging**
