### PR TITLE
Revert getaddrs and gp_primarymirror changes

### PR DESCRIPTION
**Pull request by pivotal-mike**
This reverts the two commits b09c749b and 6d2a1f6 as reviewing the changes across now 3 PRs has become too difficult.  We will revert these commits and reapply changes from the start on the master branch and back-port to 5X_STABLE

### CODE REVIEW

**Comment by pivotal-mike** [comment]
@dyozie FYI - possible doc changes

**Comment by ashwinstar** [comment]
@pivotal-mike revert this as well please https://github.com/greenplum-db/gpdb/commit/a4a801881bf9bc4ea75a9715fd7d221bc6bc7fb8

**Comment by pivotal-mike** [comment]
@ashwinstar done

**Comment by dyozie** [comment]
@pivotal-mike I thought https://github.com/greenplum-db/gpdb/pull/4716 covered this?

**Comment by pivotal-mike** [comment]
@dyozie Quite likely?  More of a heads up

**Comment by dyozie** [comment]
Great.  And just fyi - the docs associated with this change are still in an unmerged PR, so reverting the code at this point shouldn't impact the docs at all.

**Comment by xiong-gang** [comment]
@pivotal-mike Should revert c1e148a489f16846798533744b3b34405a9d9c2d as well

**Comment by Eulerizeit** [comment]
@xiong-gang could you please revert that commit. If we wait till tomorrow we won't be able to release for 4-6 hours (or whatever the entire process takes)

**Pull request merged**
