### PR TITLE
Add test case for writable external table with more URIs than segments.

### PR DESCRIPTION
**Pull request by hlinnaka**
Seems like a good thing to test.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Good point. Actually, shouldn't we also throw a warning for gpfdist URLs with more locations than segments? They can't be queried until the cluster is expanded, either:
```
postgres=# create external table ret_too_many_uris(a text, b text) location(
  'gpfdist://foo.invalid:7070/ret.tbl1',  'gpfdist://foo.invalid:7070/ret.tbl2',
  'gpfdist://foo.invalid:7070/ret.tbl3',  'gpfdist://foo.invalid:7070/ret.tbl4',
  'gpfdist://foo.invalid:7070/ret.tbl5',  'gpfdist://foo.invalid:7070/ret.tbl6',
  'gpfdist://foo.invalid:7070/ret.tbl7',  'gpfdist://foo.invalid:7070/ret.tbl8',
  'gpfdist://foo.invalid:7070/ret.tbl9',  'gpfdist://foo.invalid:7070/ret.tbl10',
  'gpfdist://foo.invalid:7070/ret.tbl11', 'gpfdist://foo.invalid:7070/ret.tbl12',
  'gpfdist://foo.invalid:7070/ret.tbl13', 'gpfdist://foo.invalid:7070/ret.tbl14',
  'gpfdist://foo.invalid:7070/ret.tbl15', 'gpfdist://foo.invalid:7070/ret.tbl16',
  'gpfdist://foo.invalid:7070/ret.tbl17', 'gpfdist://foo.invalid:7070/ret.tbl18',
  'gpfdist://foo.invalid:7070/ret.tbl19', 'gpfdist://foo.invalid:7070/ret.tbl20'
) format 'text';
CREATE EXTERNAL TABLE
postgres=# select * from ret_too_many_uris ;
ERROR:  There are more external files (URLs) than primary segments that can read them. Found 20 URLs and 3 primary segments.
```

**Comment by hlinnaka** [comment]
And should we also throw that warning for writable external tables?

**Comment by danielgustafsson** [comment]
> On 13 Mar 2017, at 09:31, Heikki Linnakangas <notifications@github.com> wrote:
> 
> And should we also throw that warning for writable external tables?

I would say on both accounts, WET and gpfdist. Not sure why I didn’t include that in my commit but I can’t see any reason why not.

**Comment by hlinnaka** [comment]
Ok. I updated this PR to:

1. Also add a test case for a readable external table. It uses gpfdist, like the original writable external table, so you still don't get that WARNING. Per discussion, we should change the code to also throw the warning with gpfdist protocol, and with that change, these tests will also throw the warning. But I'll leave that code change for another PR.

2. Change the error message you got with a readable external table in ORCA, to match that you get without ORCA. Consistency is good, and it avoids having to have separate expected output files.

**Comment by ashwinstar** [comment]
@hlinnaka Seems ready to get this in ?

**Comment by ashwinstar** [comment]
@hlinnaka What's remaining here to get in ?

**Comment by Eulerizeit** [comment]
@hlinnaka seems like you can push this.

**Pull request merged**
