### PR TITLE
6X: Use a unicast IP address for motion sockets

### PR DESCRIPTION
**Pull request by divyeshddv**
This backports #9696 and follow-up refactor #13326, and follow-up test fixes #13351 and #13352 in order to reduce the number of ports consumed by interconnect sockets. We also had to backport commit 349bf7cc1a.

Co-authored-by: Soumyadeep Chakraborty <soumyadeep2007@gmail.com>

Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6x_ic_use_address

### CODE REVIEW

**Comment by divyeshddv** [comment]
Recommendation for reviewers: Review the first commit separately and last two commits together. (See attached image)
image

**Review by Aegeaner — APPROVED** [review]
LGTM

**Comment by Aegeaner** [comment]
Looks good, except for a CI failure inside the `check_motion_sockets` test : https://prod.ci.gpdb.pivotal.io/builds/1369853

**Comment by divyeshddv** [comment]
> Looks good, except for a CI failure inside the `check_motion_sockets` test : https://prod.ci.gpdb.pivotal.io/builds/1369853

Fixed, thanks!

**Pull request merged**
