### PR TITLE
Delete gpmapreduce code

### PR DESCRIPTION
**Pull request by ashwinstar**
It's decided that this functionality will not be provided for GPDB7 and forward. Hence, deleting the code for the same.

PR contains change to remove even documentation for the same (I am not sure I did the right modifications for the same @dyozie)

Also, `libyaml` was listed as required dependency for mapreduce so with it the check for this dependency is also going away. I see `gpfdist` doesn't have strong dependency on `libyaml` but if present enables some transformations. How do we wish to deal with that aspect? Do we wish to make `libyaml` required dependency for gpfdist or keep it optional the current way and leave it to chance? @adam8157 @huiliang-liu 

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by dyozie — APPROVED** [review]
Thanks @ashwinstar - the doc changes look good to me. We can do a follow-on search to make sure we've removed all references from the proprietary docs repo.

**Comment by adam8157** [comment]
Transforming External Data with gpfdist and gpload
https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-admin_guide-load-topics-transforming-xml-data.html

yaml is a required library for this feature we provide, currently Greenplum is compiled with it if the compiling env has it. I suppose it's fine.

**Comment by ashwinstar** [comment]
> Transforming External Data with gpfdist and gpload https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-admin_guide-load-topics-transforming-xml-data.html
> 
> yaml is a required library for this feature we provide, currently Greenplum is compiled with it if the compiling env has it. I suppose it's fine.

Do we really wish to leave it as a chance (hit or miss state)? What if new platform is added tomorrow which doesn't have this, then feature silently gets disabled for it.

**Comment by adam8157** [comment]
> Do we really wish to leave it as a chance (hit or miss state)? What if new platform is added tomorrow which doesn't have this, then feature silently gets disabled for it.

Good point, I have been there. It would be nice to require it directly.

**Comment by ashwinstar** [comment]
> > Do we really wish to leave it as a chance (hit or miss state)? What if new platform is added tomorrow which doesn't have this, then feature silently gets disabled for it.
> 
> Good point, I have been there. It would be nice to require it directly.

Done, added `libyaml` as required dependency for gpfdist.

**Review by adam8157 — APPROVED** [review]

**Pull request merged**
