### PR TITLE
Fix Shared Scan hang with subplan

### PR DESCRIPTION
**Pull request by charliettxx**
If a shared scan is in subplan, it may cause hang because in GPDB we dispatch subplan first and then dispatch
main plan next. Subplan and main plan cannot share a shared scan, disusing shared input scan could be a safe
and sensible workaround for this issue like 6X did https://github.com/greenplum-db/gpdb/pull/12730.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by charliettxx** [comment]
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-cte_hang-rocky8

**Review by interma — APPROVED** [review]
LGTM

**Comment by interma** [comment]
Thanks Haotian. This PR is good for me.

from previous https://github.com/greenplum-db/gpdb/issues/12701
> Master branch dose not have the issue (top commit https://github.com/greenplum-db/gpdb/commit/435cea1e2e722624c0e24ed550e909f683c035b3)

A little curious what causes it regression.
If you have time, you can take a look and do a verification.

**Comment by charliettxx** [comment]
thanks @interma review
from previous PR https://github.com/greenplum-db/gpdb/issues/12701, we got plan as below
```
postgres=# explain (COSTS OFF)
with cte1 as (select * from sisc1),
cte2 as (select * from sisc2),
cte3 as (select * from sisc3)
select * from cte1 where ( EXISTS ( select cte2.a from cte2 left join cte3 on (EXISTS ( select cte1.b from cte2))));
                              QUERY PLAN                              
----------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)
   InitPlan 2 (returns $1)  (slice2)
     ->  Nested Loop Left Join
           Join Filter: $0
           InitPlan 1 (returns $0)  (slice5)
             ->  Subquery Scan on cte2
                   ->  Materialize
                         ->  Gather Motion 3:1  (slice6; segments: 3)
                               ->  Seq Scan on sisc2
           ->  Materialize
                 ->  Gather Motion 3:1  (slice3; segments: 3)
                       ->  Subquery Scan on cte2_1
                             ->  Shared Scan (share slice:id 3:0)
                                   ->  Seq Scan on sisc2 sisc2_1
           ->  Materialize
                 ->  Materialize
                       ->  Gather Motion 3:1  (slice4; segments: 3)
                             ->  Seq Scan on sisc3
   ->  Result
         One-Time Filter: $1
         ->  Seq Scan on sisc1
 Optimizer: Postgres query optimizer
(22 rows)
```
cte2 do not share Shared Scan so it will not hit the issue.
I suppose https://github.com/greenplum-db/gpdb/pull/13838 change some behaviors of subquery especially on
targetlist in function `simplify_EXISTS_query()` and it hit the issue we meet now.

**Comment by kainwen** [comment]
@charliettxx this is to fix https://github.com/greenplum-db/gpdb/issues/15827, right?

**Comment by Aegeaner** [comment]
> > I suppose SubPlan can use shared plan but not InitPlan. Here seems we disallow more cases.
> 
> yes you're right, but it's a little hard and tricky to distinguish initplan&&subplan as we set `config->gp_cte_sharing` and now at least we could just guarantee no hang in such cases.

From `build_subplan()` we can see the condition of `splan->is_initplan` is:
```
(splan->parParam == NIL && subLinkType == EXPR_SUBLINK) ||
(splan->parParam == NIL && subLinkType == ARRAY_SUBLINK) ||
(splan->parParam == NIL && subLinkType == ROWCOMPARE_SUBLINK) ||
(splan->parParam == NIL && subLinkType == MULTIEXPR_SUBLINK)
```
, which means `un-correlated or undirect correlated plans of EXISTS, EXPR, ARRAY, ROWCOMPARE, or MULTIEXPR types can be used as initPlans.`

So the condition here should be 
```
config->gp_cte_sharing = splan->parParam != NIL ||
				!(subLinkType == ROWCOMPARE_SUBLINK ||
				 subLinkType == ARRAY_SUBLINK ||
				 subLinkType == EXPR_SUBLINK ||
				 subLinkType == EXISTS_SUBLINK);
```
But `splan->parParam` is not available yet here.

But at least we can remove the condition `IsSubqueryCorrelated(subquery) ||` here, to narrow down the influence:
```
if (Gp_role == GP_ROLE_DISPATCH)
	{
		config->gp_cte_sharing = 
				!(subLinkType == ROWCOMPARE_SUBLINK ||
				 subLinkType == ARRAY_SUBLINK ||
				 subLinkType == EXPR_SUBLINK ||
				 subLinkType == EXISTS_SUBLINK);
	}
```

**Review by Aegeaner — APPROVED** [review]
LGTM

**Pull request merged**
