### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by divyabhargov**
This adds some basic checklist that we tend to forget. This is not a complete list and may not cater to every feature. The hope is to have this catch some things we often forget and also keep the list short.

### CODE REVIEW

**Comment by kmacoskey** [comment]
Some possible additions:

If a pipeline change
  * Was the pipeline regenerated?
  * Was the production pipeline updated in Concourse?

**Comment by divyabhargov** [comment]
@kmacoskey I like your ideas, but I am also bearing in mind the open source developers outside of Pivotal who don't have the ability to set pipelines.

**Comment by kmacoskey** [comment]
Is the template solving a problem of outside developers making mistakes or solving the problem internal developers making mistakes?

**Comment by Eulerizeit** [comment]
On Thu, Nov 29, 2018 at 10:57 AM Kristofer Macoskey <
notifications@github.com> wrote:

> Is the template solving a problem of outside developers making mistakes or
> solving the problem internal developers making mistakes?
>
I hope, yes to both.

**Comment by kmacoskey** [comment]
Perhaps another thing to add to the check list:

  * Has the PR been reviewed and +1'ed by others?
  * Has there been enough time to be reviewed by others?
  * If the commits were not done by a pair, is this ok and why?

**Pull request merged**
