### PR TITLE
Remove step to build PL/Java from Makefile.

### PR DESCRIPTION
**Pull request by hsyuan**
This is an old version of PL/Java and the newer version is maintained in
a separate repo.

### CODE REVIEW

**Comment by hsyuan** [comment]
@davecramer @Eulerizeit @Chibin Please take a look.

**Comment by danielgustafsson** [comment]
Why not combine this with a `git rm -r gpAux/extensions/pljava/`?

**Comment by hsyuan** [comment]
Aha, good idea. In fact, we are planning to do this. Will add another
commit.

Thanks~
Haisheng Yuan

**Comment by Chibin** [comment]
If you're planning on removing the whole `gpAux/extentions/pljava`, you might want to remove other pljava related things in `gpAux/Makefile`

**Comment by hsyuan** [comment]
Yes, we will remove pljava related code in gpAux/Makefile too.

Thanks~
Haisheng Yuan

**Comment by asimrp** [comment]
How about some tests that seem to be using pljava?
Tests using pg_regress:
```
test/regress/bugbuster/sql/jdbc.sql
test/regress/sql/qp_misc_rio.sql
```

TINC tests:
```
test/tinc/tincrepo/mpp/gpdb/tests/package/language/pljava/*
```

The patch should also remove these tests because without pljava, I am assuming they will fail.

**Comment by Eulerizeit** [comment]
If there are test dependencies on PL/Java just make sure you're pointing to the correct repo when building it and then please don't package it. The packaged version will come from our pipeline.

**Comment by hsyuan** [comment]
@asimrp `test/regress/bugbuster/sql/jdbc.sql` is used for testing jdbc. We removed `pljava` related query in qp_misc_rio sql and output file.

@Eulerizeit We removed all the dependencies on PL/Java from gpdb repo. This is being tested in separately in the pljava pipeline I assume?

**Comment by d** [comment]
LGTM

**Pull request merged**
