### PR TITLE
Enforce constraints directly in the executor, even with ORCA.

### PR DESCRIPTION
**Pull request by hlinnaka**
This allows removing many alternative expected output files for ORCA.

The flag was added to ORCA in v2.48.0, so bump our dependency to that
version.

### CODE REVIEW

**Comment by hlinnaka** [comment]
At first I thought we could get rid of the AssertOp node in GDPB completely after this, but unfortunately not. It's also used to check that a subquery doesn't return more than one row, in some queries. We should change the error message for that to match the one you get without ORCA, so that we can eliminate some more ORCA-specific expected output files. But that's a separate task.

**Comment by bhuvnesh2703** [comment]
it is also used for checking cardinality for updated value during update..https://jira-pivotal.atlassian.net/browse/MPP-19883

**Comment by hlinnaka** [comment]
The concourse tests are failing to start, because it cannot find the new ORCA version. Is there something else that I need to do in the ORCA repository to make that work? Create a tag? A github release?

**Comment by bhuvnesh2703** [comment]
The latest build on ORCA concourse failed: https://ci.orca.pivotalci.info/teams/main/pipelines/gporca/jobs/orca_publish_tag/builds/197
appears to be due to missing module (not sure but shouldn't happen unless the image changed)..if it runs greens the tag and github release should get created

**Comment by vraghavan78** [comment]
@dhanashreek89 when you port it to 4.3 rather that passing in the value, can we have a GUC since existing customers have tests that will start failing when they upgrade ORCA version. GPDB 5 will have less of an issue.

**Comment by hlinnaka** [comment]
On 10/20/2017 07:50 PM, Venkatesh Raghavan wrote:
> @dhanashreek89 when you port it to 4.3 rather that passing in the
> value, can we have a GUC since existing customers have tests that
> will start failing when they upgrade ORCA version. GPDB 5 will have
> less of an issue.

Surely we're not porting this to 4.3, are we? If you must update 4.3 to 
the latest ORCA version, you can just pass "True" as the new flag to 
keep the old behavior.

- Heikki

**Comment by vraghavan78** [comment]
@hlinnaka that is also fine. We can hard code it to True.

**Comment by dhanashreek89** [comment]
> Surely we're not porting this to 4.3, are we? If you must update 4.3 to
the latest ORCA version, you can just pass "True" as the new flag to
keep the old behavior.
Correct. We will set to to true for 4.3.

**Comment by hlinnaka** [comment]
Pushed, after silencing the last regression failures caused by the error message difference.

**Pull request merged**
