### PR TITLE
Fix check for empty array of failed_binaries

### PR DESCRIPTION
**Pull request by bradfordboyle**

### CODE REVIEW

**Comment by bradfordboyle** [comment]
Dev pipeline here: https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-bboyle/jobs/compile_gpdb_ubuntu16_oss_abi/builds/1

**Comment by marksliva** [comment]
The check that was there before worked in most cases. The case that fails is when the array starts with an empty element. Did this actually happen at some point, or is this change mainly about making the check more robust? Either way, LGTM.
example:
```
array=('' bin/postgres)
if [ "${#array[@]}" -ne 0 ]; then
  echo "new way: array contains items"
fi
if [ -n "$array" ]; then
  echo "old way: array contains items"
fi

--- output of running above:
new way: array contains items
```

**Comment by bradfordboyle** [comment]
From @marksliva 
> The case that fails is when the array starts with an empty element. Did this actually happen at some point, or is this change mainly about making the check more robust?

This PR is needed to fix a failing job in 5X_STABLE: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/5X_STABLE/jobs/compile_gpdb_ubuntu16_oss_abi/builds/77

**Comment by d** [comment]
On Fri, Jun 28, 2019 at 8:47 AM Mark Sliva <notifications@github.com> wrote:
>
> The check that was there before worked in most cases. The case that fails is when the array starts with an empty element. Did this actually happen at some point, or is this change mainly about making the check more robust? Either way, LGTM.
> example:
>
> array=('' bin/postgres)
> if [ "${#array[@]}" -ne 0 ]; then
>   echo "new way: array contains items"
> fi
> if [ -n "$array" ]; then
>   echo "old way: array contains items"
> fi
>
> --- output of running above:
> new way: array contains items
>

In Bash, $array is equivalent to ${array[0]}. Consequently, an empty
array will lead to the evaluation of an unset variable in $array. We
usually run our Bash scripts with "set -o unset". I think that's the
context you've missed.

**Pull request merged**
