### PR TITLE
Bump gpdb default version to 7.0.0-alpha.0

### PR DESCRIPTION
**Pull request by amilkh**
If getversion is not able to determine a version from git then it uses
the version in configure.in (autconf).
configure was generated by running `autoreconf` after modifiying
configure.in.

Co-authored-by: Ben Christel <bchristel@pivotal.io>
Co-authored-by: David Sharp <dsharp@pivotal.io>
Co-authored-by: Amil Khanzada <akhanzada@pivotal.io>

### CODE REVIEW

**Comment by amilkh** [comment]
anybody know why 6.0.0-beta.1 AND 6.0.0-alpha.0 were both tagged on the commit: [bumped default version to 6.0.0-alpha.0](https://github.com/greenplum-db/gpdb/commit/d413c0ddcb3410930dccf25e4b8a93f6ce8d492a)?

**Comment by bradfordboyle** [comment]
> anybody know why 6.0.0-beta.1 AND 6.0.0-alpha.0 were both tagged on the commit: [bumped default version to 6.0.0-alpha.0](https://github.com/greenplum-db/gpdb/commit/d413c0ddcb3410930dccf25e4b8a93f6ce8d492a)?

They weren't tagged on the same commit:

```sh
$ git rev-list -n 1 6.0.0-beta.1
067fb8e43115bb087c872ee3d2269d869430263d

$ git rev-list -n 1 6.0.0-alpha.0
d413c0ddcb3410930dccf25e4b8a93f6ce8d492a
```

Here are the GitHub links: 
1. https://github.com/greenplum-db/gpdb/releases/tag/6.0.0-beta.1
2. https://github.com/greenplum-db/gpdb/releases/tag/6.0.0-alpha.0

**Comment by amilkh** [comment]
ah my mistake

**Comment by amilkh** [comment]
Thanks @danielgustafsson !

Actually cleaned up those and other references of "6.0.0" in the codebase.
Below is what remains after the latest changes.
```
 → ag "6\.0\.0"
gpdb-doc/markdown/pxf/access_hdfs.html.md.erb
26:<div class="note">In previous versions of Greenplum Database, you may have used the <code>gphdfs</code> external table protocol to access data stored in Hadoop. Greenplum Database version 6.0.0 removes the <code>gphdfs</code> protocol. Use PXF and the <code>pxf</code> external table protocol to access Hadoop in Greenplum Database version 6.x.</div>

gpdb-doc/dita/security-guide/topics/Authenticate.xml
101:                <codeph>10.6.0.0/16</codeph> for a larger one. An IPv6 address range might look like

gpdb-doc/dita/admin_guide/client_auth.xml
105:                    <codeph>10.6.0.0/16</codeph> for a larger one. An IPv6 address range might look

gpdb-doc/dita/admin_guide/external/pxf-overview.xml
10:      Greenplum Database version 6.0.0 removes the <codeph>gphdfs</codeph> protocol.

contrib/pg_upgrade/tablespace.c
57:	 * removed in 6.0.0 during the 8.4 merge

contrib/pg_upgrade/info.c
606:	 * removed in 6.0.0 during the 8.4 merge

gpAux/extensions/pgbouncer/source/test/hba_test.rules
27:host		tmp1,all	user1,user2 , user3			16.0.0.0/8	md5

gpAux/extensions/pgbouncer/source/test/hba_test.eval
32:reject		db2	user		16.0.0.1
33:md5		db2	user1		16.0.0.1
34:md5		db2	user2		16.0.0.1
35:md5		db2	user3		16.0.0.1
36:reject		db2	user4		16.0.0.1

doc/src/sgml/client-auth.sgml
252:       <literal>10.6.0.0/16</literal> for a larger one.
```

**Comment by l-wang** [comment]
> I made another commit related to the .out files, should those be updated as well, probably not?? A little concerned about the "PostgreSQL 9.2" and git SHAs.

I'm not worried about "PostgreSQL 9.2" and the git SHAs. The changes you made in the .out files are inside of the ignored blocks anyways so doesn't really matter. If you are too avoid by this we are at "PostgreSQL 9.4.20" right now, but it will soon be changed as merge work going on, and there's nothing we can do to know the actual SHA. So I would just leave them as they are.

**Comment by bradfordboyle** [comment]
Do we need to make sure we tag this commit when this gets merged?

**Comment by benchristel** [comment]
@bradfordboyle I believe so. It should be tagged 7.0.0-alpha.0

**Comment by danielgustafsson** [comment]
Can we please get this in soon?

**Comment by benchristel** [comment]
@danielgustafsson sure thing. Just waiting for a green build on master (I wouldn't want to tag a failing commit...)

**Comment by amilkh** [comment]
Thanks for bumping it Daniel! Sorry I'm off work.

@benchristel I think you can use a green commit from the past.

**Comment by amilkh** [comment]
This may warrant pausing master, sticky situation...

**Comment by benchristel** [comment]
Rebased and tagged: [7.0.0-alpha.0](https://github.com/greenplum-db/gpdb/tree/7.0.0-alpha.0)

**Comment by danielgustafsson** [comment]
On Wednesday, April 10, 2019 7:04 PM, Ben Christel <notifications@github.com> wrote:

> Rebased and tagged: [7.0.0-alpha.0](https://github.com/greenplum-db/gpdb/tree/7.0.0-alpha.0)

Thanks!

**Pull request merged**
