### PR TITLE
Use GCP instead of AWS to store intermediate Concourse resources

### PR DESCRIPTION
**Pull request by benchristel**
We are in the process of moving all our Concourse storage from S3 to GCS for GPDB 6 only. This PR is the first step. It moves only the intermediate resources (which are only used internally in the pipeline), so should not affect consumers of Concourse output.

Here are the affected resources:

```
bin_gpdb_centos6
bin_gpdb_centos7
bin_gpdb_sles11
binary_swap_gpdb_centos6
compiled_bits_ubuntu16
deb_package_ubuntu16
icw_gporca_centos6_dump
installer_aix7_gpdb_client
installer_aix7_gpdb_loader
madlib_gppkg
```

Our dev pipeline using GCS buckets:
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gp-releng-use-gcs-buckets-dev

Co-authored-by: Ben Christel <bchristel@pivotal.io>
Co-authored-by: Amil Khanzada <akhanzada@pivotal.io>
Co-authored-by: Sambitesh Dash <sdash@pivotal.io>
Co-authored-by: Oliver Albertini <oalbertini@pivotal.io>

### CODE REVIEW

**Comment by ashwinstar** [comment]
Just curious to know if we will see any performance improvement with this?

**Comment by benchristel** [comment]
We haven't measured, but probably not? The only difference would be the speed to upload/download from GCS vs S3 is our guess.

**Comment by kmacoskey** [comment]
While not measured, I would expect some performance difference overall. The roundtrip from VMs in GCP to AWS s3 (over the public interwebs) is much further then from GCP -> GCP.

**Comment by bhuvnesh2703** [comment]
It does not impact any of the ORCA pipelines in https://orca.ci.gpdb.pivotal.io.
Not sure if any other team uses these as their source.

**Comment by chrishajas** [comment]
This does appear to impact the gpbackup/upgrade pipelines. @jmcatamney @kyeap-pivotal

**Comment by amilkh** [comment]
It does not appear to affect PXF/UD pipelines.
- Ben and Amil

**Comment by amilkh** [comment]
Doesn't appear to affect GPCC pipeline, but @bxu-github @funcode @pivotal-ning-yu  can you please confirm it?

**Comment by pivotal-ning-yu** [comment]
Looks like MPP pipelines (interconnect, resgroup) are not affected.

**Comment by baotingfang** [comment]
@magi345 Could you please confirm on GPCC side.

**Comment by benchristel** [comment]
@chrishajas @jmcatamney @kyeap-pivotal we have two routes for resolving the gpbackup/upgrade breakage.

Plan A:

1. Change gpbackup/upgrade pipelines to use the stable "published" build of `bin_gpdb`, currently on S3.
2. Merge this PR.
3. Later, we will have to change the gpbackup/upgrade pipelines again to consume the stable bin_gpdb from GCS.

Plan B:

1. Start pushing the stable build of bin_gpdb to GCS now (we'd open another PR to do this).
2. Update the gpbackup/upgrade pipelines to consume the bin_gpdb artifact from GCS. 
3. Merge this PR.

I'd prefer Plan A because it minimizes work in flight on the RelEng side, but if the two-step change is too onerous for you, we can do Plan B.

**Comment by tyacovone** [comment]
The binary being consumed by the 'gpbackup' pipeline has been updated to refer to the release candidate bin, rather than the intermediate bin([Commit here](https://github.com/greenplum-db/gpbackup/commit/55518a168bd04b36e40fc31db2192672c8feefc1)). This PR should no longer cause any issues with DP-managed infra.

**Comment by amilkh** [comment]
Merged! Nandish and I also set the gpdb_master and gpdb_master_without_asserts pipelines. Not sure if this affected other pipelines, if so please let's reset those.

**Pull request merged**
