### PR TITLE
Backport Postgres TAP SSL tests 

### PR DESCRIPTION
**Pull request by pf-qiu**
OpenSSL upgrade needs verification, backport related tests from Postgres.
Also, add config options to enable tap tests, adapt test framework to gpdb.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Why are you backporting the patch to allow SSL configuration to be changed with SIGHUP?

Why do we need the SSL tests right now? We're just updating the version of OpenSSL that we build with in the CI system, right?

**Comment by pf-qiu** [comment]
Upgrading OpenSSL has great impact on gpdb, before we commit it's good to have some tests on basic ssl functionalities. If all tests passed using new OpenSSL, then we can be sure it works like before.

About backporting SIGHUP patch, it takes a long time to restart the whole gpdb cluster, so ssl test will run very slowly, maybe longer than 20min. It's better to have ssl config refreshed just with reload, so test time can be reduced to about 20s.

**Comment by lij55** [comment]
for reference:
https://github.com/greenplum-db/gpdb/pull/2758

**Comment by hlinnaka** [comment]
On 07/11/2017 12:19 PM, Peifeng Qiu wrote:
> Upgrading OpenSSL has great impact on gpdb, before we commit it's
> good to have some tests on basic ssl functionalities. If all tests
> passed using new OpenSSL, then we can be sure it works like before.
>
> About backporting SIGHUP patch, it takes a long time to restart the
> whole gpdb cluster, so ssl test will run very slowly, maybe longer
> than 20min. It's better to have ssl config refreshed just with
> reload, so test time can be reduced to about 20s.

Ok. The background of the SSL test in PostgreSQL is that I wrote them 
specifically to test commit acd08d764a, which added support for Subject 
Alternative Names in certificates. So the tests are centered around 
using server and client certificates with different properties. Just for 
updating the version of OpenSSL, I don't think those tests are very 
interesting. There aren't any significant changes in SSL certificates 
are handled in GPDB, compared to the upstream, I believe. I would be OK 
without having these tests at all.

I'm not very happy with backporting the SIGHUP patch, because it will 
cause merge conflicts as we go forward. Why does restarting the server 
take so long? For testing SSL, you don't need to restart the whole 
cluster, restarting the QD server should be enough.

- Heikki

**Comment by pf-qiu** [comment]
> So the tests are centered around using server and client certificates with different properties. Just for updating the version of OpenSSL, I don't think those tests are very interesting.

Yes, I don't think there's any problem with certificate checking procedure of GPDB, with or without new OpenSSL. At least these tests will query gpdb via psql with SSL on. The upgraded .so or .a library will be really used, just in case there are any packaging problem. That's what I mean by 'basic functionalities'. 

> I'm not very happy with backporting the SIGHUP patch, because it will cause merge conflicts as we go forward. Why does restarting the server take so long? For testing SSL, you don't need to restart the whole cluster, restarting the QD server should be enough.

I agree it will be cumbersome for future merges, especially those code lies in separate file be-secure-openssl.c. At first I try to minimum modifications needed, just like in the 4.3 PR. But after investigated commit de41869 I realize it's not quite enough to just call secure_initialize and force clear the global SSL_context. We need error handing during reload, and some flags to record status. Then most parts of commit de41869 is contained.

In fact I already modified the original SIGHUP patch to make reload operation only carried out on QD, since QE usually don't have needed certificate and key files within its data directory.

**Comment by hlinnaka** [comment]
On 07/11/2017 04:56 PM, Peifeng Qiu wrote:
> In fact I already modified the original SIGHUP patch to make reload
> operation only carried out on QD, since QE usually don't have needed
> certificate and key files within its data directory.

My point was that, if we don't backport the SIGHUP patch, you only need 
to stop and restart the QD node, to reload the certificates. So you 
could modify the test case so that instead of restarting the whole 
cluster with gpstop + gpstart, only bounce the QD node, perhaps with a 
direct "pg_ctl restart" call.

That's surely a lot slower than SIGHUP, but a lot faster than restarting 
all the nodes in the cluster. If I counted correctly, the test case 
reloads the certificates 4 times, and restarting just the QD node should 
take a lot less than 20 minutes.

- Heikki

**Comment by pf-qiu** [comment]
I see, didn't think of pg_ctl directly. That would certainly fit our needs. We will try this approach.

**Comment by pivotal-mike** [comment]
@hlinnaka Build system is failing with:
```
configure: error: Perl module IPC::Run is required to run TAP tests
```

Are there any other modules we need for this?

**Comment by hlinnaka** [comment]
On 07/11/2017 06:18 PM, Michael Roth wrote:
> @hlinnaka Build system is failing with:
> ```
> configure: error: Perl module IPC::Run is required to run TAP tests
> ```
>
> Are there any other modules we need for this?

I think that's the only one.

- Heikki

**Comment by pf-qiu** [comment]
@pivotal-mike Forgot to mention, TAP requires two perl packages, perl-IPC-Run and perl-Test-Base. Please update them in the centos6 concourse image. By the way, TAP can't be run on centos5 directly, because it needs perl 5.10.1, but centos5 only has perl 5.8.

**Comment by schubert** [comment]
@pf-qiu RHEL5 shouldn't matter for GPDB 5.x+ so that should be fine.

**Comment by pf-qiu** [comment]
@hlinnaka We have modified tests to just restart QD to reload ssl config, without SIGHUP patch.

**Pull request merged**
