### PR TITLE
Init ICProxy's SHM variable in CreateSharedMemoryAndSemaphores()

### PR DESCRIPTION
**Pull request by interma**
My previous commit 8915cd09333961e203baf0255ca1a0f2c4d8607e caused coredump in some pipeline jobs.
Example stack:
```
Core was generated by `postgres:  7000, ic proxy process                                             '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000b46ec3 in pg_atomic_read_u32_impl (ptr=0x7f05a8c51104) at ../../../../src/include/port/atomics/generic.h:48
(gdb) bt
#0  0x0000000000b46ec3 in pg_atomic_read_u32_impl (ptr=0x7f05a8c51104) at ../../../../src/include/port/atomics/generic.h:48
#1  pg_atomic_read_u32 (ptr=0x7f05a8c51104) at ../../../../src/include/port/atomics.h:247
#2  LWLockAttemptLock (mode=LW_EXCLUSIVE, lock=0x7f05a8c51100) at lwlock.c:751
#3  LWLockAcquire (lock=0x7f05a8c51100, mode=mode@entry=LW_EXCLUSIVE) at lwlock.c:1188
#4  0x0000000000b32fff in ShmemInitStruct (name=name@entry=0x130e160 "", size=size@entry=4, foundPtr=foundPtr@entry=0x7ffcf94513bf) at shmem.c:412
#5  0x0000000000d6d18e in ic_proxy_server_main () at ic_proxy_main.c:545
#6  0x0000000000d6c219 in ICProxyMain (main_arg=<optimized out>) at ic_proxy_bgworker.c:36
#7  0x0000000000aa9caa in StartBackgroundWorker () at bgworker.c:955
#8  0x0000000000ab9407 in do_start_bgworker (rw=<optimized out>) at postmaster.c:6450
#9  maybe_start_bgworkers () at postmaster.c:6706
#10 0x0000000000abbc59 in ServerLoop () at postmaster.c:2095
#11 0x0000000000abd777 in PostmasterMain (argc=argc@entry=5, argv=argv@entry=0x36e3650) at postmaster.c:1633
#12 0x00000000006e4764 in main (argc=5, argv=0x36e3650) at main.c:240
(gdb) p *ptr
Cannot access memory at address 0x7f05a8c51104
```

The root cause is I forgot to init SHM structure at `CreateSharedMemoryAndSemaphores()`.
Fix it in this PR.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by interma** [comment]
No specific test case is needed for the PR: previous case can test it.

**Review by Aegeaner — APPROVED** [review]
LGTM.
The second commit is enough for requesting shared memory access in ic-proxy's bgworker process normally, IMO.

`MainLWLockArray` is initialized in `CreateSharedMemoryAndSemaphores` , but it would only be enabled when `fault inject` enabled：
[if (worker->bgw_flags & BGWORKER_SHMEM_ACCESS)](https://github.com/greenplum-db/gpdb/blob/880a85659d84eb4b0a495505b0a9e11983028f27/src/backend/postmaster/bgworker.c#L918)

So we need to just turn on the flag `BGWORKER_SHMEM_ACCESS` for `worker->bgw_flags` and remove the restriction with `fault inject`: 
https://github.com/greenplum-db/gpdb/blob/880a85659d84eb4b0a495505b0a9e11983028f27/src/backend/postmaster/postmaster.c#L431

`bgw_flags` is a bitwise-or'd bit mask indicating the capabilities that the module wants. Possible values are `BGWORKER_SHMEM_ACCESS` \(requesting shared memory access\) and `BGWORKER_BACKEND_DATABASE_CONNECTION` \(requesting the ability to establish a database connection, through which it can later run transactions and queries\).

**Review by adam8157 — APPROVED** [review]

**Comment by interma** [comment]
> The second commit is enough for requesting shared memory access in ic-proxy's bgworker process normally, IMO.

Thanks, I didn't revert the first commit since looks it follows the best practice of using SHM (init it in `CreateSharedMemoryAndSemaphores()` and used it later).

**Comment by interma** [comment]
pipeine passed: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-fix_init_shm_icproxy-rhel8?group=all

I am going to merge it, thanks all.

**Pull request merged**
