### PR TITLE
gpactivatestandby_ubuntu18 concourse pipeline fix

### PR DESCRIPTION
**Pull request by deenav**
gpactivatestandby_ubuntu18 concourse job is failing in recent times. As per the investigation found that the job has always been running very close to the memory threshold which could be due to recent Canonical cloud ubuntu base image (that is used for CCP VM image baking) change.

As a workaround, reducing max_connections on the test cluster (as these tests are very tiny) to lower the memory footprint which should allow the tests to run again in the same VM instance type.

In this PR, introducing a new parameter 'REDUCE_MAX_CONNECTIONS' in concourse which will reduce the GP max_connections value by half. This can be leveraged for other tests to reduce memory footprint (if required).

Co-authored-by: Jimmy Yih <jyih@vmware.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ashwinstar** [comment]
I would prefer to give the exact number for `max_connections` for master and segments or something on those lines. `REDUCE_MAX_CONNECTIONS` is very fishy implicit way to do this.

**Comment by deenav** [comment]
> I would prefer to give the exact number for `max_connections` for master and segments or something on those lines. `REDUCE_MAX_CONNECTIONS` is very fishy implicit way to do this.

@ashwinstar updated the PR as per the suggestion. 
Please note that Current max_connections values on concourse test VMs are, Coordinator=250 and Segment=750 which are consuming more memory footprint on Ubuntu VMs and @jimmyyih and I thought that will reduce it by half.
Now, as you said reduced `max_connections` to more explicit values and saw dev pipeline is green.

Let me know, thanks.

**Comment by ashwinstar** [comment]
I feel we shouldn't have REDUCE_MAX_CONNECTIONS variable at all. Both coordinator and segment connection values should be passed as values explicitly top to bottom, if not specified then use defaults.

**Comment by deenav** [comment]
> I feel we shouldn't have REDUCE_MAX_CONNECTIONS variable at all. Both coordinator and segment connection values should be passed as values explicitly top to bottom, if not specified then use defaults.

Thanks @ashwinstar for the inputs. I have updated the PR with changes by introducing `COORDINATOR_MAX_CONNECT` and `SEGMENT_MAX_CONNECT` variables at the pipeline YAML file explicitly.

Note: I have regenerated `gpdb_master-generated.yml` pipeline file and seems like there are changes related to `gp_bash_functions.sh` tests which got included in PR https://github.com/greenplum-db/gpdb/pull/12481.

**Review by jimmyyih — APPROVED** [review]

**Review by ashwinstar — APPROVED** [review]

**Pull request merged**
