### PR TITLE
Transient type qdremap v2

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
This PR is based on https://github.com/greenplum-db/gpdb/pull/2094, which introduced test failures on DML cases. The root cause is that https://github.com/greenplum-db/gpdb/pull/2094 changed how DML passes tupledesc to ExecInitJunkFilter(). This change is avoidable, just like what we've done in this new PR.

### CODE REVIEW

**Comment by hlinnaka** [comment]
I'd like to know *why* ExecInitJunkFilter() needs to be different from the usptream.

**Comment by hlinnaka** [comment]
In PostgreSQL, there's a call to ExecCleanTypeFromTL() within ExecInitJunkFilter(). Can you change the code so that it's identical to the upstream, please?

It might be best to deal with just that change in a separate PR, and get that in first.

**Comment by pivotal-ning-yu** [comment]
@hlinnaka There's some problem to use ExecCleanTypeFromTL approach in ExecInitDML, we are talking about this with QX team right now. We will file another pr later.

**Comment by foyzur** [comment]
To answer the question of duplicating tuple descriptor from underlying relation, rather than deriving it from target list: currently ORCA doesn't maintain the typmod. Therefore, using targetlist type to construct the cleanTupType gives us a TupleDesc that doesn't precisely line up with the underlying table attribute type. The ExecInsert detects such mismatch and mistakenly assumes that it needs to remap the columns (mostly for dropped column handling, where the tuple descriptor of the input doesn't line up with the table's tuple descriptor). To prevent that redundant remapping we use CreateTupleDescCopy(), directly copying the result relation's rd_att. 

As we already have a *clean* tuple descriptor (no junk in the underlying relation's rd_att), we no longer need another pass through TL to derive cleanTupType. So, we just refactored the ExecInitJunkFilter to use the already clean tuple descriptor.

**Comment by pivotal-ning-yu** [comment]
Rebased to origin/master to trigger a rebuild, previous CI check failed due to unexpected reason.

**Comment by pivotal-ning-yu** [comment]
A new PR is opened for the junkfilter change, https://github.com/greenplum-db/gpdb/pull/2182, please help to review it, thanks.

**Comment by pivotal-ning-yu** [comment]
We have this PR merged and found below case failed in pipeline:

```diff
--- /tmp/build/e9195d60/gpdb_src/src/test/tinc/tincrepo/functions/builtin/output/select_fromtable_pg_lock_status.out	2017-04-11 02:50:18.901140288 +0000
+++ /tmp/build/e9195d60/gpdb_src/src/test/tinc/tincrepo/functions/builtin/output/select_fromtable_pg_lock_status_mod.ans	2017-04-11 02:50:18.905140288 +0000
@@ -8,20 +8,20 @@
 
 
 
 
 
 
 
 SELECT pg_lock_status() FROM foo
                             pg_lock_status                            
 ----------------------------------------------------------------------
- (relation,151955,151957,,,,,,,,2/4,29461,AccessShareLock,t,1117,t,0)
- (relation,151955,151957,,,,,,,,2/4,29461,AccessShareLock,t,1117,t,0)
- (relation,151955,151957,,,,,,,,2/4,29462,AccessShareLock,t,1117,t,1)
- (relation,151955,151957,,,,,,,,2/4,29462,AccessShareLock,t,1117,t,1)
+ (relation,151955,151957,,,,,,,,2/4,29453,AccessShareLock,t,1116,t,0)
+ (relation,151955,151957,,,,,,,,2/4,29453,AccessShareLock,t,1116,t,0)
+ (relation,151955,151957,,,,,,,,2/4,29454,AccessShareLock,t,1116,t,1)
+ (relation,151955,151957,,,,,,,,2/4,29454,AccessShareLock,t,1116,t,1)
  (virtualxid,,,,,VIRTUAL/XID,,,,,VIRTUAL/XID,PID,ExclusiveLock,t,SESSIONID,t,0)
  (virtualxid,,,,,VIRTUAL/XID,,,,,VIRTUAL/XID,PID,ExclusiveLock,t,SESSIONID,t,0)
  (virtualxid,,,,,VIRTUAL/XID,,,,,VIRTUAL/XID,PID,ExclusiveLock,t,SESSIONID,t,1)
  (virtualxid,,,,,VIRTUAL/XID,,,,,VIRTUAL/XID,PID,ExclusiveLock,t,SESSIONID,t,1)
 (8 rows)
```

W/o this PR this case produces output like below:

```
SELECT pg_lock_status() FROM foo
psql:/gpdb/src/test/tinc/tincrepo/functions/builtin/output/select_fromtable_pg_lock_status.sql:14: ERROR:  record type has not been registered
```

So it looks like an issue in the case, we'll check how to fix it asap.

**Comment by hlinnaka** [comment]
On 04/11/2017 08:03 AM, Ning Yu wrote:
> We have this PR merged and found below case failed in pipeline:
>
> ```diff
> --- /tmp/build/e9195d60/gpdb_src/src/test/tinc/tincrepo/functions/builtin/output/select_fromtable_pg_lock_status.out	2017-04-11 02:50:18.901140288 +0000
> +++ /tmp/build/e9195d60/gpdb_src/src/test/tinc/tincrepo/functions/builtin/output/select_fromtable_pg_lock_status_mod.ans	2017-04-11 02:50:18.905140288 +0000
> @@ -8,20 +8,20 @@

It'd be nice if someone could review 
https://github.com/greenplum-db/gpdb/pull/1923, to avoid failures from 
these tests in the future.

- Heikki

**Comment by pivotal-ning-yu** [comment]
@hlinnaka from my point of view we should transform the pid, sessionid, etc., in the `(relation,*)` lines, just like the `(virtualxid,*)` lines, is this the correct way to fix the failures? Please let us know your suggestions, thanks in advance.

**Comment by pivotal-ning-yu** [comment]
@hlinnaka oh, just saw your recent comments, so are you suggesting to remove those cases instead of fixing them?

**Comment by hlinnaka** [comment]
On 04/11/2017 08:26 AM, Ning Yu wrote:
> @hlinnaka from my point of view we should transform the pid,
> sessionid, etc., in the `(relation,*)` lines, just like the
> `(virtualxid,*)` lines, is this the correct way to fix the failures?

Yeah, although I wonder how this could ever have worked. Those pids, 
sessionids, etc. in the output are not new.

> @hlinnaka oh, just saw your recent comments, so are you suggesting to
> remove those cases instead of fixing them?

Yes.

- Heikki

**Comment by pivotal-ning-yu** [comment]
To make the pipeline green asap https://github.com/greenplum-db/gpdb/pull/2196 is opened to fix this failure by transforming the `(relation,*)` lines, please help to review it, thanks.

**Comment by pivotal-ning-yu** [comment]
@hlinnaka we performed some experiments just now:

* w/o this PR: only the cases that runs directly on master (like `select pg_lock_status();`) would produce the output, others (like `select pg_lock_status() from t;`) simply fail with error "ERROR:  record type has not been registered". When running only on master the relation *ids do not change between two queries;
* w/ this PR: we could now get the output correctly when running on segments, and the relation *ids change between two queries;

This explains why this ever worked but now failed with our PR.

**Pull request merged**
