### PR TITLE
Speed up ANALYZE by computing column-level statistics in memory.

### PR DESCRIPTION
**Pull request by entong**
Previously ANALYZE in GPDB uses up to 6 SPI calls per column to compute column level statistics including null fraction, average width, ndistinct, mcv and histogram. That resulted in slow performance when the number of columns and number of partitions are large.

In this overhaul of Analyze, we keep the collection of table level stats (reltuples, relpages) and the sampling mechanism unchanged. For column-level stats, we use a similar approach as PostgreSQL. We also have some optimization for string typed columns since they are slow to sort in a plain way. We leverage the ability of mk_sort in the executor to sort string datums much efficiently.

Performance numbers: TPC-H with partitioned lineitem (84 parts) and orders (80 parts), both 1GB locally and 256GB on a server with 64 segments (primary+mirror) observed 4x speed up. If the schema contains a lot of small tables with many columns, the speed-up could reach an order of magnitude or even more.

Obviously this PR is not ready to be pushed since we are still working on having more test coverage. However, I would like to open it early so that we can get feedback sooner. analyzeutils.c is removed since the merging of stats was only used for mid-level partition tables but neither planner nor Orca uses them. All the major changes are in analyze.c. 

@hornn @hsyuan @vraghavan78 @hlinnaka

### CODE REVIEW

**Comment by entong** [comment]
Help! How can one see a large diff on Github. Currently analyze.c diff is too large to be shown.

**Comment by hsyuan** [comment]
The following limits affect the commit, pull request, and compare view diffs:
No single file's diff may exceed 1,500 lines or 100 KB of raw diff data.

Unfortunately, the analyze.c has more than 1500 lines of changes.

**Comment by hlinnaka** [comment]
Please rebase these into a coherent set of patches, so that each patch in the series makes sense individually. Git tip of the week: "git rebase -i origin/master" is very handy for that.

**Comment by hsyuan** [comment]
Hi, I rebased these commits into set of patches.

**Comment by hlinnaka** [comment]
Ok, let's step and think a bit about the design of this whole thing.

Why have we rewritten commands/analyze.c in the first place? What prompted us to rip out and replace the upstream implementation? AFAICS, we're collecting the same statistics that Postgres does, we just do the collection differently.

What if we took the upstream implementation, and only replaced the acquire_sample_rows() function to do the collection of sample rows using the SQL queries. All the rest of the machinery of computing histograms etc. should work as is. Am I missing something?

**Comment by ivannovick** [comment]
The goal of this feature is SPEED.  According to my understanding this will be at least 2 x faster then the existing GPDB analyze and on schemas with many columns and many small tables it can be an order of magnitude faster.  We want that speed even if it means diverging from upstream.  However, if the patch can be modified to minimize differences with upstream and still accomplish the speed improvements that sounds like a sensible thing to do, and i would also wonder if its applicable to submit such a patch upstream as well.  Thats my understanding

**Comment by xinzweb** [comment]
@hlinnaka very good question! We haven't thought about the impact of merging with upstream.

Even though this will reset the progress, I do see the value to step-back and look at it again. 
If we just commit as it is, all the merges of upstream changes will hit by this change. @hsyuan and I looked at the latest analyze.c and it's very different from what we have now.

I see some starting points for prototyping on a new branch:

. Keep all the new tests added for the ANALYZE, and using them to ensure the same behavior.

. Understand how much upstream changes for analyze.c. @hlinnaka we need some help here.

. Prototype to leverage upstream acquire_sample_rows(), and evaluate performance.

We DO need help from PostgreSQL to ensure good design from the beginning as well as the new analyze behavior.

**Comment by ascherbaum-pivotal** [comment]
Can we move this discussion from the Pull Request to the mailinglist? This seems like a bigger effort, which requires investigation and planning.

**Comment by entong** [comment]
To answer Heikki's question, ANALYZE in GPDB is different from Postgres in the following ways:

- When estimating reltuples and relpages, we have different code path for different types of storages. For heap we use block-level sampling in a similar way as Postgres. For AO and AO/CS we access AO metadata stored in segment catalogs.

- Logic for partition tables: analyze root partition + leaf children or root partition only. Handling of external partitions (we excluding them when building the sample table).

- Creation of a temp sample table: due to polymorphic storage, we use an SPI call with a random() predicate to create a sample table. And sample table size is determined in a slightly different way.

- Sorting of string values is too slow in PG (unless we fast-forward to 9.5 with abbreviation key support). GPDB uses MK Sort which is 3x faster for string columns.

The above pull request brings the Analyze code much closer to upstream since we are basically using the same code as compute_scalar_stats() in PG for computing the column stats.

Now I have to figure out how to display the large diff in analyze.c in Github so people can compare with the old code and put comments...

**Comment by entong** [comment]
@xinzweb: we already have acquire_sample_rows() in GPDB, that's the block sampling part for heap storage. Search 'FirstOffsetNumber' in both GPDB and PG 8.3 and you can see. The difference is that we only use acquire_sample_rows() to estimate reltuples for heap storage. For other types of storage acquire_sample_rows() does not apply.

**Comment by xinzweb** [comment]
Refactoring work tracked in: https://github.com/greenplum-db/gpdb/issues/279

**Pull request closed without merging**
