### PR TITLE
Rename legacy planner to Postgres planner

### PR DESCRIPTION
**Pull request by danielgustafsson**
As we merge with upstream and by that keep refining the Postgres planner, legacy planner is no longer a suitable name. This changes all variations of the spelling (legacu planner, legacy optimizer, legacy query optimizet etc) to say "Postgres" rather than "legacy".

By request from @Eulerizeit

### CODE REVIEW

**Comment by berlin-ab** [comment]
That's nice. Thanks @danielgustafsson and @Eulerizeit

**Comment by vraghavan78** [comment]
@dyozie please make sure that the docs reflects this.

**Comment by dyozie** [comment]
Thanks for the heads up.

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review!

**Pull request closed without merging**
