### PR TITLE
WIP: Lwlock unit tests

### PR DESCRIPTION
**Pull request by joaopapereira**
For now the PR is just a WIP because I still do not have the tests for the lwlock that I want. Feel free to take a look at this PR before it is ready as I would love to have some comments on the implementation of these Fakes.

What can you find in this PR:

Implementation of a Fake Test Double for the Shared Memory as well as some basic tests that will allow us to understand if the fake is behaving in the same way as the real implementation.
An example of sharing tests between both fake a real implementations.
Plumbing to replace the real implementation object with the fake ones
A PR that I sent to CMockery to add the prefix on the test name

### CODE REVIEW

**Comment by joaopapereira** [comment]
@hlinnaka I created the branch in the wrong repository. So lets continue the conversation in this one:

> Where are you going with this? What is the thing you actually want to test?

Going to try to walk y'll on my train of thought. Last week I was reviewing a PR that resulted from an interview and realized that it did not have unit tests. This was around the distributedlog functionality.
So I thought how can we test this functionality using our current unit test framework and realized that the best option would be if we have some Fakes that would help us do this. The first thing that poped up in my mind was the locking mechanism. If we have a fake for the locking mechanism we will not need to think anymore about it in our unit testing. So I decided that I wanted to start from there.

In order to do a Fake I would have to create some test around the LWLock to ensure that the it was
"quacking like a duck"(that the behavior of the same was the same as the real implementation without all the burden associated with setting up a Locking mechanism).
When I analyzed the code for the LWLock I realized that it relied heavily on the Shared Memory portion of postgres which made me think that I would have to go one deep and try to fake out the Shared Memory so that I could then fake out the LWLock so that I could have an easier time testing the distribute log.

And this train of thought brought me to the position where I am right now. The next steps that still need to be covered in this PR are:

Create a fake for the LWLock functions that we need distributed log
Use the LWLock and Share Memory Fakes to try to wrap some unit tests around the distributed log implementation
To be fair I am not 100% sure the second point will be part of this PR or if it makes more sense to be moved into its own PR, but time will tell.

Hope this helped out understand where I am coming from

**Comment by joaopapereira** [comment]
Closed due to incorrect branch as a base

**Comment by hlinnaka** [comment]
Have you considered running the tests in a real server environment? You can write test C code e.g. in `src/test/regress/regress_gp.c`, and expose it as a SQL callable function.

**Comment by joaopapereira** [comment]
> Have you considered running the tests in a real server environment? You can write test C code e.g. in `src/test/regress/regress_gp.c`, and expose it as a SQL callable function.

I need a little bit more context to understand what you just said.
Are you suggesting the creation of function like `test__LWLockAcquire_when_trying_to_aquire_101_locks_it_elogs_error` that is run from a SQL file?
Or your suggestion is to expose to SQL the function `LWLockAcquire` and then in the SQL script we run it 100 times and check if it works?

**Comment by hlinnaka** [comment]
On 11/10/2018 23:29, João Pereira wrote:
>     Have you considered running the tests in a real server environment?
>     You can write test C code e.g. in |src/test/regress/regress_gp.c|,
>     and expose it as a SQL callable function.
> 
> I need a little bit more context to understand what you just said.
> Are you suggesting the creation of function like 
> |test__LWLockAcquire_when_trying_to_aquire_101_locks_it_elogs_error| 
> that is run from a SQL file?

Yeah, something like that.

BTW, the 9.4 merge will break these tests, see commit ea9df812d8. And 
9.5 will break them again (commit 3acc10c997). That's probably just the 
tip of the iceberg, there have been small changes to the internals of 
LWLocks in almost every release, even thought the external API has 
stayed mostly unchanged. This kind of tests on the implementation 
details are very fragile. -1.

- Heikki

**Comment by joaopapereira** [comment]
Me and Jimmy tried and interesting project where we tried to port the tests for the merge repository. It can be found
https://github.com/joaopapereira/gpdb-postgres-
merge/commit/8de8095aae1bdcc1d44cfd4f6ef964d7c8c6c00e
https://github.com/joaopapereira/gpdb-postgres-merge/commit/ba58e2f7c885c3be156f5155d94715ba52aa26f7
And the interesting thing about it was that the changes that we had to make in order to port it is to change the calls to the public APIs.
So the tests are really not fragile, because if the changes are affected by the changes in public API there isn't much we can do but change the calls to them.


Despite that it looks like there is not a great deal of interest in having this change committed. So I will close this PR in the next couple of days

**Pull request closed without merging**
