### PR TITLE
Minor code review on clsSystemState.py

### PR DESCRIPTION
**Pull request by danielgustafsson**
This just removes unused imports, variables and functions as well as cleans up a little bit of whitespace. No functional changes.

### CODE REVIEW

**Comment by berlin-ab** [comment]
This didn't run through CI testing.

**Comment by danielgustafsson** [comment]
> This didn't run through CI testing.

If I had a nickel every time I have to rebase and force push a PR to get CI to pick it up. This is the 4th or 5th just today..

**Comment by kalensk** [comment]
> > This didn't run through CI testing.
> 
> If I had a nickel every time I have to rebase and force push a PR to get CI to pick it up. This is the 4th or 5th just today..

Not sure if this helps, but sometimes I have to do force check on the `gpdb_src` resource with `fly -t gpdb-dev cr -r <pipeline_name>/gpdb_src`. However, there are some scenarios where it is not "smart" enough to detect that things have changed, which can happen when there is a force push, or an amend.

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review!

**Pull request closed without merging**
