### PR TITLE
Fix a bug when setting DistributedLogShared->oldestXmin

### PR DESCRIPTION
**Pull request by dh-cloud**
The shared oldestXmin (DistributedLogShared->oldestXmin) may be updated
concurrently. It should be set to a higher value, because a higher xmin
can belong to another distributed log segment, its older segments might
already be truncated.

For Example: txA and txB call DistributedLog_AdvanceOldestXmin concurrently.

```
txA and txB: both hold shared DistributedLogTruncateLock.

txA: set the DistributedLogShared->oldestXmin to XminA. TransactionIdToSegment(XminA) = 0009

txB: set the DistributedLogShared->oldestXmin to XminB. TransactionIdToSegment(XminB) = 0008

txA: truncate segment 0008, 0007...

After that, DistributedLogShared->oldestXmin == XminB, it is on removed segment 0008.
```

Subsequent GetSnapshotData() calls will be failed because SimpleLruReadPage will error out.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dh-cloud Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=9796)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=9796) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dh-cloud Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=9796)!

**Comment by dh-cloud** [comment]
Commit 39fbfe96 (PR #9452) introduced a new function  `DistributedLog_GetDistributedXid()` similar to `DistributedLog_CommittedCheck()`, but it does not check DistributedLogShared->oldestXmin, it calls SimpleLruReadPage_ReadOnly() directly, is it safe?

**Comment by xiong-gang** [comment]
Hi @dh-cloud , I created a PR (https://github.com/greenplum-db/gpdb/pull/9849) to fix this same issue and also change the truncate timing, would you please review it? Thanks.

**Comment by dh-cloud** [comment]
Update: use looped CAS operation.

**Comment by dh-cloud** [comment]
> Logic looks good to me.
> 
> Albeit maybe excessive, would a naive approach to acquire LW_EXCLUSIVE on DistributedLogTruncateLock also technically work?

It also works. At commit 3c69565ad, exclusive DistributedLogControlLock was removed, only shared DistributedLogTruncateLock remained.

**Pull request merged**
