### PR TITLE
Add libpq as database driver

### PR DESCRIPTION
**Pull request by andreasscherbaum**

### CODE REVIEW

**Comment by mkiyama** [comment]
@ivannovick 
Should libpq be added as a supported API?

**Comment by lisakowen** [comment]
@mkiyama  -  libpq is the C api to postgres/gpdb/hawq.  we have included similar information about libpq in hawq docs:  http://hawq.incubator.apache.org/docs/userguide/2.1.0.0-incubating/clientaccess/g-database-application-interfaces.html#libpq_api

@andreasscherbaum - i noticed that this (and other recent PRs) cross-reference postgres current docs, i.e. https://www.postgresql.org/docs/current/static.

most of the other postgres xrefs/links in the docs reference a specific version of postgres (most usually 8.3), i.e. ttps://www.postgresql.org/docs/8.3/static.  is the libpq version in gpdb5 aligned with postgres current?

**Comment by dyozie** [comment]
@lisakowen - good point.  Not sure where the docs currently are, but a while back we went through the effort of "pinning" external postgresql.org references to the correct versions (8.3 in most cases, except for a few features merged from later 9.x releases).  Would like to continue doing that so the doc links don't drift away from what we provide in the code.

**Comment by mkiyama** [comment]
Thanks for the hawq info.
So, if libpq is supported in hawq, does that mean it is supported in gpdb?

**Comment by danielgustafsson** [comment]
> On 30 Jun 2017, at 17:41, David Yozie <notifications@github.com> wrote:
> 
> @lisakowen - good point. Not sure where the docs currently are, but a while back we went through the effort of "pinning" external postgresql.org references to the correct versions (8.3 in most cases, except for a few features merged from later 9.x releases). Would like to continue doing that so the doc links don't drift away from what we provide in the code.

The base of libpq is at 8.3 as the rest of the server, but it has features cherry-picked in from much later versions so referencing a single upstream page is hard since they will all be wrong/incomplete to some degree. Using the 8.3 page is the safe bet, but longer term we should probably create a Greenplum specific libpq page documenting the featureset that we have.

**Comment by andreasscherbaum** [comment]
Link updated with 8.3

**Comment by mkiyama** [comment]
I am assuming @ivannovick is ok having libpq as a supported api for both oss and enterprise.

**Comment by Eulerizeit** [comment]
I'm confused. libpq is an API. there is no choice as to whether we want to
support it or not because it is integral to Postgres/Greenplum working.

-- Rob

**Comment by mkiyama** [comment]
Please correct me if I'm wrong, but my gut feeling is that libpq is a little different than say jdbc.
My thinking is that libpq is a "lower level" and I believe GPDB uses libpq is used not only to communicate with GPDB master but between master and segments.

My concern is supporting enterprise customers who build apps that try to work with master and segments "outside of the gpdb infrastructure" and cause damage.

I understand that an api such as jdbc might also be used in such a way, by connecting to segments as a postgres host, but my thinking is that there is a lot more code to use as samples for connecting to gpdb segments with the libpq api

If there is no way around that, then it will have to be supported.

sorry if I am incorrect, and have caused unnecessary confusion.

**Comment by andreasscherbaum** [comment]
JDBC is a bit different, as it implements it's own access methods (at least I think so).
But Perl and Python are basically just frameworks on top of libpq ... they both (and many other drivers) require that libpq is somehow present.

I agree that we should clarify that no one is supposed to connect to the segments, only to the master. But this entire chapter is about connecting to the master, and the protocol between master and segments is defined somewhere else, and not public.

**Comment by mkiyama** [comment]
ok, thanks

**Pull request merged**
