### PR TITLE
Removes python unittest2 from shipped product

### PR DESCRIPTION
**Pull request by professor**
We want unittest2 on development machines, not production machines

### CODE REVIEW

**Comment by khuddlefish** [comment]
Actually just noticed the PR pipeline failed because of this. We should definitely fix that before this goes in.

**Comment by chrishajas** [comment]
Also, please make sure that the MU_check_centos job still passes in Concourse.

**Comment by khuddlefish** [comment]
@chrishajas MU_check_centos is in the PR pipeline

**Comment by professor** [comment]
@danielgustafsson, we removed pychecker here https://github.com/greenplum-db/gpdb/pull/2203

**Comment by danielgustafsson** [comment]
@professor aha, great!

**Comment by skahler-pivotal** [comment]
like seeing test code that doesn't need to be there in final product cleaned up

**Comment by professor** [comment]
For the curious, I discovered that we need to add python unittest2 to the concourse docker images. I've done this for several of them, but I want to spin up a new pipeline to make sure that this works properly.

**Comment by ashwinstar** [comment]
Is it possible to even loose out this https://github.com/greenplum-db/gpdb/tree/master/src/test/tinc/ext/unittest2 ?? if we are making sure machines running the tests have unittest2.

**Comment by hsyuan** [comment]
Any update on this PR?

**Comment by professor** [comment]
So it turns out that a different Makefile is responsible for copying the python libs. We'll create a new pull request when that work is done.

**Pull request closed without merging**
