### PR TITLE
Add m4 macro processor as a MADlib requirement.

### PR DESCRIPTION
**Pull request by mkiyama**

### CODE REVIEW

**Comment by hlinnaka** [comment]
I don't think this is the right place to list MADlib's requirements. Wouldn't this belong better in MADlib's own documentation? I'm sure MADlib has a lot more dependencies than just m4, and we don't list anything else here.

I'm quite surprised if MADlib actually requires m4, though. What does it use it for? The only place where I've ever encountered m4, is in autoconf. And even there, it's only required to generate the `configure` script from the source `configure.in` file, which is something that only developers need to do. Not when running `configure`, to compile and install it.

**Comment by mkiyama** [comment]
@skahler-pivotal @fmcquillan99 
Should this be in or out?

**Comment by mkiyama** [comment]
@skahler-pivotal @fmcquillan99 
Any response to Heikki's comment about not adding m4 requirement to GDPB doc?

**Comment by mkiyama** [comment]
@ivannovick 
No response about adding m4 to the GPDB MADlib docs.
Should this go in?

**Comment by dyozie** [comment]
Let's plan to keep this in for now.  We're already documenting a madlib gppkg install, and it seems reasonable to call out the m4 component requirement since it's not something that's normally installed on a gpdb node.  If it turns out m4 isn't actually needed we can remove later.

**Pull request merged**
