### PR TITLE
fix panic when a query in res waiting queue is about to cancel itself

### PR DESCRIPTION
**Pull request by dreamedcheng**
Fix issue #9649

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by kainwen** [comment]
Hi @dreamedcheng 
Thanks for opening this PR.

Does master branch also have the issue?
If so, would you please first open this PR to master? And it is merged into master branch, then
we consider to cherry-pick it to the previous version of GPDB.

Can you add a test case for this?

Thanks again.

**Comment by dreamedcheng** [comment]
> Hi @dreamedcheng
> Thanks for opening this PR.
> 
> Does master branch also have the issue?
> If so, would you please first open this PR to master? And after it is merged into master branch, then
> we consider to cherry-pick it to the previous version of GPDB.
> 
> Can you add a test case for this?
> 
> Thanks again.

OK, I'll try it on master branch.

**Comment by dreamedcheng** [comment]
Hi  @kainwen,
    I've tried to reproduce this issue on master branch, and I found a new issue see #9651, I also open a PR for that. After #9651 is fixed, though #9650 will not incur the panic, because master branch handle deadlock timeout in another way, but I think it may cause other problems which is not clear now. So this fix also needs merge into master after #9651 is fixed.

**Comment by jimmyyih** [comment]
@dreamedcheng Sorry for the late follow-up.  I reviewed and tested the original patch you proposed and everything seemed good.  I rebased your branch and added an isolation2 test to the patch to demonstrate the issue (hope that's okay).  Thanks for debugging this issue and proposing the patch.

For 7X (master), the issue is already fixed with https://github.com/greenplum-db/gpdb/commit/b57bf4a2a3da9d7dc0fb21c69aea074d22e5098a.  For 5X_STABLE, the issue exists there so we'll need to backport this fix there as well.

I ran this PR through a dev Concourse pipeline and all ICW jobs were green.

**Review by soumyadeep2007 — COMMENTED** [review]
@jimmyyih :
I have mostly cosmetic comments. Here are some non-cosmetic ones:

1. Lets add the stack trace from the PANIC into the commit message.
2. I think we should add code coverage for cases where `lock_timeout` is set. Bad things are probably going to happen if `LockTimeoutHandler` is called in the middle of `ResLockWaitCancel`. We will have a double cancellation scenario. Eek!
3. We can make the test more minimal: I think we don't need an extra session (Session 1) to consume the active_statements. We could have a setup like the following where we can combine session 1 and 2:
begin;
declare cursor c1 as select 1; --will consume the only slot
select whatever; -- will block

**Comment by jimmyyih** [comment]
@soumyadeep2007 
> Lets add the stack trace from the PANIC into the commit message.

Added.

> I think we should add code coverage for cases where lock_timeout is set. Bad things are probably going to happen if LockTimeoutHandler is called in the middle of ResLockWaitCancel. We will have a double cancellation scenario. Eek!

No need for lock_timeout-specific test as LockTimeoutHandler simply sends a SIGINT to its own process which would get ignored after the first query cancel caused by `Ctrl-C` or `pg_cancel_backend()`.  Regardless, I wrote the test for it but scrapped it after playing around with it for a couple hours since it didn't seem to add any value.

> We can make the test more minimal: I think we don't need an extra session (Session 1) to consume the active_statements. We could have a setup like the following where we can combine session 1 and 2:
    begin;
    declare cursor c1 as select 1; --will consume the only slot
    select whatever; -- will block

The single session cursor scenario won't work for this test because it'll trigger a fast self-deadlock error instead of going through the code path of interest.  However, I did minimize the test a bit more by removing the gpconfig call and instead set the deadlock_timeout GUC during the superuser session (I forgot it was a PGC_SUSET GUC).

Comments addressed and PR has been rebased on top of latest.  This PR should be good to go.

**Comment by soumyadeep2007** [comment]
> No need for lock_timeout-specific test as LockTimeoutHandler simply sends a SIGINT to its own process which would get ignored after the first query cancel caused by Ctrl-C or pg_cancel_backend().

How so? Won't `StatementCancelHandler()` be called and then `QueryCancelPending=true` and then we will do interrupt processing in `ProcessInterrupts()` since `QueryCancelPending=true`. What am I missing?

> The single session cursor scenario won't work for this test because it'll trigger a fast self-deadlock error instead of going through the code path of interest. However, I did minimize the test a bit more by removing the gpconfig call and instead set the deadlock_timeout GUC during the superuser session (I forgot it was a PGC_SUSET GUC).

Ah I forgot about the self-deadlock code-path. Great that makes sense.

**Comment by jimmyyih** [comment]
> How so? Won't StatementCancelHandler() be called and then QueryCancelPending=true and then we will do interrupt processing in ProcessInterrupts() since QueryCancelPending=true. What am I missing?

Yes, essentially `StatementCancelHandler()` is called twice (e.g. think what would happen if you Ctrl-C'd twice during any query).  The first `StatementCancelHandler()` will set `ImmediateInterruptOK` to false during its `ProcessInterrupts()` call.  The second will skip its `ProcessInterrupts()` due to `ImmediateInterruptOK` being false.  The next client read will set `ImmediateInterruptOK` to true in `prepare_for_client_read()` in Postgres loop.  In assistance, `QueryCancelPending` is also a factor which is set to true in `StatementCancelHandler()` and then set to false in `ProcessInterrupts()` in the `if (QueryCancelPending)` conditional section.  That conditional section will only ever be executed one time.  This scenario is not specific to resource queues at all and applies to most situations.  For deadlock timeout, `CheckDeadLock()` is the handler which does a lot of extra things (relative to this PR, it acquires partition LWLocks) before calling ERROR if deadlock is detected... so it needs some special attention.

**Comment by soumyadeep2007** [comment]
> Yes, essentially StatementCancelHandler() is called twice (e.g. think what would happen if you Ctrl-C'd twice during any query). The first StatementCancelHandler() will set ImmediateInterruptOK to false during its ProcessInterrupts() call. The second will skip its ProcessInterrupts() due to ImmediateInterruptOK being false. The next client read will set ImmediateInterruptOK to true in prepare_for_client_read() in Postgres loop. In assistance, QueryCancelPending is also a factor which is set to true in StatementCancelHandler() and then set to false in ProcessInterrupts() in the if (QueryCancelPending) conditional section. That conditional section will only ever be executed one time. This scenario is not specific to resource queues at all and applies to most situations. For deadlock timeout, CheckDeadLock() is the handler which does a lot of extra things (relative to this PR, it acquires partition LWLocks) before calling ERROR if deadlock is detected... so it needs some special attention.

Sounds good and thanks for the detailed explanation. I was looking at gpdb7 by mistake, its a little different there.

**Review by soumyadeep2007 — APPROVED** [review]
LGTM!

**Pull request merged**
