### PR TITLE
Add parentheses to update_condition

### PR DESCRIPTION
**Pull request by Howard229**
Prevent the presence of 'or' in 'update_condition', leading to logical changes.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Howard229 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=8578)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=8578) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Howard229 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=8578)!

**Comment by berlin-ab** [comment]
Thanks @Howard229 - would you provide a specific example where this fix is a solution?

**Comment by gfphoenix78** [comment]
@Howard229 Could you describe the issue clearer?

**Comment by asimrp** [comment]
@Howard229 please feel free to create a new PR that includes a test case describing the issue you are trying to fix.

**Pull request closed without merging**
