### PR TITLE
Remove order from flow

### PR DESCRIPTION
**Pull request by dhanashreek89**
Motion node often needs to "merge" the incoming streams, to preserve the
overall sort order. Instead of carrying sort order information throughout
the later stages of planning, in the Flow struct, pass it as argument
directly to make_motion() and other functions, where a Motion node is
created. This simplifies things.

To make that work, we can no longer rely on apply_motion() to add the final
Motion on top of the plan, when the (sub-)query contains an ORDER BY. That's
because we no longer have that information available at apply_motion(). Add
the Motion node in grouping_planner() instead, where we still have that
information, as a path key.

This fixes a bug, where the sortColIdx of plan flow node may refer to wrong
resno. A test case for that is included.

There are a few plan changes after the refactoring of sort ordering code
in Motion nodes. This commit also updates the expected files.

Also, after this following query in subselect.sql does not error out and
produces results which are not in correct format :

```
select q from (select max(f1) from int4_tbl group by f1 order by f1) q;
```
We already have issue #618 in gpdb master to track this query. We need
to add this test case back once issue #618 is fixed. Ideally this query
should produce results.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Is this the same as PR #1460? Did you address the comments left on that PR?

**Comment by dhanashreek89** [comment]
@hlinnaka Yes this is same as #1460 and addresses the comments there.

**Comment by hlinnaka** [comment]
Ok. I was wondering about the plan changes with table functions that you pointed out on PR #1460. They seemed like valid issues:

If you specify SCATTER RANDOMLY, shouldn't we indeed redistribute the input data to the function, like the old plan did? The new plan doesn't do that. Or do we interpret SCATTER RANDOMLY as "any distribution will do", so that it's OK that the input data hashed by any key, and hence don't need to redistribute it? Probably not, as that would make SCATTER RANDOMLY the same as not specifying any SCATTER clause, no?

Regarding he other plan change, again with a table function but no SCATTER clause, where the Gather Merge node was previously done on top of the Table Function node, but is now done below the Table Function node. Is that really OK? It's probably correct, from a correctness point of view, but isn't it potentially a lot less efficient to collect all the data to the QD, and run the table function there, instead of running the table function in parallel in all the QE nodes, and collecting the results?

**Comment by ashwinstar** [comment]
What's the plan for this PR ?

**Comment by hsyuan** [comment]
Closing this PR, since no one is working on this.

**Pull request closed without merging**
