### PR TITLE
Fix TupleDesc leak when COPY partition table from file

### PR DESCRIPTION
**Pull request by eurekaka**

### CODE REVIEW

**Comment by eurekaka** [comment]
@xiong-gang @pengzhout @yydzero @atris any comments? thanks

**Comment by atris** [comment]
I reviewed it earlier on but forgot to comment. +1 from me

**Comment by hlinnaka** [comment]
This doesn't feel right to me. Why is CopyFromDispatch() responsible for releasing those slots, when it had nothing to do with creating them in the first place? That is very surprising, so at the very least there needs to be a long comment explaining the arrangement.

Does this bug point to a bigger problem: do we have similar leak issues with other resources associated with EState? Normally, an EState is destroyed by ExecEndPlan(), but for some reason CopyFromDispatch() isn't doing that. How about just calling ExecEndPlan() ?

**Comment by hlinnaka** [comment]
oops, clicked "close" by accident, sorry

**Comment by hlinnaka** [comment]
(continuing from my previous comment):

I think if CopyFromDispatch() would call ExecEndPlan(), we could get rid of the whole for-loop over the ResultRelInfos. And it would be less prone to leaking other resources like this; it's currently not obvious at all that if you hold a reference to something in ResultRelInfo, it's not enough to release it in ExecEndPlan(), but CopyFromDispatch() also needs to be changed.

That's assuming that ExecEndPlan() does everything we need it to do, of course. I think it does, but needs some closer inspection.

**Comment by atris** [comment]
@hlinnaka Good point. I am wondering if it should be FreeExecutorState that clears this up, rather than ExecEndPlan.

I am bit skeptical about calling ExecEndPlan as it drops buffer pins too. The reason I was fine with the patch was because it is a quite localized change, so I was ok to give some leeway there but if it might point to a larger problem, as you suggested, then I agree with you that we need a further deep dive.

**Comment by hlinnaka** [comment]
On 07/03/16 09:32, Atri Sharma wrote:
> @hlinnaka Good point. I am wondering if it should be
> FreeExecutorState that clears this up, rather than ExecEndPlan.

Comments in FreeExecutorState explicitly says that it "is not 
responsible for releasing non-memory resources, such as open relations 
or buffer pins." We could change the comment, of course, but I'm a bit 
weary of changing upstream behaviour like that.

> I am bit skeptical about calling ExecEndPlan as it drops buffer pins
> too.

Hmm. That would be a good thing, no? I don't think we're holding any 
buffer pins at that point, anyway.

- Heikki

**Comment by atris** [comment]
On Mon, Mar 7, 2016 at 1:15 PM, Heikki Linnakangas <notifications@github.com
> wrote:
>
>
> Comments in FreeExecutorState explicitly says that it "is not
> responsible for releasing non-memory resources, such as open relations
> or buffer pins." We could change the comment, of course, but I'm a bit
> weary of changing upstream behaviour like that.
>

Sure, I just thought that this specific case is a thin line between
ExecEndPlan and FreeExecutorState, but point taken.

>
> > I am bit skeptical about calling ExecEndPlan as it drops buffer pins
> > too.
>
> Hmm. That would be a good thing, no? I don't think we're holding any
> buffer pins at that point, anyway.
>

We should document why we are calling ExecEndPlan in the copy function
then, because it might seem a bit counterintuitive to be putting it there
for a random reader of the function. Small nitpick

**Comment by eurekaka** [comment]
@hlinnaka , thanks for the comments. For your idea,
>I think if CopyFromDispatch() would call ExecEndPlan(), we could get rid of the whole for-loop over the ResultRelInfos. And it would be less prone to leaking other resources like this;

here are my concerns:
(1) ExecEndPlan is literally related to "plan' and is called in ExecutorEnd/ExecEndSubPlan, which are all in the code path for SELECT/UPDATE/INSERT/DELETE, not for utility commands. To cater for utility commands like COPY, we have to adjust the function name and awkwardly pass a NULL pointer as the PlannedStmt parameter;

(2) ExecEndPlan works very well for CopyFrom, it covers most of the cleanups of CopyFrom; while for CopyFromDispatch, most works of ExecEndPlan is not applicable, such as SendAOTupCounts, finishing jobs for files of INSERT/UPDATE/DELETE since master has no data file, and row mark stuffs;

Any suggestion on how to tackle these? thanks

**Comment by hlinnaka** [comment]
On 08/03/16 11:05, Kenan Yao wrote:
> @hlinnaka , thanks for the comments. For your idea,
>> I think if CopyFromDispatch() would call ExecEndPlan(), we could
>> get rid of the whole for-loop over the ResultRelInfos. And it would
>> be less prone to leaking other resources like this;
>
> here are my concerns: (1) ExecEndPlan is literally related to "plan'
> and is called in ExecutorEnd/ExecEndSubPlan, which are all in the
> code path for SELECT/UPDATE/INSERT/DELETE, not for utility commands.
> To cater for utility commands like COPY, we have to adjust the
> function name and awkwardly pass a NULL pointer as the PlannedStmt
> parameter;

Hmm, yeah, there is that..

> (2) ExecEndPlan works very well for CopyFrom, it covers most of the
> cleanups of CopyFrom; while for CopyFromDispatch, most works of
> ExecEndPlan is not applicable, such as SendAOTupCounts, finishing
> jobs for files of INSERT/UPDATE/DELETE since master has no data file,
> and row mark stuffs;

The function will just not do those things if they're not applicable. 
I.e. if there are no relations kept open for row marks, it will just 
skip that part.

> Any suggestion on how to tackle these? thanks

I'm not sure, but we do need some kind of a straightforward shutdown 
mechanism for these things. We can't expect every caller to know how to 
release all the resources allocated somewhere within the executor.

The comments in FreeExecutorState say:

>  * Note: this is not responsible for releasing non-memory resources,
>  * such as open relations or buffer pins.  But it will shut down any
>  * still-active ExprContexts within the EState.  That is sufficient
>  * cleanup for situations where the EState has only been used for expression
>  * evaluation, and not to run a complete Plan.

The COPY case needs to release non-memory resources, but it also doesn't 
have a complete plan. So one option would be to make FreeExecutorState 
responsible for the cleanup, and change the comment to note that it does 
close resources, besides memory, which are not attached to a Plan but to 
the EState.

Another option would be to add a new function for that. And for 
symmetry, a function that creates the required state. I think the 
charter for the "constructor" function would be to create enough state 
so that you can insert/update/delete tuples in a given relation. It 
would open the partitions of that relation, if it's partitioned, open 
the indexes, and set up enough machinery for calling ExecConstraints. 
And the destructor would close all those things, as well update the 
AO-table totals stuff that CopyFromDispatch currently does.

How does CREATE TABLE AS work, BTW?

- Heikki

**Comment by atris** [comment]
> I'm not sure, but we do need some kind of a straightforward shutdown
> mechanism for these things. We can't expect every caller to know how to
> release all the resources allocated somewhere within the executor.
>
> The comments in FreeExecutorState say:
>
> > * Note: this is not responsible for releasing non-memory resources,
> > * such as open relations or buffer pins. But it will shut down any
> > * still-active ExprContexts within the EState. That is sufficient
> > * cleanup for situations where the EState has only been used for
expression
> > * evaluation, and not to run a complete Plan.
>
> The COPY case needs to release non-memory resources, but it also doesn't
> have a complete plan. So one option would be to make FreeExecutorState
> responsible for the cleanup, and change the comment to note that it does
> close resources, besides memory, which are not attached to a Plan but to
> the EState.
>

Unless it conflicts with upstream, I support this idea as I mentioned up
thread.

**Comment by eurekaka** [comment]
Sorry to bring this back so late due to other escalations. I changed the way to fix this issue based on previous comments, the new pull request is: https://github.com/greenplum-db/gpdb/pull/542, so I would close this one. Please help take a look at that one, thanks.

**Pull request closed without merging**
