### PR TITLE
Remove tests for corrupt pg_aoseg or pg_aocsseg.

### PR DESCRIPTION
**Pull request by hlinnaka**
It's a good thing that we have a sanity check for this kind of corruption
in the system, but I don't think we necessarily need to have automated
regression tests for a pg_aoseg / gp_relation_node inconsistency. It'd be
more interesting to test that various operations don't lead to an
inconsistency in the first place (and I suppose the rest of the whole test
suite also tests for that implicitly), but we generally don't have explicit
tests for all the various sanity checks we have in the system.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@asimrp, @ashwinstar, whadda you think about this? It's a value judgment if it's worthwhile to have tests for this. I think not, but then again, I don't know when this test was added and in what context.

**Comment by danielgustafsson** [comment]
I haven't fully dug into this but I wonder if something like this could help in tracking down the aoseg issue in pg_upgrade? @ashwinstar @slari-pivotal what do you think?

**Comment by asimrp** [comment]
The test intends to test the sanity check.  A unit-test for `CheckAOConsistencyWithGpRelationNode()` would be more appropriate than a TINC test like this one.  My only concern on this PR is it intends to remove a test leaving underlying code untouched.  I would refrain from removing the test in view of upcoming large refactors such as RP #790.  Unless the test is taking too long or is too cumbersome to run.

The sanity check was added because we had seen issues in production where contents of aoseg happened to be inconsistent with contents of gp_relation_node.  The sanity check caused any inserts to abort rather than silently corrupt data. Daniel is right, when manually populating aoseg tables as is done by pg_upgrade, such a check would be useful.

**Comment by hlinnaka** [comment]
The sanity check is no doubt a good thing. The question is, is it worthwhile to have a bespoken regression test for the sanity check?

It wouldn't be too difficult to move the old TINC test to the main regression suite, but if we don't think the test is worthwhile, let's not bother.

**Comment by asimrp** [comment]
The test is doing a lot of unnecessary work but we need something to ensure the sanity check remains sane.  Our only option at this point is this test.

**Comment by ashwinstar** [comment]
On Sun, Mar 12, 2017 at 10:44 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> It's a good thing that we have a sanity check for this kind of corruption
> in the system, but I don't think we necessarily need to have automated
> regression tests for a pg_aoseg / gp_relation_node inconsistency.
>
If you don't have test for broken scenario, how do you prove the sanity
check is working ? Incorrectly coded check can pass both with and without
inconsistency.

It'd be more interesting to test that various operations don't lead to an
> inconsistency in the first place (and I suppose the rest of the whole test
> suite also tests for that implicitly),
>
Yes, rest of the tests validate the healthy scenarios.


> but we generally don't have explicit
> tests for all the various sanity checks we have in the system.
>
Again not good argument to remove test if something similar doesn't have
the test, better would be add test to even cover for those. Practically,
need to have 100% code coverage or better.

**Comment by ashwinstar** [comment]
On Sun, Mar 12, 2017 at 2:37 PM, Daniel Gustafsson <notifications@github.com
> wrote:

> I haven't fully dug into this but I wonder if something like this could
> help in tracking down the aoseg issue in pg_upgrade? @ashwinstar
> <https://github.com/ashwinstar> @slari-pivotal
> <https://github.com/slari-pivotal> what do you think?
>
These are just tests which itself corrupts to validate sanity checks in
code are working fine or not. So, this PR per se doesn't help in any
context to pg_upgrade aoseg issue.

What maybe helpful is to evaluate if adding similar sanity check in
pg_upgrade code is worth or not, but since its already failing with error
in pg_upgrade when issue happens seems is hitting some check.

**Comment by hlinnaka** [comment]
Closing, since you guys want to keep the tests.

**Pull request closed without merging**
