### PR TITLE
Make fsync default off to improve test stability.

### PR DESCRIPTION
**Pull request by xinzweb**
Signed-off-by: Taylor Vesely <tvesely@pivotal.io>

### CODE REVIEW

**Comment by jimmyyih** [comment]
This change is okay if we never want fsync on for any TINC test.  I'm not sure if that is a valid statement to assume.  I think it would be better to take in a string from Concourse pipeline file and loop around a delimiter to run gpconfig on any GUC instead similar to what we have in native Concourse TINC tests and what we had in Pulse projects.

**Comment by ashwinstar** [comment]
For short term this seems fine, but I agree with Jimmy's comment having visibility from pipeline under what configuration its being run is always helpful and more flexible.

**Comment by asimrp** [comment]
LGTM.  Pipeline visibility is good to have, agree on that.  But I don't see any TINC tests requiring `fsync=on`.

**Comment by Eulerizeit** [comment]
@jimmyyih I think in the medium to long term we'd like not to have any TINC tests.

**Comment by xinzweb** [comment]
Ideally, the configuration should be configured similar to `BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"`, so that we can pass in any combination of the GUCs. In that case, the cluster is created as part of the test.

However, in the terraform situation, the `gen_cluster` is part of CCP instead of part of the test job specification. That's why we put in this approach to always set the `fsync=off` for the TINC tests, and that's also the best practice so far.

In order to properly pass the option in, we need to first decouple the GPDB cluster generation from the CCP, then, we can do the similar per-test configuration as we did with native concourse test job.

At the mean time, this is the best temp solution to make `fsync=off`. Hopefully, this should also speed up the TINC tests.

Functionality wise, if we run tests with `fsync=off` always, we only lose coverage on power failure or OS kernel level issues. We should be ok for now.

**Pull request merged**
