### PR TITLE
Remove FIXME: cast the unknown typed literal to text (7X)

### PR DESCRIPTION
**Pull request by hyongtao-db**
Long log:
Don't need to cast the unknown typed literal to text, drop the cast and remove FIXME.
Related PR https://github.com/greenplum-db/gpdb/commit/1e7c4bb0049732ece651d993d03bb6772e5d281a

Signed-off-by: Yongtao Huang <yongtaoh@vmware.com>

### CODE REVIEW

**Review by higuoxing — APPROVED** [review]
Looks good!

**Review by adam8157 — APPROVED** [review]
Thanks. Please squash and merge, and note this upstream commit in the message.

```
commit 1e7c4bb0049732ece651d993d03bb6772e5d281a
Author: Tom Lane <tgl@sss.pgh.pa.us>
Date:   Wed Jan 25 09:17:18 2017 -0500

    Change unknown-type literals to type text in SELECT and RETURNING lists.
```

**Comment by hyongtao-db** [comment]
> Thanks. Please squash and merge, and note this upstream commit in the message.

OK, thanks. I will polish this commit log.

**Comment by adam8157** [comment]
Ref: https://github.com/greenplum-db/gpdb/pull/9686

I haven't checked, not sure if all the `::text` introduced by this PR could or should be all removed.

**Pull request merged**
