### PR TITLE
Disallow array types as hashable types

### PR DESCRIPTION
**Pull request by asubramanya**
Previously if the attribute was an array type such as numeric[], float[] etc,
the OID for those attributes would be considered as ANYARRAYOID instead of
their original type. This would enable the hashDatum() to hash the data for
that particular attribute since it only knows how to hash ANYARRAYOID. But this
resulted in incorrect behavior. So for now disallow all attributes which are
array types from being hashed until the hashDatum() is fixed.

Fixes github issue #5467.

Co-authored-by: Sambitesh Dash <sdash@pivotal.io>

### CODE REVIEW

**Comment by d** [comment]
-1

What? You didn't disallow `CREATE TABLE foo(a int, b int[]) DISTRIBUTED BY (b)`, but just error out for insert? How is that OK?

**Comment by d** [comment]
While it might be out-of-scope of your change, while you're at it, we might need to temporarily take out range types as well

**Comment by asubramanya** [comment]
@d This is the existing behavior on 5X_STABLE as well. We do not error out on create table but on insert instead.

**Comment by asubramanya** [comment]
Closing this PR.

**Pull request closed without merging**
