### PR TITLE
Be able to store bin_gpdb and sync_tools_gpdb to specified S3 locations

### PR DESCRIPTION
**Pull request by adam8157**
Signed-off-by: Gang Xiong gxiong@pivotal.io

### CODE REVIEW

**Comment by cjcjameson** [comment]
Hi folks -- I'm interested in this workflow. I realize that it might be nice to specify the filename and location in S3 so that things don't crash.

However, this is an issue that would apply to all S3 resources, not just bin_gpdb and sync_tools_gpdb. Our team's experience and judgement leads us to recommend that you designate a separate place to collect the bin_gpdb and sync_tools_gpdb by creating a new S3 bucket, and changing the `bucket-name` parameter. This reduces the noisy-ness in your "--load-vars-from" file.

Can you explain in more detail where these two intermediate artifacts have a special usecase?

**Comment by adam8157** [comment]
@cjcjameson we are working on GPDB5 CI, those two parameters would be nice when we have other test pipelines.

@ryantang @ashwinstar @kuien @xiong-gang different buckets seems better, how about we creating a story to switch WIP and PR files from that directory to a new bucket?

**Comment by amilkh** [comment]
+1
Seems like @challiwill just now did the task of adding those parameters into the gpdb secrets file:
https://github.com/greenplum-db/continuous-integration/commit/2803839f13e18220fc0272005fc8f20c00c43dfa

Do consider backporting this to gpdb4 also.

**Comment by ashwinstar** [comment]
Not sure I understand the intent for change. Different pipelines can use different bucket names, do we really need more finer granularity than that.

**Pull request merged**
