### PR TITLE
Add relocating tablespaces capability when init standby

### PR DESCRIPTION
**Pull request by macroyuyang**
* Port upstream `7d274e0` to support relocating tablespaces
* Add option in gpinitstandby so that we could start standby on same machine with tablespaces

### CODE REVIEW

**Comment by hlinnaka** [comment]
I don't think we should support this feature. For now, at least. Some issues:

* If you remove and recreate the standby, the old location for each tablespace would not be kept. You'd need to specify it again when you recreate the standby. Maybe that's OK, but it means if the admin wants to be able to easily rebuild the standby, he'll need to manually keep track of the mapping of each tablespace somewhere, e.g. in a separate file.

* If we do this, I think we'll need to also backport commit 16d8e594acd96661267cb7897834f9cba51a2ffd. Otherwise, the spclocation in the pg_tablespace field would not match the symlink in the standby, which seems like a recipe for trouble.

Let's keep it simple. Is there any reason why we would need this? What is the problem this is trying to solve?

**Comment by macroyuyang** [comment]
@hlinnaka , thanks for review. Ah, yes, commit  16d8e594acd96661267cb7897834f9cba51a2ffd is also needed for correct pg_tablespace display.

The port in this PR is want to resolve problem when we call gpinitstandby to create standby on the same machine of primary with tablespace created. Without this porting pg_basebackup will complains tablespace, for instance /tmp/tblspace already exists, because pg_basebackup want to write the /tmp/tblspace with same dbid

**Comment by hlinnaka** [comment]
On 10/01/18 14:39, Yu Yang wrote:
> @hlinnaka , thanks for review. Ah, yes, commit  16d8e594acd96661267cb7897834f9cba51a2ffd is also needed for correct pg_tablespace display.
> 
> The port in this PR is want to resolve problem when we call gpinitstandby to create standby on the same machine of primary with tablespace created. Without this porting pg_basebackup will complains tablespace, for instance /tmp/tblspace already exists, because pg_basebackup want to write the /tmp/tblspace with same dbid

Hmm. So, for example, when you take a backup of dbid 1, a tablespace 
created with "CREATE TABLESPACE myspc LOCATION '/tmp/myspc/' will come 
out as:

/data/myspc/GPDB_8.4_301801031_db1

Even though we have the dbid as part of the directory name, it doesn't 
help with pg_basebackup.

I assume you're changing the dbid right after the pg_basebackup call. 
Perhaps we should have an extra option to pg_basebackup to specify the 
"target" dbid, and let it do the mapping. Something like --target-dbid=9.


I'm a bit uncomfortable using the upstream -T option for this. With the 
upstream option, you would normally use it like this:

pg_basebackup .. -T /data/myspc=/otherdir/myspc

But that's not really what we want to do here, is it? You'd want to map 
/data/myspc/GPDB_8.4_301801031_db1 to 
/data/myspc/GPDB_8.4_301801031_db9, for example. Which means you'd need 
to know the exact format of the "GPDB_8.4_301801031" part in the python 
script that calls it. That seems hard to keep up-to-date. I'm also not 
sure what we'd do in the future, if we wanted to allow the user to pass 
a -T option to map a tablespace the way it's used in the upstream, if 
we're already using it for changing the dbid.


- Heikki

**Comment by macroyuyang** [comment]
Yes, it's a good idea to use parameter --target-dbid to pg_basebackup. Suppose in GPDB, user should always call gpinitstandby instead of using pg_basebackup directly. Thus, it become simpler for usage, and gpinitstandby will handle it by itself

**Pull request closed without merging**
