### PR TITLE
doc updates for "nulls first" support

### PR DESCRIPTION
**Pull request by lisakowen**
- verified nulls first support with optimizer off/on.
- verified nulls first support, windows with optimizer off/on.
- tried select into with nulls first, both optimizer on and off.  no errors were returned.  results were different between the two, maybe that is expected.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Looks good at a quick glance. Thanks for the testing! What exactly do you mean by SELECT INTO with NULLS FIRST/LAST? Got a test query you can share?

**Comment by lisakowen** [comment]
thanks for reviewing (so fast!) @hlinnaka.

 (new to GPDB...)  i wasn't sure if nulls first was supported in select into, so i tried it out both with optimizer off and on.  neither returned an error.  does it even make sense to select into with an order by clause?

this is what i tried:
```
testdb=# create table tbl_with_nulls (t text, a int, b int);
testdb=# insert into tbl_with_nulls values
  ( 'a', 1, 10),
  ( 'b', 1, 10),
  ( 'c', 1, 10),
  ( 'd', 2, 10),
  ( 'e', 2, 20),
  ( 'f', 2, 20),
  ( 'g', NULL, 20),
  ( 'h', NULL, 20),
  ( 'i', NULL, 30);

testdb=# set optimizer=off;
SET

testdb=# select * into seltab from tbl_with_nulls order by a nulls first;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 't' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
SELECT 9
testdb=# select * from seltab;
 t | a | b  
---+---+----
 i |   | 30
 c | 1 | 10
 f | 2 | 20
 h |   | 20
 b | 1 | 10
 e | 2 | 20
 g |   | 20
 a | 1 | 10
 d | 2 | 10
(9 rows)

testdb=# select * into seltabnonulls from tbl_with_nulls;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 't' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
SELECT 9

testdb=# select * from seltabnonulls;
 t | a | b  
---+---+----
 c | 1 | 10
 f | 2 | 20
 i |   | 30
 a | 1 | 10
 d | 2 | 10
 g |   | 20
 b | 1 | 10
 e | 2 | 20
 h |   | 20
(9 rows)

testdb=# set optimizer=on;
SET

testdb=# select * into seltabOpt from tbl_with_nulls order by a nulls first;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause. Creating a NULL policy entry.
SELECT 9
testdb=# select * from seltabOpt;
 t | a | b  
---+---+----
 i |   | 30
 a | 1 | 10
 e | 2 | 20
 f | 2 | 20
 g |   | 20
 h |   | 20
 c | 1 | 10
 b | 1 | 10
 d | 2 | 10
(9 rows)

testdb=# select * into seltabnonullsOpt from tbl_with_nulls;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause. Creating a NULL policy entry.
SELECT 9
testdb=# select * from tbl_with_nulls;
 t | a | b  
---+---+----
 b | 1 | 10
 e | 2 | 20
 h |   | 20
 a | 1 | 10
 d | 2 | 10
 g |   | 20
 c | 1 | 10
 f | 2 | 20
 i |   | 30
(9 rows)
```

i didn't know if the planners should be expected to return the same results, and if it was significant that they did not in the case where the select into did not include an order by with nulls first.

**Comment by hlinnaka** [comment]
Ah, gotcha. Yeah, it's not expected that you'd get the same result in both cases. It's a bit nonsensical to have an ORDER BY in SELECT INTO. It will sort the rows when it builds the query, but as soon as they are inserted to the new table, the order is lost. When you query the table with "select * from tbl_with_nulls;", that query can legally return the rows in any order. Typically, on a single-node PostgreSQL system you would in fact get the rows out in the same order, because that's the order they happen to lie on disk. On GPDB, it really varies from one invocation to another, because the rows are distributed across nodes, and it depends on chance which node happens to return its results first. So in short, that's normal.

**Comment by mkiyama** [comment]
@vraghavan78 
Just checking, NULLS FIRST/LAST is supported within a WINDOWS clause, correct?

**Comment by hlinnaka** [comment]
> Just checking, NULLS FIRST/LAST is supported within a WINDOWS clause, correct?

Yes. For reference, these tests were added with the feature:
```
-- Test NULLS FIRST/LAST in window clauses
create table tbl_with_nulls (t text, a int, b int);
insert into tbl_with_nulls values
  ( 'a', 1, 10),
  ( 'b', 1, 10),
  ( 'c', 1, 10),
  ( 'd', 2, 10),
  ( 'e', 2, 20),
  ( 'f', 2, 20),
  ( 'g', NULL, 20),
  ( 'h', NULL, 20),
  ( 'i', NULL, 30);

select t, a, b,
  first_value(t) over (order by a nulls first, t),
  first_value(t) over (order by a nulls last, t),
  first_value(t) over (partition by b order by a nulls first, t),
  first_value(t) over (partition by b order by a nulls last, t)
from tbl_with_nulls order by t;

-- Same with explicitly named window
select t, a, b,
  first_value(t) over (w1),
  first_value(t) over (w2),
  first_value(t) over (w3),
  first_value(t) over (w4)
from tbl_with_nulls
window w1 as (order by a nulls first, t),
       w2 as (order by a nulls last, t),
       w3 as (partition by b order by a nulls first, t),
       w4 as (partition by b order by a nulls last, t)
order by t;
```

**Comment by mkiyama** [comment]
thanks.

**Comment by dyozie** [comment]
Looks good - thanks, Lisa!

**Pull request merged**
