### PR TITLE
Reduce differences between reshuffle tests.

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
There are 3 reshuffle tests, the ao one, the co one, and the heap one.
They share almost the same cases, but different on table names and
create table options.  There are also some differences caused when
adding regression tests, they are only added in one file but not others.

We want to keep minimal differences between these tests, so we ensure
that a regression test for ao also covers similar case for heap.  And
once we understand one of the test file we have almost the same
knowledge on the others.

Here is a list of changes to these tests:
- reduce differences on table names by using schema;
- reduce differences on CREATE TABLE options by setting default storage
  options;
- simplify the creation of partially distributed tables by using the
  gp_debug_numsegments extension;
- copy some regression tests to all the tests;
- retire the no longer used helper function;
- move the tests into an existing parallel test group;

pg_regress test framework provides some @@ tokens for ao/co tests,
however we still can not merge the ao and co tests into one file as
WITH (OIDS) is only supported by ao but not co.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Do we really need to have three copies of all tests, for heap, AO and AOCO tables? The reshuffling should work the same, regardless of the table type. The difference in table type is handled at a lower level, in the executor. Has there been any bugs during development so far, where something worked correctly with a heap table, but didn't work on an AO/AOCO table?

We should keep a few tests for AO/AOCO tables, just to be sure it's not completely broken for them, but I think it's sufficient to run most of the tests on heap tables only.

**Comment by danielgustafsson** [comment]
> On 22 Nov 2018, at 09:05, Heikki Linnakangas <notifications@github.com> wrote:
> 
> Do we really need to have three copies of all tests, for heap, AO and AOCO tables? The reshuffling should work the same, regardless of the table type. The difference in table type is handled at a lower level, in the executor. Has there been any bugs during development so far, where something worked correctly with a heap table, but didn't work on an AO/AOCO table?
> 
> We should keep a few tests for AO/AOCO tables, just to be sure it's not completely broken for them, but I think it's sufficient to run most of the tests on heap tables only.

+1

**Comment by kainwen** [comment]
> Do we really need to have three copies of all tests, for heap, AO and AOCO tables? The reshuffling should work the same, regardless of the table type. The difference in table type is handled at a lower level, in the executor. Has there been any bugs during development so far, where something worked correctly with a heap table, but didn't work on an AO/AOCO table?

Only one case:  https://github.com/greenplum-db/gpdb/issues/6068#issuecomment-438931716 

> We should keep a few tests for AO/AOCO tables, just to be sure it's not completely broken for them, but I think it's sufficient to run most of the tests on heap tables only.

Sounds good.

**Comment by pivotal-ning-yu** [comment]
Discussed offline with the team, we will open separate PRs to clean them up.

For current one, as it's approved by some of you and the PR pipeline is green, I'll merge it now, thanks for the review.

**Pull request merged**
