### PR TITLE
Add missing field skipData in RefreshClause serialization.

### PR DESCRIPTION
**Pull request by zhangh43**
Co-authored-by: Jinbao Chen <jinchen@pivotal.io>

Just add the missing field in serialization, so no test is needed.
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by zhangh43** [comment]
This PR fixed #9894

**Comment by kainwen** [comment]
Can we add a test case for this?

**Comment by baobao0206** [comment]
Great, Thank you for fixing the remaining bugs in matview

**Comment by zhangh43** [comment]
@baobao0206 Also fix the temp file leak issue when skipData is enabled on segment. Please review it.

**Comment by zhangh43** [comment]
> Can we add a test case for this?

Added.

**Pull request merged**
