### PR TITLE
Docs: LDAP page corrections

### PR DESCRIPTION
**Pull request by mperezfuster**
This PR addresses the following corrections for the page Using LDAP Authentication with TLS/SSL:

1. all "ldaptls=1" should be replaced with "ldaptls=true"
2. "Specify a non-default port with the ldapport parameter. In this example, the authentication method includes the ldaptls parameter and the ldapport parameter to specify the port 550.
ldap ldapserver=[myldap.com](http://myldap.com/) ldaptls=1 ldapport=500 ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com"
"
The description the port550 and the ldapport=500 doesn't match. It should be both 550 or 500.
3. the last example is wrong,
"host all ldapsuser 0.0.0.0/0 ldap ldapserver=[ldaps://myldap.com] ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com"
"
should be modified with
"host all ldapsuser 0.0.0.0/0 ldap ldapserver=[myldap.com](http://myldap.com/) ldapscheme=ldaps ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com "

### CODE REVIEW

**Comment by RuiWang-vmw** [comment]
Sorry, we found the ldaptls=true is not the root cause. We will investigate that soon, and the doc change can be either pending, or close. When we fix the issue, we can reopen it and rewrite it. Thanks.

**Comment by zhaorui20005** [comment]
That is strange, I found that `ldaptls` should only be set to "1" from the code perspective. So why do we need to change from "1" to "true"?

**Comment by yangru** [comment]
Agree with zhaorui, 
hbaline->ldaptls can be set to true only when "ldaptls=1" is found in pg_hba record.
```
	else if (strcmp(name, "ldaptls") == 0)
	{
		REQUIRE_AUTH_OPTION(uaLDAP, "ldaptls", "ldap");
		if (strcmp(val, "1") == 0)
			hbaline->ldaptls = true;
		else
			hbaline->ldaptls = false;
	}
```

**Comment by RuiWang-vmw** [comment]
The following three options all should be OK
1. host all ldapsuser 0.0.0.0/0 ldap ldapurl=ldaps://myldap.com ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com"
2. host all ldapsuser 0.0.0.0/0 ldap ldapserver=myldap.com ldapscheme=ldaps ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com"
3. host all tlsuser 0.0.0.0/0 ldap ldapserver=myldap.com ldaptls=1 ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com"

currently, the third one wiill crash, the first one and the second one is ok.
The "true" is not correct. When it is set true, the ssl does not take any effect. We should fix the bug of crash when ldaptls=1

**Comment by RuiWang-vmw** [comment]
Hi @mperezfuster, maybe you can update the doc now,  1. no need to do any change to ldaptls=1; 2. 550 and 500 match problem should still be fixed; 3. fix the third example as I mentioned before, it should be ldapserver=myldap.com ldapscheme=ldaps to replace ldapserver=ldaps://   4. add an example host all ldapsuser 0.0.0.0/0 ldap ldapurl=ldaps://myldap.com ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com" at the end of the page. Thanks.

**Comment by mperezfuster** [comment]
> Hi @mperezfuster, maybe you can update the doc now, 1. no need to do any change to ldaptls=1; 2. 550 and 500 match problem should still be fixed; 3. fix the third example as I mentioned before, it should be ldapserver=myldap.com ldapscheme=ldaps to replace ldapserver=ldaps:// 4. add an example host all ldapsuser 0.0.0.0/0 ldap ldapurl=ldaps://myldap.com ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com" at the end of the page. Thanks.

Sure I will make these changes, can you confirm what the description for the additional example should be? @RuiWang-vmw

**Comment by RuiWang-vmw** [comment]
copied from postgresql ldap documentation:
The URL scheme ldaps chooses the LDAPS method for making LDAP connections over SSL, equivalent to using ldapscheme=ldaps. 
https://www.postgresql.org/docs/current/auth-ldap.html

**Comment by mperezfuster** [comment]
> The URL scheme ldaps chooses the LDAPS method for making LDAP connections over SSL, equivalent to using ldapscheme=ldaps.

@RuiWang-vmw how about now?

**Review by RuiWang-vmw — APPROVED** [review]

**Comment by RuiWang-vmw** [comment]
Thanks， it looks good to me.

**Review by zhaorui20005 — APPROVED** [review]

**Review by dyozie — APPROVED** [review]

**Pull request merged**
