### PR TITLE
Fix case when query having NOT IN uses Merge Join but Merge Join ha…

### PR DESCRIPTION
**Pull request by atris**
…s no support for NOT IN joins

### CODE REVIEW

**Comment by vraghavan78** [comment]
Do we have tests that exercise this change?

**Comment by atris** [comment]
I think:
explain select * from gp_relation_node where persistent_tid not in (select ctid from gp_persistent_relation_node); 

should be enough to exercise this.

**Comment by atris** [comment]
@hlinnaka Please let me know if this is ok.

**Comment by hlinnaka** [comment]
LGTM. But please add a test case to the regression suite. And in the test case, please create test tables specifically for the test, and don't rely on gp_relation_node and gp_persistent_relation_node. Those tables might go away in a future release.

**Comment by vraghavan78** [comment]
+1 after test. Also agree with @hlinnaka do not rely on the catalog tables

**Comment by vraghavan78** [comment]
@atris please also push into GPDB4 when done

**Comment by vraghavan78** [comment]
@atris do u need more inputs on this. Could we get this in the master as well as 43 branch?

**Comment by atris** [comment]
@hlinnaka @vraghavan78 I do not have an ORCA enabled system and Pulse is out of commission so cannot run ICG tests.

BTW, I am not able to reproduce it with a normal NOT IN query:

SET enable_nestloop=off
SET enable_hashjoin=off
SELECT * INTO foo1 FROM generate_series(..)
SELECT * INTO foo2 FROM generate_series(..)
EXPLAIN ANALYZE SELECT * FROM foo1 WHERE foo1.generate_series NOT IN (SELECT * FROM foo2);

This does not trigger the error.

**Comment by oarap** [comment]
@atris, the change is on planner, so, maybe ICG with planner will already be helpful. Also, try to create a repro by copy out the system catalog tables into separate table and see whether you can repro. @xinzweb and I got some luck there to repro the issue. Then, you can shrink the repro to smaller table with smaller number of columns. Good luck.

```
create table t as select * from gp_relation_node;
create table tt as select * from gp_persistent_relation_node;
set optimizer=off;
```

```
pivotal=# explain select * from t where persistent_tid not in (select ctid from tt);
ERROR:  Unexpected internal error (nodeMergejoin.c:1685)
```

**Comment by hsyuan** [comment]
Close this PR. Since @vraghavan78 open a new PR https://github.com/greenplum-db/gpdb/pull/1099 with this change, plus test cases.

**Pull request closed without merging**
