### PR TITLE
Docs: added Multiple Distinct Qualified Aggregates to ORCA limitations

### PR DESCRIPTION
**Pull request by mperezfuster**
It was pointed out that "Feature not supported: Multiple Distinct Qualified Aggregates are disabled in the optimizer" had not been documented under ORCA limitations. Adding it to the list followed by the example used in that user case.

### CODE REVIEW

**Comment by d** [comment]
Hmm, the example isn't exactly _multiple_, do you want to try something a bit more illustrative, like `SELECT count(DISTINCT a), sum(DISTINCT b) FROM foo`?

**Comment by mperezfuster** [comment]
thanks for your input @d I have changed the example now.

**Review by d — APPROVED** [review]

**Comment by vraghavan78** [comment]
@mperezfuster this is not completely correct. Orca does support multiple dqa if u enable `optimizer_enable_multiple_distinct_aggs` to on.

**Comment by mperezfuster** [comment]
@vraghavan78 thanks, since optimizer_enable_multiple_distinct_aggs is not documented, should I remove Multiple Distinct Qualified Aggregates from unsupported and document the GUC instead?

**Pull request merged**
