### PR TITLE
Update subselect_optimizer output file

### PR DESCRIPTION
**Pull request by bhuvnesh2703**
In commit af9669449, looks like the optimizer output file was not
updated correctly. This commit fixes it.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ashwinstar** [comment]
Curious to know why only fails for without asserts?

**Comment by bhuvnesh2703** [comment]
> Curious to know why only fails for without asserts?

oops, let me spend some proper time on it.

**Comment by bhuvnesh2703** [comment]
The expected plan in the file is `planner plan`

Assertion Failure with ORCA 
```
LOG:  2021-11-23 13:31:38:053171 PST,THD000,ERROR,"CSubqueryHandler.cpp:1609: Failed assertion: !(COperator::EopLogicalConstTableGet == popSubqChild->Eopid()) || (0 == CLogicalConstTableGet::PopConvert(popSubqChild) ->Pdrgpdrgpdatum() ->Size() && "Constant subqueries must be unnested during preprocessing")
Stack trace:
1    0x0000000104e2b010 gpos::CException::Raise + 432
2    0x000000010534179c gpopt::CSubqueryHandler::FRemoveAllSubquery + 268
3    0x0000000105343154 gpopt::CSubqueryHandler::FProcessScalarOperator + 244
```

Without Assert build, it does not fallback to planner and generates an ORCA Plan, so we see the problem. whereas in assert build it falls back.

**Comment by bhuvnesh2703** [comment]
Closing the request to fix it properly.

**Pull request closed without merging**
