### PR TITLE
Fix gpfdist regression tests

### PR DESCRIPTION
**Pull request by jimmyyih**
The gppinggpfdist.py file is located in $GPHOME/bin/lib. This was
unnoticed because the status check is under ignore blocks.

### CODE REVIEW

**Comment by hlinnaka** [comment]
What is gppinggpfdist.py, anyway? Is it supposed to be used in production, or is it just for testing? If it's to be used in production, we should probably have tests for it, that are not in ignore-blocks. If it's just for testing, but we actually only use it inside an ignore-block, how about just removing the the tool and all the references to it in the tests?

**Comment by jimmyyih** [comment]
I think it's only used in these tests to check if gpfdist is up/down and there are no references in our GPDB docs.  So yes I agree, I'll replace it with something else to get rid of the ignore-block or just remove it all.

**Comment by yydzero** [comment]
It is used to test some behavior of gpfdist. It would be good if there is any better replacement. Think it better to not just remove it and corresponding cases.

**Comment by danielgustafsson** [comment]
It does verify via the GET request that it is indeed gpfdist that responds on the specified url. The test doesn't seem terribly exciting in its current form but I agree with @yydzero that it would good if it was extended to properly validate.

**Comment by jimmyyih** [comment]
Closing this PR for now in favor of making it actually do something instead of having the ignore blocks.

**Pull request closed without merging**
