### PR TITLE
Update relstats after index builds on the QD

### PR DESCRIPTION
**Pull request by soumyadeep2007**
This PR contains a fix to update the relstats after index builds on the QD 
for index rels and their base rels (fixes https://github.com/greenplum-db/gpdb/issues/14460), including some minor refactor commits.

Please review commits individually.

Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/relstats_createidx

### CODE REVIEW

**Comment by soumyadeep2007** [comment]
There are a bunch of plan diffs that we need to fix.

**Comment by soumyadeep2007** [comment]
Pushed a fix to guard the `vac_send_relstats_to_qd` with `!IsSystemClass(rd_rel->oid, rd_rel)`.
Plan fixes are still TODO.

**Review by divyeshddv — APPROVED** [review]
LGTM! Nice clear tests and comments!

**Comment by soumyadeep2007** [comment]
Thanks for the review, rebased against latest HEAD. Waiting for pipeline.

**Pull request merged**
