### PR TITLE
ORCA: Shuffle cost models

### PR DESCRIPTION
**Pull request by soumyadeep2007**
ORCA: Shuffle cost models

This commit removes the existing legacy cost model implementation and
absorbs the experimental cost model into the calibrated cost model,
while deprecating the existing calibrated cost model to be "legacy".
Details:

1. With optimizer_cost_model=legacy, the user will get the old
calibrated cost model behavior.

2. With optimizer_cost_model=calibrated, the user will get the old
experimental cost model behavior (old calibrated cost model behavior +
EopttraceCalibratedBitmapIndexCostModel trace flag).

3. With optimizer_cost_model=experimental, the user will get the exact
same functionality as the new calibrated model above. This option is
kept open to support experimental changes in the future.

Please note: there are no changes to associated GUC values/defaults.

#### Notes

- We have a separate commit for the MDP changes and two other 
minor commits containing somewhat unrelated MDP changes.

- This needs a backport to 6x.

### CODE REVIEW

**Comment by zellerh** [comment]
Can you also handle the use of the EopttraceCalibratedBitmapIndexCostModel trace flag? This flag gets set when we use the (old) experimental cost model and it influences the cost model for bitmap scans. If we keep this flag, can we rename it, as @hardikar suggested in https://github.com/greenplum-db/gpdb/pull/11083? The trace flag is used in CCostModelGPDB.cpp. Once you change this, you'll likely get some plan changes.

**Comment by soumyadeep2007** [comment]
> Can you also handle the use of the EopttraceCalibratedBitmapIndexCostModel trace flag? This flag gets set when we use the (old) experimental cost model and it influences the cost model for bitmap scans. If we keep this flag, can we rename it, as @hardikar suggested in #11083? The trace flag is used in CCostModelGPDB.cpp. Once you change this, you'll likely get some plan changes.

I agree it should not be named based on the cost model. It should be named more on intent. What do you think a good name for the traceflag should be? It seems to involve a lot of distinct things.

**Comment by zellerh** [comment]
> I agree it should not be named based on the cost model. It should be named more on intent. What do you think a good name for the traceflag should be? It seems to involve a lot of distinct things.

Until now, we used different classes to choose between `legacy` and `calibrated`. With your PR, maybe we need another trace flag to do that? So, two trace flags with three different configurations? With names like `EopttraceLegacyCostModel` and `EopttraceExperimentalCostModel` (zero or one of them could be set)? Now, that would go against your suggestion of naming it after the intent. My assumption would be that the trace flags just provide the value of the guc to ORCA. What do you think? I would argue that it is hard to pick a name that shows the intent, because for `experimental` we don't know yet what the intent is going to be.

**Comment by soumyadeep2007** [comment]
w/ @dgkimura : Following on from a conversation with @zellerh yesterday, we opted to remove the `EopttraceCalibratedBitmapIndexCostModel` trace flag - since we get the associated behavior by default, it should not have to be triggered by an explicit trace flag.
To get non-default behavior, the two new trace flags `EopttraceLegacyCostModel` and `EopttraceExperimentalCostModel` will have to be specified.

**Review by zellerh — APPROVED** [review]
LGTM. Thanks for taking care of the traceflags and for setting up `experimental` for the next adventure.

**Pull request merged**
