### PR TITLE
Porting DPE tests to ICG

### PR DESCRIPTION
**Pull request by vraghavan78**
@oarap @xinzweb @hsyuan please take a quick look

### CODE REVIEW

**Comment by hlinnaka** [comment]
What does DPE stand for?

On 11 March 2016 07:38:33 EET, Venkatesh Raghavan <notifications@github.com> wrote:
>@oarap @xinzweb @hsyuan please take a quick look
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/greenplum-db/gpdb/pull/515
>
>-- Commit Summary --
>
>  * Porting DPE tests to ICG
>
>-- File Changes --
>
>    A src/test/regress/expected/qp_dpe.out (349)
>    A src/test/regress/expected/qp_dpe_optimizer.out (349)
>    M src/test/regress/greenplum_schedule (2)
>    A src/test/regress/sql/qp_dpe.sql (227)
>
>-- Patch Links --
>
>https://github.com/greenplum-db/gpdb/pull/515.patch
>https://github.com/greenplum-db/gpdb/pull/515.diff
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/515

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vraghavan78** [comment]
DPE: Dynamic Partition Elimination, I could rename it as partition tests

**Comment by hlinnaka** [comment]
I think DPE is good in the file names,  but please add a comment to the top of qp_dpe.sql to explain it.

On 11 March 2016 08:25:46 EET, Venkatesh Raghavan <notifications@github.com> wrote:
>DPE: Dynamic Partition Elimination, I could rename it as partition
>tests
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/515#issuecomment-195215688

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gcaragea** [comment]
LGTM Venky

**Comment by xinzweb** [comment]
+1

**Comment by vraghavan78** [comment]
Thanks y'all

**Pull request closed without merging**
