### PR TITLE
Unix socket permissions

### PR DESCRIPTION
**Pull request by mperezfuster**
- Modified default value of GUC unix_socket_permissions to 0777
- Added GUC log_file_mode
- Did not add data_directory_mode since I cannot see it available on a Greenplum test environment.
Can you please confirm that the values under Set Classifications column for log_file_mode are correct?
Test site:  https://mireia-gucs.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/config_params/guc-list.html

Needs to be added to 6.17 as well

### CODE REVIEW

**Comment by gfphoenix78** [comment]
@mperezfuster `data_directory_mode` is only available in GPDB master/7X. But the `gpdb` repo doesn't contain the document for this GUC yet.

> Did not add data_directory_mode since I cannot see it available on a Greenplum test environment.

 I don't understand what "Greenplum test environment" is.

**Comment by mperezfuster** [comment]
@gfphoenix78 thank you, that helps. By test environment I meant a local installation of Greenplum 6.16, it makes sense I could not see the GUC as it is only for master branch. I will create a separate PR for it.
Can you please confirm that the values under Set Classifications column for `og_file_mode` are correct?
Also what are the corresponding ones for the guc `data_directory_mode`. Thanks!

**Comment by gfphoenix78** [comment]
log_file_mode:
default: 0600
value range: 0000 ~ 0777
The acceptable value 0000 or like doesn't make sense. The owner of the log file should at least have the write permission in runtime, and the owner should also have the read permission in order to see the log file.

data_directory_mode:
default: 0700
range value: 0000 ~ 0777
As I said before, the owner should have READ/WRITE/EXE permission for the data directory, the database should not be able to start successfully if the owner lacks any of the 3 types of permissions. Permissions for group or other doesn't matter, but related to security policies, i.e. whether expose access privileges to other users.

NOTE: The value ranges are hard coded in the source code which follows the upstream(postgresql). The best practise is to use the default values in production.

**Comment by mperezfuster** [comment]
@gfphoenix78 thank you.
Can you please confirm the values under the Set Classifications column (local, system, restart, etc) for both `log_file_mode` and `data_directory_mode`? More details on the table here: https://gpdb.docs.pivotal.io/6-17/ref_guide/config_params/guc_config.html#topic_vsn_22l_z4 Thanks!

**Comment by gfphoenix78** [comment]
@mperezfuster `data_directory_mode` is an internal GUC in Postgres. If we want to document it, the Set Classification of `data_directory_mode` is `system` and `readonly`.
The Set Classification of `log_file_mode` is `system`, `reload`

**Review by dyozie — APPROVED** [review]

**Comment by mperezfuster** [comment]
@gfphoenix78 thank you, I agree maybe we shouldn't have to document `data_directory_mode` as it is internal and read only. @dyozie @wenwangBJ  do you agree? Thanks.

**Comment by dyozie** [comment]
> @gfphoenix78 thank you, I agree maybe we shouldn't have to document `data_directory_mode` as it is internal and read only. @dyozie @wenwangBJ do you agree? Thanks.

I agree - let's not document internal-only gucs.

**Pull request merged**
