### PR TITLE
Make contrib/seg build and test

### PR DESCRIPTION
**Pull request by danielgustafsson**
The `contrib/seg` module wasn't compiling due to using V0 conventions, and the test files were missing since the open sourcing of GPDB. This cherry-picks the upstream commit to make it build with V1 instead, and brings back the tests. The module in itself may not be terribly important to GPDB, but we should avoid to have broken code in the repo nevertheless.

This is another breakout PR from #6978

### CODE REVIEW

**Comment by ashwinstar** [comment]
:+1:  Don't see this added to Makefile so curious does it compile and test by default ?

**Comment by danielgustafsson** [comment]
Adding it to the Makefiles and enabling by default is part of #6978, this is a breakout PR to pick off the pieces one by one for easier review. Once all the parts build, the Makefile will be switched on.

**Comment by berlin-ab** [comment]
Another that didn't run in the pipeline.

**Comment by danielgustafsson** [comment]
This doesn't really have any components exposed to the pipeline, but gave it a nudge anyways to try and get a green run through before merging.

**Comment by danielgustafsson** [comment]
> `make install` and `make installcheck` work for me. `make check` does not, probably due to missing GPDB arguments to `pg_ctl`, but I assume that's a more general problem in our tests.

Correct, we aren't yet at a point where `make check` works unfortunately.

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review! I will continue to make contrib green by pulling apart #6978 into more separate PRs.

**Pull request closed without merging**
