### PR TITLE
hide pgAdmin III topics

### PR DESCRIPTION
**Pull request by lisakowen**
hide the pgAdmin III topics:
- commented out references from the appropriate .ditamap
- commented out reference from supported client applications overview
- removed reference and example from configuring kerberos for windows client doc

### CODE REVIEW

**Comment by ascherbaum-pivotal** [comment]
Since pgAdminIII is the only supported version so far, is it useful to hide these topics?

**Comment by Eulerizeit** [comment]
Ads,

Do you know if pgAdminIII works with GPDB 5?

-- Rob

On Wed, Jun 28, 2017 at 8:57 PM, Andreas Scherbaum <notifications@github.com

**Comment by ascherbaum-pivotal** [comment]
Right. So don't disable it, point out when it is working and when not.

**Comment by dyozie** [comment]
The information we have from Jing and Robert IS that pgadmin IV 1.4 or
higher was needed, and that even then we'll be building a custom version to
hide things that don't work. I don't have any word that we support pgadmin
III is tested or supported.

**Pull request merged**
