### PR TITLE
Pg upgrade

### PR DESCRIPTION
**Pull request by davecramer**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Ok, this is quite a bag of changes. This needs to be squashed into more manageable pieces, I think.

PR 995 contains some of these changes, in a more polished form. Let's get that in first. It's pretty much ready for pushing, but needs to be rebased, and a few small changes that were pointed in the comments.

**Comment by asimrp** [comment]
Can we briefly describe the design of upgrade on gpdb-dev list please?  Reverse engineering such a huge change solely based on code is cumbersome.

**Comment by Eulerizeit** [comment]
Are you referring to the pg_upgrade tool or the upgrade process it is going to be used for? 

If the later, I sent out an email a while back to gpdb-eng I'd be happy to forward to you. I'd also be happy to start a thread on the gpdb-dev mailing list if you'd like.

**Comment by asimrp** [comment]
On Wed, Aug 31, 2016 at 10:38 AM, Robert Eckhardt <notifications@github.com>
wrote:
>
> Are you referring to the pg_upgrade tool or the upgrade process it is
going to be used for?

I'm referring to the patch-set in this PR.

>
> If the later, I sent out an email a while back to gpdb-eng I'd be happy
to forward to you. I'd also be happy to start a thread on the gpdb-dev
mailing list if you'd like.
>

Sorry, I am not able to find any discussion regarding upgrade workflow /
design.  Can you please share a pointer?

Asim

**Comment by pivotal-issuemaster** [comment]
@davecramer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1096) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by danielgustafsson** [comment]
Opened a new PR in #1340 with a revamped branch which is also rebased on top of current master, closing this.

**Pull request closed without merging**
