### PR TITLE
WIP: Replace GROUPING SETS implementation with upstream's

### PR DESCRIPTION
**Pull request by hlinnaka**
This set of patches replaces GPDB's implementation of GROUPING SETS, ROLLUP and CUBE, with the PostgreSQL 9.5 implementation. The patches fall roughly into three stages:

1. Small refactorings to existing GPDB code, to make the later patches apply more cleanly to GPDB codebase
2. Remove existing GROUPING SETS implementation. Leave the regression tests in place, failing.
3. Backport the upstream commit that adds GROUPING SETS support, along with some upstream follow-up fixes related to it.
4. Add back GROUP_ID() function. PostgreSQL doesn't have that, so I had to re-implement it on top of the upstream GROUPING SETS code. The new implementation is also quite different from the old one. 
5. Adjust expected output of tests that produce different results with the new implementation. Some queries used to produce incorrect results, or throw an error, with the old implementation.

Caveats/TODOs:

- This new implementation works somewhat differently than the old one, and produces different plans. Some queries might be faster with the new plans, some are surely worse. The new implementation will not do anything smart with the data distribution, and will tend to gather all data to a single node, in all but the simplest cases.
- I haven't done anything about ORCA yet.
- Some regression tests are failing, because of differences in query results. These are cases where I haven't yet investigated, if the new query results are in fact correct, and we had just memorized incorrect results in the expected output.
- A few queries are failing with error:
`ERROR:  too many grouping sets present (max 4096)`
  That is an arbitrary, hard-coded, limit in the upstream code, to prevent exponential growth in the number of grouping sets in some cases. I tested bumping up the limit, to see if the queries can be made to work. The answer is yes. But I think we would be better off keeping the limit the same as in upstream, I don't think customers are likely to hit that limit in real queries, and even if they do, performance might be unacceptably bad.

So, there is still some work to do, but this mostly works. Let's see if the buildfarm agrees :-).

### CODE REVIEW

**Comment by hlinnaka** [comment]
@danielgustafsson asked me on slack for a guesstimate on what it would take to do the grouping in a more MPP fashion. Here's my answer, I figured it would be useful to have it here, for the benefit of whoever might address that in the future:

At first glance, it seems easy enough. In a nutshell, you do the grouping in the segments, ignoring the "rolling up" part, transfer the grouped rows to the master, and do the rolling up in the master.
But digging into it, there is some trickiness.
The rolling up doesn't currently work the way you might expect. You don't take the already grouped up rows, and sum them up further. Instead, the GroupAggregate node keeps multiple transition values, one for each group, and also one for the "total".
For example, let's take this query:

```
postgres=#  select g, count(*) from testtab group by rollup(g);
 g  |  count  
----+---------
  0 |   99999
  1 |  100000
  2 |  100000
  3 |  100000
  4 |  100000
  5 |  100000
  6 |  100000
  7 |  100000
  8 |  100000
  9 |  100000
 10 |       1
    | 1000000
(12 rows)
```

You might think that the GroupAggregate would first compute the totals for each value of `g`, i.e. you might think that the executor would first do the equivalent of this:
```
postgres=#  select g, count(*) from testtab group by g;
g  | count
----+--------
10 |      1
 8 | 100000
 9 | 100000
 1 | 100000
 0 |  99999
 2 | 100000
 5 | 100000
 6 | 100000
 7 | 100000
 4 | 100000
 3 | 100000
(11 rows)
```
and then sum up all the counts to get the one more "grand total" row.
But it doesn't work like that. Instead, then the GroupAggregate processes each input row, it calls the transition function twice, once to compute the current group's aggregate, and second time to compute the grand total.
That might seem surprising, but it's done that way because the aggregates are very generic. There is no function to "combine" the values of two already-computed aggregates. For cases like COUNT or SUM, it might seem trivial, but e.g. with AVG, you can't just take the averages of each group and mash them together to get the total average.
I'm sure there are ways around that. Firstly, we do actually have "combine" functions defined for all the important aggregates in GPDB. We use them for combining aggregates accross segments. And later versions of PostgreSQL also has such functions, used for parallel aggregates. So we could leverage those. It's just a Small Matter Of Programming, but not quite trivial.

**Comment by d** [comment]
There are two problems we may want to solve with a mostly unmodified
grouping sets aggregate operator we get from upstream:

1. Missed opportunity to do partial aggregate within each roll-up (a subset
of all grouping sets) like Heikki just mentioned. That means for grouping
columns with small number of district values, we are calling the transition
functions of the aggregate a shit ton more than we otherwise would.
2. Difficulty to separate the "final" (upper) stage of the aggregate
functions from the "transition" (lower) stages because now that each Agg
operator handles multiple grouping sets, a hypothetically separate final
Agg needs to be able to identify the partial results (trans values) with
the grouping columns. *That means we won't be able to plan for the
aggregate to run on the segments in parallel, except for a few trivial
cases.*

Jesse

**Comment by hlinnaka** [comment]
Rebased over current master.

**Comment by bhuvnesh2703** [comment]
@hlinnaka - Have not tried this branch, but what happens to the queries when run against ORCA?

**Comment by hlinnaka** [comment]
We'll revisit this for GPDB 7, but closing for now.

**Pull request closed without merging**
