### PR TITLE
fix spelling tabes -> tables

### PR DESCRIPTION
**Pull request by foobar**
tables looks to be a typo of tables

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Thanks for your contribution, this is indeed a typo. In order to push the patch with your credentials intact I will need a CLA, see the bot comment above.

**Comment by foobar** [comment]
I just sent a CLA to the bot.

**Comment by danielgustafsson** [comment]
Closing/reopening to trigger the bot.

**Comment by danielgustafsson** [comment]
Committed to master, thanks for your contribution!

**Pull request closed without merging**
