### PR TITLE
Allow simplification of functions returning a composite types with ORCA.

### PR DESCRIPTION
**Pull request by hlinnaka**
This was disabled a long time ago, but even after digging into the git
history, I could not figure out why. Nothing seems to break with it, and
if there's a problem with handling composite types in ORCA, disabling
this transformation would just be plastering over it anyway, because there
are many other ways that you could end up with composite type constants
in a query.

### CODE REVIEW

**Comment by vraghavan78** [comment]
Original intent by the authors:
===
By default, the constant evaluation query mutator recurses into test expressions of sublinks, and may evaluate those to a constant. Consider for example, the following query:

```

select NULL in (select 1);
```

The test expression in the sublink is an OPEXPR(=, NULL, PARAM). Since the function that implements the operator "=" is strict, and one of the arguments is NULL, this gets constant folded into NULL. 
However, the algebrizer only expects OPEXPRessions in the sublink's test expression, and there is no easy way to translate the one where the expression has been constant folded, as we still want to preserve the subquery part of the sublink.

**Comment by hlinnaka** [comment]
Hmm, ok, thanks. That doesn't make much sense to me. Did you understand what that means? There's another flag, `recurse_sublink_testexpr` which sounds more like what you're describing. Although even if that explanation was for `recurse_sublink_testexpr`, not the rowtype-returning function one that this PR is about, I didn't understand that explanation for that flag either..

**Comment by vraghavan78** [comment]
My previous comment was the above comment was the sublink expression and not composite type.

**Comment by vraghavan78** [comment]
finally found the internal JIRA for the original issue will send you an email.

**Comment by bhuvnesh2703** [comment]
@d @vraghavan78 and myself double checked the original intent of the commit, we believe it can be reverted. PR looks good.

**Comment by oarap** [comment]
merged

**Comment by hlinnaka** [comment]
Thanks!

**Pull request closed without merging**
