### PR TITLE
Create symbolic link for sources root dir

### PR DESCRIPTION
**Pull request by lavjain**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Can you explain what the point of this change is? Is this still needed or can we just close this?

**Comment by lavjain** [comment]
@hlinnaka 
The symbolic link allows us to have a deterministic name for the root where the concourse resources are mounted. Rather than using /tmp/build/xYzAbC, the scripts can refer to /home/build if needed.

**Comment by pivotal-mike** [comment]
This seems really superfluous to me - the current scripts just stash `cwd` at start into a shell variable and use that.  Testing scripts shouldn't be making too many assumptions about the environment.

@divyabhargov @doty-pivotal @kmacoskey @l-wang thoughts on this pattern?

**Comment by kmacoskey** [comment]
I agree that the testing scripts shouldn't require a deterministic path. Anything that needs the full path can easily determine that on execution. Keeping everything that runs in a concourse container inside the `/tmp/build/[ID]' directory has many advantages because if the container is going to be exporting volumes, then that has to be done at `/tmp/build/[ID]/[Resource Name]`

**Comment by lavjain** [comment]
This pattern has been successfully used in HAWQ pipelines for a while:

https://github.com/Pivotal-DataFabric/hawq-ci/blob/master/concourse/scripts/common.bash#L123

It comes in handy when setting HADOOP_HOME or similar environment variables.

**Comment by danielgustafsson** [comment]
This discussion seems to have stalled, can we close it or will there be updates?

**Comment by lavjain** [comment]
I still find it useful for PXF scripts. I will merge it in next week if there are no objections.

**Comment by danielgustafsson** [comment]
I'm just poking at old PRs to try to and advance them, I will let @kmacoskey and @pivotal-mike address the question of objections since they are ones who has raised them.

**Comment by kmacoskey** [comment]
My thoughts have not changed about the pattern being one that we should avoid if possible. That being said, I don't know the code for PXF CI well so if it makes sense to use the pattern for that context then I'll trust the change being beneficial. Perhaps in the future we can evaluate our use of absolute paths in any CI code and whether a larger refactor is preferable.

**Comment by lavjain** [comment]
@kmacoskey Thanks a lot for the review. I will close the PR for now and do it inside the PXF script (rather than common.bash).

**Pull request closed without merging**
