### PR TITLE
Add new option --gp_version to pg_config.

### PR DESCRIPTION
**Pull request by higuoxing**
Some extension development framework need to read pg_config at compile time to determine the Greenplum version. This patch adds a new option --gp_version to pg_config to allow these tools to determine the Greenplum's version.

```
BINDIR = /home/v/.local/gpdb6/bin
DOCDIR = /home/v/.local/gpdb6/share/doc/postgresql
HTMLDIR = /home/v/.local/gpdb6/share/doc/postgresql
INCLUDEDIR = /home/v/.local/gpdb6/include
PKGINCLUDEDIR = /home/v/.local/gpdb6/include/postgresql
INCLUDEDIR-SERVER = /home/v/.local/gpdb6/include/postgresql/server
LIBDIR = /home/v/.local/gpdb6/lib
PKGLIBDIR = /home/v/.local/gpdb6/lib/postgresql
LOCALEDIR = /home/v/.local/gpdb6/share/locale
MANDIR = /home/v/.local/gpdb6/share/man
SHAREDIR = /home/v/.local/gpdb6/share/postgresql
SYSCONFDIR = /home/v/.local/gpdb6/etc/postgresql
PGXS = /home/v/.local/gpdb6/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/home/v/.local/gpdb6' '--with-perl' '--with-python' '--enable-debug' '--enable-debug-extensions' '--disable-orca' '--disable-gpcloud' 'CC=/usr/bin/clang' 'CFLAGS=-Og -g3 -ggdb -fno-inline' 'CXX=/usr/bin/clang++'
CC = /usr/bin/clang
CPPFLAGS = -D_GNU_SOURCE -I/home/v/.local/gpdb6/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Wno-address -Wno-unused-command-line-argument -g -ggdb -Og -g3 -ggdb -fno-inline -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/home/v/.local/gpdb6/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/v/.local/gpdb6/lib',--enable-new-dtags -L/home/v/.local/gpdb6/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lnuma -lrt -lzstd -lcrypt -lm -L/home/v/.local/gpdb6/lib
VERSION = PostgreSQL 9.4.26
GP_VERSION = Greenplum 6.26.1+dev.24.gbd5a17db94b build dev
```

### CODE REVIEW

**Review by Sasasu — APPROVED** [review]
fine to me, but this is a little break change. need add into release note

**Comment by bmdoil** [comment]
> Some extension development framework need to read pg_config at compile time to determine the Greenplum version. This patch adds a new option --gp_version to pg_config to allow these tools to determine the Greenplum's version.

The utilities aren't consistent with outputting `--version` or `--gp-version` which makes it hard to code version checks. Should we try to make them consistent?

```
# pg_ctl/pg_controldata/pg_resetxlog/initdb/postgres
$ pg_controldata --version
pg_controldata (Greenplum Database) 9.4.26
$ pg_controldata --gp-version
pg_controldata (Greenplum Database) 6.26.1+dev.2.gaf36662bc94 build dev

# pg_dump/pg_dumpall/pg_receivexlog/pg_xlogdump/pg_upgrade/psql
$ pg_basebackup --version
pg_basebackup (PostgreSQL) 9.4.26
$ pg_basebackup --gp-version
pg_basebackup: unrecognized option '--gp-version'

# vacuumdb/createdb/dropdb/reindexdb/clusterdb/createuser/createlang/dropuser/droplang/pg_isready/pg_rewind/pg_restore/pg_xlogdump/pg_isready
$ vacuumdb --version
vacuumdb (Greenplum Database) 9.4.26
$ vacuumdb --gp-version
vacuumdb: unrecognized option '--gp-version'

# gp utilities (gpinitsystem, gpstart, packcore, gpfdist etc.)
$ gpfdist --version
gpfdist version "6.26.1+dev.2.gaf36662bc94 build dev"

#analyzedb/minirepro
$ analyzedb --version
analyzedb version 1.0
$ analyzedb --gp-version
Usage: analyzedb [options]
```

**Comment by higuoxing** [comment]
> > Some extension development framework need to read pg_config at compile time to determine the Greenplum version. This patch adds a new option --gp_version to pg_config to allow these tools to determine the Greenplum's version.
> 
> The utilities aren't consistent with outputting `--version` or `--gp-version` which makes it hard to code version checks. Should we try to make them consistent?
> 
> ```
> # pg_ctl/pg_controldata/pg_resetxlog/initdb/postgres
> $ pg_controldata --version
> pg_controldata (Greenplum Database) 9.4.26
> $ pg_controldata --gp-version
> pg_controldata (Greenplum Database) 6.26.1+dev.2.gaf36662bc94 build dev
> 
> # pg_dump/pg_dumpall/pg_receivexlog/pg_xlogdump/pg_upgrade/psql
> $ pg_basebackup --version
> pg_basebackup (PostgreSQL) 9.4.26
> $ pg_basebackup --gp-version
> pg_basebackup: unrecognized option '--gp-version'
> 
> # vacuumdb/createdb/dropdb/reindexdb/clusterdb/createuser/createlang/dropuser/droplang/pg_isready/pg_rewind/pg_restore/pg_xlogdump/pg_isready
> $ vacuumdb --version
> vacuumdb (Greenplum Database) 9.4.26
> $ vacuumdb --gp-version
> vacuumdb: unrecognized option '--gp-version'
> 
> # gp utilities (gpinitsystem, gpstart, packcore, gpfdist etc.)
> $ gpfdist --version
> gpfdist version "6.26.1+dev.2.gaf36662bc94 build dev"
> 
> #analyzedb/minirepro
> $ analyzedb --version
> analyzedb version 1.0
> $ analyzedb --gp-version
> Usage: analyzedb [options]
> ```

Good point. I think it's reasonable to make them consistent.

**Review by beeender — APPROVED** [review]
We have discussed `gp-version` vs `gp_version` for GP7 in #15906 .

At least, we need to align with what we already have in GP7.

**Pull request merged**
