### PR TITLE
docs: Add link to MADlib upgrade matrix

### PR DESCRIPTION
**Pull request by mkiyama**
updated pkg upgrade example.

PR for 5X_STABLE 
Will be ported to MAIN

### CODE REVIEW

**Comment by danielgustafsson** [comment]
This patch seems to be contained in #4309, can we close this one?

**Comment by dyozie** [comment]
It does seem like #4309 has all changes + a few extras.  @mkiyama - any reason to keep this PR open?

**Comment by mkiyama** [comment]
I haven't had time to look at it yet.
@dyozie if all the changes are in the other PR, then we can close this.

**Comment by dyozie** [comment]
Covered in https://github.com/greenplum-db/gpdb/pull/4309

**Pull request closed without merging**
