### PR TITLE
Small refactoring in copy.c, to make merging with PostgreSQL 9.1 easier.

### PR DESCRIPTION
**Pull request by hlinnaka**

### CODE REVIEW

**Comment by jchampio** [comment]
Note that this change seems to break gpload in the merge pipeline (gpload assumes that it can directly manipulate/query the fmtopts, and this patch changes the format of that column). Do we need to consider modifying pg_exttable during upgrade, too?

**Comment by jchampio** [comment]
> this change seems to break gpload

Ah, sorry, didn't see that this patch is subtly different from the one that is in the merge -- it doesn't escape the formatter arguments? Do we need to pull that same change into the merge?

**Comment by xinzweb** [comment]
Thanks a lot @jchampio. Who is carry the flag now? @hlinnaka any update on this PR?

This PR is monitored by https://greenplum.slack.com/messages/C9NHTUWUB. Thanks.

**Comment by jchampio** [comment]
> Do we need to pull that same change into the merge?

For the record, I've done this.

> Thanks a lot @jchampio. Who is carry the flag now?

@xinzweb I'm not sure, but this PR has a finite lifetime -- whether it goes into master directly or pieces of it are indirectly pulled in as part of the merge.

**Comment by xinzweb** [comment]
Since you already pulled it as part of merge effort, then I will close this PR for now. If we change our decisions later, feel free to reopen it. Thanks.

**Pull request closed without merging**
