### PR TITLE
Save git root, submodule and changelog information.

### PR DESCRIPTION
**Pull request by funcode**
This is a cherry pick from 5X_STABLE. The `git-info.json` is useful information during integration testing.

The following information will be saved in
${GREENPLUM_INSTALL_DIR}/etc/git-info.json:

* Root repo (uri, sha1)
* Submodules (submodule source path, sha1, tag)

Save git commits since last release tag into
${GREENPLUM_INSTALL_DIR}/etc/git-current-changelog.txt

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@funcode Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=6711)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=6711) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@funcode Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=6711)!

**Comment by kmacoskey** [comment]
This is in preparation for `6X_STABLE` being branched off of `master`. The information gets used in CI pipelines for integration testing and release that had not existed until very recently. It only existed in `5X_STABLE` prior to this because there was no CI setup yet in preparation for Greenplum 6.X. @edespino would need to confirm why it was originally only committed to `5X_STABLE` and not `master` -> `5X_STABLE`.

I see no harm in this being in `master` even when there should never be a release tag on the branch. Eventually when Greenplum 7.X integration testing and release gets setup, the same thing will need to exist (assuming nothing changes between now and then).

**Comment by baotingfang** [comment]
The git doesn't recognize the @ symbol that stand for the HEAD in later git version. 
In order to support the previous git version, we change it back to HEAD.

The pipeline finished the compile jobs. [pipeline here](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/git-info-test-nfu)

**Comment by kmacoskey** [comment]
+1 I think this PR is ready

**Pull request merged**
