### PR TITLE
Fix flaky test in subselect_gp2

### PR DESCRIPTION
**Pull request by paul-guo-**
The previous test case is flaky, possibly due to similar costs of join nodes.
So various join ordering lead to different plans. Fixing it with a simpler and
more deterministic test.

### CODE REVIEW

**Comment by paul-guo-** [comment]
Here is an example of another plan.

```
@@ -40,19 +40,19 @@
 QUERY PLAN
 ___________
  Hash Join
-   Hash Cond: (s.usesysid = u.oid)
+   Hash Cond: (s.datid = d.oid)
    InitPlan 1 (returns $0)
      ->  Result
    ->  Hash Join
-         Hash Cond: (s.datid = d.oid)
-         ->  Function Scan on pg_stat_get_activity s
-               Filter: (query = $0)
-         ->  Hash
-               ->  Seq Scan on pg_database d
-                     Filter: (datname = 'xxx'::name)
-   ->  Hash
+         Hash Cond: (u.oid = s.usesysid)
          ->  Seq Scan on pg_authid u
                Filter: (rolname = 'xxx'::name)
+         ->  Hash
+               ->  Function Scan on pg_stat_get_activity s
+                     Filter: (query = $0)
+   ->  Hash
+         ->  Seq Scan on pg_database d
+               Filter: (datname = 'xxx'::name)
 GP_IGNORE:(15 rows)

 -- Planner test: constant folding in subplan testexpr  produces no error
```

**Comment by hlinnaka** [comment]
Thanks for working on this, I've been seeing that diff too and it's been annoying.

Unfortunately the new test doesn't cover the same case as the old one. The old plan had "Filter: (query = $0)" attached to a FunctionScan. That was critical to the test. You can test easily on 5X_STABLE:
1. Revert d8fbd3457c44, to re-introduce the bug that this tests.
2. Try both queries. The old test query crashes the server, but the new one does not.

**Comment by paul-guo-** [comment]
Oops, thanks. I just roughly looked at the original patch & the message. Will rework on this.

**Comment by paul-guo-** [comment]
Tested the new query on gpdb 5. Without that patch, InitPlan is gone (see the first plan).

```
postgres=# explain select *  from generate_series(1,2) s1 join pg_class on true where s1=(select pg_backend_pid());
                                  QUERY PLAN
------------------------------------------------------------------------------
 Nested Loop  (cost=0.01..25.99 rows=399 width=201)
   ->  Function Scan on generate_series s1  (cost=0.00..15.00 rows=1 width=4)
         Filter: s1 = $0
   ->  Seq Scan on pg_class  (cost=0.00..6.99 rows=399 width=197)
 Optimizer status: legacy query optimizer
(5 rows)

postgres=# \q
[gpadmin@dev6:/home/gpadmin/ws/gpdb5]$ psql
psql (8.3.23)
Type "help" for help.

postgres=# explain select *  from generate_series(1,2) s1 join pg_class on true where s1=(select pg_backend_pid());
                                  QUERY PLAN
------------------------------------------------------------------------------
 Nested Loop  (cost=0.01..25.99 rows=399 width=201)
   InitPlan
     ->  Result  (cost=0.00..0.01 rows=1 width=0)
   ->  Function Scan on generate_series s1  (cost=0.00..15.00 rows=1 width=4)
         Filter: s1 = $0
   ->  Seq Scan on pg_class  (cost=0.00..6.99 rows=399 width=197)
 Optimizer status: legacy query optimizer
(7 rows)
```

**Pull request merged**
