### PR TITLE
Add README to concourse directory

### PR DESCRIPTION
**Pull request by challiwill**
This file explains the contract that we are drawing out for the use and maintenance of the concourse directory. It describes the organization of the directory, and how to make changes safely. It also describes individual team's responsibility to make sure they are alerted if changes are made to a pipeline they are using.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@challiwill Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1321)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1321) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@challiwill Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1321)!

**Comment by Eulerizeit** [comment]
Has there been a decision on what should or shouldn't live here?

**Comment by hlinnaka** [comment]
Can we just move cpplint.py to src/backend/codegen?

**Comment by challiwill** [comment]
@hlinnaka That seems fine to me. If they agree I can update here.

**Comment by challiwill** [comment]
@Eulerizeit not specifically no. It seems to me the logical stuff to have here is pipelines/tasks/scripts that are deployed to the http://gpdb.ci.pivotalci.info/ Concourse instance. 

I do not have a very good understanding of the team structures. For example GPORCA has requested a few task/script files remain and I don't know enough to say whether that is a good idea or not, so I am putting them as exception files specifically called out in the README for now.

**Comment by Eulerizeit** [comment]
I think the concern is, this is an open source code base. Our team names don't really have anything to do with the OSS community.  I appreciate everything being in the open, however, we need to do it in such a way that it is meaningful to non-Pivotal employees.

**Comment by hlinnaka** [comment]
On 11/15/2016 08:21 PM, Robert Eckhardt wrote:
> I think the concern is, this is an open source code base. Our team
> names don't really have anything to do with the OSS community.  I
> appreciate everything being in the open, however, we need to do it in
> such a way that it is meaningful to non-Pivotal employees.

And Pivotal employees as well, for that matter. Last I checked, I'm an 
employee, and I don't really know what teams we have, or what I should 
do with the "responsible" and "dependent" team information. And I don't 
understand how a pipeline file can have a responsible team or dependent 
teams. A pipeline builds and tests the software, it's not structured 
around teams, so where does the team structure come to play?

I get the feeling that I have a very different idea in my head of what 
pipelines we will have in this directory, than what Corbin is thinking. 
I'm envisioning that there are two pipelines, the "master" pipeline, and 
the "PR" pipeline. The master pipeline pulls all the pre-requisites, 
like the build VM images, ORCA, and whatever other external software we 
depend on. It then runs "make install", and creates a bunch of 
installers. And finally, it runs all the regression tests. The PR 
pipeline does the same, but gets the sources from the github pull 
requests, instead of git master.

Corbin, what did you have in mind? Can you explain that in the README, 
please, so that we can discuss it?

- Heikki

**Comment by challiwill** [comment]
@hlinnaka I think you're right. 

I put the `Responsible` and `Dependent` team fields there with the understanding that different teams had pipeline yamls in the directory that they wanted to keep. As it turns out different teams only have stray tasks sitting in the directory, and all we should be keeping is the pipelines you have identified. I will update the README to reflect this.

**Comment by challiwill** [comment]
@hlinnaka do you have any ideas for how we can reconcile having few pipelines with the workflow that people are familiar with where they `get`/`set` a duplicate pipeline to test their own fork? 

Perhaps a `gpdb_branch` pipeline that only reads but doesn't write to any buckets, and can be duplicated and safely run on a specific but non-master source?

**Comment by hlinnaka** [comment]
On 11/15/2016 09:12 PM, Corbin Halliwill wrote:
> @hlinnaka I think you're right.
>
> I put the `Responsible` and `Dependent` team fields there with the
> understanding that different teams had pipeline yamls in the
> directory that they wanted to keep. As it turns out different teams
> only have stray tasks sitting in the directory, and all we should be
> keeping is the pipelines you have identified. I will update the
> README to reflect this.

Ok, cool.

- Heikki

**Comment by hlinnaka** [comment]
On 11/15/2016 09:37 PM, Corbin Halliwill wrote:
> @hlinnaka do you have any ideas for how we can reconcile having few
> pipelines with the workflow that people are familiar with where they
> `get`/`set` a duplicate pipeline to test their own fork?
>
> Perhaps a `gpdb_branch` pipeline that only reads but doesn't write to
> any buckets, and can be duplicated and safely run on a specific but
> non-master source?

Dunno. I'd love to run a copy of the master pipeline myself, but I 
haven't figured out how to do that. I don't know how others do it today.

Yeah, a pipeline that doesn't write to any S3 buckets seems like good 
start. Or is there an easy way to override those resources to write e.g. 
to a local file instead of S3? Might be sufficient to explain in the 
README how to do that. Are there other issues or dependencies that 
prevent one from running the current pipeline locally, or on a different 
concourse instance?

- Heikki

**Comment by hlinnaka** [comment]
Looks MUCH better now, thanks! The short descriptions of each of the pipelines are tremendously helpful.

**Comment by challiwill** [comment]
After a quick discussion with @ryantang it sounds like it will be helpful to have the dev pipeline still produce installers, but we can save them to a separate bucket. 

I'm updating the README to reflect this. 

Also I am adding guidelines for creating your own pipeline copy.

**Pull request merged**
