### PR TITLE
[backport] Move resolution of AlternativeSubPlan choices to the planner.

### PR DESCRIPTION
**Pull request by yanwr1**
When commit https://github.com/postgres/postgres/commit/bd3daddaf232d95b0c9ba6f99b0170a0147dd8af introduced AlternativeSubPlans, I had some
ambitions towards allowing the choice of subplan to change during
execution.  That has not happened, or even been thought about, in the
ensuing twelve years; so it seems like a failed experiment.  So let's
rip that out and resolve the choice of subplan at the end of planning
(in setrefs.c) rather than during executor startup.

It's possible for us to copy an AlternativeSubPlan expression node
into multiple places, for example the scan quals of several
partition children.  Then it's possible that we choose a different
one of the alternatives as optimal in each place.  Commit https://github.com/postgres/postgres/commit/41efb8340877e8ffd0023bb6b2ef22ffd1ca014d
failed to consider this scenario, so its attempt to remove "unused"
subplans could remove subplans that were still used elsewhere.

Fix by delaying the removal logic until we've examined all the
AlternativeSubPlans in a given query level.

Details see commit message
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by kainwen** [comment]
Some background:

when I was working on https://github.com/greenplum-db/gpdb/pull/15842 I find gp6 and gp7 (based on pg12 kernel) still generate AlternativeSubPlan, see plan in cases in the above PR.

SubPlan in GPDB almost always contain motion nodes and now we merge the above PR, so gpdb will prefetch subplans before execute the proc node. And during then, it makes me unhappy to prefetch unsed subplan or setup interconnect or dispatch whole plan to those slices.

Testing under latest postgres, there is no alternative subplan and I go through the two commits they are clear and easy to understand so I suggest @yanwr1 to backport.

--------

Take a basic review of this PR, looks fine. Will spend more time on it.

Thanks so much! @yanwr1

**Comment by yanwr1** [comment]
After backport the commit, it will remove unused subplan in planner stage, so it will reduce slice number, and so reduce interconnect, especially for partitioned tables.
for the below test case :
```
postgres=# \d+ exists_tbl
                             Partitioned table "public.exists_tbl"
 Column |     Type     | Collation | Nullable | Default | Storage  | Stats target | Description 
--------+--------------+-----------+----------+---------+----------+--------------+-------------
 c1     | integer      |           |          |         | plain    |              | 
 c2     | integer      |           |          |         | plain    |              | 
 c3     | integer      |           |          |         | plain    |              | 
 c4     | character(1) |           |          |         | extended |              | 
Partition key: LIST (c4)
Partitions: exists_tbl_ad FOR VALUES IN ('a', 'd'),
            exists_tbl_bc FOR VALUES IN ('b', 'c'),
            exists_tbl__ef FOR VALUES IN ('e', 'f'),
            exists_tbl_g FOR VALUES IN ('g'),
            exists_tbl_null FOR VALUES IN (NULL),
            exists_tbl_default DEFAULT
Distributed by: (c1)
Access method: heap

postgres=# explain (costs off)
select * from exists_tbl t1
  where (exists(select 1 from exists_tbl t2 where t1.c1 = t2.c2) or c3 < 0);
```
before merge these commits, show slice number 
```
(gdb) p *estate->es_sliceTable
$4 = {type = T_SliceTable, localSlice = 0, numSlices = 14, slices = 0x55b4d1901398, hasMotions = true, 
  instrument_options = 0, ic_instance_id = 0}
```
and after merge commits, the slice number reduced to 8
```
(gdb) p *estate->es_sliceTable
$7 = {type = T_SliceTable, localSlice = 0, numSlices = 8, slices = 0x55f74d166c28, hasMotions = true, instrument_options = 0, 
  ic_instance_id = 0}
```

**Review by kainwen — APPROVED** [review]
LGTM from my side.

Lets wait to see if there will be more comments.

**Comment by ashwinstar** [comment]
> After backport the commit, it will remove unused subplan in planner stage, so it will reduce slice number, and so reduce interconnect, especially for partitioned tables.

That's fantastic win.

Do we know if ORCA already uses such technique? how many slices are used by ORCA for above example query?

**Comment by kainwen** [comment]
> > After backport the commit, it will remove unused subplan in planner stage, so it will reduce slice number, and so reduce interconnect, especially for partitioned tables.
> 
> That's fantastic win.
> 
> Do we know if ORCA already uses such technique? how many slices are used by ORCA for above example query?

hi @ashwinstar 
orca never generate hash subplan thus no alternative subplan.

orca's dynamic scan will save many slices that is very important in gpdb.

@yanwr1 can you also paste orca plan of partition table scan with qual containing subplan herw?

**Review by Aegeaner — APPROVED** [review]

**Comment by yanwr1** [comment]
> Do we know if ORCA already uses such technique? how many slices are used by ORCA for above example query?
orca plan:
```
postgres=# explain (costs off)
select * from exists_tbl t1
  where (exists(select 1 from exists_tbl t2 where t1.c1 = t2.c2) or c3 < 0);
                                        QUERY PLAN                                         
-------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)
   ->  Result
         Filter: ((COALESCE((count()), '0'::bigint) > '0'::bigint) OR (exists_tbl.c3 < 0))
         ->  Hash Left Join
               Hash Cond: (exists_tbl.c1 = exists_tbl_1.c2)
               ->  Dynamic Seq Scan on exists_tbl
                     Number of partitions to scan: 6 (out of 6)
               ->  Hash
                     ->  Finalize HashAggregate
                           Group Key: exists_tbl_1.c2
                           ->  Redistribute Motion 3:3  (slice2; segments: 3)
                                 Hash Key: exists_tbl_1.c2
                                 ->  Streaming Partial HashAggregate
                                       Group Key: exists_tbl_1.c2
                                       ->  Dynamic Seq Scan on exists_tbl exists_tbl_1
                                             Number of partitions to scan: 6 (out of 6)
 Optimizer: Pivotal Optimizer (GPORCA)
(17 rows)
```

**Comment by kainwen** [comment]
> > Do we know if ORCA already uses such technique? how many slices are used by ORCA for above example query?
> > orca plan:
> 
> ```
> postgres=# explain (costs off)
> select * from exists_tbl t1
>   where (exists(select 1 from exists_tbl t2 where t1.c1 = t2.c2) or c3 < 0);
>                                         QUERY PLAN                                         
> -------------------------------------------------------------------------------------------
>  Gather Motion 3:1  (slice1; segments: 3)
>    ->  Result
>          Filter: ((COALESCE((count()), '0'::bigint) > '0'::bigint) OR (exists_tbl.c3 < 0))
>          ->  Hash Left Join
>                Hash Cond: (exists_tbl.c1 = exists_tbl_1.c2)
>                ->  Dynamic Seq Scan on exists_tbl
>                      Number of partitions to scan: 6 (out of 6)
>                ->  Hash
>                      ->  Finalize HashAggregate
>                            Group Key: exists_tbl_1.c2
>                            ->  Redistribute Motion 3:3  (slice2; segments: 3)
>                                  Hash Key: exists_tbl_1.c2
>                                  ->  Streaming Partial HashAggregate
>                                        Group Key: exists_tbl_1.c2
>                                        ->  Dynamic Seq Scan on exists_tbl exists_tbl_1
>                                              Number of partitions to scan: 6 (out of 6)
>  Optimizer: Pivotal Optimizer (GPORCA)
> (17 rows)
> ```

ORCA pull up this sublink, we might see the one orca don't pull up.

**Comment by yanwr1** [comment]
Also for the orca plan which doesn't pull up the sublink, dynamic scan will save many slices:
```
postgres=# explain (costs off)
select * from exists_tbl t1
  where (exists(select 1 from exists_tbl t2 where t1.c1 = t2.c2) or c3 < 0);
                                     QUERY PLAN                                     
------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)
   ->  Result
         Filter: (((SubPlan 1) > '0'::bigint) OR (exists_tbl.c3 < 0))
         ->  Dynamic Seq Scan on exists_tbl
               Number of partitions to scan: 6 (out of 6)
         SubPlan 1
           ->  Aggregate
                 ->  Result
                       Filter: (exists_tbl.c1 = exists_tbl_1.c2)
                       ->  Materialize
                             ->  Broadcast Motion 3:3  (slice2; segments: 3)
                                   ->  Dynamic Seq Scan on exists_tbl exists_tbl_1
                                         Number of partitions to scan: 6 (out of 6)
 Optimizer: Pivotal Optimizer (GPORCA)
(14 rows)

```

**Comment by ashwinstar** [comment]
Great thanks for information. So, ORCA is very sophisticated in terms of handling such cases and also efficient in terms of slice usage.

**Review by ashwinstar — APPROVED** [review]

**Comment by yanwr1** [comment]
dev pipeline is ok: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/test

**Pull request merged**
