### PR TITLE
Rename cdb* functions and structures from explain_gp.c

### PR DESCRIPTION
**Pull request by joaopapereira**
All the functions cdb* were renamed to gp* and all the
structures Cdb* where renamed to GP*

### CODE REVIEW

**Comment by hlinnaka** [comment]
I have no objection as such, but: why bother? I don't think there's anything wrong with the "CDB" prefix, and we have a ton of code that uses that, anyway.

**Comment by danielgustafsson** [comment]
I'm also neither for nor against, but if done it should be in a single commit and PR not doing anything else (which is what I complained against last time I saw this, so that doesn't apply here). Question is, do we want to wholesale rebrand ourselves GP for everything? Or do we want to wholesale adopt CDB for internals? Since GP and PG are quite visually close, continuing on with CDB might be a way for our code to more stand out in a clear way?

I've been on the let's-just-use-GP bandwagon but the more I think about it, I might prefer CDB for internals..

**Comment by jchampio** [comment]
-0.1 on this; it adds to noise during `git blame` and it's a little strange that `src/include/cdb/cdbexplain.h` declares functions with both `cdbexplain` and `gpexplain` prefixes.

**Comment by jimmyyih** [comment]
I am in agreement with Jacob here.  However, if this is merged, it would need to be backported to 5X_STABLE to prevent backport merge conflicts and ingrained ctag autocomplete confusion (I always type cdb and tab autocomplete for ctag searches).

**Comment by joaopapereira** [comment]
The major issue that I see is at this point in time you have GP and CDB prefix depending if it is new code or not. What does CDB mean after all? We are working in Greenplum so our stuff should be called gp, at least in my point of view. It is just a branding thing, but for someone that just arrived this makes all the difference.

> Question is, do we want to wholesale rebrand ourselves GP for everything? Or do we want to wholesale adopt CDB for internals? Since GP and PG are quite visually close, continuing on with CDB might be a way for our code to more stand out in a clear way?

These are good questions, as a matter of fact you are right on the proximity of GP and PG that could become an issue. 
About the rest of the questions in my opinion it is worth to do the rebranding to make the application more consistent.

> -0.1 on this; it adds to noise during git blame

I agree with @jchampio this will create noise on the blame, but change indentation on the files also does it and we doit it none the less.

> it's a little strange that src/include/cdb/cdbexplain.h declares functions with both cdbexplain and gpexplain prefixes.

In this point is fair so I will change that.

About @jimmyyih's point of backporting to 5, I think we should have the new version as a clean slate(this is a loosely held opinion).

**Comment by danielgustafsson** [comment]
> On 7 Sep 2018, at 19:39, João Pereira <notifications@github.com> wrote:
> About @jimmyyih <https://github.com/jimmyyih>'s point of backporting to 5, I think we should have the new version as a clean slate(this is a loosely held opinion).
> 
This I disagree with, we will live with backporting to 5 for a long time and having patches not apply over structure naming will force us to spend a lot of effort for no gain.

**Comment by jchampio** [comment]
> The major issue that I see is at this point in time you have GP and CDB prefix depending if it is new code or not. What does CDB mean after all? We are working in Greenplum so our stuff should be called gp, at least in my point of view. It is just a branding thing, but for someone that just arrived this makes all the difference.

Your latter point (ease of onboarding) is well-taken, but I do actually use the `cdb` prefix as an indication that the code has roots back to the historical archives, and I've learned to associate certain attributes and expectations (quality, maintenance, risk) with that. With `gp`, I expect to be dealing with recent additions, not legacy code.

**Comment by ashwinstar** [comment]
@joaopapereira do we know path forward for this PR?

**Comment by joaopapereira** [comment]
Looks like that people disagree with this change so I am going to close this PR.

**Pull request closed without merging**
