### PR TITLE
Derive Combined Hashed Spec For Outer Joins

### PR DESCRIPTION
**Pull request by THANATOSLAVA**
Issue: Outer join operations enforce unnecessary data redistribution, causing ORCA plan execution to be much longer than planner execution.

Root cause: Unlike inner join operators, outer join operators only derive hashed distribution spec from one out of the two relations. Children nodes not delivering all the distribution properties led to parent nodes enforcing unnecessary data redistribution.

Solution: To mimic inner join distribution spec derivation, derive combined hashed spec for outer join operations from both relations. Eg. 10-relation outer join delivers a combined hashed spec with 10 (including itself) equivalent specs.

Implementation:
1. [CPhysicalLeftOuterHashJoin] -- Override PdsDerive (distribution spec derivation) in CPhysicalJoin. Add a case where both outer and inner relations are hash distributed. Return combined distribution spec if both outer and inner relations are hash distributed. Since NULLs are only added to unmatched rows, set Nullscolocated to false for all equivalent distribution specs of the inner relation.
2. [CPhysicalHashJoin] -- Set Nullscolocated to false when requesting or matching the hash distributed spec.
3. [CDistributionSpecHashed] -- Rewrite Combine function for hash distribution spec with linked list concatenation.
4. [CDistributionSpecHashed] -- Rewrite Copy function with recursion to ensure deep copy.
5. [CDistributionSpecHashed] -- Add Copy function to allow fNullsColocated configuration
6. [CDistributionSpecHashed] -- Enforce nulls colocation for hash redistribution. This is necessary when the non-null hash distribution request is not met.
7. [CPhysicalFullMergeJoin] -- Fix PdsDerive (distribution spec derivation). In full joins, both tables are outer tables. The join output is hash distributed by non-NULL join keys.
8. [CDistributionSpecTest] -- Add function test for hash spec combinination and copy.
9. [regress] -- Update regression test output. Verified plan equivalency.
10. [minidump] -- MDP plan shape update: LOJNonNullRejectingPredicates, LOJReorderWithSimplePredicate, Remove-Distinct-From-Subquery. The rest are SpaceSize and scan order changes. Add LeftJoinNullsNotColocated.

(cherry picked from commit 29f2550cda4dbc7257deb7e75bbdcadfc4d36445)

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by gpopt** [comment]
There are 2 tests failed:
```
The following tests FAILED:
	 64 - gporca_test_CPartTblDPETest (Failed)
	116 - gporca_test_CBitmapTest (Failed)
Errors while running CTest
```

**Review by dgkimura — APPROVED** [review]

**Comment by fishtree1161** [comment]
Sorry, I have a question about this issue.
In this commit, I noticed that we "set Nullscolocated to false when requesting or matching the hash distributed spec" for CPhysicalHashJoin. I wonder why we do this，and I'm worry about more unnecessary redistribute motion for InnerHashJoin.
for example:

drop table if exists t1;
drop table if exists t2;

CREATE TABLE t1 (a1 int, b1 int, c1 int) DISTRIBUTED BY (a1);
CREATE TABLE t2 (a2 int, b2 int, c2 int) DISTRIBUTED BY (a2);

INSERT INTO t1 VALUES(1, 1, 1);
INSERT INTO t2 VALUES(1, 2, 4);

analyze t1;
analyze t2;

EXPLAIN SELECT b2, sum(c1) FROM t1, t2 WHERE a1 = b2 GROUP BY b2 ORDER BY b2;

I get this plan before this commit
image

And, I get this plan after this commit
image

we can see that an additional redistribute motion was appeared, is it necessary?
I found that, when Epet hash distribute required to the InnerHashJoin, fNullsCollocated of the derived one is "false" but required is "true" for hashagg. This "false" was provided by this commit.
Is there something I haven't considered about it，or it's just a bug or something?
Thanks for your times.

**Comment by gpopt** [comment]
@fishtree1161  It is a regression, thanks a lot for your report. We will fix it soon.

**Comment by fishtree1161** [comment]
@gpopt Thanks for your reply.
I find another problem: if join quals contains an 'INDF'(is not distinct from) expression, and the NULL-statistic is outdated, the plan will lead to wrong results.
I think fNullsCollocated should keep true in the 'INDF' join, which is care about 'NULL' values. BTY, 'EXCEPT ALL' which will be cheated as hash-anti-join also have the same problem.
And I also think, optimizer can be suggested by statistics and provide a better plan. But it can't treated statistics as meta data and provide a plan，which may not work correctly in other cases.
For Example:

drop table o1;
drop table o2;
drop table o3;

create table o1 (a int, b int);
create table o2 (a int, b int);
create table o3 (a int, b int);

insert into o1 select generate_series(1,10000), generate_series(1,10000);
analyze o3;
truncate o3;
insert into o3 values (NULL, 1);
-- do not analyze o3 again!!

explain select count(*) from (select * from o1 left join o2 on o1.a = o2.a join o3 on o2.a is not distinct from o3.a) t;
select count(*) from (select * from o1 left join o2 on o1.a = o2.a join o3 on o2.a is not distinct from o3.a) t;
image


truncate o3;
analyze o3;
insert into o3 select NULL, generate_series(1,10000);
-- do not analyze o3 again!!

explain (select o2.a a1, o1.a a2 from o1 left join o2 on o1.a = o2.a) except all (select * from o3);
select count(*) from ((select o2.a a1, o1.a a2 from o1 left join o2 on o1.a = o2.a) except all (select * from o3)) t;
image

**Comment by gpopt** [comment]
@fishtree1161 Thanks so much for your query examples. These are indeed regressions for INDF join condition, we will provide fixes later. Stay tuned. Thanks again.

**Pull request merged**
