### PR TITLE
Skip pq_endmessage() for bgworker.

### PR DESCRIPTION
**Pull request by zhrt123**
## Problem
A notice will be generated when a primary segment shutdown and QD executes a query by SPI_execute(). But the bgworker connecting to the specified database does not establish pq with the client, which causes dead loop in internal_putbytes(). 

A dead loop will happen following these steps:
- Bgworker executes a query by SPI_execute().
- Some QE's generate notices(for example, the crash of this server) and pass them to QD(bgworker).
- The bgworker wants to forward notices to the client in SPI_execute(). But there's no client for bgworker to establish the pq connection, which will cause a dead loop for bgworker.

So that bgworker will not run anymore. For example, the diskquota bgworker will always wait for internal_putbytes(), and can not update table size.

## Solve
We should skip pq_endmessage() when QD is a bgworker.

## Backport
We should backport this PR to 6X_STABLE.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ashwinstar** [comment]
Sorry, the use facing problem isn't clear. What behavior does user see due to this and when?

**Comment by zhrt123** [comment]
> Sorry, the use facing problem isn't clear. What behavior does user see due to this and when?

I've updated the problem and added a test for this PR to describe it.

**Review by Aegeaner — COMMENTED** [review]
Can we make `src/test/modules/worker_spi` workable under GPDB? As a complete PG module, we can avoid the `gpconfig -c shared_preload_libraries -v 'gp_worker_spi'` trick then.

**Comment by zhrt123** [comment]
> Can we make `src/test/modules/worker_spi` workable under GPDB? As a complete PG module, we can avoid the `gpconfig -c shared_preload_libraries -v 'gp_worker_spi'` trick then.

Some queries in `src/test/modules/worker_spi` cannot run on GPDB, if we want to make it workable, we should change the code in `worker_spi.c`.

**Comment by zhrt123** [comment]
This problem is not caused by GPDB, this PR should be closed. Thanks for discussion.

**Pull request closed without merging**
