### PR TITLE
Enable HBase in PXF Regression

### PR DESCRIPTION
**Pull request by shivzone**

### CODE REVIEW

**Comment by Eulerizeit** [comment]
Does this mean we are now going to be installing HBase in our CI?

**Comment by shivzone** [comment]
@Eulerizeit as part of regression_tests_pxf_xxx jobs, we will be running HBase. Any concerns ?
We already have hdfs,hive running as part of that job to certify GPDB external table reads from Hdfs and Hive.

**Comment by Eulerizeit** [comment]
Honestly yes, but they are well outside the scope of this PR.

**Comment by shivzone** [comment]
@Eulerizeit  Feel free to drop a note via email or on #hawq-ud slack channel

**Comment by pivotal-mike** [comment]
@shivzone Can we resolved the merge conflicts and merge this in?

**Comment by lavjain** [comment]
No longer needed.

**Pull request closed without merging**
