### PR TITLE
New GUC optimizer_prefer_scalar_dqa_multistage_agg, and bump optimize…

### PR DESCRIPTION
**Pull request by xinzweb**
…r to 1.611.

### CODE REVIEW

**Comment by xinzweb** [comment]
Is that possible to skip this pull request? There are some issues found in this check-in and need to be fixed.

**Comment by ivannovick** [comment]
Hi @xinzweb how come this is a GUC and the user need to pick manually.  Although customer loves to have a GUC when they have no choice because of bad plan, how come Optimizer can not determine dynamically to apply this or not?

**Comment by vraghavan78** [comment]
@ivannovick by default Orca will always pick three stage agg because the guc is turned on by default. So in the the general case customers will get the better plan. Reason for the GUC was that the cost model was too sensitive and may accidentally pick a two stage agg because of a tie. In the near future, we plan to tune the cost model to replace the GUC. Hope this helps!

**Comment by xinzweb** [comment]
Thanks @vraghavan78. @ivannovick that's exactly the reason. The GUC is to sort of 'FORCE' the 3-stage plans by disabling 2-stage plans. By default, query optimizer will make cost based decision. This GUC is only required when customer cannot get the 3-stage plan as they expected.

**Pull request merged**
