### PR TITLE
fix compile warning in io_limit_gram.y

### PR DESCRIPTION
**Pull request by RMTT**
fix compile warning in io_limit_gram.y

related issure: https://github.com/greenplum-db/gpdb/issues/16038

### CODE REVIEW

**Comment by Tao-T** [comment]
The warnings are caused by the token type (`keyword` type are declared to be `value` type)

Just patch `io_limit_gram.y` as following:

Just follow the parser/Makefile :
```
diff --git a/src/backend/utils/resgroup/io_limit_gram.y b/src/backend/utils/resgroup/io_limit_gram.y
index 70ba3e6538f..dd8d674258d 100644
--- a/src/backend/utils/resgroup/io_limit_gram.y
+++ b/src/backend/utils/resgroup/io_limit_gram.y
@@ -34,7 +34,8 @@
        void io_limit_yyerror(IOLimitParserContext *parser_context, void *scanner, const char *message);
 }
 
-%token <str> ID IOLIMIT_CONFIG_DELIM TABLESPACE_IO_CONFIG_START IOCONFIG_DELIM VALUE_MAX IO_KEY STAR
+%token IOLIMIT_CONFIG_DELIM TABLESPACE_IO_CONFIG_START IOCONFIG_DELIM VALUE_MAX STAR
+%token <str> ID IO_KEY
 %token <integer> VALUE
```

**Review by Tao-T — COMMENTED** [review]
And some minor issues found in makefile:

1) `io_limit_lex.o` do not exists, should be `io_limit_scanner.o`

2) `common.mk` should be included before first local rule so that we can have `all` as default target and fix broken prerequisite during rebuild

3) we can turn on the performance pull-up and checks for lex (refer to `backend/parser`)
and enable the warning fix for flex < 2.5.36


The patch for those mentioned above:

```
diff --git a/src/backend/utils/resgroup/Makefile b/src/backend/utils/resgroup/Makefile
index 6151441952c..76bde8bcf91 100644
--- a/src/backend/utils/resgroup/Makefile
+++ b/src/backend/utils/resgroup/Makefile
@@ -23,14 +23,28 @@ OBJS += io_limit_scanner.o
 OBJS += io_limit_gram.o
 OBJS += cgroup_io_limit.o

+include $(top_srcdir)/src/backend/common.mk
+
 io_limit_gram.h: io_limit_gram.c
        touch $@

 io_limit_gram.c: BISONFLAGS += -d

-io_limit_gram.o io_limit_lex.o cgroup-ops-linux-v2.o: io_limit_gram.h
+io_limit_scanner.c: FLEXFLAGS = -CF -p -p
+io_limit_scanner.c: FLEX_NO_BACKUP=yes
+io_limit_scanner.c: FLEX_FIX_WARNING=yes
+
+# Force these dependencies to be known even without dependency info built:
+io_limit_gram.o io_limit_scanner.o cgroup-ops-linux-v2.o: io_limit_gram.h
+
 else
+
 OBJS += cgroup-ops-dummy.o
-endif

 include $(top_srcdir)/src/backend/common.mk
+
+endif
+
+clean distclean maintainer-clean:
+       rm -f lex.backup
```

**Comment by RMTT** [comment]
> The warnings are caused by the token type (`keyword` type are declared to be `value` type)
> 
> Just patch `io_limit_gram.y` as following:
> 
> Just follow the parser/Makefile :
> 
> ```
> diff --git a/src/backend/utils/resgroup/io_limit_gram.y b/src/backend/utils/resgroup/io_limit_gram.y
> index 70ba3e6538f..dd8d674258d 100644
> --- a/src/backend/utils/resgroup/io_limit_gram.y
> +++ b/src/backend/utils/resgroup/io_limit_gram.y
> @@ -34,7 +34,8 @@
>         void io_limit_yyerror(IOLimitParserContext *parser_context, void *scanner, const char *message);
>  }
>  
> -%token <str> ID IOLIMIT_CONFIG_DELIM TABLESPACE_IO_CONFIG_START IOCONFIG_DELIM VALUE_MAX IO_KEY STAR
> +%token IOLIMIT_CONFIG_DELIM TABLESPACE_IO_CONFIG_START IOCONFIG_DELIM VALUE_MAX STAR
> +%token <str> ID IO_KEY
>  %token <integer> VALUE
> ```

hmmm, seems i don't encountered such warning, can you show some logs?

**Comment by RMTT** [comment]
> > > The warnings are caused by the token type (`keyword` type are declared to be `value` type)
> > > Just patch `io_limit_gram.y` as following:
> > 
> > 
> > hmmm, seems i don't encountered such warning, can you show some logs?
> 
> It's the `unused value` warnings mentioned in issue #16038 :
> 
> They is reported by the compiler because the tokens (e.g. `STAR`, `IOCONFIG_DELIM`...) are declared and treated as `value` type tokens. Indeed they are of type `keyword`.
> 
> So no fake usage in action section but correct the declaration of tokens

it make sense, thanks.

**Comment by RMTT** [comment]
There already has a pr to modify `.gitignore`: https://github.com/greenplum-db/gpdb/pull/16011

**Pull request merged**
