### PR TITLE
Add concourse build pipeline for GPDB

### PR DESCRIPTION
**Pull request by hsyuan**
This change enable GPDB build pipeline with GPORCA on centos6.

Also removed the stub pipeline under /ci folder.

### CODE REVIEW

**Comment by hsyuan** [comment]
@jimmyyih @edespino would you please take a look on this pipeline change? Thanks.

**Comment by xinzweb** [comment]
+1

**Comment by jimmyyih** [comment]
Scripts look fine (assuming the docker instances inherit the VM's correct sysctl and ulimit values).  Other than that, I don't know much about Concourse for the other files.

**Comment by danielgustafsson** [comment]
Should we include a section in the README on how to enable building GPDB in Concourse using this?

**Comment by edespino** [comment]
Not sure if the team generally runs [Pylint](https://www.pylint.org/) against python code, but here is the output of a default non-configured Pylint run for the two python scripts included with this pull request.  They issues identified fall into formatting and documentation areas.

-=e

```
pylint --version
No config file found, using default configuration
pylint 1.5.5, 
astroid 1.4.5
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

pylint build_with_orca.py
No config file found, using default configuration
************* Module build_with_orca
C: 28, 0: Line too long (103/100) (line-too-long)
C: 33, 0: Wrong continued indentation (add 18 spaces).
            "ed",
            ^                 | (bad-continuation)
C: 34, 0: Wrong continued indentation (add 18 spaces).
            "readline-devel",
            ^                 | (bad-continuation)
C: 35, 0: Wrong continued indentation (add 18 spaces).
            "zlib-devel",
            ^                 | (bad-continuation)
C: 36, 0: Wrong continued indentation (add 18 spaces).
            "curl-devel",
            ^                 | (bad-continuation)
C: 37, 0: Wrong continued indentation (add 18 spaces).
            "bzip2-devel",
            ^                 | (bad-continuation)
C: 38, 0: Wrong continued indentation (add 18 spaces).
            "python-devel",
            ^                 | (bad-continuation)
C: 39, 0: Wrong continued indentation (add 18 spaces).
            "apr-devel",
            ^                 | (bad-continuation)
C: 40, 0: Wrong continued indentation (add 18 spaces).
            "libevent-devel",
            ^                 | (bad-continuation)
C: 41, 0: Wrong continued indentation (add 18 spaces).
            "openssl-libs",
            ^                 | (bad-continuation)
C: 42, 0: Wrong continued indentation (add 18 spaces).
            "openssl-devel",
            ^                 | (bad-continuation)
C: 43, 0: Wrong continued indentation (add 18 spaces).
            "libyaml",
            ^                 | (bad-continuation)
C: 44, 0: Wrong continued indentation (add 18 spaces).
            "libyaml-devel",
            ^                 | (bad-continuation)
C: 45, 0: Wrong continued indentation (add 18 spaces).
            "epel-release",
            ^                 | (bad-continuation)
C: 46, 0: Wrong continued indentation (add 18 spaces).
            "htop",
            ^                 | (bad-continuation)
C: 47, 0: Wrong continued indentation (add 18 spaces).
            "perl-Env",
            ^                 | (bad-continuation)
C: 48, 0: Wrong continued indentation (add 18 spaces).
            "perl-ExtUtils-Embed",
            ^                 | (bad-continuation)
C: 49, 0: Wrong continued indentation (add 18 spaces).
            "libxml2-devel",
            ^                 | (bad-continuation)
C: 50, 0: Wrong continued indentation (add 18 spaces).
            "libxslt-devel"])
            ^                 | (bad-continuation)
C: 62, 0: Line too long (103/100) (line-too-long)
C: 75, 0: Wrong continued indentation (add 19 spaces).
         "--enable-orca",
         ^                  | (bad-continuation)
C: 76, 0: Wrong continued indentation (add 19 spaces).
         "--enable-mapreduce",
         ^                  | (bad-continuation)
C: 77, 0: Wrong continued indentation (add 19 spaces).
         "--with-perl",
         ^                  | (bad-continuation)
C: 78, 0: Wrong continued indentation (add 19 spaces).
         "--with-libxml",
         ^                  | (bad-continuation)
C: 79, 0: Wrong continued indentation (add 19 spaces).
         "--with-python",
         ^                  | (bad-continuation)
C: 80, 0: Wrong continued indentation (add 19 spaces).
         "--prefix=/usr/local/gpdb"], cwd="gpdb_src")
         ^                  | (bad-continuation)
C: 84, 0: Wrong continued indentation (add 20 spaces).
        "-j" + str(num_cpus())], cwd="gpdb_src")
        ^                   | (bad-continuation)
C:  1, 0: Missing module docstring (missing-docstring)
C:  8, 0: Missing function docstring (missing-docstring)
C: 24, 0: Missing function docstring (missing-docstring)
C: 27, 0: Missing function docstring (missing-docstring)
C: 65, 0: Missing function docstring (missing-docstring)
C: 73, 0: Missing function docstring (missing-docstring)
C: 82, 0: Missing function docstring (missing-docstring)
C: 86, 0: Missing function docstring (missing-docstring)
C: 91, 0: Missing function docstring (missing-docstring)


Report
======
67 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |1      |NC         |NC         |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
|method   |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
|function |8      |NC         |NC         |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+



Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |70     |58.82 |NC       |NC         |
+----------+-------+------+---------+-----------+
|docstring |28     |23.53 |NC       |NC         |
+----------+-------+------+---------+-----------+
|comment   |4      |3.36  |NC       |NC         |
+----------+-------+------+---------+-----------+
|empty     |17     |14.29 |NC       |NC         |
+----------+-------+------+---------+-----------+



Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |NC       |NC         |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |NC       |NC         |
+-------------------------+------+---------+-----------+



Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |36     |NC       |NC         |
+-----------+-------+---------+-----------+
|refactor   |0      |NC       |NC         |
+-----------+-------+---------+-----------+
|warning    |0      |NC       |NC         |
+-----------+-------+---------+-----------+
|error      |0      |NC       |NC         |
+-----------+-------+---------+-----------+



Messages
--------

+------------------+------------+
|message id        |occurrences |
+==================+============+
|bad-continuation  |25          |
+------------------+------------+
|missing-docstring |9           |
+------------------+------------+
|line-too-long     |2           |
+------------------+------------+



Global evaluation
-----------------
Your code has been rated at 4.63/10


pylint test_with_orca.py 
No config file found, using default configuration
************* Module test_with_orca
C: 28, 0: Line too long (103/100) (line-too-long)
C: 33, 0: Wrong continued indentation (add 18 spaces).
            "sudo",
            ^                 | (bad-continuation)
C: 34, 0: Wrong continued indentation (add 18 spaces).
            "passwd",
            ^                 | (bad-continuation)
C: 35, 0: Wrong continued indentation (add 18 spaces).
            "openssh-server",
            ^                 | (bad-continuation)
C: 36, 0: Wrong continued indentation (add 18 spaces).
            "ed",
            ^                 | (bad-continuation)
C: 37, 0: Wrong continued indentation (add 18 spaces).
            "readline-devel",
            ^                 | (bad-continuation)
C: 38, 0: Wrong continued indentation (add 18 spaces).
            "zlib-devel",
            ^                 | (bad-continuation)
C: 39, 0: Wrong continued indentation (add 18 spaces).
            "curl-devel",
            ^                 | (bad-continuation)
C: 40, 0: Wrong continued indentation (add 18 spaces).
            "bzip2-devel",
            ^                 | (bad-continuation)
C: 41, 0: Wrong continued indentation (add 18 spaces).
            "python-devel",
            ^                 | (bad-continuation)
C: 42, 0: Wrong continued indentation (add 18 spaces).
            "apr-devel",
            ^                 | (bad-continuation)
C: 43, 0: Wrong continued indentation (add 18 spaces).
            "libevent-devel",
            ^                 | (bad-continuation)
C: 44, 0: Wrong continued indentation (add 18 spaces).
            "openssl-libs",
            ^                 | (bad-continuation)
C: 45, 0: Wrong continued indentation (add 18 spaces).
            "openssl-devel",
            ^                 | (bad-continuation)
C: 46, 0: Wrong continued indentation (add 18 spaces).
            "libyaml",
            ^                 | (bad-continuation)
C: 47, 0: Wrong continued indentation (add 18 spaces).
            "libyaml-devel",
            ^                 | (bad-continuation)
C: 48, 0: Wrong continued indentation (add 18 spaces).
            "epel-release",
            ^                 | (bad-continuation)
C: 49, 0: Wrong continued indentation (add 18 spaces).
            "htop",
            ^                 | (bad-continuation)
C: 50, 0: Wrong continued indentation (add 18 spaces).
            "perl-Env",
            ^                 | (bad-continuation)
C: 51, 0: Wrong continued indentation (add 18 spaces).
            "perl-ExtUtils-Embed",
            ^                 | (bad-continuation)
C: 52, 0: Wrong continued indentation (add 18 spaces).
            "libxml2-devel",
            ^                 | (bad-continuation)
C: 53, 0: Wrong continued indentation (add 18 spaces).
            "libxslt-devel"])
            ^                 | (bad-continuation)
C: 65, 0: Line too long (103/100) (line-too-long)
C: 90, 0: Wrong continued indentation (add 19 spaces).
         "--enable-orca",
         ^                  | (bad-continuation)
C: 91, 0: Wrong continued indentation (add 19 spaces).
         "--enable-mapreduce",
         ^                  | (bad-continuation)
C: 92, 0: Wrong continued indentation (add 19 spaces).
         "--with-perl",
         ^                  | (bad-continuation)
C: 93, 0: Wrong continued indentation (add 19 spaces).
         "--with-libxml",
         ^                  | (bad-continuation)
C: 94, 0: Wrong continued indentation (add 19 spaces).
         "--with-python",
         ^                  | (bad-continuation)
C: 95, 0: Wrong continued indentation (add 19 spaces).
         "--prefix=/usr/local/gpdb"], cwd="gpdb_src")
         ^                  | (bad-continuation)
C:103, 0: Line too long (163/100) (line-too-long)
C:106, 0: Line too long (154/100) (line-too-long)
C:109, 0: Line too long (214/100) (line-too-long)
C:  1, 0: Missing module docstring (missing-docstring)
C:  8, 0: Missing function docstring (missing-docstring)
C: 24, 0: Missing function docstring (missing-docstring)
C: 27, 0: Missing function docstring (missing-docstring)
C: 68, 0: Missing function docstring (missing-docstring)
C: 76, 0: Missing function docstring (missing-docstring)
C: 88, 0: Missing function docstring (missing-docstring)
C: 97, 0: Missing function docstring (missing-docstring)
C:102, 0: Missing function docstring (missing-docstring)
C:111, 0: Missing function docstring (missing-docstring)
R:111, 0: Too many return statements (7/6) (too-many-return-statements)


Report
======
83 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |1      |NC         |NC         |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
|method   |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
|function |9      |NC         |NC         |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+



Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |88     |61.54 |NC       |NC         |
+----------+-------+------+---------+-----------+
|docstring |33     |23.08 |NC       |NC         |
+----------+-------+------+---------+-----------+
|comment   |4      |2.80  |NC       |NC         |
+----------+-------+------+---------+-----------+
|empty     |18     |12.59 |NC       |NC         |
+----------+-------+------+---------+-----------+



Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |NC       |NC         |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |NC       |NC         |
+-------------------------+------+---------+-----------+



Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |42     |NC       |NC         |
+-----------+-------+---------+-----------+
|refactor   |1      |NC       |NC         |
+-----------+-------+---------+-----------+
|warning    |0      |NC       |NC         |
+-----------+-------+---------+-----------+
|error      |0      |NC       |NC         |
+-----------+-------+---------+-----------+



Messages
--------

+---------------------------+------------+
|message id                 |occurrences |
+===========================+============+
|bad-continuation           |27          |
+---------------------------+------------+
|missing-docstring          |10          |
+---------------------------+------------+
|line-too-long              |5           |
+---------------------------+------------+
|too-many-return-statements |1           |
+---------------------------+------------+



Global evaluation
-----------------
Your code has been rated at 4.82/10
```

**Comment by xinzweb** [comment]
Thanks @edespino, first time learned about the `pylint`, seems like a good code quality check. We will give it one pass and see if we can fix some of the coding style issues.

@danielgustafsson regarding to build GPDB in concourse, this is for the part in supporting the GPORCA pipeline to build GPDB with GPORCA. And, there should be separate effort to have a complete GPDB concourse pipeline. At this moment, please checkout the GPORCA concourse description at: https://github.com/greenplum-db/gporca#experimental-concourse.

It's still experimental. As soon as we have a complete GPDB pipeline, we will update the GPDB readme. Thanks.

**Comment by hsyuan** [comment]
Only documentation `pylint` remains, all other coding style issues fixed.

```
[scripts: hyuan{concourse}]$ pylint build_with_orca.py
No config file found, using default configuration
************* Module build_with_orca
C:  1, 0: Missing module docstring (missing-docstring)
C:  8, 0: Missing function docstring (missing-docstring)
C: 24, 0: Missing function docstring (missing-docstring)
C: 27, 0: Missing function docstring (missing-docstring)
C: 67, 0: Missing function docstring (missing-docstring)
C: 75, 0: Missing function docstring (missing-docstring)
C: 84, 0: Missing function docstring (missing-docstring)
C: 88, 0: Missing function docstring (missing-docstring)
C: 93, 0: Missing function docstring (missing-docstring)

------------------------------------------------------------------
Your code has been rated at 8.66/10 (previous run: 8.66/10, +0.00)
```

```
[scripts: hyuan{concourse}]$ pylint test_with_orca.py
No config file found, using default configuration
************* Module test_with_orca
C:  1, 0: Missing module docstring (missing-docstring)
C:  8, 0: Missing function docstring (missing-docstring)
C: 24, 0: Missing function docstring (missing-docstring)
C: 27, 0: Missing function docstring (missing-docstring)
C: 70, 0: Missing function docstring (missing-docstring)
C: 78, 0: Missing function docstring (missing-docstring)
C: 90, 0: Missing function docstring (missing-docstring)
C: 99, 0: Missing function docstring (missing-docstring)
C:104, 0: Missing function docstring (missing-docstring)
C:120, 0: Missing function docstring (missing-docstring)

------------------------------------------------------------------
Your code has been rated at 8.77/10 (previous run: 8.38/10, +0.39)
```

**Pull request closed without merging**
