### PR TITLE
Reduce the number of ports used by TCP interconnect from n * m to 2

### LINKED ISSUE #10048: Set SO_REUSEPORT to avoid too many ports taken up by TCP interconnect
Currently, a QE will take up about `n * m` ports during a query execution when gp_interconnect_type is TCP, and `n` is the number of slices, `m` is the number of primary segments. 

We can reduce the number of ports used to 2 with the usage of `SO_REUSEPORT`. More specifically, we can bind all send sockets in QE to the same local address by using SO_REUSEPORT, just like:

```python
import socket
sendsocket1 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sendsocket2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sendsocket1.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
sendsocket2.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
sendsocket1.bind(('', 33333)) # 33333 is a port chose randomly.
sendsocket2.bind(('', 33333)) # also bound at 33333
sendsocket1.connect(('hidva.com', 33330))  # hidva.com:33330 is a receiver QE
sendsocket2.connect(('hidva.com', 33331))  # hidva.com:33331 is another receiver QE
```

Here, we use the same local port to connect two QEs. And `lsof -nPp` shows that all send sockets have bound at the same local address

```
Python zhanyi IPv4 TCP 30.225.140.26:33333->180.76.167.43:33330 (ESTABLISHED)
Python zhanyi IPv4 TCP 30.225.140.26:33333->180.76.167.43:33331 (ESTABLISHED)
```

So we can make the following changes to `setupOutgoingConnection()` in ic_tcp.c to reduce the number of ports used by send sockets.

```diff
diff --git a/src/backend/cdb/motion/ic_tcp.c b/src/backend/cdb/motion/ic_tcp.c
index 9875d7562c..a6ef971cd1 100644
--- a/src/backend/cdb/motion/ic_tcp.c
+++ b/src/backend/cdb/motion/ic_tcp.c
@@ -674,6 +674,29 @@ setupOutgoingConnection(ChunkTransportState *transportStates, ChunkTransportStat
        {                                                       /* connect() EINTR retry loop */
                ML_CHECK_FOR_INTERRUPTS(transportStates->teardownActive);
 
+               int one = 1;
+               if ((setsockopt(conn->sockfd, SOL_SOCKET, SO_REUSEPORT, (char *) &one, sizeof(one))) == -1)
+                       _exit(2);  // just for DEBUG
+               struct sockaddr_in sndaddr;
+               memset(&sndaddr, 0, sizeof(sndaddr));
+               sndaddr.sin_family = AF_INET;
+               sndaddr.sin_addr.s_addr = htonl(INADDR_ANY);  
+               sndaddr.sin_port = g_sendport;  
+               // g_sendport is a static variable, its initial value is htons(0).
+               // In the first call of setupOutgoingConnection, the bind() will choose an unused port randomly, 
+               // and we will get the port via getsockname(), and assign it to g_sendport,
+               // it means that the following call of setupOutgoingConnection() will use the same port.
+               if (bind(conn->sockfd, &sndaddr, sizeof(sndaddr)) < 0)
+                       _exit(3);  // just for DEBUG
+               if (g_sendport == 0) {
+                       struct sockaddr local_addr;
+                       socklen_t len = sizeof(sockaddr);
+                       if (getsockname(conn->sockfd, &local_addr, &len) != 0)
+                               _exit(4);
+                       struct sockaddr_in *laddr = (struct sockaddr_in*)&local_addr;
+                       g_sendport = laddr->sin_port;                   
+               }
+
                n = connect(conn->sockfd, addrs->ai_addr, addrs->ai_addrlen);
 
                /* Non-blocking socket never connects immediately, but check anyway. */
```

### PR DESCRIPTION
**Pull request by hidva**
see [issue10048](https://github.com/greenplum-db/gpdb/issues/10048) for detail. Fix #10048 

We will use the following SQL as an example to demonstrate the effect.

```
postgres=# explain analyze select j, count(1) from aocs group by j;
                                                                QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=3.33..5.00 rows=100 width=12) (actual time=8.709..9.055 rows=99 loops=1)
   ->  HashAggregate  (cost=3.33..3.67 rows=33 width=12) (actual time=5.171..5.311 rows=37 loops=1)
         Group Key: j
         Extra Text: (seg0)   Hash chain length 1.5 avg, 3 max, using 25 of 32 buckets; total 0 expansions.
         ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..3.00 rows=67 width=4) (actual time=4.746..4.819 rows=76 loops=1)
               Hash Key: j
               ->  Seq Scan on aocs  (cost=0.00..1.67 rows=67 width=4) (actual time=3.265..3.403 rows=76 loops=1)
 Planning time: 3.459 ms
   (slice0)    Executor memory: 40K bytes.
   (slice1)    Executor memory: 89K bytes avg x 3 workers, 89K bytes max (seg0).
   (slice2)    Executor memory: 147K bytes avg x 3 workers, 147K bytes max (seg0).
 Memory used:  128000kB
 Optimizer: Postgres query optimizer
 Execution time: 148.815 ms
(14 rows)
```

Now we attach QE 12742 and set a breakpoint on `ExecutorRun()`.

```
$ ps -u zhanyi -o pid,cmd  | grep -F con10
 12707 postgres:  7000, zhanyi postgres [local] con10 cmd52 EXPLAIN
 12709 postgres:  7002, zhanyi postgres 172.17.0.4(59760) con10 seg0 cmd53 slice1 MPPEXEC SELECT
 12710 postgres:  7003, zhanyi postgres 172.17.0.4(54472) con10 seg1 cmd53 slice1 MPPEXEC SELECT
 12711 postgres:  7004, zhanyi postgres 172.17.0.4(58626) con10 seg2 cmd53 slice1 MPPEXEC SELECT
 12741 postgres:  7002, zhanyi postgres 172.17.0.4(59840) con10 seg0 idle
 12742 postgres:  7003, zhanyi postgres 172.17.0.4(54552) con10 seg1 cmd53 slice2 MPPEXEC SELECT
 12743 postgres:  7004, zhanyi postgres 172.17.0.4(58706) con10 seg2 idle
```

The TCP Listener Port corresponding to the 3 QEs in slice1 are as follows:

```
$ lsof -nPp 12709 | grep -F LISTEN
postgres 12709 zhanyi    4u     IPv4 726122462       0t0       TCP 172.17.0.4:52225 (LISTEN)
$ lsof -nPp 12710 | grep -F LISTEN
postgres 12710 zhanyi    4u     IPv4 726126504       0t0       TCP 172.17.0.4:38797 (LISTEN)
$ lsof -nPp 12711 | grep -F LISTEN
postgres 12711 zhanyi    4u     IPv4 726124316       0t0       TCP 172.17.0.4:49975 (LISTEN)
```

Now we can see that the QE 12742 in slice2 uses the same local port (52331) when connecting the QEs in slice1.

```
$ lsof -nPp 12742 | grep -F ESTABLISHED
postgres 12742 zhanyi    7u     IPv4 726152318       0t0       TCP 127.0.0.1:52331->172.17.0.4:52225 (ESTABLISHED)
postgres 12742 zhanyi    8u     IPv4 726152319       0t0       TCP 127.0.0.1:52331->172.17.0.4:38797 (ESTABLISHED)
postgres 12742 zhanyi   10u     IPv4 726139415       0t0       TCP 172.17.0.4:7003->172.17.0.4:54552 (ESTABLISHED)
postgres 12742 zhanyi   13u     IPv4 726152320       0t0       TCP 127.0.0.1:52331->172.17.0.4:49975 (ESTABLISHED)
```

### CODE REVIEW

**Comment by hlinnaka** [comment]
Using SO_REUSEPORT for this seems surprising. All the documentation I can find on it suggests that its purpose is to allow multiple processes to *listen* on the same port. You're using it to reuse the same *outgoing* port number for multiple connections. Does it really work for that purpose? What happens if you create two sockets, bind them to the same local port number with SO_REUSEPORT, and use both sockets to connect to the same remote port? Maybe that situation doesn't arise with the interconnect but it seems a bit weird.

Also, why do you force the outgoing connections to use the same local port number that's used to listen for incoming connections?

Would setting `net.ipv4.tcp_tw_reuse` solve this problem?

**Comment by hidva** [comment]
@hlinnaka 
> Does it really work for that purpose? 

It does work, you can see the example above.

> What happens if you create two sockets, bind them to the same local port number with SO_REUSEPORT, and use both sockets to connect to the same remote port? Maybe that situation doesn't arise with the interconnect but it seems a bit weird.

It will fail as follow, and as you said, this does not happen in interconnect.

```python
>>> import socket
>>> sendsocket1 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> sendsocket1.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
>>> sendsocket1.bind(('', 33333))
>>> sendsocket1.connect(('hidva.com', 33333))
>>>
>>> sendsocket2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> sendsocket2.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
>>> sendsocket2.bind(('', 33333))
>>> sendsocket2.connect(('hidva.com', 33333))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
```

**Comment by hidva** [comment]
@hlinnaka 

> Also, why do you force the outgoing connections to use the same local port number that's used to listen for incoming connections?

UDPIFC has caused a lot of problems in our production environment because of its overuse of IP fragmentation. We have to drastically increase the value of `net.ipv4.ipfrag_high_thresh` and `net.ipv4.ipfrag_time` to alleviate it. Of course, we can reduce the value of `gp_max_packet_size` to MTU, but the performance will be greatly affected in this way. 

So we have to use TCP interconnect, and TCP interconnect uses a much higher number of ports than UDPIFC, so we submit this PR to make TCP interconnect use the same port number as UDPIFC.

> Would setting net.ipv4.tcp_tw_reuse solve this problem?

We think `tcp_tw_reuse` cannot solve the problem of TCP interconnect using too many port numbers.

**Comment by hlinnaka** [comment]
On 08/09/2020 18:56, 盏一 wrote:
> @hlinnaka
> 
>> Also, why do you force the outgoing connections to use the same
>> local port number that's used to listen for incoming connections?
> 
> UDPIFC has caused a lot of problems in our production environment
> because of its overuse of IP fragmentation. We have to drastically
> increase the value of `net.ipv4.ipfrag_high_thresh` and
> `net.ipv4.ipfrag_time` to alleviate it. Of course, we can reduce the
> value of `gp_max_packet_size` to MTU, but the performance will be
> greatly affected in this way.
> 
> So we have to use TCP interconnect, and TCP interconnect uses a much
> higher number of ports than UDPIFC, so we submit this PR to make TCP
> interconnect use the same port number as UDPIFC.
Never mind, I misread the patch. I thought you were using the same port 
number for outgoing connections and incoming connections, but you're 
not. ICsenderPort is different from the listener port.

>> Would setting net.ipv4.tcp_tw_reuse solve this problem?
> 
> We think `tcp_tw_reuse` cannot solve the problem of TCP interconnect using too many port numbers.

Have you tried it? My understanding is that the option exists to solve 
precisely that problem.

- Heikki

**Comment by hidva** [comment]
@hlinnaka 

> Have you tried it? My understanding is that the option exists to solve
precisely that problem.

`tcp_tw_reuse` is used to reuse the port in `TIME_WAIT` state, it cannot reuse port in `ESTABLISHED` state. 

Suppose we have a cluster which has 600 primary segments, there are 4 segments on one host. And now we run a query which has 50 slices. 

Without `SO_REUSEPORT` mentioned in this PR, each QE will use 50 * 600 ports, and the query can not run due to insufficient ports.

With `SO_REUSEPORT`, each QE will only use 2 ports, query will run normally.

**Comment by hlinnaka** [comment]
Note that there was a similar discussion wrt. the QD -> QE connections at https://github.com/greenplum-db/gpdb/pull/577. The solution there was to set SO_REUSEADDR on the outgoing socket before calling connect(). Would that do the trick for the interconnect, too?

**Comment by hidva** [comment]
@hlinnaka 
> Would that do the trick for the interconnect, too?

Yes, it works.

**Comment by hlinnaka** [comment]
> @hlinnaka
> 
> > Have you tried it? My understanding is that the option exists to solve
> > precisely that problem.
> 
> `tcp_tw_reuse` is used to reuse the port in `TIME_WAIT` state, it cannot reuse port in `ESTABLISHED` state.
> 
> Suppose we have a cluster which has 600 primary segments, there are 4 segments on one host. And now we run a query which has 50 slices.
> 
> Without `SO_REUSEPORT` mentioned in this PR, each QE will use 50 * 600 ports, and the query can not run due to insufficient ports.

A TCP connection is identified by the quadruplet (local port, local IP address, remote port, remote IP address). The same local port number can be used for multiple outgoing connections, as long as remote IP address or port is different. The kernel knows that, and will reuse the same local port number for two outgoing connections.

Usually it's the `TIME_WAIT` connections that lead to running out of port numbers.

**Comment by hidva** [comment]
I have done a test, and you are right! We don't need this PR now, I will close it. 

Thanks for your reply.

**Pull request closed without merging**
