### PR TITLE
Fix the memory leak in _bitmap_xlog_insert_bitmapwords()

### PR DESCRIPTION
**Pull request by interma**
An obvious memory leak in `_bitmap_xlog_insert_bitmapwords()`, it caused the memory usage of startup process to continue to grow. We already have a user to report it and it can be reproduced locally.

* Fix it in the first commit.
* In the process of checking this issue, we found another memory leak related commit of upstream (https://github.com/postgres/postgres/commit/0bd56172b2871e94c0d7115ffbf430308317ac49), also ported it in the second commit.

(need to backport to 6x)

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by soumyadeep2007 — COMMENTED** [review]
I can understand the change in `_bitmap_xlog_insert_bitmapwords`, but why are we adding pfrees in upstream code paths?

I didn't check but hose upstream variables are probably implicitly pfreed when their MemoryContext gets cleared.

If those pfrees were added as part of an upstream fix, please backport the fix instead.

**Comment by soumyadeep2007** [comment]
Lol I clearly didnt have my morning coffee

**Comment by interma** [comment]
Dev pipeline (passed): https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-fix_memleak_bitmapxlog-rhel8

**Comment by haolinw** [comment]
LGTM.

**Review by haolinw — APPROVED** [review]

**Pull request merged**
