### PR TITLE
Clean up GDD's gang after acquiring the lock status

### PR DESCRIPTION
**Pull request by dreamedcheng**
Not that commit 1735b5ca3dd37d83e58d3fd4d5da3d31d4d948dc remove `DisconnectAndDestroyAllGangs` in `gp_dist_wait_status` to avoid error when calling it in transaction blcok. However, it will cause GDD's gang exists all the time when the cluster is up (with GDD enabled).

There is no need for the long existence of GDD's gang, and it will further cause utility tools like `gp_toolkit.__gp_check_orphaned_files_func` throw `There is a client session running on one or more segment.Aborting...` ERROR.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by huansong — APPROVED** [review]
Thanks for your contribution. LGTM. I think cleaning it up is the right thing to do. GDD QEs are idle most of the time besides to run gp_dist_wait_status once a while (2 minutes by default). So definitely seems not worth keeping them around.

Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/pr-16903

**Comment by ashwinstar** [comment]
If frequency is every 2 mins - isn't it better to just leave the process in place and avoid fork and such overhead every-time to create connection / gang and query such simple SQL (acts like connection poller :))?

**Comment by huansong** [comment]
Yes could avoid fork overheads. But my impression was that 2 minutes is a rather long time to amortize the overheads (I could very well be wrong). Compared to having to keep all the backend memory exclusively for the simple query, seems the former one is more resource-friendly?

**Comment by dreamedcheng** [comment]
@huansong 
Do we have plan to merge this PR? 
An alternative way is that, we can modify the check logic of running session in `gp_toolkit.__gp_check_orphaned_files_func ` by adding condition `state <> 'idle'` to exclude idle session.

**Comment by ashwinstar** [comment]
> @huansong 
> Do we have plan to merge this PR? 
> An alternative way is that, we can modify the check logic of running session in `gp_toolkit.__gp_check_orphaned_files_func ` by adding condition `state <> 'idle'` to exclude idle session.

That's the route we should be taking. Any downsides to report from it?

**Comment by huansong** [comment]
> Any downsides to report from it?

Not that I'm aware of. Checking **any** concurrent session was intended to be an over-restriction for max safety. We mainly just wanted to avoid running with idle transaction (see https://github.com/greenplum-db/gpdb/pull/16428). In hintsight, checking all idle sessions was probably not a good idea - not just GDD gang, but also GPCC or other user admin activity could all be a pain in usage. I'm OK with relaxing that aspect by putting `state <> 'idle'`. 

@dreamedcheng thanks for the suggestion! Feel free to open a new PR for the fix (P.S. no need for new gp_toolkit minor version, we can just modify `gp_toolkit--1.4--1.5.sql` that you just added). Thanks.

> That's the route we should be taking. 

Now this becomes a completely separate issue. I still hope we can give it some more thoughts about what should be the expected behavior for the GDD gang. To me it seems it was not an intentional decision to keep the gang, but just an inadvertent outcome of fixing https://github.com/greenplum-db/gpdb/pull/13826. We actually ran with the behavior of destroying gang longer than the behavior of keeping the gang. 

As a reference, there's no other types of background process where we keep gang for. For example dtx recovery gang comes and go as needed. Of course, the difference is that dtx recovery is on-demand. If the system runs fine for a long time it doesn't make any sense to keep the gang around. In the case of GDD, we run it periodically so there's more reason to keep it. And if the user sets a more frequent interval like 10 seconds, we should definitely keep the gang (but in reality no one would sets such low value because there would be many false alarm I imagine).

But I just hope we can define the expectation clearly. My main concern was just the memory as mentioned: the backends are kept exclusively for GDD. So it's not really like a connection pooler per se. Other client activity won't be utilizing those memory at all. So it's mainly a trade-off between the forking overheads and the memory efficiency.

**Comment by dreamedcheng** [comment]
@huansong 
Thanks for your detailed explanation.

I proposed a new PR https://github.com/greenplum-db/gpdb/pull/17220 to solve this problem.

Close this PR.

**Pull request closed without merging**
