### PR TITLE
6X back port: Remove unused faulinject facility

### PR DESCRIPTION
**Pull request by asimrp**
This was a redundant fault injection facility we had in the codebase. It has not been used and offers only a subset of the functionality offerred by gp_inject_fault contrib module.  This commit removes it as much as possible, without changing catalog because there is no room for another beta release in 6.X release cycle.  Commit ec0287a04168 removes it fully from master.

### CODE REVIEW

**Comment by asimrp** [comment]
Original PR that was merged in master: #8497

**Comment by asimrp** [comment]
Looking into the pre-open-source repository, I found that the feature was introduced to simulate complicated test scenarios.
```
commit dc7ca9b0c635b40f5dd4b9dfd94859aa04479b34
Date:   Mon May 19 09:09:38 2008 -0800

    Add fault injection.
    
 cdb-pg/src/backend/utils/error/faultinject.c | 96 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 96 insertions(+)
```
It was found to fall short and a new fault injection feature was introduced.
```
commit 84765cddf25d568d71add9b75942524c7eb134d4
Date:   Wed Jan 20 21:08:00 2010 -0800

    Fault injection infrastructure that can be exercised by Fault Injector utility "gpfaultinjector".
    
 cdb-pg/src/backend/utils/misc/faultinjector.c | 741 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 741 insertions(+)
```
We made a contrib module out of the new feature which is currently in use as `gp_inject_fault()`.  I was not able to dig out specific tests from the pre-open-source Greenplum repository, most likely because the tests used to reside in a different repository.

I am certain that the code being removed was used, if at all, by old tests that are already non-existent.

**Comment by ashwinstar** [comment]
I am on fence for this. I feel it's okay to leave it alone and not worth the cleanup in STABLE branch. But I am even okay if you feel we should do it. It didn't cause any confusion or issues so far and anyways deleted from master so leaving doesn't seem will cause any problem.

**Comment by asimrp** [comment]
Looking at it after a long time, I also feel it's not worth the trouble.  We may revisit this if / when stripping out faultinjector stuff from released binaries.

**Pull request closed without merging**
