### PR TITLE
pg_upgrade

### PR DESCRIPTION
**Pull request by danielgustafsson**
This is a mostly complete patch for binary upgrades of GPDB 4.3->5.0 using the upstream utility `pg_upgrade` backported from 9.0.23, complete enough to get eyes on it reviewing.

Known issues remaining include:

- Toasted NUMERIC attributes must be untoasted before conversion
- Tests and pipeline integration
- Upgrading from 5.0 to 5.0 is currently not working
- 4.3 clusters lack array types for relation types, creating them in 5.0 breaks on OID dispatching
- VACUUM must rewrite AO/AOCS tables where all segments are allocated

The commits will need to be squashed into something more manageable before pushing, but for now they can assist in reviewing.

Work by @hlinnaka, @davecramer and me.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Wow, that is a lot of code! :-)

I would suggest squashing this into closer-to-final set of commits before people spend a lot of time reviewing this. Are there parts that could be cherry-picked and pushed separately? (efdf0f9 at least seems like a candidate)

**Comment by hlinnaka** [comment]
I cherry-picked and pushed 74c5403 to master.

**Comment by hlinnaka** [comment]
Also cherry-picked and pushed efdf0f9b.

**Comment by danielgustafsson** [comment]
Makes sense, not sure if there are too many more commits that can be pulled out now. I can take a stab at squashing the leftovers into a more concrete set of commits for getting into master.

**Comment by hlinnaka** [comment]
On 11/18/2016 02:08 PM, Daniel Gustafsson wrote:
> Makes sense, not sure if there are too many more commits that can be
> pulled out now. I can take a stab at squashing the leftovers into a
> more concrete set of commits for getting into master.

I think the "long options" patches could be pulled into a separate PR. 
That's quite independent, and IMHO a good thing to do regardless of 
pg_upgrade. But that's pretty much it.

- Heikki

**Comment by danielgustafsson** [comment]
Pushed a rebased branch on top of master which implements the array type OID dispatching from the QD to the QEs. The mechanism is clunky but with proper scripting around it the clunkyness should be manageable, see commit 912ca66 for details.

Some commits have also been squashed where it made sense, the final set is yet to be squashed together.

**Comment by hlinnaka** [comment]
Is there a risk, that when restoring the dump in the QD, the system assigns an OID for an array type, that's used by another type later in the dump file?



On 24 November 2016 13:04:28 EET, Daniel Gustafsson <notifications@github.com> wrote:
>Pushed a rebased branch on top of master which implements the array
>type OID dispatching from the QD to the QEs. The mechanism is clunky
>but with proper scripting around it the clunkyness should be
>manageable, see commit 912ca66 for details.
>
>Some commits have also been squashed where it made sense, the final set
>is yet to be squashed together.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/1340#issuecomment-262750249

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danielgustafsson** [comment]
Thats a good point, there are no safeguards for that. Any ideas on how to deal with that? Avoiding to create the array type in the CREATE TABLE statement and doing them all at the tail end of the restore seems the safe option but I wonder how intrusive such a codepath will be?

**Comment by hlinnaka** [comment]
On 11/24/2016 01:42 PM, Daniel Gustafsson wrote:
> Thats a good point, there are no safeguards for that. Any ideas on
> how to deal with that? Avoiding to create the array type in the
> CREATE TABLE statement and doing them all at the tail end of the
> restore seems the safe option but I wonder how intrusive such a
> codepath will be?

We have all the OIDs in the preassigned_oids list, before we create any 
objects, right? So we could hack GetNewObjectId() (or whatever the 
function to get a new oid is called), to check and skip over any OIDs in 
that list.

- Heikki

**Comment by danielgustafsson** [comment]
> On 24 Nov 2016, at 13:03, Heikki Linnakangas <notifications@github.com> wrote:
> 
> On 11/24/2016 01:42 PM, Daniel Gustafsson wrote:
> > Thats a good point, there are no safeguards for that. Any ideas on
> > how to deal with that? Avoiding to create the array type in the
> > CREATE TABLE statement and doing them all at the tail end of the
> > restore seems the safe option but I wonder how intrusive such a
> > codepath will be?
> 
> We have all the OIDs in the preassigned_oids list, before we create any 
> objects, right? So we could hack GetNewObjectId() (or whatever the 
> function to get a new oid is called), to check and skip over any OIDs in 
> that list.

Not really, the preassigned_oids list is in general populated with the Oid to
use just before it’s used like:

	SELECT preassign_oid_for_<object>(oid);
	CREATE <object>;

To get all the preassignments first we’d either need to hack pg_dump to reorder
them (seems intrusive) or hack pg_upgrade such that the splitting step pulls
them out and puts them first (hacky and kludgy).  Is there a third better
option I’m missing?

**Comment by hlinnaka** [comment]
On 11/24/2016 02:18 PM, Daniel Gustafsson wrote:
>
>> On 24 Nov 2016, at 13:03, Heikki Linnakangas <notifications@github.com> wrote:
>>
>> On 11/24/2016 01:42 PM, Daniel Gustafsson wrote:
>>> Thats a good point, there are no safeguards for that. Any ideas on
>>> how to deal with that? Avoiding to create the array type in the
>>> CREATE TABLE statement and doing them all at the tail end of the
>>> restore seems the safe option but I wonder how intrusive such a
>>> codepath will be?
>>
>> We have all the OIDs in the preassigned_oids list, before we create any
>> objects, right? So we could hack GetNewObjectId() (or whatever the
>> function to get a new oid is called), to check and skip over any OIDs in
>> that list.
>
> Not really, the preassigned_oids list is in general populated with the Oid to
> use just before it’s used like:
>
> 	SELECT preassign_oid_for_<object>(oid);
> 	CREATE <object>;
>
> To get all the preassignments first we’d either need to hack pg_dump to reorder
> them (seems intrusive) or hack pg_upgrade such that the splitting step pulls
> them out and puts them first (hacky and kludgy).  Is there a third better
> option I’m missing?

Hmm. Hacking pg_dump to move the preassignments to the beginning seems 
like the easiest option. It might be best to remove all the upstream 
code to emit those OID-assignment calls, and replace them with a single 
function that gets the OIDs for all types. I.e. do "SELECT oid, 
typnamespace, typname FROM pg_type" and loop over the result set, 
printing "SELECT preassign_oid_for_type(...)" calls. That would be 
problematic, if we were doing a partial dump, but this is only used for 
pg_upgrade, which dumps all objects. Might be best to do it that way for 
all objects, not just types, for consistency.

Third option:

Assign new OIDs for the to-be-created array types in the old cluster, in 
pg_dump. We can't actually create the objects, because you can't create 
array types for composite types before 8.3, and we don't want to modify 
the old cluster anyway, but we could still call GetNewId() to get a free 
OID for each. I think I would prefer moving the preassignments to the 
beginning of the dump, though.

- Heikki

**Comment by danielgustafsson** [comment]
The latest update to this branch is now a rebased set of commits that pass the CI pipeline for upgrading 4.3 to 5.0. A brief documentation has been added in [README.gpdb](https://github.com/danielgustafsson/gpdb/blob/pg_upgrade/contrib/pg_upgrade/README.gpdb) to outline the process and how pg_upgrade is different for Greenplum than in upstream. While there are a few items left, this branch is ready to be merged into master to get more eyes on the code. The TODO on being feature complete is:

- Toasted NUMERIC attributes must be untoasted before conversion
- Upgrading from 5.0 to 5.0 is currently not working
- VACUUM must rewrite AO/AOCS tables where all segments are allocated
- Ensure Oid allocation for array types is safe (see discussion above)
- Ensure that no distributed transactions are in progress when upgrade starts

Work by @hlinnaka, @danielgustafsson and @davecramer

**Comment by danielgustafsson** [comment]
Pushed a rebase on top of current master with all the recent work squashed into the neat set of commits intended for merging to master. While there are TODO items left it's time to merge this to master to avoid running this branch longer. Remaining work can be done as PR's against master as per usual.

The cache of array types is left as a separate commit since it can be argued whether we should keep it or not. If we are keeping it then we should probably extend it to cache normal types as well and trade memory usage for repeated queries for large clusters. 

Ping @hlinnaka, @davecramer, @Eulerizeit

**Comment by hlinnaka** [comment]
On 12/19/2016 12:00 PM, Daniel Gustafsson wrote:
> Pushed a rebase on top of current master with all the recent work
> squashed into the neat set of commits intended for merging to master.
> While there are TODO items left it's time to merge this to master to
> avoid running this branch longer. Remaining work can be done as PR's
> against master as per usual.

Yep, go for it!

- Heikki

**Comment by danielgustafsson** [comment]
Ping @chrishajas @Chibin - as a heads up: here are some more pg_dump patches. This PR will add --binary-upgrade to pg_dump, a mode specifically tailored for preassigning Oids during database upgrades using pg_upgrade. There are few user visible parts here, if any, but there are small general optimizations too which might be of interest.

**Comment by danielgustafsson** [comment]
At long last, this has been pushed to master. Thanks for hard work and reviews!

**Pull request merged**
