### PR TITLE
Move grouping tests from TINC.

### PR DESCRIPTION
**Pull request by hlinnaka**

### CODE REVIEW

**Comment by hlinnaka** [comment]
There is one problem with this. With ORCA enabled, I'm getting random errors like this from this test:
```
  select 'a', * from ((SELECT SUM(sale.pn) as g1 FROM product, sale WHERE product.pn=sale.pn GROUP BY ROLLUP((sale.pn,product.pname)) ORDER BY g1) UNION (SELECT sale.pn FROM sale))a;
! ERROR:  indexqual doesn't have key on left side (nodeIndexscan.c:810)
```
The error message is always the same, but the query where it happens varies. Sometimes 2-3 queries fail with the same error in a test run. 

That's weird, because the same queries work fine when run in TINC. There are some differences, however:
1. The test tables in TINC have no indexes. The corresponding tables in the main test suite, by 'olap_setup' test, have indexes on primary keys.
2. In TINC, each query is run in a separate session (I believe). In this PR, they are all run in the same session.

It's probably the presence of indexes that make it fail.

In any case, that is a bug, which this PR happened to expose. We should get that fixed. I'll refrain from merging this PR until it is fixed. Hopefully it gets fixed quickly.

**Comment by hlinnaka** [comment]
Anyway, that bug is not this PR's fault, so please review, ignoring that issue for now.

**Comment by hlinnaka** [comment]
One question is, should we run these tests against tables that don't have indexes, like the TINC test used to, to accurately emulate the old tests? IMHO no, it's better to run them against the tables with indexes, like this PR does, because that will surely exercise more code. Might exercise slightly different code paths, but more of them overall. To be really paranoid, you could argue that we should do both, but I'm not that paranoid. It is easy to go overboard, and explode the amount of tests in a combinatorial fashion, if you start doing that.

**Comment by vraghavan78** [comment]
Thanks for bring the issue with the indexed case. Will create a story and work on it soon.

**Comment by d** [comment]
To make the issue more self-contained, I copied the DDL's required into the description of #1893 . However, I *cannot* reproduce ...

**Comment by hlinnaka** [comment]
Ah, never mind, I found the cause: I used a custom build of ORCA, with some hacks that are apparently a few bricks shy of a load :-). With stock 2.7.0 checkout of ORCA, it works

**Comment by hlinnaka** [comment]
So, now that issue has been settled, can you review this, please?

**Comment by hlinnaka** [comment]
Rebased. @d, @vraghavan78, can you have a look at this one, please? The error I saw was a red herring, this is ready to go.

**Comment by bhuvnesh2703** [comment]
Looks Good. +1, ship it

**Pull request merged**
