### PR TITLE
Add 24h timeout for all icw jobs

### PR DESCRIPTION
**Pull request by khuddlefish**
Authored-by: Karen Huddleston <khuddleston@vmware.com>

### CODE REVIEW

**Comment by ashwinstar** [comment]
4h is too less to be able to notice hangs and investigate the issue.

I think we need a little more reasonable timeout to provide enough time to notice hangs and debug, but if it goes unnoticed then doesn't become a pain to manually require cleanup. Hence, think maybe 24 or 36 hours possible could be a reasonable number.

**Comment by khuddlefish** [comment]
We can make it longer to give folks time to notice and debug. I'd probably aim for 24 hours then.

**Review by 50wu — APPROVED** [review]
Do we need to add the timeout feature for the 6X_STABLE pipeline as well?

**Comment by khuddlefish** [comment]
Yes @50wu I plan to do that next. and 5x also

**Comment by khuddlefish** [comment]
Backport PRs for 5x https://github.com/greenplum-db/gpdb/pull/13852 and 6x https://github.com/greenplum-db/gpdb/pull/13853

**Pull request merged**
