### PR TITLE
Behave CLI tests: use n1-standard-2 for ccp clusters

### PR DESCRIPTION
**Pull request by dkrieger-pvtl**
The recent sysctl changes(42930ed) modified the ccp nodes.
Somehow, this causes memory issues on our ccp nodes for
Behave.  There was a recent, similar modification for
gpexpand(6f49463).

I will also add in the generated yml file but don't think it deserves running the pipeline again.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by kalensk** [comment]
Need to add the generated pipeline.

**Comment by dkrieger-pvtl** [comment]
This is temporary, and we'll merge a sysctl-based fix shortly thereafter.

**Comment by bradfordboyle** [comment]
> This is temporary, and we'll merge a sysctl-based fix shortly thereafter.

Does that mean you plan to revert this change after the sysctl-based fix lands?

**Comment by dkrieger-pvtl** [comment]
> > This is temporary, and we'll merge a sysctl-based fix shortly thereafter.
> 
> Does that mean you plan to revert this change after the sysctl-based fix lands?

Yes...actually, to revert it in the same PR that does the sysctl-based fix.

**Comment by kmacoskey** [comment]
Scratch that LGTM. 

I see the template changes but not the generated file.

**Comment by slari-pivotal** [comment]
We have made the changes to the master pipeline as well.

**Comment by asimrp** [comment]
Merged and set gpdb_master as well as gpdb_master_without_assert pipelines with the new instance type.

**Pull request merged**
