### PR TITLE
Remove the gpinitsystem extra symbol

### PR DESCRIPTION
**Pull request by yanchaozhong**
Remove extra symbol (#) that has no relation with others in the gpinitsystem.

$ gpinitsystem -c gpinitsystem_config
...
...gpinitsystem:node:gp-[INFO]:---------------------------------------
...gpinitsystem:node:gp-[INFO]:-Master Configuration
...gpinitsystem:node:gp-[INFO]:---------------------------------------
...gpinitsystem:node:gp-[INFO]:-Master instance name       = EMC Greenplum DW
...gpinitsystem:node:gp-[INFO]:-Master hostname               = node
...gpinitsystem:node:gp-[INFO]:-Master port                        = 9432
...gpinitsystem:node:gp-[INFO]:-Master instance dir            = /data1/gp/master/gpseg-1
...gpinitsystem:node:gp-[INFO]:-Master LOCALE                  = en_US.utf8
...gpinitsystem:node:gp-[INFO]:-Greenplum segment prefix= gpseg
...gpinitsystem:node:gp-[INFO]:-Master Database                = 
...gpinitsystem:node:gp-[INFO]:-Master connections            = 250
...gpinitsystem:node:gp-[INFO]:-Master buffers                    = 128000kB
...gpinitsystem:node:gp-[INFO]:-Segment connections         = 750
...gpinitsystem:node:gp-[INFO]:-Segment buffers                 = 128000kB
...gpinitsystem:node:gp-[INFO]:-Checkpoint segments         = 8
...gpinitsystem:node:gp-[INFO]:-Encoding                             = UNICODE
...gpinitsystem:node:gp-[INFO]:-Postgres param file             = Off
...gpinitsystem:node:gp-[INFO]:-Initdb to be used                = /usr/local/gp/bin/initdb
...gpinitsystem:node:gp-[INFO]:-GP_LIBRARY_PATH is          = /usr/local/gp/lib
...gpinitsystem:node:gp-[INFO]:-HEAP_CHECKSUM is           = on
...gpinitsystem:node:gp-[INFO]:-Ulimit check                        = Passed
...gpinitsystem:node:gp-[INFO]:-Array host connect type     = Single hostname per node
...gpinitsystem:node:gp-[INFO]:-Master IP address [1]          = ::1
...gpinitsystem:node:gp-[INFO]:-Master IP address [2]          = 192.168.59.106
...gpinitsystem:node:gp-[INFO]:-Master IP address [3]          = fe80::20c:29ff:feae:ff82
...gpinitsystem:node:gp-[INFO]:-Standby Master                  = Not Configured
...gpinitsystem:node:gp-[INFO]:-Primary segment **#**             = 1
...gpinitsystem:node:gp-[INFO]:-Total Database segments   = 1
...gpinitsystem:node:gp-[INFO]:-Trusted shell                       = ssh
...gpinitsystem:node:gp-[INFO]:-Number segment hosts      = 1
...gpinitsystem:node:gp-[INFO]:-Mirror port base                 = 50015
...gpinitsystem:node:gp-[INFO]:-Replicaton port base          = 41015
...gpinitsystem:node:gp-[INFO]:-Mirror replicaton port base= 51015
...gpinitsystem:node:gp-[INFO]:-Mirror segment **#**               = 1
...gpinitsystem:node:gp-[INFO]:-Mirroring config                 = ON
...gpinitsystem:node:gp-[INFO]:-Mirroring type                    = Group
...gpinitsystem:node:gp-[INFO]:----------------------------------------

### CODE REVIEW

**Comment by cjcjameson** [comment]
The `#` markers were conveying "count of", and I'm looking elsewhere in your output and see similar:

"Total database segments"
"Number segment hosts"

Can we consolidate on a shared naming for "count of" ideas? I propose "Number primary segments" / "Number mirror segments". Even though it is not quite grammatical, it's parallel to other labelling of outputs.

The concept of "Total" to me means "across all cluster hosts": fine to keep as it is.

My concern with the patch as it is right now is that people might misunderstand it to mean "the content_id of the primary segment" or some similar misunderstanding.

**Comment by skahler-pivotal** [comment]
@cjcjameson your point is valid there. So that would follow through as:

Primary segment # -> Number of primary segments
Total Database segments -> Total database segments
Number segment hosts -> Number of segment hosts
Mirror segment # -> Number of mirror segments

**Comment by Chibin** [comment]
> Primary segment # -> Number of primary segments
> Total Database segments -> Total database segments
> Number segment hosts -> Number of segment hosts
> Mirror segment # -> Number of mirror segments

👍

**Comment by yanchaozhong** [comment]
There is a #, the first glance looked a bit puzzled. 
After we think about it, we can determine the meaning of #, why not intuitively? Saving thinking time.

Number primary segments -> Number of primary segments
Total Database segments -> Total database segments
Number segment hosts -> Number of segment hosts
Number mirror segments -> Number of mirror segments

**Comment by Chibin** [comment]
@yanchaozhong Will you be able to update the commit to the agreed changes for the message?

**Comment by yanchaozhong** [comment]
+1
@Chibin Already modified.

**Comment by Chibin** [comment]
> +1
> @Chibin Already modified.

**Pull request merged**
