### PR TITLE
pt_ctl: rework the wrapper function

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
pg_ctl supports two internal cmdline arguments, --wrapper and
--wrapper-args, they are gpdb specific arguments for debugging purpose,
however we lost them since gpdb 5 during the postgres merging.  The
arguments are still accepted, just not being used.

Now we bring the function back.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by pivotal-ning-yu** [comment]
> LGTM. Maybe add simple tap tests to make sure this continues to work with future merges. This is required for `valgrind` and also for `rr` I think.

Yes, I will try to add some tests.

**Comment by pivotal-ning-yu** [comment]
Pushed a simple TAP test.

**Comment by asimrp** [comment]
The PR pipeline must be failing due to a legitimate problem.  Have you tried initializing standby with this change?  [`gpinitstandby`](https://github.com/greenplum-db/gpdb/blob/89a11719a1ba0ec6898e28ea36e095a7d67955fa/gpMgmt/bin/gpinitstandby#L335) is using `--wrapper` argument currently to set dbid.  The proposed change breaks that.  As a result, I see the following in `~/gpAdminLogs/gpinitstandby*.log` after creating demo cluster:

```
20200828:16:54:37:021610 gpinitstandby:asimmac:apraveen-[INFO]:-MasterStart pg_ctl cmd is env GPSESSID=0000000000 GPERA=8 $GPHOME/bin/pg_ctl -D gpAux/gpdemo/datadirs/standby -l gpAux/gpdemo/datadirs/standby/log/startup.log --wrapper="3" -t 600 -o " -p 7001 -c gp_role=dispatch " start
20200828:16:54:38:021610 gpinitstandby:asimmac:apraveen-[ERROR]:-Failed to create standby
20200828:16:54:38:021610 gpinitstandby:asimmac:apraveen-[WARNING]:-Trying to rollback changes that have been made...
```

**Comment by asimrp** [comment]
In iteration 12 branch, we are using [this fix](https://github.com/greenplum-db/gpdb-postgres-merge/commit/807899d64003a398758b4cd0f4656d22a553929f), FYI.

**Comment by pivotal-ning-yu** [comment]
Thanks for the fix, I'll include into this PR.

**Comment by ashwinstar** [comment]
Code for this committed as PostgreSQL 12 merge commit. Committed the test via commit 67de66a41a2790871cc84ccf2188b1f89bc484ee now. So, that concludes this PR, closing it.

**Comment by lij55** [comment]
Hi @wuj21 and all

could we backport this to GP6? We have some memory issue with GP6 which need to diagnose with valgrind. Thanks.

**Pull request closed without merging**
