### PR TITLE
Dispatcher should use DISPATCH_WAIT_FINISH mode to wait QEs for init …

### PR DESCRIPTION
**Pull request by pengzhout**
…plans

GPDB always set the REWIND flag for subplans include init plans, in 6195b96780,
we enhanced the restriction that if a node is not eager free, we cannot squelch
a node earlier include init plans, this exposes a few hidden bugs: if init plan
contains a motion node that needs to be squelched earlier, the whole query will
get stuck in cdbdisp_checkDispatchResult() because some QEs are still keep
sending tuples.

To resolve this, we use DISPATCH_WAIT_FINISH mode for dispatcher to wait the
dispatch results of init plan, init plan with motion is always executed on
QD and should always be a SELECT-like plan, init plan must already fetched
all the tuples it needed before dispatcher waiting for the QEs,
DISPATCH_WAIT_FINISH is the right mode for init plan.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`

### CODE REVIEW

**Comment by hlinnaka** [comment]
Hmm. Is the ExecSquelchNode() call earlier in the function unnecessary now?

Got a test case for this?

**Comment by pengzhout** [comment]
> Hmm. Is the ExecSquelchNode() call earlier in the function unnecessary now?
> 
> Got a test case for this?

Yes, removing it, lots of ICW cases get stuck under TCP interconnect without this patch,
tests passed under UDPIFC because the data is not big enough to fill the sending queue.

**Comment by hlinnaka** [comment]
On 08/01/2019 11:17, Tang Pengzhou wrote:
>> Hmm. Is the ExecSquelchNode() call earlier in the function unnecessary now?
>>
>> Got a test case for this?
> 
> Yes, removing it, lots of ICW cases get stuck under TCP interconnect without this patch,
> tests passed under UDPIFC because the data is not big enough to fill the sending queue.

OK.

Hmm. I wonder why the ExecSquelchNode() call wasn't enough. Are we 
failing to squelch in some node, where we should?

I looked closer at the cases that got stuck. There was this:

explain  select min(unique1) from tenk1 as a
where not exists (select 1 from tenk1 as b where b.unique2 = 10000);
                                                     QUERY PLAN
------------------------------------------------------------------------------------------------------------------
  Result  (cost=100.20..100.21 rows=1 width=0)
    InitPlan 1 (returns $0)  (slice3)
      ->  Limit  (cost=0.16..100.20 rows=1 width=0)
            ->  Gather Motion 3:1  (slice1; segments: 3) 
(cost=0.16..100.20 rows=1 width=0)
                  ->  Limit  (cost=0.16..100.18 rows=1 width=0)
                        ->  Index Only Scan using tenk1_unique2 on tenk1 
b  (cost=0.16..100.18 rows=1 width=0)
                              Index Cond: (unique2 = 10000)
    InitPlan 2 (returns $1)  (slice4)
      ->  Limit  (cost=0.16..0.33 rows=1 width=4)
            ->  Gather Motion 3:1  (slice2; segments: 3) 
(cost=0.16..1675.16 rows=10000 width=4)
                  Merge Key: a.unique1
                  ->  Result  (cost=0.16..1675.16 rows=3334 width=4)
                        One-Time Filter: (NOT $0)
                        ->  Index Only Scan using tenk1_unique1 on tenk1 
a  (cost=0.16..1675.16 rows=3334 width=4)
                              Index Cond: (unique1 IS NOT NULL)
  Optimizer: legacy query optimizer
(16 rows)

In this case, we have a Limit node in the subplan. But we have this code 
in nodeLimit to squelch when the Limit node doesn't fetch any more rows:

TupleTableSlot *
ExecLimit(LimitState *node)
{
	TupleTableSlot *result;

	result = ExecLimit_guts(node);

	if (TupIsNull(result) && !node->delayEagerFree)
	{
		/*
		 * CDB: We'll read no more from inner subtree. To keep our sibling
		 * QEs from being starved, tell source QEs not to clog up the
		 * pipeline with our never-to-be-consumed data.
		 */
		ExecSquelchNode((PlanState *) node);
	}

	return result;
}


Now that I think about that a bit harder, I realized that that's wrong. 
In the case of a SubPlan, we must squelch it, even if 'delayEagerFree' 
is set. I'm not sure why it is set in this case in the first place, I 
wouldn't expect the InitPlans to be re-scanned. But in any case, the 
Limit node is certainly not going to fetch any more rows from the 
subplan, after hitting the limit. It is not Limit's business to shield 
underlying nodes from being rescanned or squelched; if there are any 
nodes in the subtree that can't handle those, then it's their 
responsibility to delay eager freeing on their own.

The similar code in Nested Loop Joins and Merge Joins have the same 
issue. Those node types are perfectly OK with rescanning, and they 
shouldn't try to delay eager freeing on their own. I'm not sure about a 
hash join, I think it might have similar issues, too, but it does keep 
around the Hash table over rescans, at least sometimes, so the logic 
there probably needs to be somewhat more complicated.


After fixing Limit, this query still gets stuck:

regression=# explain with recursive
r(i) as (
     select 1
     union all
     select r.i + 1 from r, recursive_table_2 where i = recursive_table_2.id
),
y(i) as (
     select 1
     union all
     select i + 1 from y, recursive_table_1 where i = 
recursive_table_1.id and EXISTS (select * from r limit 10)
)
select * from y limit 10;
                                                           QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------
  Limit  (cost=0.00..0.20 rows=10 width=4)
    ->  Recursive Union  (cost=0.00..24.96 rows=35 width=4)
          ->  Result  (cost=0.00..0.01 rows=1 width=0)
          ->  Result  (cost=2.15..2.43 rows=4 width=4)
                One-Time Filter: $2
                InitPlan 1 (returns $2)  (slice3)
                  ->  Limit  (cost=0.00..0.02 rows=1 width=0)
                        ->  Subquery Scan on r  (cost=0.00..0.68 rows=35 
width=0)
                              ->  Recursive Union  (cost=0.00..24.76 
rows=12 width=4)
                                    ->  Result  (cost=0.00..0.01 rows=1 
width=0)
                                    ->  Hash Join  (cost=2.13..2.41 
rows=4 width=4)
                                          Hash Cond: (r_1.i = 
recursive_table_2.id)
                                          ->  WorkTable Scan on r r_1 
(cost=0.00..0.20 rows=4 width=4)
                                          ->  Hash  (cost=2.09..2.09 
rows=1 width=4)
                                                ->  Gather Motion 3:1 
(slice2; segments: 3)  (cost=0.00..2.09 rows=3 width=4)
                                                      ->  Seq Scan on 
recursive_table_2  (cost=0.00..2.03 rows=1 width=4)
                ->  Hash Join  (cost=2.13..2.40 rows=4 width=4)
                      Hash Cond: (y.i = recursive_table_1.id)
                      ->  WorkTable Scan on y  (cost=0.00..0.20 rows=4 
width=4)
                      ->  Hash  (cost=2.09..2.09 rows=1 width=4)
                            ->  Gather Motion 3:1  (slice1; segments: 3) 
  (cost=0.00..2.09 rows=3 width=4)
                                  ->  Seq Scan on recursive_table_1 
(cost=0.00..2.03 rows=1 width=4)
  Optimizer: legacy query optimizer
(23 rows)

This is explained by the fact that ExecSquelchNode on a SubQueryScan is 
not recursing correctly. The subplan of a SubQueryScan is not stored in 
Plan.lefttree, like in most node types, so it needs to implement a 
ExecSquelchSubqueryScan() function to do the recursion. Oops!

So this was a very fruitful exercise. After fixing those, 
installcheck-world is not getting stuck anymore. So we wouldn't 
necessarily need this PR anymore. But +1 on committing it anyway. Using 
DISPATCH_WAIT_FINISH is a more robust way of stopping the query from 
running. As we've seen, that works even if we get the ExecSquelchNode() 
support wrong. We need to fix those other bugs, anyway, because you they 
might still occur without SubPlans, in Nested Loop joins, for example. 
But better to make ExecSubPlan() more robust, too.

I'll open a separate PR for those bugs in Limit and SubQueryScan squelching.

- Heikki

**Comment by pengzhout** [comment]
> As we've seen, that works even if we get the ExecSquelchNode() support wrong. We need to fix those other bugs, anyway, because you they might still occur without SubPlans, in Nested Loop joins, for example. But better to make ExecSubPlan() more robust, too. I'll open a separate PR for those bugs in Limit and SubQueryScan squelching. - Heikki

Agreed, there are many cases that are not safe (or have no chance) to call ExecSquelchNode, so DISPATCH_WAIT_FINISH is the final place to avoid an infinite waiting in QD, actually, As you mentioned, I'm thinking of moving TeardownInterconnect ahead of cdbdisp_checkDispatchResult in QD because TeardownInterconnect can also stop the interconnect stream (but how to stop a
shared input scan stream), but it is another story and need more investigate.

I think we should be very careful about calling ExecSquelchNode(), wrong results are much worse than a high workload, Limit is also rescanable like
```
gpadmin=# explain select * from t1 where t1.c1 > ANY(select c2 from t2 limit t1.c1);
                                                        QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)  (cost=0.00..1248872.88 rows=43050 width=8)
   ->  Seq Scan on t1  (cost=0.00..1248872.88 rows=14350 width=8)
         Filter: (SubPlan 1)
         SubPlan 1  (slice2; segments: 3)
           ->  Limit  (cost=0.00..26.83 rows=287 width=4)
                 ->  Limit  (cost=0.00..96.10 rows=2870 width=4)
                       ->  Result  (cost=0.00..1391.50 rows=28700 width=4)
                             ->  Materialize  (cost=0.00..1391.50 rows=28700 width=4)
                                   ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..961.00 rows=28700 width=4)
                                         ->  Seq Scan on t2  (cost=0.00..961.00 rows=28700 width=4)
```
HashJoin is also rescanable, I once construct a case that we squelch wrongly.

**Comment by pengzhout** [comment]
Ouch, forget to squash.

**Comment by pengzhout** [comment]
Merged, thanks for the reviews.

**Pull request merged**
