### PR TITLE
Use double-parens params in pipeline definition.

### PR DESCRIPTION
**Pull request by d**
Having double curly braces in a YAML file actually invalidates the
YAML-ness (yamility? Anyway, an open curly brace is the token for
beginning an "inline mapping"). I noticed this while trying to come up
with a regression test suite in a bigger refactoring to the pipeline
templates (gotta parse that YAML one way or another).

The double-parens syntax was introduced more than 3 years ago [1] to be
less rough around the edges.

[1] https://github.com/concourse/concourse/releases/tag/v3.2.0

## Pre-merge TODO
- [ ] dry-run setting master pipeline
- [ ] dry-run setting coverity pipeline
- [ ] dry-run setting PR pipeline
- [x] dry-run setting orca test explain pipeline
- [x] dry-run setting orca test orca pipeline

## Post merge TODO
- [ ] set master pipeline
- [ ] set coverity pipeline
- [ ] set PR pipeline
- [ ] set orca test explain pipeline
- [ ] set orca test orca pipeline

### CODE REVIEW

**Comment by d** [comment]
tagging @bradfordb-vmware to get some timezone proximity

**Comment by d** [comment]
This is a fairly harmless change, so I'm gonna merge it if there hasn't been a review for 18 hours

**Comment by d** [comment]
@chrishajas I might need some hand-holding in setting the two ORCA pipelines

**Comment by bradfordb-vmware** [comment]
One behavioral difference between `{{variable}}` and `((variable))` to be aware of when setting pipelines: if `variable` is not defined, then `{{variable}}` will cause an error when calling `fly set-pipeline`, while `((variable))` does not. A convention I have seen used in other places is to add `--check-creds` to `fly set-pipeline` to catch undefined variables when setting pipelines.

**Comment by d** [comment]
> One behavioral difference between `{{variable}}` and `((variable))` to be aware of when setting pipelines: if `variable` is not defined, then `{{variable}}` will cause an error when calling `fly set-pipeline`, while `((variable))` does not. A convention I have seen used in other places is to add `--check-creds` to `fly set-pipeline` to catch undefined variables when setting pipelines.

Would you suggest that I change the prompt from the python script?

**Comment by edespino** [comment]
In gen_pipeline.py, the validate_pipeline_release_jobs() function removes (ignores) the concourse v2.x variable interpolation as part of pipeline validation. With this change, this can now be removed/reworked.

```
    # ignore concourse v2.x variable interpolation
    pipeline_yml_cleaned = re.sub('{{', '', re.sub('}}', '', raw_pipeline_yml))
```

**Comment by bradfordb-vmware** [comment]
> Would you suggest that I change the prompt from the python script?

I know for the master pipeline we use `gen_pipeline.py` to generate the pipeline yml and print the appropriate `fly` command. I think we should update that prompt. For the other pipelines, we'll need to find the Makefile/pipeline documentation and update accordingly.

**Comment by d** [comment]
> One behavioral difference between `{{variable}}` and `((variable))` to be aware of when setting pipelines: if `variable` is not defined, then `{{variable}}` will cause an error when calling `fly set-pipeline`, while `((variable))` does not. A convention I have seen used in other places is to add `--check-creds` to `fly set-pipeline` to catch undefined variables when setting pipelines.

hmmm, I tried `--check-creds` with intentionally missing `--load-vars-from`, but `fly` didn't try to stop me. Is that expected?

**Comment by d** [comment]
> hmmm, I tried `--check-creds` with intentionally missing `--load-vars-from`, but `fly` didn't try to stop me. Is that expected?

Aha I see what's going on here, OK that's kind of a UX surprise

**Comment by d** [comment]
> With this change, can this now be removed/reworked?

Yes, although I don't plan to include that as part of this patch. I'm trying to balance the scope here.

**Comment by d** [comment]
> One behavioral difference between `{{variable}}` and `((variable))` to be aware of when setting pipelines: if `variable` is not defined, then `{{variable}}` will cause an error when calling `fly set-pipeline`, while `((variable))` does not. A convention I have seen used in other places is to add `--check-creds` to `fly set-pipeline` to catch undefined variables when setting pipelines.

I've included changes to the prompted `fly` command, see if it's kosher?

**Review by edespino — APPROVED** [review]
My local PR testing was as expected. +1

**Review by bradfordb-vmware — APPROVED** [review]
:shipit:

**Pull request merged**
