### PR TITLE
Misc test cleanup

### PR DESCRIPTION
**Pull request by hlinnaka**
see commit messages for details.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Nice! I intend to review this later on tonight when I have more time. Do you have a ballpark guesstimate for the time savings from this?

**Comment by hlinnaka** [comment]
> Nice! I intend to review this later on tonight when I have more time. Do you have a ballpark guesstimate for the time savings from this?

Probably under one minute...

**Comment by hlinnaka** [comment]
I had to remove one commit from this series, because it was failing in the pipeline:

I tried to move the tests from bfv_partition, that created a partitioned table with primary keys and a foreign key references, to another test file, so that the tables would not get dropped at the end of the test. Because I believe we don't have any test coverage for pg_dump/pg_upgrade of that case. (The test tables called 'mpp3762_*'.) But that caused the pg_upgrade tests to fail, because the pre-script that drops all indexes on partitioned tables threw an error, when it tried to drop the index that backs the primary key.

I removed that change for now, so that we can proceed with the rest of the cleanups.

**Comment by berlin-ab** [comment]
Looks green now. Let's push it in.

**Comment by hlinnaka** [comment]
Pushed, thanks for the reviews!

> Are you planning on squashing the commits?

I squashed some that were doing similar things, just on different tests. Went from 8 commits to 5.

**Pull request merged**
