### PR TITLE
[ORCA] Allow push down of filter with BETWEEN predicate (#14872)

### PR DESCRIPTION
**Pull request by dgkimura**
This commit enables additional opportunities for predicate push down based on a synergetic relationship between join conditions and select filters.  For example, let's use query:

    SELECT count(*) FROM t2 INNER JOIN t1 ON t2.c BETWEEN t1.a AND t1.b WHERE t2.c = 2;

Input:
```
    +--CLogicalSelect
       |--CLogicalNAryJoin
       |  |--CLogicalGet "t2" ("t2"), Columns: ["c" (0), "d" (1),...
       |  |--CLogicalGet "t1" ("t1"), Columns: ["a" (9), "b" (10),...
       |  +--CScalarBoolOp (EboolopAnd)
       |     |--CScalarCmp (>=)
       |     |  |--CScalarIdent "c" (0)
       |     |  +--CScalarIdent "a" (9)
       |     +--CScalarCmp (<=)
       |        |--CScalarIdent "c" (0)
       |        +--CScalarIdent "b" (10)
       +--CScalarCmp (=)
          |--CScalarIdent "c" (0)
          +--CScalarConst (2)
```

Notice that the join predicate references columns (a, b, and c) coming from either sides of the join. Typically this means the predicate cannot be pushed down.  However, the select filter above the join predicate filters on c=2.  We can utilize that in conjunction with the join condition to filter out more rows. We do that outputing:

Output:
```
    +--CLogicalSelect
       +--CLogicalSelect
       |  |--CLogicalNAryJoin
       |  |  |--CLogicalGet "t2" ("t2"), Columns: ["c" (0), "d" (1),...
       |  |  |--CLogicalGet "t1" ("t1"), Columns: ["a" (9), "b" (10),...
       |  |  +--CScalarBoolOp (EboolopAnd)
       |  |     |--CScalarCmp (>=)
       |  |     |  |--CScalarIdent "c" (0)
       |  |     |  +--CScalarIdent "a" (9)
       |  |     +--CScalarCmp (<=)
       |  |        |--CScalarIdent "c" (0)
       |  |        +--CScalarIdent "b" (10)
       |  +--CScalarBoolOp (EboolopAnd)
       |     |--CScalarCmp (>=)
       |     |  +--CScalarConst (2)
       |     |  +--CScalarIdent "a" (9)
       |     +--CScalarCmp (<=)
       |     |  +--CScalarConst (2)
       |        +--CScalarIdent "b" (10)
       +--CScalarCmp (=)
          |--CScalarIdent "c" (0)
          +--CScalarConst (2)
```

Note: One might naively think that it is possible to directly replace the constant identifier in the join predicate.  However, that would be a mistake as it could prevent hash join alternative plans. This is why we must instead add a new select filter above the join.

The preprocessor step in this commit can add new select filters that were constructed by substituting constants into join conditions.  It is possible that the new filter is of the form:

    (const relop ident)

However, prior to this commit the constraint interval is constructed using a scalar compare operator that is expected to be an expression of the form:

    (ident relop const)

There doesn't seem a good reason to not to support that form too. In fact there's a FIXME from 2012 that suggests maybe we should enable even more forms.  So this commit also enables the above form.

(cherry picked from commit 063b0abc3cccb488f23060954f959551e4c2f544)

---

Cherry-pick conflicts:
 - usual c++11 (NULL vs nullptr, typedef vs using)
 - regenerated new MDPs because of parser tag diffs

### CODE REVIEW

**Comment by dgkimura** [comment]
One of our workloads found what looks like a regression where this change produces a seemingly duplicate filter.  Below is a minimal repro.  It seems to require `bigint` columns as it doesn't repro with `int4` or `float`.

```
CREATE TABLE t1(a bigint);
CREATE TABLE t2(a bigint);

EXPLAIN (costs off)
SELECT * FROM t1 INNER JOIN t2 ON t2.a = t1.a WHERE t1.a = 17353232;
                                      QUERY PLAN                                      
--------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)
   ->  Hash Join
         Hash Cond: (t1.a = t2.a)
         ->  Seq Scan on t1
               Filter: (a = 17353232)
         ->  Hash
               ->  Seq Scan on t2
                     Filter: ((a OPERATOR(pg_catalog.=) 17353232) AND (a = 17353232))
 Optimizer: Pivotal Optimizer (GPORCA)
 ```
 
After normalization, the preprocessor failed to deduplicate the filter on t2.  But, if you look inside the plan there are actually different operators (410 and 416) which is why we couldn't deduplicate.

```
:qual (
   {BOOLEXPR
   :boolop and 
   :args (
      {OPEXPR
      :opno 410 
      :opfuncid 467 
      :...
      :args (
         ... 
      )   
      :location 0
      }   
      {OPEXPR
      :opno 416 
      :opfuncid 474 
      :...
      :args (
         ... 
         }   
      )   
      :location 0
      }  
```

**Review by gpopt — APPROVED** [review]
+1

**Review by THANATOSLAVA — APPROVED** [review]

**Comment by ashwinstar** [comment]
> One of our workloads found what looks like a regression where this change produces a seemingly duplicate filter. 

Is this addressed as don't wish to ship with regression?

**Comment by dgkimura** [comment]
> > One of our workloads found what looks like a regression where this change produces a seemingly duplicate filter.
> 
> Is this addressed as don't wish to ship with regression?

Yes.  It's addressed in the second follow up commit "Prevent duplicate filter issue" https://github.com/greenplum-db/gpdb/pull/14971/commits/cee4a8d80fdf1d7c22000eb1e9deb3fd680b8a82.  Sorry if that wasn't clear.

**Pull request merged**
