### PR TITLE
[WIP]Enable source data transform inside external table.

### PR DESCRIPTION
**Pull request by JunfengYang**
The main purpose of the transformer is to resolve abortion for ETL
tasks.

A transformer is used to transform a readable external table's
unmatched data source into the external table definition data.
And handle any possible errors during the transform phase through
single row error handler.

A simple example is:
A CSV file contains 3 columns' data. But the external table is
defined as (a int, b json).
Without the transformer, read data from this external table will raise
an error.

Although an alternative way to do this is to define an external with the
same table definition of the data source. And then use SELECT statement
to transform data into another table.
Like (INSERT INTO t AS SELECT expression(c1), expression(c2) from ext).

For ETL tasks, it's not a good solution. Since once the expression raises
error, the whole task will be aborted.
So for ETL tasks, it can use the transformer to transform data, and errors
should be handled by the single row error handler.

The CREATE EXTERNAL statement should look like this:
```sql
CREATE EXTERNAL TABLE EXTTBL (id int, value boolean)
LOCATION (
    'data source'
    )
FORMAT 'any format'
OPTIONS (
    transform_from 'TEMPLATE',
    transform_expression '(*), (***)',
    transform_arguments '*[, *...]')
LOG ERRORS SEGMENT REJECT LIMIT 5;
```
The reason why these options are set through OPTIONS filed is when
migrating external table to foreign data wrapper(FDW) interface, there
should be not much effort for the transformer.

Check src/test/regress/input/external_table_transform.source to see the
usage.

Also, move `FileScanDescData` from relscan.h to fileam.h. Since it actually a
foreign scan now.

TODO:
1. Consider expression escape for "transform_expression" in OPTIONS.
2. Add more test cases.
3. Performance test.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by danielgustafsson** [comment]
I strongly object to doing any work on external tables until they have been converted fully to foreign tables.

**Comment by schubert** [comment]
Flagging @yydzero @macroyuyang for commentary. I agree with Daniel, we shouldn't modify external tables more right now until we resolve things.

cc @ivannovick @brianlugongyu

**Comment by lij55** [comment]
Hi @danielgustafsson  @schubert ,
I believe this PR is not intended for master. As gp5 would be frozen soon, this PR is only for 5 (and 6). 
I totallly agree we would migrate to fdw and we are planning for this already.

For this feature itself, it helps to handle the expression errer (such as `jsondata->>'id'`) during loading (extract items from json/avro message and serilize  into target table ).

**Comment by JunfengYang** [comment]
Although this PR is mainly for GPDB5's user request.
But for master, the design is already considered the external table FDW migration.
The new component doesn't need further change on FDW.

This is a simple solution for user requests.
But the main purpose of this PR is we can come out with a better solution to fulfill the user
requests through the discussion. Not only limited to the current implementation.

**Pull request closed without merging**
