### PR TITLE
refresh localBackendStatusTable so hasBackendsExist can get real-time backends status

### PR DESCRIPTION
**Pull request by pengzhout**
This commit also rename the function name and add more comments

### CODE REVIEW

**Comment by hlinnaka** [comment]
I feel this is getting quite complicated and invasive, for the sake of a regression test. Couldn't you formulate the test more simply with a PL/pgSQL function that executes something like:

select * from pg_stat_get_db_numbackends(<current database ID>), gp_dist_random('gp_id');

in a loop?

**Comment by pengzhout** [comment]
@hlinnaka  we tried that before, for statement ```select * from pg_stat_get_db_numbackends(), gp_dist_random('gp_id');```,  pg_stat_get_db_numbackends()  somehow was planned to be executed only on QD which is not expected.

**Comment by hlinnaka** [comment]
On 12/13/2016 05:06 AM, Tang Pengzhou wrote:
> @hlinnaka  we tried that before, for statement ```select * from
> pg_stat_get_db_numbackends(), gp_dist_random('gp_id');```,
> pg_stat_get_db_numbackends()  somehow was planned to be executed only
> on QD which is not expected.

That's odd, it works as expected here:

postgres=# explain select gp_segment_id, * from 
pg_stat_get_db_numbackends(12070), gp_dist_random('gp_id');
                                         QUERY PLAN 

-------------------------------------------------------------------------------------------
  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1.07 rows=4 
width=78)
    ->  Nested Loop  (cost=0.00..1.07 rows=2 width=78)
          ->  Function Scan on pg_stat_get_db_numbackends 
(cost=0.00..0.01 rows=1 width=4)
          ->  Seq Scan on gp_id  (cost=0.00..1.03 rows=1 width=74)
  Settings:  gp_enable_mk_sort=off
  Optimizer status: legacy query optimizer
(6 rows)

postgres=# select gp_segment_id, * from 
pg_stat_get_db_numbackends(12070), gp_dist_random('gp_id');
  gp_segment_id | pg_stat_get_db_numbackends |  gpname   | numsegments | 
dbid | content
---------------+----------------------------+-----------+-------------+------+---------
              2 |                          2 | Greenplum |          -1 | 
   -1 |      -1
              0 |                          2 | Greenplum |          -1 | 
   -1 |      -1
              1 |                          2 | Greenplum |          -1 | 
   -1 |      -1
(3 rows)

PS. There is an existing pg_stat_clear_snapshot() function, should use that.

- Heikki

**Comment by pengzhout** [comment]
@hlinnaka  Oops, i was running ```select gp_id,  pg_stat_get_db_numbackends(16385) from gp_dist_random('gp_id');``` that the function was only executed on master, this can reduce the slices involved in the query.

**Comment by pengzhout** [comment]
updated with pg_stat_clear_snapshot()

**Comment by pengzhout** [comment]
Merged , thanks for review.

**Pull request closed without merging**
