### PR TITLE
Porting Queries on Table with Indexes to ICG

### PR DESCRIPTION
**Pull request by vraghavan78**
Porting queries on table with indexes from TINC_BFV.

Kind Attention: @hlinnaka @danielgustafsson @xinzweb @oarap @hsyuan

### CODE REVIEW

**Comment by hsyuan** [comment]
LGTM.

**Comment by gcaragea** [comment]
LGTM

**Comment by danielgustafsson** [comment]
Looks good to me too.

(As a side note not blocking this PR: I'm starting to wonder if we should provide the functions used in these tests as a toolkit available to all tests rather than sprinkling them across the test files. The speedup will be miniscule but it might make the files more readable etc. I'll add this to my TODO to fix up once the test work stabilizes unless there are objections.)

**Comment by vraghavan78** [comment]
Thanks!

**Pull request closed without merging**
