### PR TITLE
DOCS: gpinitsystem additions

### PR DESCRIPTION
**Pull request by dyozie**
Adding info for previously-undocumented options.

### CODE REVIEW

**Comment by dyozie** [comment]
I've also put an HTML version of this page up at http://docs-gpdb-review-staging.cfapps.io/500Beta/utility_guide/admin_utilities/gpinitsystem.html if that's easier to review.

**Comment by dyozie** [comment]
@skahler-pivotal @Chibin - does this look correct?  Additions are the `-I` and `-O` options and associated config file entries.  Also need to confirm that `-m` is the same as `--max-connections`, `-n` is the same as `--locale`, and `-e` is the same as `--su_password`.

**Comment by Chibin** [comment]
> @skahler-pivotal @Chibin - does this look correct? Additions are the -I and -O options and associated config file entries.  

Need to verify this

> Also need to confirm that -m is the same as --max-connections, -n is the same as --locale, and -e is the same as --su_password.

This looks correct

**Comment by Chibin** [comment]
Follow up: -I and -O looks good to me

**Comment by dyozie** [comment]
Great - Thanks Marbin!

**Pull request merged**
