### PR TITLE
Remove gphdfs from source code

### PR DESCRIPTION
**Pull request by frankgh**
Deprecate and remove gphdfs from Greenplum source code.

- [x] Add tests for the change
- [x] Documentation changes
- [x] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [x] Remove gphdfs from Greenplum docs (doc/*)
- [x] Remove GUCs and code related to gphdfs
- [x] Remove tests using gphdfs
- [x] Remove gphdfs from Makefile(s)
- [x] Remove gphdfs from gpcontrib
- [x] Remove gphdfs from pipelines

### CODE REVIEW

**Comment by lavjain** [comment]
We would like to merge this PR by end of the week if there are no objections.

**Comment by ashwinstar** [comment]
Seems good to go, what are we waiting for +1 (just wish to know what's exactly being waited for is clear)?

**Comment by danielgustafsson** [comment]
There is also a failing test which needs to be addressed, with a patch of this size I'd prefer to see the PR pipeline green before merging.

**Comment by frankgh** [comment]
@danielgustafsson what type of query can we perform to determine whether gphdfs external tables exist? `pg_catalog.pg_depend` has some information about external tables. However, I am unable to determine a way to get the oid for gphdfs external tables that we could use to query tables in `pg_depend` with  `refobjid` = objid for gphdf?
i.e.

```
select *  FROM pg_depend WHERE refclassid = 'pg_extprotocol'::regclass ;
 classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype
---------+-------+----------+------------+----------+-------------+---------
                  .................
    1259 | 16430 |        0 |       7175 |    16390 |           0 | n
    1259 | 16433 |        0 |       7175 |    12425 |           0 | n
    1259 | 16436 |        0 |       7175 |    12425 |           0 | n
    1259 | 16439 |        0 |       7175 |    12425 |           0 | n
    1259 | 16442 |        0 |       7175 |    16390 |           0 | n
                  .................
```
I know that objects with `objid` 16433, 16436, 16439 are gphdfs external tables, and they all share the same `refobjid` 12425. But I am unsure where that refobjid came from.

**Comment by frankgh** [comment]
@danielgustafsson I have restored pg_dump support for older versions in commit https://github.com/greenplum-db/gpdb/pull/6735/commits/f730ee272b4a4fcf9d52e53045c1fb3307e05d1a. Let me know if that's what you were looking for.

I am also working on pg_upgrade support, which will be part of a different commit

**Comment by ashwinstar** [comment]
On Tue, Jan 22, 2019 at 11:56 AM Daniel Gustafsson <notifications@github.com>
wrote:

> *@danielgustafsson* commented on this pull request.
>
> This removes support for reading gphdfs in pg_dump from older versions of
> the server where it still supported. pg_dump is expected to (within reason)
> be able to properly dump also older versions of the server with the
> featureset intact.
>

I am little confused on this one. pg_upgrade is the only user of pg_dump in
greenplum and below we are saying pg_upgrade should bail out for gphdfs
tables. So, what's the need for having gphdfs support in pg_dump for lower
versions ?

Even if we do it, since there exists no tests or validations for the same,
how can we be confident keeping that code it works ?

**Comment by danielgustafsson** [comment]
> On 26 Jan 2019, at 00:17, Ashwin Agrawal <notifications@github.com> wrote:

> I am little confused on this one. pg_upgrade is the only user of pg_dump in
> greenplum and below we are saying pg_upgrade should bail out for gphdfs
> tables. So, what's the need for having gphdfs support in pg_dump for lower
> versions ?

How would we know that pg_upgrade is the only consumer? Our codebase isn’t using it elsewhere, but that’s not to say that someone is using it as a backup tool for example.

The expectation is that pg_dump will be able to dump the database with the capabilities the source database had. It is true that a dump containing gphdfs tables won’t restore into a 6.x cluster, but thats generally true for any source database object relying on an extension which isn’t available in the target cluster. I don’t see why this is different in that regard, and I don’t see why silently ignoring relations is user friendly.

**Comment by lavjain** [comment]
@danielgustafsson What other code changes are required for our team to merge this PR before the beta goes out?

**pg_dump/pg_upgrade** needs a larger discussion on the migration strategy as it does not affect the customers that are migrating from 4.x to 5.x 

Also, GPHDFS tables in Greenplum are DDLs only (with no data) and can those scripts can be generated in a SQL file that requires manual migration steps. Any customer on 5.X should be heavily encouraged to migrate their GPHDFS scripts to PXF before 6.X becomes GA.

**Comment by divyabhargov** [comment]
I would agree that removal of GPHDFS should happen before Beta. Fixing the pg_upgrade when GPHDFS is being used can go in before GA. However if it is a simple enough fix, we could do it within the same PR.

**Comment by frankgh** [comment]
@lisakowen just wanted to let you know about this PR. We will need some documentation changes to reflect the removal of gphdfs. We have a lot of gphdfs related documentation under `gpdb-docs`

**Comment by lisakowen** [comment]
thanks for the heads-up, @frankgh.  this work is in-progress; i will submit a docs PR for gpdb-docs/ shortly after your PR is merged.

**Comment by frankgh** [comment]
@danielgustafsson we've added support for `pg_upgrade` in this commit https://github.com/greenplum-db/gpdb/pull/6735/commits/f26e4a2655c4e6568ebc2d297eb2b48da2e7a03a and manually tested the new functionality. This is the output from `pg_upgrade`:
```
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is a superuser                       ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* system OID user data types                ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for online expansion status                        ok
Checking for external tables used in partitioning           ok
Checking for non-covering indexes on partitioned AO tables  ok
Checking for indexes on partitioned tables                  ok
Checking for orphaned TOAST relations                       ok
Checking for gphdfs external tables                         fatal

| Your installation contains gphdfs external tables.  These
| tables need to be dropped before upgrade.  A list of
| external gphdfs tables to remove is provided in the file:
| 	gphdfs_external_tables.txt

Failure, exiting
```
and `gphdfs_external_tables.txt` correctly reports the affected tables:
```
gphdfs external table "public.lineitem_gphdfs_read" in database "tpch"
gphdfs external table "public.lineitem_gphdfs_write" in database "tpch"
```

After dropping gphdfs tables, `pg_upgrade` succeeds with the following output:
```
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is a superuser                       ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* system OID user data types                ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for online expansion status                        ok
Checking for external tables used in partitioning           ok
Checking for non-covering indexes on partitioned AO tables  ok
Checking for indexes on partitioned tables                  ok
Checking for orphaned TOAST relations                       ok
Checking for gphdfs external tables                         ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok
Checking for presence of required libraries                 ok
Checking database user is a superuser                       ok
Checking for prepared transactions                          ok

If pg_upgrade fails after this point, you must re-initdb the
new cluster before continuing.

Performing Upgrade
------------------
Analyzing all rows in the new cluster                       ok
Freezing all rows on the new cluster                        ok
Deleting files from new pg_clog                             ok
Copying old pg_clog to new server                           ok
Setting next transaction ID and epoch for new cluster       ok
Deleting files from new pg_multixact/offsets                ok
Copying old pg_multixact/offsets to new server              ok
Deleting files from new pg_multixact/members                ok
Copying old pg_multixact/members to new server              ok
Setting next multixact ID and offset for new cluster        ok
Resetting WAL archives                                      ok
Deleting files from new pg_distributedlog                   ok
Copying old pg_distributedlog to new server                 ok
Setting frozenxid and minmxid counters in new cluster       ok
Restoring global objects in the new cluster                 ok
Adding support functions to new cluster                     ok
Restoring database schemas in the new cluster
                                                            ok
Removing support functions from new cluster                 ok
Invalidating bitmap indexes in new cluster                  ok
Restoring append-only auxiliary tables in new cluster       ok
Freezing all rows in new master after pg_restore            ok
Copying user relation files
                                                            ok
Setting next OID for new cluster                            ok
Sync data directory to disk                                 ok
Creating script to analyze new cluster                      ok
Creating script to delete old cluster                       ok

Upgrade Complete
```

Additionally, this branch has been rebased with the latest master (as of morning of Feb. 4) and all checks are green.

Finally, support for `pg_dump` was restored in commit https://github.com/greenplum-db/gpdb/pull/6735/commits/1a5545ee3458703baf20ef820cb4b2a5ee8684b1#diff-f635c4de8d1a39c3d55c7de7aec22148. It has been rebased from master and hash has changed from last time.

**Comment by frankgh** [comment]
@danielgustafsson thanks for the feedback. I have addressed your comments and will merge later today.

**Pull request merged**
