### PR TITLE
removing xerces patch

### PR DESCRIPTION
**Pull request by zellerh**
The scripts we use in Concourse pipelines download Apache xerces-c-3.1.2 and then apply a patch that is part of our source code tree. @asubramanya has pointed out that this is no longer necessary. This commit removes the patch and uses the vanilla xerces source code instead.

Eventually, we want to stop including xerces into our releases and rely on the natively installed xerces. See also https://github.com/greenplum-db/gpdb/pull/10068.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by kainwen** [comment]
Can we also modify the related readme https://github.com/greenplum-db/gpdb/blob/master/src/backend/gporca/README.md ?

Thanks.

**Comment by zellerh** [comment]
> Can we also modify the related readme https://github.com/greenplum-db/gpdb/blob/master/src/backend/gporca/README.md ?

As far as I understood, we currently have three ways to integrate with xerces:

- Use gp-xerces, as described in the README
- Use Apache xerces and apply a patch
- Use the natively installed xerces that comes with the OS

In the long term, we want to go to the third method. This PR is about removing the second method, in preparation of that long-term goal. We are not quite ready to get rid of the first method, since some platforms come with a version of xerces that doesn't work with GPDB. See also https://github.com/greenplum-db/gpdb/pull/10068, which gets us a big step closer to using native xerces. So, in short, changing the README will be done in a future PR.

**Comment by zellerh** [comment]
> LGTM. We might also be able to get rid of `src/backend/gporca/concourse/xerces-c/package_tarball.yml`

Thanks, done.

**Comment by zellerh** [comment]
@bradfordboyle, could you please take a quick look at this to see whether it might impact the release pipelines?

**Comment by bradfordboyle** [comment]
@zellerh The change looks to be safe for enterprise builds; for OSS releases, the change in directory name will break the build. For GPDB 6, OSS builds are driven from greenplum-db/greenplum-database-release. We keep a separate [`compile_gpdb_oss.bash`](https://github.com/greenplum-db/greenplum-database-release/blob/master/ci/concourse/scripts/compile_gpdb_oss.bash#L16-L31) script there.

**Comment by zellerh** [comment]
Thanks very much, @bradfordboyle! I'll undo the directory name change.

**Pull request merged**
