### PR TITLE
Fix relcache reference leaks if readindex() function isn't run to com…

### PR DESCRIPTION
**Pull request by hlinnaka**
…pletion.

You get warnings about relcache reference leaks if you run something like
"select readindex('pg_class_oid_index'::regclass) limit 1;". To fix,
don't hold the relcache entries or the buffer pin across calls. Looking
up the relcache entry on every call adds some overhead, of course, but a
full index scan isn't exactly cheap anyway. And this is just a debugging
function, not performance critical.

Spotted by Ashwin Agrawal.

### CODE REVIEW

**Comment by ashwinstar** [comment]
The initial intent this was coded was for debugging only, as you spotted. But now gpcheckcat wishes to use it to validate the correctness of index corresponding to base table. Something high level like during a join between select * from base table and readindex to validate two cases
1] missing entries in index present in base table
2] index entry (with key A) pointing to incorrect tuple (B) in base table
So, I would say with that usage it would be performance critical. Is there no alternative way to accomplish the fix.

**Comment by hlinnaka** [comment]
On 13/05/16 19:02, Ashwin Agrawal wrote:
> The initial intent this was coded was for debugging only, as you
> spotted. But now gpcheckcat wishes to use it to validate the
> correctness of index corresponding to base table. Something high
> level like during a join between select * from base table and
> readindex to validate two cases
> 1] missing entries in index present in base table
> 2] index entry (with key A) pointing to incorrect tuple (B) in base table

Oh, ok. readindex() returns the contents of the whole table. That seems 
like overkill for gpcheckcat. I would recommend writing a separate index 
checking tool that has a more suitable interface.

Coincidentally, Peter G has been hacking on such a tool. Looks like he 
just posted a new version of it: 
http://pgeoghegan.blogspot.com/2016/05/amcheck-verify-logical-consistency-of.html. 
That one doesn't check the pointers from index to heap, though. But it 
should be fairly straightforward to add.

> So, I would say with that usage it would be performance critical.
> Is there no alternative way to accomplish the fix.

So, whether or not we pick that as the base or write something from 
scratch, I don't think we should turn readindex() into an index 
validation tool. The requirements for that are indeed quite different.

We could certainly write readindex() differently, and e.g. read 1000 
heap tuples into memory at a time, and buffer them in the context 
struct, returning one on each call. That way you'd only need to do the 
relcache lookups once for each 1000 tuples. But if we instead invent a 
new function, "validateindex()", with a different API, we can make it 
return just a bool or a string, or a set of errors, instead of returning 
every single tuple in the table. That way, you don't need to worry about 
holding the relation open across calls, as the function can run to 
completion in a single invocation.

- Heikki

**Comment by ashwinstar** [comment]
Yes, have looked into the tool Peter G was coding for index.
But the tool was more checking the sanity of index structure than its
correctness compared to base table.

Agree need to implement something in backend to verify the index
correctness compared to base table,
I believe we were just lazy and wished to make it happen in sql layer
leveraging best what we have today.

**Comment by ashwinstar** [comment]
👍 for now to resolve the resource leaks.

**Pull request closed without merging**
