### PR TITLE
Enable ccache on Travis CI

### PR DESCRIPTION
**Pull request by d**
### A moderate proposal
While working on #9937, I realized we took out ccache from Travis. This patch set brings it back with some additional TLC. Please see each commit for details. I plan to squash them (dropping the commits marked as "drop me" of course) when ready to merge.

Highlights:
- Care is taken to ensure `ccache` is actually used on macOS. The default settings in Travis somehow neglected it so we compensate for it.
- Similar care is taken to ensure ccache is actually used when we build with Clang. The version of `ccache` used in Travis is just slightly older than when automatic Clang symlink supported was added.
- This cuts down a 13 minute compilation to 3 minutes for me (it still seems to vary)

## Here are some reminders before you submit the pull request
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by d** [comment]
@danielgustafsson when you dropped `ccache` from travis last time (in de256d128598f) was there any specific concerns I should address here?

**Comment by danielgustafsson** [comment]
> On 4 May 2020, at 21:12, Jesse Zhang <notifications@github.com> wrote:

> @danielgustafsson when you dropped ccache from travis last time (in de256d1) was there any specific concerns I should address here?

I don't exactly remember, but I was seeing odd crashes and linker failures that I attributet to ccache since they went away when I disabled it. That may very well have been solar flares though. The Travis documentation for caching in matrices does indicate that care should be taken, so following that should work I assume: https://docs.travis-ci.com/user/caching/#caches-and-build-matrices.

One very probably reason was that I did so much else I didn't want one more thing to spend even more iterations of push-wait-see-scratch-head with Travis and just wanted the pain to stop..

**Comment by d** [comment]
> One very probably reason was that I did so much else I didn't want one more thing to spend even more iterations of push-wait-see-scratch-head with Travis and just wanted the pain to stop..

I realize It's almost 11PM your time, do you want to give a quick look at this patch set tomorrow morning? The debug commit ("drop me") does help one see that indeed ccache is used. If that helps. The `ccache --show-stats` at the end also is a good indicator I suppose (An all-zero cache means we didn't actually use ccache)

**Comment by d** [comment]
Pipeline is green, merging shortly

**Comment by d** [comment]
So Travis _just_ finished a build on after merging this patch set (https://travis-ci.org/github/greenplum-db/gpdb/builds/683468750). And I've just merged in PR #9997 so that build (https://travis-ci.org/github/greenplum-db/gpdb/builds/683481297) will be the first to benefit from a compilation cache. I'll report back on the perceived speedup!

**Comment by d** [comment]
N.B. the timing below includes both the build time _and_ the time it takes to run the tests. Caching is only gonna speed up the compilation time, not the test run time.

matrix entry | cold cache | warm cache
---|---|---
GCC | 868.21 | 441.29s
Clang | 573.61s | 335.02s
Xcode | 878.92s | 345.86s
GCC w/o compression * | 826.77s | 276.36s

* Disclosure: the "GCC w/o compression libs" comparison doesn't come from the Travis build for merging #9997 because it somehow got a pretty stale cache. I pulled the numbers instead from a [later pull request build](https://travis-ci.org/github/greenplum-db/gpdb/jobs/683623018). The original comparison numbers are here:

matrix entry | cold cache | warm cache
---|---|---
GCC w/o compression | 826.77s | 853.02s

**Pull request merged**
