### PR TITLE
Compile 5x on catalina

### PR DESCRIPTION
**Pull request by berlin-ab**
- I backported a few changes from upstream related to compiling on Mojave
- I updated the checkinc.py from regress to also search PG_SYSROOT for includes
- I updated `gpAux/platform/gpnetbench` to use the makefile global flags

### CODE REVIEW

**Comment by Eulerizeit** [comment]
Are these changes already on master and 6.x?  Is a cherry pick from there not possible?

**Comment by berlin-ab** [comment]
They are cherry-picked from 6x, but introduced by upstream. Sorry for the confusion.

**Comment by ashwinstar** [comment]
Why not cherry-pick this commit and remove the `checkinc.py`?

```
commit 0ba05383b95a43948f638eea201b1292a4e2bf57
Author: Daniel Gustafsson <dgustafsson@pivotal.io>
Date:   Tue Jul 2 08:55:39 2019 +0200

    Remove checkinc script and Makefile target
    
    The checkinc.py script was performing a check for the presence of
    header files we're not shipping.  This was essentially guaranteed
    to always pass as the code was able to compile, and has generally
    provided little value.  Recent changes in macOS installations has
    also made it fail with false positives, so finally remove it to
    minimize developer time spent fighting quite useless tests.
    
    Any checks for headers should be performed in autoconf before the
    code is compiled, not during testing.
    
    Discussion: https://github.com/greenplum-db/gpdb/issues/7961
    https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/cCXsHwPr7GM/XbExPStmAgAJ
    Reviewed-by: Ashwin Agrawal, Jimmy Yih
```

**Comment by berlin-ab** [comment]
Sure, sounds good.

**Comment by berlin-ab** [comment]
@ashwinstar Updated. I'll rebase out that `checkinc.py` script before merging.

**Comment by ashwinstar** [comment]
I suppose no one is complaining anymore about this, which means no one is facing the issue. I develop on linux, so no idea about this pain. @asimrp any ideas on need for this exist or please feel free to close it.

**Comment by chrishajas** [comment]
> I suppose no one is complaining anymore about this, which means no one is facing the issue. I develop on linux, so no idea about this pain. @asimrp any ideas on need for this exist or please feel free to close it.

I'm supportive of merging "Remove checkinc script and Makefile target", I've hit that when developing on 5X.

**Comment by asimrp** [comment]
Yes, checkinc.py is a problem on MacOS.  When compiling 5X, I disable it manually every time.

Upon rebasing against the latest 5X, the patch still fails to compile on my MacOS 10.15.6 due a perl script in `ecpg` using a feature that's no longer available in Perl.

```sh
[~/workspace/gpdb5]$ make -C src/interfaces/ecpg
"/usr/local/bin/perl" ./parse.pl . < ../../../../src/backend/parser/gram.y > preproc.y
Assigning non-zero to $[ is no longer possible at ./parse.pl line 21.

**Comment by ashwinstar** [comment]
I am closing this PR, seems no interest from anyone to pursue and complete it out either due to no need for it or folks are happy with their own workarounds to develop on MAC.

**Pull request closed without merging**
