### PR TITLE
Starve case improvements

### PR DESCRIPTION
**Pull request by seryozhasmirnov**
Merge fixes to 5x to improve starve case test.

In upstream Postgres, pg_locks exposes part of the lock manager so that
DBA's can inspect locks taken by various backends. In Greenplum, we
modified pg_lock_status() -- the function that underlies pg_locks -- to

a) provide additional Greenplum-specific information (e.g.
mppsessionid); and

b) aggregate the locks from master and all primary segments.

One consequence of the implementation we chose to achieve point b above,
is that queries that involve both pg_locks and a distributed table won't
work. If you're lucky (planner or ORCA places the function call in the
top slice), it "won't work" and throws an error like this at you:

ERROR: query plan with multiple segworker groups is not supported

If you're not lucky (planner or ORCA schedules the function call on a
different slice running on master), it most likely secretly doesn't do
point b and only returns locks from the master.

Before we fix pg_locks, rewrite the isolation2 test case "starve_case"
to separate the repeated queries in pg_locks from the main query. This
does logically the same thing in PL/pgSQL but it's now safe.

This commit also adds starve_case back to the isolation2 schedule.

### CODE REVIEW

**Comment by seryozhasmirnov** [comment]
Dear @kainwen, I see that https://github.com/greenplum-db/gpdb/pull/11215 is merged to **5X_STABLE**.

Please take a look at this PR that provides improvements for starve case from master.

**Comment by kainwen** [comment]
> Dear @kainwen, I see that #11215 is merged to **5X_STABLE**.
> 
> Please take a look at this PR that provides improvements for starve case from master.

Hi @seryozhasmirnov I see 5X pipeline is red after that is merged. I do not have time to look into today.  Will first check for that PR and then come to this.

**Comment by seryozhasmirnov** [comment]
> > Dear @kainwen, I see that #11215 is merged to **5X_STABLE**.
> > Please take a look at this PR that provides improvements for starve case from master.
> 
> Hi @seryozhasmirnov I see 5X pipeline is red after that is merged. I do not have time to look into today. Will first check for that PR and then come to this.

Dear @kainwen, just to follow up if the 5X pipeline is green.
Thank you!

**Comment by kainwen** [comment]
Looks good. But I notice this is for 5X. I doubt that we will release this for 5X.

cc @ashwinstar

**Comment by ashwinstar** [comment]
If its only the change in this PR and not dependent on anything else, I am fine applying the same to 5X_STABLE as fixes crashing with ORCA without the change.

**Comment by kainwen** [comment]
I will rebase this locally and run the full pipeline, after pipeline get green, I push this.

Thanks a lot for your contribution!

**Pull request merged**
