### PR TITLE
7X: Add compile job for rhel8

### PR DESCRIPTION
**Pull request by bhanu-atturu**
Authored-by: Bhanu Kiran Atturu <batturu@vmware.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by 50wu** [comment]
See the [dev pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-GP-1089-compile-rhel8-7X?group=Release) is a little weird. The input of `gate_release_candidate_start` looks so many duplicate resources and the `Release_Candidate` is seperately.

**Comment by 50wu** [comment]
> See the [dev pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-GP-1089-compile-rhel8-7X?group=Release) is a little weird. The `Release_Candidate` job is separate, should it be after the `gate_release_candidate_start` job like the 6X_STABLE pipeline?
> 
> Also, we need to add the `bin_gpdb_rhel8_rc` as well.

No worries, I add the `bin_gpdb_rhel8_rc` on the branch https://github.com/greenplum-db/gpdb/compare/master...pivotal:GP-1060-add-tests-rhel8-gpdb7?expand=1 when doing the GP-1060, just checkout from your branch :-)

**Comment by bhanu-atturu** [comment]
I had removed passed condition for testing, I have reset the pipeline now. I didn't add bin_gpdb_rhel8_rc since it has to be added after adding tests like ICW, CLI.

**Review by BaiShaoqi — APPROVED** [review]
Looks good to me!

**Pull request merged**
