### PR TITLE
pull dependencies at build time

### PR DESCRIPTION
**Pull request by visualphoenix**
download available versions of dependencies with pip/wget at build time. update source build/lib.* path.

### CODE REVIEW

**Comment by ivannovick** [comment]
@jimmyyih @edespino does this fix our issue with python dependancies I had this morning?

**Comment by visualphoenix** [comment]
@ivannovick these fixes enabled me to use the docker builder in my other pull request to successfully build gpdb

**Comment by visualphoenix** [comment]
@ivannovick i have yet to test them on rhel. will update the docker builder to include a centos build environment to check that these changes are compatible.

**Comment by visualphoenix** [comment]
@ivannovick 7f9467c seems to change the check so it doesnt try to build this missing stuff. are any of these tools or the tools that depend on these python packages required?

**Comment by ivannovick** [comment]
@jimmyyih is expert on this, and can answer what to do here.

**Comment by jimmyyih** [comment]
@visualphoenix the "missing stuff" is required for some gpMgmt utilities.  We were unsure how a developer would want to install these python packages whether it be on their system python, a virtualenv, or some other way so we left those as a README requirement.  The pythonSrc/ext directory that we check for is just a directory full of unedited python tarballs that get built and pushed with the binaries (PYTHONPATH line in greenplum_path.sh).  This patch mimics our submodule process pretty well.  We'll do some verification and most likely accept this patch.

**Comment by visualphoenix** [comment]
Treasure Data bundles a verified known-good ruby build with fluentd. Maybe you guys could do the same for gpdb python. What I had to do to pull the pychecker source is less elegant. Might consider bundling that source at minimum since it doesnt seem to be actively maintained.

**Pull request closed without merging**
