### PR TITLE
FIXME remove gp_enable_sort_distinct and noduplicates optimizing

### PR DESCRIPTION
**Pull request by yaowangm**
On GPDB6, the GUC `gp_enable_sort_distinct` is used to optimize sort by indicating "noduplicate" to remove duplicated rows and reduce data handling. It effects on replacement selection sort only. However, on GPDB7, replacement selection sort has been removed completely. So we need to remove `gp_enable_sort_distinct` and other codes related to "noduplicate" sort.

In GPDB6, `Tuplesortstate` has a member `noduplicates`:
```
 326     bool        noduplicates;   /* discard duplicate rows if true *//* CDB */
```
The usages of `noduplicates` is to indicate `tuplesort_sorted_insert()` to discard duplicated tuples:
```
3990     if (state->noduplicates && (0 == comparestat))
3991     {
3992         freetup = tuple;
3993         goto L_freetup;
3994     }
```
And they are ONLY usages of noduplicates, which has been removed on GPDB7.

Besides those, there are other codes, including `Sort.noduplicates` and `SortState.noduplicates`, which are just related to save and pass the flag. All of they need to be removed on GPDB7.

### CODE REVIEW

**Comment by interma** [comment]
This PR is LGTM for me, but looks it missed some places which referred `gp_enable_sort_distinct`, I found:
https://github.com/greenplum-db/gpdb/blob/a1cb6e44b7eb5b060652bd9a3274057b8cdb8731/src/include/utils/unsync_guc_name.h#L198
https://github.com/greenplum-db/gpdb/blob/a1cb6e44b7eb5b060652bd9a3274057b8cdb8731/src/backend/utils/misc/postgresql.conf.sample#L377

May also have other places, please take a look and remove them. (especially non-*.c/*.h files)
Thanks!

**Comment by yaowangm** [comment]
> This PR is LGTM for me, but looks it missed some places which referred `gp_enable_sort_distinct`, I found:
> 
> https://github.com/greenplum-db/gpdb/blob/a1cb6e44b7eb5b060652bd9a3274057b8cdb8731/src/include/utils/unsync_guc_name.h#L198
> 
> https://github.com/greenplum-db/gpdb/blob/a1cb6e44b7eb5b060652bd9a3274057b8cdb8731/src/backend/utils/misc/postgresql.conf.sample#L377
> 
> May also have other places, please take a look and remove them. (especially non-_.c/_.h files) Thanks!

Many thanks for your found! Yes I did miss the non-_.c/_.h files. This time I scanned all the files and didn't find any more. Code has been updated.

**Review by vraghavan78 — APPROVED** [review]

**Review by interma — APPROVED** [review]
LGTM

**Review by adam8157 — COMMENTED** [review]
Have you considered getting the optimization back? It's not complicated in Greenplum 6.

I haven't checked if it's complicated to set `noduplicates` based on the planner estimation.

**Comment by yaowangm** [comment]
> Have you considered getting the optimization back? It's not complicated in Greenplum 6.
> 
> I haven't checked if it's complicated to set `noduplicates` based on the planner estimation.

Thanks for your comments. I did consider the possibility. As I saw, the noduplicates optimization is applied only for replacement selection sort, and not for other sort algorithms in GPDB7 (and the optimization never exists on upstream). So I afraid it's infeasible unless we can implement a new sort algorithm which can utilize the optimization.

**Pull request merged**
