### PR TITLE
Karthijrk node agg issue

### PR DESCRIPTION
**Pull request by karthijrk**
When there is an aggregate with rollup(complex aggregate), we found it is causing seg fault because we still have pointer to memory which was deleted. This change has a function that reset all the memory to NULL when associate memory context get deleted. 

@gcaragea @armenatzoglou @foyzur @entong @xinzweb 
Please take a look when you get chance

### CODE REVIEW

**Comment by hlinnaka** [comment]
That's a prettu complicated test case. Can you reduce it to something simpler?

**Comment by karthijrk** [comment]
@hlinnaka This test run about 0.94 sec in my laptop. Is there any motivation to reduce this test complexity?. We do have some simple aggregate test already in our ICG and tinc. This test exercise many parts of code and I am not able to reproduce crash easily with simple sql. Let me know if you still have reason to go for simpler case. I am more than happy to work with you to write some simpler one to reproduce this issue.

**Comment by hlinnaka** [comment]
On 01/12/15 03:14, Karthikeyan Jambu Rajaraman wrote:
> @hlinnaka This test run about 0.94 sec in my laptop. Is there any
> motivation to reduce this test complexity?. We do have some simple
> aggregate test already in our ICG and tinc. This test exercise many
> parts of code and I am not able to reproduce crash easily with simple
> sql. Let me know if you still have reason to go for simpler case. I
> am more than happy to work with you to write some simpler one to
> reproduce this issue.

Well, simpler is always better. From this complicated query, I couldn't 
figure out what makes that query special from all the other queries. So 
yeah, please try to simplify it.

- Heikki

**Comment by atris** [comment]
Agreed.

One of the objectives of the test case is to be able to pull out a small section of queries and have them emulate the scenario. This allows easier and simpler trace through and ensuring that the corner case is actually holistically solved.

Please provide an independent minimalistic set of queries that trigger the corner case.

**Comment by karthijrk** [comment]
I am closing this pull request. I will add a simpler test case and open new pull request.

**Comment by karthijrk** [comment]
Here is the new pull request https://github.com/greenplum-db/gpdb/pull/143

**Pull request closed without merging**
