### PR TITLE
Avoid could not open file pg_subtrans/xxx situation during recovery.

### PR DESCRIPTION
**Pull request by ashwinstar**
Initialize TransactionXmin to avoid situations where scanning pg_authid or other
tables mostly in BuildFlatFiles() via SnapshotNow may try to chase down
pg_subtrans for older "sub-committed" transaction. File corresponding to which
may not and is not supposed to exist. Setting TransactionXmin will avoid calling
SubTransGetParent() in TransactionIdDidCommit() for older XIDs.

Repro for record of one such case:
```
CREATE ROLE foo;

BEGIN;
SAVEPOINT sp;
DROP ROLE foo;
RELEASE SAVEPOINT sp; -- this is key which marks in clog as sub-committed.

kill or gpstop -air
< N transactions to atleast cross pg_subtrans single file limit roughly
CLOG_XACTS_PER_BYTE * BLCKSZ* SLRU_PAGES_PER_SEGMENT >

restart -- errors recovery with missing pg_subtrans
```

Note:
Merge with 9.0 will get rid of BuildFlatFiles() (actually whole flatfiles.c) till then this is needed.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Look good as far as it goes. I wonder if we would need to also set RecentGlobalXmin? Heap access functions contain Assertions that RecentGlobalXmin is set. Or is it set elsewhere already? If so, a comment to explain where it's set would be good.

**Comment by ashwinstar** [comment]
Initialized RecentGlobalXmin, yes should do it too, wasn't initialized. Not sure why no assert fired.

**Comment by hlinnaka** [comment]
And how about RecentXmin? Not sure if that's needed for anything we care here..

**Comment by ashwinstar** [comment]
On Fri, Mar 31, 2017 at 10:59 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> And how about RecentXmin? Not sure if that's needed for anything we care
> here..
>
Had checked that and its seems not.

**Pull request merged**
