### PR TITLE
Remove unused code and fix compiler warnings from upstream

### PR DESCRIPTION
**Pull request by danielgustafsson**
Commit ff3474e which removed the `gp_partition_*` catalog functions left some auxiliary code behind which is now unused. Remove the now dead functions and while in there, put back the filename in the file header comment to match other files.

Also cherry-pick https://github.com/postgres/postgres/commit/418e1d82 from upstream which cleans up a few `sprintf()` calls and by that removes compiler warnings.

@vraghavan78 does this cleanup look Ok?

### CODE REVIEW

**Comment by hlinnaka** [comment]
These two patches are not in any way related to each other, right?

Anyway, +1 for both.

**Comment by danielgustafsson** [comment]
> On 28 Oct 2016, at 20:41, Heikki Linnakangas <notifications@github.com> wrote:
> 
> These two patches are not in any way related to each other, right?
> 
> Anyway, +1 for both.

Well, they kind of sort of are since I went on a silence-compiler-warning spree and thats the common denominotor. Looking at the PR though, that wasn’t at all clear.

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review!

**Comment by vraghavan78** [comment]
Sorry for the delay in response. Thanks for doing this.

**Pull request closed without merging**
