### PR TITLE
Use text type in output of array type

### PR DESCRIPTION
**Pull request by baobao0206**
If the field type is array, then the type of statistical information
will be array[array]. But now we use One-dimensional array like
array[float].

Since we have output in a good format, if it is considered to be of text
type, it will be automatically converted to array[array]

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by dgkimura — COMMENTED** [review]
A minirepro regress test was added as part of commit 908280a199.  Is it possible to add a testcase that exercises this change?

**Review by chrishajas — COMMENTED** [review]
Thanks! This change looks good! Can you also update `gpMgmt/bin/gpsd` (should be a near identical code change) in addition to adding a test. Note that when this is fixed in the master branch, this code is in a common function so there isn't duplication.

**Comment by baobao0206** [comment]
Add test for minirepro

**Comment by baobao0206** [comment]
Have add test cases for minirepro

**Comment by bhuvnesh2703** [comment]
@baobao0206 master has a minirepro.sql which has a different set of test cases, any reason why we cannot port the master's minirepro.sql and add the test which is relevant to this fix?

**Review by bhuvnesh2703 — APPROVED** [review]
Tested. The fix works.

Earlier if we load the data as suggested in the test, we get this error:
```
psql:/tmp/t2.out:120: ERROR:  invalid input syntax for integer: "{10000,10000,10000,10000}"
LINE 23:  E'{"{10000,10000,10000,10000}"}'::_int4,
```

Now it loads fine.

**Review by chrishajas — APPROVED** [review]

**Pull request merged**
