### PR TITLE
5X_STABLE pipeline: add Ubuntu and make more like master pipeline

### PR DESCRIPTION
**Pull request by goutamtadi1**
- Cherry pick Ubuntu jobs from master.
- Cherry pick @ashwinstar cf0ce92 commit to add trigger to control frequency so that future cherry-picks can come across cleanly
- Update syntax on boolean flags for concourse 3.x

### CODE REVIEW

**Comment by goutamtadi1** [comment]
@doty-pivotal We just realized that we did not pick few older commits that should be part of this. Thanks to PR pipeline which detected those changes. We will add new stuff and fly a dev pipeline in one of the concourse instances (gpbosh/gpdb-dev) and update you.

**Comment by larham** [comment]
@doty-pivotal The test pipeline for this is at https://gpdb-dev.data.pivotal.ci/teams/main/pipelines/gpbosh_5X_STABLE  (currently running from scratch)

**Comment by doty-pivotal** [comment]
+1 but can't seem to approve ... hmmm

**Comment by larham** [comment]
In the results of the PR pipeline for this PR, the failure on the QP test "qp_correlated_query" is a well-understood issue that is fixed in master and just waiting to be pushed for 5X_STABLE.  Therefore, we consider this PR ready to be pushed.

**Pull request merged**
