### PR TITLE
Skip eliminating alien node on master for FDW with private list

### PR DESCRIPTION
**Pull request by zhangh43**
In PXF, the fdw private list is used to store meta data from
external source like hive.
To avoid accessing external source on each segment, PXF will
initialize the fdw private list on master and fetch from hive
only once for better performance. Since this work is done in
ExecInitNode, thus we should skip eliminating alien node on master.

test case is in PXF pipeline.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by hlinnaka** [comment]
Two thoughts:

1. I can see that pxfBeginForeignScan() fetches the fragment list and stores it in ForeignScan->fdw_private. That's quite a hack; the Plan tree might point to a cached query in the plan cache, for example, so modifying the ForeignScan directly seems wrong. I think we should provide a proper interface for FDWs to do this. I'm not sure what, but there should be a better place to store information that should be dispatched along to the QEs.

2. How about we just revert commit 874939f47f? This patch introduces a new walk through the plan tree, which I complained about in the first version of PR #9938 already. The performance gain i really small, I still don't think this is worth it.

**Comment by frankgh** [comment]
> Two thoughts:
> 
> 1. I can see that pxfBeginForeignScan() fetches the fragment list and stores it in ForeignScan->fdw_private. That's quite a hack; the Plan tree might point to a cached query in the plan cache, for example, so modifying the ForeignScan directly seems wrong. I think we should provide a proper interface for FDWs to do this. I'm not sure what, but there should be a better place to store information that should be dispatched along to the QEs.

@hlinnaka  We decided to use `fdw_private` because the documentation states the following:

 > _GetForeignPlan can examine the fdw_private field of the selected ForeignPath node, and can generate fdw_exprs and fdw_private lists to be placed in the ForeignScan plan node, where they will be available at execution time. Both of these lists must be represented in a form that copyObject knows how to copy. The fdw_private list has no other restrictions and is not interpreted by the core backend in any way._

https://www.postgresql.org/docs/9.4/fdw-planning.html

> 2. How about we just revert commit [874939f](https://github.com/greenplum-db/gpdb/commit/874939f47f64e472395a807ad28915b8e4d7f59e)? This patch introduces a new walk through the plan tree, which I complained about in the first version of PR #9938 already. The performance gain i really small, I still don't think this is worth it.

As for this PR, I have tested it and it is working correctly in my local.

**Comment by hlinnaka** [comment]
On 28/04/2020 14:27, Francisco Guerrero wrote:
>     Two thoughts:
> 
>      1. I can see that pxfBeginForeignScan() fetches the fragment list
>         and stores it in ForeignScan->fdw_private. That's quite a hack;
>         the Plan tree might point to a cached query in the plan cache,
>         for example, so modifying the ForeignScan directly seems wrong.
>         I think we should provide a proper interface for FDWs to do
>         this. I'm not sure what, but there should be a better place to
>         store information that should be dispatched along to the QEs.
> 
> @hlinnaka <https://github.com/hlinnaka> We decided to use |fdw_private| 
> because the documentation states the following:
> 
>     /GetForeignPlan can examine the fdw_private field of the selected
>     ForeignPath node, and can generate fdw_exprs and fdw_private lists
>     to be placed in the ForeignScan plan node, where they will be
>     available at execution time. Both of these lists must be represented
>     in a form that copyObject knows how to copy. The fdw_private list
>     has no other restrictions and is not interpreted by the core backend
>     in any way./

Right. But *modifying* fdw_private, or any other part of the Plan tree 
for that matter, in InitPlan phase seems unsafe.

Given that the Plan tree might come from the plan cache, what would 
happen if you have two executors running the same plan at the same time, 
for example? They would write over each other's fdw_private. Maybe it 
can't happen because there are other limitations that prevent it, but 
it's certainly not intended to be used like that.

I don't have an immediate better answer for you, unfortunately. I do 
think we do need a better mechanism for this, however.

- Heikki

**Comment by frankgh** [comment]
> Right. But *modifying* fdw_private, or any other part of the Plan tree for that matter, in InitPlan phase seems unsafe. Given that the Plan tree might come from the plan cache, what would happen if you have two executors running the same plan at the same time, for example? They would write over each other's fdw_private. Maybe it can't happen because there are other limitations that prevent it, but it's certainly not intended to be used like that. I don't have an immediate better answer for you, unfortunately. I do think we do need a better mechanism for this, however. - Heikki

That's a good point. However, by looking at the code, it looks like FDWs `GetForeignPlan` will create a new `ForeignScan` every time.

```
static ForeignScan *
pxfGetForeignPlan(PlannerInfo *root,
				  RelOptInfo *baserel,
				  Oid foreigntableid,
				  ForeignPath *best_path,
				  List *tlist,	/* target list */
				  List *scan_clauses)
{
	....
	return make_foreignscan(
							tlist,
							scan_clauses,
							scan_relid,
							NIL,	/* no expressions to evaluate */
							fdw_private);
		);
```

The `ForeignScan` returned by the `make_foreignscan` function is unique https://github.com/greenplum-db/gpdb/blob/master/src/backend/optimizer/plan/createplan.c#L5829. A new node is always created. Even if the plan might be cached, the `ForeignScan` node should not be cached. The `fdw_private` is a field in the `ForeignScan`, which is what we are propagating from QD to QEs, so I am really not concerned two executors running the same plan at the same time because the node should be unique.

**Comment by zhangh43** [comment]
> 2\. How about we just revert commit [874939f](https://github.com/greenplum-db/gpdb/commit/874939f47f64e472395a807ad28915b8e4d7f59e)? This patch introduces a new walk through the plan tree, which I complained about in the first version of PR #9938 already. The performance gain i really small, I still don't think this is worth it.

@hlinnaka  I'm fine to revert the original commit. Here is the reason why introduce this commit. If you still think it's not necessary, I will revert that PR.

This feature is requested by the HTAP scenario.  OLTP queries, especially select only queries, are often master CPU bound, while the OLAP queries often contain many slices. As the slices increase, we could see the InitPlan CPU percentage would rise as well on master. commit [874939f](https://github.com/greenplum-db/gpdb/commit/874939f47f64e472395a807ad28915b8e4d7f59e) could reduce the InitPlan cpu cost on master even if we run the plan tree walker. In fact, the bigger the plan tree is, the cost of walker is also higher. But the ExecInitNode cost is always much higher than walker.

**Comment by kainwen** [comment]
> > 2. How about we just revert commit [874939f](https://github.com/greenplum-db/gpdb/commit/874939f47f64e472395a807ad28915b8e4d7f59e)? This patch introduces a new walk through the plan tree, which I complained about in the first version of PR #9938 already. The performance gain i really small, I still don't think this is worth it.
> 
> @hlinnaka I'm fine to revert the original commit. To help you understand the full context, I'll summary the reason why introducing this commit. If you still think it's not necessary, I will revert that PR.
> 
> This feature is requested by the HTAP scenario. OLTP queries, especially select only queries, are often master CPU bound, while the OLAP queries often contain many slices. As the slices increase, we could see the InitPlan CPU percentage would rise as well on master. commit [874939f](https://github.com/greenplum-db/gpdb/commit/874939f47f64e472395a807ad28915b8e4d7f59e) could reduce the InitPlan cpu cost on master even if we run the plan tree walker. In fact, the bigger the plan tree is, the cost of walker is also higher. But the ExecInitNode cost is always much higher than walker.

Just my 2 cent,

OLTP query is often very simple and direct-dispatched (no slice).

OLAP workload, master should not be the bottleneck.

**Comment by hlinnaka** [comment]
On 29/04/2020 10:49, Hubert Zhang wrote:
>     2. How about we just revert commit 874939f
>     <https://github.com/greenplum-db/gpdb/commit/874939f47f64e472395a807ad28915b8e4d7f59e>?
>     This patch introduces a new walk through the plan tree, which I
>     complained about in the first version of PR #9938
>     <https://github.com/greenplum-db/gpdb/pull/9938> already. The
>     performance gain i really small, I still don't think this is worth it.
> 
> @hlinnaka <https://github.com/hlinnaka> I'm fine to revert the original 
> commit. Here is the reason why introduce this commit. If you still think 
> it's not necessary, I will revert that PR.
> 
> This feature is requested by the HTAP scenario. OLTP queries, especially 
> select only queries, are often master CPU bound, while the OLAP queries 
> often contain many slices. As the slices increase, we could see the 
> InitPlan CPU percentage would rise as well on master. commit 874939f 
> <https://github.com/greenplum-db/gpdb/commit/874939f47f64e472395a807ad28915b8e4d7f59e> 
> could reduce the InitPlan cpu cost on master even if we run the plan 
> tree walker. In fact, the bigger the plan tree is, the cost of walker is 
> also higher. But the ExecInitNode cost is always much higher than walker.

Even in an OLTP query, I doubt the InitPlan overhead in master is 
significant, compared to all the other things that happen, like 
dispatching the query. I could be wrong - wouldn't be the first time - 
but I won't believe it without some performance testing. You mentioned a 
test in the original PR, where ExecInitPlan CPU usage went from 3.8% to 
0.45%. That's a good start for testing, but you said yourself that it's 
not the bottleneck in that test, so it won't yield any meaningful 
user-visible gain.

So yeah, please just revert it. Thanks!

- Heikki

**Comment by zhangh43** [comment]
commit [874939f](https://github.com/greenplum-db/gpdb/commit/874939f47f64e472395a807ad28915b8e4d7f59e) reverted.
This PR will also be closed.

**Pull request closed without merging**
