### PR TITLE
Guard Recursive CTE behind a GUC

### PR DESCRIPTION
**Pull request by sambitesh**
While Recurisve CTE is still being developed it will be hidden from users by
the guc gp_recursive_cte_prototype

Signed-off-by: Sambitesh Dash <sdash@pivotal.io>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sambitesh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2986)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2986) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sambitesh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2986)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2986) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sambitesh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2986)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2986) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sambitesh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2986)!

**Comment by hsyuan** [comment]
I don't see the necessity of adding the GUC.
But putting this aside, you should update the ICG test to turn on the GUC, because the recursive CTE is disabled by default in this patch.

**Comment by d** [comment]
Hiding the feature behind a GUC is a product decision, @hsyuan.

But I concur, we should exercise the feature in relevant tests by enabling that GUC.

- Jesse

**Comment by vraghavan78** [comment]
We should exercise the feature in the recursive cte tests. But disable it by default.

**Comment by melanieplageman** [comment]
Our intent is to merge our recursive CTE work to master, so we are closing this and opening a new PR against `master`

Sam, Melanie, and Jesse

**Pull request closed without merging**
