### PR TITLE
Fix Orca stream operator<< precision

### PR DESCRIPTION
**Pull request by dgkimura**
Issue is that string formatter in COstream used plain "%f" which may
lead to truncation of significant digits. By default it keeps 6 digits
after the decimal. This caused Orca to mistakenly identify two
inequivalent statistics with a small precision diff as being identical.
That mistake occasionally led to assertion errors when merging histogram
statistics.

Fix is to preserve the significant bits for double values. The scope of
the change is limited to bucket upper/lower bounds.

### CODE REVIEW

**Review by zellerh — APPROVED** [review]
LGTM.

**Comment by chrishajas** [comment]
I think the assertion this is trying to fix is: `GPOS_ASSERT_IMP(IsSingleton(), is_lower_closed && is_upper_closed);`

Does this only increase the precision of the bounds of the dxl buckets from GPDB, or did the merging process also lose precision?

We currently consider two double values as equal if they're within some epsilon (0.00001). Does that assumption still hold?

**Comment by dgkimura** [comment]
@chrishajas Thanks for the questions as they forced me to dive a little deeper!

> I think the assertion this is trying to fix is: `GPOS_ASSERT_IMP(IsSingleton(), is_lower_closed && is_upper_closed);`

Yup, that's the intent.  `IsSingleton()` checks whether the double values are equal (i.e. if they're within epsilon of each other as you pointed out).

In the SQL test in the commit, the stats are `-0.25475` and `-0.2547399` which differ by `0.0000101`.  Since that's `0.0000001` more than epsilon, it should not be considered equal.  But when we only enforced 6 significant digits, the values in this example turned out to be `-0.25474999999999998` and `-0.25474000000000002` due to rounding of floats.  The difference between the values is `0.00000999999999996` which happens to be just shy of epsilon.  Thus it was mistakenly considered equal.

> Does this only increase the precision of the bounds of the dxl buckets from GPDB, or did the merging process also lose precision?

It should only be the bounds of the dxl buckets.

> We currently consider two double values as equal if they're within some epsilon (0.00001). Does that assumption still hold?

Yes, that assumption should still hold.

**Review by chrishajas — APPROVED** [review]
> In the SQL test in the commit, the stats are `-0.25475` and `-0.2547399` which differ by `0.0000101`. Since that's `0.0000001` more than epsilon, it should not be considered equal. But when we only enforced 6 significant digits, the values in this example turned out to be `-0.25474999999999998` and `-0.25474000000000002` due to rounding of floats. The difference between the values is `0.00000999999999996` which happens to be just shy of epsilon. Thus it was mistakenly considered equal.
> 
If I understand correctly, this is purely due to rounding of the float, causing it to round by more than epsilon. By adding more precision, the rounding would be more likely to round to a value less than epsilon. In the translator, we end up marking the above bucket not a singleton, but after we send it to Orca, we consider it a singleton due to rounding, and that mismatch causes the assertion failure. 

Was using 17 digits done to further minimize the chance of a rounding error (since we might be able to still hit this issue if we increased precision by 1-2 digits?)

Is `%g` safe here (https://stackoverflow.com/questions/54162152/what-precisely-does-the-g-printf-specifier-mean)?

**Comment by dgkimura** [comment]
> If I understand correctly, this is purely due to rounding of the float, causing it to round by more than epsilon. By adding more precision, the rounding would be more likely to round to a value less than epsilon. In the translator, we end up marking the above bucket not a singleton, but after we send it to Orca, we consider it a singleton due to rounding, and that mismatch causes the assertion failure.

Yes, that matches my understanding.

> Was using 17 digits done to further minimize the chance of a rounding error (since we might be able to still hit this issue if we increased precision by 1-2 digits?)

Yeah, I figured adding more significant digits shouldn't hurt.

> Is `%g` safe here (https://stackoverflow.com/questions/54162152/what-precisely-does-the-g-printf-specifier-mean)?

Do you have suspicions?  I don't quite see why it may not be.  I really only used `%g` as an attempt to keep the MDP a little more readable, but can change back to `%f`.

**Comment by dgkimura** [comment]
Merged. Thanks for reviews!

**Pull request merged**
