### PR TITLE
fix gpfdist regression failure due to fdw code removing by 601c58c33a…

### PR DESCRIPTION
**Pull request by yydzero**
fix gpfdist regression failure due to fdw code removing by 601c58c33aa9f8686e2a128153aa0272c7e878a5; 

also remove duplicated cases

### CODE REVIEW

**Comment by yydzero** [comment]
pushed

**Comment by hlinnaka** [comment]
Hmm, 601c58c33a was committed a long time ago. Why haven't we seen 
regression failures because of this? Are we not running the gpfdist 
tests regularly?

- Heikki

**Comment by yydzero** [comment]
Yes, as now we have moved gpfdist test cases along with gpfdist code, and
gpfdist is not built by default.  For CI, sounds like we don't enable
installcheck for gpfdist.

I don't understand why we don't build gpfdist by default. Do you have any
insights?

Regards,
Yandong

On Tue, Jan 5, 2016 at 7:14 PM, Heikki Linnakangas <notifications@github.com
> wrote:

> Hmm, 601c58c33a was committed a long time ago. Why haven't we seen
> regression failures because of this? Are we not running the gpfdist
> tests regularly?
>
> - Heikki
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/pull/237#issuecomment-168974374>.
>



-- 
Best Regards,
Yandong

**Comment by yydzero** [comment]
Hi Guys,

If there is no objection, we will enable build for gpfdist by default and
include cases into ICG.

gpfdist has only 2 c files, so it will not increase build time in a visible
way.

Regards,
Yandong

On Tue, Jan 5, 2016 at 10:00 PM, Yandong Yao <yyao@pivotal.io> wrote:

> Yes, as now we have moved gpfdist test cases along with gpfdist code, and
> gpfdist is not built by default.  For CI, sounds like we don't enable
> installcheck for gpfdist.
>
> I don't understand why we don't build gpfdist by default. Do you have any
> insights?
>
> Regards,
> Yandong
>
> On Tue, Jan 5, 2016 at 7:14 PM, Heikki Linnakangas <
> notifications@github.com> wrote:
>
>> Hmm, 601c58c33a was committed a long time ago. Why haven't we seen
>> regression failures because of this? Are we not running the gpfdist
>> tests regularly?
>>
>> - Heikki
>>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/greenplum-db/gpdb/pull/237#issuecomment-168974374>.
>>
>
>
>
> --
> Best Regards,
> Yandong
>



-- 
Best Regards,
Yandong

**Comment by ashwinstar** [comment]
Yes please, Thanks.

On Jan 5, 2016, at 8:39 PM, Yandong Yao <notifications@github.com> wrote:

Hi Guys,

If there is no objection, we will enable build for gpfdist by default and
include cases into ICG.

gpfdist has only 2 c files, so it will not increase build time in a visible
way.

Regards,
Yandong

On Tue, Jan 5, 2016 at 10:00 PM, Yandong Yao <yyao@pivotal.io> wrote:

> Yes, as now we have moved gpfdist test cases along with gpfdist code, and
> gpfdist is not built by default. For CI, sounds like we don't enable
> installcheck for gpfdist.
>
> I don't understand why we don't build gpfdist by default. Do you have any
> insights?
>
> Regards,
> Yandong
>
> On Tue, Jan 5, 2016 at 7:14 PM, Heikki Linnakangas <
> notifications@github.com> wrote:
>
>> Hmm, 601c58c33a was committed a long time ago. Why haven't we seen
>> regression failures because of this? Are we not running the gpfdist
>> tests regularly?
>>
>> - Heikki
>>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/greenplum-db/gpdb/pull/237#issuecomment-168974374>.
>>
>
>
>
> --
> Best Regards,
> Yandong
>



-- 
Best Regards,
Yandong

—
Reply to this email directly or view it on GitHub
<https://github.com/greenplum-db/gpdb/pull/237#issuecomment-169217908>.

**Comment by danielgustafsson** [comment]
:+1: on enabling.

**Pull request closed without merging**
