### PR TITLE
Undeprecate gpmapreduce

### PR DESCRIPTION
**Pull request by dyozie**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Please squash away the merge commits before pushing.

**Comment by dyozie** [comment]
Will do - I was unable to rebase due to some quirk in handling my fork, so had to merge instead.  We always squash PRs before merging as a rule anyhow.

**Comment by Eulerizeit** [comment]
Why are we Undeprecating this now? I thought we were going to talk to the
customers who were using it to figure out if it was something we needed to
continue to support.

-- Rob

**Comment by rvs** [comment]
my question exactly! I thought it was gone for good.

**Comment by dyozie** [comment]
Will let @ivannovick speak to this, as he was in touch with customers who used this in production and did not want it deprecated.  Happy to roll back the PR if something has changed.

**Comment by ivannovick** [comment]
Its my call guys, I am un-deprecating it.

REASON: Burden of proof is against removal of existing functions.

**Pull request merged**
