### PR TITLE
basebackup: optimize for large exclude list

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
This PR contains below two optimizations:

## pg_basebackup: new option to load exclude lists from files

The pg_basebackup command supports the --exclude option to exclude a
path name, it can be provided multiple times to exclude multiple path
names.  However it can be provided at most 255 times, the limit is
hard-coded in the source code because it is internall a fix-sized string
array.

To support excluding more path names, we could enlarge this number,
however there is still limits on the cmdline size or the argument count.

So we now provide a new option, --exclude-from=FILE, to get the path
names to exclude from a file.

## replication/basebackup: use hash table for the exclude list

The replication basebackup command supports excluding path names with
the EXCLUDE clause, the excluding list used to be stored internally as a
string list and be matched one by one, this can be very inefficient when
the excluding list is large.

Now we store the path names to exclude in a hash table for better
performance.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Document changes
- [x] Pass `make installcheck`
- [x] Review a PR in return to support the community

### CODE REVIEW

**Comment by hlinnaka** [comment]
What are you using the exclude list for?

**Comment by pivotal-ning-yu** [comment]
> What are you using the exclude list for?

We need large exclude list for https://github.com/greenplum-db/gpdb/pull/9551, it brings some optimizations to gpexpand, one of them is to exclude the master-only catalog tables from the segment template.

gpexpand creates new segments by first creating a segment template and then copying to the new segments.  The template is based on the master data directory, on master and 6X it's done with the pg_basebackup command.

Some catalog tables are considered as master-only due to some reasons, we need to ensure that they are cleared on the new segments:
https://github.com/greenplum-db/gpdb/blob/64c4588323ceaa7570553cf73ec07e34ce9ca539/gpMgmt/bin/gppylib/gpcatalog.py#L25-L38

We used to do the clearing by first copying the original tables from master to segments, then execute the `DELETE * FROM <tab>` on them, so unnecessary time are spent in several steps:
1. copying them from master data dir to the template;
2. transferring the template from master to new segments;
3. deleting them on the new segments.

Step 3 is extremely slow because the DELETE command is slow by nature, and we could not use TRUNCATE because the filenodes can't be changed on catalog tables.

So we want to optimize it by excluding the master-only data directly via pg_basebackup.  In gpdb the pg_basebackup command already has a `--exclude` option, it works but can be inefficient when a large exclude list is specified, so we intorduce the current PR to optimize this.

**Comment by pivotal-ning-yu** [comment]
Any objections or suggestions?  Otherwise I plan to have this merged tomorrow to unblock another PR.

**Comment by pivotal-ning-yu** [comment]
I'll merge it now, thanks for the reviews.

**Pull request merged**
