### PR TITLE
Disable multiple validations for master data directory in gpdeletesystem

### PR DESCRIPTION
**Pull request by shubh8689**
Refers to issue #1145 - Enables gpdeletesystem to use environment variable MASTER_DATA_DIRECTORY if command line argument -d is not set. If both -d and environment variable MASTER_DATA_DIRECTORY are set, -d will take precedence over environment variable.

### CODE REVIEW

**Comment by shubh8689** [comment]
How can I check concourse-ci build failure ?

**Comment by Eulerizeit** [comment]
@schubert @ryantang is there a way we can open this up?

**Comment by Chibin** [comment]
Looks good to me, but the help file would also need to be updated.
https://github.com/greenplum-db/gpdb/blob/master/gpMgmt/doc/gpdeletesystem_help

**Comment by shubh8689** [comment]
Accidentally merged complete branch into issue on local, fixing it. Revert applied as of now but not visible, I can see it in git log though. Please don't merge this pull request as of now.

**Comment by shubh8689** [comment]
Corrected the wrong merge.

**Comment by Chibin** [comment]
@mkiyama FYI, for doc updates

**Comment by Eulerizeit** [comment]
@Chibin have you written the documentation?

**Comment by Chibin** [comment]
Doc updates is in this commit:
https://github.com/greenplum-db/gpdb/pull/1385/commits/1f03a540dd7ab6460324690a148aa5fef3cf56f0

**Comment by shubh8689** [comment]
@Chibin I tried merging the changes but it appears that I don't have merge rights. Could you please help in merging this PR?

**Comment by cjcjameson** [comment]
Squashed and merged: https://github.com/greenplum-db/gpdb/commit/8de258ce9a73d1f57f3d0b3157d0855ebac5d0a0

Thank you for your contributions and patience!

**Pull request closed without merging**
