### PR TITLE
Add requirement to install ed text editor

### PR DESCRIPTION
**Pull request by sujeetv**

### CODE REVIEW

**Comment by ivannovick** [comment]
Yeah, this is a longstanding issue that Ed is required... can't wait until we get rid of that dependcy

**Comment by visualphoenix** [comment]
@sujeetv thanks - will add ed to the fpm dependencies in my docker builder branch.

**Comment by davecramer** [comment]
This is also required for debian based systems

**Comment by visualphoenix** [comment]
yeah. noticed that. it should be pretty easy to replace ed with sed. or is there another preferred tool?

**Comment by visualphoenix** [comment]
@hlinnaka if you prefer python, i'll do a rough pass in python

**Comment by hlinnaka** [comment]
On 10/29/2015 05:19 PM, Raymond Barbiero wrote:
> @hlinnaka if you prefer python, i'll do a rough pass in python

'sed' is perfectly fine too, I think we depend on 'sed' in other places 
already. Thanks for looking into this!

- Heikki

**Pull request closed without merging**
