### PR TITLE
Fix dump file diff due to space for partition tables during pg_upgrad…

### PR DESCRIPTION
**Pull request by paul-guo-**
…e test.

This patch modifies a bit the SQL format in UDF pg_get_partition_def().

### CODE REVIEW

**Comment by jchampio** [comment]
I think I share @danielgustafsson 's opinion that this may not be worth it. Maybe we should put removal of whitespace diffs on the wishlist? But for now, since we already have released versions of GPDB in the wild, it seems like we can't just drop them altogether.

**Comment by paul-guo-** [comment]
@jchampio This does not seem to affect upgrading on an existing old gpdb without the patch applied since the dump SQL syntax is correct with or without the patch. The purpose of the patch is: 1) Make the SQL format pretty. 2) For pg_upgrade test between two gpdb versions with this patch, we see no diff for this case and thus make testing easier (I'm not sure how we will handle those could-be-ignored diff in pg_upgrade test in the future but I suspect we will need to have rule setting to do ignoring).

**Comment by jchampio** [comment]
I'm -1 on this for the moment. We've been running our own end-to-end upgrade tests for a couple of months now, and those diffs (which diff the entirety of the database contents, not just the schema) make use of `--ignore-space-change` instead of `--ignore-all-space` to try to limit the damage that a false positive can do. This commit would add guaranteed work for us, because diff is going to flag the difference between `word )` and `word)`, but it's not clear to me that there's anyone benefiting.

If we weren't currently relying on `--ignore-space-change`, it'd be a +1 from me, but at the moment I don't think the cost/benefit makes sense. If, later, we find that we have to change back to `--ignore-all-space` for some other reason, or if we find a way to dump these tables in a way that doesn't rely on the old database, then it will definitely make sense to perform this cleanup.

**Comment by paul-guo-** [comment]
I'm gonna close this patch at this moment, given current gpdb code can handle this case via "diff -w" and thus the patch is not high prioritized but debatable. As mentioned, we could re-apply the change in the future if needed.

**Pull request closed without merging**
