### PR TITLE
[WIP] Avoid async hazard in backtrace(3) in WAL Receiver shutdown sequence

### PR DESCRIPTION
**Pull request by berlin-ab**
I created this PR on behalf of @melanieplageman and @d .

--

backtrace(3) is useful for debugging. For example, in GPDB
`send_message_to_server_log`, every log line that is ERROR, PANIC, or
FATAL is accompanied by a stack trace. In upstream Postgres, only a line
number is provided.
Most implementations of backtrace(3) though, aren't async-safe. This,
however, makes `elog` async-unsafe. And one signal handler that
calls `elog` is WalRcvShutdownHandler.

errstart calls backtrace(3)

backtrace(3) is async unsafe
- backtrace is useful for debugging -- yay dumping stack
- backtrace the first time it is called does stuff
- exercise for the reviewer: audit our signal handlers and see if we
are doing anything weird
- elog/ereport(FATAL) seem like they would always have this problem
- also didn't add a test because hard
- should we even do the backtrace when log level < error

Co-authored-by: Jesse Zhang <sbjesse@gmail.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ashwinstar** [comment]
`elog(FATAL)` is bad in signal handler PERIOD So, I am not sure there is any point making it little safer as is not going to fix the problem and deadlock can still be easily seen during exit() processing, so I am not in favor of adding more code which doesn't help and deviate us from upstream.

**Comment by Eulerizeit** [comment]
What is happening on Postgres HEAD? If this is unsafe with us it is unsafe there, we can at least figure out if there is solid reasoning.

**Comment by ashwinstar** [comment]
On Tue, Feb 26, 2019 at 9:44 PM Robert Eckhardt <notifications@github.com>
wrote:

> What is happening on Postgres HEAD? If this is unsafe with us it is unsafe
> there, we can at least figure out if there is solid reasoning.
>
Yes, it is unsafe on Postgres HEAD too and hence should be fixed.

Since exit() is not safe in signal handlers, seems clearly
WalRcvShutdownHandler() is performing invalid call. This issue is similar
to ones we reported earlier for quick_die() calling exit() which were fixed
by replacing it with _exit(). Thread for reference
https://www.postgresql.org/message-id/flat/CAOMx_OAuRUHiAuCg2YgicZLzPVv5d9_H4KrL_OFsFP%3DVPekigA%40mail.gmail.com
.

Seems the usage of EnableWalRcvImmediateExit(); is not at right point as
memory allocation is performed when its enabled at various points, exposing
window to cause this deadlock. Hence, we must fix the same.

ImmediateInterruptOK was removed from regular backends as part of commit
2505ce0be0b686c5a0a5141e9d080e7fdc35988a and previous commits
4fe384bd858671d40d311ca68cc9b80f4c683a3e and
6647248e3708843be93c7ca670cd219fe8e61026. Seems similar needs to be done
for walreceiver backend upstream and in GPDB.

>

**Comment by ashwinstar** [comment]
To close the loop here upstream fixed this issue by commit https://github.com/postgres/postgres/commit/a1a789eb5ac894b4ca4b7742f2dc2d9602116e46. I will try to cherry-pick that commit and see how it behaves in GPDB. It aligns with what we had discussed that elog(FATAL) should be removed from signal handler.

**Pull request closed without merging**
