### PR TITLE
Skip column acl check in gp_acquire_sample_rows

### PR DESCRIPTION
**Pull request by zhangh43**
Using 'select pg_catalog.gp_acquire_sample_rows(...)' instead of
'select * from pg_catalog.gp_acquire_sample_rows(...) as (...)'.
The old one requires USAGE privilege on each columns which is not
consistent with GPDB 5X.

The following SQL failed to pass acl check in master now:
revoke all on schema public from public;
create role gmuser1;
grant create on schema public to gmuser1;
create extension citext;
create table testid (id int , test citext);
alter table testid owner to gmuser1;
analyze testid;

Idea from Ashwin Agrawal <aagrawal@pivotal.io>
Idea from Taylor Vesely <tvesely@pivotal.io>

We already have analyze test cases, skip in this PR.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ashwinstar** [comment]
> We already have analyze test cases, skip in this PR.

Disagree with this statement, existing tests didn't expose this bug. So, we definitely need to add test for this PR for the issue its fixing. I had written small test for it, but it's sitting on work-station in office when I get to office can give to you or you should be able to easily write one (don't need citext for it). Can easily write test by creating type in schema and revoke the privileges. (Note: I didn't review the code change / fix)

**Comment by zhangh43** [comment]
> > We already have analyze test cases, skip in this PR.
> 
> Disagree with this statement, existing tests didn't expose this bug. So, we definitely need to add test for this PR for the issue its fixing. I had written small test for it, but it's sitting on work-station in office when I get to office can give to you or you should be able to easily write one (don't need citext for it). Can easily write test by creating type in schema and revoke the privileges. (Note: I didn't review the code change / fix)

@ashwinstar  Test case added. I create a new schema and also create citext extension(also type) under this schema. Others are similar to the case in the PR comment

**Comment by tvesely** [comment]
Parsing the record type as a cstring and then parsing the string seems kinda brittle. Instead would it be possible to create our tuple descriptor similar to how it is created in `ExecInitFunctionScan` and parsing the record directly?

In `ExecInitFunctionScan()` it takes the type information in a `RangeTableFunction` and parses it into a tuple descriptor using `BuildDescFromLists`. 

This is what a RangeTableFunction looks like:

```
RangeTblFunction [funccolcount=6 funcuserdata=0x0 funcparams=0x0]
	[funcexpr] 
		FuncExpr [funcid=6038 funcresulttype=2249 funcretset=true funcvariadic=false funcformat=COERCE_EXPLICIT_CALL funccollid=0 inputcollid=0 location=14 is_tablefunc=false]
			[args] 
				Const [consttype=26 constlen=4 constvalue=16476 constisnull=false constbyval=true]
				Const [consttype=23 constlen=4 constvalue=3 constisnull=false constbyval=true]
				Const [consttype=16 constlen=1 constvalue=0 constisnull=false constbyval=true]
	[funccolnames] 
		String ["total_rows"]
		String ["totaldeadrows"]
		String ["oversized_cols_bitmap"]
		String ["a"]
		String ["b"]
		String ["c"]
	[funccoltypes] OidList: [701, 701, 25, 23, 23, 23]
	[funccoltypmods] IntList: [4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295]
	[funccolcollations] OidList: [0, 0, 100, 0, 0, 0]
```

This is where we parse the information from the RangeTblFunction into a new TupleDescriptor:

https://github.com/greenplum-db/gpdb/blob/9dfa8ab7c8c18fa99d183a03b668751efb4ca653/src/backend/executor/nodeFunctionscan.c#L475-L487

We already have all of the information we need to build the tuple descriptor on the Master. Instead of splitting up a cstring, does it make sense to instead build a tuple descriptor from lists like above and parsing the record as a whole? Does that work for this use case, or does the fact we have the `RECORD` datatype in a `pg_result` complicate things somehow?

**Comment by tvesely** [comment]
It seems you were way ahead of me. I see that you are generating a tuple descriptor in much the same way I suggested above- I just missed it my first pass through the code. I dug around a bit and after trying to answer my own questions above, it lead me to implement this in about the same way you did. I can't think of much else we can do here. I did explore some alternative solutions, one of which was dispatching this query instead:

```
select * from pg_catalog.gp_acquire_sample_rows(...) as (total_rows float8, totaldeadrows float8, oversized_cols_bitmap text, table_record_type foo);
```
In the example above, foo is the type that is created as part of the table creation..
```
pivotal=# select * from pg_type where oid= 'foo'::regtype;
 typname | typnamespace | typowner | typlen | typbyval | typtype | typcategory | typispreferred | typisdefined | typdelim | typrelid | typelem | typarray | typinput  | typoutput  | typreceive  |   typsend   | typm
odin | typmodout | typanalyze | typalign | typstorage | typnotnull | typbasetype | typtypmod | typndims | typcollation | typdefaultbin | typdefault | typacl 
---------+--------------+----------+--------+----------+---------+-------------+----------------+--------------+----------+----------+---------+----------+-----------+------------+-------------+-------------+-----
-----+-----------+------------+----------+------------+------------+-------------+-----------+----------+--------------+---------------+------------+--------
 foo     |         2200 |       10 |     -1 | f        | c       | C           | f              | t            | ,        |    16476 |       0 |        0 | record_in | record_out | record_recv | record_send | -   
     | -         | -          | d        | x          | f          |           0 |        -1 |        0 |            0 |               |            | 
(1 row)
```
Doing so would prevent us from needing to write a function like `parse_record_to_string`, because we could directly call `record_in` with the type of `foo` and it should produce a tuple for us. Unfortunately, I'm not certain that the owner of the table foo will always have access to the type `foo`, and when we create a partition table we don't create the type for the child partitions. 

Also, nothing prevents a user from dropping a table's tuple type directly. That all creates even more complications.
```
pivotal=# select * from pg_type where oid='foo_1_prt_1'::regclass;
 typname | typnamespace | typowner | typlen | typbyval | typtype | typcategory | typispreferred | typisdefined | typdelim | typrelid | typelem | typarray | typinput | typoutput | typreceive | typsend | typmodin | 
typmodout | typanalyze | typalign | typstorage | typnotnull | typbasetype | typtypmod | typndims | typcollation | typdefaultbin | typdefault | typacl 
---------+--------------+----------+--------+----------+---------+-------------+----------------+--------------+----------+----------+---------+----------+----------+-----------+------------+---------+----------+-
----------+------------+----------+------------+------------+-------------+-----------+----------+--------------+---------------+------------+--------
(0 rows)
```
It seems strange to me that we haven't had to deal with an issue like this before now. @hlinnaka Does any function exist where we can input a `CString` representation of a `record` data type, and a tuple descriptor describing it, and get out `value` and `isnull` arrays? Everything I see right now operates on something that already has a `value` and `isnull` array of `CString`s. The `record_in` function requires an already existing type, so we had to reuse a bunch of code to perform the same operation with an anonymous tuple descriptor instead.

**Comment by zhangh43** [comment]
> In the example above, foo is the type that is created as part of the table creation..
> Doing so would prevent us from needing to write a function like `parse_record_to_string`, because we could directly call `record_in` with the type of `foo` and it should produce a tuple for us. Unfortunately, I'm not certain that the owner of the table foo will always have access to the type `foo`, and when we create a partition table we don't create the type for the child partitions.

Create a user-defined type for each table is too heavy. In fact, we could treat the whole function return result as a Record and use `record_in` to parse. But as I mentioned in the commit, this method would fail when checking NOT NULL constraint of the original table(i.e. the row only contains the summary information).

**Comment by zhangh43** [comment]
This PR is for 6X, open PR #9522  to fix it on master firstly.
So closed this PR now.

**Pull request closed without merging**
