### PR TITLE
Pipeline update to add missing pulse input

### PR DESCRIPTION
**Pull request by Chibin**
* pipelines were missing the new input from pulse trigger
  gpdb_src_behave_tarball. This is an update to fix that issue.

* Restructured/refactored the pipeline for better visibility for each
  job

### CODE REVIEW

**Comment by Chibin** [comment]
@cjcjameson @tom-meyer Can you guys please take a look? Thanks.

**Comment by cjcjameson** [comment]
Yeah, what Larry said, good use of YAML. For next time, it would have been easier for me to review if there was one commit for the refactor, and another for the fix.

Is there a pipeline which you've `fly set-pipeline`d up somewhere to see / verify it's a fix?

**Comment by Chibin** [comment]
> Is there a pipeline which you've fly set-pipelined up somewhere to see / verify it's a fix?

https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/gpdb-master-ace
TINC tests specifically for Catalog and Storage are green.

**Comment by Chibin** [comment]
Thanks for the review.

**Pull request merged**
