### PR TITLE
6X Backport: Extend Travis pipeline to a build matrix

### PR DESCRIPTION
**Pull request by danielgustafsson**
Backport from master to extend the coverage of backported PRs.

This extends our coverage by defining a build matrix in the Travis CI pipeline rather than just having a single job. The idea is to build PRs against combinations of common platforms and compilers in order to catch compiler errors and warnings early. The gist of the changes to the previous CI configuration is:

  - static configuration is replaced by per build config in a matrix
  - ccache is removed to avoid caching issues
  - macOS is again built on
  - the version printing is more selective to only print versions
    for binaries built in every job
  - notifications are removed to minimize spamming
  - builds with various un-orthodox flags are supported
  - build silently to make output more manageable
  - parts of the regression tests are executed via new installcheck
    target in src/test/regress

Future tasks is to extend this to more combinations and also to build clientside tooling on Windows as well as extended the test coverage to include more parts of ICW.

### CODE REVIEW

**Comment by asimrp** [comment]
Looks like we have some bugs left in unit-tests.  Once those are ironed out, big +1 to back porting this patch.  We currently have no validation on 6X because PR pipeline only runs for PRs against master.

**Comment by danielgustafsson** [comment]
I've included all the unittest fixing commits in this PR (more or less straight backports) as they are a pre-requisite for the Travis pipeline at all working.

**Comment by asimrp** [comment]
And Travis has blessed the PR.  I would be happy to commit this, as your leave has already started @danielgustafsson.

**Comment by Eulerizeit** [comment]
@asimrp if you want to pick this up it would be awesome.

**Comment by asimrp** [comment]
Merged to 6X_STABLE a96c73439d6a92bc271f848700f9b79cae9e4e18..4e524fcb7aff14ad9dde2aa9cdae936321f3cd21

**Pull request closed without merging**
