### PR TITLE
gp_system views: Remove \n from sed replacement

### PR DESCRIPTION
**Pull request by soumyadeep2007**
\n doesn't translate to a newline on many platforms in sed's
replacement. Remove it, the generated file looks more compact without
them anyway.

Bug reported on: MacOS Catalina 10.15.7

PS: It's not straight-forward to escape them in a platform-independent
way.

Co-authored-by: Asim R Praveen <asimrp@lavabit.com>

Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/sed_fix_gp_views

### CODE REVIEW

**Comment by ashwinstar** [comment]
In general change looks good.
Though would be good if you can post the before and after version this PR (lazy to download/build and see what the new outcome looks like compared to old).

**Comment by soumyadeep2007** [comment]
[system_views_gp_after.sql.txt](https://github.com/greenplum-db/gpdb/files/12232324/system_views_gp_after.sql.txt)
[system_views_gp_before.sql.txt](https://github.com/greenplum-db/gpdb/files/12232428/system_views_gp_before.sql.txt)

**Review by huansong — APPROVED** [review]
LGTM!

**Comment by ashwinstar** [comment]
Ahh its definitely much harder to read the newer version compared to before. Though seems we have no choice for now as no easy way to get better formatting. Fine for now for correctness reasons to absorb the change. In longer run we can evaluate possibilities to help the eye. :+1:

**Comment by soumyadeep2007** [comment]
> Ahh its definitely much harder to read the newer version compared to before. Though seems we have no choice for now as no easy way to get better formatting. Fine for now for correctness reasons to absorb the change. In longer run we can evaluate possibilities to help the eye. +1

Looks okay in a wide monitor though! But yeah I get your sentiment, we want to be as friendly as possible to all dev envs.

**Pull request merged**
