### PR TITLE
Refactoring hash join code, to reduce our diff vs. upstream

### PR DESCRIPTION
**Pull request by hlinnaka**

### CODE REVIEW

**Comment by Eulerizeit** [comment]
@hsyuan @dhanashreek89 would one of you please check this out. We'd like to get this committed to master, before we spend much time fixing the conflicts on the hash join code. It should make it easier

**Comment by hsyuan** [comment]
Will do

**Comment by vraghavan78** [comment]
@hlinnaka, talked to @Eulerizeit we are looking at two flakey test issues that we want to fix so the CI is more stable. We will get to this PR after that.

**Comment by hlinnaka** [comment]
Rebased. @hsyuan, @vraghavan78, when do you think you'll get to reviewing this? This is one of the few blockers left, before we can merge the rest of 8.4 into master.

**Comment by hlinnaka** [comment]
Thanks, pushed!

**Pull request merged**
