### PR TITLE
Cleanup cdbhash usage

### PR DESCRIPTION
**Pull request by hlinnaka**
Remove unnecessary use of GPDB's cdbhash functions. This is the first step towards replacing cdbhash with the regular PostgreSQL hash functions, as discussed in https://github.com/greenplum-db/gpdb/pull/5426#issuecomment-412493468.

The commits in this PR can be divided in roughly three parts:

1. In analyzeutils.c, use PostgreSQL hash functions instead of GPDB's "cdbhash" functions, in the code that merges leaf partition statistics. The "cdbhash" functions are used when computing distribution keys, but this code has to do with partitioning, not distribution across segments, so it's better to use the upstream functions that work with any datatype. 

While we're at it, clean up the formatting and #includes in analyzeutils.c, making it nicer to work with.

2. In predtest.c, use PostgreSQL hash functions instead of GPDB's "cdbhash" functions. The corresponding "match" function actually compared the raw bytes, instead of computing a datatype-aware hash, so we can hash the raw bytes in the hash function, too.

While we're at it, move the "PossibleValues" code to a separate source file, to keep GPDB separate from upstream code as much as possible. Clean up formatting, and refactor the code that we need to change anyway, for readability.

3. Remove hashDatum() and hashDatumNull() functions from cdbhash.c. They are no longer used outside cdbhash.c, so we can inline them into the cdbhash() and cdbhashnull() functions.

### CODE REVIEW

**Comment by Eulerizeit** [comment]
@hlinnaka for the first point. If users have a table that is distributed and partitioned already, does this cause conflicts with the existing partitions?

**Comment by hlinnaka** [comment]
On 29/10/2018 14:55, Robert Eckhardt wrote:
> @hlinnaka for the first point. If users have a table that is distributed and partitioned already, does this cause conflicts with the existing partitions?

Not sure what exactly you mean. But no, this doesn't affect existing 
users, and should have no user-visible effect, except that the 
leaf-statistics merging method now works also for datatypes that are not 
"gpdb hashable".

- Heikki

**Comment by hlinnaka** [comment]
Turns out that wasn't 100% correct: the money and varbit datatypes doesn't have a hash opclass in the upstream, so this PR loses the capability of merging leaf stats for money datatype. I think that's acceptable: the money datatype is problematic in many ways, and I would not recommend anyone to use it, anyway. Same with "varbit". But if that becomes a problem, we could add hash opclasses for them. (Or a user can even fairly easily create it themselves, if needed.)

That became apparent in the 'incremental_analyze' regression test failure. In addition to that, the failure shows a second class of differences: for some cases where a table has an equal number of some values, but not all of them fit in the MCV, the code now sometimes chooses a different value to include in the MCV. So that's behaviour where it could've gone either way before, since the values have the same frequency, and this patch changes which one is chosen. That seems harmless.

**Comment by kainwen** [comment]
Thanks @hlinnaka 

I notice there is an issue on performance: https://github.com/greenplum-db/gpdb/issues/5961

If we solve that issue in the PR(If this PR backport to 5X)? or open another PR to solve this issue(if this PR does not backport to 5X)?

**Comment by hlinnaka** [comment]
> Thanks @hlinnaka
> 
> I notice there is an issue on performance: #5961
> 
> If we solve that issue in the PR(If this PR backport to 5X)? or open another PR to solve this issue(if this PR does not backport to 5X)?

Ah yes, this PR should address the performance issue, too. I'm not sure what the best course of action for 5X would be. This patch isn't too large, so backporting is one option.

**Comment by hlinnaka** [comment]
> > Thanks @hlinnaka
> > I notice there is an issue on performance: #5961
> > If we solve that issue in the PR(If this PR backport to 5X)? or open another PR to solve this issue(if this PR does not backport to 5X)?
> 
> Ah yes, this PR should address the performance issue, too. I'm not sure what the best course of action for 5X would be. This patch isn't too large, so backporting is one option.

No wait, this PR doesn't address that performance issue yet. I was thinking ahead of myself: I've been working on an add-on patch to change the cdbhash functions, so that the type OIDs are passed as argument to the makeCdbHash(), which eliminates teh typeIs*() calls from the hot path, in cdbhash().  But this PR doesn't do that yet. So, never mind!

**Comment by hlinnaka** [comment]
Pushed, thanks for the review!

**Comment by Eulerizeit** [comment]
@hlinnaka you mentioned a performance improvement above that will close out an issue. Is that coming?

**Comment by hlinnaka** [comment]
> @hlinnaka you mentioned a performance improvement above that will close out an issue. Is that coming?

Yeah, see https://github.com/greenplum-db/gpdb/pull/6123.

**Pull request merged**
