### PR TITLE
Plr

### PR DESCRIPTION
**Pull request by davecramer**
Initial commit of plr, this is a WIP. It does not compile yet

### CODE REVIEW

**Comment by ivannovick** [comment]
@davecramer which version did you pull of PLR?  Also do we have any automated tests for PLR?

**Comment by hlinnaka** [comment]
PL/R is GPL-licensed...

**Comment by davecramer** [comment]
Which I guess explains why it wasn't added in the first place

Any ideas on how to deal with that ?

Can we have a separately licensed repo just for PL/R? The user would be
responsible for pulling it into the source code and building it themselves

Dave Cramer

**Comment by davecramer** [comment]
Ivan,

How do we deal with GPL code. Clearly it can't go into the github repo as
that is all Apache licensed, and the licenses are incompatible

Dave Cramer

**Comment by hlinnaka** [comment]
We're clearly not going to commit this patch because of the license issue, so I'll close this PR. Discussion on what we want to do instead can continue on the mailing list..

**Pull request closed without merging**
