### PR TITLE
Remove function owner functionality from Tinc

### PR DESCRIPTION
**Pull request by danielgustafsson**
In the past there was functionality to decorate a stacktrace with the developer in charge of the separate functions. This is not in use anymore and it's not something we want either.

Note: I haven't tested optimizer functional with this since I didn't want to spend too much time before getting some level of buy-in from those knowing this suite better. @vraghavan78 @d is this anything you want/use or can it go? It seems a leftover from earlier times that doesnt fit in the OSS workflow.

### CODE REVIEW

**Comment by pivotal-mike** [comment]
@oarap can someone from QO please take a quick look?  The owners list is severely outdated as none of the of folks listed are working on ORCA any longer

**Comment by hsyuan** [comment]
+1, I don't think anyone of us use it.

**Comment by hsyuan** [comment]
@danielgustafsson I think this PR is good to go.

**Comment by danielgustafsson** [comment]
I just haven't had the time to run the optimizer functional tests to ensure that the Python parts are correct. Once that's done it should be ready to go in.

**Comment by d** [comment]
@danielgustafsson will you need help on getting the optimizer functional suite up and running? We can help get you started

**Comment by danielgustafsson** [comment]
@d if you can run optimizer functional and see if this breaks it that would be much appreciated, I've just been too bogged down with other patches to get around to it.

**Comment by danielgustafsson** [comment]
Pushed to master after running Tinc locally green, will hold off on closing until I see a green CI run.

**Pull request closed without merging**
