### PR TITLE
Change PORT_BASE semantics for demo cluster

### PR DESCRIPTION
**Pull request by ashwinstar**
Previously, three different environment variables were required to
modify ports to be used by demo cluster. I think that's unnecessary
and such flexibility comes at greater cost for developers, instead
better to have only one environment variable to help provide the
flexibility. Hence, removing MASTER_PORT and STANDBY_PORT
variables. Now, only PORT_BASE is used. This becomes the starting port
number and master port number. All other required port numbers for
demo cluster are sequential to it, including standby port, followed by
primaries and mirrors.

Also, very often need to create demo cluster across different GPDB
versions. So, would be helpful to have PORT_BASE default set to not
conflict across different GPDB versions. Hence, using 7000 as this is
GPDB7 branch. For GPDB6 we can have it start at 6000 and GPDB5 at
5000. I think that makes it easy to remember as well and shorter to
type as well compared to 5 digits previously used :-)

What do team think about this? (I know some folks, including myself, may have memorized old numbers and will have to purge our mind cache with this change, but seem will help in future)

### CODE REVIEW

**Comment by berlin-ab** [comment]
YES! I love it.

I've always thought it was weird that the demo cluster allows these to be configured separately.

Also, I currently have my clusters set up to start on 5000, 6000, and 7000 - so nothing new to remember for me.

**Comment by frankgh** [comment]
@ashwinstar this is great, but I think there's demo cluster documentation, pointing to PGPORT 15432, that will need to be changed.

**Comment by ashwinstar** [comment]
Thanks, glad this is helpful to folks.

Yes, `PGPORT` is hardcoded at quite few places and will have to loose those out. Wish to start small to get the feedback, I will incrementally fix all those instances.

**Comment by asimrp** [comment]
Seriously, love it!  Especially the idea of back porting this such that PORT_BASE is adjusted according to version number.

**Comment by jchampio** [comment]
Great idea!

**Comment by pf-qiu** [comment]
We have test script that call create cluster of multiple versions of gpdb.
The problem is if we set PORT_BASE before make cluster, it works for latest master. But it won't work for gpdb6 GA and gpdb5 because that's start point of segments.
I agree with the idea to use a single variable for port setup, is it possible to introduce a different environment variable like CLUSTER_PORT_BASE and derive PORT_BASE from that? This way we can set the new variable and it will have no effect on old make cluster script.

**Comment by ashwinstar** [comment]
The plan is to back-port this change to at least 6X_STABLE and if works out fine to 5X_STABLE as well. So, it won't be issue for too long.

Logically, you can easily modify the variable setting based on what version is being installed? Seems shouldn't be that hard.

I don't have problem with introducing new variable but `CLUSTER_PORT_BASE` is too long to type, so something smaller would be preferred. Also, if introducing I would prefer to completely replace `PORT_BASE` with new one instead of one more wrapper on top of it. There are already too many variables and we should try to cut them down as much as possible.

**Pull request merged**
