### PR TITLE
Create a public dockerfile for compiling greenplum on ubuntu

### PR DESCRIPTION
**Pull request by lavjain**
The resulting dockerfile is 1.1GB:
```
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
pivotaldata/gpdb-dev             ubuntu16            48d804e0efef        About an hour ago   1.1GB
```
Here is an example of how to use this dockefile for development:
```
docker build -t pivotaldata/gpdb-dev:ubuntu16 .
docker run --rm -it   -p 5432:5432  -w /home/gpadmin/workspace   -v ~/workspace/gpdb:/home/gpadmin/workspace/gpdb   -v   pivotaldata/gpdb-dev:ubuntu16 /bin/bash

# Once inside the docker container
su - gpadmin
cd /home/gpadmin/workspace/gpdb
make clean
./configure \
  --enable-mapreduce \
  --enable-orafce \
  --with-gssapi \
  --with-perl \
  --with-libxml \
  --with-python \
  --enable-debug-extensions \
  --with-libraries=/home/gpadmin/workspace/gpdb/depends/build/lib \
  --with-includes=/home/gpadmin/workspace/gpdb/depends/build/include \
  --prefix=/usr/local/greenplum-db-devel
make -j8
```

### CODE REVIEW

**Comment by kmacoskey** [comment]
There are already three other distinct implementations of how to compile Greenplum on Ubuntu that exist already on this branch:
https://github.com/greenplum-db/gpdb/blob/master/concourse/scripts/compile_gpdb_open_source_ubuntu.bash#L28
https://github.com/greenplum-db/gpdb/blob/master/concourse/scripts/compile_gpdb.bash#L59
https://github.com/greenplum-db/gpdb/blob/master/concourse/pr_pipeline/runner.bash#L87

Which one is the canonical way we should be building Greenplum for Ubuntu for either OSS or not OSS?

There are also three other distinct Ubuntu Docker files for Greenplum in use on the branch as well:
https://github.com/greenplum-db/gpdb/blob/master/src/tools/docker/ubuntu-16.04/Dockerfile
https://github.com/greenplum-db/gpdb/blob/master/src/tools/docker/ubuntu-16.04-persistent/Dockerfile
https://github.com/greenplum-db/gpdb/blob/master/concourse/pr_pipeline/docker/Dockerfile

Which one is the canonical environment we should be using for building and testing Greenplum on Ubuntu for ether OSS or not OSS?

Is Greenplum on this branch intended to support Ubuntu 16.04? or only Ubuntu 18.04?

**Comment by lavjain** [comment]
This dockerfile is for ubuntu 16 only (hence it is located under src/tools/docker/ubuntu16/Dockerfile).

The other images on this branch use ubuntu package to install GPDB. This dockerfile will allow you to compile your own GPDB and do development on it.

**Comment by kmacoskey** [comment]
What are the two other Ubuntu 16 Docker files for?
`src/tools/docker/ubuntu-16.04/Dockerfile`
`src/tools/docker/ubuntu-16.04-persistent/Dockerfile`

This PR would result in having both a `ubuntu-16.04` and `ubuntu16` directory that both contain Ubuntu 16.04 Dockerfiles.

**Comment by kmacoskey** [comment]
This would result in two directories at the same level:
`src/tools/docker/ubuntu-16.04`
`src/tools/docker/ubuntu16`

This may be a bit confusing.

**Comment by kmacoskey** [comment]
The other Ubuntu 16.04 image is actually installing Greenplum 5 from PPA as well:
https://github.com/greenplum-db/gpdb/blob/master/src/tools/docker/ubuntu-16.04/Dockerfile#L15
There is no Greenplum 6 OSS release in PPA yet.

**Comment by lavjain** [comment]
@kmacoskey For the other ubuntu image, the directory should be renamed to ubuntu16_run. Let me change the directory for this image to ubuntu16_build

**Comment by bradfordboyle** [comment]
Echoing some of @kmacoskey's comments: As we start building more open source Docker images for Greenplum, I think that we should consolidate the location of the Dockerfiles. This will make it easier to apply changes across the different containers.

Can we consolidate all our Dockerfiles in `docker/`?

**Comment by berlin-ab** [comment]
The Dockerfile under `concourse/pr_pipeline/docker/` is there for good reason, and it should stay there.

It should be obvious that the Dockerfile under that directory has only one purpose - to serve that pipeline. If it were moved into centralized location for all dockerfiles, it would lose that cohesion with its purpose and we may be tempted to use that dockerfile for other purposes.

**Comment by lavjain** [comment]
The docker file under `concourse/pr_pipeline/docker/` caters to ubuntu18. For right now, it can stay separate.

**Comment by oliverralbertini** [comment]
LGTM

🚢

**Pull request merged**
