### PR TITLE
Move Docker and Vagrant to src/tools

### PR DESCRIPTION
**Pull request by andreasscherbaum**
Update README

Per previous discussion on gpdb-dev list.

### CODE REVIEW

**Comment by ashwinstar** [comment]
Looks fine.

**Comment by pivotal-issuemaster** [comment]
@andreasscherbaum Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1206) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by danielgustafsson** [comment]
The `config.vm.synced_folder` setting in the Vagrant files would need to be updated to reflect the new directory depth don't they?

**Comment by amilkh** [comment]
+1
Note that `vagrant/` seems to have been removed from the repo already.

Also note there were some recent Docker changes in a Pivotal-internal repo:
https://github.com/greenplum-db/gpdb4/pull/163

**Comment by andreasscherbaum** [comment]
@danielgustafsson Updated the path names.

@davecramer Can you please check if the path names for synced_folder make sense? I only had to change it for Debian, CentOS is built different.

@amilkh Can you backport this, once it is merged?

**Comment by ascherbaum-pivotal** [comment]
For the record, this is my PR, using my personal account. My CLA is on file, just the bot does not agree.

**Pull request merged**
