### PR TITLE
added job to identify release candidates

### PR DESCRIPTION
**Pull request by pivotal-mike**
Added a single get job that triggers for any commit which passes _all_ the tests (including the nightly timer).  This is used to help identify possible commits to tag for release.

Because of the changes to the pipeline shape I've also introduced groups to keep the pipeline readable

### CODE REVIEW

**Comment by cjcjameson** [comment]
Great `job`, but -1 on the groups:

- Concourse should have a feature that creates an "all" group by default but it doesn't. If it did, I wouldn't be -1.
- if I add a new job to the pipeline, I need to remember to add it to the "all" group. If I don't, I end up spending time trying to figure out why my new job doesn't appear on the screen: frustrating!
- putting this new job in the same group (or unified by the lack of groups) with the rest of the pipeline actually has very strong meaning! If ever we were to automate "promotion" of commits, then this new job would be an easy refactor from being informational to actually doing the promotion. It plays very well with the pipeline metaphor. It's well worth the additional column and lines on the UI.

To the second point above, at some point people will forget to loop their job in when writing a new job (even without the groups thing). Can we put an automated check in place? I have an idea... Hard to describe and just on my phone right now.

**Comment by pivotal-mike** [comment]
@cjcjameson While I get what you're saying a couple of things:

1. it's not just a matter of extra lines, adding this job re-ordered the jobs and it becomes much less clear which jobs are part of ICW vs Pulse etc...
2. I don't buy they "people will forget the "all" group - you should at least be testing any pipeline changes and when you fail to see the new job in your test pipeline then it should be a fairly strong reminder that you forgot to do this.

**Comment by kmacoskey** [comment]
+1  to merging with the groups

It is easy to forget to to add to the `all` group (I do it all the time), but it's always been easy to notice and remedy when I click refresh and don't see my new job in the UI.

**Comment by cjcjameson** [comment]
Also linking to #1795 and #1797 as prior work that didn't necessarily go anywhere

**Comment by cjcjameson** [comment]
WIP to make Mike's point 2 above highlighted: https://github.com/cjcjameson/gpdb/tree/concourse_pipeline_alert_new_release_jobs

**Pull request merged**
