### PR TITLE
use-existing flag for pg_regress

### PR DESCRIPTION
**Pull request by bhuvnesh2703**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`

Porting the use-existing flag related code from master to 5X_STABLE. It was introduced as part of efc16ea520679d713d98a2c7bf1453c4ff7b91ec, so extracted only the relevant part for pg_regress.
It is a useful flag, and can save time recreating the database objects required for testing queries.

### CODE REVIEW

**Comment by bhuvnesh2703** [comment]
@ashwinstar Yes, i did. I originally coded it on 5X, and in the process of porting to master, realized it's there in the master.

**Comment by paul-guo-** [comment]
This seems to be one that could be returned to the pg community.

**Comment by danielgustafsson** [comment]
> This seems to be one that could be returned to the pg community.

Since this is a backport of functionality from PostgreSQL, which part do you see us contributing?

**Comment by paul-guo-** [comment]
@danielgustafsson Oops. I thought this was code added in gpdb only, and I just noticed that this is a backport patch (from gpdb master to gp5).

**Pull request merged**
