### PR TITLE
Start standby master in create-demo-cluster when WITH_MIRRORS = true.

### PR DESCRIPTION
**Pull request by dsharp-pivotal**
Author: Max Yang <myang@pivotal.io>
Author: Xiaoran Wang <xiwang@pivotal.io>
(cherry picked from commit 0c7f12814bbff95885c7c5b2c93621138c35bafc)
Excluded changes to gpsegwalrep.py since they don't apply.

### CODE REVIEW

**Comment by macroyuyang** [comment]
@dsharp-pivotal Thanks for porting this to 5x stable. LGTM after concourse pass.

**Comment by xinzweb** [comment]
@ashwinstar I worked with @dsharp-pivotal to get the test removed, since it's covering the segwalrep, and we are actually plan to remove the `--enable-segwalrep` in 5X. Would you please take a quick look? Thanks a lot.

**Comment by ashwinstar** [comment]
LG from PR pipeline perspective but we need to run full pipeline. I do remember few fixes required for `Storage` job relating to this change, which maybe required to be cherry-picked.

**Comment by dsharp-pivotal** [comment]
Only the "storage" concourse job is now failing, in the "storage_uao_transactionmanagement" task:

```
======================================================================
FAIL: CrashRecovery_2PC.test_master_panic_after_phase1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/build/2a3fb5cb/gpdb_src/src/test/tinc/tincrepo/mpp/gpdb/tests/storage/transaction_management/crashrecovery/test_crashrecovery.py", line 89, in test_master_panic_after_phase1
    assert len(gparray.getHostList()) == 1, "cannot run on multi-node"
AssertionError: cannot run on multi-node
```

Cherry-picked [another commit](https://github.com/greenplum-db/gpdb/commit/6554324b18046f73fb2e61fd9f64179937f4afb5) to hopefully fix it.

**Comment by dsharp-pivotal** [comment]
Now that Concourse is back up to full strength, I ran the pipeline again with the fix for the "storage" test. Looks like a green pipeline. Anybody want to take another look before I merge?

**Pull request merged**
