### PR TITLE
Reverted change on condition for ReleaseTupleDesc.

### PR DESCRIPTION
**Pull request by gcaragea**
This reverts to the upstream version of this function. 

POSTGRES VERSION: 
```
#define ReleaseTupleDesc(tupdesc) \
	do { \
		if ((tupdesc)->tdrefcount >= 0) \
			DecrTupleDescRefCount(tupdesc); \
	} while (0)
```

GPDB VERSION: 
```
#define ReleaseTupleDesc(tupdesc) \
	do { \
		if ((tupdesc)->tdrefcount > 0) \
			DecrTupleDescRefCount(tupdesc); \
	} while (0)
```

The change from ```>= 0``` to ```>0``` was made in GPDB based on code inspection, but the GPDB behavior is not desirable. The change will mask bugs where you call ReleaseTupleDesc on a tuple that's refcounted, but whose refcount has already reached zero. Without this change, such a bug would fire the assertion in DecrTupleDescRefCount():
```
void
DecrTupleDescRefCount(TupleDesc tupdesc)
{
	Assert(tupdesc->tdrefcount > 0);

	ResourceOwnerForgetTupleDesc(CurrentResourceOwner, tupdesc);
	if (--tupdesc->tdrefcount == 0)
		FreeTupleDesc(tupdesc);
}
```

The assertion gives you a better chance to notice it during development.

### CODE REVIEW

**Comment by armenatzoglou** [comment]
LGTM

**Comment by gcaragea** [comment]
@hlinnaka Can you please take a look, since you caught this change in the first place? 

Thanks.

**Comment by hlinnaka** [comment]
The patch that introduced this change also added a unit test as src/backend/access/common/test/tupdesc_test.c. That probably should be removed/fixed too.

**Comment by hlinnaka** [comment]
Other than that, looks good to me.

**Comment by gcaragea** [comment]
On Tue, Apr 5, 2016 at 6:38 AM, Heikki Linnakangas <notifications@github.com
> wrote:

> The patch that introduced this change also added a unit test as
> src/backend/access/common/test/tupdesc_test.c. That probably should be
> removed/fixed too.
>

Thanks, good catch Heikki! I should have run the unit tests before starting
the PR, that would have caught it.. .I'll remove the unit test as well.

**Comment by gcaragea** [comment]
Pushed to master.

**Pull request closed without merging**
