### PR TITLE
Dispatch transaction snapshot in CdbDispatchSetCommand()

### PR DESCRIPTION
**Pull request by adam8157**
CdbDispatchSetCommand() dispatches SET commands to idle segments, which
could not see the changes from a transaction with isolation levels
higher than or equal to repeatable read.

To fix that, dispatch the transaction snapshot in this case and set it
on the idle segments.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change

### CODE REVIEW

**Comment by adam8157** [comment]
My theory is the idle segments hadn't got the chance to set the correct transaction snapshot, with isolation levels
higher than or equal to repeatable read.

Is it? If so, is there a more decent fix?

**Comment by zhangh43** [comment]
For Repeatable read, we just generate the snapshot once, and later call of `GetTransactionSnapshot` will return CurrentSnapshot directly.
So in the query below
```
BEGIN ISOLATION LEVEL REPEATABLE READ;
CMD1: Query creates two gangs
CMD2: SET GUC 
```
CMD1 will create the distributed snapshot on QD and dispatch them the Gang1 and Gang2.
Since query is not committed, both QD and QEs in Gang1 and Gang2 should not call `AtEOXact_Snapshot` to free the `CurrentSnapshot`, right? If so, the CMD2 will dispatch SET command to all the gangs and reuse the `CurrentSnapshot` in CMD1. If `CdbDispatchSetCommand` dispatch with DF_WITH_SNAPSHOT flag, the snapshot on QD will be dispatched all the QEs, but note that we are in REPEATABLE READ level, so the snapshot on QD doesn't change at all, so dispatch with DF_NONE should work as well. I think there may exist another error(or behavior?), for example the QD call `AtEOXact_Snapshot` to free the `CurrentSnapshot`. We need to check it.

**Comment by zhangh43** [comment]
> CMD1 will create the distributed snapshot on QD and dispatch them the Gang1 and Gang2.
> Since query is not committed, both QD and QEs in Gang1 and Gang2 should not call `AtEOXact_Snapshot` to free the `CurrentSnapshot`, right? 

The above statement is not correct. The writer gang will stay in TRANS_INPROGRESS state, but reader gangs will just call the transaction commit, since reader gangs do not need to handle transaction related staff.  As a side effect, all the states including all the snapshots will also be cleared by `AtEOXact_Snapshot()` 

So the original issue is triggered when `SET ROLE guc_gp_test_role;` to idle gangs. The `check_role` hook will access `pg_auth` table, but failed to get the latest role inserted by the same transaction. Here we use the `CatalogSnapshot` to access the catalog table `pg_auth`. Note that CatalogSnapshot is fetched using `GetNonHistoricCatalogSnapshot(relid, DTX_CONTEXT_LOCAL_ONLY)` whose Dtxcontext is DTX_CONTEXT_LOCAL_ONLY, So it's still not clear to me why enable "DF_WITH_SNAPSHOT" works.

**Comment by zhangh43** [comment]
I try to find the root cause of why idle reader gangs can not see the new created row. Here are some findings
1. READ committed level also has this issue
```
set gp_vmem_idle_resource_timeout to 0;
select * from a, a b; -- create two gangs
begin;
CREATE ROLE guc_gp_test_role;
SET ROLE guc_gp_test_role; -- error when check_role
```
2. The error happens at idle reader gang, the check hook of SET ROLE(check_role) will search in syscache(AUTHNAME) to find whether guc_gp_test_role exists. In gpdb master, the syscache doesn't know this role and will refer to pg_authid catalog table and using CatalogSnapshot. During `HeapTupleSatisfiesMVCC` of tuple in catalog table, since the tuple is not committed, is cannot be visible using snapshot. But we know that this tuple is inserted by ourselves, so the write gang  could see the tuple xmin==current xid. As a result write gang could see this tuple ("guc_gp_test_role").
But for reader gang, when its  DistributedTransactionContext == DTX_CONTEXT_QE_READER, it will use the write gang's xid and could also see this tuple. But this is a catalog table and CatalogSnapshot is created with DTX_CONTEXT_LOCAL_ONLY. As a result, reader gang's xid is zero and it failed to see tuple ("guc_gp_test_role")

This fix in this PR somehow enable the syscache(AUTHNAME) to find the tuple("guc_gp_test_role"), so the real catalog table search is skipped. This needs more spike on it.

**Comment by zhangh43** [comment]
Updated the PR.
The root cause is that CatalogSnapshot previously uses DTX_CONTEXT_LOCAL_ONLY. As a result, the idle reader gang's local transaction id would be zero and it would see inconsistent tuples in catalog table compared with writer gangs.
The first commit happens to fix this issue by setting the reader gang's dtx to DTX_CONTEXT_QE_READER by `GetTransactionSnapshot` which is not used by SET GUC command in fact.

**Comment by adam8157** [comment]
#10456

**Pull request closed without merging**
