### PR TITLE
Making optimizer_metadata_caching GUC public

### PR DESCRIPTION
**Pull request by armenatzoglou**
This PR makes the optimizer_metadata_caching GUC public.

### CODE REVIEW

**Comment by hsyuan** [comment]
LGTM.

**Comment by gcaragea** [comment]
LGTM

**Comment by hlinnaka** [comment]
Is "DEVELOPER_OPTIONS" category still appropriate for this?

**Comment by atris** [comment]
+1

**Comment by armenatzoglou** [comment]
@hlinnaka Good catch, thanks a lot! I changed it to "QUERY_TUNING_METHOD".

**Comment by armenatzoglou** [comment]
Pushed to master. Thank you a lot for the review.

**Pull request closed without merging**
