### PR TITLE
6X Backport: Allow cluster to start when standby host is down

### PR DESCRIPTION
**Pull request by jmcatamney**
Previously, gpstart could not start the cluster if a standby master host was configured but currently down.  In order to check whether the standby was supposed to be the acting master (and prevent the master from being started if that was the case), gpstart needed to access the standby host to retrieve the TimeLineID of the standby, and if the standby host was down the master would not start.

This commit modifies gpstart to assume that the master host is the acting master if the standby is unreachable, so that it never gets into a state where neither the master nor the standby can be started.

This PR is a backport of #9526; it was a clean cherry-pick, no modifications aside from the typo fix.

### CODE REVIEW

**Comment by jchampio** [comment]
For docs: what is the expected behavior change from a user perspective after this lands in 6X?

**Comment by kalensk** [comment]
@litzell @mkiyama 

For 6X the following behavior has changed from a user perspective. When starting the cluster and the standby is unreachable, we will log and prompt the user with the following lines:

> "Standby host is unreachable, cannot determine whether the standby is currently acting as the master. Received error: %s"
> "Continue only if you are certain that the standby is not acting as the master."

When this situation occurs in non-interactive mode (ie: when gpstart is started with "-a"), then this prompt will not be given. The cluster will not be started for safety reasons, and an additional log line will be recorded: 

> "Non interactive mode detected. Not starting the cluster. Start the cluster in interactive mode."

**Comment by mkiyama** [comment]
@jmcatamney @kalensk 
With gpstart -a  and a successful start this is the last line of the command output.
`[INFO]:-Database successfully started`

If the standby host is not available, will these be the last lines displayed on the command line? 
`[ERROR]:-Standby host is unreachable, cannot determine whether the standby is currently acting as the master. Received error: %s"`
`[ERROR]:-Non interactive mode detected. Not starting the cluster. Start the cluster in interactive mode.`

thanks

**Comment by kalensk** [comment]
> @jmcatamney @kalensk
> With gpstart -a and a successful start this is the last line of the command output.
> `[INFO]:-Database successfully started`
> 
> If the standby host is not available, will these be the last lines displayed on the command line?
> `[ERROR]:-Standby host is unreachable, cannot determine whether the standby is currently acting as the master. Received error: %s"`
> `[ERROR]:-Non interactive mode detected. Not starting the cluster. Start the cluster in interactive mode.`
> 
> thanks

Yes, that is correct for gpstart -a.

**Pull request merged**
