### PR TITLE
Add missing type conversion functions of PL/Python

### PR DESCRIPTION
**Pull request by HaozhouWang**
PL/Python already has different type conversion functions to
convert GPDB datum to Python object. However, the conversion
functions from Python object to GPDB datum only has Boolean, Bytea
and String functions. This commit add rest of Integer and Float related datatype
conversion functions,and can increase the performance of
data conversion greatly especially when returning a large array.

We prepared a simple UDF to test this, where num is the number of elements in returned array.

```
CREATE OR REPLACE FUNCTION pyoutfloat8(num int) RETURNS float8[] AS $$
return [x/3.0 for x in range(num)]
$$ LANGUAGE plpythonu;
```
The test results are (number of elements in array vs. running time)
|                      |  1.5k          | 15k           | 150k        | 1.5m         | 15m          |
|origin             |2.66ms      |4.48ms     |25.03ms  |231.8ms   |2339ms     |
|with commit  |3.9ms        |26.22ms   |255.8ms  |2595ms    |26080ms   |

We can see the performance is increased one order of magnitude (10X).
We also did similar things in PLR, and the performance is increased about 20x under same circumstances.

Author: Haozhou Wang <hawang@pivotal.io>
Author: Paul Guo <paulguo@gmail.com>
Author: Hubert Zhang <zhanghuan929@gmail.com>

### CODE REVIEW

**Comment by Eulerizeit** [comment]
Does this exist in Postgres? If not can we contribute this code upstream?

**Comment by HaozhouWang** [comment]
No, this does not exist in PG either. 
Yes, We have a plan to contribute to upstream.

**Comment by xinzweb** [comment]
Any update on this PR? Make it to upstream? What's timeline? also @HaozhouWang and @Eulerizeit feel free to mark as `ToDo` label if we want to track in the PR. Thanks. This will remove it from the PR reminder. Thanks.

**Comment by HaozhouWang** [comment]
Thanks @xinzweb . We are still waiting upstream reviewing the patch. Will backport the patch once the upstream review is done. I added a `ToDo` label.

**Comment by xinzweb** [comment]
Thanks a lot.

**Comment by HaozhouWang** [comment]
The link is https://commitfest.postgresql.org/19/1499/
The PG patch was updated by another person but seems no more response from him.

**Comment by danielgustafsson** [comment]
This patch has been rejected by upstream, how do we want to handle it?

**Comment by berlin-ab** [comment]
@HaozhouWang What's the plan for this PR?

**Comment by HaozhouWang** [comment]
Hi, 
As this is been rejected by upstream, I would like to close it now and wait for another chance.
Thanks.

**Comment by paul-guo-** [comment]
This patch is very useful and there was good discussion on upstream if I remeber correctly. Maybe we should understand the concern from upstream at first. I did not see any related email in pg hacker email about this.

**Pull request closed without merging**
