### PR TITLE
Initialize all subplans in ValuesScanState (backport)

### PR DESCRIPTION
**Pull request by leskin-in**
This is a backport of https://github.com/postgres/postgres/commit/2e2646060e18461de24e3585344095664dc7727b.

`EXPLAIN` output is incorrect in [current GPDB 7](https://github.com/greenplum-db/gpdb/tree/fc4b84d2e0de28b4637eb95646f7c49e17e0bbbd). Compare the following queries:

* [Current GPDB 7](https://github.com/greenplum-db/gpdb/tree/fc4b84d2e0de28b4637eb95646f7c49e17e0bbbd)
```
EXPLAIN select val.x
  from generate_series(1,10) as s(i),
  lateral (
    values ((select s.i + 1)), (s.i + 101)
  ) as val(x)
where s.i < 10 and (select val.x) < 110;
                                 QUERY PLAN                                 
----------------------------------------------------------------------------
 Nested Loop  (cost=10000000000.00..10000000000.33 rows=3 width=4)
   ->  Function Scan on generate_series s  (cost=0.00..0.13 rows=3 width=4)
         Filter: (i < 10)
   ->  Values Scan on "*VALUES*"  (cost=0.00..0.05 rows=1 width=4)
         Filter: ((SubPlan 1) < 110)
         SubPlan 1
           ->  Result  (cost=0.00..0.01 rows=1 width=4)
 Optimizer: Postgres query optimizer
(8 rows)
```

* PostgreSQL 12.6
```
EXPLAIN select val.x
  from generate_series(1,10) as s(i),
  lateral (
    values ((select s.i + 1)), (s.i + 101)
  ) as val(x)
where s.i < 10 and (select val.x) < 110;
                                 QUERY PLAN                                 
----------------------------------------------------------------------------
 Nested Loop  (cost=0.00..0.31 rows=3 width=4)
   ->  Function Scan on generate_series s  (cost=0.00..0.13 rows=3 width=4)
         Filter: (i < 10)
   ->  Values Scan on "*VALUES*"  (cost=0.00..0.05 rows=1 width=4)
         Filter: ((SubPlan 1) < 110)
         SubPlan 1
           ->  Result  (cost=0.00..0.01 rows=1 width=4)
         SubPlan 2
           ->  Result  (cost=0.00..0.01 rows=1 width=4)
(9 rows)
```

One `SubPlan` (which actually produces the results) is missing.

* GPDB 7 with this PR applied
```
EXPLAIN select val.x
  from generate_series(1,10) as s(i),
  lateral (
    values ((select s.i + 1)), (s.i + 101)
  ) as val(x)
where s.i < 10 and (select val.x) < 110;
                                 QUERY PLAN                                 
----------------------------------------------------------------------------
 Nested Loop  (cost=10000000000.00..10000000000.33 rows=3 width=4)
   ->  Function Scan on generate_series s  (cost=0.00..0.13 rows=3 width=4)
         Filter: (i < 10)
   ->  Values Scan on "*VALUES*"  (cost=0.00..0.05 rows=1 width=4)
         Filter: ((SubPlan 1) < 110)
         SubPlan 1
           ->  Result  (cost=0.00..0.01 rows=1 width=4)
         SubPlan 2
           ->  Result  (cost=0.00..0.01 rows=1 width=4)
 Optimizer: Postgres query optimizer
(10 rows)
```

## Extra changes compared to upstream commit
`subselect` test is updated as a part of the original fix, and this PR. In GPDB, there is an extra version of this test's result file - `subselect_optimizer`. It is updated with corresponding output from GPDB with ORCA enabled.

### CODE REVIEW

**Comment by kainwen** [comment]
Thanks a lot for this PR @leskin-in 

I found PG 12_STABLE also contains this:

```
commit 2e2646060e18461de24e3585344095664dc7727b
Author: Tom Lane <tgl@sss.pgh.pa.us>
Date:   Fri Jan 17 16:17:17 2020 -0500

    Repair more failures with SubPlans in multi-row VALUES lists.

    Commit 9b63c13f0 turns out to have been fundamentally misguided:
    the parent node's subPlan list is by no means the only way in which
    a child SubPlan node can be hooked into the outer execution state.
    As shown in bug #16213 from Matt Jibson, we can also get short-lived
    tuple table slots added to the outer es_tupleTable list.  At this point
    I have little faith that there aren't other possible connections as
    well; the long time it took to notice this problem shows that this
    isn't a heavily-exercised situation.

    Therefore, revert that fix, returning to the coding that passed a
    NULL parent plan pointer down to the transiently-built subexpressions.
    That gives us a pretty good guarantee that they won't hook into the
    outer executor state in any way.  But then we need some other solution
    to make SubPlans work.  Adopt the solution speculated about in the
    previous commit's log message: do expression initialization at plan
    startup for just those VALUES rows containing SubPlans, abandoning the
    goal of reclaiming memory intra-query for those rows.  In practice it
    seems unlikely that queries containing a vast number of VALUES rows
    would be using SubPlans in them, so this should not give up much.

    (BTW, this test case also refutes my claim in connection with the prior
    commit that the issue only arises with use of LATERAL.  That was just
    wrong: some variants of SubLink always produce SubPlans.)

    As with previous patch, back-patch to all supported branches.

    Discussion: https://postgr.es/m/16213-871ac3bc208ecf23@postgresql.org
```

Given that we will merge to 12STABLE for 7X and catch up later postgres in master branch, I think we might not backport it now.

Close the PR.

Thanks again and sorry for long time no response.

**Comment by Stolb27** [comment]
@kainwen, FYI, 6X_STABLE was affected by this problem too, but we opened PR to the master branch first. There is ready to apply fix from our fork: https://github.com/arenadata/gpdb/pull/197

**Comment by kainwen** [comment]
> @kainwen, FYI, 6X_STABLE was affected by this problem too, but we opened PR to the master branch first. There is ready to apply fix from our fork: [arenadata#197](https://github.com/arenadata/gpdb/pull/197)

Ah， thanks for the reminder. Got it. Seems I cannot reopen this.

Let me mark it internally and see how we can fix for 6X.

@Stolb27 Thanks again!

**Comment by kainwen** [comment]
Hi @Stolb27  @leskin-in 
seems pivotal-cla is not signed so that I cannot push this.

Would you please sign it?  Or let me backport in a new PR.

**Review by kainwen — APPROVED** [review]

**Comment by Stolb27** [comment]
@kainwen, you are free to create a backport, because I don't have possibility to sign CLA instead of @leskin-in or ask him about.

**Comment by kainwen** [comment]
> @kainwen, you are free to create a backport, because I don't have possibility to sign CLA instead of @leskin-in or ask him about.

Sure. Let me create the same PR as this one to push it to master branch.

Extra question: do you have a finished version of 6X backport commit? If so, just open a new PR. If not, do you want to take the backport-to-6x job or let my team do it?

Thanks! @Stolb27

**Comment by kainwen** [comment]
Close this since I open a new one: https://github.com/greenplum-db/gpdb/pull/13931

Thanks a lot @leskin-in @Stolb27

**Comment by Stolb27** [comment]
@kainwen, FYI original Postgres commit was ported to 6X_STABLE as a part of 9.4.26 sync: https://github.com/greenplum-db/gpdb/pull/11784/commits/eb9d1f0504a64aeae2b91279bc59e2649d35b4b0

**Comment by kainwen** [comment]
> @kainwen, FYI original Postgres commit was ported to 6X_STABLE as a part of 9.4.26 sync: [eb9d1f0](https://github.com/greenplum-db/gpdb/commit/eb9d1f0504a64aeae2b91279bc59e2649d35b4b0)

Ah, 6X has already done merging to stable. So GPDB6 now does not have the issue.

Then I prefer not to backport to master and let master just wait for next merge.

**Pull request closed without merging**
