### PR TITLE
[6X] Adds feature flags for check cluster: `continue-check-on-fatal` and `skip-target-check`

### PR DESCRIPTION
**Pull request by degaurab**
Adds `--skip-target-check` and `--continue-check-on-fatal` features for check mode:

- `--continue-check-on-fatal` flag allows to parse through the
  checklist without erroring out in case of failure.
   - Need to be used along with check flag `-c`
   - Indent log messages for proper output rendering
   
- `--skip-target-check` allows to skip checks on new cluster
     - when you are using --skip-target-check along with check flag (-c) we
  dont need to provide
      - new-bindir (-B)
      - new-datadir (-D)
      - new-port (-P)
      - new-gp-dbid
   - it can be used along with `--continue-check-on-fatal`

Example:
`--continue-check-on-fatal`
```
pg_upgrade \
-b /usr/local/5XSTABLE/bin/ \
-B /usr/local/6XSTABLE/bin/ \
-d /data/5XStable/demoDataDir-1 \
-D /data/6XStable/demoDataDir-1 \
-p 15432 \
-P 6000 \
--old-gp-dbid=1 \
--new-gp-dbid=1 \
-c --continue-check-on-fatal
```

`--skip-target-check`
```
pg_upgrade \
-b /usr/local/5XSTABLE/bin/ \
-d /data/5XStable/demoDataDir-1 \
-p 15432 \
--old-gp-dbid=1 \
-c --skip-target-check
```

Co-authored-by: Gaurab Dey <gaurabd@vmware.com>
Co-authored-by: Bhuvnesh Chaudhary <bchaudhary@vmware.com>

### CODE REVIEW

**Comment by kalensk** [comment]
Let's not make it a hard requirement (ie: still run) if the user passes new-bindir (-B),  new-datadir (-D) new-port (-P), new-gp-dbid, etc. with `--skip-target-check` flag. Just ignore those additional flags if they are passed in. Maybe make it clear in the --help output that only the source cluster settings are needed. This makes the gpupgrade calling code much simpler. And there are no other callers other than gpupgrade as well, so its fine.

**Comment by degaurab** [comment]
> Let's not make it a hard requirement (ie: still run) if the user passes new-bindir (-B), new-datadir (-D) new-port (-P), new-gp-dbid, etc. with `--skip-target-check` flag. Just ignore those additional flags if they are passed in. 

Only hard requirement is the check flag `-c`, any additional flag will be ignore right now.

>Maybe make it clear in the --help output that only the source cluster settings are needed. This makes the gpupgrade calling code much simpler. And there are no other callers other than gpupgrade as well, so its fine.

make sense, can updated the description to make it clear for users.

thanks for the feedback @kalensk

**Comment by jimmyyih** [comment]
This PR conflicts heavily with https://github.com/greenplum-db/gpdb/pull/13084 (obviously because it's basically a subset of changes contained in this PR).  I would suggest finishing up https://github.com/greenplum-db/gpdb/pull/13084 first and then rebase the main commit of this PR on top of the future 6X_STABLE HEAD.  Then alert reviewers afterwards.

**Comment by kalensk** [comment]
Going off @jimmyyih what said...Could we close one of the PRs and just update the PR description to include both commits. Or close both PRs and open a fresh one with both commits?

**Comment by khuddlefish** [comment]
@degaurab Should this PR be closed now?

**Comment by jimmyyih** [comment]
This should have been closed a while ago.  The newer PR is https://github.com/greenplum-db/gpdb/pull/13273 which has already been merged into 6X_STABLE.

**Pull request closed without merging**
