### PR TITLE
Support gptransfer tables with dots in the names

### PR DESCRIPTION
**Pull request by adam8157**
Take dot as a valid character, and quote the corresponding external
table's name.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Does it escape double-quotes correctly, too?

**Comment by khuddlefish** [comment]
There are other special characters that can be in tables that need to be escaped separately from just wrapping the table name in quotes. Things like double quotes and backslashes. If you get the name from the database and can use the Postgres quote_ident() function, that is best because it handles everything for you. It will even quote reserved keyword names that may not have special characters, but still need to be quoted. Alternatively, you can create a function that looks for the characters that need to be escaped and escape them yourselves. We did that in gpbackup using regular expressions (though we have since switched to using the db quote_ident everywhere).

**Comment by adam8157** [comment]
No, it doesn't handle double-quotes or backslashes well.

gptransfer has its own supported identifiers, check `is_identifier_supported()`, I wonder if there is a reason of the limit. Will check with PM and have a new story I suppose.

**Comment by adam8157** [comment]
We decided to merge this first, before a good solution.

If we are going to support all special characters, since gptransfer is a python script with lots of shell commands, quote_indent() is far not enough, the escape thing goes a bit out of control, check #4524 .

**Comment by adam8157** [comment]
Oops, this is much more complex than we thought, logging and outputs need refactor to display right, this PR is not good enough, reverted it.

**Pull request merged**
