### PR TITLE
WIP: Connect gpperfmon to main build rather than gpAux

### PR DESCRIPTION
**Pull request by danielgustafsson**
Building gpperfmon is today not done via the main buildsystem, something which cause issues since it has non-standard dependencies. Given that gpperfmon is a tool which is in production use, this is an attempt at modernizing it and bringing it in as a first class citizen in Greenplum 5.0. This PR is a WIP to solicit feedback and help on finalizing this. Should this be accepted I think the commits should be squashed into one but I've kept them separate here to show the steps clearer.

The gist of the work is:

* Move the code into `src/bin`
* Get rid of as much platform dependent building as possible, today the code fails to build on for example Ubuntu for no good reason
* Refactor lots of code to reduce warnings
* Bring in dependency resolution in autoconf and add all the needed libraries
* Start to remove the deprecated emcconnect support

### CODE REVIEW

**Comment by yydzero** [comment]
Could you please share more info about removing emcconnect from GPDB5? Any impact to its user? not sure whether GPCC has used it or not.

@ivannovick @seriouslynow

**Comment by danielgustafsson** [comment]
I'm not sure about the impact, I'm merely acting upon a request from @ivannovick in https://github.com/greenplum-db/gpdb/issues/529#issuecomment-216259190 to remove it. Judging by that comment though it sounds like emcconnect has been replaced by other tools in production already.

**Comment by yydzero** [comment]
Thanks Daniel!

@ivannovick could you please confirm whether this is safe to remove?

**Comment by ivannovick** [comment]
Really appreciate this effort I think its great.  EMC Connect code can be safely removed from GPDB, there are now seperate code in EMC's Appliance to send dial homes and not required in GPDB.

**Comment by danielgustafsson** [comment]
This PR was to solicit feedback, it's not in a state where it can be expected to be merged anytime soon. Closing and will open a new PR once (if?) I get time to finish this patch.

**Pull request closed without merging**
