### PR TITLE
Update clients submodule with case sensitive fix

### PR DESCRIPTION
**Pull request by cjcjameson**
Please enter the commit message for your changes. Lines starting

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cjcjameson Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1289)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1289) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by cjcjameson** [comment]
@davecramer & @Eulerizeit, who know more about this particular submodule.

**Comment by pivotal-issuemaster** [comment]
@cjcjameson Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1289)!

**Comment by Eulerizeit** [comment]
Is there anything in the affected submodule we build anymore? I didn't notice anything.

**Comment by danielgustafsson** [comment]
This was commited in ce0d2d894456faa4f3e0b2bd175bb41ef41c72ae, closing.

**Comment by cjcjameson** [comment]
Thanks for noticing the connection, Daniel!

**Pull request closed without merging**
