### PR TITLE
Clean up the way the results array is allocated in cdbdisp_returnResults().

### PR DESCRIPTION
**Pull request by hlinnaka**
Plus a fix for a memory leak that was exposed when I removed the NULL terminator from the array returned by cdbdisp_returnResults().

### CODE REVIEW

**Comment by hlinnaka** [comment]
@xiong-gang, you hacked in this area recently, can you review this one, please?

**Comment by danielgustafsson** [comment]
LGTM

**Comment by hlinnaka** [comment]
Ok, pushed, thanks for the review. @xiong-gang, if you get a chance, review from you would still be highly appreciated.

**Comment by xiong-gang** [comment]
+1
I didn't get the notification, sorry for the late response.

**Comment by hlinnaka** [comment]
On 13/05/16 18:01, xiong-gang wrote:
> +1
> I didn't get the notification, sorry for the late response.

No worries, thanks!

- Heikki

**Pull request closed without merging**
