### PR TITLE
Don't transform large array Const into ArrayExpr for Orca

### PR DESCRIPTION
**Pull request by hsyuan**
If the number of elements in the array Const is greater than
optimizer_array_expansion_threshold, returns the original Const unmodified.
Otherwise, it will cause severe performance issue for Orca optimizer for array
with very large number of elements, e.g. 50K.

Fixes issue #3355
[#151340976]

### CODE REVIEW

**Comment by hsyuan** [comment]
This commit https://github.com/greenplum-db/gpdb/commit/9a817d453550776ee02a2a0d73a33b8870842fac says that transform small array Const into to ArrayExpr, but in fact it also transforms large array const, no matter how large the size of the array.

**Comment by hlinnaka** [comment]
Looks fine as such, but wouldn't it be better to fix the performance issue in ORCA itself? This only affects very large array constants, so even with this patch, you might still have a very large Array expression in your query, if it's not a constant.

**Comment by hsyuan** [comment]
Heikki, your original patch was correct in your PR https://github.com/greenplum-db/gpdb/pull/2146, but our guy changed it. sigh..

I thought Orca already fixed it by https://github.com/greenplum-db/gporca/pull/147. But seems like it doesn't consider the case with cast on const. Currently, we only optimize for const only large array, for non-const element, we leave as it is, because we haven't see this issue yet. ;)

**Comment by hlinnaka** [comment]
On 09/28/2017 08:57 AM, Haisheng Yuan wrote:
> Heikki, your original patch was correct in your PR
> https://github.com/greenplum-db/gpdb/pull/2146, but our guy changed
> it. sigh..
> 
> I thought Orca already fixed it by
> https://github.com/greenplum-db/gporca/pull/147. But seems like it
> doesn't consider the case with cast on const. Currently, we only
> optimize for const only large array, for non-const element, we leave
> as it is, because we haven't see this issue yet. ;)

Can we fix this newly-found issue with a cast on const in ORCA as well? 
It sure would be nicer.

- Heikki

**Comment by hsyuan** [comment]
If the large array contains non-const expressions, Orca will generate a MEMO group for every single element in the array. This still has performance issue, but little can be done to optimize the MEMO group size.

**Comment by hsyuan** [comment]
Yep, I believe so. Will fix it tomorrow.

~ ~ ~
Haisheng Yuan

**Comment by hsyuan** [comment]
Pushed to
Master: https://github.com/greenplum-db/gpdb/commit/1c82fac22d76492c9392aadc0bc6935fbeb2fd87
5X_STABLE: https://github.com/greenplum-db/gpdb/commit/41fe57f978beb77e616f4c534b0306de45df64ac

Thanks for the review.

**Pull request merged**
