### PR TITLE
docs: integrate cast information with install guide.

### PR DESCRIPTION
**Pull request by mkiyama**
-Move cast examples to install guide
-Pointer from install guide to admin guide for cast description.

Link to updated pages on gpdb review site
http://docs-gpdb-review-staging.cfapps.io/review/install_guide/43x_to_5x.html

http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/query/topics/defining-queries.html#topic14

### CODE REVIEW

**Comment by mkiyama** [comment]
The Admin Guide can go as is.
I think the Install Guide changes might need to be tweaked. 
Currently the topic mentions GPDB 5.x. Should it be changed to 6.x?

**Comment by dyozie** [comment]
Yeah - the installation material in master needs work.  I know there are fixes that haven't been committed there, since we don't yet publish an install procedure for the oss release (ubuntu-only packaging).

**Comment by Eulerizeit** [comment]
Certainly not part of this PR, but, we should do some simple user
acceptance testing with our install stuff.

Rob

**Comment by mkiyama** [comment]
@dyozie 
-Remove duplicate cast information. Pointer from install guide to admin guide for cast description.
-Update cast examples to install guide. Added fixes to cast examples.

**Pull request merged**
