### PR TITLE
Fix dependencies issue in GPPKG utility (6X_STABLE)

### PR DESCRIPTION
**Pull request by HaozhouWang**
1. When two gppkg packages have the same dependencies, gppkg utility
   will refuse to install the second gppkg package and throw an error.
   This patch fixes this issue and the second gppkg package can install
   successfully.

2. Fix install/uninstall issue if the master and standby master use the
   same node address.

PS: This patch is different from the fix in 5X_STABLE branch

### CODE REVIEW

**Comment by Eulerizeit** [comment]
What is the reason this isn't going through master?

**Comment by kmacoskey** [comment]
Does doing a `--force` with the RPM installation have the potentially for hiding or causing other problems? There are many things a `--force` will ignore.

**Comment by bradfordboyle** [comment]
Does this handle DEB-based packages?

**Comment by HaozhouWang** [comment]
@bradfordboyle Thanks for the review. Yes, this is a workaround (quick fix) for gppkg shared library issue. I totally agree there are many issues in gppkg, and need completely rewrite and upgrade. I suppose that we currently do some workarounds about it as we all discussed and agreed in the previous discussion (like 5X_STABLE).  As Python2.7 is out of date, we can do some further discussion about the GPDB utils tools.

@Eulerizeit This is a workaround for PostGIS gppkg module. Python 2.7 is not supported after 2020.1.1, I think we can have a new solution in master.

@kmacoskey Thank you very much for the review. I'm not very familiar with RPM command,  this is a quick fix for gppkg as we did in 5X_STABLE. My two cents is that the extension module in 6x_STABLE, needs to use the system provided libraries (via yum install or apt-get install) and should not bundle the libraries in the gppkg. This will cause many potential problems.

**Comment by HaozhouWang** [comment]
@bradfordboyle deb package does not have the dependency issue. So it will not impact the deb package.

**Comment by Eulerizeit** [comment]
@HaozhouWang I'm not worried about if this is the permanent fix or not, it needs to go through master. The reason we have this issue now is because a temporary fix was pushed into 5.x and not though master more than a year ago. 

Also, why doesn't the .deb have the same dependency issues?

**Comment by Eulerizeit** [comment]
IMO what we need todo here is spend the time to properly fix this on master, then we can figure out if/how to backport this to all relevant versions. 

It seems like proper fix must include 

1. no longer vendoring packages we aren't supposed to vendor -- (is this a gppkg problem?)
2. making sure what ever is done deals with dependency resolution
3. making sure we deal with issues in .rpm and .deb 

gppkg is problematic. I can't see how hiding these dependency problems helps. what we are going to end up having is a bunch of extensions running on different libraries and the library that they use will be based on the installation order. How do we test that or debug that?

**Comment by schubert** [comment]
Flagging @edespino @pivotal-mike @divyabhargov @macroyuyang @yydzero to weigh in here.

**Comment by HaozhouWang** [comment]
@Eulerizeit , the deb is newly added into gppkg, so the ubuntu gppkg does not need to worry about the dependency issue. The dependency management of gppkg is a long historical issue, we had a lot of discussion on this. IMO, the gppkg framework needs completely rewritten to fix all issues (dependency is only one issue here). So, I'm +1 on this. Also, it needs all extension users to agree to fix it.

**Comment by wuj21** [comment]
Just like greenplum 5.x, I think for greenplum 6.x we just need to quick fix to resolve the libraries conflict between postgis and plcontainer. 
Although there are lots of issue in gppkg, it works for most of all cases. So I think it is OK to leave it there in greenplum 6.x.

**Comment by pivotal-mike** [comment]
@HaozhouWang Watching the discussion here can I ask that we put a fix into master first?  I'd like to avoid putting fixes into stable branches and then forgetting about them like we did here with the fix on 5X

**Comment by HaozhouWang** [comment]
As discussed before, this PR went to the master branch and the pipeline is green now.

**Pull request merged**
