### PR TITLE
Honor BLD_TYPE if set.

### PR DESCRIPTION
**Pull request by xinzweb**

### CODE REVIEW

**Comment by xinzweb** [comment]
@vraghavan78 @oarap @hsyuan @hlinnaka

**Comment by hlinnaka** [comment]
LGTM. I wonder how this ever worked, though.We've done debug-builds before, haven't we?

**Comment by hsyuan** [comment]
+1

**Comment by danielgustafsson** [comment]
:+1:

**Comment by ascherbaum-pivotal** [comment]
+1

**Comment by xinzweb** [comment]
@hlinnaka well, the gpopt is always hard coded to build in opt. We used to build GPDB in debug, as long as we don't use GPORCA in debug, we are good. Or, we build GPDB in debug, and link to GPORCA build in `opt`, and we are also good. :) Just we never be able to build GPDB in debug, and GPORCA in debug. This little fix just a small step towards a better build experience between GPDB and GPORCA. This enabled people to override build flavor using `BLD_TYPE`. Thanks.

**Pull request merged**
