### PR TITLE
Use build-gpdb-rpm.yml for GP5 packaging

### PR DESCRIPTION
**Pull request by bhanu-atturu**
[GP-776]

Authored-by: Bhanu Kiran Atturu <batturu@vmware.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by BaiShaoqi — APPROVED** [review]
Looks good to me

**Review by BaiShaoqi — COMMENTED** [review]
Curious, whey https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-batturu/resources/gpdb_rpm_installer_centos6
shows 
```


path | server/published/gpdb5/greenplum-db-soumyadeep2007-5x_test-5.28.13+dev.4.g34d5bc4a03-rhel6-x86_64.rpm



```

**Comment by BaiShaoqi** [comment]
With @50wu  the non valid artifacts  which confuse us: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/5X_STABLE/resources/gpdb_rpm_installer_centos6
https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/5X_STABLE/resources/gpdb_rpm_installer_centos7
here can be removed

**Comment by bhanu-atturu** [comment]
These artifacts were probably created from a dev pipeline. But I'm not sure why they were added to the prod bucket.

**Review by bmdoil — APPROVED** [review]
+1

**Pull request merged**
