### PR TITLE
Remove exceptionally slow test query.

### PR DESCRIPTION
**Pull request by hlinnaka**
This test case tests that a CTE query from earlier in the test file also
works if it's put in a view. There are a few other tests for CTEs in views
in there, and this query doesn't seem particularly interesting from the
point of view of testing views. There's usually little harm in a little
excessive test queries, but this query is exceptionally slow. Removing it
reduces the runtime of this test by about 5-10 seconds on my laptop.

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
It says "deeply nested" - does any of the other tests cover this in a nested way?

That said: 10s is really slow - maybe running this on a smaller dataset might help.

**Comment by vraghavan78** [comment]
Will look at it later today

**Comment by hlinnaka** [comment]
On 03/02/2017 12:31 PM, Andreas Scherbaum wrote:
> It says "deeply nested" - does any of the other tests cover this in a nested way?

There is this exact same query earlier in the file, just not in a view. 
I don't think the "in a view" aspect is important here.

> That said: 10s is really slow - maybe running this on a smaller dataset might help.

Yeah, that'd be one option. There are a lot of queries on the same 
dataset in the file, so changing it would affect a lot of queries. But 
maybe we should do it - it would make a lot of the queries faster. And 
there's no reason to think that a smaller data set would give less 
coverage. Some queries might choose different plans, but we don't know 
if the current plans are the most interesting ones to test anyway.

- Heikki

**Comment by hlinnaka** [comment]
On 03/03/2017 12:05 AM, Venkatesh Raghavan wrote:
> LGTM.

Ok, pushed.

> Will add this test unit test inside Orca.

May I ask why? By the time Orca sees the query, the rewriter has already 
expanded the view, and it shouldn't be any different from running it as 
a plain query.

- Heikki

**Pull request closed without merging**
