### PR TITLE
(5x only)Fix access-to-already-freed-memory issue in plpython's error handling.

### PR DESCRIPTION
**Pull request by kainwen**
This commit is backported from upstream's d54de3962a1. Following is
original commit message (refined):

```
PLy_elog() could attempt to access strings that Python had already freed,
because the strings that PLy_get_spi_error_data() returns are simply
pointers into storage associated with the error "val" PyObject.  That's
fine at the instant PLy_get_spi_error_data() returns them, but just after
that PLy_traceback() intentionally releases the only refcount on that
object, allowing it to be freed --- so that the strings we pass to
ereport() are dangling pointers.

In principle this could result in garbage output or a coredump.  In
practice, I think the risk is pretty low, because there are no Python
operations between where we decrement that refcount and where we use the
strings (and copy them into PG storage), and thus no reason for Python
to recycle the storage.  Still, it's clearly hazardous, and it leads to
Valgrind complaints when running under a Valgrind that hasn't been
lobotomized to ignore Python memory allocations.

The code was a mess anyway: we fetched the error data out of Python
(clearing Python's error indicator) with PyErr_Fetch, examined it, pushed
it back into Python with PyErr_Restore (re-setting the error indicator),
then immediately pulled it back out with another PyErr_Fetch.  Just to
confuse matters even more, there were some gratuitous-and-yet-hazardous
PyErr_Clear calls in the "examine" step, and we didn't get around to doing
PyErr_NormalizeException until after the second PyErr_Fetch, making it even
less clear which object was being manipulated where and whether we still
had a refcount on it.  (If PyErr_NormalizeException did substitute a
different "val" object, it's possible that the problem could manifest for
real, because then we'd be doing assorted Python stuff with no refcount
on the object we have string pointers into.)

So, rearrange all that into some semblance of sanity, and don't decrement
the refcount on the Python error objects until the end of PLy_elog().
In HEAD, I failed to resist the temptation to reformat some messy bits
from 5c3c3cd along the way.
```

Author-by: Tom Lane

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by gfphoenix78 — APPROVED** [review]
The patch looks the same as the original patch. +1

**Comment by kainwen** [comment]
It is not easy to add a test case. We reproduce this issue locally by compiling a specific version of Python.

**Review by HaozhouWang — APPROVED** [review]
+1, great work!

**Review by soumyadeep2007 — COMMENTED** [review]
I see that we also had to backport a part of Heikki's commit: https://github.com/postgres/postgres/commit/316186f2893d37ecd8e32392ee7c910cca9b93eb

Why not have two commits? One that backports Heikki's change followed by Tom Lane's commit. That way we can also get the test changes that accompany Heikki's commit and it leads to a cleaner history.

**Comment by soumyadeep2007** [comment]
With @ashwinstar :
We felt that the changes from 316186f were unrelated and this fix need not depend on those.
We also saw that 316186f was not backported to versions below 9.3, which further confirmed our notion. Also, we tried running
the tests added in 316186f, which turned out irrelevant to the GPDB5 codebase (since `plpy.spiexceptions` doesn't exist, etc.)

If we had used Tom Lane's commit from 9.2, we wouldn't have had to deal with changes from 316186f. In general, backporting from the version closest to ours is easiest.

Testing notes:
1. We ran the patch and tested manually with the debug build of Python which clobbers freed memory. Unlike before the patch ,we saw that the memory for `query`, `detail` and `hint` were cleaned up only after `ereport` gets called.
2. We also ran `make installcheck` inside `src/pl/plpython` which passed against the Python debug build.

**Comment by soumyadeep2007** [comment]
> It is not easy to add a test case. We reproduce this issue locally by compiling a specific version of Python. Upstream's patch does not contain test case also.

True. Here are some manual steps to test. **Please add these at the end of the commit message for posterity:**

1. Build python from source with the following flags to clobber freed memory:
./configure CFLAGS=-DPYMALLOC_DEBUG --with-pydebug --enable-shared --prefix=/home/pivotal/cpython_install_2.7
make -j16 && make install

2. Configure gpdb with this cpython:
PYTHON=/home/pivotal/cpython_install_2.7/bin/python2.7 ./configure --prefix=/usr/local/gpdb5 --with-python --disable-gpcloud --disable-orca -enable-cassert --enable-debug --enable-depend --enable-shared --enable-tap-tests CFLAGS='-ggdb -O0 -fno-omit-frame-pointer'
make && make install # gpdb

   Add the following to greenplum_path.sh:
   export PYTHONPATH=/home/pivotal/cpython_install_2.7/lib/python2.7:/usr/local/gpdb5/lib/python

3. Run the following PL/Python function "valid_type" from src/pl/plpython/sql/plpython_function.sql:
    SELECT valid_type('rick');
    
    Before the patch the output observed:

    select valid_type('rick'); -- will spew out garbage in the "QUERY" field
ERROR:  plpy.SPIError: relation "users" does not exist
LINE 1: ���������������������������������������������������������
                          ^
QUERY:  ���������������������������������������������������������
CONTEXT:  Traceback (most recent call last):
  PL/Python function "valid_type", line 2, in <module>
    SD["plan"] = plpy.prepare("SELECT fname FROM users WHERE lname = $1", [ "text" ])
PL/Python function "valid_type"

   After the patch, the query field is correct:

   postgres=# select valid_type('rick');
ERROR:  plpy.SPIError: relation "users" does not exist
LINE 1: SELECT fname FROM users WHERE lname = $1
                          ^
QUERY:  SELECT fname FROM users WHERE lname = $1
CONTEXT:  Traceback (most recent call last):
  PL/Python function "valid_type", line 2, in <module>
    SD["plan"] = plpy.prepare("SELECT fname FROM users WHERE lname = $1", [ "text" ])
PL/Python function "valid_type"

**Review by soumyadeep2007 — APPROVED** [review]
Looks good. Please squash the commit we added and merge after PR pipeline is successful.

**Comment by kainwen** [comment]
> > It is not easy to add a test case. We reproduce this issue locally by compiling a specific version of Python. Upstream's patch does not contain test case also.
> 
> with @ashwinstar
> 
> True. Here are some manual steps to test. **Please add these at the end of the commit message for posterity:**
> 
> 1. Build python from source with the following flags to clobber freed memory:
>    ./configure CFLAGS=-DPYMALLOC_DEBUG --with-pydebug --enable-shared --prefix=/home/pivotal/cpython_install_2.7
>    make -j16 && make install
> 2. Configure gpdb with this cpython:
>    PYTHON=/home/pivotal/cpython_install_2.7/bin/python2.7 ./configure --prefix=/usr/local/gpdb5 --with-python --disable-gpcloud --disable-orca -enable-cassert --enable-debug --enable-depend --enable-shared --enable-tap-tests CFLAGS='-ggdb -O0 -fno-omit-frame-pointer'
>    make && make install # gpdb
>    Add the following to greenplum_path.sh:
>    export PYTHONPATH=/home/pivotal/cpython_install_2.7/lib/python2.7:/usr/local/gpdb5/lib/python
> 3. Run the following PL/Python function "valid_type" from src/pl/plpython/sql/plpython_function.sql:
>    SELECT valid_type('rick');
>    Before the patch the output observed:
>    select valid_type('rick'); -- will spew out garbage in the "QUERY" field
>    ERROR:  plpy.SPIError: relation "users" does not exist
>    LINE 1: ���������������������������������������������������������
>    ^
>    QUERY:  ���������������������������������������������������������
>    CONTEXT:  Traceback (most recent call last):
>    PL/Python function "valid_type", line 2, in 
>    SD["plan"] = plpy.prepare("SELECT fname FROM users WHERE lname = $1", [ "text" ])
>    PL/Python function "valid_type"
>    After the patch, the query field is correct:
>    postgres=# select valid_type('rick');
>    ERROR:  plpy.SPIError: relation "users" does not exist
>    LINE 1: SELECT fname FROM users WHERE lname = $1
>    ^
>    QUERY:  SELECT fname FROM users WHERE lname = $1
>    CONTEXT:  Traceback (most recent call last):
>    PL/Python function "valid_type", line 2, in 
>    SD["plan"] = plpy.prepare("SELECT fname FROM users WHERE lname = $1", [ "text" ])
>    PL/Python function "valid_type"

Will add this when squash and merge. Thanks.

**Pull request merged**
