### PR TITLE
Fix building xlogdump on platforms with strlcpy in base

### PR DESCRIPTION
**Pull request by danielgustafsson**
OS X and OpenBSD (and most likely more but those are the ones I have handy) already supply `strlcpy()` in base and thus we need to avoid building the supplied file on those platforms. This could have been handled by ifdefs in the code as well but doing it in the Makefile mimics how strlcpy.c is handled in `src/port` such that we have a single consistent behavior. Checking for the Windows specific env variable isn't pretty but is the safest way I know to not break on Windows where uname isn't available.

Also reconnects building xlogdump following the temporary disconnect during the merge.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Updated to simply remove `strlcpy.c` since it's not actually used in the code at all as @hlinnaka discovered.

**Comment by hlinnaka** [comment]
LGTM.

strlcpy.c came from the upstream xlogdump, so you could also argue that it'd be better to keep it in our repository to minimize the diff against upstream. I won't argue that though, on balance, it seems better to not have dead code lying around.

**Comment by danielgustafsson** [comment]
I was considering leaving it but *a)* dead code is a bit yuck and; *b)* by the looks of things it was included by mistake in the first place in the original commit (https://github.com/snaga/xlogdump/commit/f62791195f0dca5378b62ebfd3057b5b3565eb57) so I will instead open a PR against upstream to remove it there as well. Thanks for review.

**Comment by danielgustafsson** [comment]
Pushed. Upstream is however abandoned in favor of `src/bin/pg_xlogdump` in base so probably not worth opening a PR there to sit and not go anywhere.

**Pull request closed without merging**
