### PR TITLE
Remove unnecessary null pointer checks in gpcloud code (#13877)

### PR DESCRIPTION
**Pull request by jingwen-yang-yjw**
1. Remove unnecessary null pointer checks
In C++, there is no need to check whether a pointer is null or not.
This pr removes these unnecessary null pointer checks.
This issue is reported in #8194.

2. Fix bug using delete to destroy objects allocated by new[]
Using delete on a pointer returned by new [] results in undefined behavior.
This pr fix this bug reported by issue #13811.

### CODE REVIEW

**Comment by elfring** [comment]
I find it safer to split desirable changes according to different issues. 🤔

**Comment by jingwen-yang-yjw** [comment]
> I find it safer to split desirable changes according to different issues. 🤔

**Review by elfring — COMMENTED** [review]
* I find the first sentence of the commit description incomplete.
  Please improve the message another bit.
* Can the proposed adjustment trigger also the removal of questionable delete statements?

**Comment by jingwen-yang-yjw** [comment]
> * I find the first sentence of the commit description incomplete.
>   Please improve the message another bit.
> * Can the proposed adjustment trigger also the removal of questionable delete statements?

Thank you. I've improved the first commit message.
But I don't understand your question. Could you please explain it with more details?

**Comment by elfring** [comment]
Thanks for a small wording adjustment.

-----

💭 Would you like to [follow C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/444704f703a40aa1295605f0ef70d94615376034/CppCoreGuidelines.md#Rr-newdelete "R.11: Avoid calling new and delete explicitly") any more?

**Comment by jingwen-yang-yjw** [comment]
> Thanks for a small wording adjustment.
> 
> 💭 Would you like to [follow C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/444704f703a40aa1295605f0ef70d94615376034/CppCoreGuidelines.md#Rr-newdelete) any more?

Thanks for your suggestion.
To support older platforms, we follow the c++11 standard while developing gpcloud.
And make_unique is a new feature in the c++14 standard. So I think it's better not to make such changes now.

**Comment by elfring** [comment]
💭 I suggest to take another look at [available information sources](https://en.wikipedia.org/wiki/C%2B%2B11#General-purpose_smart_pointers "Description for C++11").

How do you think about to improve source code analysis accordingly? 🤔

**Comment by lij55** [comment]
Hi @elfring ,  I totally understand the benefit of new pointer provided C++ STL

those codes were born from GP4 quite a lot of year ago.  we didn't enable c++11 event on GP5. we'd need to keep those code consistent before GP5 officially die... these codes mostly are in maintenance mode now. so it is fine so long as it just work. Appreciated for your interest and help.

**Pull request merged**
