### PR TITLE
Add debug assert and ERROR message when sub-plan for share_id is NULL.

### PR DESCRIPTION
**Pull request by xinzweb**

### CODE REVIEW

**Comment by xinzweb** [comment]
@vraghavan78 @hlinnaka @hsyuan

**Comment by vraghavan78** [comment]
@hlinnaka I said the exact same thing :)

**Comment by xinzweb** [comment]
Thanks for the CR. Please see the new patch. I am running ICG now. Thanks @vraghavan78 @hlinnaka @hsyuan @atris

**Comment by hlinnaka** [comment]
LGTM. But since we're nitpicking, I'll fire away on some trivial stylistic issues :-)

* error messages should begin with a lower-case letter
* there should be a space between the "if" and the paren, i.e. "if (" instead of than "if("
* braces {} are not needed around the single-line elog(). (someone told me earlier that greenplum has had a convention to always use braces in such cases, but the PostgreSQL style is to *not* have them, and I think we should follow the PostgreSQL style for consistency)

**Comment by xinzweb** [comment]
Thanks for the comment. 

. Since all the "if(" is without space in this file, I will keep it consistent for now.
. All the rest will be fixed. 

Thanks a lot for keep bring the upstream hints here.

**Comment by hlinnaka** [comment]
On 26/01/16 20:25, Xin Zhang wrote:
> Thanks for the comment.
>
> . Since all the "if(" is without space in this file, I will keep it consistent for now.
> . All the rest will be fixed.

Ok, fair enough :-).

- Heikki

**Pull request closed without merging**
