### PR TITLE
[6X backport] Enable for partitioned tables to use column-wise statistics setting

### PR DESCRIPTION
**Pull request by maksm90**
Backport #11226 to 6X_STABLE

### CODE REVIEW

**Review by asimrp — APPROVED** [review]
Looks like a clean cherry-pick, PR pipeline has passed.  Thanks @maksm90 for taking care of the back port.

**Comment by kmacoskey** [comment]
@wenwangBJ @bhuvnesh2703

**Comment by kainwen** [comment]
@maksm90 
We forgot to merge this after approval. So sorry for that.

Now we have `community` label for PR from open source community and this help push PRs quickly.

Would you please help rebase this and then I will get this in once pipeline is green.

Thanks a lot!

**Comment by kainwen** [comment]
The pr pipeline seems failing at some known flaky cases. I set up a new full dev pipeline and will merge this once it is green.

**Comment by kainwen** [comment]
Dev pipeline is all green. Push this. @maksm90 Thanks a lot for your contribution.

**Pull request merged**
