### PR TITLE
WIP: Manage AO segments independently in QE nodes

### PR DESCRIPTION
**Pull request by hlinnaka**
This is still very much Work-In-Progress, no need to review in detail, but please join the discussion on the design on gpdb-dev mailing list, thread "Why does VACUUM use distributed transactions?": https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/JrXnNap84tw.

The basic idea is to let QE nodes manage the AO segments independently, instead of having the master choose the segment to insert to or vacuum.

### CODE REVIEW

**Comment by hlinnaka** [comment]
I spent some more time on this, rebasing it over current master, and cleaning up various loose ends. I also removed the in-memory hash table that was used for keeping track of which segments were in use. The code now relies entirely on the AO segment table for that. Every time a new target segment is needed, the AO segment table is scanned for an available segment, and the chosen target is locked, by acquiring a tuple lock on the row in the AO segment table (with heap_lock_tuple()). This slashes another ~1000 lines of code.

**Comment by hlinnaka** [comment]
There are some regression failures, but nothing too serious AFAICS. This is ready to be reviewed with a serious eye towards getting it committed.

**Comment by ivannovick** [comment]
@deepesh1081 can you help organizing folks to review from your side?

**Comment by hlinnaka** [comment]
Rebased and fixed a few bugs found by src/test/isolation tests. Please review.

**Comment by ashwinstar** [comment]
It would be very helpful to review (folks familiar with the current code or not), if can explain out the new design in terms of how it now works compared to earlier, handles concurrent inserts, crash-recovery, fail-over to mirror, stats it was updating earlier on master is taken care of, incremental backup dependency, etc..

**Comment by hlinnaka** [comment]
On 08/12/2016 08:55 AM, Ashwin Agrawal wrote:
> It would be very helpful to review (folks familiar with the current
> code or not), if can explain out the new design in terms of how it
> now works compared to earlier, handles concurrent inserts,
> crash-recovery, fail-over to mirror, stats it was updating earlier on
> master is taken care of, incremental backup dependency, etc..

Ok, let's see:

* AO segment files are managed locally, in each QE node. If you start an 
insert from the master, each QE independently chooses a target segfile 
to route the inserts to. The algorithm for choosing the target segfile, 
to ensure correct MVCC rules, is the same as before: The segfile must be 
in "available" state, and the last transaction that inserted to the same 
AO segment file must not have run concurrently with the current one. But 
all those checks and the decision are made locally. Instead of 
distributed transaction IDs, local XIDs are used for those checks.

* All the vacuum phases are now performed independently in each QE as 
well, using local transactions. The QD sends a single "VACUUM aotable" 
command to each QE, and the QE opens several local transactions to go 
through the phases.

* Segfile #0 is no longer reserved for utility mode. It can and will be 
chosen as insertion target, like any other segfile. Now that the 
algorithm for choosing insertion target runs locally, utility mode 
doesn't need any special treatment.

* The in-shared-memory hash table is gone. It was used to decide which 
AO segfile to insert to, and to remember the last XID that updated each 
segfile (to avoid choosing a segment that was used "concurrently" (this 
ties to the discussion on PR #1034). The pg_aoseg table is used directly 
for that now. To choose the target segfile, the new code opens the 
pg_aoseg table and scans it for the next available one. And to get the 
last XID that inserted to a segfile, it looks at the pg_aoseg tuple's 
xmin. To lock a segfile when you start inserting to it, the pg_aoseg 
tuple is locked with heap_lock_tuple().

* The segfile information, like which segfiles exist, tupcount and 
modcount, are not kept up-to-date in the master anymore. The pg_aoseg 
table in the master is always empty. It's no longer needed in the 
master, because the QE nodes manage them independently. The code related 
to sending tupcount/modcount information back from QE nodes to the 
master are gone.

* Crash recovery, mirroring, and all that are unchanged. All the changes 
are in to upper layers of the code.

* Incremental backups rely on the modcount field in the AO segment map. 
That's no longer updated in the master, as each QE node manages the AO 
segfiles independently. I don't think this affects incremental backup. I 
presume that incremental backup works independently on each segment too? 
I couldn't actually find the incremental backup code. Where is it?

- Heikki

**Comment by kaknikhil** [comment]
> I couldn't actually find the incremental backup code. Where is it?

the incremental backup code is distributed among the python and c code base. 

*  python , most of it resides in gppylib/operations/dump.py and gppylib/operations/gpcrondump 
*  c , most of it resides in bin/pg_dump/cdb/cdb_dump.c , bin/pg_dump/cdb/cdb_dump_util.c and bin/pg_dump/cdbcdb_dump_agent.c

**Comment by Eulerizeit** [comment]
Is the python code dependent upon the 2.6.2 version. Ideally I'd like to
move away from that version for security and PL/* reasons.

Rob

**Comment by hlinnaka** [comment]
On 08/13/2016 07:47 AM, kaknikhil wrote:
>> I couldn't actually find the incremental backup code. Where is it?
>
> the incremental backup code is distributed among the python and c code base.
>
> *  python , most of it resides in gppylib/operations/dump.py and gppylib/operations/gpcrondump
> *  c , most of it resides in bin/pg_dump/cdb/cdb_dump.c , bin/pg_dump/cdb/cdb_dump_util.c and bin/pg_dump/cdbcdb_dump_agent.c

Let's see if I understand this correctly:

* The incremental backup is all-or-nothing at the partition level. If 
there have been any changes to a partition whatsoever, the whole 
partition is backed up.

* The crux of deciding what needs to be backed up is this SQL query, 
from dump.py:

select to_char(coalesce(sum(modcount::bigint), 0), 
'999999999999999999999') from %s.%s" % (catalog_schema, tupletable)

That's executed on the master, and the table name is the AO segment 
table, i.e. pg_aoseg.pg_aoseg_12345.

Hmm, yeah, this PR needs a bit of extra work to keep that working. Since 
we no longer store the modcounts in the master, the above query will 
always return zero. I think we can just throw a gp_dist_random() in 
there, to fetch the information from all the segments instead:

select to_char(coalesce(sum(modcount::bigint), 0), 
'999999999999999999999') from gp_dist_random('%s.%s'" % (catalog_schema, 
tupletable)

- Heikki

**Comment by kaknikhil** [comment]
> Is the python code dependent upon the 2.6.2 version. Ideally I'd like to
> move away from that version for security and PL/* reasons.

AFAIK , the code isn't dependent on 2.6.2 anymore . @lij55 , can you confirm ?

**Comment by ashwinstar** [comment]
On Thu, Aug 11, 2016 at 11:55 PM, Heikki Linnakangas <
notifications@github.com> wrote:

> * AO segment files are managed locally, in each QE node. If you start an
> insert from the master, each QE independently chooses a target segfile
> to route the inserts to. The algorithm for choosing the target segfile,
> to ensure correct MVCC rules, is the same as before: The segfile must be
> in "available" state, and the last transaction that inserted to the same
> AO segment file must not have run concurrently with the current one. But
> all those checks and the decision are made locally. Instead of
> distributed transaction IDs, local XIDs are used for those checks.
>

Using local XIDs for this check may yield incorrect results, as if
distributed transaction T1 and T2 started together. T1 was assigned
segment-file 1 and inserted data from offset 0-100 and committed, so lock
is released. Then T2 starts on segment will also be assigned segment-file 1
(which creates the problem). As if T2 writes from 100-200 offset and then
reads the table, will return all rows from offset 0-200. So, to make this
work need to reverse map local XID to distributed XID and then perform
concurrency check same way it was performed earlier on master.


>
> * Segfile #0 is no longer reserved for utility mode. It can and will be
> chosen as insertion target, like any other segfile. Now that the
> algorithm for choosing insertion target runs locally, utility mode
> doesn't need any special treatment.
>

Nice. So, I think then Alter will also be no more a special case where it
used to push all the tuples to segfile 0. Which always worried me, like
will we reach a day when Alter will hit the error of max row-number /
tuples reached for segfile.


>
> * The in-shared-memory hash table is gone. It was used to decide which
> AO segfile to insert to, and to remember the last XID that updated each
> segfile (to avoid choosing a segment that was used "concurrently" (this
> ties to the discussion on PR #1034). The pg_aoseg table is used directly
> for that now. To choose the target segfile, the new code opens the
> pg_aoseg table and scans it for the next available one. And to get the
> last XID that inserted to a segfile, it looks at the pg_aoseg tuple's
> xmin. To lock a segfile when you start inserting to it, the pg_aoseg
> tuple is locked with heap_lock_tuple().
>

I believe the lock is held till end of transaction and is getting persisted
on Prepare transaction record. So, incase of failover to mirror after
prepare or crash-recovery the segment file will still remain locked till
commit-prepared.


>
> * The segfile information, like which segfiles exist, tupcount and
> modcount, are not kept up-to-date in the master anymore. The pg_aoseg
> table in the master is always empty. It's no longer needed in the
> master, because the QE nodes manage them independently. The code related
> to sending tupcount/modcount information back from QE nodes to the
> master are gone.
>

I am not sure how that information was leveraged by Optimizer and Executor
and impacts due to same. Someone from QP should be able to help provide
answers on the same.

**Comment by ashwinstar** [comment]
On Sat, Aug 13, 2016 at 1:16 PM, Heikki Linnakangas <
notifications@github.com> wrote:
>
> Let's see if I understand this correctly:
>
> * The incremental backup is all-or-nothing at the partition level. If
> there have been any changes to a partition whatsoever, the whole
> partition is backed up.
>
> * The crux of deciding what needs to be backed up is this SQL query,
> from dump.py:
>
> select to_char(coalesce(sum(modcount::bigint), 0),
> '999999999999999999999') from %s.%s" % (catalog_schema, tupletable)
>

Yes, that's correct.


>
> That's executed on the master, and the table name is the AO segment
> table, i.e. pg_aoseg.pg_aoseg_12345.
>
> Hmm, yeah, this PR needs a bit of extra work to keep that working. Since
> we no longer store the modcounts in the master, the above query will
> always return zero. I think we can just throw a gp_dist_random() in
> there, to fetch the information from all the segments instead:
>
> select to_char(coalesce(sum(modcount::bigint), 0),
> '999999999999999999999') from gp_dist_random('%s.%s'" % (catalog_schema,
> tupletable)


Yup seems the way to go.

**Comment by hlinnaka** [comment]
On 08/16/2016 03:44 AM, Ashwin Agrawal wrote:
> On Thu, Aug 11, 2016 at 11:55 PM, Heikki Linnakangas <
> notifications@github.com> wrote:
>
>> * AO segment files are managed locally, in each QE node. If you start an
>> insert from the master, each QE independently chooses a target segfile
>> to route the inserts to. The algorithm for choosing the target segfile,
>> to ensure correct MVCC rules, is the same as before: The segfile must be
>> in "available" state, and the last transaction that inserted to the same
>> AO segment file must not have run concurrently with the current one. But
>> all those checks and the decision are made locally. Instead of
>> distributed transaction IDs, local XIDs are used for those checks.
>
> Using local XIDs for this check may yield incorrect results, as if
> distributed transaction T1 and T2 started together. T1 was assigned
> segment-file 1 and inserted data from offset 0-100 and committed, so lock
> is released. Then T2 starts on segment will also be assigned segment-file 1
> (which creates the problem). As if T2 writes from 100-200 offset and then
> reads the table, will return all rows from offset 0-200. So, to make this
> work need to reverse map local XID to distributed XID and then perform
> concurrency check same way it was performed earlier on master.

In that scenario, T2 would see that T1 ran concurrently with it (i.e. 
it's seen as in-progress by the transaction's first snapshot), and it 
would not choose segfile 1. That's what the 
usedByConcurrentTransaction() test is for.

I didn't understand how distributed transactions make a difference to 
that. Am I missing something?

- Heikki

**Comment by hlinnaka** [comment]
On 08/16/2016 03:44 AM, Ashwin Agrawal wrote:
> On Thu, Aug 11, 2016 at 11:55 PM, Heikki Linnakangas <
> notifications@github.com> wrote:
>
>> * Segfile #0 is no longer reserved for utility mode. It can and will be
>> chosen as insertion target, like any other segfile. Now that the
>> algorithm for choosing insertion target runs locally, utility mode
>> doesn't need any special treatment.
>
> Nice. So, I think then Alter will also be no more a special case where it
> used to push all the tuples to segfile 0. Which always worried me, like
> will we reach a day when Alter will hit the error of max row-number /
> tuples reached for segfile.

Hmm. Alter will still always use segfile 0. A (rewriting) ALTER always 
creates a new relfilenode from scratch. The algorithm will choose the 
first available segment, which will always be 0 when you're building the 
table from scratch.

>> * The in-shared-memory hash table is gone. It was used to decide which
>> AO segfile to insert to, and to remember the last XID that updated each
>> segfile (to avoid choosing a segment that was used "concurrently" (this
>> ties to the discussion on PR #1034). The pg_aoseg table is used directly
>> for that now. To choose the target segfile, the new code opens the
>> pg_aoseg table and scans it for the next available one. And to get the
>> last XID that inserted to a segfile, it looks at the pg_aoseg tuple's
>> xmin. To lock a segfile when you start inserting to it, the pg_aoseg
>> tuple is locked with heap_lock_tuple().
>
> I believe the lock is held till end of transaction and is getting persisted
> on Prepare transaction record. So, incase of failover to mirror after
> prepare or crash-recovery the segment file will still remain locked till
> commit-prepared.

Yes, it will remain locked.

(Strictly speaking, a lock on a heap tuple is taken by marking the 
tuple's XMAX, with a flag indicating that it's been locked rather than 
updated or deleted. So it's not included in the prepare transaction 
record per se, there's a separate WAL record for setting the xmax for 
locking purposes. But yes, the effect is the same, the lock survives a 
crash and recovery, if the transaction is prepared)

>> * The segfile information, like which segfiles exist, tupcount and
>> modcount, are not kept up-to-date in the master anymore. The pg_aoseg
>> table in the master is always empty. It's no longer needed in the
>> master, because the QE nodes manage them independently. The code related
>> to sending tupcount/modcount information back from QE nodes to the
>> master are gone.
>
> I am not sure how that information was leveraged by Optimizer and Executor
> and impacts due to same. Someone from QP should be able to help provide
> answers on the same.

The optimizer doesn't use tupcount, it relies on pg_class.reltuples for 
its number of rows estimate.

- Heikki

**Comment by ashwinstar** [comment]
On Tue, Aug 16, 2016 at 8:48 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 08/16/2016 03:44 AM, Ashwin Agrawal wrote:
> > On Thu, Aug 11, 2016 at 11:55 PM, Heikki Linnakangas <
> > notifications@github.com> wrote:
> >
> >> * AO segment files are managed locally, in each QE node. If you start an
> >> insert from the master, each QE independently chooses a target segfile
> >> to route the inserts to. The algorithm for choosing the target segfile,
> >> to ensure correct MVCC rules, is the same as before: The segfile must be
> >> in "available" state, and the last transaction that inserted to the same
> >> AO segment file must not have run concurrently with the current one. But
> >> all those checks and the decision are made locally. Instead of
> >> distributed transaction IDs, local XIDs are used for those checks.
> >
> > Using local XIDs for this check may yield incorrect results, as if
> > distributed transaction T1 and T2 started together. T1 was assigned
> > segment-file 1 and inserted data from offset 0-100 and committed, so lock
> > is released. Then T2 starts on segment will also be assigned
> segment-file 1
> > (which creates the problem). As if T2 writes from 100-200 offset and then
> > reads the table, will return all rows from offset 0-200. So, to make this
> > work need to reverse map local XID to distributed XID and then perform
> > concurrency check same way it was performed earlier on master.
>
> In that scenario, T2 would see that T1 ran concurrently with it (i.e.
> it's seen as in-progress by the transaction's first snapshot), and it
> would not choose segfile 1. That's what the
> usedByConcurrentTransaction() test is for.
>
> I didn't understand how distributed transactions make a difference to
> that. Am I missing something?


The earlier usage of usedByConcurrentTransaction was based on distributed
Xid and on master. Important property in play here is distributed
transaction concurrently on master doesn't mean its also running
concurrently on segment locally. Transactions can start and end on segments
in different order compared to master.
The case I mentioned above T1 committed and completed locally on segment
but yet to complete on master, when T2 starts. So for T2, distributed XID
of T1 will be in in-progress list but not the local XID. As when T2
acquires the local snapshot on segment, T1 has completed and hence will not
appear in-progress list. The earlier check in usedByConcurrentTransaction
was checking in-progress list of distributed XID in snapshot not local XID
and on master. If we move the check to segment reverse mapping is needed
from local to distributed and then checked in snapshots in-progress
distributed XIDs list not local xids. The check definitely becomes lot
heavier. Hope I was able to clarify the problem.

**Comment by hlinnaka** [comment]
On 08/17/2016 02:06 AM, Ashwin Agrawal wrote:
> On Tue, Aug 16, 2016 at 8:48 AM, Heikki Linnakangas <
> notifications@github.com> wrote:
>
>> In that scenario, T2 would see that T1 ran concurrently with it (i.e.
>> it's seen as in-progress by the transaction's first snapshot), and it
>> would not choose segfile 1. That's what the
>> usedByConcurrentTransaction() test is for.
>>
>> I didn't understand how distributed transactions make a difference to
>> that. Am I missing something?
>
> The earlier usage of usedByConcurrentTransaction was based on distributed
> Xid and on master. Important property in play here is distributed
> transaction concurrently on master doesn't mean its also running
> concurrently on segment locally. Transactions can start and end on segments
> in different order compared to master.
> The case I mentioned above T1 committed and completed locally on segment
> but yet to complete on master, when T2 starts. So for T2, distributed XID
> of T1 will be in in-progress list but not the local XID. As when T2
> acquires the local snapshot on segment, T1 has completed and hence will not
> appear in-progress list. The earlier check in usedByConcurrentTransaction
> was checking in-progress list of distributed XID in snapshot not local XID
> and on master. If we move the check to segment reverse mapping is needed
> from local to distributed and then checked in snapshots in-progress
> distributed XIDs list not local xids. The check definitely becomes lot
> heavier. Hope I was able to clarify the problem.

I see. Hmm. I guess we just need to follow the normal visibility rules 
for this, and the tqual machinery will do all the heavy lifting for us. 
I added a commit to the PR that does that (and rebased over master). 
Please have a look.

- Heikki

**Comment by ashwinstar** [comment]
On Wed, Aug 17, 2016 at 8:42 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 08/17/2016 02:06 AM, Ashwin Agrawal wrote:
> > On Tue, Aug 16, 2016 at 8:48 AM, Heikki Linnakangas <
> > notifications@github.com> wrote:
> >
> >> In that scenario, T2 would see that T1 ran concurrently with it (i.e.
> >> it's seen as in-progress by the transaction's first snapshot), and it
> >> would not choose segfile 1. That's what the
> >> usedByConcurrentTransaction() test is for.
> >>
> >> I didn't understand how distributed transactions make a difference to
> >> that. Am I missing something?
> >
> > The earlier usage of usedByConcurrentTransaction was based on distributed
> > Xid and on master. Important property in play here is distributed
> > transaction concurrently on master doesn't mean its also running
> > concurrently on segment locally. Transactions can start and end on
> segments
> > in different order compared to master.
> > The case I mentioned above T1 committed and completed locally on segment
> > but yet to complete on master, when T2 starts. So for T2, distributed XID
> > of T1 will be in in-progress list but not the local XID. As when T2
> > acquires the local snapshot on segment, T1 has completed and hence will
> not
> > appear in-progress list. The earlier check in usedByConcurrentTransaction
> > was checking in-progress list of distributed XID in snapshot not local
> XID
> > and on master. If we move the check to segment reverse mapping is needed
> > from local to distributed and then checked in snapshots in-progress
> > distributed XIDs list not local xids. The check definitely becomes lot
> > heavier. Hope I was able to clarify the problem.
>
> I see. Hmm. I guess we just need to follow the normal visibility rules
> for this, and the tqual machinery will do all the heavy lifting for us.
> I added a commit to the PR that does that (and rebased over master).
> Please have a look.


That part of code looks much better now. Don't we need to acquire lock
after InsertInitialSegnoEntry and its CO equivalent ? Hoping you are adding
tests while fixing these cases TDD ?

How does this work with sub-transactions ?

**Comment by ivannovick** [comment]
shall we close this and resubmit in the future if we have something we are ready to merge?

**Comment by pivotal-issuemaster** [comment]
@hlinnaka Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=790) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-mike** [comment]
@ashwinstar @hlinnaka Is the consensus that we close this PR?

**Comment by pivotal-issuemaster** [comment]
@hlinnaka Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=790)!

**Comment by asimrp** [comment]
This PR is superseded by PR #2242.  Hence closing.

**Pull request closed without merging**
