### PR TITLE
Use binaries from PivNet for binary_swap tests

### PR DESCRIPTION
**Pull request by bradfordboyle**
Instead of re-compiling from source at a release tag, the pipeline downloads a
released RPM from PivNet and transforms it to a tarball for use in binary_swap
tests.

Co-authored-by: Asim Praveen <apraveen@pivotal.io>
Co-authored-by: Bradford D. Boyle <bboyle@pivotal.io>

### CODE REVIEW

**Comment by bradfordboyle** [comment]
Before merging, re-generate the 6X_STABLE pipeline with these changes and re-set the pipeline.

**Comment by asimrp** [comment]
I realized after the fact, that we should create this PR on master first and back-port it to 6X.  Regardless, any feedback on this PR should be applicable to master as well, because the related code has not changed between the two branches.

**Comment by amilkh** [comment]
found this commit: https://github.com/pivotal/gp-continuous-integration/commit/e0dadc7415214e9b9ad50349987df8d78fe4743a

https://github.com/pivotal/gp-continuous-integration/commit/e0dadc7415214e9b9ad50349987df8d78fe4743a
maybe we should cherry pick changes to 6X_STABLE without_asserts secrets yml

Should we include binary-swap in the name of the variable `pivotal-gpdb-pivnet-product-version`, e.g. `pivotal-gpdb-pivnet-binary-swap-product-version`

w/ @marksliva

**Comment by jimmyyih** [comment]
This seems a tiny bit incorrect.  If I was fixing a binary swap issue (adding a test and fix for something that was missed) where I would have to unfortunately set the minimum binary swap version to my branch's HEAD, pivNet would not have that binary to test on a dev pipeline.  It's not always going to be 100% pivNet releases as the minimum binary swap version.

It only ever recompiles if the tag changes so why the needed change?  It's not explained in this PR.

**Comment by amilkh** [comment]
I think the reason for this PR is because the below job is orange because it relies on changes to gpdb_src which are newer than 6.0.0-beta.1:
https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE/jobs/compile_gpdb_binary_swap_centos6/builds/211

Also, pulling the beta.1 rpm released to customers seem like better pattern to me than recompiling based on the beta.1 tag gpdb_src.

**Comment by jimmyyih** [comment]
Let me try explaining better with an upcoming scenario.  Consider `6.0.0-beta.3` and `6.0.0-beta.4` where beta 4 has not been cut yet and is currently 6X_STABLE HEAD.  `6.0.0-beta.4` has a catalog update so using `6.0.0-beta.3` or lower as the binary_swap binary is no longer valid.  It will have to be `6.0.0-beta.4` if we've tagged or 6X_STABLE HEAD.  If this PR were to be committed, the 6X_STABLE pipeline will fail because it cannot pass binary swap tests without a `6.0.0-beta.4` binary.  A `6.0.0-beta.4` binary will not be produced until the 6X_STABLE pipeline passes (if the 6X release pipeline actually does produce a binary without caring about 6X_STABLE pipeline passing, our flow is wrong).  You end up with a chicken/egg scenario.

**Comment by bradfordboyle** [comment]
@jimmyyih Thanks for the explanation --- I agree that this is a chicken/egg problem.

An easy fix, is to temporarily add the `sync_tools` task back to the pipeline. But this creates scenario where the pipeline definition on 6X_STABLE contains references to a Concourse task that doesn't exist in 6X_STABLE.

Looking at the pipeline, it looks like we test the binary swap via `icw_planner_centos6` which is a release blocking job. Would it make sense to split the binary swap test into a separate test that we can remove from the list of release blockers when we expect the failure?

**Comment by asimrp** [comment]
Binary swap test should block a release on a stable branch.  When a branch is transitioning towards a stable branch (e.g. alpha and beta phase), there is a possibility of catalog change and thereby breaking binary swap test.  If the catalog change is intentional, may I suggest the following workflow?
1. Disable binary swap test.
2. Make the catalog change commit.
3. The commit will flow through the pipeline and make it eventually to Pivnet.
4. Pin the `pivotal_gpdb_pivnet_product_version` to the release generated in previous step.
5. Enable the binary swap test so subsequent commits are tested for binary compatibility against the pinned version.

**Pull request merged**
