### PR TITLE
Fix failure when DynamicSeqScan has a subPlan 

### PR DESCRIPTION
**Pull request by red1452**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by red1452** [comment]
## Problem description

The following scenario produces internal error:
```sql
CREATE TABLE ds_part ( a INT, b INT, c INT) PARTITION BY RANGE(c)( START(1) END (10) EVERY (2), DEFAULT PARTITION deflt);
CREATE TABLE non_part1 (c INT);
CREATE TABLE non_part2 (e INT, f INT);

INSERT INTO ds_part SELECT i, i, i FROM generate_series (1, 1000)i; 
INSERT INTO non_part1 SELECT i FROM generate_series(1, 100)i; 
INSERT INTO non_part2 SELECT i, i FROM generate_series(1, 100)i;

SET optimizer_enforce_subplans TO ON;
analyze ds_part;
analyze non_part1;
analyze non_part2;
EXPLAIN ANALYZE SELECT * FROM ds_part, non_part2 WHERE ds_part.c = non_part2.e AND non_part2.f = 10 AND a IN ( SELECT b + 1 FROM non_part1);
```
```
FATAL:  Unexpected internal error (assert.c:44)
DETAIL:  FailedAssertion("!(rsi->pstype == planstate->type && ns->segindex0 <= rsh->segindex && rsh->segindex < ns->segindex0 + ns->ninst)", File: "explain_gp.c", Line: 1024)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>
```

Query plan of select in example above contains SubPlan under DynamicSeqScan node:
```
postgres=# EXPLAIN (costs off) SELECT * FROM ds_part, non_part2 WHERE ds_part.c = non_part2.e AND non_part2.f = 10 AND a IN ( SELECT b + 1 FROM non_part1);
                                   QUERY PLAN                                   
--------------------------------------------------------------------------------
 Gather Motion 3:1  (slice4; segments: 3)
   ->  Hash Join
         Hash Cond: (ds_part.c = non_part2.e)
         ->  Dynamic Seq Scan on ds_part (dynamic scan id: 1)
               Filter: ((a = (b + 1)) AND (SubPlan 1))
               SubPlan 1  (slice4; segments: 3)
                 ->  Materialize
                       ->  Broadcast Motion 1:3  (slice2)
                             ->  Limit
                                   ->  Gather Motion 3:1  (slice1; segments: 3)
                                         ->  Limit
                                               ->  Seq Scan on non_part1
         ->  Hash
               ->  Partition Selector for ds_part (dynamic scan id: 1)
                     ->  Broadcast Motion 3:3  (slice3; segments: 3)
                           ->  Seq Scan on non_part2
                                 Filter: (f = 10)
 Optimizer: Pivotal Optimizer (GPORCA)
(18 rows)
```

While gathering execution statistics of EXPLAIN ANALYZE from QE for slice4:
```
 Gather Motion 3:1  (slice4; segments: 3)
   ->  Hash Join
         Hash Cond: (ds_part.c = non_part2.e)
         ->  Dynamic Seq Scan on ds_part (dynamic scan id: 1)
               Filter: ((a = (b + 1)) AND (SubPlan 1))
               SubPlan 1  (slice4; segments: 3)
                 ->  Materialize
                       ->  Broadcast Motion 1:3  (slice2)
         ->  Hash
               ->  Partition Selector for ds_part (dynamic scan id: 1)
                     ->  Broadcast Motion 3:3  (slice3; segments: 3)
```

we traverse plan nodes in depth-first order and bump into inappropriate order of received messages: at `cdbexplain_depositStatsToNode` macro `Insist` fails at condition `rsi->pstype == planstate->type`. In particular, we have duplicate messages for Materialize and Broadcast Motion nodes.

```
(gdb) p ctx->msgptrs[0]->inst[1]
$80 = {pstype = T_DynamicSeqScanState, starttime = {tv_sec = 0, tv_usec = 0}, counter = {tv_sec = 0, tv_usec = 0}, firsttuple = 0, startup = 0.000301, total = 0.000301, ntuples = 0, nloops = 1, execmemused = 0, workmemused = 0, 
  workmemwanted = 0, workfileCreated = 0 '\000', firststart = {tv_sec = 1659499436, tv_usec = 21285}, peakMemBalance = 55000, numPartScanned = 1, sortMethod = UNINITIALIZED_SORT, sortSpaceType = UNINITIALIZED_SORT_SPACE_TYPE, 
  sortSpaceUsed = 0, bnotes = 61, enotes = 61}
(gdb) p ctx->msgptrs[0]->inst[2]
$81 = {pstype = T_MaterialState, starttime = {tv_sec = 0, tv_usec = 0}, counter = {tv_sec = 0, tv_usec = 0}, firsttuple = 0, startup = 0, total = 0, ntuples = 0, nloops = 0, execmemused = 0, workmemused = 0, workmemwanted = 0, 
  workfileCreated = 0 '\000', firststart = {tv_sec = 0, tv_usec = 0}, peakMemBalance = 3368, numPartScanned = 0, sortMethod = UNINITIALIZED_SORT, sortSpaceType = UNINITIALIZED_SORT_SPACE_TYPE, sortSpaceUsed = 0, bnotes = 61, 
  enotes = 61}
(gdb) p ctx->msgptrs[0]->inst[3]
$82 = {pstype = T_MotionState, starttime = {tv_sec = 0, tv_usec = 0}, counter = {tv_sec = 0, tv_usec = 0}, firsttuple = 0, startup = 0, total = 0, ntuples = 0, nloops = 0, execmemused = 0, workmemused = 0, workmemwanted = 0, 
  workfileCreated = 0 '\000', firststart = {tv_sec = 0, tv_usec = 0}, peakMemBalance = 3520, numPartScanned = 0, sortMethod = UNINITIALIZED_SORT, sortSpaceType = UNINITIALIZED_SORT_SPACE_TYPE, sortSpaceUsed = 0, bnotes = 61, 
  enotes = 61}
(gdb) p ctx->msgptrs[0]->inst[4]
$83 = {pstype = T_MaterialState, starttime = {tv_sec = 0, tv_usec = 0}, counter = {tv_sec = 0, tv_usec = 0}, firsttuple = 0, startup = 0, total = 0, ntuples = 0, nloops = 0, execmemused = 0, workmemused = 0, workmemwanted = 0, 
  workfileCreated = 0 '\000', firststart = {tv_sec = 0, tv_usec = 0}, peakMemBalance = 3368, numPartScanned = 0, sortMethod = UNINITIALIZED_SORT, sortSpaceType = UNINITIALIZED_SORT_SPACE_TYPE, sortSpaceUsed = 0, bnotes = 61, 
  enotes = 61}
(gdb) p ctx->msgptrs[0]->inst[5]
$84 = {pstype = T_MotionState, starttime = {tv_sec = 0, tv_usec = 0}, counter = {tv_sec = 0, tv_usec = 0}, firsttuple = 0, startup = 0, total = 0, ntuples = 0, nloops = 0, execmemused = 0, workmemused = 0, workmemwanted = 0, 
  workfileCreated = 0 '\000', firststart = {tv_sec = 0, tv_usec = 0}, peakMemBalance = 3520, numPartScanned = 0, sortMethod = UNINITIALIZED_SORT, sortSpaceType = UNINITIALIZED_SORT_SPACE_TYPE, sortSpaceUsed = 0, bnotes = 61, 
  enotes = 61}
(gdb) p ctx->msgptrs[0]->inst[6]
$85 = {pstype = T_HashState, starttime = {tv_sec = 0, tv_usec = 0}, counter = {tv_sec = 0, tv_usec = 0}, firsttuple = 0, startup = 0.001132, total = 0.001132, ntuples = 1, nloops = 1, execmemused = 0, workmemused = 0, 
  workmemwanted = 0, workfileCreated = 0 '\000', firststart = {tv_sec = 1659499436, tv_usec = 20153}, peakMemBalance = 2104040, numPartScanned = 0, sortMethod = UNINITIALIZED_SORT, sortSpaceType = UNINITIALIZED_SORT_SPACE_TYPE, 
  sortSpaceUsed = 0, bnotes = 61, enotes = 61}
```

This is because QE executing slice4 initializes two identical subplans for DynamicSeqScan node:
```
(gdb) p *((SubPlanState *)lsecond(planstate->subPlan))
$7 = {xprstate = {type = T_SubPlanState, expr = 0x5566209fb4b0, evalfunc = 0x5566191cb820 <ExecSubPlan>}, planstate = 0x5566209df100, testexpr = 0x0, args = 0x0, curTuple = 0x0, curArray = 0, projLeft = 0x0, projRight = 0x0, 
  hashtable = 0x0, hashnulls = 0x0, havehashrows = 0 '\000', havenullrows = 0 '\000', hashtablecxt = 0x0, hashtempcxt = 0x0, innerecontext = 0x0, keyColIdx = 0x0, tab_hash_funcs = 0x0, tab_eq_funcs = 0x0, lhs_hash_funcs = 0x0, 
  cur_eq_funcs = 0x0, ts_pos = 0x0, ts_state = 0x556620b24698}
(gdb) p *((SubPlanState *)linitial(planstate->subPlan))
$8 = {xprstate = {type = T_SubPlanState, expr = 0x5566209fb4b0, evalfunc = 0x5566191cb820 <ExecSubPlan>}, planstate = 0x5566209df100, testexpr = 0x0, args = 0x0, curTuple = 0x0, curArray = 0, projLeft = 0x0, projRight = 0x0, 
  hashtable = 0x0, hashnulls = 0x0, havehashrows = 0 '\000', havenullrows = 0 '\000', hashtablecxt = 0x0, hashtempcxt = 0x0, innerecontext = 0x0, keyColIdx = 0x0, tab_hash_funcs = 0x0, tab_eq_funcs = 0x0, lhs_hash_funcs = 0x0, 
  cur_eq_funcs = 0x0, ts_pos = 0x0, ts_state = 0x556620b10f80}
```

The fist subplan item is initialized at [executor start](https://github.com/greenplum-db/gpdb/blob/c4a3ce097f554a15ef489630928f03d19e129b39/src/backend/executor/nodeDynamicSeqscan.c#L53-L58). The second one - at execution of DynamicSeqScan node [in initNextTableToScan](https://github.com/greenplum-db/gpdb/blob/c4a3ce097f554a15ef489630928f03d19e129b39/src/backend/executor/nodeDynamicSeqscan.c#L150-L163). This duplication was caused by commit https://github.com/greenplum-db/gpdb/commit/c4a3ce097f554a15ef489630928f03d19e129b39 that added initialization of quals and targetlist at executor start alongside initialization at running stage.

Another issue with second subplan initialization is that this subplan structure is allocated in temporary memory context `partitionMemoryContext`. In particular, after targetlist remapping we end up to dangling pointer in list of subplans:
```
postgres=# create table ds2 (a int, a1 int, b int, c int);
create table ds3 (a int, b int, b1 int, c int);
alter table ds2 drop column a1;
alter table ds3 drop column b1;
alter table ds_part exchange partition for (1) with table ds2;
alter table ds_part exchange partition for (2) with table ds3;
INSERT INTO ds_part SELECT i, i, i FROM generate_series (1, 1000)i; 
EXPLAIN ANALYZE SELECT * FROM ds_part, non_part2 WHERE ds_part.c = non_part2.e AND non_part2.f < 10 AND a IN ( SELECT b + 1 FROM non_part1);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
INSERT 0 1000
ERROR:  Unexpected internal error (list.c:54)  (seg0 slice4 127.0.1.1:6002 pid=41068) (list.c:54)
DETAIL:  FailedAssertion("!(list->tail->next == ((void *)0))", File: "list.c", Line: 54)
HINT:  Process 41068 will wait for gp_debug_linger=120 seconds before termination.
```

## Patch details

Remapping of attributes doesn't require valuable changes in qual list and targetlist after substitution of variables in expression tree. Also initialization of these structures at execution of DynamicSeqScan changes nothing compared to initial initialization routine at executor start. This was checked on query with explicit subplan external parameter from partitioning table:
```sql
SELECT *
FROM ds_part, non_part2
WHERE ds_part.c = non_part2.e AND non_part2.f = 10
      AND a IN (
           SELECT b + 1
           FROM non_part1
           WHERE ds_part.c = non_part1.c
      );
```

Because of this I have removed the second initalization of routine in `initNextTableToScan`.
Also I fixed the same problem at DynamicBitmapHeapscan.

## Affected version

adb-6.x
master

**Review by chrishajas — APPROVED** [review]
This looks good! Thanks for the detailed explanation. I'm surprised this only showed up during explain. I also don't see this code in nodeDynamicIndexScan, so we should be good there.

Also, the ICW failure in CI looks to just be an unrelated flake.

**Review by gpopt — APPROVED** [review]
+1

**Comment by chrishajas** [comment]
Pushed to main, thanks! If this also exists in 6X please create a PR and we can merge it there too

**Comment by red1452** [comment]
> Pushed to main, thanks! If this also exists in 6X please create a PR and we can merge it there too

Thanks! I will create PR to 6X today or tomorrow.

**Comment by red1452** [comment]
> > Pushed to main, thanks! If this also exists in 6X please create a PR and we can merge it there too
> 
> Thanks! I will create PR to 6X today or tomorrow.

[PR to 6X_STABLE](https://github.com/greenplum-db/gpdb/pull/14591)

**Pull request merged**
