### PR TITLE
Don't use the relation cache of foreign tables

### PR DESCRIPTION
**Pull request by adam8157**
Foreign tables' policy depends on the foreign server even the wrapper's
options, don't use relation and its policy in the cache.

This is a quick fix and will refactor to avoid performance loss.

### CODE REVIEW

**Comment by adam8157** [comment]
CI without asserts noticed this issue, so it's already covered by the test.

**Comment by kainwen** [comment]
> CI without asserts noticed this issue, so it's already covered by the test.

Can you elaborate more on detailed issues hitted?

**Comment by adam8157** [comment]
> > CI without asserts noticed this issue, so it's already covered by the test.
> 
> Can you elaborate more on detailed issues hitted?

Sure, for instance, the `num_segments` option only exists for foreign servers, but the foreign table's policy depends on it. If the user alters the server's `num_segments` option, the policy will be different correspondingly, but Greenplum still provides the old policy which is stored in the relation cache since the table's catalog never changed.

Will have this in the commit message.

**Comment by avamingli** [comment]
> Don't use the relation cache of foreign tables

`Don't use` sounds we never put it in rel cache. But...is it possible that we don't cache foreign relations in RelationIdGetRelation()

**Comment by kainwen** [comment]
This code change make foreign table's relation cache invalid every time, just sort of like what we need under Assert (currently, under Assert the macro `RELCACHE_FORCE_RELEASE` will be defined).

The core problem is, options in server impact plan and impact the most important part of plan in Greenplum.
I don't think  (am not sure) Postgres will have such kind of impact. 

So for Postgres code, `alter server` will not do any cache invalidation things of other backends' relcache.

------

* this patch's code
* without this patch's code but with cassert

both of the above two situations will have the following problem on foreign table plan:

```
-- transaction 1
-- use gdb to break at `RelationIdGetRelation` if relationId > 16384
explain select * from tf;
-- during the above SQL execution, it will execute several times of `RelationIdGetRelation` for the table `tf`
-- 1st time, it sees numsegments = 4
-- now hold the gdb, open a new transaction


-- transaction 2
alter server postgres_server options (set num_segments '400');

-- now back to gdb, use continue command to hit the breakpoint 2nd time
-- you will ses numsegments become to 400

-- now in new transaction 3
alter server postgres_server options (set num_segments '900');

-- then back to gdb use continue command to hit the breakpoint 3nd time
-- you will see numsegments become to 900
```

All the numbers you are seeing it in a single query's `exec_simple_query`.

-------

NOTE: the same phenomenon can also be found for any tables in GPDB, while the other transactions using `update gp_distribution_policy set numsegments = xxx`. But never for `alter table set distributed`. 

This is because `alter table` will send invalidate cache message out for other backends.

--------

So I think in GPDB, we might consider at the end of commit of alter server, clear all forein table's cache.

**Comment by adam8157** [comment]
new and better solution: https://github.com/greenplum-db/gpdb/pull/16082

**Pull request closed without merging**
