### PR TITLE
Retire threaded dispatcher

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
Now there is only the async dispatcher.  The dispatcher API interface is
kept so we might add new backend in the future.

The GUC gp_connections_per_thread is also retired which was used to
switch between the async and threaded backends.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Cool!

Some more stuff that can now be removed:
* cdbdisp_appendMessage()
* mutex usage in  cdbdisp_seterrcode()
* WRITE_LOG_DISPATCHER_DEBUG macro
* cdbconn_doConnect()
* cdbdisp_onProcExit
* `errcode` and `error_message` fields in `SegmentDatabaseDescriptor`

**Comment by ashwinstar** [comment]
Thank You :+1:

**Comment by pivotal-ning-yu** [comment]
Sorry for the late reply, pushed a commit to retire more unused functions/fields.

We kept `cdbdisp_onProcExit()` in the code as we want to keep the API interfaces, in the future we might add new dispatch backends.

**Comment by hlinnaka** [comment]
On 15 October 2018 06:33:34 EEST, Ning Yu <notifications@github.com> wrote:
>We kept `cdbdisp_onProcExit()` in the code as we want to keep the API
>interfaces, in the future we might add new dispatch backends.

Nah, please remove that, too. I hope that any future dispatcher we might add will not use that hack. There's a generic facility to register exit callbacks, which should be used instead.


- Heikki

**Comment by pivotal-ning-yu** [comment]
On Mon, Oct 15, 2018 at 12:45 PM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 15 October 2018 06:33:34 EEST, Ning Yu <notifications@github.com>
> wrote:
> >We kept `cdbdisp_onProcExit()` in the code as we want to keep the API
> >interfaces, in the future we might add new dispatch backends.
>
> Nah, please remove that, too. I hope that any future dispatcher we might
> add will not use that hack. There's a generic facility to register exit
> callbacks, which should be used instead.


Makes sense, will retire it.

**Comment by pivotal-ning-yu** [comment]
A commit was pushed to retire `cdbdisp_onProcExit()`.

**Comment by pivotal-ning-yu** [comment]
The pipeline is green, will merge it on master now.  Thanks for all the reviews.

**Pull request merged**
