### PR TITLE
Add protection and small code refactor for gp_fastsequence

### PR DESCRIPTION
**Pull request by ashwinstar**
The commit message provides details for the included commits.

### CODE REVIEW

**Review by SmartKeyerror — COMMENTED** [review]
This looks fine to me. Just have some above minor questions.

Besides, this PR will fix #13699 too. 

And we shoud write detailed merge commit messages to make it clearer to others what the current PR is doing, and what changed.

**Comment by ashwinstar** [comment]
> Besides, this PR will fix #13699 too.

This will avoid the issue yes. Though will not call it a fix :-) as will continue to bump the sequence across truncates and not clean either. So, I will prefer we commit the fix in PR https://github.com/greenplum-db/gpdb/pull/13762 as a real fix for that issue. This PR is only intended to provide code cleanup and extra added protection to avoid issues in future, not really as fix for #13699

**Comment by SmartKeyerror** [comment]
> Plus, I am not even planning to backport this refactor PRs to 6X_STABLE.

Does it because this will not reset the `last_sequence` when we truncate the table?

> I made my best effort via commit messages to do the job. Am I missing something there?

Sorry for that, I missed the separated commit message, my fault _(:з」∠)_

**Comment by ashwinstar** [comment]
>> Plus, I am not even planning to backport this refactor PRs to 6X_STABLE.
>
> Does it because this will not reset the last_sequence when we truncate the table?

These are pure refactors to make life easy for future modifications / enhancements / edits to code and hence doesn't fit the criteria to backport code to STABLE branches as not fixing something. And yes I don't like this as solution (just code enhancement) to #13699  when we have much better solution in #13762 to help fix the issue.

**Comment by SmartKeyerror** [comment]
> These are pure refactors to make life easy for future modifications / enhancements / edits to code and hence doesn't fit the criteria to backport code to STABLE branches as not fixing something. And yes I don't like this as solution (just code enhancement) to #13699 when we have much better solution in #13762 to help fix the issue.

Get it, thanks for the refactoring, it's cleaner now. 

I will close the PR to master and reopen a PR to backport #13762 to 6X.

**Pull request closed without merging**
