### PR TITLE
Integrate S3 readable external table extentions.

### PR DESCRIPTION
**Pull request by lij55**
This is first release and doesn't support write operation.
S3 has its own unittest with gtest

Detailed history can be found here: https://github.com/lij55/gps3ext

### CODE REVIEW

**Comment by ivannovick** [comment]
Are there any known bugs or defects in this version.  Were you able to complete all the testing including cancel query and SSL?

**Comment by hlinnaka** [comment]
Oh dear, this is a lot of code, and a lot of bad high-level design decisions. At a quick glance:

* Needs to be rewritten in C rather than C++. There are a lot of problems with interfacing C++ code into PostgreSQL/GPDB. The ORCA guys have managed to make it work, but it comes at a high cost: you need to control the interactions between the C++ code and backend code carefully, mainly to avoid exceptions from being thrown across the boundary, and memory handling gets tricky too. Since we're developing in the green field, we definitely should not go down that error-prone path, and should just use plain C.
* Using threading is also a bad idea. The backend code is not generally thread-safe, so you again have to very carefully control all interactions between backend code, and code that uses threads. Much much simpler to just not go there. 
* Should use the existing cmockery or pg_regress test frameworks for testing, instead of introducing yet another framework

All in all, if I have any say in this, there's zero chance of this being accepted in its current form. Let's backtrack to design phase, and try to define what we're trying to accomplish, and then come up with a design that's maintainable in the long term. As a hint for the future, you *really* should discuss design of major features like this on the gpdb-dev mailing list before starting the implementation. It would save a lot of hassle for everyone.

What are the functional requirements for this? Which features need to be included in the first version? What features do we foresee to support in the future?

What are the non-functional requirements? What kind of performance do we expect out of this? How should it behave on various error scenarios, like network errors?

**Comment by lij55** [comment]
Hi @ivannovick 
Currently, the only known issue about SSL (and curl) is slightly memory leak in libssl and libcurl library, which won't increase with downloading data. I think it is safe to release.
For cancel query, we can't fix it in a quick way so we create a tracker story for it. It might have effect on all custom protocol.

**Comment by lij55** [comment]
Hi @hlinnaka 

Sorry for late reply because of spring festaval...

This is a quick answer for what you worry the most. We do have reasons for them, in other word, almost no choice...

In short, we need to support data saved on S3 as our data source. We decide to implement it in external table similar as gpfist and gphdfs.

Our original code is implemented in pure C. The reason we chagned to C++ is that the official SDK provided by Amazon is in C++ (full of classes and templates). S3 depends on a lot of other AWS servcies for advanced features, like access control, encryption, index, etc. It would be much more difficult if we implement API of every service by ourselves. Those APIs are more complex than first glance. Porting needed feature from official SDK can save a lot of efforts for both developement and test.

Because we need to test c++ code, gtest is a better choice than cmockery after comparaiton. We don't imtegrate our test to pg_regress/install-check because of S3 account credential. We create unit test for all classes and functions in S3 extention and try our best to avoid thread-unsafe functions.

For thread, if we don't use background thread to download, when GPDB read 64K byte data from external read function each time, we need to send a https request to S3 and fetch data to feed GPDB. Performance would be extremly bad. We download data to a buffer in background and give data to GPDB through read funciton.
For background download, we use multi-thread with curl_easy_* APIs. The curl_multi_* API can achieve same goal but introduce complex code.

**Comment by hlinnaka** [comment]
On 15/02/16 04:46, Jasper Li wrote:
> Our original code is implemented in pure C. The reason we chagned to
> C++ is that the official SDK provided by Amazon is in C++ (full of
> classes and templates). S3 depends on a lot of other AWS servcies for
> advanced features, like access control, encryption, index, etc. It
> would be much more difficult if we implement API of every service by
> ourselves. Those APIs are more complex than first glance. Porting
> needed feature from official SDK can save a lot of efforts for both
> developement and test.

Which SDK is that? I don't see any references to any outside SDK in the 
code or the build scripts.

> For thread, if we don't use background thread to download, when GPDB
> read 64K byte data from external read function each time, we need to
> send a https request to S3 and fetch data to feed GPDB. Performance
> would be extremly bad. We download data to a buffer in background and
> give data to GPDB through read funciton. For background download, we
> use multi-thread with curl_easy_* APIs. The curl_multi_* API can
> achieve same goal but introduce complex code.

The curl_multi_* API isn't that complex. Certainly not as complex as 
introducing multi-threading into the backend.

- Heikki

**Comment by lij55** [comment]
Official SDK is https://github.com/awslabs/aws-sdk-cpp. We don't use external library now. We will port code from this SDK.

**Comment by hlinnaka** [comment]
On 15/02/16 09:38, Jasper Li wrote:
> Official SDK is https://github.com/awslabs/aws-sdk-cpp. We don't use external library now. We will port code from this SDK.

What exactly do mean by porting code from that?

- Heikki

**Comment by lij55** [comment]
Even we can solve concurrency downloading through curl_multi_* API regardless of the complexity,  additional thread is also required because it still need to download data continually in background.

**Comment by lij55** [comment]
The next feature we would port is "V4 signature". We only implement V2 signature, which is old. In order to support all region of S3, V4 signature is required.
Tracker is https://www.pivotaltracker.com/story/show/112025571 .

The other feature that might need porting is "list bucket" operation of S3. Currently we only support less than 1000 files.

In long term, we need to access IAM service of AWS to obtain temp token to access private data. (customer has already required ...)

**Comment by hlinnaka** [comment]
On 15/02/16 09:50, Jasper Li wrote:
> The next feature we would port is "V4 signature". We only implement V2 signature, which is old. In order to support all region of S3, V4 signature is required.
> Tracker is https://www.pivotaltracker.com/story/show/112025571 .
>
> The other feature that might need porting is "list bucket" operation of S3. Currently we only support less than 1000 files.
>
> In long term, we need to access IAM service of AWS to obtain temp token to access private data. (customer has already required ...)

How are you planning to "port" those features from the official C++ SDK?

- Heikki

**Comment by lij55** [comment]
> How are you planning to "port" those features from the official C++ SDK?

Source code level ... 

Official SDK is huge, depends on cmake and not very easy to use. It doesn't support concurrent downloading either.  This is the reason why I decide to port some feature from it instead of use it directly.

Even if we use it directly, it is also required to call those API in C++ code.

**Comment by wangzw** [comment]
Interconnect module use working thread to transfer data as far as I know. Thread will work well if we code very carefully. It does not means I support to introduce threading into GPDB. But we should compare the complexity between threading and curl_multi_* API.  curl_multi_* API is not much easy to use in my opinion.

Wrapper third party C++ SDKs or reimplement them with C are bad. People have to pay much time to maintain the C version and reimplement new features of C++ version. It make GPDB wait a long time to use new features provided by C++ SDKs. It is error-prone since we become the only user of C version SDKs.

Apache HAWQ use C++ code aggressively. Avoiding exceptions from being thrown across the boundary is not problem. And ORCA has given an example of memory handling. If the C++ code does not use much memory, memory handling can become much simpler by using malloc and bypass palloc and memory accounting (just like interconnect module did).

**Comment by yydzero** [comment]
+1 for Zhanwei's comments.

C++ exception is not a problem once we catch all exceptions and handle them
in C++ code. C code just call a C++ method as a pure c function. In terms
of memory handling, GPText has used C++ UDF also and overload new/delete
operator to allocate memory using palloc instead of malloc.

Multiple-threading is bit complex while as what we have done in many code
like dispatcher/interconnect, it is not blocker.

Regards,
Yandong

On Mon, Feb 15, 2016 at 4:38 PM, Zhanwei Wang <notifications@github.com>
wrote:

> Interconnect module use working thread to transfer data as far as I know.
> Thread will work well if we code very carefully. It does not means I
> support to introduce threading into GPDB. But we should compare the
> complexity between threading and curl_multi_* API. curl_multi_* API is not
> much easy to use in my opinion.
>
> Wrapper third party C++ SDKs or reimplement them with C are bad. People
> have to pay much time to maintain the C version and reimplement new
> features of C++ version. It make GPDB wait a long time to use new features
> provided by C++ SDKs. It is error-prone since we become the only user of C
> version SDKs.
>
> Apache HAWQ use C++ code aggressively. Avoiding exceptions from being
> thrown across the boundary is not problem. And ORCA has given an example of
> memory handling. If the C++ code does not use much memory, memory handling
> can become much simpler by using malloc and bypass palloc and memory
> accounting (just like interconnect module did).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/pull/339#issuecomment-184112770>.
>



-- 
Best Regards,
Yandong

**Comment by hlinnaka** [comment]
On 15/02/16 14:52, Yandong Yao wrote:
> +1 for Zhanwei's comments.
>
> C++ exception is not a problem once we catch all exceptions and handle them
> in C++ code. C code just call a C++ method as a pure c function. In terms
> of memory handling, GPText has used C++ UDF also and overload new/delete
> operator to allocate memory using palloc instead of malloc.

I believe you also need to about backend functions throwing errors with 
elog(), while you're running C++ code. You can make it work, but you 
have to be very very careful through the code. You end up with very 
brittle code. Much better to avoid the problem in the first place, and 
not use C++.

> Multiple-threading is bit complex while as what we have done in many code
> like dispatcher/interconnect, it is not blocker.

I strongly disagree. The threading is not needed here, so let's avoid 
adding that complexity and not use threading.

- Heikki

**Comment by lij55** [comment]
> The threading is not needed here, so let's avoid adding that complexity and not use threading.

If the reason that you disagree with thread is complexity, there is no need to worry. The producer-consumer model is very mature and easy to understand and debug. I don't think it would be more complex than asynchronize event model in single thread.

There is at least one additional download thread is required. It downloads data to local buffer and GPDB get data from this local buffer. I don't think there is better solution without threading.
Or GPDB must issue http request and download 64K byte of data from S3 server each time, which is expensive and heavily over-headed.

**Comment by danielgustafsson** [comment]
I haven't had the time to read all the code yet so it might be obvious, but, what is being continually downloaded in the background thread mentioned? Is is pre-fetching?

**Comment by lij55** [comment]
>  Is is pre-fetching?

Prefetching.

**Comment by yydzero** [comment]
On Mon, Feb 15, 2016 at 9:00 PM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 15/02/16 14:52, Yandong Yao wrote:
> > +1 for Zhanwei's comments.
> >
> > C++ exception is not a problem once we catch all exceptions and handle
> them
> > in C++ code. C code just call a C++ method as a pure c function. In terms
> > of memory handling, GPText has used C++ UDF also and overload new/delete
> > operator to allocate memory using palloc instead of malloc.
>
> I believe you also need to about backend functions throwing errors with
> elog(), while you're running C++ code. You can make it work, but you
> have to be very very careful through the code. You end up with very
> brittle code. Much better to avoid the problem in the first place, and
> not use C++.
>
> > Multiple-threading is bit complex while as what we have done in many code
> > like dispatcher/interconnect, it is not blocker.
>
> I strongly disagree. The threading is not needed here, so let's avoid
> adding that complexity and not use threading.
>

My point is that C++ and threading code could work greatly as many code has
demostrated in both GPDB and HAWQ. And discussions here will not scare our
GPDB/HAWQ users because we have used C++ and multi-threading.  While I am
not encouraging everyone to use C++ and multi-threading, and I agree with
you we should avoid that in terms of simplicity if there is better
alternative.

While for this case, team actually has used C for the first version and
soon decided to move to C++ as S3 official SDK is C++ and there is no good
C equivalent. We don't want to reinvent wheels especially when the efforts
is huge. Eg: the authentication and encryption mechanism in S3 is pretty
complex and we don't want to reimplement that by ourselves and maintain
those code will be nightmare.

If you have better idea for this problem, would love to discuss those
alternatives.  One alternative is move those C++ code as a standalone
process, backend communicate with this process using pipe. While I don't
really think it worthy of the efforts.


>
> - Heikki
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/pull/339#issuecomment-184196639>.
>



-- 
Best Regards,
Yandong

**Comment by wangzw** [comment]
It is much important to make it work than make it prefect at first. Current solution looks the tradeoff between code complexity, performance and maintainability. 

Such discussion happened many times before for other modules(dispatcher, interconnect). And the conclusion was make it work first and improve it if it get trouble. Some pioneers tried many times to pursue "perfect" solutions to improve these modules and failed at last. So it make the current solutions "perfect" in some view of point.

Instead of "do not do something", it is more constructive to propose a better solution, post the design and demo the code.

**Comment by hlinnaka** [comment]
(trying to understand how this works now, to see what it'll take to rewrite this...)

S3Uploader.cpp isn't included in the Makefile. Is it dead code? What exactly is the functionality that this implements ATM? Is there documentation for this somewhere?

**Comment by lij55** [comment]
Hi @hlinnaka 
Upload feature is under development. For S3, we need to support both readable and writable external table.  Readable table download data from S3 and Writable table upload data to S3.

Because we changed our release plan, upload feature is not finished so we don't build them now.

For design doc, because we change our implementing code very frequently, there is no doc describing the details. 
Goal is effectively and concurrently downloading from / uploading to S3.

**Comment by lij55** [comment]
Push to release first.
Find better solution later.

**Pull request closed without merging**
