### PR TITLE
Submodule update to keep all urls consistent.

### PR DESCRIPTION
**Pull request by Chibin**

### CODE REVIEW

**Comment by hlinnaka** [comment]
that's fine as far as it goes, but we really should move all those other repositories to github too...

**Comment by Chibin** [comment]
Yes... there's a story in the backlog to do all that migration work.

**Comment by fire** [comment]
Are these repositories openly accessible?

**Comment by edespino** [comment]
@fire - Except for a few which we cannot expose due to contractual reasons, we will be publishing the majority of our repositories soon.

**Pull request closed without merging**
