### PR TITLE
Upgrade OpenSSL to 1.0.2l

### PR DESCRIPTION
**Pull request by adam8157**
0.9.8 is EOL, 1.0+ version has many security and performance improvements.

### CODE REVIEW

**Comment by adam8157** [comment]
@danielgustafsson @hlinnaka any potential risks you have in mind?

**Comment by hlinnaka** [comment]
Nope, go for it.

**Comment by pivotal-mike** [comment]
@adam8157 are there plans to pull the TAP framework into GPDB5 ?

**Comment by hlinnaka** [comment]
On 07/11/2017 05:45 PM, Michael Roth wrote:
> @adam8157 are there plans to pull the TAP framework into GPDB5 ?

See https://github.com/greenplum-db/gpdb/pull/2765

- Heikki

**Pull request merged**
