### PR TITLE
Enable for partitioned tables to use column-wise statistics setting

### PR DESCRIPTION
**Pull request by maksm90**
## Problem description
The analyze routine for partitioned table is based on merging statistics from its child tables. And building routines for MCV and histogram bounds collections explicitly use the default_statistics_target value as the number of slots for these structures ignoring the similar higher priority column-wise setting assigned via ALTER TABLE ... ALTER COLUMN ... SET STATISTICS ... statement.

Besides of main fix of upper function calls (`aggregate_leaf_partition_MCVs` and `aggregate_leaf_partition_histograms`) there was fixed the definition of upper bound of minimal frequency (expressed in terms of estimated count of rows having target value of attribute) for MCV values gotten from partitions. Also I have made light refactoring into that routine.

## Steps to reproduce

```sql
-- create partitioned table with 2 partitions
CREATE TABLE foo (a int) PARTITION BY RANGE (a) (START (0) END (1000) EVERY (500));
-- fill in foo with even numbers twice as large than odd ones
-- to avoid fully even distribution of 'a' attribute and hence empty MCV/MCF
INSERT INTO foo SELECT i%1000 FROM generate_series(0, 10000) i;
INSERT INTO foo SELECT i%1000 FROM generate_series(0, 10000) i WHERE i%2 = 0;
-- default_statistics_target is 100 by default
ALTER TABLE foo ALTER COLUMN a SET STATISTICS 50;
ANALYZE foo;
-- the lengths of MCV, MCF and number of histogram bounds are 100, 100 and 101 correspondingly -
-- values incurred from default_statistics_target setting,
-- not 50, 50 and 51 as appointed in previous ALTER TABLE ALTER COLUMN SET STATISTICS statement
SELECT
    array_length(most_common_vals, 1),
    array_length(most_common_freqs, 1),
    array_length(histogram_bounds, 1)
FROM pg_stats
WHERE tablename = 'foo' AND attname = 'a';
```

## Affected versions

master, 6X

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by kainwen — APPROVED** [review]

**Comment by kainwen** [comment]
The concourse failed because of the ans file when optimizer = on, is not updated.

**Comment by maksm90** [comment]
> The concourse failed because of the ans file when optimizer = on, is not updated.

Thanks, added.

**Comment by kainwen** [comment]
Merged, thanks.

**Comment by maksm90** [comment]
Thanks, added backport PR to 6X

**Pull request merged**
