### PR TITLE
Change icon of windows tool

### PR DESCRIPTION
**Pull request by pf-qiu**

### CODE REVIEW

**Comment by lij55** [comment]
Add some comments:

This ico contain 8 png format of greenplum oss logo for different resolution.

**Comment by danielgustafsson** [comment]
I don't mind the change, since I assume we are replacing an upstream logo with a Greenplum logo, but can you share a screenshot or some form of png of what it looks like? I'm mostly curious.

**Comment by pf-qiu** [comment]
Hi, @danielgustafsson . I've uploaded a screenshot of client binaries with new icon.
image

**Comment by danielgustafsson** [comment]
Thanks @pf-qiu!

**Pull request merged**
