### PR TITLE
Create TINC source tarball in concourse.

### PR DESCRIPTION
**Pull request by slari-pivotal**
Adding a new step in concourse that generates a tarball for
the tinc.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@slari-pivotal Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1327)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1327) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@slari-pivotal Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1327)!

**Comment by hlinnaka** [comment]
Why? What is the tarball used for?

**Comment by slari-pivotal** [comment]
@hlinnaka This is tied to our Pulse CI integration, where we currently need the TINC source code along with the binaries when running the tests.

**Comment by hlinnaka** [comment]
On 11/16/2016 01:31 AM, Shoaib Lari wrote:
> @hlinnaka This is tied to our Pulse CI integration, where we
> currently need the TINC source code along with the binaries when
> running the tests.

I'm confused. I thought we're using Concourse for CI?

- Heikki

**Comment by slari-pivotal** [comment]
> I'm confused. I thought we're using Concourse for CI?
> 
> - Heikki

You are correct that Concourse will eventually will be our CI.  However, our automated TINC testing infrastructure is still tied to Pulse.  We will decommission the TINC src tarball functionality in Concourse once we've migrated everything (our TINC testing infrastructure) to Concourse.

**Pull request merged**
