### PR TITLE
Remove dead code.

### PR DESCRIPTION
**Pull request by hlinnaka**
I found these with "callcatcher", written by Caolán McNamara. Many thanks
for the tool! See https://www.skynet.ie/~caolan/Packages/callcatcher.html

### CODE REVIEW

**Comment by hlinnaka** [comment]
@ashwinstar, per discussion on PR #1052, I googled around for a tool to find dead code, and found this. At first I thought I did it wrong, when it found so many dead functions, but on closer inspection, most of them were indeed dead :-).

**Comment by hlinnaka** [comment]
I should add that the tool found many more dead functions, but I refrained from removing anything that's inherited from upstream, or is debugging code that would be used with suitable #ifdefs, or seemed like something that might come handy when running in a debugger.

**Comment by ashwinstar** [comment]
On Wed, Aug 17, 2016 at 3:04 PM, Heikki Linnakangas <
notifications@github.com> wrote:

> @ashwinstar <https://github.com/ashwinstar>, per discussion on PR #1052
> <https://github.com/greenplum-db/gpdb/pull/1052>, I googled around for a
> tool to find dead code, and found this. At first I thought I did it wrong,
> when it found so many dead functions, but on closer inspection, most of
> them were indeed dead :-).
>
Awesome Great, that's extremely handy tool. Hoped the ToDo mentioned on
website happened "Now that gcc supports user-written plugins converting
this to a gcc plugin might make more sense than scraping assembly"

So did you write wrapper on-top to get rid of sooo many dead-functions ;-)

**Comment by hsyuan** [comment]
Cool! We are going to try it on Orca and gpos. thanks for sharing.

**Comment by hlinnaka** [comment]
On 08/18/2016 02:41 AM, Ashwin Agrawal wrote:
> On Wed, Aug 17, 2016 at 3:04 PM, Heikki Linnakangas <
> notifications@github.com> wrote:
>
>> @ashwinstar <https://github.com/ashwinstar>, per discussion on PR #1052
>> <https://github.com/greenplum-db/gpdb/pull/1052>, I googled around for a
>> tool to find dead code, and found this. At first I thought I did it wrong,
>> when it found so many dead functions, but on closer inspection, most of
>> them were indeed dead :-).
>>
> Awesome Great, that's extremely handy tool. Hoped the ToDo mentioned on
> website happened "Now that gcc supports user-written plugins converting
> this to a gcc plugin might make more sense than scraping assembly"
>
> So did you write wrapper on-top to get rid of sooo many dead-functions ;-)

Heh, that would be a cool project :-).

I interepreted your "Awesome" as a +1, and pushed. Thanks!

- Heikki

**Pull request closed without merging**
