### PR TITLE
Automatically regenerate gppylib catalog JSON file

### PR DESCRIPTION
**Pull request by danielgustafsson**
Instead of having to remember to manually update the gppylib JSON file (which has frequently been forgotten), hook the generation into the `src/backend/catalog` "all" target such that it's generated
automatically when needed.

Also updates the documentation and some minor comment fixes to the `process_foreign_key.pl` script.

Note: this still generates 5.json even though we really should be at 6.json, but thats not the fault of this PR..

### CODE REVIEW

**Comment by ashwinstar** [comment]
Do we still wish to have committed version of Json file ? I was thinking if its generated automatically then lets not have committed version.

**Comment by danielgustafsson** [comment]
> On 20 Oct 2017, at 20:05, Ashwin Agrawal <notifications@github.com> wrote:
> 
> Do we still wish to have committed version of Json file ? I was thinking if its generated automatically then lets not have committed version.

Thats a fair point, I was thinking about it like configure.in/configure but thinking more on it I agree. We can definitaly skip this as a checked in file once this goes in, will update the PR.

**Comment by ashwinstar** [comment]
@danielgustafsson Can we bring this to closure ?

**Comment by danielgustafsson** [comment]
> On 08 Nov 2017, at 23:10, Ashwin Agrawal <notifications@github.com> wrote:
> 
> @danielgustafsson Can we bring this to closure ?

As soon as the pipeline is green during hours when I’m awake so I can see it through.. fingers crossed

**Comment by danielgustafsson** [comment]
Pushed to master, thanks

**Pull request closed without merging**
