### PR TITLE
Avoid "HEAP_MOVED_OFF was expected" errors in VACUUM FULL.

### PR DESCRIPTION
**Pull request by hlinnaka**
If a page has hint bits set, but the buffer has not been marked as dirty,
and it gets evicted between the 1st and 2nd vacuum pass, the 2nd pass
gets upset. That can't happen in the upstream, as setting a hint bit
always marks the buffer as dirty, but that is not guaranteed in GPDB, because
of gp_disable_tuple_hints.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Here's a script to reproduce it. I didn't include it in the regression suite, because it requires running some concurrent action manually. This particular bug doesn't seem too likely to re-appear in the same form, and this whole VACUUM FULL mechanism is going away in PostgreSQL 9.0 anyway.

[vacuum-full-heap-moved-off.sql.txt](https://github.com/greenplum-db/gpdb/files/290958/vacuum-full-heap-moved-off.sql.txt)

**Comment by atris** [comment]
+1

I am a bit concerned about the lost update that we have when page is evicted without being marked dirty. IMO this is a waste of a scan of potentially a large table.
Not that this is concerning this PR, but I have never liked the GUC anyways. Is it actually useful? IMO if we disable setting hint bits, then it should only be for tables which have limited set of inserting transactions and for them, we should have a hint bit cache (if we do not already). Plain disabling of hint bits is a bit broken, IMO.

**Comment by danielgustafsson** [comment]
:+1:

**Comment by hlinnaka** [comment]
On 31/05/16 14:31, Atri Sharma wrote:
> I am a bit concerned about the lost update that we have when page is
> evicted without being marked dirty. IMO this is a waste of a scan of
> potentially a large table. Not that this is concerning this PR, but I
> have never liked the GUC anyways. Is it actually useful?

That's a fair question. It's certainly true that you could save a lot of 
CPU cycles by setting the hint bits, if you repeatedly scan the same 
table. It's a CPU vs. IO tradeoff. Overall, I actually think that 
disabling them makes sense (or to be precise, to not mark the buffer 
dirty when a hint bit is set). While you save on CPU, the I/O penalty of 
dirtying pages is huge. It's been discussed on pgsql-hackers many times 
over the years as well, and many people have suggested doing exactly 
what GPDB does, but it hasn't gone anywhere. The tradeoff might be 
different between OLTP and OLAP workloads too.

But that's a different story.

> IMO if we disable setting hint bits, then it should only be for
> tables which have limited set of inserting transactions and for them,
> we should have a hint bit cache (if we do not already). Plain
> disabling of hint bits is a bit broken, IMO.

There is a one-element cache on the clog lookups, so if you lookup the 
same XID repeatedly, it's pretty cheap. Not quite as cheap as checking 
the hint bit, but still cheap. That helps a lot.

- Heikki

**Comment by atris** [comment]
I agree with your points. The single element XID cache seems good enough for this case

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Pull request closed without merging**
