### PR TITLE
Use normal hash operator classes for data distribution.

### PR DESCRIPTION
**Pull request by hlinnaka**
Use normal hash operator classes for data distribution.

Replace the use of the built-in hashing support for built-in datatypes, in
cdbhash.c, with the normal PostgreSQL hash functions. Now is a good time
to do this, since we've already made the change to use jump consistent
hashing in GPDB 6, so we'll need to deal with the upgrade problems
associated with changing the hash functions, anyway.

It is no longer enough to track which columns/expressions are used to
distribute data. You also need to know the hash function used. For that,
a new field is added to gp_distribution_policy, to record the hash
operator class used for each distribution key column. In the planner,
a new opfamily field is added to DistributionKey, to track that throughout
the planning.

Normally, if you do "CREATE TABLE ... DISTRIBUTED BY (column)", the
default hash operator class for the datatype is used. But this patch
extends the syntax so that you can specify the operator class explicitly,
like "... DISTRIBUTED BY (column opclass)". This is similar to how an
operator class can be specified for each column in CREATE INDEX.

To support upgrade, the old hash functions have been converted to special
(non-default) operator classes, named cdbhash_*_ops. For example, if you
want to use the old hash function for an integer column, you could do
"DISTRIBUTED BY (intcol cdbhash_int4_ops)". The old hard-coded whitelist
of operators that have "compatible" cdbhash functions has been replaced
by putting the compatible hash opclasses in the same operator family. For
example, all legacy integer operator classes, cdbhash_int2_ops,
cdbhash_int4_ops and cdbhash_int8_ops, are all part of the
cdbhash_integer_ops operator family).

This removes the pg_database.hashmethod field. The hash method is now
tracked on a per-table and per-column basis, using the opclasses, so it's
not needed anymore.

To help with upgrade from GPDB 5, this introduces a new GUC called
'gp_use_legacy_hashops'. If it's set, CREATE TABLE uses the legacy hash
opclasses, instead of the default hash opclasses, if the opclass is not
specified explicitly. pg_upgrade will set the new GUC, to force the use of
legacy hashops, when restoring the schema dump. It will also set the GUC
on all upgraded databases, as a per-database option, so any new tables
created after upgrade will also use the legacy opclasses. It seems better
to be consistent after upgrade, so that collocation between old and new
tables work for example. The idea is that some time after the upgrade, the
admin can reorganize all tables to use the default opclasses instead. At
that point, he should also clear the GUC on the converted databases. (Or
rather, the automated tool that hasn't been written yet, should do that.)

ORCA doesn't know about hash operator classes, or the possibility that we
might need to use a different hash function for two columns with the same
datatype. Therefore, it cannot produce correct plans for queries that mix
different distribution hash opclasses for the same datatype, in the same
query. There are checks in the Query->DXL translation, to detect that
case, and fall back to planner. As long as you stick to the default
opclasses in all tables, we let ORCA to create the plan without any regard
to them, and use the default opclasses when translating the DXL plan to a
Plan tree. We also allow the case that all tables in the query use the
"legacy" opclasses, so that ORCA works after pg_upgrade. But a mix of the
two, or using any non-default opclasses, forces ORCA to fall back.

One curiosity with this is the "int2vector" and "aclitem" datatypes. They
have a hash opclass, but no b-tree operators. GPDB 4 used to allow them
as DISTRIBUTED BY columns, but we forbid that in GPDB 5, in commit
56e7c16bad. Now they are allowed again, so you can specify an int2vector
or aclitem column in DISTRIBUTED BY, but it's still pretty useless,
because the planner still can't form EquivalenceClasses on it, and will
treat it as "strewn" distribution, and won't co-locate joins.

Abstime, reltime, tinterval datatypes don't have default hash opclasses.
They are being removed completely on PostgreSQL v12, and users shouldn't
be using them in the first place, so instead of adding hash opclasses for
them now, we accept that they can't be used as distribution key columns
anymore. Add a check to pg_upgrade, to refuse upgrade if they are used
as distribution keys in the old cluster. Do the same for 'money' datatype
as well, although that's not being removed in upstream.

The legacy hashing code for anyarray in GPDB 5 was actually broken. It
could produce a different hash value for two arrays that are considered
equal, according to the = operator, if there were differences in e.g.
whether the null bitmap was stored or not. Add a check to pg_upgrade, to
reject the upgrade if array types were used as distribution keys. The
upstream hash opclass for anyarray works, though, so it is OK to use
arrays as distribution keys in new tables. We just don't support binary
upgrading them from GPDB 5. (See github issue
https://github.com/greenplum-db/gpdb/issues/5467). The legacy hashing of
'anyrange' had the same problem, but that was new in GPDB 6, so we don't
need a pg_upgrade check for that.

This also tightens the checks ALTER TABLE ALTER COLUMN and CREATE UNIQUE
INDEX, so that you can no longer create a situation where a non-hashable
column becomes the distribution key. (Fixes github issue
https://github.com/greenplum-db/gpdb/issues/6317)

Discussion: https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/4fZVeOpXllQ
Co-authored-by: Mel Kiyama <mkiyama@pivotal.io>
Co-authored-by: Abhijit Subramanya <asubramanya@pivotal.io>
Co-authored-by: Pengzhou Tang <ptang@pivotal.io>
Reviewed-by: Bhuvnesh Chaudhary <bchaudhary@pivotal.io>
Reviewed-by: Ning Yu <nyu@pivotal.io>
Reviewed-by: Simon Gao <sgao@pivotal.io>
Reviewed-by: Jesse Zhang <jzhang@pivotal.io>
Reviewed-by: Zhenghua Lyu <zlv@pivotal.io>
Reviewed-by: Melanie Plageman <mplageman@pivotal.io>
Reviewed-by: Yandong Yao <yyao@pivotal.io>

### CODE REVIEW

**Comment by hlinnaka** [comment]
This is a rebased version of the work that was discussed at https://github.com/greenplum-db/gpdb/pull/6327 at length.

I believe this is now ready to be committed. Give the CI one more chance to run, and the last chance for people to speak up before this goes in. Going once, going twice..

**Comment by hlinnaka** [comment]
After this is pushed, there is one follow-up task left, that I mentioned in the commit message:
```
The idea is that some time after the upgrade, the
admin can reorganize all tables to use the default opclasses instead. At
that point, he should also clear the GUC on the converted databases. (Or
rather, the automated tool that hasn't been written yet, should do that.)
```
We should write a script like that, to allow the admin to reorganize all tables some time after upgrade, to use the new hash opclasses.

**Comment by hlinnaka** [comment]
Concourse pipeline is showing two failures: A crash with ORCA, and the GDD isolation2 tests are getting stuck. I cannot reproduce either of these on my laptop. @bhuvnesh2703, @vraghavan78, can you help to debug the ORCA crashes, please? Anyone have a clue on the GDD test failures?

**Comment by kainwen** [comment]
Let me take the GDD case.

**Comment by pengzhout** [comment]
@kainwen, @pivotal-ning-yu has already fixed it.

**Comment by kainwen** [comment]
> @kainwen, @pivotal-ning-yu has already fixed it.

Cool. I am too late for the party.

**Comment by adam8157** [comment]
FYI, gptransfer is removed by #6794

**Comment by hlinnaka** [comment]
> FYI, gptransfer is removed by #6794

Rebased.

**Comment by chrishajas** [comment]
@hlinnaka 

This crash was occurring when running the partition_indexing and
partition_ddl schedules in a parallel schedule with ORCA. Specifically,
a `select count(*) from part_table` was running simultaneously with an
`\d+` on a different table.

We found that the server was crashing when referencing the opclass in
`if (policy->opclasses[i] == default_opclass)`. When looking at the
disassembly via the core dump and tracing the addresses, we saw that the
reference to opclass from rel -> policy -> opclasses was correct
and wasn't getting overwritten; however, the reference pointed to in the
register (which should match this address) was an invalid memory
address.

Storing opclasses in a variable seems to fix the issue without any
change to the logic. However, we're not certain this isn't masking a different underlying issue. We didn't see anything that would indicate memory getting overwritten. What do you think? I don't like to write things off as a compiler bug since they're rare.

See https://github.com/chrishajas/gpdb/commit/cf1a0338bb794e236b2d840d1f8b73f59320b7a2 for the fix. It passed the orca-related tests. There's still other failures that are also failing with planner and seem unrelated to ORCA.

**Comment by pivotal-ning-yu** [comment]
On Wed, Jan 30, 2019 at 9:14 AM Chris Hajas <notifications@github.com>
wrote:

> @hlinnaka <https://github.com/hlinnaka>
>
> This crash was occurring when running the partition_indexing and
> partition_ddl schedules in a parallel schedule with ORCA. Specifically,
> a select count(*) from part_table was running simultaneously with an
> \d+ on a different table.
>
> We found that the server was crashing when referencing the opclass in
> if (policy->opclasses[i] == default_opclass). When looking at the
> disassembly via the core dump and tracing the addresses, we saw that the
> reference to opclass from rel -> policy -> opclasses was correct
> and wasn't getting overwritten; however, the reference pointed to in the
> register (which should match this address) was an invalid memory
> address.
>
> Storing opclasses in a variable seems to fix the issue without any
> change to the logic. However, we're not certain this isn't masking a
> different underlying issue. We didn't see anything that would indicate
> memory getting overwritten. What do you think? I don't like to write things
> off as a compiler bug since they're rare.
>
> See chrishajas@cf1a033
> <https://github.com/chrishajas/gpdb/commit/cf1a0338bb794e236b2d840d1f8b73f59320b7a2>
> for the fix. It passed the orca-related tests. There's still other failures
> that are also failing with planner and seem unrelated to ORCA.
>

Not related to this issue but I noticed that a table mpp13806 is created
and altered in both partition.sql and partition1.sql, and they are in the
same parallel group, I wonder whether will they cause flaky results.

**Comment by hlinnaka** [comment]
> This crash was occurring when running the partition_indexing and
> partition_ddl schedules in a parallel schedule with ORCA. Specifically,
> a `select count(*) from part_table` was running simultaneously with an
> `\d+` on a different table.
> 
> We found that the server was crashing when referencing the opclass in
> `if (policy->opclasses[i] == default_opclass)`. When looking at the
> disassembly via the core dump and tracing the addresses, we saw that the
> reference to opclass from rel -> policy -> opclasses was correct
> and wasn't getting overwritten; however, the reference pointed to in the
> register (which should match this address) was an invalid memory
> address.
> 
> Storing opclasses in a variable seems to fix the issue without any
> change to the logic. However, we're not certain this isn't masking a different underlying issue. We didn't see anything that would indicate memory getting overwritten. What do you think? I don't like to write things off as a compiler bug since they're rare.
> 
> See [chrishajas@cf1a033](https://github.com/chrishajas/gpdb/commit/cf1a0338bb794e236b2d840d1f8b73f59320b7a2) for the fix. It passed the orca-related tests. There's still other failures that are also failing with planner and seem unrelated to ORCA.

Huh, that's weird. My first thought was relcache invalidation happening at an unfortunate moment, but the code looks safe from that, too. I'm also reluctant to write this off as a compiler bug, the code is pretty straightforward so it would be strange to hit a compiler bug with that. But just in case, is the compiler on the concourse box up-to-date?

In any case, I'll cherry-pick that commit to this PR, so that we can move on...

**Comment by hlinnaka** [comment]
@chrishajas, others, looks like we're not out of the woods with the ORCA failure yet. I just got a failure like this on the PR pipeline:
```
--- /tmp/build/6d3dc0ce/gpdb_src/src/test/regress/expected/qp_derived_table.out	2019-01-31 16:49:03.212861251 +0000
+++ /tmp/build/6d3dc0ce/gpdb_src/src/test/regress/results/qp_derived_table.out	2019-01-31 16:49:06.552861251 +0000
@@ -4341,6 +4346,8 @@
 ORDER BY
 	MAX( DT255.C1104 )
 LIMIT 343;
+INFO:  GPORCA failed to produce a plan, falling back to planner
+DETAIL:  Feature not supported: Query contains relations with non-default hash opclasses
  max 
 -----
    1
```
I'm quite sure that there is in fact no non-default hash opclasses being used in that test query. This looks kind of similar to the mysterious crashes; if the policy->opclasses field is somehow read incorrectly in the code that scans the input query for opclasses, it could explain that.

Any ideas?

**Comment by hlinnaka** [comment]
Finally, I managed to fix all the remaining test failures, and got a green build! There were a bunch of trivial issues that were masked by earlier failing tests. Silly little things, but it took about a dozen runs to flush them all out.

Barring any last-minute objections, I'm going to push this later today.

**Comment by danielgustafsson** [comment]
> On 1 Feb 2019, at 12:58, Heikki Linnakangas <notifications@github.com> wrote:

> Barring any last-minute objections, I'm going to push this later today.

+1. Great work!

**Comment by hlinnaka** [comment]
Pushed! Thanks to everyone involved!

**Pull request merged**
