### PR TITLE
5X: Dispatch truncated query strings

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
Query string is dispatched with each sub command, when the query string
and the count of sub commands are both large it is a huge effort to
dispatch it repeatedly.  One simple example is as below:

    create table t (c1 int, c2 int)
    /* comment */
    /* ... */
    /* comment */
    partition by range(c2) (start(0) end(1000) every(1));

This SQL contains 2001 sub commands, if we put 10MB comments into it
then it is 10MB*2001 = 20GB data to dispatch, that will impact the
performance a log.  There can also be real world example:

    create table t (c1 int, c2 int, ..., c100 int)
    with (appendonly=true, compresslevel=5, orientation=column, compresstype=zlib)
    partition by range(c2) (
        start(0) end(1) every(1) with (tablename='p1', appendonly=true, compresslevel=5, orientation=column, compresstype=zlib)
            column c1 encoding (compresslevel=5, compresstype=zlib, blocksize=32768)
            ...
            column c100 encoding (compresslevel=5, compresstype=zlib, blocksize=32768),
        ...
        start(999) end(1000) every(1) with (tablename='p1000', appendonly=true, compresslevel=5, orientation=column, compresstype=zlib)
            column c1 encoding (compresslevel=5, compresstype=zlib, blocksize=32768)
            ...
            column c100 encoding (compresslevel=5, compresstype=zlib, blocksize=32768)
    );

However dispatched query strings are not always useful, it is mainly for
debugging purpose if there is a valid query tree or plan tree.  In such
a case we could dispatch truncated query strings to improve the
performance.  The truncated size is hard coded to 1KB for now.

A discussion in mailing list:
https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/8tz4oivq3vM/cp12HKL-BAAJ

Reviewed-by: Heikki Linnakangas <hlinnakangas@pivotal.io>
Reviewed-by: Pengzhou Tang <ptang@pivotal.io>

(cherry picked from commit 08f6b6dcf9025ab8474e9928ab6f582a6c60d572)

### CODE REVIEW

**Comment by pivotal-ning-yu** [comment]
This is the 5X version of https://github.com/greenplum-db/gpdb/pull/5942, we will have it merged once the pipeline is green.

**Comment by pivotal-ning-yu** [comment]
The pipeline is green, I'll merge it now.

**Comment by goutamtadi1** [comment]
@pivotal-ning-yu  Did you reference the wrong PR in the above comments? Should  this be #5962?

**Comment by pivotal-ning-yu** [comment]
@goutamtadi1 oops, yes you are right, it's for #5962.

**Pull request merged**
