### PR TITLE
Port Correlated SubQuery + Function Tests to ICG

### PR DESCRIPTION
**Pull request by vraghavan78**
Kind Attention: @oarap @xinzweb @hsyuan

### CODE REVIEW

**Comment by hsyuan** [comment]
LGTM.

**Comment by xinzweb** [comment]
+1. How much more minutes added to ICG? Thanks.

**Comment by oarap** [comment]
+1

**Comment by vraghavan78** [comment]
@xinzweb less than 30 sec

**Comment by vraghavan78** [comment]
Thanks Y'all

**Pull request closed without merging**
