### PR TITLE
Fix environment variables generation when using symlinks

### PR DESCRIPTION
**Pull request by pobbatihari**
Issue #12420

INFO : backporting changes from master 
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by 50wu** [comment]
@pobbatihari Thanks for the PR here. Look at the context from the issue [12420](https://github.com/greenplum-db/gpdb/issues/12420), notice you are expecting the `GPHOME` to be `/usr/local/greenplum-db` when you are creating multiple layers of symlinks like:
```
~/gpdb -> /usr/local/greenplum-db -> /usr/local/greenplum-db-6.17.1
```

But our expectation is `GPHOME` should always be `%{installation prefix}/greenplum-db-[version]`, the reference is here [Greenplum Path Layer](https://github.com/greenplum-db/greenplum-database-release/blob/main/Greenplum-Server-RPM-Packaging-Specification.md#greenplum-path-layer) . 

So I am afraid this change is not meet our requirements. @gp-releng Please correct me if I am wrong.

**Review by BaiShaoqi — APPROVED** [review]
The PR looks good to me.  @khuddlefish , any concerns from you ?

**Comment by BaiShaoqi** [comment]
@50wu , it looks like the is doc `GPHOME should always be %{installation prefix}/greenplum-db-[version]` is  implemented by https://github.com/greenplum-db/greenplum-database-release/commit/a35f209bcb63a91e32df276aa762660c051a3be0, but later we introduced the https://github.com/greenplum-db/gpdb/pull/10737 to delete the assumption. but the doc is not updated, need to update the doc.

**Comment by 50wu** [comment]
> @50wu , it looks like doc you are reference `GPHOME should always be %{installation prefix}/greenplum-db-[version]` is implemented by [greenplum-db/greenplum-database-release@a35f209](https://github.com/greenplum-db/greenplum-database-release/commit/a35f209bcb63a91e32df276aa762660c051a3be0), but later we introduced the #10737 to delete the assumption. but the doc is not updated, need to update the doc.

@kmacoskey Do we change the assumption of `GPHOME should always be %{installation prefix}/greenplum-db-[version]`?

**Review by khuddlefish — APPROVED** [review]
I approved the master PR already so the backport seems fine to me

**Comment by khuddlefish** [comment]
@50wu and @BaiShaoqi You are right that our doc does say that. I'm not sure if it is actually required. However, if it is required the current state of the code already broke the requirement because it will only ever go one level down in the symlink. So in the example, of
```
~/gpdb -> /usr/local/greenplum-db -> /usr/local/greenplum-db-6.17.1
```
if called from `~/gpdb`. The current code will set GPHOME to `~/greenplum-db`. The proposed fix will set GPHOME to `/usr/local/greenplum-db`. The path we would currently produce is not valid, but the second one is. I think we should accept the fix to at least always create valid paths. If we need to always have it point at the installation dir we will have to develop a different method anyways.

**Pull request merged**
