### PR TITLE
Fix error code overwrite in cdbdisp_dumpDispatchResult.

### PR DESCRIPTION
**Pull request by JunfengYang**
The error code should not set twice with different codes in `errfinish_and_return`.
Since the order of function's parameters depends on the compiler.
If the final error code is ERRCODE_INTERNAL_ERROR, file name and line number print out.
```
ERROR:  Error on receive from SEG IP:PORT pid=PID: *** (cdbdispatchresult.c:487)
```

It's strange to print out the file name and line number here.
So, remove ERRCODE_INTERNAL_ERROR, and only keep ERRCODE_GP_INTERCONNECTION_ERROR,
which is also the error code before commit: 143bb7c.

### CODE REVIEW

**Comment by paul-guo-** [comment]
Please fix those match rules in tests also. For example,
```
-- # create a match/subs expression
--
-- m/ERROR:.*server closed the connection unexpectedly (cdbdispatchresult.c:\d+)/
```

Probably just need to revert those rule changes in https://github.com/greenplum-db/gpdb/commit/143bb7c6fcfcbd540239747391feec2b5b5548e8

**Comment by JunfengYang** [comment]
Sure, I'll fix the test results.

**Comment by JunfengYang** [comment]
@paul-guo- I can not trigger the concourse check now. So, I would like to close this pr and re-open a new one.

**Comment by JunfengYang** [comment]
Still can not trigger the concourse on new PR, close the new PR, reopen current.

**Pull request merged**
