### PR TITLE
Change the way "unknown" literals are handled in SELECT lists.

### PR DESCRIPTION
**Pull request by hlinnaka**
We had made some changes in this area in GPDB, to allow the cases that
were covered by the GPDB-added test queries in 'strings' test. PostgreSQL
v10 revamped this area, to support similar cases. Cherry-pick the upstream
changes, replacing the previous GPDB hacks. We would get these changes
with the next merge from upstream anyway, but cherry-pick now to get some
more visibility to this, as it replaces previous GPDB-specific code.

While we're at it, move the tests for these from 'strings' to 'gp_types'
test, to keep the upstream 'strings' test clean from GPDB changes. That
reduces the number of merge conflicts as we merge with upstream.

This changes the behavior in some GPDB tests. 'unknown' can no longer be
used as a column's type, so remove tests that did that. Also, unknown
literals in a subquery's target list are now always converted to text.
Previuosly, we tried to coerce it depending on where the subquery's output
was used.

Upstream commit:
```
commit 1e7c4bb0049732ece651d993d03bb6772e5d281a
Author: Tom Lane <tgl@sss.pgh.pa.us>
Date:   Wed Jan 25 09:17:18 2017 -0500

    Change unknown-type literals to type text in SELECT and RETURNING lists.

    Previously, we left such literals alone if the query or subquery had
    no properties forcing a type decision to be made (such as an ORDER BY or
    DISTINCT clause using that output column).  This meant that "unknown" could
    be an exposed output column type, which has never been a great idea because
    it could result in strange failures later on.  For example, an outer query
    that tried to do any operations on an unknown-type subquery output would
    generally fail with some weird error like "failed to find conversion
    function from unknown to text" or "could not determine which collation to
    use for string comparison".  Also, if the case occurred in a CREATE VIEW's
    query then the view would have an unknown-type column, causing similar
    failures in queries trying to use the view.

    To fix, at the tail end of parse analysis of a query, forcibly convert any
    remaining "unknown" literals in its SELECT or RETURNING list to type text.
    However, provide a switch to suppress that, and use it in the cases of
    SELECT inside a set operation or INSERT command.  In those cases we already
    had type resolution rules that make use of context information from outside
    the subquery proper, and we don't want to change that behavior.

    Also, change creation of an unknown-type column in a relation from a
    warning to a hard error.  The error should be unreachable now in CREATE
    VIEW or CREATE MATVIEW, but it's still possible to explicitly say "unknown"
    in CREATE TABLE or CREATE (composite) TYPE.  We want to forbid that because
    it's nothing but a foot-gun.

    This change creates a pg_upgrade failure case: a matview that contains an
    unknown-type column can't be pg_upgraded, because reparsing the matview's
    defining query will now decide that the column is of type text, which
    doesn't match the cstring-like storage that the old materialized column
    would actually have.  Add a checking pass to detect that.  While at it,
    we can detect tables or composite types that would fail, essentially
    for free.  Those would fail safely anyway later on, but we might as
    well fail earlier.

    This patch is by me, but it owes something to previous investigations
    by Rahila Syed.  Also thanks to Ashutosh Bapat and Michael Paquier for
    review.

    Discussion: https://postgr.es/m/CAH2L28uwwbL9HUM-WR=hromW1Cvamkn7O-g8fPY2m=_7muJ0oA@mail.gmail.com
```

### CODE REVIEW

**Comment by mkiyama** [comment]
@hlinnaka 
For a doc update, does this PR affect PREPARE?
https://gpdb.docs.pivotal.io/6-4/ref_guide/sql_commands/PREPARE.html

This text is in the second paragraph. 
``
A corresponding list of parameter data types can optionally be specified. When a parameter's data type is not specified or is declared as unknown, the type is inferred from the context in which the parameter is first used (if possible).
``
thanks

**Comment by hlinnaka** [comment]
> @hlinnaka
> For a doc update, does this PR affect PREPARE?
> https://gpdb.docs.pivotal.io/6-4/ref_guide/sql_commands/PREPARE.html
> 
> This text is in the second paragraph.
> `A corresponding list of parameter data types can optionally be specified. When a parameter's data type is not specified or is declared as unknown, the type is inferred from the context in which the parameter is first used (if possible).`
> thanks

No, that's not affected. The upstream commit add text to the "typeconv.sgml" file. I couldn't find text like that in the GPDB docs.

I just updated this PR by applying the same changes to `CREATE_VIEW.xml` that were made in upstream to `create_view.sgml`.

**Comment by d** [comment]
Hi Heikki, David and I were looking into this earlier today. We were thinking about something simpler: just rip out the `unknown` cleverness from `parse_coerce.c` without backporting commit 1e7c4bb0049732ece651d993d03bb6772e5d281a. Obviously we haven't done that yet. I wonder what would happen if we don't backport 1e7c4bb0049732ece651d993d03bb6772e5d281a ?

**Comment by hlinnaka** [comment]
On 4 March 2020 09:10:43 EET, Jesse Zhang <notifications@github.com> wrote:
>Hi Heikki, David and I were looking into this earlier today. We were
>thinking about something simpler: just rip out the `unknown` cleverness
>from `parse_coerce.c` without backporting commit
>1e7c4bb0049732ece651d993d03bb6772e5d281a. Obviously we haven't done
>that yet. I wonder what would happen if we don't backport
>1e7c4bb0049732ece651d993d03bb6772e5d281a ?

Then the tests that were added with the original cleverness will start to fail. And a few others that have been added later that happen to excercise that codepath.

- Heikki

**Comment by dgkimura** [comment]
> And a few others that have been added later that happen to exercise that codepath.

Are the others you're referring to the set ops?  These were the only ones we noticed so far.

```
select * from (select 'a' as a, 'b' as b, 'c' as c, 1 as d)d union select 'a' as a, 'b' as b, 'c' as c, 1 as d;
```
and 
```
select 'a' as a, 'b' as b, 'c' as c, 1 as d union select * from (select 'a' as a, 'b' as b, 'c' as c, 1 as d)d;
```

We believe that these two queries will still work even if rip out the unknown handling.  We confirmed that they work on vanilla 9.6.  We see the value in removing the unknown handing in master as it promotes visibility, but we're not quite sure of the value of the backport.

Would you be open to an alternative patch to remove the unknown handling and keep the set op tests working, but break queries like

```
select foo || 'bar'::text from (select 'bar' as foo) a;
```

until we merge back the patches from 12?

**Comment by hlinnaka** [comment]
On 5 March 2020 00:17:15 EET, David Kimura <notifications@github.com> wrote:
>> And a few others that have been added later that happen to exercise
>that codepath.
>
>Are the others you're referring to the set ops?  These were the only
>ones we noticed so far.

I'm not sure which tests might fail, I haven't tried running the tests that way.

>Would you be open to an alternative patch to remove the unknown
>handling and keep the set op tests working, but break queries like
>
>```
>select foo || 'bar'::text from (select 'bar' as foo) a;
>```
>
>until we merge back the patches from 12?

Works for me.

- Heikki

**Comment by d** [comment]
> but we're not quite sure of the value of the backport.

To add to @dgkimura 's comment, even for queries like 

```sql
select foo || 'bar'::text from (select 'bar' as foo) a;
```

the Postgres 10 backport will _only_ save the ones that happen to coerce `unknown` to `text`. Specifically, it won't save if the cleverness tries to coerce `unknown`s into `int`:

```sql
select foo + 123 from (select 'bar' as foo) a;
```

**Comment by hlinnaka** [comment]
This was superseded by commit 4c8dace3e13b8c4560ec494a1fb4d2bde457c1e8 that removed the current "unknown" handling, and we'll get the replacement from upstream as we merge with v10. Closing.

**Pull request closed without merging**
