### PR TITLE
Backport the CUDE token definition in production rules of parser from PG 9.5

### PR DESCRIPTION
**Pull request by maksm90**
## Problem description

The statement `create extension cube` raises syntax error on parsing of the following statement:
```sql
CREATE FUNCTION cube_in(cstring)
RETURNS cube
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;
```

In particular, parser fails on the return type `cube`. The reason of this is the nonterminal symbol `func_return` that denotes return type in [CreateFunctionStmt production rule](https://github.com/greenplum-db/gpdb/blob/6.10.1/src/backend/parser/gram.y#L8791-L8793)  doesn't derive CUBE token anyway.

The current patch moves CUDE token from `col_name_keyword` production rule to `unreserved_keyword` one. The second one is derived from `func_return` nonterminal through the sequence of derivations: `func_return -> func_type -> type_function_name -> unreserved_keyword`. Such modification is backward compatible since the use cases of `col_name_keyword` nonterminal symbol is completely covered by `unreserved_keyword` one.

This fix could be seemed as backport of CUBE token location in grammar from PG 9.5 and as consequence from new upcoming release of GPDB.

## Affected versions

GPDB 6 and below

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by JunfengYang** [comment]
Thanks for your contribution! @maksm90 
I'll take a look.

**Review by JunfengYang — APPROVED** [review]
LGTM

**Comment by gaos1** [comment]
Thanks @maksm90 with this patch, cube extension can fully work with GP6 or is there any other problems?

**Comment by JunfengYang** [comment]
@gaos1 I ran the cube's tests, it passed with the patch.
But the 6X doesn't contain the test data file which is weird, I have to copy the data file from master.

**Comment by kapustor** [comment]
@gaos1 same thing as @JunfengYang , tests from https://github.com/postgres/postgres/blob/REL9_4_STABLE/contrib/cube/sql/cube.sql work fine, have to load test data manually.

**Comment by gaos1** [comment]
Thanks @JunfengYang @kapustor nice to see that cube extension works fine with gp6.

**Comment by JunfengYang** [comment]
Merged, thanks for the contribution!

**Pull request merged**
