### PR TITLE
Fix pg_stat_activity show wrong session id after session reset bug

### PR DESCRIPTION
**Pull request by zhangteng5513**
Currently if a session is reset because of some error such as OOM,
after call CheckForResetSession, gp_session_id will bump to a new one,
but sess_id in pg_stat_activity remains unchanged and show the wrong number.
This commit changes sess_id in pg_stat_activity, once a session is reset.

ISSUE: #5599

### CODE REVIEW

**Comment by zhangteng5513** [comment]
@pengzhout Would you please help review those changes?

**Comment by pengzhout** [comment]
For codes, LGTM.

**Comment by asimrp** [comment]
The code change looks fine but the test needs to be more focused.  Instead of creating a table and let the session be reset as a side-effect of `dtm_broadcast_prepare` fault, what if one of the segment backend processes is terminated?  That will cause session ID to be reset to a new value.  The newly introduced `gp_execute_on_server()` facility may be put to use here.
```SQL
 CREATE FUNCTION gp_execute_on_server(content smallint, query cstring) returns boolean
language C as '@abs_builddir@/../../src/test/regress/regress.so', 'gp_execute_on_server';
show gp_session_id;
-- terminate backend process for this session on segment with content ID = 0
select gp_execute_on_server(0::smallint, 'select pg_terminate_backend(pg_backend_pid())'::cstring);
-- this gp_session_id value is different.
show gp_session_id;
```

One big advantage of the above approach is the test can added to a parallel group in in `greenplum_schedule`.

**Comment by zhangteng5513** [comment]
@pengzhout @asimrp 
Thanks for the review.
I agree gp_execute_on_server is a better way, but gp_execute_on_server is available on master only,
For 5X_STABLE, is there a way to trigger session reset better than inject dtm_broadcast_prepare fault?

**Comment by asimrp** [comment]
How about back porting `gp_execute_on_server()` to 5X?  It should be a simple back port and, if that makes testing easy, worth doing in my view.

**Comment by magi345** [comment]
+1 for backport to 5X, have done that in separate PR https://github.com/greenplum-db/gpdb/pull/5793

**Pull request merged**
