### PR TITLE
Create gp_inject_fault extension as part of pg_regress and isolation2

### PR DESCRIPTION
**Pull request by asimrp**
The extension is created by the test harness, after creating the regression / isolation2test databases.  Tests should directly start using the extension and not attempt to create it.  In addition to simplifying tests a little bit, this change avoids an error (`duplicate key value violates unique constraint on pg_extension`) when two or more tests execute create extension command concurrently.  The error is not a problem in practice, it expected because of the way create extension DDL works.  It is, however, unacceptable for regress-style test that expect a deterministic response to each SQL command.

This PR is based on Ashwin and Jimmy's feedback on another PR: https://github.com/greenplum-db/gpdb/pull/7585#issuecomment-488224256

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ashwinstar** [comment]
Curious to know, What error do we get or how gracefully does it fail if gp_inject_fault is installed?

**Comment by asimrp** [comment]
If `gp_inject_fault` extension is not already installed, `pg_regress` fails right after creating `regression` database like this:

```
============== creating database "regression"         ==============
CREATE DATABASE
ALTER DATABASE
============== installing gp_inject_fault             ==============
ERROR:  could not open extension control file "/Users/apraveen/workspace/gpdb/gpAux/greenplum-db-devel/share/postgresql/extension/gp_inject_fault.control": No such file or directory
command failed: "/Users/apraveen/workspace/gpdb/gpAux/greenplum-db-devel/bin/psql" -X -c "CREATE EXTENSION IF NOT EXISTS \"gp_inject_fault\"" "regression"
```

**Comment by pengzhout** [comment]
Thanks, it does make life easier. LGTM.

One question, the extension is per database, so any tests need gp_fault_injection in databases other than regression/isolation2 still need to create extension explicitly, right?

**Comment by paul-guo-** [comment]
👍 for the change. Looks like we can additionally do the same change to test heap_checksum and test fsync. By the way where is the `load-extension=gp_inject_fault` change for Makefile of regression tests?

**Comment by paul-guo-** [comment]
Ignore my question of "makfile for regression". Somehow on safari searching makefile just reports one occurrence (i.e. the isolation2 one).

**Comment by asimrp** [comment]
> One question, the extension is per database, so any tests need gp_fault_injection in databases other than regression/isolation2 still need to create extension explicitly, right?

Yes, that's right.  `dispatch` regression test is an example.

**Comment by asimrp** [comment]
@paul-guo- changed fsync and heap_checksum suites, thanks for catching that.

**Pull request merged**
