### PR TITLE
refactory dispatcher code

### PR DESCRIPTION
**Pull request by xiong-gang**
refactory cdbdisp_dispatchToGang interface.
refactory memory management in dispatcher.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Can you please give an overview of what the intention and goal with this patch is to aid review?

**Comment by xiong-gang** [comment]
@danielgustafsson 
We want to make dispatcher modularized and testable first, so we can make some other improvements on top of that, such as Heikki's async way. We want to do this with small PRs to make it's easier to review. In this first patch, i tried to cleanup the memory management code, remove some unnecessary variables, and simplify the cdbdisp_dispatchToGang function.

**Comment by eurekaka** [comment]
cdbdisp.c is collapsed, several comments for that file:
* should we add some comments in line 327 for explanation?
* in line 4028, NULL check is needed for the created memory context;
* in line 4110, parameter pParms is not used in function PQbuildGpQueryString, should remove it;
* typo in line 4334

**Comment by xiong-gang** [comment]
pushed.

**Pull request closed without merging**
