### PR TITLE
Merge 9.4.25

### PR DESCRIPTION
**Pull request by d**
Merge with PostgreSQL 9.4 STABLE (release 9.4.25)

This merges up to upstream commit 6cd154923526141e (tag: REL9_4_25)

To reviewers: I've cherry-picked one commit out-of-order because the conflict resolution is less trivial (see "Allow repalloc() to give back space when a large chunk is downsized.")

## Here are some reminders before you submit the pull request
- [x] Pass `make installcheck`

### CODE REVIEW

**Comment by d** [comment]
Also to reviewers: if you decide to merge this in for me, please don't use the "merge" or "rebase" buttons, but instead manually preserve the merge commit in a two-way merge whose first parent is Greenplum and the second parent is Postgres

jesse

**Comment by d** [comment]
hmmm, I broke the build, taking a quick look why

**Comment by hlinnaka** [comment]
No need to bring in `doc/src/sgml/release-9.4.sgml`.

**Comment by d** [comment]
I'm withdrawing this patchset because I don't have time to finish fixing up the test failures in the foreseeable future (like not in the next week).

**Pull request closed without merging**
