### PR TITLE
Add missing #ifdef block in aset.c

### PR DESCRIPTION
**Pull request by andreasscherbaum**
Might be missing from the 9.0 merge

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
@hlinnaka @danielgustafsson Can you please have a look if that is correct?

**Comment by andreasscherbaum** [comment]
Spotted it while investigating why #4669 is not working. But this missing code was not the cause.

**Comment by ashwinstar** [comment]
@andreasscherbaum is this done to be committed ?

**Comment by andreasscherbaum** [comment]
Let me rebase that, then I push it.

**Pull request merged**
