### PR TITLE
Document steps for installing pygresql for OSS database build

### PR DESCRIPTION
**Pull request by tylarb**
PyGreSQL may now be installed via pip or via Ubuntu apt.

Authored-by: Tyler Ramer <tramer@pivotal.io>

### CODE REVIEW

**Comment by ashwinstar** [comment]
This PR is continuing to fail on travis
```
Traceback (most recent call last):

  File "/home/travis/build/greenplum-db/gpdb/gpsql/bin/lib/gphostcachelookup.py", line 12, in <module>

    from gppylib.gphostcache import GpInterfaceToHostNameCache

  File "/home/travis/build/greenplum-db/gpdb/gpsql/lib/python/gppylib/gphostcache.py", line 30, in <module>

    from gppylib.commands import base

  File "/home/travis/build/greenplum-db/gpdb/gpsql/lib/python/gppylib/commands/base.py", line 34, in <module>

    from pg import DB

ImportError: No module named pg
```

**Comment by tylarb** [comment]
`pg` is provided by pygresql - we need to update the travis containers to contain pygresql

**Comment by tylarb** [comment]
@d All of the containers need pygresql installed - can you point me to where to do that or add them? 

For ubuntu, `apt-get install python-pygresql` should be sufficient. for OSX... I don't have access to OSX, but I'd assume the same steps needed for Centos - need libpq, pg_config (whatever is provided by `postgresql` packages in Centos) and gcc, but those should be installed already. Then pip install pygresql. Version should be 5.1.2.

**Comment by tylarb** [comment]
Most recent updates should fix travis. Will merge once CI goes green.

**Pull request merged**
