### PR TITLE
Remove use of pg_filespace from gpperfmon

### PR DESCRIPTION
**Pull request by cjcjameson**
- use the new fact that datadirs are in the gp_segment_configuration
- fix a few things with the gpperfmon behave tests (mostly for macOS)
   --> the change to mgmt_utils.py is to do the config file manipulation
   natively in python
   --> the change to the gp_bash_functions.sh is to use ASCII '
   characters so that python string comparison is happier

Author: C.J. Jameson <cjameson@pivotal.io>

### CODE REVIEW

**Comment by ashwinstar** [comment]
Thank You CJ, if it works feel free to commit the same. I am not sure if these tests get tested in PR pipeline. If they do then it would provide the feedback then can wait for it.

**Comment by cjcjameson** [comment]
The failure on the concourse pipeline is as follows... can I get some help to diagnose?

```
============== running regression test queries        ==============
	
test setup                ... ok
	
test replication_views_mirrored ... ok
	
test missing_xlog         ... FAILED
	

	
======================
	
 1 of 3 tests failed. 
	
======================
	

	
The differences that caused some tests to fail can be viewed in the
	
file "/tmp/build/ace8def5/gpdb_src/src/test/walrep/regression.diffs".  A copy of the test summary that you see
	
above is saved in the file "/tmp/build/ace8def5/gpdb_src/src/test/walrep/regression.out".
	

	
make[1]: *** [installcheck] Error 1
	
make: *** [installcheck-world] Error 2
	

	
======================================================================
	
DIFF FILE: ../gpdb_src/src/test/walrep/regression.diffs
	
----------------------------------------------------------------------
	

	
--- /tmp/build/ace8def5/gpdb_src/src/test/walrep/expected/missing_xlog.out	2018-01-05 01:25:45.838435283 +0000
	
+++ /tmp/build/ace8def5/gpdb_src/src/test/walrep/results/missing_xlog.out	2018-01-05 01:25:45.842435283 +0000
	
@@ -72,7 +72,7 @@
	
 select wait_for_replication_replay(200);
	
  wait_for_replication_replay 
	
 -----------------------------
	
- t
	
+ f
	
 (1 row)
	
 
	
 -- stop a mirror 
	

	
======================================================================
```

**Comment by xinzweb** [comment]
Basically, the mirror didn't catch up with the primary. Need to look at the log to see what's additional issue caused the mirror left behind. Thanks.

**Comment by cjcjameson** [comment]
Looking for an upcoming commit to fix flakiness in the failed test; merging into `walreplication` now

**Pull request merged**
