### PR TITLE
Remove unused Ubuntu-16.04 dockerfiles

### PR DESCRIPTION
**Pull request by kmacoskey**
Greenplum 6 will not be supported on Ubuntu 16.04, so there is no reason
to carry along these Dockerfiles. Ubuntu 18.04 will be supported and
when support for the platform is worked on then new docker images can be
created in this same location.

### CODE REVIEW

**Comment by benchristel** [comment]
+1 sounds good.
Note that we also checked `README.ubuntu.bash` and that file doesn't need to be removed because it's for people trying to compile on Ubuntu directly.

FYI @joaopapereira who had created the original Ubuntu docker files

—with @amilkh

**Comment by amilkh** [comment]
Good point Lav! There is a chance those docker files will just work with the new version of Ubuntu on gpdb6, although we are not testing it.

**Comment by benchristel** [comment]
Recently, we found we could no longer build GPDB6 on Ubuntu 16.04 because of libzstd compatibility issues. We are now using the libzstd (and many other libraries) from the system instead of shipping the version that's in Artifactory. This gives customers more flexibility in which version of the library they use. Unfortunately, it also means that GPDB 6 won't work on some older platforms, at least with the libraries available from the standard repositories.

We will eventually replace these Dockerfiles with Ubuntu 18.04 versions, but as we're not supporting Ubuntu for the GPDB 6 beta release it hasn't been an immediate priority for us. However, if it's going to cause developers pain to not have an Ubuntu image that works out of the box, we could possibly reprioritize... what do you think, @kmacoskey?

**Comment by kmacoskey** [comment]
I'm ok with holding off on merging this until we start working on Ubuntu 18.04 support. I wasn't sure if anyone was using these images for Greenplum 6 so I opened a PR to find out 😄 Although there are any process that rely on a Ubuntu 16.04 environment for Greenplum 6, they are soon going to need to change.

**Comment by lavjain** [comment]
Thanks @kmacoskey If libzstd was the only issue, I can add it to this dockerfile and test if gpdb compiles.

**Pull request closed without merging**
