### PR TITLE
Fix quoting issues in dispatching ALTER and DROP DATABASE.

### PR DESCRIPTION
**Pull request by hlinnaka**
Fixes github issue #3832.

### CODE REVIEW

**Comment by ashwinstar** [comment]
Seems gpcheckcat doesn't handle it correctly as well, PR pipeline complains

```
[ERROR] Executing: duplicate persistent entries check for gp_persistent_relation_node
  Execution error: ERROR:  syntax error at or near "with\"
LINE 18:               WHERE d.datname = 'funny"db'with\\quotes'
                                                   ^


          SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

          -- distribute catalog table from master, so that we can avoid to gather
          CREATE TEMPORARY TABLE _tmp_master ON COMMIT DROP AS
              SELECT gp_segment_id segid, tablespace_oid,database_oid,relfilenode_oid,segment_file_num, mirror_existence_state FROM gp_persistent_relation_node;
          SELECT tablespace_oid,database_oid,relfilenode_oid,segment_file_num, total, array_agg(segid order by segid) as segids
          FROM (
              SELECT segid, tablespace_oid,database_oid,relfilenode_oid,segment_file_num, count(*) as total
              FROM (
                   select segid, tablespace_oid,database_oid,relfilenode_oid,segment_file_num from _tmp_master
                   where mirror_existence_state != 6
                   union all
                   select gp_segment_id as segid, tablespace_oid,database_oid,relfilenode_oid,segment_file_num from gp_dist_random('gp_persistent_relation_node')
                   where mirror_existence_state != 6
              ) all_segments
                LEFT OUTER JOIN pg_database d ON (all_segments.database_oid = d.oid)
              WHERE d.datname = 'funny"db'with\\quotes'
              GROUP BY segid, tablespace_oid,database_oid,relfilenode_oid,segment_file_num
              HAVING count(*) > 1
          ) rowresult
          GROUP BY tablespace_oid,database_oid,relfilenode_oid,segment_file_num, total
```

**Comment by hlinnaka** [comment]
On 11/09/2017 06:34 PM, Ashwin Agrawal wrote:
> Seems gpcheckcat doesn't handle it correctly as well, PR pipeline complains

A-ha, fixed!

- Heikki

**Comment by ashwinstar** [comment]
pg_upgrade test seems next 

```
/tmp/build/34bc7e05/gpdb_src/contrib/pg_upgrade/tmp_check/upgrade/qd /tmp/build/34bc7e05/gpdb_src/contrib/pg_upgrade
Performing Consistency Checks
-----------------------------
Checking old data directory (/tmp/build/34bc7e05/gpdb_src/contrib/pg_upgrade/../../gpAux/gpdemo/datadirs//qddir/demoDataDir-1)ok
Checking old bin directory (/usr/local/gpdb/bin)            ok
Checking new data directory (/tmp/build/34bc7e05/gpdb_src/contrib/pg_upgrade/tmp_check/datadirs/qddir/demoDataDir-1)ok
Checking new bin directory (/usr/local/gpdb/bin)            ok
Connection to database failed: missing "=" after "with\\quotes'" in connection info string
```

**Comment by hlinnaka** [comment]
On 11/09/2017 08:33 PM, Ashwin Agrawal wrote:
> pg_upgrade test seems next
> 
> ```
> /tmp/build/34bc7e05/gpdb_src/contrib/pg_upgrade/tmp_check/upgrade/qd /tmp/build/34bc7e05/gpdb_src/contrib/pg_upgrade
> Performing Consistency Checks
> -----------------------------
> Checking old data directory (/tmp/build/34bc7e05/gpdb_src/contrib/pg_upgrade/../../gpAux/gpdemo/datadirs//qddir/demoDataDir-1)ok
> Checking old bin directory (/usr/local/gpdb/bin)            ok
> Checking new data directory (/tmp/build/34bc7e05/gpdb_src/contrib/pg_upgrade/tmp_check/datadirs/qddir/demoDataDir-1)ok
> Checking new bin directory (/usr/local/gpdb/bin)            ok
> Connection to database failed: missing "=" after "with\\quotes'" in connection info string
> ```

Yep. That was fixed in the upstream by commit 
a2385cac135bb8498a12b1af2cde18244c7be2b1. Unfortunately, that doesn't 
apply very cleanly, there were a lot of refactoring on pg_upgrade 
between 9.0 and 9.1, which was the oldest supported version when that 
was fixed. :-(. I might need to cherry-pick more pg_upgrade changes 
between 9.0 and 9.1 to make that work.

- Heikki

**Comment by hlinnaka** [comment]
Cherry-picking that seems more effort than I'm willing to pick up right now. So for now, I just added a DROP DATABASE to the test, to hide it from pg_upgrade. (and gpcheckcat, although this PR fixes that). Let's revisit this after we catch up with PostgreSQL 9.1, if not sooner.

**Comment by danielgustafsson** [comment]
> On 10 Nov 2017, at 09:15, Heikki Linnakangas <notifications@github.com> wrote:
> 
> Cherry-picking that seems more effort than I'm willing to pick up right now. So for now, I just added a DROP DATABASE to the test, to hide it from pg_upgrade. (and gpcheckcat, although this PR fixes that). Let's revisit this after we catch up with PostgreSQL 9.1, if not sooner.

Agreed, let’s await with the pg_upgrade refactorings for now since they are quite substantial. Listing this in a “known bugs” section in the pg_upgrade README.gpdb file would be a helpful reminder.

**Comment by ashwinstar** [comment]
On Fri, Nov 10, 2017 at 12:19 AM, Daniel Gustafsson <
notifications@github.com> wrote:

> > On 10 Nov 2017, at 09:15, Heikki Linnakangas <notifications@github.com>
> wrote:
> >
> > Cherry-picking that seems more effort than I'm willing to pick up right
> now. So for now, I just added a DROP DATABASE to the test, to hide it from
> pg_upgrade. (and gpcheckcat, although this PR fixes that). Let's revisit
> this after we catch up with PostgreSQL 9.1, if not sooner.
>
> Agreed, let’s await with the pg_upgrade refactorings for now since they
> are quite substantial. Listing this in a “known bugs” section in the
> pg_upgrade README.gpdb file would be a helpful reminder.
>

And creating GitHub issue as well. +1 for the PR.

**Comment by hlinnaka** [comment]
Ok, pushed and opened issue #3857 to track the remaining pg_upgrade issue.

**Pull request merged**
