### PR TITLE
Move union tinc tests to installcheck good

### PR DESCRIPTION
**Pull request by hsyuan**

### CODE REVIEW

**Comment by vraghavan78** [comment]
LGTM!

**Comment by ivannovick** [comment]
Love it!

**Comment by xinzweb** [comment]
+1

**Comment by hlinnaka** [comment]
Please put these into 'union_gp' rather than 'union' test. 'union' is from upstream, and I'd like to minimize changes there to make diffing/merging easier.

**Comment by hsyuan** [comment]
Yes, make sense. I will do it.

Thanks~
Haisheng Yuan

**Pull request closed without merging**
