### PR TITLE
Add compile_gpdb_centos7 job to gpdb5 pipeline

### PR DESCRIPTION
**Pull request by pengzhout**
@cjcjameson @ryantang  @hardikar  could you please help to review this PR? thanks

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pengzhout Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1295)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1295) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by cjcjameson** [comment]
This generally looks fine -- @schubert how soon can we get an ant-junit into the image that Pengzhou is using?

**Comment by pivotal-issuemaster** [comment]
@pengzhout Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1295)!

**Comment by pengzhout** [comment]
Thanks @cjcjameson  pushed and closed

**Pull request closed without merging**
