### PR TITLE
Adding a check for 64-bit interpreters with Windows to identify bundl…

### PR DESCRIPTION
**Pull request by kdunn926**
Creating PR for Windows-specific issue [#254](https://github.com/greenplum-db/gpdb/issues/254)

### CODE REVIEW

**Comment by ivannovick** [comment]
@kdunn926 can you update you organization profile to make the greenplum-db organization public, since you are a pivotal employee no need for CLA.  @schubert in case u need help, do we have an FAQ on this?

**Comment by asimrp** [comment]
We need the same check in all client side Python scripts that could potentially run on Windows.  Is `gpload` the only one?

**Comment by danielgustafsson** [comment]
Any news on getting this finished and into the tree? Ping @kdunn926 @asimrp

**Comment by asimrp** [comment]
LGTM.  @kdunn926 can you please commit this?

**Comment by kdunn926** [comment]
Not certain what exactly I need to do - I don't have write access to the repo but the PR is already committed?

**Comment by lij55** [comment]
Assumed this is already tested on Windows and what's the python version tested on Windows?

**Comment by kdunn926** [comment]
Apologies for the delay. This was wested on Windows 7 Enterprise with Python 2.5.4.

**Pull request closed without merging**
