### PR TITLE
Transaction commit replay code forgets to update minimum recovery poi…

### PR DESCRIPTION
**Pull request by paul-guo-**
…nt for dropped relation/database/tablespace.

### CODE REVIEW

**Comment by ashwinstar** [comment]
Please can you explain impact without the fix. Also, having test would be greatly helpful.

**Comment by asimrp** [comment]
I have the same question as Ashwin.  What's the impact if the minRecoveryPoint is not updated?

Can we please stick to 72 characters long commit message title?  E.g. in this case, the title can be rephrased to: `Update minRecoveryPoint during replay of distributed commit records`  and the impact can of not doing so can be described in the message.

**Comment by paul-guo-** [comment]
I dug this today. previously I read the tablespace function DoTablespaceDeletionForRedoXlog wrong. The function actually just does empty directory removal so we do not need to set minimum recovery point for it. But for code related to relation files/database directories dropping, we still need to set the minimum recovery point. 

I pushed the new code and updated the commit message as below.

```
    Update minRecoveryPoint if needed during replay of XLOG_XACT_DISTRIBUTED_COMMIT

    xlog XLOG_XACT_DISTRIBUTED_COMMIT is used on master to do 2pc commit, and
    similar to local transaction commit, there might be dropping of relation files
    or database directories when replaying the xlog.  Previously we do not update
    minimum recovery point when doing that.  Minimum recovery point is used to
    check consistency, when we replay to that point we know the database is
    consistent and then so-called invalid-pages during replay are not allowed. On
    upstream hot standby is allowed when it reaches consistency. Greenplum does not
    support that but we might support that later.
```

**Comment by paul-guo-** [comment]
@asimrp Sorry for the late reply. Yes what you said is one of the scenario the minimum recovery point want to resolve in theory, but on greenplum it seems that it is hard to find a case that meets the condition after some investigation and thinking, i.e.

There is drop/rewrite table with 2pc on master and the table had content modified.

For usual tables, there is no table content on master though we could easily create a 2pc case that drop/rewrite on the table;

For catalog table, we could easily create a 2pc case using begin/end block but drop/rewrite catalog files in begin/end is not easy (e.g. vacuum full is not allowed in begin/end block & truncate a catalog is not practical and not usual).

**Comment by asimrp** [comment]
Speaking of table rewrite, how about reindex `pg_class`?  This should rewrite both the pg_class indexes on master as well as all segments.

**Comment by paul-guo-** [comment]
> Speaking of table rewrite, how about reindex `pg_class`? This should rewrite both the pg_class indexes on master as well as all segments.

I tried previously. It does not work.

postgres=# begin;
BEGIN
postgres=# reindex table pg_class;
ERROR:  REINDEX of a catalog table cannot run inside a transaction block.

**Comment by paul-guo-** [comment]
I can not think out the scenario for this PR at this moment so I'd like to close this PR tomorrow if there is no more progress, but I feel this might be an issue some day in the future along with more new changes on master so maybe just let's keep them in mind.

**Pull request closed without merging**
