### PR TITLE
GPDB DOCS - Remove error table logging information.

### PR DESCRIPTION
**Pull request by mkiyama**
For COPY, CREATE EXTERNAL TABLE, and gpload, capturing formatting errors when importing data is no longer supported. Only capturing data in a internal GPDB log is supported.

For example, the INTO <error_table> clause is no longer supported by COPY and CREATE EXTERNAL TABLE.

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
Would wish for a reference when this feature was removed. There is plenty of old code out there which is using error tables - and if someone stumbles over the official documentation and sees no mention whatsoever about this feature ... This can be confusing.

**Comment by mkiyama** [comment]
@andreasscherbaum 
There will be 5.0.0 release notes that lists changes similar to the GPDB 4.3.x release notes.
This item will be in the release notes.

The 5.0.0 release notes will be available for alpha.

As for your question about when the feature was removed, I am not quite sure. It is deprecated in 4.3.x a while ago and was removed from OSS GPDB repo a while ago.
 
+ @dyozie

**Comment by andreasscherbaum** [comment]
@mkiyama As for the release notes: that's probably the last point where I go and search (because long, and unstructured) when I want to find out what happened to this feature.

If you search for: greenplum "log errors into"
on Google, you come up with more than 1000 hits. And that is just the publically available information. Not talking about myriads of scripts hidden somewhere in customer repos.

For the timing, the 4.3.9 docs state "next major release" - without ever saying what is the next available major release. Haven't checked other versions though ...

I'm thinking along the lines of the PostgreSQL documentation, which has a "Compatibility" section wherever it makes sense. That would be the right place to add this, and make this a link to the release notes.

**Comment by laixiong** [comment]
Any one could explain why do that , I'm confusing and want to know why.

**Comment by Eulerizeit** [comment]
@laixiong error tables have been replaced with error logs. Functionally this is aligning us with the Postgres implementation.

**Comment by dyozie** [comment]
This looks good to me.  @andreasscherbaum theRelease Notes have sections for "Changed Features" and "Removed Features".  Plus the Release Notes themselves are also linked as a "CHANGELOG" at the top of each page.  I'm not sure we can be any clearer than that.

**Pull request merged**
