### PR TITLE
Change slice info output order for easier debug

### PR DESCRIPTION
**Pull request by hsyuan**
Make sliceIndex, parentIndex, rootIndex and children near each other to see
slice debug output info easily.

### CODE REVIEW

**Comment by hsyuan** [comment]
Weird, it doesn't pass the CI, gpperfmon behave test, specifically.

**Comment by Eulerizeit** [comment]
Consistently???  That doesn't seem right.

**Comment by hsyuan** [comment]
close this PR for now, because it doesn't pass CI. Will reopen it after investigation.

**Comment by hsyuan** [comment]
applied feedback.

**Comment by hsyuan** [comment]
I want to trigger the test again.

**Pull request merged**
