### PR TITLE
gpcloud: hash and sign the payload

### PR DESCRIPTION
**Pull request by adam8157**
Signed-off-by: Adam Lee <ali@pivotal.io>
Signed-off-by: Yuan Zhao <yuzhao@pivotal.io>

### CODE REVIEW

**Comment by yydzero** [comment]
@adam8157 Would be good to add more description into the commits or PR so that community members could understand the context easier.

**Comment by adam8157** [comment]
```
When you send a request, you must tell Amazon S3 which of the preceding options you have chosen in your signature calculation, by adding the x-amz-content-sha256 header with one of the following values:

If you choose chunked upload options, set the header value to STREAMING-AWS4-HMAC-SHA256-PAYLOAD.
If you choose to upload payload in a single chunk, set the header value to the payload checksum (signed payload option), or set the value to the literal string UNSIGNED-PAYLOAD (unsigned payload option).
```

ref:
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html

We used to not hash or sign the payload, it's not quite secure with HTTPS off, which is enabled by default, and some compatible S3 services don't support "unsigned payload option", this commit fixes it.

**Comment by yydzero** [comment]
Do we need to add any test cases?

**Comment by adam8157** [comment]
All tests are hashed and signed now. It's OK :)

**Pull request merged**
