### PR TITLE
Reopen: add pg_resgroup to syscache

### PR DESCRIPTION
**Pull request by pengzhout**
This commit is a modified version of 8286b61f76014d1f3d58176ec3f12bb2dc9a9dcc,
the only difference is we put new entries to the end of cacheinfo array, so extensions
like madlib, plcontainer who linked with syscache.h can still have the same enum value of cache
identifier.

I'm curious who has experience in this area? Is it reasonable to add a new syscache entry to
a stable version? @Eulerizeit @ashwinstar @hlinnaka

### CODE REVIEW

**Comment by asimrp** [comment]
Is it possible to add a test (ICW) that mimics the madlib behavior?

**Comment by kaknikhil** [comment]
@pengzhout We spoke to @amilkh and it looks like that with the latest commit, you have made changes to the code so that madlib doesn't fail anymore. I would suggest forking this pipeline https://gpdb.bosh.pivotalci.info/teams/main/pipelines/5X_STABLE?groups=G%3AAdvancedAnalytics for your branch to make sure that all the madlib tests are green. Let us know if you need help.

Here is the old PR for reference that was merged and then reverted because of madlib failures: https://github.com/greenplum-db/gpdb/pull/4883

**Comment by pengzhout** [comment]
@asimrp Can't figure out a good way to do this in ICW, AdvancedAnalytics jobs can discover such issues although it can't report it in the first place like ICW.

**Comment by pengzhout** [comment]
@kaknikhil build a dev pipeline and all AdvancedAnalytics are green.

**Comment by amilkh** [comment]
Nice! I would say merge it.

**Comment by dsharp-pivotal** [comment]
We merged this commit after discussion with team members to make sure it will go into the next release.
Good news is that the 5X_STABLE pipeline is green!

-- d# and @amilkh

**Pull request merged**
