### PR TITLE
Two fixes for postmaster reset failure

### PR DESCRIPTION
**Pull request by eurekaka**

### CODE REVIEW

**Comment by eurekaka** [comment]
@hlinnaka @asimrp @ashwinstar Could you please help review these patches? thanks

**Comment by hlinnaka** [comment]
Can you have a look at PR 906, please? That one also included the missing logic for WAL writer. We'll want to refactor the code to match the upstream as close as possible, anyway, so I think it would make sense to get PR 906 committed first, and see what remains after that. Daniel is on vacation, so if you could have take over PR 906, and get that committed, that would be great.

**Comment by eurekaka** [comment]
Sorry for the late reply. I have went through https://github.com/greenplum-db/gpdb/pull/906, and I think the commit in that PR for WalWriterPID check is not complete, besides it does not contain fix for segment postmaster reset failure in this PR; so I prefer to merge this PR first if no objection against the code change, and rebase that PR. @danielgustafsson , any objections? thanks

**Comment by danielgustafsson** [comment]
Well, I'm even later since I (as Heikki mentioned) was offline for some time. Reading over this diff it makes sense, feel free to push this first and then I can rebase #906 over this.

**Comment by eurekaka** [comment]
Merged, thanks for the reviewing.

**Pull request closed without merging**
