### PR TITLE
Multi-dimensional arrays can now be used as arguments to a PL/python …

### PR DESCRIPTION
**Pull request by davecramer**
…function

(used to throw an error), and they can be returned as nested Python lists.

This makes a backwards-incompatible change to the handling of composite
types in arrays. Previously, you could return an array of composite types
as "[[col1, col2], [col1, col2]]", but now that is interpreted as a two-
dimensional array. Composite types in arrays must now be returned as
Python tuples, not lists, to resolve the ambiguity. I.e. "[(col1, col2),
(col1, col2)]".

To avoid breaking backwards-compatibility, when not necessary, () is still
accepted for arrays at the top-level, but it is always treated as a
single-dimensional array. Likewise, [] is still accepted for composite types,
when they are not in an array. Update the documentation to recommend using []
for arrays, and () for composite types, with a mention that those other things
are also accepted in some contexts.

The upstream patch is 94aceed31773

### CODE REVIEW

**Comment by hlinnaka** [comment]
This seems to be missing commit 510e1b8ecf2a6f0d91d50f41f6b7fd75242273a0, which I think is pretty important. Please also mention all the follow-up fix commits that I had to do in the upstream, to fix regression failures on various platforms, that this includes.

**Comment by pivotal-mike** [comment]
@davecramer Can we merge in the missing commit and merge this in?

**Comment by davecramer** [comment]
@pivotal-mike the whole commit does not go in, but I can work on it.

**Comment by davecramer** [comment]
@pivotal-mike this is already in here now https://github.com/greenplum-db/gpdb/pull/1292/commits/c7efc06416c7befccdf24a2146f9f8e439122eba

**Comment by pivotal-mike** [comment]
@davecramer Can you rebase this please?  It's failing the PR pipeline due to missing pipeline resources

**Pull request merged**
