### PR TITLE
docs - updates to SET/RESET/SHOW sql ref pages

### PR DESCRIPTION
**Pull request by lisakowen**
bring SET/RESET/SHOW sql ref pages up to postgres 12 content. there appears to be some greenplum-specific info on the SET page, and some postgres info on pages that wasn't in the original/6x docs.

questions:

1. on the SET page, is the statement about the DECLARE command that is preceeded by XXX still true?
2. the postgres SET reference page (https://www.postgresql.org/docs/12/sql-set.html) identifies some config params with a special syntax (like SET SEED, SET NAMES, SET SCHEMA, SET TIME ZONE).  only SET TIMEZONE is currently documented.  i tried the others on a greenplum 7 install, SET SEED and SET NAMES did not work (i may have invoked them incorrectly).  SET SCHEMA did work so i added it to the docs. i am not sure why it wasn't previously documented.  LET ME KNOW IF THIS SHOULD NOT BE IN THE DOCS, OR WE DO ACTUALLY SUPPORT SET SEED/NAMES.

doc review site links (behind vpn):
- SET ref page (can navigate to the others from there):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-setx/greenplum-database/GUID-ref_guide-sql_commands-SET.html

### CODE REVIEW

**Comment by QingMa-gp** [comment]
>the postgres SET reference page (https://www.postgresql.org/docs/12/sql-set.html) identifies some config params with a special syntax (like SET SEED, SET NAMES, SET SCHEMA, SET TIME ZONE). only SET TIMEZONE is currently documented. i tried the others on a greenplum 7 install, SET SEED and SET NAMES did not work (i may have invoked them incorrectly). SET SCHEMA did work so i added it to the docs. i am not sure why it wasn't previously documented. LET ME KNOW IF THIS SHOULD NOT BE IN THE DOCS, OR WE DO ACTUALLY SUPPORT SET SEED/NAMES.

```sql
postgres=# set names 'UTF-8';
SET
postgres=# set seed to 1;
SET
postgres=# select setseed(1);
 setseed 
---------
 
(1 row)
```
I tested `SET NAMES` and `SET SEED` locally and it worked properly. Therefore, I think this part of the document can remain consistent with the upstream.

**Comment by adam8157** [comment]
Was the statement about the DECLARE command true on 6X? Why we had that restriction, because the GUC rolling back is not guaranteed?

**Comment by QingMa-gp** [comment]
See comments in `CdbDispatchSetCommand()` and `cdbdisp_markNamedPortalGangsDestroyed()`
```
/*
 * Can not dispatch SET commands to busy reader gangs (allocated by cursors) directly because another
 * command is already in progress.
 * Cursors only allocate reader gangs, so primary writer and idle reader gangs can be dispatched to.
 */

/*
 * SET command can not be dispatched to named portal (like CURSOR). On the one
 * hand, named portal might be busy and also it should not be affected by
 * the SET command. Then when a dispatcher state of named portal is destroyed,
 * its gang should not be recycled because its guc was not set, so need to mark
 * those gangs as not recyclable.
 */

```
Thanks @kainwen for locating these comments. I have reviewed the relevant historical commits and found that the solution that initially fixed this issue is consistent with the current code(https://github.com/greenplum-db/gpdb/commit/d272592981b3cf8e65a32c01b6e5691170ba4b53), so it is unclear why there is such a restriction. 
Since the set command won't be sent to the cursor's gang and the cursor's gang won't be reused, I think it's okay to remove this statement. Any ideas? @adam8157

**Comment by lisakowen** [comment]
following up @QingMa-gp - is it safe to remove the statement about DECLARE?

**Comment by QingMa-gp** [comment]
@lisakowen  Yes, it is safe to remove the statement about DECLARE.

**Review by QingMa-gp — APPROVED** [review]

**Pull request merged**
