### PR TITLE
Move all auto-generated lines from pg_proc.h to pg_proc_catullus.h

### PR DESCRIPTION
**Pull request by hlinnaka**
pg_proc.h is split into two parts: pg_proc.h and pg_proc_catullus.h.
After the split, pg_proc.h contains functions we've inherited from upstream,
and is mostly identical to the upstream version. This makes diffing and
merging with upstream easier. All the upstream functions have been removed
from pg_proc.sql, as they are no longer auto-generated. Instead of modifying
pg_proc.h, catullus.pl is now used to create pg_proc_catullus.h, which
contains all the auto-generated DATA entries for the functions in
pg_proc.sql.

For the upstream-inherited DATA entries in pg_proc.h, remove the columns for
the columns that are not present in upstream. This was needed again to make
pg_proc.h closer to the upstream version. Also, remove extra comments and
revert whitespace changes compared to upstream.

To compensate for the missing columns, introduce a new perl script,
processs_col_defaults.pl that is run at build time, which adds the missing
columns back to any DATA rows that miss them, before they are fed to
genbki.sh. All the GPDB-added columns are marked with a magic
GPDB_COLUMN_DEFAULT() macro, similar to the CATALOG() and DATA() macros
which tells process_col_defaults.pl what values to insert into the missing
columns.

WORK-IN-PROGRESS: For demonstration purposes, I did that for the section of
procedures in the file, labeled as OIDS 1 - 99 (confusingly, there are a few
functions outside that range in the section though). The idea is to do the
same for *all* functions. And also for all the types in pg_type.h; the same
mechanism should work for it, although I haven't tried it yet.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Things to note while reviewing:

So the goal of this is to minimize the diff to upstream of pg_proc.h. At the same time, the end result of what goes into the catalogs is not supposed to change; this is just refactoring.  I haven't cleaned up all the whitespace difference vs. upstream, but you can mask them out with git diff's -w option, until it's cleaned up. Also note that I go through all the functions yet, only the first batch. Before pushing this, I intend to also verify that the resulting catalogs are unchanged, by dumping the contents of pg_proc with "SELECT oid, * FROM pg_proc" before and after this change, and checking that they match. And the same for pg_type.

So, how does this new mechanism for giving defaults for extra columns look like? Need any more comments somewhere? Anything else?

**Comment by asimrp** [comment]
Looks good to me.  With this change, we can continue using pg_proc.sql to define catalog changes and let catullus.pl generate the headers.  And also get the advantage of easily merging with upstream.

One suggestion: can we rename pg_proc_catullus.h to pg_proc_gp.h?  That seems consistent with the scheme we are following for tests.

Do we have any Greenplum specific schema changes that are different from addition of new columns?  E.g. changing type of a column?  Those, if any, will have to be addressed separately.

**Comment by hlinnaka** [comment]
I rebased this over current master, and finished moving all the remaining pg_proc entries to the new system. I also fixed the typo that Asim pointed out (thanks!). This is now complete, although we might want to improve a few things before merging:

 TODO: It's not nice that all SQL-language functions have to be marked manually
    with 'c' in prodataaccess column. I think we need to teach
    process_col_defaults.pl to mark them as such automatically.
    
    TODO: Also, instead of the system where some GPDB-added DATA rows can have
    more columns than usual, it might be nicer to have an extra DATA-like directive
    that you could put on a separate line after the main DATA line, to give
    values for extra columns. Something like DATA_EXTRA(prodataacess = 'r')

**Comment by hlinnaka** [comment]
> One suggestion: can we rename pg_proc_catullus.h to pg_proc_gp.h? That seems consistent with the scheme we are following for tests.

Works for me. I'll rename it before merging.

> Do we have any Greenplum specific schema changes that are different from addition of new columns? E.g. changing type of a column? Those, if any, will have to be addressed separately.

Not in pg_proc.h at least. I'm not sure about other catalogs, but I'm not too worried about them anyway. There just isn't that many rows in any other catalog table to become such a big burden, even if their .h files need to be maintained manually.

**Comment by hlinnaka** [comment]
Oh, I also dumped pg_proc from a cluster created before and after this change, and verified that the contents are identical.

**Comment by entong** [comment]
Can we hold off catalog changes for the folks in Beijing? They are about to merge some big commits from a team branch having catalog changes including jsonb etc.

**Comment by yydzero** [comment]
it will be very nice if we could merge 4.4dev changes to master before this
change.

Max is working on merging right now.

On Thu, Nov 12, 2015 at 7:12 AM, Entong Shen <notifications@github.com>
wrote:

> Can we hold off catalog changes for the folks in Beijing? They are about
> to merge some big commits from a team branch having catalog changes
> including jsonb etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/pull/52#issuecomment-155938995>.
>



-- 
Best Regards,
Yandong

**Comment by hlinnaka** [comment]
How long will it take? This commit would be ready for pushing, and I 
haven't seen a pull request, let alone reviewed, the upcoming 4.4dev 
stuff. I'm not against waiting if that's the best order, but I would 
hate to have this sit and bitrot for weeks.

Which catalogs will those changes modify, and how? If I push this first, 
I promise I'll help to fix the damage to the 4.4dev patch once that's 
published...



- Heikki

**Comment by yydzero** [comment]
go ahead with your commit, if we could not file pull-request today, then we
will work on merging conflicts.

On Thu, Nov 12, 2015 at 8:00 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> How long will it take? This commit would be ready for pushing, and I
> haven't seen a pull request, let alone reviewed, the upcoming 4.4dev
> stuff. I'm not against waiting if that's the best order, but I would
> hate to have this sit and bitrot for weeks.
>
> Which catalogs will those changes modify, and how? If I push this first,
> I promise I'll help to fix the damage to the 4.4dev patch once that's
> published...
>
>
>
> - Heikki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/pull/52#issuecomment-155948986>.
>



-- 
Best Regards,
Yandong

**Comment by hlinnaka** [comment]
On 11/12/2015 02:13 AM, Yandong Yao wrote:
> go ahead with your commit, if we could not file pull-request today, then we
> will work on merging conflicts.

Ok, thanks!

- Heikki

**Comment by hlinnaka** [comment]
Pushed

**Pull request closed without merging**
