### PR TITLE
Copy dump sql file for QD to QE nodes to fix pg_upgrade issue related…

### PR DESCRIPTION
**Pull request by paul-guo-**
… to greenplum partition tables.

Since we do not store partition definition on QE so there will be some
issues during pg_upgrade testing for greenplum partition implementation.

For example, we create test data set by creating a table with partitions
and then renaming a partition via 'alter table ... rename partition'
and then run the pg_upgrade test. In greenplum, the constraint names are
not renamed for partition renaming. Since on QD the dump (replay) sql
reconstructs the partition definition with the renamed partition names
and thus the constraint names will all be the renamed ones after running
the dump sql file, but on QE, the dump sql just reconstructs the table
definition using previous constraint names, without knowing the partition
definition.  This will lead to constraint name mismatch between QD and QE
for that partition and its children.

In this patch, we copy the QD dump sql file to QE also and let QE filters
partition related system table entries later. In theory, we could have
another solution: add a constraintname parameter in partition definition for
upgrade only in the dump sql, just like MPP-6297 (search the code with
this keyword), however the solution above is faster since we just need
to dump the sql file one time (i.e. on QD only).

Co-authored-by: Max Yang <myang@pivotal.io>

### CODE REVIEW

**Comment by paul-guo-** [comment]
@d 
1) Segment will have entries for partition tables/constraints in pg_inherits, pg_class, pg_constraint, but not in pg_partition*. 

2) The main issue we saw during pg_upgrade is that:

For data set which is generated by
```
create table sto_altap3 (col1 bigint, col2 date, col3 text, col4 int)           
 with(appendonly=true) distributed randomly                                     
 partition by range(col2) subpartition by list (col3)                           
 subpartition template (                                                        
  default subpartition subothers,                                               
  subpartition sub1 values ('one'),                                             
  subpartition sub2 values ('two'))                                             
 (default partition others, start(date '2008-01-01') end(date '2008-04-30')     
  every(interval '1 month'));                                                   
Alter table sto_altap3 RENAME PARTITION FOR ('2008-01-01') TO jan08; 
```

pg_dump will generate dump sql file for QD and each QEs separately, but previously
pg_upgrade copies the OID dump file only from QD to QEs to guarantee the oid consistency. SQL similar to this for relation, type, etc:
``` 
SELECT binary_upgrade.preassign_relation_oid('176774', 'newpart', '2200');
```

For the partion case above, QD dump sql will be like this:
```
CREATE TABLE sto_altap3 (
    col1 bigint,
    col2 date,
    col3 text,
    col4 integer
)
WITH (appendonly=true) DISTRIBUTED RANDOMLY PARTITION BY RANGE(col2)
          SUBPARTITION BY LIST(col3)
          (
          PARTITION jan08 START ('2008-01-01'::date) END ('2008-02-01'::date) EVERY ('1 mon'::interval) WITH (tablename='sto_altap3_1_prt_jan08', orientation=
                  (
                  SUBPARTITION sub1 VALUES('one') WITH (tablename='sto_altap3_1_prt_jan08_2_prt_sub1', orientation=row , appendonly=true ),
                  SUBPARTITION sub2 VALUES('two') WITH (tablename='sto_altap3_1_prt_jan08_2_prt_sub2', orientation=row , appendonly=true ),
                  DEFAULT SUBPARTITION subothers  WITH (tablename='sto_altap3_1_prt_jan08_2_prt_subothers', orientation=row , appendonly=true )
                  ),
          START ('2008-02-01'::date) END ('2008-03-01'::date) EVERY ('1 mon'::interval) WITH (tablename='sto_altap3_1_prt_3', orientation=row , appendonly=tru
                  (
                  SUBPARTITION sub1 VALUES('one') WITH (tablename='sto_altap3_1_prt_3_2_prt_sub1', orientation=row , appendonly=true ),
                  SUBPARTITION sub2 VALUES('two') WITH (tablename='sto_altap3_1_prt_3_2_prt_sub2', orientation=row , appendonly=true ),
                  DEFAULT SUBPARTITION subothers  WITH (tablename='sto_altap3_1_prt_3_2_prt_subothers', orientation=row , appendonly=true )
                  ),
......................
```

pg_dump  generates the partition table like this on QE.
```
CREATE TABLE sto_altap3_1_prt_jan08 (
    col1 bigint,
    col2 date,
    col3 text,
    col4 integer,
    CONSTRAINT sto_altap3_1_prt_2_check CHECK (((col2 >= '2008-01-01'::date) AND (col2 < '2008-02-01'::date)))
)
WITH (appendonly=true);
```

So it fails with message like below.
```
pg_upgrade_dump_db.sql:963: ERROR:  no pre-assigned OID for pg_constraint tuple "sto_altap3_1_prt_2_check" (namespace:2200 keyOid1:16499 keyOid2:0)
```
because QD delivers (SQL file copying) the following oid+contraint_name information to QE.
```
SELECT binary_upgrade.preassign_type_oid('16500', 'sto_altap3_1_prt_jan08', '2200');
```

**Comment by d** [comment]
@Eulerizeit sounds like we are now working around a bug in `ALTER TABLE ... RENAME PARTITION` in that it fails to dispatch the renaming of constraints to the segments. Which backlog should that go in?

@paul-guo- thank you for the example!

**Comment by paul-guo-** [comment]
@d I think the previous code is weight better design. I mean: With "alter table .. rename partition", the constraints are not renamed on both master and segments. Since 1) constraint renaming is not needed from the perspective of functionality. 2) if you rename this partition constraint name you will need to rename for all its descendants which might be heavy-weight. Actually with this command, it still renames all child-table names for that partition. I'm wondering whether we should fix this like what we did for constraint after applying this patch, given during pg_upgrade in the dump sql file, the partition create DDL already includes table name for each partition.

**Comment by Eulerizeit** [comment]
> @Eulerizeit sounds like we are now working around a bug in ALTER TABLE ... RENAME PARTITION in that it fails to dispatch the renaming of constraints to the segments. Which backlog should that go in?

It is owned by C&S. We are going to have someone working on the upgrade starting this week to look at these things.

**Comment by jchampio** [comment]
@paul-guo- @danielgustafsson @Eulerizeit I need some help determining whether this is still a PR that needs review, since so much has changed since April. Daniel, does the pg_upgrade work that you're about to merge change/obsolete this approach?

**Comment by danielgustafsson** [comment]
> On 25 Jul 2018, at 17:35, Jacob Champion <notifications@github.com> wrote:
> 
> @paul-guo- @danielgustafsson @Eulerizeit I need some help determining whether this is still a PR that needs review, since so much has changed since April. Daniel, does the pg_upgrade work that you're about to merge change/obsolete this approach?

There are some bits and pieces in here that I’d like to cherrypick, but there is little need to review it for now. I would prefer to keep it open to not lose track, but we may want to slap a TODO label or something on it.

**Comment by jchampio** [comment]
> I would prefer to keep it open to not lose track

That's fine with me -- no TODO labels or anything needed, IMO, now that we have this conversation recorded in the PR. I just wanted to make sure I wasn't ignoring a story that needed active review.

**Comment by paul-guo-** [comment]
Discussed with @danielgustafsson @jchampio and had a conclusion. Since the newest design is different than this PR, I'm closing this PR for now. truncate_pg_partition() is needed but let Daniel and Jacob determine how to handle the function since they have updated context of the pg_upgrade implementation.

**Pull request closed without merging**
