### PR TITLE
Backport moving-average optimization from PostgreSQL 9.6

### PR DESCRIPTION
**Pull request by hlinnaka**
See discussion at https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/ZXC5VrdJkKM/SR6wS6wtDAAJ

This is now ready to be reviewed, and almost ready to be committed.

There's one known regression test failure:

```
-- Check that all combine functions have signature
-- combine(transtype, transtype) returns transtype
-- NOTE: use physically_coercible here, not binary_coercible, because
-- max and min on abstime are implemented using int4larger/int4smaller.
SELECT a.aggfnoid, p.proname
FROM pg_aggregate as a, pg_proc as p
WHERE a.aggcombinefn = p.oid AND
    (p.pronargs != 2 OR
     p.prorettype != p.proargtypes[0] OR
     p.prorettype != p.proargtypes[1] OR
     NOT physically_coercible(a.aggtranstype, p.proargtypes[0]));
       aggfnoid       |      proname      
----------------------+-------------------
 pg_catalog.pivot_sum | int8_matrix_accum
(1 row)
```
This is because the definition of that aggregate, `pivot_sum(_int4, _text, text, int4)` is bogus: the aggregate's transition type is int8[], but the transition function's (`int8_matrix_accum`) argument is declared as type int4[]. So the executor will pass an int4[] argument to a function that expects an int8[]. At a quick look, I think it works, because the C implementation of `int8_matrix_accum` checks the argument array's element OID that's embedded in the array datum itself, and ignores the declared type. But it's pretty questionable.

The reason that started to fail now, is that that sanity check query was added to opr_sanity as part of this patch set. If you run the same query without this PR, it still fails.

### CODE REVIEW

**Comment by hlinnaka** [comment]
This is passing all the regression tests now, and - barring any objections or suggestions - is ready to be pushed. Please review!

**Comment by hlinnaka** [comment]
One thing that's worth noting is that this changes the reported precision of the AVG()'s result. Before:
```
postgres=# select avg(g) from generate_series(1,10) g;
 avg 
-----
 5.5
(1 row)
```

After:
```
        avg         
--------------------
 5.5000000000000000
(1 row)
```

The new behaviour is what PostgreSQL has always done. (I actually slightly prefer the GPDB behaviour of dropping the extra zeros, but it's not a big deal, and I don't want to carry a patch over PostgreSQL to keep that difference.)

**Comment by hlinnaka** [comment]
Rebased, and fixed the documentation for the "prefunc" -> "combinefunc" renaming. The rest of the commits still need documentation, but given that we didn't have any documentation on the old "invtransfn" and "invprefn" functions either, seems like that can be done as a separate PR.

**Comment by d** [comment]
This is really nice!

**Comment by d** [comment]
Also, do we plan to make deparsing the Aggref's better? Something analogous to the effect of the 9.6 patch postgres/postgres@59eb5512790

**Comment by d** [comment]
Where's the Github button to undo a "request changes" without giving an approval?

**Comment by ashwinstar** [comment]
On Wed, Aug 29, 2018 at 3:37 PM Jesse Zhang <notifications@github.com>
wrote:

> Where's the Github button to undo a "request changes" without giving an
> approval?
>
Its computers and boolean :-)

**Comment by hlinnaka** [comment]
On 30/08/18 01:32, Jesse Zhang wrote:
> Also, do we plan to make deparsing the Aggref's better? Something 
> analogous to the effect of the 9.6 patch postgres/postgres@59eb551 
> <https://github.com/postgres/postgres/commit/59eb5512790>

I actually played with that yesterday. I'd like to backport the 
setrefs.c changes from upstream, which "split" an Aggref into the 
partial and final stages. Currently cdbgroup.c works pretty hard to 
build a Subquery Scan between the stages, and replaces references in the 
upper query with Vars that point to the generated subquery. It's needed, 
because the finalize stage needs to refer to the output of the partial 
stage, and there's no way to do that within one query. In the upstream, 
you don't need a subquery, because setrefs.c takes care of that. Anyway, 
I was going to backport those ruleutils.c changes as part of that, but 
I'm not sure if we'll get that done. I was doing all that to help with 
making the GROUPING SETS rewrite more MPP-aware, and I'm not sure we'll 
get to that.

So we'll see. Let's try to finish this PR first, before we dive deeper 
into the rabbit hole.

- Heikki

**Comment by d** [comment]
So I was going over "Make use of serial/deserial functions to enable 2-phase aggregates." (commit fa2e921), and I paused on interpreting this:

> Previously, two-phase (or three-phase) aggregation was not possible for
aggregates with 'internal' transition type.

I played with the compilable commit immediate before fa2e921 "Make use of serial/deserial functions to enable 2-phase aggregates.", and I can observer that none of the aggregates with a valid `combinefn` has a `transtype` of `internal`. So we don't split these aggregates because we don't have `combinefn` for them in the catalog. I am aware that _actually_ sending a value of type `internal` over the network will probably make the receiver (or the sender, or both) explode sooner or later because even though `internal` is pass-by-val, we almost always smuggle a pointer in it, and pointers from a different process is bogus. Now I'm curious, do we have anything in code that actually guards against that? (barring your change of backporting serialfn / deserialfn from 9.6?)

My current understanding is that the ordering of the commits is intentional, and the omission of `combinefn` for aggregates with an `internal` trans type at commit fa2e921 is also intentional. But my feedback would be the wording on that commit could have been clearer.

@joaopapereira and @d

**Comment by hlinnaka** [comment]
On 30/08/18 20:52, Jesse Zhang wrote:
> So I was going over "Make use of serial/deserial functions to enable 
> 2-phase aggregates." (commit fa2e921 
> <https://github.com/greenplum-db/gpdb/commit/fa2e92150feca0c96040587a7e3ce2f982f10f4c>), 
> and I paused on interpreting this:
> 
>     Previously, two-phase (or three-phase) aggregation was not possible for
>     aggregates with 'internal' transition type.
> 
> I played with the compilable commit immediate before fa2e921 
> <https://github.com/greenplum-db/gpdb/commit/fa2e92150feca0c96040587a7e3ce2f982f10f4c> 
> "Make use of serial/deserial functions to enable 2-phase aggregates.", 
> and I can observer that none of the aggregates with a valid |combinefn| 
> has a |transtype| of |internal|. So we don't split these aggregates 
> because we don't have |combinefn| for them in the catalog. I am aware 
> that /actually/ sending a value of type |internal| over the network will 
> probably make the receiver (or the sender, or both) explode sooner or 
> later because even though |internal| is pass-by-val, we almost always 
> smuggle a pointer in it, and pointers from a different process is bogus. 
> Now I'm curious, do we have anything in code that actually guards 
> against that? (barring your change of backporting serialfn / deserialfn 
> from 9.6?)

There's nothing to prevent that specifically. However, you need to be 
superuser to create an aggregate with internal transition type. For 
superusers, it's just a case of "don't do that".

> My current understanding is that the ordering of the commits is 
> intentional, and the omission of |combinefn| for aggregates with an 
> |internal| trans type at commit fa2e921 
> <https://github.com/greenplum-db/gpdb/commit/fa2e92150feca0c96040587a7e3ce2f982f10f4c> 
> is also intentional. But my feedback would be the wording on that commit 
> could have been clearer.

Right, the combine/serial/deserial functions for those aggregates are 
added in a later commit in the series.

- Heikki

**Comment by hlinnaka** [comment]
On 30/08/18 21:05, Jesse Zhang wrote:
>     Overall this is very good. We especially appreciate the effort that
>     goes into organizing the patch into fairly atomic commits in a very
>     disciplined order, that really helps reviewing.

Thanks! I had to edit and re-edit and rewrite pg_aggregate.h many times 
over during development, to keep each commit working. But I think it was 
worth the effort in the end.

>     Unrelated question: I'm curious what led to the (now believed to be
>     accidental) omission of changes in |pg_aggregate.h| and what can we
>     do in the future to not miss those. We noticed that the test added
>     in upstream commit d95425c
>     <https://github.com/greenplum-db/gpdb/commit/d95425c8b9d3ea1681bd91b76ce73be95ca5ee21>
>     can only catch regressions in the new moving-window aggregate
>     functions for |bool_and| and friends, but it does nothing to catch
>     the case when we forget to register those in the catalog ...
One thing that helps is that after these changes, pg_aggregate has the 
same shape as in PostgreSQL 9.6. So you can do "git diff -w 
pgsql/REL9_6_STABLE", and review the differences easily, to see that 
we're not missing anything.

If you can articulate a rule for this, we could add a check in 
'opr_sanity_gp' test. But I think it's fine as it is now.

- Heikki

**Comment by d** [comment]
> There's nothing to prevent that specifically. However, you need to be
> superuser to create an aggregate with internal transition type. For
> superusers, it's just a case of "don't do that".

My bad for not being very clear the first time:

1. I'm aware that the ability to combine one trans function that returns `internal` with another finalize function that takes as input `internal` is problematic and hence the super user restriction
1. I'm also aware that it's practically a bad idea -- if not impossible -- to send `internal` directly over the network, hence the need of the serialize / deserialize functions

The kind of answer I was looking for, was either "No, planner doesn't guard against a combine func which takes internal but doesn't supply a serial/deserial pair", or "Yes planner checks it somewhere" or "no we guard it at execution time".

Unrelated question: I noticed that `make_agg_arg` in `parse_agg.c` is a small refactoring that came out of 9.6, is that why not every piece of code that duplicates the dummy param logic is replaced with `make_agg_arg`?

**Comment by hlinnaka** [comment]
Pushed, thanks for the review!

**Comment by hlinnaka** [comment]
On 31/08/18 01:30, Jesse Zhang wrote:
>     There's nothing to prevent that specifically. However, you need to be
>     superuser to create an aggregate with internal transition type. For
>     superusers, it's just a case of "don't do that".
> 
> My bad for not being very clear the first time:
> 
>  1. I'm aware that the ability to combine one trans function that
>     returns |internal| with another finalize function that takes as
>     input |internal| is problematic and hence the super user restriction
>  2. I'm also aware that it's practically a bad idea -- if not impossible
>     -- to send |internal| directly over the network, hence the need of
>     the serialize / deserialize functions
> 
> The kind of answer I was looking for, was either "No, planner doesn't 
> guard against a combine func which takes internal but doesn't supply a 
> serial/deserial pair", or "Yes planner checks it somewhere" or "no we 
> guard it at execution time".

There's a check in the executor:

https://github.com/greenplum-db/gpdb/blob/master/src/backend/executor/nodeAgg.c#L2226

But come to think of it, we really should check for that in the planner. 
Otherwise you can get a plan that fails at execution time. There are 
checks in the upstream for this, in get_agg_clause_costs_walker(), but I 
didn't backport those because that function had been heavily modified, 
and I decided to stick close to the 9.2 version in that function, rather 
than backport from 9.6. I'll add a planner check as a separate PR.

> Unrelated question: I noticed that |make_agg_arg| in |parse_agg.c| is a 
> small refactoring that came out of 9.6, is that why not every piece of 
> code that duplicates the dummy param logic is replaced with |make_agg_arg|?

Yeah, it's a balancing act on what to backport and what not. Perhaps I 
should've backported more of that. I also wasn't sure if I should 
backport the refactoring of build_aggregate_fnexprs() into separate 
build_aggregate_*_fnexpr() functions (from commit 804163bc25). So it 
ended up being a mix: build_aggregate_fnexprs() returns the expressions 
for the trans, invtrans, final, and combine functions, but there are 
separate functions for the serial and deserial functions.

Thanks for the review!

- Heikki

**Comment by d** [comment]
@hlinnaka you still missed my commit ...

**Comment by d** [comment]
I would have pushed in the missing bits had CI not been red on `gpexpand_1`, anyway, want to take a quick look at the "missing bits" over at https://github.com/greenplum-db/gpdb/pull/5655 ?

**Comment by hlinnaka** [comment]
On 1 September 2018 00:38:13 EEST, Jesse Zhang <notifications@github.com> wrote:
>@hlinnaka you still missed my commit ...

Oops, I lost it when I rebased :-(. Sorry, and thanks for fixing it!


- Heikki

**Pull request merged**
