### PR TITLE
Remove sles12 jobs

### PR DESCRIPTION
**Pull request by baotingfang**
We want to support sles12 platfrom for gpdb6/7, but now
    the build artifacts are missing ORAC,and the ORCA ICW jobs
    are gree, that's false positive. Here, we removed all the
    sles12 jobs.

[#172595616]

Authored-by: Tingfang Bao <baotingfang@gmail.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by kmacoskey** [comment]
👍 The future Greenplum 7 (master) may not ever target SLES 12 as a supported platform.

We can backport this to 6X_STABLE as well, because it is not yet a supported platform. It will be at some point in the future.

**Comment by chrishajas** [comment]
Can you expand on the missing ORCA artifacts and ICW being a false positive? SLES ICW seems to be using the ORCA answer files (the output contains `Optimizer enabled. Using optimizer answer files whenever possible`).

**Comment by d** [comment]
Good riddance

**Comment by xinzweb** [comment]
Follow the slack discussion, since gporca compiled inside the gpdb, there is no longer separated shared libraries. I went to the test machine, and queried the optimizer version:

```
> psql postgres
psql (9.4.24)
Type "help" for help.

postgres=# explain select 1
postgres-# ;
                   QUERY PLAN
------------------------------------------------
 Result  (cost=0.00..0.00 rows=1 width=4)
   ->  Result  (cost=0.00..0.00 rows=1 width=1)
 Optimizer: Pivotal Optimizer (GPORCA)
(3 rows)

postgres=# select gp_opt_version();
               gp_opt_version
---------------------------------------------
 GPOPT version: 4.0.0, Xerces version: 3.1.2
(1 row)
```

Thank @chrishajas for the missing context. Now it starts to make sense.

**Comment by d** [comment]
Yeah why have we had these tests in the pipeline, if the final RC job doesn't depend on them? Each run of `icw_planner_sles12` seems to take about 2.5 hours

**Comment by xinzweb** [comment]
Thanks @d. We further discussed with @kmacoskey, and yes with all the context, we don't need the SLES12 jobs for now. 

@baotingfang I just did a search on `sles12`, and found the `pipelines/gpdb_master-generated.yml` need to be regenerated to remove the `sles12` there using `./gen_pipeline.py -t prod`.

**Pull request merged**
