### PR TITLE
Remove gp_cancel_query() and friends.

### PR DESCRIPTION
**Pull request by hlinnaka**
The upstream pg_cancel_backend() function should work fine on GPDB. It's
not exactly the same: in gp_cancel_query(), you would pass the sesssion ID
and command ID as argument, while pg_cancel_backend() takes a PID. But it
seems just as good from a usability point of view. Let's avoid the
duplicate code, and remove gp_cancel_query().

Also remove the gp_cancel_query_print_log and gp_cancel_query_delay_time
GUCs. They were not directly related to gp_cancel_query() - they would
have an effect on cancellations caused by pg_cancel_backend() or
statement_timeout, too. But they were marked as "developer options", and
they printed the session and command ID so I think they were meant to be
used with gp_cancel_backend(). I don't think anyone uses them, though, so
let's just remove them, rather than change them to print PIDs.

### CODE REVIEW

**Comment by hlinnaka** [comment]
> Should this warrant a deprecation notice though?

I don't think that's needed. I believe we never exposed this to users. You would have to issue a manual CREATE FUNCTION to make the function callable from SQL. It wasn't documented, and googling around, I don't see any random blog posts or anything else to describe how to do that either. So I believe this was a hidden, developer-only, thing.

**Comment by ivannovick** [comment]
Are we sure its not callable?  If it is we can just add it to release notes for 6.0 to be sure we notify users in the list of changes from 5.x  @dyozie

**Comment by dyozie** [comment]
Our docs have only ever referenced pg_cancel_backend as far as I can tell.
I can't find any references to gp_cancel_*

-David

**Comment by hlinnaka** [comment]
Ok, pushed the removal. Thanks for checking!

**Pull request merged**
