### PR TITLE
Make git submodules clonable recursively without github keys

### PR DESCRIPTION
**Pull request by tushar-dadlani**
- If you are working on a computer and want to get the entirety of the
  source code of gpdb including submodules, you cannot do that as you would need your github
  key to clone the submodules.

### CODE REVIEW

**Comment by tushar-dadlani** [comment]
@cjcjameson the target audience in my head for this PR are the people who don't have a github account but want to checkout GPDB source code. The current submodule structure doesn't allow a new user to checkout the entire source code without a github key loaded.

**Comment by cjcjameson** [comment]
Oh, right, even for public repos, Github requires that it's at least using an SSH key that it can match. Hrm, I'm still against it. We want contributors to participate via github. Have you heard of a specific such audience for this?

I feel like maybe it's a smell against our use of submodules. Or maybe if there's a strong need for non-Github checking-out of the code, we might need to host it somewhere else.

**Comment by hlinnaka** [comment]
On 03/07/2017 08:42 PM, C.J. Jameson wrote:
> Oh, right, even for public repos, Github requires that it's at least
> using an SSH key that it can match. Hrm, I'm still against it. We
> want contributors to participate via github. Have you heard of a
> specific such audience for this?

Automated scripts. Or just a drive-by hacker without a github account. 
Or someone behind a lame firewall.

To turn the question around, why would we not use https urls? Is there 
any downside to using https, instead of ssh?

BTW, github seems to recommend https urls:

https://help.github.com/articles/which-remote-url-should-i-use/

> I feel like maybe it's a smell against our use of submodules. Or
> maybe if there's a strong need for non-Github checking-out of the
> code, we might need to host it somewhere else.

Or, we can use https urls, no?

- Heikki

**Comment by cjcjameson** [comment]
Indeed, I was probably being over dramatic. I find that https, with password + two factor auth, is a lot more cumbersome than having my ssh key. So I'd rather that be the default. But I realize that the burden of password + 2FA doesn't apply here. So if I'm in the minority here, then it's just a personal problem, and I do know how to repoint my remotes if they end up https. Carry on -- don't mind me!

**Comment by Eulerizeit** [comment]
Wait.  Is this PR adding the HTTPS functionality AND removing the SSH key
option?

-- Rob

**Comment by tushar-dadlani** [comment]
@Eulerizeit only for submodules. Your submodule update will continue to work as expected. If you want to make changes to code that lives in the submodule, and push it with an SSH key, it will not work. You can set a different remote or update your local copy of .gitmodules.

**Pull request merged**
