### PR TITLE
Porting misc_jiras tests from cdbfast to ICG

### PR DESCRIPTION
**Pull request by armenatzoglou**
This PR ports tests from cdbfast/misc_jiras to ICG. We migrate all tests except for 19 that perform actions, which are currently not supported by ICG, e.g., templates. Query processing team keeps track of the ported tests.  

@vraghavan78 @oarap @hsyuan Please take a look if you have time. Thanks

### CODE REVIEW

**Comment by danielgustafsson** [comment]
What is the intention with setting `gp_debug_linger` in this test? Judging by the out file we aren't expecting any terminations here anyways or am I missing something?

**Comment by vraghavan78** [comment]
@armenatzoglou when you have optimizer specific gucs like '*set optimizer_disable_missing_stats_collection=on;* please add a start and end ignore, since it will fail if OSS developer does not use optimizer.

**Comment by gcaragea** [comment]
I think you need to replace the: 
```
\echo -- start_ignore
``` 
with an actual 
```
-- start_ignore
```

**Comment by gcaragea** [comment]
Also, there are a bunch of copyright messages that look like this: 
```
-- --------------------------------------------------------------------------------------
-- COPYRIGHT: Copyright (c) 2010, Greenplum.  All rights reserved.
-- PURPOSE: Verify bug: MPP-7886
...
```

Not sure if we have encountered those before, but maybe we should remove them.

**Comment by armenatzoglou** [comment]
@vraghavan78 I have added the start and end ignore that you mentioned.
@gcaragea I applied all of your suggestions/corrections.
@danielgustafsson Correct, I do not know why we were using gp_debug_linger in that test. Makes no sense. I removed it.

The build is green in my private pulse project. 
Thanks a lot for the review.

**Comment by gcaragea** [comment]
LGTM after the latest changes. 
+1

**Comment by armenatzoglou** [comment]
Pushed to master. Thanks a lot all of you for the code review!

**Pull request closed without merging**
