### PR TITLE
docs - remove guc category section and doc files from admin guide

### PR DESCRIPTION
**Pull request by lisakowen**
the admin guide has a section on server configuration parameter categories (https://greenplum.org/docs/560/admin_guide/topics/g-configuration-parameter-categories.html).  the information is presented over multiple doc sections and files as a list of guc names in table format.  

the info exists in pretty much the same format in the reference guide (https://greenplum.org/docs/560/ref_guide/config_params/guc_category-list.html) - and this page links to the GUC reference text.

this PR removes the guc category files from the admin guide, updates the ditamap, and links to the reference guide guc category page.

(local build worked against this PR.)

### CODE REVIEW

**Comment by lisakowen** [comment]
@mkiyama - do you prefer that we not delete this from the admin guide?  if so, why?

**Comment by mkiyama** [comment]
I guess it depends on how valuable this use case is.

As a new user, sometimes I use the TOC as a search tool
looking at the titles as a summary of information.
If the Config. Parameter Categories is removed from the
the left hand nav. I loose the that summary information 
in the left hand nav when I search the Admin. Guide.

It is duplicated in the Ref.Guide, but as a new
user I'm looking in the Admin.Guide for information
about managing GPDB.

It is a balancing act between duplication and discovery.

Hope this helps. 
Let me know if you have questions.

**Comment by mkiyama** [comment]
If you think that is sufficient, then I guess it's ok.

**Comment by mkiyama** [comment]
Just a thought... 
in the context of the Admin Guide nav, it seems the nav is still loosing the information.

**Pull request merged**
