### PR TITLE
Redirect the error to log message

### PR DESCRIPTION
**Pull request by bhuvnesh2703**
Earlier the error was sent to /dev/null and the information was lost
displaying the cause of the error. Redirect the error to log file.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by dkrieger-pvtl — APPROVED** [review]
LGTM.  Likely, we'll need merge approval.

This goes to the old software engineering adage: log everything.

**Comment by asimrp** [comment]
There are a few more `/dev/null` occurrences, should they be taken care of too?
```
$ git grep '/dev/null' -- gpMgmt/bin/gpinitsystem 
gpMgmt/bin/gpinitsystem:                -m" start >> /dev/null 2>&1
gpMgmt/bin/gpinitsystem:                CHK_COUNT=`env PGOPTIONS="-c gp_role=utility" $PSQL -p $MASTER_PORT -d "$U_DB" -X -A -t -c "SELECT count(*) FROM $GP_CONFIG_TBL WHERE content=${U_CONTENT} AND preferred_role='${U_ROLE}';" 2>/dev/null` >> $LOG_FILE 2>&1
gpMgmt/bin/gpinitsystem:                        dbid=`env PGOPTIONS="-c gp_role=utility" $PSQL -p $MASTER_PORT -d "${DEFAULTDB}" -X -A -t -c "select pg_catalog.gp_add_segment_mirror(${GP_CONTENT}::int2, '${GP_HOSTNAME}', '${GP_HOSTADDRESS}', ${GP_PORT}, '${GP_DIR}');" 2>/dev/null` >> $LOG_FILE 2>&1
gpMgmt/bin/gpinitsystem:        $PSQL -p $GP_PORT -d "$DEFAULTDB" -c "select gp_request_fts_probe_scan()" >> /dev/null 2>&1
```

**Comment by bhuvnesh2703** [comment]
@asimrp thanks for pointing out, i will include them in this PR.

**Review by asimrp — APPROVED** [review]
Thank you @bhuvnesh2703!

Would you like to create a github issue to track `/dev/null` redirection in other management utilities?

**Comment by bhuvnesh2703** [comment]
> Thank you @bhuvnesh2703!
> 
> Would you like to create a github issue to track `/dev/null` redirection in other management utilities?

Created an issue for tracking other instances: https://github.com/greenplum-db/gpdb/issues/11114, Thank you @asimrp

**Pull request merged**
