### PR TITLE
Fix all known issue about dumping exchanged partition

### PR DESCRIPTION
**Pull request by hidva**
We have refactored the logic for dumping exchanged partition, all logic for
exchanged partition has moved into the dumping of external/foreign table. That is:

First, dump the partitioned table just like a normal table, there is no logic
for exchanged partition.

Second, dump the external/foreign table, and after the dumping, we will check if
the external table has been exchanged into a partition table, it means that
the TableInfo::parrelid is not zero,  and if so, we will generate a new TocEntry
for EXCHANGE PARTITION statement.

Here, we introduce a new function 'pg_get_partition_path' to construct the access path
for a leaf partition:

```sql
zhanyi=# select pg_get_partition_path('parttable_1_prt_2_2_prt_2_3_prt_other_regions'::regclass, ' ALTER PARTITION ', ' EXCHANGE PARTITION ');
                                     pg_get_partition_path                                     
-----------------------------------------------------------------------------------------------
  ALTER PARTITION FOR(RANK(1)) ALTER PARTITION FOR(RANK(1)) EXCHANGE PARTITION "other_regions"
(1 row)
```

the partitioned table `parttable` DDL is:

```sql
CREATE TABLE parttable(
    null1 int,
    null2 int,
    notnull1 int ,
    notnull2 int ,
    defnull1 int ,
    defnull2 int ,
    def31 int ,
    def32 int
)
PARTITION BY RANGE (defnull2)
  SUBPARTITION BY RANGE (def31)     
  SUBPARTITION TEMPLATE (
       START (1) END (3) EVERY (1), 
       DEFAULT SUBPARTITION other_months )
  SUBPARTITION BY LIST (def32)    
    SUBPARTITION TEMPLATE (
       SUBPARTITION usa VALUES (1),
       SUBPARTITION europe VALUES (2),
       DEFAULT SUBPARTITION other_regions)
( START (2008) END (2009) EVERY (1),
  DEFAULT PARTITION outlying_years);
```

gpbackup can also use `pg_get_partition_path` to construct the access path.

### CODE REVIEW

**Comment by hidva** [comment]
https://github.com/greenplum-db/gpdb/issues/5003

**Comment by hidva** [comment]
We have never used `pg_dump --binary-upgrade`, so there may be some unknown issues.

**Comment by hidva** [comment]
Testcase:
```
CREATE TABLE parttable(col1 int, col2 int, col3 int, col4 int)
PARTITION BY RANGE (col2) 
    SUBPARTITION BY RANGE (col3) 
    SUBPARTITION TEMPLATE (START (1) END (2) EVERY (1)) 
        SUBPARTITION BY LIST (col4)     
        SUBPARTITION TEMPLATE (SUBPARTITION val1 VALUES (1), SUBPARTITION val2 VALUES (2)) 
( START (2008) END (2009) EVERY (1));

CREATE EXTERNAL TABLE exttable (
    col1 int, col2 int, col3 int, col4 int
) LOCATION (
    'file://gpdb:7002/tmp/*.csv',
    'file://gpdb:7003/tmp/*.csv',
    'file://gpdb:7004/tmp/*.csv'
) ON ALL 
FORMAT 'csv' (delimiter E',' null E'' escape E'"' quote E'"')
ENCODING 'UTF8';

ALTER TABLE parttable ALTER PARTITION FOR (2008) ALTER PARTITION FOR (1) EXCHANGE PARTITION val1 WITH TABLE exttable WITHOUT VALIDATION;  
```

**Comment by hlinnaka** [comment]
With the PostgreSQL v12 merge, we will start using the upstream CREATE TABLE + ATTACH PARTITION syntax for dumping partitioned tables. So I don't think it makes sense to do anything about this right now on 'master'. And for backbranches, introducing a new function is problematic, because we can't change the catalogs.

**Pull request closed without merging**
