### PR TITLE
Upgrades to behave-1.2.4

### PR DESCRIPTION
**Pull request by professor**

### CODE REVIEW

**Comment by cjcjameson** [comment]
Upgrading just on general principles, or is there a specific patch that you're looking to pick up? (http://pythonhosted.org/behave/new_and_noteworthy_v1.2.4.html)

Can you remind me of the reasons for not bumping to 1.2.5 or higher?

**Comment by chrishajas** [comment]
1.2.5 requires python 3 syntax (at least for the updated print statements). 1.2.4 allows us to run scenarios by name and check for undefined steps without having to actually run the entire suite.

This PR would need to be coupled with updating the submodule and we should also test this with all of our behave suites as I I'm not 100% sure that behave 1.2.4 behaves the same way as 1.2.2

**Comment by cjcjameson** [comment]
Sounds good! Yes let's include the updated submodule reference as part of this pull request, then. But other than that, I'm +1... it'd be fine to merge, not expecting any substantial change in behavior but able to react if the main pipeline goes red on one of the behave tests at the end.

**Comment by cjcjameson** [comment]
Hi Todd,

Can you add more context to these recent additions to the PR? Perhaps you're just fiddling around on the branch, WIP-like -- if so no worries. But if this is getting close to a merge or if it's addressing specific feedback you've gotten (from tests or from people), I'm curious to know more than was in the commit messages so that I can learn more about the Behave framework for the future.

**Comment by professor** [comment]
Although we thought that upgrading to behave 1.2.4 would be simple, it turns out that behave 1.2.4 exposes import problems in our behave tests. Behave 1.2.2 must have bugs with its imports and was not respecting python namespaces. Once we're green, we'll squash a few of these commits.

**Pull request merged**
