### PR TITLE
Don't modfiy PlannedStmt during execution

### PR DESCRIPTION
**Pull request by hlinnaka**
With the upcoming PostgreSQL 8.3 merge, a PlannedStmt will be cached across multiple executions of a statement. In preparation for that, move things that modified during execution out of PlannedStmt.

### CODE REVIEW

**Comment by atris** [comment]
+1

**Comment by xiong-gang** [comment]
+1

**Comment by eurekaka** [comment]
Would the exec_make_plan_constant and stripPlanBeforeDispatch called in cdbdisp_dispatchPlan affect the upcoming cache feature? since they both modify the plan tree in execution. and how about preprocess_initplans call in ExecutorStart?

Other than that, looks good to me.

**Comment by hlinnaka** [comment]
On 03/06/16 06:13, Kenan Yao wrote:
> Would the exec_make_plan_constant and stripPlanBeforeDispatch called
> in cdbdisp_dispatchPlan affect the upcoming cache feature? since they
> both modify the plan tree in execution. and how about
> preprocess_initplans call in ExecutorStart?

Hmm. exec_make_plan_constant() is OK, as it makes a copy of the Plan 
tree. And on a quick glance, I don't think preprocess_initplans() 
modifies the original PlannedStmt or Plan tree. It does modify the 
QueryDesc and PlanStates, but those don't need to be immutable, a 
separate instance of those is created for each execution.

stripPlanBeforeDispatch() does look suspicious. I guess it's not a 
problem, and we haven't issues on the merge branch, because the 
Query-structs of subqueries are never needed after the planning, so it's 
OK that they're stripped off on the first invocation. But in that case, 
cdbdisp_dispatchPlan() doesn't seem like the right place for doing that. 
It would be more straightforward to do it once, right after planning. 
I'll try that out.

Thanks!

- Heikki

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Pull request closed without merging**
