### PR TITLE
resgroup: hashagg: ensure retried insertion succeed after spilling

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
The hashagg operator might need to spill when there is no enough memory
to insert a tuple to the hashtable, in resource queue mode this could
raise an "insufficient memory reserved for statement" error.

In resource group mode the spilling will always succeed, but depends on
the memory released by spilling the in-memory tuples and the memory
consumed by the metadata, it is possible that there is still no enough
memory for the new tuple after the spilling.

So we must enlarge max_mem to ensure the retried insertion will not fail
again.

Note that enlarging max_mem does not means the palloc() will not fail,
when that happens it means that the resource group already runs out of
its memory, so an "out of memory" error will be thrown, which is
expected.

Tests are not provided as it is already covered by the existing
resgroup/resgroup_agghash_memory test.

Discussion: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/30hiTArxsgo/aydVMcrXBQAJ

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [x] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by pivotal-ning-yu** [comment]
The resource group tests passed in my local environment.

**Comment by pivotal-ning-yu** [comment]
BTW, this PR is to fix the red resource group pipelines:
https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master/jobs/resource_group_centos7/builds/857

**Comment by adam8157** [comment]
`agg_hash_reload()` has the same logic, does it also need to be updated?

**Comment by weinan003** [comment]
> agg_hash_reload

**Comment by weinan003** [comment]
> `agg_hash_reload()` has the same logic, does it also need to be updated?

I think so, this problem only is triggered if we still do not have enough memory after the spill. But it hard to design a case for `agg_hash_reload` even.

**Comment by pivotal-ning-yu** [comment]
Thanks for the reviews.  We had some offline discussions on this issue, the conclusion is: we will disable the resgroup auto operator memory enlarging logic for hashagg.  The PR is opened at https://github.com/greenplum-db/gpdb/pull/8252, so we will close current one w/o merging.  Please help to review that new PR.

**Comment by pivotal-ning-yu** [comment]
BTW, we will not include the insertion checking after spilling in that new PR, maybe we could open a separate PR to do that job.

**Pull request closed without merging**
