### PR TITLE
Update the 4.3.JSON file.

### PR DESCRIPTION
**Pull request by asubramanya**
The 4.3.JSON file is used by gpcheckcat to figure out the foreign keys for
catalog tables. After making catalog changes, this file has to be generated by
running tidycat.pl and then copied over to gpMgmt/bin/gppylib/data/ directory.
It was missed with the FDW removal commit
601c58c33aa9f8686e2a128153aa0272c7e878a5 and it caused gpcheckcat to fail to
identify foreign key inconsistencies.

### CODE REVIEW

**Comment by hlinnaka** [comment]
We're 5.0 now, surely the 4.3 file shouldn't be modified. 

On 30 November 2015 20:39:09 EET, Abhijit Subramanya <notifications@github.com> wrote:
>The 4.3.JSON file is used by gpcheckcat to figure out the foreign keys
>for
>catalog tables. After making catalog changes, this file has to be
>generated by
>running tidycat.pl and then copied over to gpMgmt/bin/gppylib/data/
>directory.
>It was missed with the FDW removal commit
>601c58c33aa9f8686e2a128153aa0272c7e878a5 and it caused gpcheckcat to
>fail to
>identify foreign key inconsistencies.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/greenplum-db/gpdb/pull/128
>
>-- Commit Summary --
>
>  * Update the 4.3.JSON file.
>
>-- File Changes --
>
>    M gpMgmt/bin/gppylib/data/4.3.json (726)
>
>-- Patch Links --
>
>https://github.com/greenplum-db/gpdb/pull/128.patch
>https://github.com/greenplum-db/gpdb/pull/128.diff
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/128

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by asubramanya** [comment]
The version string has not been set to 5.0 yet. It still says 4.3.99.0.
Our internal test schedule for gpcheckcat is failing and we need this patch to fix it.

**Comment by asimrp** [comment]
Once the version number is bumped to 5.0, we will have to add a 5.0 json file.  This commit is necessary so that the tests run properly until then.

**Comment by schubert** [comment]
@asubramanya can you mark your membership in greenplum-db as public which should satisfy the CLA bot? Instructions are here: https://help.github.com/articles/publicizing-or-concealing-organization-membership/

**Comment by asubramanya** [comment]
@schubert Updated the membership to public.

**Comment by asubramanya** [comment]
@asimrp @hlinnaka Closing this request. 

This file needs to be updated every time catalog version is bumped. Additional commits have been made since this Pull request was opened which have bumped up the catalog version so the file needs to be updated again.

**Pull request closed without merging**
