### PR TITLE
Add support for table aliases in EXPLAIN for ORCA optimized queries

### PR DESCRIPTION
**Pull request by kovaden**
Currently, ORCA-generated query plan does not show aliases, unlike the original
PostgreSQL planner. Usually, it is much more descriptive to have the alias in the
plan, which are specified by the user in the query and might have meaning.

This patch adds table aliases support to ORCA-generated query plans 
and adjusts tests.

### CODE REVIEW

**Review by gpopt — APPROVED** [review]
+1

**Review by chrishajas — COMMENTED** [review]
Looks good! Nice find

**Review by chrishajas — APPROVED** [review]

**Comment by chrishajas** [comment]
There's also some alias diffs in `gp2pg_postgres_fdw` that need to be updated:
[diffs.txt](https://github.com/greenplum-db/gpdb/files/14796628/diffs.txt)

**Comment by kovaden** [comment]
Recent changes to tests have been merged.

**Comment by chrishajas** [comment]
Thanks! One last failure I'm seeing (likely due to recent changes):
```
--- a/src/test/regress/expected/gpdist_legacy_opclasses_optimizer.out
+++ b/src/test/regress/expected/gpdist_legacy_opclasses_optimizer.out
@@ -306,8 +306,6 @@ explain (costs off) select * from legacy_enum a inner join legacy_enum b on a.co
          Hash Cond: ((a.color)::anyenum = (b.color)::anyenum)
          ->  Seq Scan on legacy_enum a
          ->  Hash
-               ->  Broadcast Motion 3:3  (slice2; segments: 3)
-                     ->  Seq Scan on legacy_enum b
                ->  Seq Scan on legacy_enum b
  Optimizer: Pivotal Optimizer (GPORCA) version 3.41.0
 (7 rows)
 ```
 
Can you also squash these changes into a single commit without the merge commits and we'll get this in.

**Comment by kovaden** [comment]
> Can you also squash these changes into a single commit without the merge commits and we'll get this in.
Done

**Comment by chrishajas** [comment]
Merged, thanks for your contribution!

**Pull request merged**
