### PR TITLE
Add DS_Store and IDEA project file to gitignore

### PR DESCRIPTION
**Pull request by gpopt**

### CODE REVIEW

**Comment by ashwinstar** [comment]
PostgreSQL's take on this is https://www.postgresql.org/message-id/E40AD616-7FB8-4E1C-B4C3-AEA7269115D6%40yesql.se which I agree with and hence would recommend utilizing instead core.excludesfile Git
config for your usecase.

**Comment by gpopt** [comment]
Thanks. I tried it, however I got this:
```
git config --global core.excludesFile '.idea/'
git status
fatal: cannot use .idea/ as an exclude file
```

**Comment by ashwinstar** [comment]
> Thanks. I tried it, however I got this:
> 
> ```
> git config --global core.excludesFile '.idea/'
> git status
> fatal: cannot use .idea/ as an exclude file
> ```

That's not the way to do it. `core.excludesFile` you will provide file which has list of excludes mentioned in it at global level. This article should provide reference on how to do it https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

**Comment by gpopt** [comment]
Thanks a lot @ashwinstar, it worked like a charm. 
I am closing this PR.

**Pull request closed without merging**
