### PR TITLE
Allow fsync=off, and use in the concourse pipeline

### PR DESCRIPTION
**Pull request by hlinnaka**
See discussion at gpdb-dev: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/0HjPmUk469o/Hg2CdamaCAAJ

I don't know if the pipeline yaml changes are correct, but we'll find out shortly..

### CODE REVIEW

**Comment by hlinnaka** [comment]
I have no idea if my pipeline yaml changes have the desired effect or not, so if someone could have a look at those, that'd be great..

**Comment by jimmyyih** [comment]
Big +1!  Note that the -j option was taken out of compilation due to some sed commands overwriting each other in src/bin/gpupgrade/Makefile... which doesn't exist anymore so adding the -j option back should be fine.

**Comment by hlinnaka** [comment]
Ok, I give up, I have no clue on how to get the fsync=off option into the postgresql.conf files in the concourse pipeline. Anyone help, please?

**Comment by hlinnaka** [comment]
To my surprise, "-j4" doesn't seem to actually make the build any faster, in the concourse instance. Not sure why. Maybe the system is so resource-strapped already, or only has a single CPU available.

**Comment by ashwinstar** [comment]
I am not sure too how PR pipeline works, so won't be able to provide help.
But I think would have to fly set-pipeline for your pipeline changes to
take effect.

Xin, can you provide guidance on the same.

**Comment by ashwinstar** [comment]
Your change works fine, still no idea on PR pipeline but verified the same by creating separate private pipeline and ICG completes in 14 mins with this. So, please feel free to commit the change. As it stands will not break anything, once logistics are figured out can fly set-pipeline the main and PR one for change to get reflected.

**Comment by hlinnaka** [comment]
Pushed, thanks Ashwin!

**Comment by xinzweb** [comment]
Sorry, in general, the PR pipeline will take the pull request and run through the jobs there.

In this case, we don't verify any concourse related changes, since none of them will impact how the code build and running ICG.

The concourse related changes are using the `fly set-pipeline` on `gpdb_WIP` to try them out, then if it's working, then it can be pushed, and also people need to update the `master` one.

**Pull request closed without merging**
