### PR TITLE
6X: ic: implement proxy mode

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
By setting gp_interconnect_proxy to 'proxy' now the interconnect could
run in the proxy mode.  In the proxy mode a proxy bgworker is launched
on each segment, the proxy bgworkers connect to each other, the backends
only connect to the bgworker on their own segment.  By doing this we
reduced the total network flows, we also reduced the required port
counts.

To enable the proxy mode we need to first configure the guc
gp_interconnect_proxy_addresses, for example:

    gpconfig \
      -c gp_interconnect_proxy_addresses \
      -v "'1:-1:10.0.0.1:2000,2:0:10.0.0.2:2001,3:1:10.0.0.3:2002'" \
      --skipvalidation

----

The ic-proxy mode is disabled in configure by default, enable it manually with `--enable-ic-proxy`.

----

Refer to the ic-proxy [README](https://github.com/greenplum-db/gpdb/blob/master/src/backend/cdb/motion/README.ic-proxy.md) for details.

----

Below is a simple __bash__ script to set this automatically:

    #!/usr/bin/env bash

    portbase=2000

    psql -tqA -d postgres -P pager=off -F ' ' \
        -c "select dbid, content, $portbase+dbid as port, address from gp_segment_configuration order by 1" \
    | while read -r dbid content port addr; do
        ip=$(host "$addr" | fgrep -v IPv6 | head -n1)
        ip=${ip##* }
        echo "$dbid:$content:$ip:$port"
      done \
    | paste -sd, - \
    | xargs -rI'{}' gpconfig --skipvalidation -c gp_interconnect_proxy_addresses -v "'{}'"

It's only verified on ubuntu linux.

----

This PR backports https://github.com/greenplum-db/gpdb/pull/9820, https://github.com/greenplum-db/gpdb/pull/10464, and https://github.com/greenplum-db/gpdb/pull/10514 to 6X_STABLE.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by pivotal-ning-yu** [comment]
Pushed a commit to add the centos6 ICW ic-proxy jobs, also corrected some 6X specific settings.

**Comment by pivotal-ning-yu** [comment]
A devel pipeline is setup to veirfy this PR.  Have to mention that the devel pipeline is hacked to use libuv 1.18 instead of 1.38 .

**Comment by kmacoskey** [comment]
@pivotal-ning-yu 

This issue with a development pipeline is that when you are setting one, the value of `((gcs-bucket))` changed to A development bucket. The libuv 1.38.0 may not exist within the development bucket. No assumptions should be made about the content of a development bucket.

A few methods of fixing that:
1. Use the production bucket for fetching dependencies in both production and development pipelines. Development buckets should be used when creating new artifacts. The `((gcs-bucket))` variable appears to be overloaded for resources that are both fetching production artifacts and pushing new artifacts.
2. Backport these changes: https://github.com/greenplum-db/gpdb/pull/10522 . These changes assume libuv comes from the Docker container and now the GCS bucket. There is no difference between the Docker containers when setting a production or development pipeline, therefore the problem is avoided all together.

**Comment by pivotal-ning-yu** [comment]
The devel pipeline for this PR will hang on gpfdist tests in all the ic-proxy ICW jobs.  I hijacked on the pipeline, canceled the job and reran manually, it can pass; it also passed in my local environment.

So I'll enable the ic-proxy logs temporarily for debugging purposes.

**Comment by pivotal-ning-yu** [comment]
The gpfdist hanging issue is identified, it's caused by a conflict on the ic-proxy domain socket filenames, it's fixed by including the postmaster pid in the filenames.  I have rebased the PR with the latest 6X_STABLE.

**Comment by pivotal-ning-yu** [comment]
The devel pipeline is green, so I think it's ready to merge.  I force-pushed again to replace the domain socket conflict patch with one cherry-picked from master branch.

**Comment by pivotal-ning-yu** [comment]
I'll set the pipeline.

**Pull request merged**
