### PR TITLE
Move checking missing/orphaned files views to a new extension

### PR DESCRIPTION
**Pull request by huansong**
Original 7X commit 6bbafd96d698740e3b8706de8c292ec0daa3a295.

Reason for the move:
* Make it easier to upgrade from 6X where these views will be placed.
* Make it easier for future additions/modifications in 7X itself. No need to re-install gp_toolkit but just run the extension's upgrade script.

See #15343 for more discussion.

With the change, now the usage of the views becomes:

```
create extension if not exists gp_check_functions;

-- checking non-extended files
select * from gp_check_missing_files;
select * from gp_check_orphaned_files;

select * from gp_check_missing_files_ext;
select * from gp_check_orphaned_files_ext;
```

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by huansong** [comment]
> Isn't gp_toolkit itself planned to become extension. If that's the case then this benefit is noop, right?

Yes that is true. However, while that's yet decided (I hope it will happen), I think we should probably just move these views as if they never existed in gp_toolkit, so the decision for gp_toolkit won't have any impact on them.

**Comment by bmdoil** [comment]
> > Isn't gp_toolkit itself planned to become extension. If that's the case then this benefit is noop, right?
> 
> Yes that is true. However, while that's yet decided (I hope it will happen), I think we should probably just move these views as if they never existed in gp_toolkit, so the decision for gp_toolkit won't have any impact on them.

The expectation is gp_toolkit will be converted to an extension in the next beta cycle.

**Comment by huansong** [comment]
> The expectation is gp_toolkit will be converted to an extension in the next beta cycle.

Sounds good!

That will make the *re-install* part not an issue. But I think this PR is still required for the *6X->7X upgrade* part.

In addition, I've made a few changes to the views to exclude some false positive cases which need review too. Please see commit messages.

I'll make the same changes to 6X.

**Comment by huansong** [comment]
Had discussion w/ @ashwinstar and @soumyadeep2007 . Current plan is:

1. Fix views first. We will have different thinking of the missing and orphaned views:
  * Missing views should precisely describe the inconsistency between catalog and storage. Anything inconsistent, we report it; and if it's false reporting, we should fix the root cause (not the view).
  * Orphaned views will ignore the extension files if the main relfile (w/o extension) is not orphaned. As a result, we do not need to check aoseg/aocsseg  - when the main reifile is orphaned, we report all of the extension files starting with that relfilenode to be orphaned.

2. Discussion pending about where do we actually add these views. Some notes below. But this is unrelated to the first action item.
* Add them as system views: (which is current state, where they are in gp_toolkit which are created in initdb)
  * Good: no extra step of “create extension”
  * Bad: tricky upgrade
* Add them to new extension `gp_check_functions`, just like 6X:
  * Good: easy upgrade from 6X
  * Bad: we might not have any more views going into this extension in future, given we will move gp_toolkit to its own standalone extension and we’ll probably add any new ones there
* Add them to the new extension `gp_toolkit`:
  * Good: it is probably the final destination of all such views
  * Bad: tricky upgrade

Based on the plan, I will open a new PR to make fix to the existing views. And I'm closing this PR to not confuse reviewers. We can re-open it once we have the decision about the view location.

**Comment by ashwinstar** [comment]
Very highly appreciate @huansong for driving these changes and importantly discussions in extremely methodical ways.

**Pull request closed without merging**
