### PR TITLE
[#130552639] Add performance pipeline

### PR DESCRIPTION
**Pull request by xinzweb**
https://gporca.ci.pivotalci.info/pipelines/gpdb_perf

Signed-off-by: Jesse Zhang <jzhang@pivotal.io>

### CODE REVIEW

**Comment by xinzweb** [comment]
@hardikar would you please take a look?

**Comment by hardikar** [comment]
+1

**Comment by danielgustafsson** [comment]
What is this intended to do?

**Comment by xinzweb** [comment]
@danielgustafsson This pipeline in addition to the build pipeline is to ensure the performance not regressed. Do you have a location where I can share a short description of the purpose of this performance pipeline? We are thinking to run TPC-H using this pipeline with regular cadence so that we can capture performance regression as soon as possible. Thoughts? Thanks.

**Comment by Eulerizeit** [comment]
What is being tested exactly? Are we only testing ORCA and Codegen? What is
the unit of work being tested? Are we going to test patches that are 1/4
finished, 1/2 finished?  How are we going to push the work into the
pipeline?

**Comment by armenatzoglou** [comment]
+1. Thanks a lot for working on this.

**Comment by danielgustafsson** [comment]
> On 19 Sep 2016, at 22:33, Xin Zhang <notifications@github.com> wrote:
> 
> @danielgustafsson This pipeline in addition to the build pipeline is to ensure the performance not regressed. Do you have a location where I can share a short description of the purpose of this performance pipeline? We are thinking to run TPC-H using this pipeline with regular cadence so that we can capture performance regression as soon as possible. Thoughts? Thanks.

Sure, shoot an email to gpdb-dev@ with an outline of the plan.

**Comment by vraghavan78** [comment]
We are planning to test the following:
* Planner
* Orca
* CodeGen + Planner
* CodeGen + Orca

**Comment by vraghavan78** [comment]
@danielgustafsson the doc has several workloads including one customer schema and workloads.

**Comment by yydzero** [comment]
This is great work! Could we add more comments/documentation in concourse directory or added to concourse/perf_pipeline.yml file directly which is better.

**Pull request merged**
