### PR TITLE
Fix minor issues with gpinitstandby

### PR DESCRIPTION
**Pull request by macroyuyang**
*     Fix tablespace attribute number for pg_basebackup. In libpq, the attribute number is 0 zero based.
*     Fix pg_basebackup -E option.  Server side should exclude sub directory even parent directory
    wanted.

Will port `fb05f3ce83d` if required when primary and standby on the same machine with tablespace.

Another question is: for instance, if standby's dbid = 10, and primary's dbid = 1, how let standby recover from pg_basebackup results with dbid = 1?

### CODE REVIEW

**Comment by macroyuyang** [comment]
#4282 Has been ported for conflicts on same machine with talbespace

**Comment by hlinnaka** [comment]
Thanks! I pushed a slightly expanded version of the fix for the confusion on attribute numbers (commit 408766080a968b69e9fbcb2ca28503647a15bc7e).

**Comment by macroyuyang** [comment]
@hlinnaka Thanks for massaging this into committable state

**Comment by macroyuyang** [comment]
This PR includes another fix of -E option for pg_basebackup. For instance, if user specify -E gpperfmon/log/files, gpperfmon is not exclusive but gpperfmon/log should be exclusive. So we still need to pass exclude even skip_this_dir is false?

**Comment by hlinnaka** [comment]
On 10/01/18 14:46, Yu Yang wrote:
> This PR includes another fix of -E option for pg_basebackup. For instance, if user specify -E gpperfmon/log/files, gpperfmon is not exclusive but gpperfmon/log should be exclusive. So we still need to pass exclude even skip_this_dir is false?

Yep, gotcha.

- Heikki

**Comment by hlinnaka** [comment]
Pushed the second patch too. I'm not sure if there's more work to be done here, but we want that in any case. Thanks!

**Pull request closed without merging**
