### PR TITLE
change fdw multi URIs separation rule (7X)

### PR DESCRIPTION
**Pull request by hyongtao-db**
Before this pr, gpdb FDW uses '|' as the separator of multi locations.

But '|' is not a safe separator. It lead a fault in URI of PXF, '|' will convert into '%7C'. For example

```
LOCATION (E'pxf://tmp/pxf_automation_data/bfd1dbcc-e1ac-43b4-bad5-b08c4f7b2457/java_regex_special_chars/(.%7C+)*?PROFILE=hdfs:text') 
```

We found that single quotes `'` are a reserved character for the gpdb locations uri, as shown in the following two examples:
```
gpadmin=# create external table e(a text, b text) location(
gpadmin(# 'gpfdist://ab|cd,ef'gh:7070/ret.tbl1',
gpadmin'# 'gpfdist://ab|cd,ef'gh:7070/ret.tbl2') format 'text';
ERROR:  syntax error at or near "gh"
LINE 2: 'gpfdist://ab|cd,ef'gh:7070/ret.tbl1',
                            ^
gpadmin=# create external table e(a text, b text) location(
gpadmin(# 'gpfdist://ab|cd,ef\'gh:7070/ret.tbl1',
gpadmin'# 'gpfdist://ab|cd,ef\'gh:7070/ret.tbl2') format 'text';
invalid command \'gh:7070/ret.tbl2')
Try \? for help.
```
Both single quotes `'` and escape single quotes `\'` are not supported.

So we decided to use single quotes ''' and commas ',' to split strings and make uri list. It is much easier to change the code.

**Signed-off-by**: Yongtao Huang <yongtaoh@vmware.com>
**Co-author**: Jingwen Yang <jingweny1@vmware.com>

### CODE REVIEW

**Comment by adam8157** [comment]
I doubt this, the `reserved` means they have special meanings, but it doesn't say URI could not have them. `&` is reserved, but obviously, it's in many URIs. 

Instead, `|` in a URI must be encoded to `%7C`, I think the proper fix is not to decode the percent-encoded characters.

**Comment by hyongtao-db** [comment]
> 

Thanks @adam8157  for your constructive suggestion. I totally made a mistake. 

_These characters are called "reserved" because they may (or may not) be defined as delimiters by the generic syntax._
So I agree that ',' may appear in some URI. So this fix will lead to other bug.

Please refer to page 13 in https://www.rfc-editor.org/rfc/pdfrfc/rfc3986.txt.pdf

**Comment by denalex** [comment]
A few points:
- I think it will be useful to consider the URI in external table LOCATION clause as not being a strict URI as far as what characters it can contain, since there was no such restriction in GP6
- using a "manually" concatenated list of URIs with a separator and a simple logic of searching for this separator in the resulting string will prevent using this separator in the URI value, assuming there is no strict validation argued against in the point above. So any separator like `|` or `,` will not work and be backward compatible.
- we should support the original syntax - in this PR a test does `location ('gpfdist://@hostname@:7070/exttab1/nation.tbl,gpfdist://@hostname@:7070/exttab1/nation.tbl.gz')` while it should be `location ('gpfdist://@hostname@:7070/exttab1/nation.tbl','gpfdist://@hostname@:7070/exttab1/nation.tbl.gz')` - as a list of `'...'` strings, separated by a `,`, not a single string
- we should store the original list of strings serialized in a format such that it can be parsed back into a list y the gp_exttable_fdw, without prohibiting any characters to be a part of the URI.

**Comment by hyongtao-db** [comment]
Thanks Alexander for your kind advice. I will follow it up.

**Comment by hyongtao-db** [comment]
Hi all, 

We do some spike work and make a conclusiton about this bug recently.

As shown below, the urilocation are saved as text[] in 6X.
```
gpadmin=# \d pg_exttable
    Table "pg_catalog.pg_exttable"
     Column      |  Type   | Modifiers
-----------------+---------+-----------
 reloid          | oid     | not null
 urilocation     | text[]  |
 execlocation    | text[]  |
 fmttype         | "char"  |
 fmtopts         | text    |
 options         | text[]  |
 command         | text    |
 rejectlimit     | integer |
 rejectlimittype | "char"  |
 logerrors       | boolean |
 encoding        | integer |
 writable        | boolean |
Indexes:
    "pg_exttable_reloid_index" UNIQUE, btree (reloid)
```

But in 7X, all the content about external table, such as urilocation, execlocation, fmttype, ..., are saved in ftoptions text[]. And urilocation has to be converted into string(char *). 
```
gpadmin=# \d pg_foreign_table
         Table "pg_catalog.pg_foreign_table"
  Column   |  Type  | Collation | Nullable | Default
-----------+--------+-----------+----------+---------
 ftrelid   | oid    |           | not null |
 ftserver  | oid    |           | not null |
 ftoptions | text[] | C         |          |
Indexes:
    "pg_foreign_table_relid_index" UNIQUE, btree (ftrelid)
```

We wanna change urilocation from char* to text[], and save text[](urilocation) under (ftoptions), but both reading and writing are both difficult work.


**_Fortunately_**, we discovered that single quotes '\'' are a reserved character for the gpdb uri, as shown in the following two examples:
```
gpadmin=# create external table e(a text, b text) location(
gpadmin(# 'gpfdist://ab|cd,ef'gh:7070/ret.tbl1',
gpadmin'# 'gpfdist://ab|cd,ef'gh:7070/ret.tbl2') format 'text';
ERROR:  syntax error at or near "gh"
LINE 2: 'gpfdist://ab|cd,ef'gh:7070/ret.tbl1',
                            ^
gpadmin=# create external table e(a text, b text) location(
gpadmin(# 'gpfdist://ab|cd,ef\'gh:7070/ret.tbl1',
gpadmin'# 'gpfdist://ab|cd,ef\'gh:7070/ret.tbl2') format 'text';
invalid command \'gh:7070/ret.tbl2')
Try \? for help.
```
Both single quotes ''' and escape single quotes '\'' are not supported.

So We decided to use single quotes ''' and commas ',' to split strings and make uri list. It is much easier to change the code.

**Comment by zhaorui20005** [comment]
How does the result of(`select urilocation from pg_exttable`) change after this Pr? Is it acceptable? I remembered that GPLOAD reuse table relies on that.

**Comment by hyongtao-db** [comment]
> pg_exttable


```
        for i, l in enumerate(self.locations):
            sql += " and pgext.urilocation[%s] = %s\n" % (i + 1, quote(l))
```
Yes, I think this commit will affect these code above in `gpload.py`.

**Comment by adam8157** [comment]
Since the single quote character is reserved (could not be inside a token), can you create an external table with multiple locations using the FDW syntax and this PR?

**Comment by zhaorui20005** [comment]
> > pg_exttable
> 
> ```
>         for i, l in enumerate(self.locations):
>             sql += " and pgext.urilocation[%s] = %s\n" % (i + 1, quote(l))
> ```
> 
> Yes, I think this commit will affect these code above in `gpload.py`.

Since the gpload testing cases have all passed, it does not cause regression to gpload.

**Comment by zhaorui20005** [comment]
> Since the single quote character is reserved (could not be inside a token), can you create an external table with multiple locations using the FDW syntax and this PR?

There has been some multi-uri cases like
```
create external table ret_too_many_uris(a text, b text) location(
  'gpfdist://foo.invalid:7070/ret.tbl1',  'gpfdist://foo.invalid:7070/ret.tbl2',
  'gpfdist://foo.invalid:7070/ret.tbl3',  'gpfdist://foo.invalid:7070/ret.tbl4',
  'gpfdist://foo.invalid:7070/ret.tbl5',  'gpfdist://foo.invalid:7070/ret.tbl6',
  'gpfdist://foo.invalid:7070/ret.tbl7',  'gpfdist://foo.invalid:7070/ret.tbl8',
  'gpfdist://foo.invalid:7070/ret.tbl9',  'gpfdist://foo.invalid:7070/ret.tbl10',
  'gpfdist://foo.invalid:7070/ret.tbl11', 'gpfdist://foo.invalid:7070/ret.tbl12',
  'gpfdist://foo.invalid:7070/ret.tbl13', 'gpfdist://foo.invalid:7070/ret.tbl14',
  'gpfdist://foo.invalid:7070/ret.tbl15', 'gpfdist://foo.invalid:7070/ret.tbl16',
  'gpfdist://foo.invalid:7070/ret.tbl17', 'gpfdist://foo.invalid:7070/ret.tbl18',
  'gpfdist://foo.invalid:7070/ret.tbl19', 'gpfdist://foo.invalid:7070/ret.tbl20'
) format 'text';
\d ret_too_many_uris
```
in file [external_table_optimizer.source](https://github.com/greenplum-db/gpdb/pull/15088/files#diff-b2fa6dc0f7106757e7986e4289f5900f216c3877ccc46a34c163f1b857b6682c)

**Review by zhaorui20005 — APPROVED** [review]
LGTM

**Comment by hyongtao-db** [comment]
> > Since the single quote character is reserved (could not be inside a token), can you create an external table with multiple locations using the FDW syntax and this PR?

Thanks. I think I need to add some test case about FDW with option, like this [commit ](https://github.com/greenplum-db/gpdb/commit/66400e7e3e02a50a4e790b7dae13f23726ecd41b).

**Comment by hyongtao-db** [comment]
> LGTM

Thanks @zhaorui20005 .

**Comment by adam8157** [comment]
> > Since the single quote character is reserved (could not be inside a token), can you create an external table with multiple locations using the FDW syntax and this PR?
> 
> There has been some multi-uri cases like
> 
> ```
> create external table ret_too_many_uris(a text, b text) location(
>   'gpfdist://foo.invalid:7070/ret.tbl1',  'gpfdist://foo.invalid:7070/ret.tbl2',
>   'gpfdist://foo.invalid:7070/ret.tbl3',  'gpfdist://foo.invalid:7070/ret.tbl4',
>   'gpfdist://foo.invalid:7070/ret.tbl5',  'gpfdist://foo.invalid:7070/ret.tbl6',
>   'gpfdist://foo.invalid:7070/ret.tbl7',  'gpfdist://foo.invalid:7070/ret.tbl8',
>   'gpfdist://foo.invalid:7070/ret.tbl9',  'gpfdist://foo.invalid:7070/ret.tbl10',
>   'gpfdist://foo.invalid:7070/ret.tbl11', 'gpfdist://foo.invalid:7070/ret.tbl12',
>   'gpfdist://foo.invalid:7070/ret.tbl13', 'gpfdist://foo.invalid:7070/ret.tbl14',
>   'gpfdist://foo.invalid:7070/ret.tbl15', 'gpfdist://foo.invalid:7070/ret.tbl16',
>   'gpfdist://foo.invalid:7070/ret.tbl17', 'gpfdist://foo.invalid:7070/ret.tbl18',
>   'gpfdist://foo.invalid:7070/ret.tbl19', 'gpfdist://foo.invalid:7070/ret.tbl20'
> ) format 'text';
> \d ret_too_many_uris
> ```
> 
> in file [external_table_optimizer.source](https://github.com/greenplum-db/gpdb/pull/15088/files#diff-b2fa6dc0f7106757e7986e4289f5900f216c3877ccc46a34c163f1b857b6682c)

I mean creating the same table using the FDW syntax, I did a test with pg_dump, the command would be like this:
```
CREATE FOREIGN TABLE public.ret_too_many_uris (
    a text,
    b text
)
SERVER gp_exttable_server
OPTIONS (
    delimiter ' ',
    encoding '6',
    escape E'\\',
    execute_on 'ALL_SEGMENTS',
    format 'text',
    format_type 't',
    is_writable 'false',
    location_uris '''gpfdist://foo.invalid:7070/ret.tbl1'',''gpfdist://foo.invalid:7070/ret.tbl2'',''gpfdist://foo.invalid:7070/ret.tbl3'',''gpfdist://foo.invalid:7070/ret.tbl4''',
    log_errors 'f',
    "null" E'\\N'
);
```

It works, but do you think it's too complex? The FDW syntax commands would be the main(only?) syntax in the future.

**Comment by hyongtao-db** [comment]
Hi Adam. 
Thanks a log. Agree with you.
I think it's too complex. It's hard for user to type three `'` and it is so ugly.

**Pull request closed without merging**
