### PR TITLE
Convert Insist on backend/utils

### PR DESCRIPTION
**Pull request by joaopapereira**
Please refer: https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/BH1IXU6vnEw

### CODE REVIEW

**Comment by joaopapereira** [comment]
@hlinnaka just updated the PR to reflect your comment

**Comment by ashwinstar** [comment]
On Fri, Aug 10, 2018 at 12:40 AM Heikki Linnakangas <
notifications@github.com> wrote:

> *@hlinnaka* approved this pull request.
>
> I'd recommend plain elog() rather than ereport() for all of these, since
> they're all "can't happen" cases.
>
> Doesn't matter in GPDB too much, but in PostgreSQL the convention is to
> use elog() for such cases. ereport() error messages are translated, while
> elog() messages are not, so using elog() in "can't happen" sanity checks
> saves some pointless effort by the translators. But more imporantly, it's a
> little visual cue that the error is just a sanity check, and is not
> expected to ever happen unless there's a bug somewhere.
>

I think better approach is still continue to use ereport() everywhere
(atleast for all gpdb code). But call the same with errmsg_internal()
instead of just errmsg for such cases to avoid the penalty mentioned above
plus retains the same visual clue.

Ideally usage of elog() should be completely avoided, as ereport()
interface is more performant. Since it parses strings only if current log
level setting is satisfied compared to elog() which always constructs the
string and then based on log level decides if should log or not. So,
getting in practice of only using ereport() everywhere in code seems
better. (Sure for current case of ERROR level log doesn't make difference)

**Comment by danielgustafsson** [comment]
> On 13 Aug 2018, at 13:34, Ashwin Agrawal <notifications@github.com> wrote:
> 
> On Fri, Aug 10, 2018 at 12:40 AM Heikki Linnakangas <
> notifications@github.com> wrote:
> 
> > *@hlinnaka* approved this pull request.
> >
> > I'd recommend plain elog() rather than ereport() for all of these, since
> > they're all "can't happen" cases.
> >
> > Doesn't matter in GPDB too much, but in PostgreSQL the convention is to
> > use elog() for such cases. ereport() error messages are translated, while
> > elog() messages are not, so using elog() in "can't happen" sanity checks
> > saves some pointless effort by the translators. But more imporantly, it's a
> > little visual cue that the error is just a sanity check, and is not
> > expected to ever happen unless there's a bug somewhere.
> >
> 
> I think better approach is still continue to use ereport() everywhere
> (atleast for all gpdb code). But call the same with errmsg_internal()
> instead of just errmsg for such cases to avoid the penalty mentioned above
> plus retains the same visual clue.
> 
> Ideally usage of elog() should be completely avoided, as ereport()
> interface is more performant. Since it parses strings only if current log
> level setting is satisfied compared to elog() which always constructs the
> string and then based on log level decides if should log or not. So,
> getting in practice of only using ereport() everywhere in code seems
> better. (Sure for current case of ERROR level log doesn't make difference)

These should all be elog(ERROR.. ) anyways so I don’t see why that would make a difference in these cases. I too prefer elog() for these as that conveys intent with the code, and the callsites we inherit from upstream will use elog() so it will be more consistent.

**Comment by danielgustafsson** [comment]
> On 13 Aug 2018, at 15:20, Ashwin Agrawal <notifications@github.com> wrote:

> I strongly feel ideally when upstream introduced ereport() interface should have eliminated elog() completely. Having unnecessary multiple interfaces providing same functionality is always confusing and not helpful in long run.

FWIW, I agree with you on this one. I don’t remember what the arguments were for keeping both, and I’m sure it wasn’t done on a whim, but I wish elog() had been retired.

**Pull request closed without merging**
