### PR TITLE
Do not dispatch original query string to QE when log_statement is set to LOGSTMT_NONE.

### PR DESCRIPTION
**Pull request by fangzheng**
When `log_statement` GUC variable is set to `LOGSTMT_NONE`, QEs make no use of the query string dispatched from QD. So `buildGpQueryString()` can just include an empty query string in the dispatched query.

The related issue is here: https://github.com/greenplum-db/gpdb/issues/10887

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by paul-guo-** [comment]
Yeah this is a good improvement, but I'm wondering if we could do further optimization, i.e. skipping dispatching the query string to QE in all cases. I looked at the code it seems that the string is mainly for debugging (debug_query_string), but we could get the string on master logs.

By the way the CI errors should be not relevant of the PR. We just pushed the pg12 merge code; CI needs time for stabilizing.

**Comment by fangzheng** [comment]
> Yeah this is a good improvement, but I'm wondering if we could do further optimization, i.e. skipping dispatching the query string to QE in all cases. I looked at the code it seems that the string is mainly for debugging (debug_query_string), but we could get the string on master logs.
> 
> By the way the CI errors should be not relevant of the PR. We just pushed the pg12 merge code; CI needs time for stabilizing.

@paul-guo- 
Hi Paul,
Thanks for the suggestion and checking the test results. Indeed, QEs mainly use query string to print logs. If we get rid of the query string completely, would it become harder to diagnose issues from logs (for example, correlating error messages on segments with those on master)? If not, I'm all for it:)

**Comment by hlinnaka** [comment]
I frequently use the `debug_query_string` in QEs, while debugging. It's also quite nice that it's shown when you run `ps` in the QE. -1 for this patch.

Why would we not want to send it? Performance? How big an impact are we talking about?

**Comment by fangzheng** [comment]
> I frequently use the `debug_query_string` in QEs, while debugging. It's also quite nice that it's shown when you run `ps` in the QE. -1 for this patch.
> 
> Why would we not want to send it? Performance? How big an impact are we talking about?

Hi Heikki,
The proposal is to avoid sending query string to QEs when logging is completely turned off. Admittedly, this is not something for usual production or development environment, but one may set up for performance benchmark (we've observed 100% boost for TPC-C/B when logging is turned off). In that case, debugging log or ps display is less important than getting the best performance numbers. I will try to get some detailed measurements to quantify the effect.

**Comment by paul-guo-** [comment]
@fangzheng "(we've observed 100% boost for TPC-C/B when logging is turned off)" is quite surprising to me, do you have any profiling data to show why there is so much improvement? In addition, Is there any performance improvement data with and without your patch?

@hlinnaka , we could get `debug_query_string` from master log and `ps` output on QE  (like `MPPEXEC SELECT`?) does not come from the string, right? If this is just for debugging we do not seem to need to dispatch. When log_statement is none, there is no query string log on master, maybe we could log the query string when there is error (not sure if this has been the gpdb behavior or not). Or we could just dispatch it when some debugging options are configured (e.g. cassert enabled).

**Comment by fangzheng** [comment]
> @fangzheng "(we've observed 100% boost for TPC-C/B when logging is turned off)" is quite surprising to me, do you have any profiling data to show why there is so much improvement? In addition, Is there any performance improvement data with and without your patch?
> 
> @hlinnaka , we could get `debug_query_string` from master log and `ps` output on QE (like `MPPEXEC SELECT`?) does not come from the string, right? If this is just for debugging we do not seem to need to dispatch. When log_statement is none, there is no query string log on master, maybe we could log the query string when there is error (not sure if this has been the gpdb behavior or not). Or we could just dispatch it when some debugging options are configured (e.g. cassert enabled).

Hi Paul,
We did some tests and tweaks on standard benchmarks and a client app using 6X_STABLE version on a cloud environment a few months ago. The code changes I submitted recently are part of that work. I probably should have got some numbers at hand so that our discussion would be easier. I will try to compile some test results to share with you guys and get your feedback. Thanks.

**Comment by ashwinstar** [comment]
Given the lack of performance numbers and extremely specialized usage, closing this PR without merging the code change. In future if possible to propose the change with substantial performance gain from the change, then can be considered.

**Pull request closed without merging**
