### PR TITLE
Remove redundant tests from language package in TINC

### PR DESCRIPTION
**Pull request by danielgustafsson**
Following up on da580b0 and b4068cb, I took a look at the rest of the language package in TINC and found quite a lot of redundant tests with base for SQL, plpgsql, plperl and plpython.

The majority of the tests are covering very basic functionality in calling functions, and returning data from them, which is tested elsewhere. Quite a lot of time was also spent in testing the same thing for every datatype etc (not to mention creating ~ 200 tables twice which isn't blazing fast). The test left in TINC tests normal/superuser differences which is still interesting. The one test I found interesting was moved to a new greenplum specific suite in src/pl/plperl, the rest removed.

Also removes tests for functionality that has been deprecated, tests already commented out. Since I don't know PL/R very well, I left the PL/R tests mostly intact.

### CODE REVIEW

**Comment by hlinnaka** [comment]
The Naive Bayes functions, nb_classify and friends, are still alive and kicking. There's been discussion on deprecating and removing them, but it hasn't happened yet AFAICS.

**Comment by hlinnaka** [comment]
That said, I believe there's enough coverage for the Naive Bayes functions in the main test suite, so +1 for removing them from TINC anyway.

**Comment by Eulerizeit** [comment]
The code is to be removed entirely. I think Daniel volunteered once there
was agreement.

-- Rob

On Mon, Mar 6, 2017 at 4:24 PM, Heikki Linnakangas <notifications@github.com

**Comment by danielgustafsson** [comment]
> On 06 Mar 2017, at 22:24, Heikki Linnakangas <notifications@github.com> wrote:
> 
> That said, I believe there's enough coverage for the Naive Bayes functions in the main test suite, so +1 for removing them from TINC anyway.

The deprecation has been set in motion, a61bf8b7f2545dacc0452c98abec1054a3089617 pre-empted the removal of the code by purging the docs.

**Comment by Chibin** [comment]
👍

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review!

**Pull request closed without merging**
