### PR TITLE
Remove support for NLS.

### PR DESCRIPTION
**Pull request by hlinnaka**
No-one has attempted to translate Greenplum-specific strings, so it seems
like a disservice to allow anyone to build with --enable-nls.

The PostgreSQL translation files were a bit of a hodge-podge too; they
seemed to be from PostgreSQL 8.4.1, but we still carried the bunch of
incomplete translations that were removed in PostgreSQL 8.4.1. Let's not
pretend that there's any sense in them, and just remove all .po files. If
we want to make NLS to work properly in the future, we can bring them back,
using some sensible versions. Another option would've been to replace them
with the REL8_2_0 versions, which would possibly have made merging with
upstream slightly easier, as you wouldn't get merge conflicts on the
removed files, but those conflicts are easy to deal with. Also, by removing
the files completely, we don't need to decide what to do with the
references to pgsql-bugs@postgresql.org in them (we're trying to replace
all those references with bugs@greenplum.org).

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Considering the state they're in it makes sense right now to remove them. I'm however all for re-adding them with sensible content and a proper maintenance strategy/plan when time allows.

**Comment by andreasscherbaum** [comment]
We got questions from customers in the past, if and when we will provide translated versions of the software. If we remove NLS now, how easy is it to bring it back in later?

That said, since we don't use them right now, I don't have a problem with updating them to a PG version.

**Comment by hlinnaka** [comment]
On 11/09/2015 10:28 PM, Andreas Scherbaum wrote:
> We got questions from customers in the past, if and when we will
> provide translated versions of the software. If we remove NLS now,
> how easy is it to bring it back in later?

All the infrastructure is still there; someone just needs to do the 
translation. All this patch does is comment out the configure option. 
Removing the .po files no big deal, as the files were not current anyway.

If we start supporting NLS, I'd like to do some hacking in the build 
scripts so that we could use PostgreSQL's .po files as is, and just 
provide additional .po files for all the extra strings in Greenplum that 
are not present in upstream. I think that would make maintaining the 
translations a lot easier. (I also wrote a note on this in the comment 
in the configure.in file).

> That said, since we don't use them right now, I don't have a problem
> with updating them to a PG version.

Ok. Any objections to just removing them all for now?

- Heikki

**Comment by andreasscherbaum** [comment]
As long as we don't close the door behind us: no objections.

**Comment by danielgustafsson** [comment]
I think this if anything makes it easier by simplifying the merge thus making it quicker to reach a good state with translations. :+1: from me.

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Pull request closed without merging**
