### PR TITLE
Hardcode the postgis gppkg name.

### PR DESCRIPTION
**Pull request by kaknikhil**
We decided to bump the version no from 2.1.5 to 2.1.5+pivotal.1 and not
2.1.6 because we want to be in sync with the open source postgis version.
The only change in the release is the api change to get_attstatsslot.

### CODE REVIEW

**Comment by kmacoskey** [comment]
@kaknikhil @pivotal-mike 
This will need to be rebased before merging. I know that this PR was +1'd last week already, and it's the same changes. https://github.com/greenplum-db/gpdb-release/pull/35

But before merging this in, we have a couple of question. 
What is the context of this change? is it just to match the open source versioning? 

What is the next version after `2.1.5+pivotal.1` and is it semi-semantic safe? 

Hardcoding the version means that when the version changes, a commit will be necessary in `master` and `5X_STABLE`, is this intended? We typically try to avoid such things in CI that require commits for version changes. Sometimes we handle that by having the version be an interpolated variable so that the actually commit happens in the variables file in `continuous-integration`

**Comment by kaknikhil** [comment]
@kmacoskey 
Thanks for the review

1. We will rebase before merging
2. The next version will most likely be 2.1.5+pivotal.2 and so on. As we keep backporting commits from upstream, we expect more of these pivotal patches.
3. Good suggestion about the variable name in the secrets file. We will make the change and update this PR

**Comment by kmacoskey** [comment]
One pattern that has worked well for us in a few places has been to interpolate only the version itself, like so:
```
regexp: release/gpdb5/postgis-((postgis-gppkg-rhel6-version))-gp5-rhel6-x86_64.gppkg
```
Then in the secrets file:
```
postgis-gppkg-rhel6-version: "2.1.5+pivotal.1" 
```

This might be a clean way to separate out the one piece of the `regexp` that should change often. 


Related, if you like the pattern available with the new interpolation syntax, is a new thing we have started trying as well to handle the unfortunate side effect of the new interpolation syntax losing `unbound variable` exceptions when omitted. The pattern is to specify the variable in a dummy anchor with the old style in order to force resolution:

```
# Declare params with {{}} so that (()) params 
#  receive unbound exceptions when ommited
param_declaration_anchor: &declared_params
  postgis-gppkg-rhel6-version: {{postgis-gppkg-rhel6-version}}
```

There are pro's and con's of both options, so I'm just sharing context for some new patterns we have been using. 

The PR looks ok to merge. Will the same pattern be ported back up to `master`?

**Comment by kaknikhil** [comment]
@kmacoskey thank you for the suggestions. We will merge the PR as is now and maybe incorporate these changes the next time around.

Also we don't have a advanced analytics gate in the master pipeline yet but we will use the same pattern whenever we add advanced analytics for the master pipeline.

**Pull request merged**
