### PR TITLE
Fix pg_tablespace catalog documentation

### PR DESCRIPTION
**Pull request by danielgustafsson**
The pg_tablespace system catalog reference documentation had not been updated with the removal of filespaces and spclocation. This ensures that the documentation is accurate with the underlying table structure.

There are still lots of references to filespaces and gpfilespace in the documentation, but I don't consider myself qualified to rewrite those so I'm merely biting off the piece I can chew in order to help out with this.

### CODE REVIEW

**Comment by mkiyama** [comment]
For spcoptions is this correct? Would this be more clear?

Segment instance specific tablespace locations listed as \<codeph>keyword=value\</codeph>. The entries from the \<codeph>WITH\</codeph> clause of \<codeph>CREATE TABLESPACE\</codeph>.

Not sure if the keyword/value pair needs to be in quotes.

**Comment by berlin-ab** [comment]
What should be done to move this forward?

**Comment by mkiyama** [comment]
FYI - the doc file has been updated since this PR was opened
Here is the latest commit 633960feb4c8

Here is the current HTML version of the doc.
http://docs-gpdb-6x.cfapps.io/600/ref_guide/system_catalogs/pg_tablespace.html

**Comment by danielgustafsson** [comment]
Thanks for fixing this @mkiyama, I was struggling to find time to return to this PR. Closing.

**Pull request closed without merging**
