### PR TITLE
Back-patch libpq support for TLS versions beyond v1

### PR DESCRIPTION
**Pull request by ashwinstar**
Back-porting these commits from master to 5X_STABLE.
------
This was in part already supported as the backend part of the below
commit was already backported. This brings in the frontend changes
as well the followup commit to remove backend support for SSLv3 as
it no longer make any sense to keep it around.

  commit 4dddf8552801ef013c40b22915928559a6fb22a0
  Author: Tom Lane <tgl@sss.pgh.pa.us>
  Date:   Thu May 21 20:41:55 2015 -0400

    Back-patch libpq support for TLS versions beyond v1.

    Since 7.3.2, libpq has been coded in such a way that the only SSL protocol
    it would allow was TLS v1.  That approach is looking increasingly obsolete.
    In commit 820f08cabdcbb899 we fixed it to allow TLS >= v1, but did not
    back-patch the change at the time, partly out of caution and partly because
    the question was confused by a contemporary server-side change to reject
    the now-obsolete SSL protocol v3.  9.4 has now been out long enough that
    it seems safe to assume the change is OK; hence, back-patch into 9.0-9.3.

    (I also chose to back-patch some relevant comments added by commit
    326e1d73c476a0b5, but did *not* change the server behavior; hence, pre-9.4
    servers will continue to allow SSL v3, even though no remotely modern
    client will request it.)

    Per gripe from Jan Bilek.

  commit 326e1d73c476a0b5061ef00134bdf57aed70d5e7
  Author: Tom Lane <tgl@sss.pgh.pa.us>
  Date:   Fri Jan 31 17:51:07 2014 -0500

    Disallow use of SSL v3 protocol in the server as well as in libpq.

    Commit 820f08cabdcbb8998050c3d4873e9619d6d8cba4 claimed to make the server
    and libpq handle SSL protocol versions identically, but actually the server
    was still accepting SSL v3 protocol while libpq wasn't.  Per discussion,
    SSL v3 is obsolete, and there's no good reason to continue to accept it.
    So make the code really equivalent on both sides.  The behavior now is
    that we use the highest mutually-supported TLS protocol version.

    Marko Kreen, some comment-smithing by me

### CODE REVIEW

**Comment by Eulerizeit** [comment]
@pivotal-mike @schubert @lij55 FYI

**Comment by hlinnaka** [comment]
This seems to be missing the change to `initialize_SSL` from commit 326e1d7:
```
@@ -880,9 +887,11 @@ initialize_SSL(void)
 							SSLerrmessage())));
 	}
 
-	/* set up ephemeral DH keys, and disallow SSL v2 while at it */
+	/* set up ephemeral DH keys, and disallow SSL v2/v3 while at it */
 	SSL_CTX_set_tmp_dh_callback(SSL_context, tmp_dh_cb);
-	SSL_CTX_set_options(SSL_context, SSL_OP_SINGLE_DH_USE | SSL_OP_NO_SSLv2);
+	SSL_CTX_set_options(SSL_context,
+						SSL_OP_SINGLE_DH_USE |
+						SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3);
 
 	/* set up ephemeral ECDH keys */
 	initialize_ecdh();
```

**Comment by lij55** [comment]
Disable SSLv3 should be correct thing but it might cause old client tool unable to work. Could we just keep 5X branch just as it is now and update the encryption for GPDB 6 only?

**Comment by Eulerizeit** [comment]
IIRC the patch on master didn't disable SSLv.3 until the Postgres version was 9.4. @ashwinstar am I remembering correctly? That would seem to mitigate @lij55's concern.

**Comment by danielgustafsson** [comment]
The original backport in a7c6138c09a83867e1e5ee7f9db7f07ea62c6c6b indeed seems to lack a hunk from upstream to disable SSLv3. I do seem to recall there was a discussion around that at the time, but I can't find any emails about it.. and the commit message implies that it was supposed to go away.. but I can't shake the feeling that it was done on purpose. Either way, for 6.x I can't see why we'd like to keep it so let's fix it there too.

**Comment by Eulerizeit** [comment]
@ashwinstar can you rebase this and commit it please. We are going to NOT disable SSLv3 in 5.0 so this seems ready to go.

**Pull request merged**
