### PR TITLE
Readme update with docker quickstart guide

### PR DESCRIPTION
**Pull request by lucaslonergan**
Added a link to a quickstart docker guide located on the Pivotal Engineering Journal.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Considering we have a section named _"Development with Docker (alpha)"_ it seems superflous to add yet another section for Docker. Wouldn't this be better as a subsection in the already existing Docker section or simply in the lead paragraph?

**Comment by lucaslonergan** [comment]
@danielgustafsson Didn't catch that before - I moved the link to the Development with Docker section.

**Comment by danielgustafsson** [comment]
Thanks, :+1: on pushing this squashed into a single commit.

**Comment by danielgustafsson** [comment]
Do you have commit access to the repo or do you want me to push this for you?

**Comment by adam8157** [comment]
also LGTM, merge it for you :) (looks like Lucas hasn't seen the comments above)

**Comment by danielgustafsson** [comment]
Yeah, thanks for committing this!

**Pull request merged**
