### PR TITLE
Replace pg_regress test timing with upstream implementation

### PR DESCRIPTION
**Pull request by danielgustafsson**
The test and diff timing was added to GPDB pg_regress long before the feature existed in upstream. This has now been added upstream however so remove our implementation in favor of the one in PostgreSQL.  This does remove printing the diff time, but before that's re-implemented I think we need an argument for why that matters as we have gotten the diff time down low enough that further optimizations won't make much difference.

This also fixes test time printing for single test invocations, which never worked (was never implemented) in the Greenplum version.

We will get this when merging upstream 12, but I needed it to smoothen the path for my TAP patch, so I figured I might as well post this as a PR.

### CODE REVIEW

**Comment by hlinnaka** [comment]
> The  test and diff timing was added to GPDB pg_regress long before the  feature existed in upstream. This has now been added upstream however so  remove our implementation in favor of the one in PostgreSQL. 

Makes sense.

> This does  remove printing the diff time, but before that's re-implemented I think  we need an argument for why that matters as we have gotten the diff  time down low enough that further optimizations won't make much  difference.

Yeah, I don't think it's really needed to print the diff times anymore. It was useful earlier, to pinpoint that gpdiff was slow, but that's not a big problem anymore. Out of curiosity though, the numbers that are printed with this patch, do they include the gpdiff time or not?

> This also fixes test time printing for single test invocations, which  never worked (was never implemented) in the Greenplum version.

Ah, cool. That has annoyed me, but never enough to bother fixing it. Nice if it gets fixed.

Thanks!

**Comment by danielgustafsson** [comment]
> On 31 Jul 2019, at 17:20, Heikki Linnakangas <notifications@github.com> wrote:
> Yeah, I don't think it's really needed to print the diff times anymore. It was useful earlier, to pinpoint that gpdiff was slow, but that's not a big problem anymore.
> 
Agreed, speeding up gpdiff at this point has very diminishing returns.
> Out of curiosity though, the numbers that are printed with this patch, do they include the gpdiff time or not?
> 
It's exclusive of gpdiff time, only the time spent executing the test is printed.

**Comment by danielgustafsson** [comment]
PR rebased on top of current master, will push shortly unless there are objections

**Comment by danielgustafsson** [comment]
This will not come as part of the merge, so close.

**Comment by ashwinstar** [comment]
On Wed, Feb 12, 2020 at 6:22 AM Daniel Gustafsson <notifications@github.com>
wrote:

> This will not come as part of the merge, so close.
>
Will now come ?

**Comment by danielgustafsson** [comment]
> On 12 Feb 2020, at 15:34, Ashwin Agrawal <notifications@github.com> wrote:
> 
> On Wed, Feb 12, 2020 at 6:22 AM Daniel Gustafsson <notifications@github.com>
> wrote:
> 
> > This will not come as part of the merge, so close.
> >
> Will now come ?

Ah, yes ;)

**Pull request closed without merging**
