### PR TITLE
fix of issue: gpdb6 not compiling on gcc12

### PR DESCRIPTION
**Pull request by kishenkoilya**
Those changes fix this [issue](https://github.com/greenplum-db/gpdb/issues/14264). Basically its a combination of this [commit](https://github.com/greenplum-db/gpdb/commit/585e90b69dcc4e4387d60e93ef046830d1560631) and fix proposed by @bradfordboyle in issue mentioned above. Works on earlier versions of gcc too.

### CODE REVIEW

**Comment by kishenkoilya** [comment]
Are there any details on what is the trouble with this fix? Not compiling, or failing tests, etc?

**Comment by interma** [comment]
> Are there any details on what is the trouble with this fix? Not compiling, or failing tests, etc?

Oh sorry, it's a little inconvenient for the outside contributor, pasted for you:
```
Writing postgres.shdescription
clibwrapper.cpp: In function 'gpos::INT gpos::clib::Vsnprintf(gpos::CHAR*, gpos::SIZE_T, const CHAR*, __va_list_tag*)':
clibwrapper.cpp:383:44: warning: function might be possible candidate for 'gnu_printf' format attribute [-Wsuggest-attribute=format]
  return vsnprintf(src, size, format, vaArgs);
                                            ^
fileam.c: In function 'externalgettup_custom':
fileam.c:964:11: warning: statement with no effect [-Wunused-value]
     pstate->raw_buf_len bytesread;
     ~~~~~~^~~~~~~~~~~~~
fileam.c:964:25: error: expected ';' before 'bytesread'
     pstate->raw_buf_len bytesread;
                         ^~~~~~~~~
make[5]: *** [fileam.o] Error 1
make[4]: *** [external-recursive] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [access-recursive] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install-backend-recurse] Error 2
make[1]: *** [install-src-recurse] Error 2
make: *** [dist] Error 2
```

**Comment by kishenkoilya** [comment]
Sorry, mistype. Fixed.

**Review by adam8157 — CHANGES_REQUESTED** [review]
I applied your PR, but it still fails.

```
$ make -C src/backend/access/external all
make: Entering directory '/home/gpadmin/gpdb6/src/backend/access/external'
gcc-12 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3 -std=gnu99   -Werror=uninitialized -Werror=implicit-function-declaration -I../../../../src/include -D_GNU_SOURCE   -c -o fileam.o fileam.c
fileam.c: In function ‘externalgettup_custom’:
fileam.c:975:41: error: ‘error_caught’ is used uninitialized [-Werror=uninitialized]
  975 |                         bool            error_caught = false;
      |                                         ^~~~~~~~~~~~
In file included from ../../../../src/include/postgres.h:53,
                 from fileam.c:34:
../../../../src/include/utils/elog.h:421:29: error: ‘save_exception_stack’ is used uninitialized [-Werror=uninitialized]
  421 |                 sigjmp_buf *save_exception_stack = PG_exception_stack; \
      |                             ^~~~~~~~~~~~~~~~~~~~
../../../../src/include/utils/elog.h:421:29: note: ‘save_exception_stack’ was declared here
  421 |                 sigjmp_buf *save_exception_stack = PG_exception_stack; \
      |                             ^~~~~~~~~~~~~~~~~~~~
fileam.c:980:25: note: in expansion of macro ‘PG_TRY’
  980 |                         PG_TRY();
      |                         ^~~~~~
../../../../src/include/utils/elog.h:422:39: error: ‘save_context_stack’ is used uninitialized [-Werror=uninitialized]
  422 |                 ErrorContextCallback *save_context_stack = error_context_stack; \
      |                                       ^~~~~~~~~~~~~~~~~~
../../../../src/include/utils/elog.h:422:39: note: ‘save_context_stack’ was declared here
  422 |                 ErrorContextCallback *save_context_stack = error_context_stack; \
      |                                       ^~~~~~~~~~~~~~~~~~
fileam.c:980:25: note: in expansion of macro ‘PG_TRY’
  980 |                         PG_TRY();
      |                         ^~~~~~
cc1: some warnings being treated as errors
make: *** [<builtin>: fileam.o] Error 1
make: Leaving directory '/home/gpadmin/gpdb6/src/backend/access/external'
```

**Comment by adam8157** [comment]
This issue is complicated, thanks for taking the challenge. I'm closing this PR based on my test (feel free to poke me if I did something wrong).

For further discussion, please follow the issue https://github.com/greenplum-db/gpdb/issues/14264

**Pull request closed without merging**
