### PR TITLE
Remove obsolete pg_upgrade test data

### PR DESCRIPTION
**Pull request by danielgustafsson**
Back when the initial backport of pg_upgrade was added to Greenplum we included a small dump of a 4.3.x cluster for testing purposes. This cluster was inadequate for testing pg_upgrade back then, and is even more so today. Remove to reduce potential confusion that these files are actually part of the now quite extensive test harness for pg_upgrade in Greenplum.

### CODE REVIEW

**Comment by hlinnaka** [comment]
I don't know, having a cluster like that seems useful for testing. Running the extensive test harness locally seems difficult. As in, I don't know where to start.

Sure, this tiny test cluster doesn't cover much. It does cover the few special cases that we've added GPDB code for, though: AO tables, and converting the numeric datatype.

**Comment by danielgustafsson** [comment]
> On 5 Nov 2018, at 11:18, Heikki Linnakangas <notifications@github.com> wrote:
> 
> I don't know, having a cluster like that seems useful for testing. Running the extensive test harness locally seems difficult. As in, I don't know where to start.

`make -C contrib/pg_upgrade installcheck` will upgrade the currently running cluster and will consume whatever is in it (it assumes it’s the leftovers of an ICW run). The cluster should be a gpdemo cluster, not for any technical reason but for the reason that the testscript must create a new matching cluster so it was easiest to go with a defined way of setting one up. As long as the old cluster has three segments it’s probably just going to work even if it isn’t a gpdemo one.

`make -C contrib/pg_upgrade check` will only upgrade the QD as a quick test that the schema can be upgraded at all.

The difference to the test which is executed in the pipeline is that it runs off a predefined dataset to ensure a stable test. For testing locally the above mentioned targets should be maintained such that they just work for running an upgrade test repeatedly without harming the "old” cluster in any way.

> Sure, this tiny test cluster doesn't cover much. It does cover the few special cases that we've added GPDB code for, though: AO tables, and converting the numeric datatype.

Question is how useful it is to carry a 4.3 cluster which requires access to a proprietary Greenplum installation to test?

**Comment by ashwinstar** [comment]
@danielgustafsson Seems good to be committed (green and approved)

**Comment by danielgustafsson** [comment]
> On 14 Dec 2018, at 15:51, Ashwin Agrawal <notifications@github.com> wrote:
> 
> @danielgustafsson Seems good to be committed (green and approved)
> 
Well, it has one +1 and one -1 so erring on the side of caution I was hoping for more input.

**Comment by ashwinstar** [comment]
@hlinnaka does Daniel's answer above help to provide input where to start? Do you feel we should continue to carry these files around? Based on the same we can bring closure (either commit or just close it).

Reading the FIXME in the README, it seems to me that it's not something which could be of general use but seems with special knowledge only can use it.

**Comment by danielgustafsson** [comment]
Hearing no more objections, I've pushed this to master. The data is still available in back-branches and I don't think it makes any sense to backport this.

**Pull request closed without merging**
