### PR TITLE
Move update_intersect_* test from TINC to main regression suite.

### PR DESCRIPTION
**Pull request by hlinnaka**
All of these tests used the same test table, but it was dropped and
re-created for each test. To speed things up, create it once, and wrap each
test in a begin-rollback block.

There was one change in expected output, in union_update_test30, that I
could not explain:
```
======================================================================
@@ -1691,8 +1688,7 @@
 (1 row)

 UPDATE dml_union_r SET a = ( SELECT a FROM dml_union_r UNION ALL SELECT a FROM dml_union_s);
-ERROR:  One or more assertions failed
-DETAIL:  Expected no more than one row to be returned by expression
+ERROR:  more than one row returned by a subquery used as an expression
 --SELECT COUNT(DISTINCT(a)) FROM dml_union_r;
 -- @description union_update_test31: Negative Tests  more than one row returned by a sub-query used as an expression
 UPDATE dml_union_r SET b = ( SELECT a FROM dml_union_r EXCEPT ALL SELECT a FROM dml_union_s);
======================================================================
```
I.e. the error message had changed, from an ORCA-detected assertion, to
what the backend natively throws from nodeSubplan.c. When I ran the TINC
test directly on my laptop, I also got the "ERROR:  more than one row
returned by a subquery used as an expression" error, rather than the "One
or more assertions failed" error. I don't know what's going on here, but
the error message I get now seems just as correct.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@bhuvnesh2703, @d, any idea what might have caused that difference in the error message that I'm seeing? When you run the test locally, which error do you get? What does the access plan look like? Mine looks like this:
```
postgres=# explain UPDATE dml_union_r SET a = ( SELECT a FROM dml_union_r UNION ALL SELECT a FROM dml_union_s);
                                                                         QUERY PLAN                                                                          
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 Update  (cost=0.00..1765454.62 rows=34 width=1)
   ->  Result  (cost=0.00..1765443.68 rows=67 width=42)
         ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..1765443.68 rows=67 width=38)
               Hash Key: ((subplan))
               ->  Assert  (cost=0.00..1765443.67 rows=67 width=38)
                     Assert Cond: (((subplan)) <> (-1)) IS DISTINCT FROM false
                     ->  Split  (cost=0.00..1765443.67 rows=67 width=38)
                           ->  Result  (cost=0.00..1765443.67 rows=34 width=38)
                                 ->  Table Scan on dml_union_r  (cost=0.00..1765443.66 rows=334 width=38)
                                 SubPlan 1
                                   ->  Materialize  (cost=0.00..862.01 rows=101 width=4)
                                         ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..862.01 rows=101 width=4)
                                               ->  Append  (cost=0.00..862.00 rows=34 width=4)
                                                     ->  Table Scan on dml_union_r  (cost=0.00..431.00 rows=34 width=4)
                                                     ->  Sequence  (cost=0.00..431.00 rows=1 width=4)
                                                           ->  Partition Selector for dml_union_s (dynamic scan id: 1)  (cost=10.00..100.00 rows=34 width=4)
                                                                 Partitions selected: 11 (out of 11)
                                                           ->  Dynamic Table Scan on dml_union_s (dynamic scan id: 1)  (cost=0.00..431.00 rows=1 width=4)
 Settings:  optimizer=on
 Optimizer status: PQO version 2.7.0
(20 rows)
```

**Comment by d** [comment]
Hmm, that surprises me. I'll take a look at this

**Comment by d** [comment]
This test is sensitive to the number of segments:
```
                                                                                       QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Update  (cost=0.00..1765478.62 rows=50 width=1)
   ->  Result  (cost=0.00..1765462.21 rows=100 width=42)
         ->  Redistribute Motion 2:2  (slice3; segments: 2)  (cost=0.00..1765462.21 rows=100 width=38)
               Hash Key: public.dml_union_r.a
               ->  Assert  (cost=0.00..1765462.20 rows=100 width=38)
                     Assert Cond: (public.dml_union_r.a <> (-1)) IS DISTINCT FROM false
                     ->  Split  (cost=0.00..1765462.19 rows=100 width=38)
                           ->  Result  (cost=0.00..1765462.19 rows=50 width=38)
                                 ->  Nested Loop Left Join  (cost=0.00..1765462.19 rows=100 width=30)
                                       Join Filter: true
                                       ->  Table Scan on dml_union_r  (cost=0.00..431.00 rows=50 width=26)
                                       ->  Assert  (cost=0.00..862.07 rows=1 width=4)
                                             Assert Cond: (row_number()) = 1
                                             ->  Materialize  (cost=0.00..862.07 rows=101 width=12)
                                                   ->  Broadcast Motion 1:2  (slice2)  (cost=0.00..862.07 rows=202 width=12)
                                                         ->  Result  (cost=0.00..862.00 rows=51 width=12)
                                                               ->  Window  (cost=0.00..862.00 rows=51 width=12)
                                                                     ->  Gather Motion 2:1  (slice1; segments: 2)  (cost=0.00..862.00 rows=101 width=4)
                                                                           ->  Append  (cost=0.00..862.00 rows=51 width=4)
                                                                                 ->  Table Scan on dml_union_r  (cost=0.00..431.00 rows=50 width=4)
                                                                                 ->  Sequence  (cost=0.00..431.00 rows=1 width=4)
                                                                                       ->  Partition Selector for dml_union_s (dynamic scan id: 1)  (cost=10.00..100.00 rows=50 width=4)
                                                                                             Partitions selected: 11 (out of 11)
                                                                                       ->  Dynamic Table Scan on dml_union_s (dynamic scan id: 1)  (cost=0.00..431.00 rows=1 width=4)
 Settings:  optimizer=on
 Optimizer status: PQO version 2.7.0
(26 rows)
```

The error message `One or more assertions failed` comes from the `ExecAssertOp`, whereas "more than one row returned by a subquery used as an expression" comes from the `ExecSubPlan` under the scan

**Comment by hlinnaka** [comment]
A-ha, thanks! We could memorize the alternative output, or we could "set optimizer_segments" to force it one way or another. It is uncomfortably close to the edge, though, for a stable test. It's unfortunate that ORCA produces a different error message for the same issue.. Any preference?

**Comment by khannaekta** [comment]
Preferably, we can `set optimizer_segments=2`, execute the test and `reset optimizer_segments` after executing the test.

**Comment by hlinnaka** [comment]
On 03/01/2017 09:58 PM, khannaekta wrote:
> Preferably, we can `set optimizer_segments=2`, execute the test and `reset optimizer_segments` after executing the test.

Ok, added that. Pushed a new version to this PR, please have another look.

- Heikki

**Comment by hlinnaka** [comment]
Pushed, thanks for the review!

**Pull request closed without merging**
