### PR TITLE
Enable partial aggregate functions pushdown to distributed postgres_fdw servers.

### PR DESCRIPTION
**Pull request by zhaorui20005**
### 1. Scenario
We consider such scenario -- foreign table f_tbl is distributed randomly across multiple remote postgres server.
```
CREATE EXTENSION postgres_fdw;

CREATE SERVER multi_pg_servers
FOREIGN DATA WRAPPER postgres_fdw
OPTIONS (mpp_execute 'multi servers', num_segments '2', multi_hosts '127.0.0.1 127.0.0.1', multi_ports '5432 5555', dbname 'postgres');

CREATE USER MAPPING FOR gpadmin 
SERVER multi_pg_servers OPTIONS (user 'postgres');

CREATE FOREIGN TABLE demo_f_tbl(a int, b int) 
SERVER multi_pg_servers
OPTIONS(table_name 'demo_local_tbl');
```
- We set option `mpp_execute` to `multi servers` for server `multi_pg_server`. So when select something from postgres_fdw foreign table, the scan will be executed in a distributed way.
  Option `mpp_execute = 'multi servers'` is almost same as `mpp_execute = 'all segments'`, but there are multiple remote servers when `mpp_execute = 'multi servers'`.
- The number of executors is controlled by the server option `num_segments`. If this option is not set, the number of executors will be the default number of segments in GPDB. 
- Options `multi_hosts` and `multi_ports` can specify multiple remote postgres server. The number of remote postgres server **MUST** be same as the option `num_segments`.

By doing so, we build the scenario that the foreign table is a distributed foreign table which data stored on multiple remote servers. 

There are some customers who have the need to scan data from distributed foreign servers. The basic need is to make the result correct and make some basic aggregate functions pushed down to remote distributed servers and keep the result correct.

### 2. Results
As FDW is designed for Postgres which is not a distributed system database, we have to change the plan and executors for distributed scenario. 

The result of sequence scan is correct by default, but it does **NOT** work for aggregate functions.

Looking at the example below:
```
demodb=# explain verbose select sum(c1) from demo_f_tbl;
                                   QUERY PLAN
--------------------------------------------------------------------------------
 Gather Motion 2:1  (slice1; segments: 2)  (cost=100.02..101.15 rows=2 width=8)
   Output: (sum(c1))
   ->  Foreign Scan  (cost=100.02..101.12 rows=1 width=8)
         Output: (sum(c1))
         Relations: Aggregate on (public.demo_f_tbl)
         Remote SQL: SELECT sum(c1) FROM public.demo_local_table
 Optimizer: Postgres query optimizer
(7 rows)

demodb=# select sum(c1) from demo_f_tbl;
 sum
-----
  36
  90
(2 rows)
```
The plan after this PR will be like:
```
demodb=# explain verbose select sum(c1) from demo_f_tbl;
                                      QUERY PLAN
--------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=101.15..101.16 rows=1 width=8)
   Output: sum(c1)
   ->  Gather Motion 2:1  (slice1; segments: 2)  (cost=100.02..101.15 rows=2 width=8)
         Output: (PARTIAL sum(c1))
         ->  Foreign Scan  (cost=100.02..101.12 rows=1 width=8)
               Output: (PARTIAL sum(c1))
               Relations: Aggregate on (public.demo_f_tbl)
               Remote SQL: SELECT sum(c1) FROM public.demo_local_table
 Optimizer: Postgres query optimizer
(9 rows)

demodb=# select sum(c1) from demo_f_tbl;
 sum
-----
 126
(1 row)
```

### 3. Main commits
We have made the following modification to make this happen:
1. Make multi-stage AGG plan for FDW
2. Adjust push down conditions for APIs in postgres_fdw
3. Change deparse result for partial AGG functions in remote SQLs
4. Make result transforms from final result from remote servers to internal result which final aggregate needs.
5. Add testing cases and fix corner cases to make the result correct.
6. Support connecting to multiple remote postgres servers.

As postgres_fdw is the first Foreign Data Wrapper, many other FDWs need to add new features according to the implementations of postgres_fdw. 
So we want to make a template for MPP AGG push down scenarios.
Currently we try our best to make as small as modifications to postgres_fdw so that it is not difficult for future merging work from upstream. 

Co-authered-by: zhaorui <zhaoru@vmware.com>
Co-authored-by: jingwen-yang-yjw <jingweny1@vmware.com>

### CODE REVIEW

**Comment by kainwen** [comment]
Good job. Will play with it and then take a look.

**Comment by zhaorui20005** [comment]
There are discussions about [partial aggregate push down](https://www.mail-archive.com/pgsql-hackers@lists.postgresql.org/msg141848.html). The upstream aims to run postgres_fdw in parallel mode, but we face the similar problems to them that we have to handle the internal result.

The solution of upstream is that add one column to `pg_aggregate` catalog table called `partialaggfn`. This function just return the internal result of the `aggtransfn`. So when postgres generates 2-staged agg plan, postgres_fdw will deparse the `partialaggfn(column)` instead of  `aggfn(column)`.

But I think this solution does not work for us, for the two following reasons:
1. Need to change the catalog table pg_aggregate.
2. This solution relies on the remote server support `partialaggfn`, if the remote server is not postgres, it will be difficult to implement. 

Our solution only needs to make changes to FDW extensions, and require them support common agg functions.

**Comment by adam8157** [comment]
I have two questions before playing it.

> The result of sequence scan is correct by default

1, I don't get this, it's supposed to output multi results, isn't it? What is the distribution policy of the foreign table?

2, is the aggregation the last piece of the feature? The feature that Greenplum connects to the same single node Postgres via multi connections.

**Comment by jingwen-yang-yjw** [comment]
> I have two questions before playing it.
> 
> > The result of sequence scan is correct by default
> 
> 1, I don't get this, it's supposed to output multi results, isn't it? What is the distribution policy of the foreign table?
> 
> 2, is the aggregation the last piece of the feature? The feature that Greenplum connects to the same single node Postgres via multi connections.

Hi @adam8157, 

The scenario we consider is that each segment connects to different single node Postgres.
1. The foreign table is randomly distributed on different single node Postgres. 
2. The aggregation is in the scenario that gpdb connects to **different** single node Postgres via multi connections.

It's like as follows.
```
// This SQL is just an example, and we have tried to support it but not pushed related commit in this pr.
// Because code changes might be very huge and there is workaround to test MPP Aggregates pushdown feature.
CREATE SERVER postgres_local_server
FOREIGN DATA WRAPPER postgres_fdw
OPTIONS (mpp_execute 'all segments',  multi_hosts '10.117.190.1, 10.117.190.2, 10.117.190.3', multi_ports '5432, 5432, 5432', num_segments '3', dbname 'postgres');

CREATE USER MAPPING FOR public 
SERVER postgres_local_server OPTIONS (user 'postgres');

CREATE FOREIGN TABLE mpp_postgres_table(a int, b int) 
SERVER postgres_local_server 
OPTIONS(table_name 'test_multi_server');
```
```
// Now this SQL is just used to simulated the scenario with multi servers.
CREATE SERVER postgres_local_server
FOREIGN DATA WRAPPER postgres_fdw
OPTIONS (mpp_execute 'all segments',  host '127.0.0.1', port '5432', num_segments '3', dbname 'postgres');

// The SQL above is similar to -->
CREATE SERVER postgres_local_server
FOREIGN DATA WRAPPER postgres_fdw
OPTIONS (mpp_execute 'all segments',  multi_hosts '127.0.0.1, 127.0.0.1, 127.0.0.1', multi_ports '5432, 5432, 5432', num_segments '3', dbname 'postgres');
```

We will consider to push the related commit that support multi_hosts and multi_ports.
Maybe it will help to understand usage scenarios of this MPP aggregate functions pushdown.

**Comment by adam8157** [comment]
Ah, I totally got it wrong, thanks for the info.

Seems this PR is still under active development, I suggest converting it to draft until you have the confidence that it's ready for review and merge.

**Comment by jingwen-yang-yjw** [comment]
> Ah, I totally got it wrong, thanks for the info.
> 
> Seems this PR is still under active development, I suggest converting it to draft until you have the confidence that it's ready for review and merge.

We have finished development for feature MPP aggregates functions pushdown.
Recent commits are about test cases or small improvement. We won't change the main approach implementing MPP aggregate functions pushdown feature.
So I think maybe it's ready for review.

**Comment by zhaorui20005** [comment]
For the convenience of reviewing, we would split this PR into several PRs:
https://github.com/greenplum-db/gpdb/pull/15819
https://github.com/greenplum-db/gpdb/pull/15821
https://github.com/greenplum-db/gpdb/pull/15822

**Pull request closed without merging**
