### PR TITLE
fix 6x gpload cannot process multipul input files

### PR DESCRIPTION
**Pull request by xiaoxiaoHe-E**
* fix gpload cannot process multiple input files
gpload can process multiple files in one input source.
We need the file location when creating or finding reuse external tables. 
The original location string is wrong. We make it write in the right way.

* add test case for multiple hostname in one input source

the input yaml config is like :
```
GPLOAD:
   INPUT:
     - SOURCE:
         LOCAL_HOSTNAME:
           - 10.117.190.113
           - 10.117.190.51
         PORT: 8081
         FILE: 
           - /home/gpadmin/workspace/test.txt
           - /home/gpadmin/workspace/test1.txt
```
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by zhaorui20005** [comment]
Can you show us an example of multi-location in the pr info? Like what is the yaml look like and the external table location look like.

**Comment by tonyyf** [comment]
Two points:
1. Add case for same file but with multiple NICs (IPs).
2. Check if the error message always reports same file missing.

**Review by tonyyf — APPROVED** [review]
LGTM

**Comment by xiaoxiaoHe-E** [comment]
We thought gpload write the file location in an unusual way. However gpfdist can still process it if started with `-f file location` in the command.  Gpload starts a gpfdist process with the right command and the files can be read successfully. 
`-f` option is not in the gpfdist document, you can find it in the gpfdist code.
Closing this pr for this fix is no longer needed.

**Comment by zhaorui20005** [comment]
Right, the gpfdist parses the path in glob_path function in fstream.c. It can handle not only '*' '?', but can also paths seperated by space.

**Pull request closed without merging**
