### PR TITLE
Update python version to 2.7.12

### PR DESCRIPTION
**Pull request by tushar-dadlani**
- Compile python 2.7.12 on centos6
- Update ext tarball on ivy to remove python 2.6.2
- Update ivy dependencies for python to point to 2.7.12

Signed-off-by: Tushar Dadlani <tdadlani@pivotal.io>

### CODE REVIEW

**Comment by Eulerizeit** [comment]
It there a way for us to remove Python from IVY entirely?

**Comment by ivannovick** [comment]
love it

**Comment by tushar-dadlani** [comment]
This is Mike Roth - @Eulerizeit yes there is, it's moving to RPMs and externalizing dependencies.  Right now we need to use IVY

**Comment by cjcjameson** [comment]
@larham @skahler-pivotal @royc1 I think that if we in Management/Monitoring think that this might break us, we could get ahead of the game by providing a Pipeline Fork running the tests we think will be at risk. Ya?

**Comment by chrishajas** [comment]
Yes, please run this on a fork of the pipeline for all the MU jobs if there are any differences between 2.6 and 2.7. TINC tests also use python so it may be worth it to just run everything to be sure.

**Comment by larham** [comment]
Tushar already has a pipeline up for this. Talk h to him

**Comment by cjcjameson** [comment]
Hi folks, here's the pipeline that we're using to verify the python version change across a wide variety of the tests that use python: https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/python2.7-rhel6

I've coordinated with a few other folks who work on gptransfer & netbackup to unpause two more long-running jobs.

**Comment by larham** [comment]
@tushar-dadlani can you rebase?  I recall that the MU expand redness was fixed after the AMI was updated.

**Comment by cjcjameson** [comment]
Larry rebased yesterday, which got gpexpand green (though it flaked -- I'll take a look). I needed to rebase again because it crashed with https://github.com/greenplum-db/gpdb/commit/13cdbd0b361e7d07ce8b32975c09e0e16eafa82d

**Comment by pivotal-mike** [comment]
@cjcjameson Any objections to merging this in?

**Comment by cjcjameson** [comment]
Looks like gptransfer on the demo pipeline might be having issues

**Comment by Chibin** [comment]
Pushed:
https://github.com/greenplum-db/gpdb/commit/f3c3093bfc7a22b833a48cb266e44adbcf29d0f1
https://github.com/greenplum-db/gpdb/commit/83d0c53e13d0f919e90d400e9da206182e7241bc

**Pull request closed without merging**
