### PR TITLE
Remove *.po translator files

### PR DESCRIPTION
**Pull request by jimmyyih**
Greenplum does not support this. These were originally removed in the
postgres 8.3 merge iteration but the 8.4 through 9.4 merge iterations
brought them back accidentally.

This commit is going directly to 6X_STABLE because the postgres 9.5
merge iteration will remove the *.po translator files for master.

### CODE REVIEW

**Comment by ashwinstar** [comment]
We should document this in merge WIKI for creating iteration branch that `.po` files should be deleted.

**Comment by Eulerizeit** [comment]
On Wed, Mar 20, 2019, 6:26 PM Ashwin Agrawal <notifications@github.com>
wrote:

> We should document this in merge WIKI for creating iteration branch that
> .po files should be deleted.
>
If it isn't documented then yes.

Rob

**Comment by ashwinstar** [comment]
On Wed, Mar 20, 2019 at 3:29 PM Robert Eckhardt <notifications@github.com>
wrote:

> On Wed, Mar 20, 2019, 6:26 PM Ashwin Agrawal <notifications@github.com>
> wrote:
>
> > We should document this in merge WIKI for creating iteration branch that
> > .po files should be deleted.
> >
> If it isn't documented then yes.


If its documented then its no-op anyways ;-)

**Comment by danielgustafsson** [comment]
The merge process has been documented in too many places, most of them slightly different and most of them outdated by now. I know for a fact that this, along with ECPG handling, was documented in one of these places but I have no idea which, and that illustrates the problem.

Wiki documents almost always become outdated as soon as they're saved, it's just something about the format which seems to lend itself to never be updated. I suggest we add a README in the code tree for this, which can/should be kept up to date as the merge proceeds.

**Comment by ashwinstar** [comment]
@jimmyyih seems good to go.

**Comment by jimmyyih** [comment]
@ashwinstar Yes, this PR is good to go.  It is currently waiting on the 6X_STABLE merge process (it's actually not even recorded in the doc @Eulerizeit).

**Pull request merged**
