### PR TITLE
Restructures readme to put build directions front and center

### PR DESCRIPTION
**Pull request by professor**
Partiall addresses https://github.com/greenplum-db/gpdb/issues/2422

### CODE REVIEW

**Comment by jimmyyih** [comment]
Moving the Python module dependencies for gpMgmt below the compilation instructions may not be a good thing.  If a new user follows the README sequentially and does compilation without looking further down, they would probably fail at `make install` if they don't have the Python module dependencies already installed.  The way it's rewritten, it sounds as if the current gpMgmt can be built separately... which they are not built but copied into the install path since it's just Python files (only the version gets stamped into the utilities via putversion perl script).

**Comment by professor** [comment]
We've updated the readme to address @jimmyyih (Good catch, I found that part of the readme very confusing before this change.)

**Comment by andreasscherbaum** [comment]
Looks nice, good work!

**Comment by professor** [comment]
@hlinnaka thanks for the suggestion, I moved code layout down to just above contributing.

**Comment by Eulerizeit** [comment]
Is gp_xerces still needed? I know there was discussion around removing it but I don't know if it was done.

**Pull request merged**
