### PR TITLE
Fix issue that distributed key will be changed automatically when using "create unique index" on 5.2x versions

### PR DESCRIPTION
**Pull request by water32**
In versions before 5.20, adding a unique index requires that the distribution key be a subset of the columns of the unique index, and the 5.2x versions require it as a prefix. The user experience is not good. After code analysis, I think it should be modified. Before version 5.20, the partition table containing unique index will require a prefix when adding partitions, it should be modified to requires a subset.

## Here are some reminders before you submit the pull request

- [*] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by hlinnaka** [comment]
I don't think we should make functional changes like this in back-branches. It's been fixed in 6X_STABLE, and if it's important to a user, they should upgrade.

**Comment by baobao0206** [comment]
There is another function 'transformDistributedBy' needs to be fixed. GreenPlum checks the compatibility between PRIMARY KEY and DISTRIBUTION KEY in that function.

**Comment by yydzero** [comment]
It is too costly for the most affecting customer to upgrade to 6. 

As the changes is introduced in 5.2x, and incompatible with 5.20 and earlier version. It will be better to keep compatible with old version or make it better everywhere (subset over prefix)

**Comment by ginobiliwang** [comment]
@water32 , would you please change the name of the PR to some thing like below
`Fix issue that distributed key will be changed automatically when using "create unique index" on  5.2x versions `
which is more friendly to read.

**Pull request closed without merging**
