### PR TITLE
Remove gpverify code.

### PR DESCRIPTION
**Pull request by ashwinstar**
gpverify functionality was planned in past to deliver online verification of primary and mirror. It's completely dead code as never exposed this functionality and have no plans either. It eliminates creation of unused processes, extra directory, shared memory space, catalog table and all.

### CODE REVIEW

**Comment by asimrp** [comment]
That's quite a clean up!  Looks good to me.  Thanks!

**Comment by hlinnaka** [comment]
Yep, very nice! Please squash the commits into one before pushing.

**Comment by ivannovick** [comment]
nice!

**Comment by hlinnaka** [comment]
Ashwin pushed this yesterday. However, we're now seeing a core dump from the cdbfilerep.t mock test in the buildfarm, on OS X only. @ashwinstar, can you investigate, please?

**Comment by ashwinstar** [comment]
@asimrp @asubramanya Please review the latest commit to fix the unit-test failure, once done will push.

**Comment by asimrp** [comment]
Looks good!  :+1:

**Comment by ashwinstar** [comment]
Thanks for review, Merged closing.

**Pull request closed without merging**
