### PR TITLE
Fix query hang / fallback if involving CTE of replicated (Backport)

### PR DESCRIPTION
**Pull request by THANATOSLAVA**
**Motivation**

This subject has been revisited on several occasions, as seen in the merged PR
13833, PR 14896, and closed PR 13728. However, sporadically, we still encounter
unexpected fallbacks. The hang in the CTE query is a result of a mismatch
between the number of CTE producers and consumers. This mismatch can occur when
there are either more producers than consumers or more consumers than producers,
leading to unconsumed producers or starved consumers that cause the query to
hang.

Historically, we have addressed query hangs by resorting to intentional
fallbacks. While ORCA falling back on the planner is not an ideal solution, it
is preferable to the query not completing. The intentional fallback was
implemented in PR 13833 by restricting the optimization of potential
alternatives that could result in a producer/consumer number mismatch.

In this PR, we reevaluate several test cases previously examined, aiming to find
a solution that avoids hanging or falling back.

**RCA**

The hang in a CTE query commonly arises when the CTE is of a replicated nature,
either tainted or strict. Such occurrences are less frequent if the CTE is hash
or randomly distributed. In the latter case, both producer and consumer
naturally execute on all segments. However, given a replicated input, producers
and consumers can choose to execute on either all segments and then deduplicate,
or, just on one segment. This flexibility results in potential mismatch between
the numbers of producers and consumers. This PR tackles the problem by sending
appropriate distribution requests on both the producer and consumer. Note that a
query hang is usually not a concern with universal input, despite the presence
of duplicate tuples. Universal producer guarantees universal data availability,
and the consumer execution operates based on necessity. This avoids any mismatch
between producer and consumer numbers.

**Implementation**

Historically, we initiate two sets of distribution requests from the physical
sequence operator to its two children. In the first request, we specify both
children to be `Non-Singleton`, aiming for the producer and consumer to execute
across all segments. In the second request, we request `Any` on the producer,
allowing it to retain its inherent distribution property. We align the
consumer's request accordingly. Specifically, if the producer is universal, the
consumer's locality can be `Any`. If the producer is replicated, we forego the
request, which occasionally results in fallbacks due to missing plan alternative
that satisfies all the required properties. In all the other scenarios, we
request `Non-Singleton`, mirroring the first request to spread out data
consumption. Note if the producer is a singleton, we always request the consumer
to be a matching singleton, either on the coordinator or one segment.

As mentioned earlier, query hang arises when dealing with replicated CTEs. In
response, we modify the first distribution request to be `Non-Singleton
Non-Replicated`. This request exclusively handles non-replicated input, where
both the producer and consumer naturally execute across all segments. For
replicated input, a hash filter is applied to enforce the producer into a random
distribution, allowing the consumer to still execute across all segments. In the
second request, we maintain the request for the producer to be `Any` to preserve
its original property. If the original property is replicated, we request the
consumer to be replicated as well. This avoids abandoning the optimization
context.

It's important to clarify that the terms "producer" and "consumer" in the above
requests pertain to the producer and consumer **sides** of the physical sequence
operator. The requests don't directly impact the actual producer, i.e., the
shared scan, or the actual consumer, i.e., consumption of the shared scan.
Therefore, the updated requests don't eliminate the possibility of a number
mismatch between the producer and consumer. However, it does significantly
minimize the likelihood. This is because the plan with the minimal cost is
unlikely to incorporate motions that alter the locality of the actual producer
or consumer from that is requested on their respective sides in an asymmetric
manner that would cause number mismatch.

Interestingly, the physical sequence operator receives a third distribution
request originating from the CTE consumer. This bottom-up request stands out as
an exception in ORCA's top-down optimization framework. The methodology is
documented in this [VLDB paper, section
7.1](https://www.vldb.org/pvldb/vol8/p1704-elhelw.pdf), with the goal of
minimizing unnecessary motions, hash redistributionin particular. It was
implemented by PR 11904. What occurs is the casting of the consumer's derived
property (post partial optimization) as a request back onto the producer.

Currently, this request does not specifically address a replicated CTE input.
However, based on the analysis presented earlier, it becomes evident that this
bottom-up request should not override the producer's duplicate sensitivity.
Specifically, if the CTE starts as replicated but is then converted to random by
the hash filter, we should not allow a duplicate-insensitive request to be sent
to the producer, as it may lead to duplicate hazards and query hang. In this PR,
we assess the derived duplicate sensitivity of the producer and consumer,
preventing mismatching requests.

**Tests**

This PR reverts commit b350160, which solved the query hang by intentional fall
back, while retaining the tests introduced by that commit. Now we no longer
encounter query hang or fallback.

The MDP test, NLJ-Rewindability-CTAS.mdp, reveals a plan diff in which the
duplicate sensitive random distribution request is no more sent to the physical
filter on the CTE consumer side. Pushing a duplicate sensitive random motion
below the physical filter is a conservative maneuver used to handle the scenario
where a CTE is inlined by a filter. In this context, one CTE is referenced
within another CTE, and the results of the first CTE contribute to the filtering
criteria in the second CTE.  While the physical filter is unaware of whether it
references an inlined CTE, the above restriction on replicated distribution
eliminates the possibility of costly query hangs. In this case, the cost model
determines it's less expensive to enforce the duplicate sensitive random
property after the CTE consumption instead of before.

(cherry picked from commit 3e37d72e6579bdfed7e3a1544399a645b460664a)

### CODE REVIEW

**Review by dgkimura — COMMENTED** [review]
Were there any merge conflicts during the cherry-pick?  If so, it'd be good to call them out in the PR.  And if not, it'd be good to know that too.

**Comment by THANATOSLAVA** [comment]
> Were there any merge conflicts during the cherry-pick? If so, it'd be good to call them out in the PR. And if not, it'd be good to know that too.

No conflicts except for `NULL` vs. `nullptr` and regression/mdp tests, which I always discard in cherry-picking and just handle manually.

We did get a different plan diff in NLJ-Rewindability-CTAS.mdp, which I incorporated in this commit message. It got me to think more about the distribution request that we send to physical filter knowing there could be a CTE underneath. I will raise a separate PR on that topic to explain my thoughts.

**Review by dgkimura — APPROVED** [review]

**Review by gpopt — APPROVED** [review]
+1

**Comment by pobbatihari** [comment]
pipeline : https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-6X/jobs/compile_and_test_gpdb/builds/639

**Pull request merged**
