### PR TITLE
Full vacuum on heap table should not commit the transaction in `repai…

### PR DESCRIPTION
**Pull request by asubramanya**
…r_frag()`.

In GPDB, vacuum full on heap relations is divided into two steps. The first
step moves the tuples of the relation to free the last pages. The
second step truncates the unused pages of the relation. Both the steps are
performed in two separate transactions so we don't need to commit the
transaction in `repair_frag()`.

### CODE REVIEW

**Comment by hlinnaka** [comment]
This makes me very scared. Changing the control flow in a fundamental way like this is asking for trouble. (Not this patch's fault, we've controlled the vacuum transactions in the master since time immemorial). For one example, I don't think it's safe to go ahead with the vacuum_page() loop that follows, if the transaction hasn't been committed yet.

It would be nice if we could get PR #790 committed soon. It would change the control flow back the way it is in the upstream, and allow us to perform local transaction commit here. Or if we cannot get that done anytime soon, I wonder if we could at least change that logic for heap tables. AFAICS, there's no reason that vacuuming heap tables need to use global transactions, nor need to have them coordinated across segments like this.

**Comment by asimrp** [comment]
It's a chicken and egg problem, we need the CI green so that #790 can be verified easily.  This patch is a step towards making the CI green.  It fixes a failing test in `src/test/tinc/tincrepo/mpp/gpdb/tests/storage/vacuum/scenario`.  The test simulates a user canceling `vacuum full` on a heap table after tuples are moved but before the table is truncated.  Without this patch the test causes PANIC on master with "cannot abort a transaction that is already committed" error.

Our proposal is to get this patch in so that we can start running the vacuum tests regularly in CI.  Then we can make vacuum operate independently on segments for heap, similar to how PR #790 does for AO.

- Asim and Abhijit

**Comment by hlinnaka** [comment]
Well, if all you want is to paper over the problem temporarily, it'd be better to #ifdef out the code, with a comment along the lines of:
```
/*
 * FIXME: We don't commit the transaction here in GPDB. vacuumStatement_Relation()
 * is responsible for that. This is wrong, because the vacuum_page() calls below might remove
 * tuples that are still be needed if we crash before the commit. But this avoids "cannot abort a
 * transaction that is already committed" error during abort processing, which leads to a PANIC
 * in GPDB.
 */
#if 0
...
#endif
```

Or how about disabling the failing test, until we get PR #790? We apparently don't have a test for the issues that committing this patch would bring either, so it wouldn't be any worse.

**Comment by asubramanya** [comment]
@hlinnaka Can you please explain why `vacuum_page()` would end up removing required tuples if we don't commit the transaction?

**Comment by hlinnaka** [comment]
On 01/18/2017 01:16 AM, Abhijit Subramanya wrote:
> @hlinnaka Can you please explain why `vacuum_page()` would end up
> removing required tuples if we don't commit the transaction?

Hmm. I thought that it would remove tuples that were moved, but I was 
wrong. It only removes tuples that were deemed as dead by the 
scan_heap() stage earlier. The tuple-moving loop constructs new VacPage 
structs to hold the old versions of the tuples that it moves, but those 
VacPages are not processedd by the vacuum_page() loop in repair_frag().

So I guess it's safe. Still gives me creeps, though.

- Heikki

**Comment by ashwinstar** [comment]
On Wed, Jan 18, 2017 at 2:44 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 01/18/2017 01:16 AM, Abhijit Subramanya wrote:
> > @hlinnaka Can you please explain why `vacuum_page()` would end up
> > removing required tuples if we don't commit the transaction?
>
> Hmm. I thought that it would remove tuples that were moved, but I was
> wrong. It only removes tuples that were deemed as dead by the
> scan_heap() stage earlier. The tuple-moving loop constructs new VacPage
> structs to hold the old versions of the tuples that it moves, but those
> VacPages are not processedd by the vacuum_page() loop in repair_frag().
>
> So I guess it's safe. Still gives me creeps, though.
>

The RecordTransactionCommit there has larger implications of causing
cluster down and was seen multiple times by multiple customers, only way
out being reset xlogs causing data-loss. So protecting the clearly known
repro case is more important than no known scenario. hence current code and
comment seems okay.

We still definately need to enhance vacuum to use distributed snapshots but
avoid 2PC, but yes its separate work than this PR.

**Comment by ashwinstar** [comment]
👍

**Comment by hlinnaka** [comment]
On 01/18/2017 04:29 PM, Ashwin Agrawal wrote:
> The RecordTransactionCommit there has larger implications of causing
> cluster down and was seen multiple times by multiple customers, only way
> out being reset xlogs causing data-loss. So protecting the clearly known
> repro case is more important than no known scenario. hence current code and
> comment seems okay.

Wait, what? How can do you get data-loss that way?

- Heikki

**Comment by ashwinstar** [comment]
On Wed, Jan 18, 2017 at 6:34 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 01/18/2017 04:29 PM, Ashwin Agrawal wrote:
> > The RecordTransactionCommit there has larger implications of causing
> > cluster down and was seen multiple times by multiple customers, only way
> > out being reset xlogs causing data-loss. So protecting the clearly known
> > repro case is more important than no known scenario. hence current code
> and
> > comment seems okay.
>
> Wait, what? How can do you get data-loss that way?
>

Ouch... seems connected wrong dots. No data-loss just PANIC for this case.
Was some other situation where transaction was aborted locally and tried to
be committed later, needing pg_resetxlog to fix not this one.

**Comment by hlinnaka** [comment]
On 01/18/2017 07:42 PM, Ashwin Agrawal wrote:
> On Wed, Jan 18, 2017 at 6:34 AM, Heikki Linnakangas <
> notifications@github.com> wrote:
>
>> On 01/18/2017 04:29 PM, Ashwin Agrawal wrote:
>>> The RecordTransactionCommit there has larger implications of causing
>>> cluster down and was seen multiple times by multiple customers, only way
>>> out being reset xlogs causing data-loss. So protecting the clearly known
>>> repro case is more important than no known scenario. hence current code
>> and
>>> comment seems okay.
>>
>> Wait, what? How can do you get data-loss that way?
>
> Ouch... seems connected wrong dots. No data-loss just PANIC for this case.
> Was some other situation where transaction was aborted locally and tried to
> be committed later, needing pg_resetxlog to fix not this one.

Ok, phew! :-)

- Heikki

**Comment by asubramanya** [comment]
@hlinnaka Thanks for confirming that its safe. I will rebase the change on top of master and push it once the PR pipeline is green.

**Comment by asubramanya** [comment]
Pushed: b7aade7140fb142d8c22f1618a10cca73e12d474

**Pull request merged**
