### PR TITLE
Remove DB_IN_STANDBY_MODE, DB_IN_STANDBY_PROMOTED and use DB_IN_ARCHIVE_RECOVERY instead

### PR DESCRIPTION
**Pull request by BaiShaoqi**
Have passed all pipeline , should be ok to merge, now it looks more like 9.4 stable Postgres.

Modify a unittest `test_HandleFtsWalRepPromoteMirror`, because it says need mode `DB_IN_STANDBY_MODE`, but it has been deleted in the pr, so modify unit test to pass.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`

### CODE REVIEW

**Comment by paul-guo-** [comment]
I think pipeline green should be just the first step. We need to understand the context and even what we could do or improve.

**Comment by ashwinstar** [comment]
I think to find what can break or rational for why the state was added to gpdb, might be worth trying to crash the system where `DB_IN_STANDBY_PROMOTED` was set with the removed code in this PR. If things continue to work fine, means mirror comes back up fine as primary and gets promoted fine then the state is not needed. Special play with master and standby for this exercise instead of primary/mirror as code was added for it.

**Comment by BaiShaoqi** [comment]
Thanks, Ashwin, will have a try to see DB_IN_STANDBY_PROMOTED is needed or not.

**Comment by BaiShaoqi** [comment]
> I think to find what can break or rational for why the state was added to gpdb, might be worth trying to crash the system where `DB_IN_STANDBY_PROMOTED` was set with the removed code in this PR. If things continue to work fine, means mirror comes back up fine as primary and gets promoted fine then the state is not needed. Special play with master and standby for this exercise instead of primary/mirror as code was added for it.

After asked @paul-guo-  what your meaning, we both did not figure out what's point.

So I make a commit to test if `DB_IN_STANDBY_PROMOTED` by commenting the use of of the mode.
see commit https://github.com/BaiShaoqi/gpdb/commit/75d0d95cd8c3165391c35c456cf63b3427ff23d0

And it turns out, the commit has passes `fts_recovery_in_progress` and `fts_error`, and behave test `gpinitstandby` and `gpactivatestandby`, does my experiment make sense to you?

**Comment by ashwinstar** [comment]
@BaiShaoqi and @paul-guo- Nope the experiment doesn't cover what I am referring to. Let me try to use more C language (code) this time.

This is what I did to justify why state was added:
1. Checkout code for this PR6725 (which removes the state `DB_IN_STANDBY_PROMOTED`)
2. Add experiment code
```diff
csteam@station1:~/workspace/gpdb$ git diff
diff --git a/src/backend/access/transam/xlog.c b/src/backend/access/transam/xlog.c
index 8466800846b..cece5772096 100644
--- a/src/backend/access/transam/xlog.c
+++ b/src/backend/access/transam/xlog.c
@@ -7819,6 +7819,9 @@ StartupXLOG(void)
         */
        if (needToPromoteCatalog)
        {
+               struct stat fileStat;
+               if (stat("/tmp/inject_fault_before_standby_promotion", &fileStat) >= 0)
+                       elog(PANIC, "fault injection file exists so bailing out.....");
                UpdateCatalogForStandbyPromotion();
        }
```
3. touch `/tmp/inject_fault_before_standby_promotion` file. That fault simulates if system crashes after promoting standby but before updating the catalog.
4. gpactivatestandby
5. Standby comes up fine and works. But catalog represents incorrect state
```sql
postgres=# select * from gp_segment_configuration;
 dbid | content | role | preferred_role | mode | status | port  | hostname | address  |                                    datadir       
                             
------+---------+------+----------------+------+--------+-------+----------+----------+-------------------------------------------------------------------------------
    1 |      -1 | p    | p              | n    | u      | 15432 | station1 | station1 | /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
    2 |       0 | p    | p              | s    | u      | 25432 | station1 | station1 | /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0
    6 |       0 | m    | m              | s    | u      | 25435 | station1 | station1 | /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0
    3 |       1 | p    | p              | s    | u      | 25433 | station1 | station1 | /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1
    5 |       1 | m    | m              | s    | u      | 25436 | station1 | station1 | /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1
    4 |       2 | p    | p              | s    | u      | 25434 | station1 | station1 | /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2
    7 |       2 | m    | m              | s    | u      | 25437 | station1 | station1 | /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2
    8 |      -1 | m    | m              | s    | u      | 16432 | station1 | station1 | /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/standby
(8 rows)
```
Even is dbid=8,  /home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/standby is now new master. Still remains listed as standby and old master remains listed as master. That purely wrong.
6. Also, now as next step try to add new standby as master is running without standby. `gpinistrandby` fails as it says catalog already has standby.
7. More dangerous is `gpinitstandby -r` as it just deletes `/home/csteam/workspace/gpdb/gpAux/gpdemo/datadirs/standby` based on catalog which is data directory of currently running master.

So, old code was using `DB_IN_STANDBY_PROMOTED` state to make sure the catalog update happens even if standby fails at the point the fault was introduced above for experiment based on `DB_IN_STANDBY_PROMOTED`.

So, based on this atleast
1. I am convinced state is definitely not needed for primary and mirror. Only used for master and standby which is only on QD
2. If possible find alternative way to cover for the scenario. I gave some thoughts but currently can't think of way to achieve the same.

**Comment by BaiShaoqi** [comment]
@ashwinstar thanks for your analysis. with help of @paul-guo- , I finally reproduce your scenario step by step 

On latest master, with your patch applied.  I also followed your step. and I am confused by the final result, 
I can successfully connect to standby and create a table , using `psql -d postgre -p 16432 -c 'create table test1(a int)'`

The following is the step I follow your description on gpdb cluster built by latest master with your patch applied.

1  stop qd postgres
 `pg_ctl stop -D /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1`

2 gpactivatestanby to promote standby to master, this command will definately fail with your patch which has a elog(PANIC  
`export PGPORT=16432; gpactivatestandby  -a -d /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/standby`

3 start the master and standby by gpstart 
`gpstart -a`

And the gpdb cluster is strange now, because the following command will both succeed. Do you think the current code in master is already broken somewhere ? or I am misunderstood here.
`psql -d postgres -p 15432 -c 'create table test(a int)'`
`psql -d postgres -p 16432 -c 'create table test1(a int)'`

Also, both the `psql -d postgres -p 15432 -c 'select * from gp_segment_configuration'` and `psql -d postgres -p 16432 -c 'select * from gp_segment_configuration'`shows the same result
```
postgres=# select * from gp_segment_configuration;
 dbid | content | role | preferred_role | mode | status | port  |            hostname             |             address             |                                 datadir
------+---------+------+----------------+------+--------+-------+---------------------------------+---------------------------------+-------------------------------------------------------------------------
    1 |      -1 | p    | p              | n    | u      | 15432 | Shaoqi-Bais-MacBook-Pro-2.local | Shaoqi-Bais-MacBook-Pro-2.local | /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
    2 |       0 | p    | p              | s    | u      | 25432 | Shaoqi-Bais-MacBook-Pro-2.local | Shaoqi-Bais-MacBook-Pro-2.local | /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0
    5 |       0 | m    | m              | s    | u      | 25435 | Shaoqi-Bais-MacBook-Pro-2.local | Shaoqi-Bais-MacBook-Pro-2.local | /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0
    3 |       1 | p    | p              | s    | u      | 25433 | Shaoqi-Bais-MacBook-Pro-2.local | Shaoqi-Bais-MacBook-Pro-2.local | /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1
    6 |       1 | m    | m              | s    | u      | 25436 | Shaoqi-Bais-MacBook-Pro-2.local | Shaoqi-Bais-MacBook-Pro-2.local | /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1
    4 |       2 | p    | p              | s    | u      | 25434 | Shaoqi-Bais-MacBook-Pro-2.local | Shaoqi-Bais-MacBook-Pro-2.local | /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2
    7 |       2 | m    | m              | s    | u      | 25437 | Shaoqi-Bais-MacBook-Pro-2.local | Shaoqi-Bais-MacBook-Pro-2.local | /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2
    8 |      -1 | m    | m              | s    | u      | 16432 | Shaoqi-Bais-MacBook-Pro-2.local | Shaoqi-Bais-MacBook-Pro-2.local | /Users/sbai/work/gpdb/gpAux/gpdemo/datadirs/standby
(8 rows)
```

**Comment by ashwinstar** [comment]
We @BaiShaoqi and I did one more experiment today to gain more confidence on the code. Panic standby during promotion just before renaming recovery.conf file. In old code, for this case standby will get promoted after panic based on `DB_IN_STANDBY_PROMOTED`.
But in new code since that state is no more, for this case standby comes up back as standby due to presence of recovery.conf file. This difference is OKAY from previous behavior as upstream behaves same way. It caused no damage and re-issuing promote to standby promotes it fine. Hence, seems we are all fine to remove those states and loose nothing.

**Pull request merged**
