### PR TITLE
fix: pljava so that it reads absolute directories for jar files

### PR DESCRIPTION
**Pull request by davecramer**
securitypolicy needs to be aware of classpath
added test to pljava

### CODE REVIEW

**Comment by ivannovick** [comment]
@davecramer @mkiyama @litzell if i understand this correctly, now the GUC can be used to set the classpath and any jar files in that class path will be available for use by application developers.  In order to change the class you need a system restart and in order to add new files to the existing class path you need to start a new session. 

Did I get this right?

**Comment by davecramer** [comment]
Everything except changing the GUC. That can be done by a reload

**Comment by ivannovick** [comment]
@davecramer ok cool!!  and the GUC for class path can't be changed in the session level right?  That would be a security problem

**Comment by davecramer** [comment]
Only by a superuser

**Comment by davecramer** [comment]
closed by https://github.com/greenplum-db/gpdb/commit/9703d1ce06a3460006532820b5ceee5c79c50beb

**Pull request closed without merging**
