### PR TITLE
First step to support plpython3u

### PR DESCRIPTION
**Pull request by yydzero**
This is first step to support plpython3u.

With this PR, we could build Greenplum (plpython3u) using python3.

By using 'PYTHON=/path/to/python3 ./configure' one could even build plpython3 under python2 env (assuming 2 versions have been installed in different place)

---------------------- Ignore below thing which make this PR complex ---------------

Next step is make 'make install' works, while it is now blocked by PyGreSQL as 4.0 only support Python 2.x during 'make install'. Below is error details.

There is another email thread to discuss upgrading PyGreSQL (latest 5 supports both Python 2 and 3).  As this won't break python2 support, so plan to submit this PR, and continue when PyGreSQL issue is unblocked.

```
cd /Users/yydzero/work/workspace/pivotal/mygpdb/gpMgmt/bin/src/stream && NO_M64=TRUE gcc stream.c -o stream
. /Users/yydzero/work/build/mymaster/greenplum_path.sh && unset PYTHONHOME && \
	if [ `uname -s` = 'HP-UX' ]; then \
	    cd /Users/yydzero/work/workspace/pivotal/mygpdb/gpMgmt/bin/pythonSrc/PyGreSQL-4.0 && DESTDIR="" CC="gcc" LDFLAGS="-L../../../../gpAux/ext/hpux_ia64/python-2.5.6/lib" python setup.py build; \
	elif [ "" = 'aix7_ppc_64' ]; then \
	    unset PYTHONPATH && cd /Users/yydzero/work/workspace/pivotal/mygpdb/gpMgmt/bin/pythonSrc/PyGreSQL-4.0 && DESTDIR="" CC="gcc" python_64 setup.py build; \
	else \
	    cd /Users/yydzero/work/workspace/pivotal/mygpdb/gpMgmt/bin/pythonSrc/PyGreSQL-4.0 && DESTDIR="" CC="gcc" python setup.py build; \
	fi
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    " newer than 2.2." % version)
Exception: PyGreSQL 4.0 requires a Python 2 version newer than 2.2.
make[2]: *** [pygresql] Error 1
make[2]: *** Waiting for unfinished jobs....
cp /Users/yydzero/work/workspace/pivotal/mygpdb/gpMgmt/bin/src/stream/stream /Users/yydzero/work/workspace/pivotal/mygpdb/gpMgmt/bin/lib/stream
make[1]: *** [install] Error 2
make: *** [install] Error 2
```

### CODE REVIEW

**Comment by kainwen** [comment]
The commit in this PR is not to make code compatible with python3, it is using only python3 syntax.

Python3 is totally a different language than python2. It is not easy to finish the work by just modifying some `print` syntax.

And I do not think the utilities under `gpMgmt` has anything to do with supporting `plpython3u`.

**Comment by pivotal-ning-yu** [comment]
Just FYI, there is a tool `2to3` which is provided by python officially to automatically to convert python2 code to python3 code. For example, by running `2to3` on `src/test/regress/checkinc.py`:

```diff
--- src/test/regress/checkinc.py    (original)
+++ src/test/regress/checkinc.py    (refactored)
@@ -11,9 +11,9 @@
 inc    = p1.communicate()[0].strip();
 pkginc = p2.communicate()[0].strip();

-print "Greenplum INCLUDEDIR:    %s" % inc
-print "Greenplum PKGINCLUDEDIR: %s" % pkginc
-print "Checking includes..."
+print("Greenplum INCLUDEDIR:    %s" % inc)
+print("Greenplum PKGINCLUDEDIR: %s" % pkginc)
+print("Checking includes...")

 include = re.compile('\s*#include\s*["<](\S*)[">]')

@@ -105,10 +105,10 @@

 # For all files, check to see if the list of includes is in the list
 missing = False
-keys = fileset.keys()
+keys = list(fileset.keys())
 keys.sort()
 for f in keys:
-    for i in filter(lambda(x): None == fileset.get(x), fileset[f]):
+    for i in [x for x in fileset[f] if None == fileset.get(x)]:
         # There are a couple reasons an included file might not be listed:

         # 1. It might be a standard include
@@ -127,11 +127,11 @@
         # But if it's not one of those then it's probably a file that we have
         # omitted
         missing = True
-        print '  %-30s includes missing file "%s" ' % (f, i)
+        print('  %-30s includes missing file "%s" ' % (f, i))

 if missing:
-    print "Include files... FAILED"
+    print("Include files... FAILED")
     sys.exit(1)
 else:
-    print "Include files are ok"
+    print("Include files are ok")
     sys.exit(0)
```

It might not always generate the correct code, but at least could save us some time on those obvious parts, such as `print`.

**Comment by yydzero** [comment]
Think gpMgmt stuff makes this PR more confusing. So please ignore it, and it could be ignorable also if we go with the way to build plpython3u under Python 2 env.

**Comment by yydzero** [comment]
for 2), Good to know.

The goal is to make Greenplum Python 2 and Python 3 compatible, which include 2 aspects:
1) Greenplum python scripts like gpstart/gpstop
2) plpython3u

1) is tedious and needs more efforts for testing etc and lower business value than 2). 2) has higher value as many users ask for it.

So first step is able to build plpython3u with python 2 as default python (means gpstart/gpstop use python 2), that is the purpose of this PR.  With this PR, you could compile plpython3u:

```
$ python -V
Python 2.7.10

± |support-python3 ?:5 ✗| → make
gcc -O0 -g3 -ggdb3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -g -ggdb  -Werror=uninitialized  -Wno-error -I. -I. -I/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I../../../src/include -I/usr/local/include/ -I/usr/local/opt/openssl/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2   -c -o plpython.o plpython.c
gcc -O0 -g3 -ggdb3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -g -ggdb  -Werror=uninitialized  -bundle -multiply_defined suppress -o plpython3.so plpython.o -L../../../src/port -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib  -Wl,-dead_strip_dylibs   -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/../.. -L/Users/yydzero/.venv/python3/bin/../lib -lpython3.6 -ldl  -framework CoreFoundation  -bundle_loader ../../../src/backend/postgres

$ ls plpython3.so
plpython3.so
```

Again forget about 'PygreSQL' issue, which make this PR very hard to understand.

Next step is to use python 3 environment to start each postgresql instance (mostly using virtualenv)

**Comment by yydzero** [comment]
after more thought, close this and will try to find a time to make plpython3u works completely.

**Pull request closed without merging**
