### PR TITLE
Add check for tsquery datatype columns

### PR DESCRIPTION
**Pull request by bhuvnesh2703**
Co-Authored-By: David Kimura <dkimura@pivotal.io>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by d** [comment]
1. Huh, the pattern of running `pg_upgrade --check` mid-flight is kind of cute. But it seems to expect the check to fail
1. What's the merit of running _anything_ after the upgrade for `tsquery` type? If I interpret the test correctly, we want to exercise the check that fails the upgrade.
1. Does anybody actually use GIN index on Greenplum 5? `tsquery` and `tsvector` are not terribly useful without GIN

**Comment by Eulerizeit** [comment]
GIN indexes aren't supported on 5.x so no one should be using them.

-- Rob

**Comment by bhuvnesh2703** [comment]
> 1. Huh, the pattern of running pg_upgrade --check mid-flight is kind of cute. But it seems to expect the check to fail

Agree. It's similar to the SQL statement where we expect them to fail due to a bad syntax or SQL which we have banned and error out.

> 2. What's the merit of running anything after the upgrade for tsquery type? If I interpret the test correctly, we want to exercise the check that fails the upgrade.

Just to verify that there were not issues to upgrade after tsquery was altered to text, and after upgrade we are able to convert that to tsquery to get back to the original state. Although the upgrade of text columns is already tested..

> 3. Does anybody actually use GIN index on Greenplum 5? tsquery and tsvector are not terribly useful without GIN

Who knows may be somone has..

**Comment by d** [comment]
> Just to verify that there were not issues to upgrade after tsquery was altered to text, and after upgrade we are able to convert that to tsquery to get back to the original state

1. So this is _just_ testing `ALTER TABLE ... ALTER COLUMN ... TYPE ... USING ...` works
1. It sounds to me we are testing here out of fear, not that it's covering anything that we want to cover

**Comment by bhuvnesh2703** [comment]
>1. So this is just testing ALTER TABLE ... ALTER COLUMN ... TYPE ... USING ... works
>2. It sounds to me we are testing here out of fear, not that it's covering anything that we want to cover

In other words, we are testing that you have something before upgrade, you upgraded it, there was no data issues after upgrade and you were able to query the data in 6 too.

Are you suggesting that we shouldn't test anything on 6 for this case? just the test on 5 is good enough..?

**Comment by d** [comment]
> Are you suggesting that we shouldn't test anything on 6 for this case? just the test on 5 is good enough..?

Yes

**Comment by bhuvnesh2703** [comment]
Rebased. Spoke to Jesse and he is fine with the test, as the intent is to test what we have in 5 has been upgraded successfully and we are able to query the data in 6. The intent is not to test alter on 6.

**Pull request merged**
