### PR TITLE
Remove gppkg packaging of PL/perl.

### PR DESCRIPTION
**Pull request by hlinnaka**
In previous versions of GPDB, we compiled PL/perl against the Perl version
that shipped with RHEL5, and built a separate gpkkg package of plperl,
compiled against the version that ships with RHEL6. If you wanted to use
PL/perl on RHEL6, you had to install the package separately. That's now
obsolet, as we don't support RHEL5 anymore. We can just always build
against the later Perl version.

### CODE REVIEW

**Comment by ivannovick** [comment]
How will we support PL/Perl on RHEL7?   Its a different major version of Perl and should not work with a RHEL6 compiled version

**Comment by hlinnaka** [comment]
On 11/14/2016 09:25 PM, Ivan Novick wrote:
> How will we support PL/Perl on RHEL7?   Its a different major version of Perl and should not work with a RHEL6 compiled version

I don't know. Hopefully not using gpppkg.

Off the top of my head, I would assume that the installer includes both 
versions, and copies the correct one to the lib directory upon installation.

- Heikki

**Comment by hlinnaka** [comment]
@schubert, this has been lingering for a long time. What are the plans for dealing with different Perl versions in RHEL6 and RHEL7? Can we get rid of the gppkg packaging of plperl?

**Comment by ivannovick** [comment]
If we compiled different binaries for RHEL6 and RHEL7 and have different installers this problem would go away.

**Comment by schubert** [comment]
Agreed @ivannovick - given that we already can kick out pl/perl packages for each I see no reason to not just go forward with separate installers for each. I'll chase this up.

**Comment by schubert** [comment]
So in light of driving to separate packages for each platform, I'd say +1 go ahead and nuke this and if we need to grab anything to get working for different platforms we'll deal with that when we get to it.

**Pull request merged**
