### PR TITLE
Adding isolation2 .gitignore

### PR DESCRIPTION
**Pull request by ashwinstar**

### CODE REVIEW

**Comment by hlinnaka** [comment]
The .gitignores look OK, but there seem to be some unrelated changes in the commit.

**Comment by andreasscherbaum** [comment]
What Heikki said, plus the comment on the second .gitignore file.

**Comment by ashwinstar** [comment]
@hlinnaka not really unrelated they are intentional as seems files committed unintentionally earlier and hence cleaning them up, missed to mention the same in PR comment. Please let me know, if looks fine.

**Comment by hlinnaka** [comment]
Ah, gotcha. +1, thanks for cleaning up my mess :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ashwinstar** [comment]
Merged.

**Pull request closed without merging**
