### PR TITLE
docs - add content for greenplum_fdw for gp7

### PR DESCRIPTION
**Pull request by lisakowen**
the first commit adds the greenplum_fdw doc source file from the 6X_STABLE branch.  the second commit includes the changes i made for greenplum 7.

in this PR:
- support 7beta4+ to 7beta4+ for now, so removed the dependencies section (parallel retrieve cursor functionality is built-in in greenplum 7).
- add missing/new content from https://www.postgresql.org/docs/12/postgres-fdw.html. this includes importing a foreign schema and import options, remote execution options, remote query execution environment.
- update postgres links to v12

questions:
- i added a few known issues based on the test output, not sure if i captured them correctly.
- i've noticed some fdw-related PRs in the works, not sure if any of those are applicable to greenplum_fdw.  let me know if they are.

doc review site link (behind vpn): https://docs-staging.vmware.com/en/draft/VMware-Greenplum/gpfdw7/greenplum-database/GUID-ref_guide-modules-greenplum_fdw.html

### CODE REVIEW

**Comment by zhaorui20005** [comment]
> i've noticed some fdw-related PRs in the works, not sure if any of those are applicable to greenplum_fdw. let me know if they are.
They are not related with greenplum_fdw. But these PRs tries to add new features for postgres_fdw and to avoid breaking the behavior for greenplum_fdw.

**Review by zhaorui20005 — APPROVED** [review]
LGTM

**Comment by lisakowen** [comment]
thank you for reviewing, @zhaorui20005 , and for the info about the work on postgres_fdw.  the greenplum postgres_fdw docs (https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/ref_guide-modules-postgres_fdw.html) include a section that identifies greenplum limitations.  please pass along any updates for that section when you complete the work.

**Comment by zhaorui20005** [comment]
> thank you for reviewing, @zhaorui20005 , and for the info about the work on postgres_fdw. the greenplum postgres_fdw docs (https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/ref_guide-modules-postgres_fdw.html) include a section that identifies greenplum limitations. please pass along any updates for that section when you complete the work.

Thanks for the info, our new work involves adding multi_hosts for postgres_fdw foreign table, and it is still under development, we will write some introductions about that after it is finished.

**Pull request merged**
