### PR TITLE
Run clang-tidy against GPOPT translator in CI

### PR DESCRIPTION
**Pull request by d**
Annoyed by having to fix a few lint errors (in #12066) a long time after merging the code, I decided it's high time we ran this continuously in CI

## Post merge TODO
- [ ] re-fly PR pipeline

### CODE REVIEW

**Comment by d** [comment]
For reviewers, if we had this earlier, we would have caught the issue that #12066 fixes before it was merged. See the check in action here https://dev.ci.gpdb.pivotal.io/builds/326881

**Review by chrishajas — APPROVED** [review]
This LGTM! I have seen the clang-tidy job takes between 3-10 minutes. I think I'd actually prefer ICW to run even if clang-tidy fails, mostly because clang-tidy isn't super easy for me to run on Mac so a failure wouldn't necessarily be surprising, but I'd like to get the ICW feedback while I'm fixing clang-tidy failures.

**Comment by d** [comment]
> This LGTM! I have seen the clang-tidy job takes between 3-10 minutes. I think I'd actually prefer ICW to run even if clang-tidy fails, mostly because clang-tidy isn't super easy for me to run on Mac so a failure wouldn't necessarily be surprising, but I'd like to get the ICW feedback while I'm fixing clang-tidy failures.

Have seen the commit where I changed the README? I've made it so you can follow the README step-by-step

**Comment by d** [comment]
Thanks for the review @chrishajas ! Merged

**Pull request merged**
