### PR TITLE
Adds make create-demo-cluster

### PR DESCRIPTION
**Pull request by professor**
Based on feedback from new gpdb developers, we are improving
top level make targets.

https://github.com/greenplum-db/gpdb/issues/2422

### CODE REVIEW

**Comment by professor** [comment]
I like the parallelism between create-demo-cluster and destroy-demo-cluster. 

Other build systems allow tab-auto-completion of targets. Maybe such a thing exists for make?

**Comment by hlinnaka** [comment]
My bash at least seems to have tab-completion of makefile targets. Didn't know it does until I tried it now :-). It seems to be very slow, though, I doubt I'll use it.

**Comment by andreasscherbaum** [comment]
Nice, I like it.

**Comment by ashwinstar** [comment]
Might be good to update concourse scripts like common.bash `make_cluster()` to use new target instead of 
``` 
pushd gpdb_src/gpAux/gpdemo
      su gpadmin -c make cluster
popd
```

**Comment by professor** [comment]
@ashwinstar , you mean like this pull request? https://github.com/greenplum-db/gpdb/pull/2485 =)

I've been waiting 36 hours to be able to open it up.

**Pull request merged**
