### PR TITLE
Adding and calling clear method for  aggstate's member variable when …

### PR DESCRIPTION
**Pull request by karthijrk**
…memory context get deleted

When there is an aggregate with rollup(complex aggregate), we found it is causing seg fault because we still have pointer to memory which was deleted. This change has a function that reset all the memory to NULL when associate memory context get deleted. 

Added test case to tinc and it is in Fisheye's code review

@gcaragea @armenatzoglou @foyzur @entong @xinzweb 
Please take a look when you get chance

### CODE REVIEW

**Comment by hlinnaka** [comment]
@atris, you've been looking at the GROUPING SETS implementation lately. Can you have a look at this, please?

**Comment by atris** [comment]
I will look into this.

**Comment by atris** [comment]
Hi,

While I am reviewing this, could you please add the test case to install check good instead of TINC please? It makes finding and testing much easier.

**Comment by karthijrk** [comment]
Hi, I created a new pull request with ICG test. Here is the link https://github.com/greenplum-db/gpdb/pull/129. Please review over there and I am closing this.

**Pull request closed without merging**
