### PR TITLE
Porting subquery tests into ICG

### PR DESCRIPTION
**Pull request by vraghavan78**
Porting subquery tests from TINC_BFV.

Kind Attention: @hlinnaka @danielgustafsson @xinzweb @oarap @hsyuan

### CODE REVIEW

**Comment by hlinnaka** [comment]
Other than the comment on --disable-orca, LGTM.

I wish this had more comments on what the tests are trying to verify, but I guess asking for that right now would be too much, as you're  just porting existing tests.

**Comment by hsyuan** [comment]
LGTM.

**Comment by vraghavan78** [comment]
@hlinnaka I was trying to test that there is no fallback but did not want explains. But since there is only query let me see what I can do. The comments currently there was a result of me digging through code reviews. I just have so many it cannot scale unfortunately. I have 18000 tests to migrate

**Comment by oarap** [comment]
LGTM

**Comment by vraghavan78** [comment]
Thanks all!

**Pull request closed without merging**
