### PR TITLE
gpcheckcat: Improvements to aoseg vpinfo check

### PR DESCRIPTION
**Pull request by soumyadeep2007**
Please review commits individually.

Dev pipeline with gpcheckat box: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/checkcat_attrib

### CODE REVIEW

**Review by interma — APPROVED** [review]
LGTM, and just know there is such a check in `gpcheckcat`, thanks Deep.

**Review by divyeshddv — COMMENTED** [review]
Changes LGTM, having a behave test would be great here
Adding a behave test should be simple here for a scenario like this one:

    Scenario: gpcheckcat should not print error when vpinfo for RESERVED_SEGNO is of different length
        Given database "vpinfo_reserved_segno" is dropped and recreated
        And the user runs "psql vpinfo_reserved_segno -c "CREATE TABLE co_table(a int, b int) using ao_column; INSERT INTO co_table values (1,1);""
        And the user runs "psql vpinfo_reserved_segno -c "BEGIN; ALTER TABLE co_table ADD COLUMN newcol int; INSERT INTO co_table VALUES (1,1,1); ABORT;""
        Then psql should return a return code of 0
        When the user runs "gpcheckcat miss_attr_db4"
        And gpcheckcat should return a return code of 0
        Then gpcheckcat should not print "[FAIL] inconsistent vpinfo" to stdout

**Comment by ashwinstar** [comment]
Nice! On CI I see this difference in timing. It's helping at least cut down ~3 minutes of runtime

Before
```
Performing test 'aoseg_table'
Total runtime for test 'aoseg_table': 0:00:06.29
```
After
```
Performing test 'aoseg_table'
Total runtime for test 'aoseg_table': 0:00:03.25
```

**Comment by soumyadeep2007** [comment]
>Adding a behave test should be simple here for a scenario like this one:

Added, thanks for the suggestion!

**Review by divyeshddv — COMMENTED** [review]
LGTM, thanks for adding both tests!

**Pull request merged**
