### PR TITLE
Fix btree change tracking

### PR DESCRIPTION
**Pull request by hlinnaka**
This was intentionally left broken by the recent 8.3 merge commits. See discussion at https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/axrbquEo9jI/DJQOwtZcDQAJ.

The first commit in this pull request is the one that fixes the obvious damage of that.

I also noticed that xlogdump didn't compile, after the same merge commit, because it didn't get the memo of the changes to the B-tree split record format. Instead of fixing it directly, replace our xlogdump with the upstream version. The three last commits are related to that: first one brings in the upstream xlogdump code, unchanged from upstream, the second one fixes it to work with Greenplum, and finally there are some improvements to the way SPLIT_R records are logged.

I tested this as suggested by @ashwinstar: I created a test cluster with gpdemo, a test table with a single B-tree index, and inserted some data. I then killed one of the mirror segments, and inserted more data to the table, creating a B-tree split record among others. Then I ran gprecoverseg to bring restart and resynchronize the mirror segment, and killed the primary segment instead. And finally, I ran a query that uses the index. Before these changes, that produced a "page 5 of relation ... not found" error, and after these changes, it worked. I also verified with contrib/changetrackingdump that the blocks modified by the split-record were correctly recorded in the change-tracking log after these changes, but not before.

Some care was needed in testing to make sure that the B-tree split record was the only record that touched a block - otherwise other B-tree records would mask the problem by marking the changes to the blocks. I inserted rows to the table in reverse order, so that the B-tree insertions were always done to the leftmost page, so that whenever a page was split, the (newly-allocated) right page was not touched by subsequent inserts.

### CODE REVIEW

**Comment by ashwinstar** [comment]
:+1: Thank You :sparkles: Looks Great.

**Comment by hlinnaka** [comment]
Thanks, pushed.

**Comment by hlinnaka** [comment]
No, wait, I was confused; this isn't pushed yet

**Comment by hlinnaka** [comment]
Ok, pushed now for real

**Comment by danielgustafsson** [comment]
Thanks a lot for your help on this and sorry for not being clear on having commented out building xlogdump for the same reason as the change tracking, my bad.

**Comment by hlinnaka** [comment]
On 08/02/16 23:36, Daniel Gustafsson wrote:
> Thanks a lot for your help on this and sorry for not being clear on having commented out building xlogdump for the same reason as the change tracking, my bad.

Ah, I didn't actually realize that you commented it out in the Makefile 
as part of this commit. It should be re-enabled now, I guess.

- Heikki

**Comment by danielgustafsson** [comment]
Yes, I can clean that up today.

**Comment by danielgustafsson** [comment]
xlogdump building submitted as #349

**Pull request closed without merging**
