### PR TITLE
Distributed pg_stat_replication views

### PR DESCRIPTION
**Pull request by tvesely**
In order to view the primary segments' replication stream data from
their pg_stat_replication view, we currently need to connect to the
primary segment individually via utility mode. With these new views
powered by a function that obtains each primary segment's replication
stream data by query dispatch, we are now able to view everything from
the master in a regular psql session.

Authors: Taylor Vesely and Jimmy Yih

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tvesely Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=3304)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=3304) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tvesely Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=3304)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=3304) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tvesely Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=3304)!

**Comment by Eulerizeit** [comment]
@hlinnaka @danielgustafsson @davecramer this was the PR I was referring to. 

@tvesely @xinzweb there is a related convo on the gpdb-dev list https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/OuPc20lIdws

**Comment by jimmyyih** [comment]
Thanks Rob for linking the gpdb-dev discussion.  I like Heikki's idea but I'm not sure of the scope of it yet since I have not personally tried out Heikki's prototype yet.

**Comment by hlinnaka** [comment]
Thanks! Yeah, at a quick glance, I think this could take advantage of the EXECUTE ON SEGMENTS feature, so that you' wouldn't need to do the dispatching in the C function.

**Comment by jimmyyih** [comment]
Trying out Heikki's prototype, it was fairly easy to condense this entire PR into just the following SQL:
```
CREATE FUNCTION pg_stat_get_segment_replication() RETURNS SETOF RECORD AS $$
BEGIN
    RETURN QUERY SELECT gp_execution_segment() AS gp_segment_id, * FROM pg_stat_replication;
END;
$$ LANGUAGE plpgsql EXECUTE ON SEGMENTS;

CREATE VIEW pg_stat_replication_segments AS
    SELECT * FROM pg_get_stat_replication() R(gp_segment_id integer, procpid integer, usesysid oid,
                                              usename name, application_name text, client_addr inet,
                                              client_port integer, backend_start timestamptz, state text,
                                              sent_location text, write_location text, flush_location text,
                                              replay_location text, sync_priority integer, sync_state text)
    ORDER BY gp_segment_id;

CREATE VIEW pg_stat_replication_all AS
    SELECT * FROM pg_stat_replication_segments
    UNION
    SELECT gp_execution_segment() AS gp_segment_id, * from pg_stat_replication;
```

**Comment by davecramer** [comment]
+1

**Comment by hlinnaka** [comment]
On 09/16/2017 01:55 AM, Jimmy Yih wrote:
> Trying out Heikki's prototype, it was fairly easy to condense this entire PR into just the following SQL:

Great! I think we have consensus to move ahead with the feature. I'll 
flesh out the prototype and open a PR on Monday. The exact syntax etc. 
probably needs some bikeshedding, but we're still early in the dev cycle 
so there's plenty of time for that even after the initial version is 
committed. But we need it for the 8.4 merge, and you need this for this 
pg_stat_replication view, now.

- Heikki

**Comment by hlinnaka** [comment]
Opened PR for the new syntax: https://github.com/greenplum-db/gpdb/pull/3312

**Comment by hlinnaka** [comment]
I pushed PR #3312, so you could rewrite this using the new syntax now.

**Comment by tvesely** [comment]
Closing this PR, as we can now rewrite this function using the new syntax.

**Pull request closed without merging**
