### PR TITLE
s3ext: implement signature v4

### PR DESCRIPTION
**Pull request by adam8157**
Now s3ext supports all amazon s3 regions.
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

Cc: @lij55 @50wu @yydzero

### CODE REVIEW

**Comment by hlinnaka** [comment]
I'm thoroughly confused on where this project is heading. The argument 
for using the AWS SDK was that you don't need to re-implement the wheel, 
and V4 signature was cited as a prime example of the stuff that you 
won't need to write yourself. And the extension was written in C++ only 
because the SDK needs that. But now we're implementing this stuff 
ourselves anyway?

To be clear, I whole-heartedly agree that it's much better to just write 
these small functions ourselves than import the whole SDK. And that 
means that we can write this extension in C rather than C++, which makes 
it a lot simpler and more robust. But right now, we seem to be choosing 
the worst of both worlds.

Can you please step back, and list the requirements and some sort of a 
roadmap for this extension. I don't mean a long formal document, just a 
few paragraphs on what functionality is needed now and in the near 
future, what performance characteristics we're looking for, and when it 
needs to be ready.

- Heikki

**Comment by adam8157** [comment]
@hlinnaka 

This basic signature v4 feature is targeting to MVP release, so I still
did it by the old way before we get final decision of future development plan.

About the roadmap, we are planning to support: (most of them come from
customer's feedback)
1, list bucket which has more than 1000 files
2, multipart upload(abortable)
3, IAM and token
4, ACL
5, server side encryption
6, compression
7, cloudfront
...

It will be over complex if we implement them all by ourselves, I
suppose. That's why I'm planning to use SDK(which is written by C++)
directly after MVP release.

**Comment by hlinnaka** [comment]
On 08/03/16 09:02, Adam Lee wrote:
> @hlinnaka
>
> This basic signature v4 feature is targeting to MVP release, so I still
> did it by the old way before we get final decision of future development plan.

IMHO we should switch to a more robust design now, as I laid out 
earlier, to avoid duplicating any more effort as we rewrite this later. 
This V4 stuff for example is completely redundant with the work I did 
back then. But I digress..

> About the roadmap, we are planning to support: (most of them come from
> customer's feedback)

Great, thank you!

> 1, list bucket which has more than 1000 files
> 2, multipart upload(abortable)
> 3, IAM and token

These seem straightforward, with or without the SDK.

> 4, ACL

What are you planning to do with ACLs? Attach an ACL to the objects when 
they're uploaded?

> 5, server side encryption

I believe this is transparent to the client.

> 6, compression

There's no compression features in S3 itself, I believe. I presume this 
means compressing the data in the extension before uploading it, and 
decompressing at download.

> 7, cloudfront

I think this is just a matter of using a different URL to access the 
objects, pointing to a cloudfront server instead of AWS.

> ...
>
> It will be over complex if we implement them all by ourselves, I
> suppose. That's why I'm planning to use SDK(which is written by C++)
> directly after MVP release.

Well, the SDK just provides functions for doing the REST calls, you 
still have to write all the logic on when to do the calls and what 
information to include in them yourself. Performing the REST calls with 
libcurl is the easy part.

Thanks for this list, now we have something to evaluate the designs against!

- Heikki

**Comment by adam8157** [comment]
On Tue, Mar 08, 2016 at 08:46:30AM -0800, Heikki Linnakangas wrote:
> ...
>
> > 4, ACL
> 
> What are you planning to do with ACLs? Attach an ACL to the objects when
> they're uploaded?

Yes, or add ACL info later.

> > 5, server side encryption
> 
> I believe this is transparent to the client.
> 
> > 6, compression
> 
> There's no compression features in S3 itself, I believe. I presume this
> means compressing the data in the extension before uploading it, and
> decompressing at download.

Yes.

> > 7, cloudfront
> 
> I think this is just a matter of using a different URL to access the
> objects, pointing to a cloudfront server instead of AWS.
> 
> > ...
> >
> > It will be over complex if we implement them all by ourselves, I
> > suppose. That's why I'm planning to use SDK(which is written by C++)
> > directly after MVP release.
> 
> Well, the SDK just provides functions for doing the REST calls, you
> still have to write all the logic on when to do the calls and what
> information to include in them yourself. Performing the REST calls with
> libcurl is the easy part.

Yes, but I think it will become over complex if we got more and more
feature requests from customers. Also, we did have some problems that
REST API documents haven't mentioned, like list_bucket will list own
directory with size 0.

> Thanks for this list, now we have something to evaluate the designs against!
> 
> - Heikki

Thanks for suggestions, I do appreciate.

Will push this v4 feature for MVP, we could discuss the best design
issue later via mails.

**Pull request closed without merging**
