### PR TITLE
Delete top-level Dockerfile

### PR DESCRIPTION
**Pull request by bradfordboyle**
It doesn't build because --disable-orca is not being passed to configure
and pivotaldata/gpdb-devel doesn't have xerces, on which Orca depends.

It seems this Dockerfile is not used. The Dockerfiles in
./src/tools/docker/*/Dockerfile are more recently maintained.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
While not a fault of this PR, it seems that our Docker support is in dire need of some TLC. We have this file, a section on Docker in the toplevel README, a toplevel README.docker.md, several dockerfiles in src/tools/docker and in there even more README documents.. and Dockerfiles reported as broken seems like a pretty regular thing. I personally don't use Docker at all, but it seems to me that we should be able to do better. As you clearly use it more than me, what is your take on this? Also, does removing this file require any documentation changes to either of these READMEs?

**Comment by d** [comment]
> While not a fault of this PR, it seems that our Docker support is in dire need of some TLC. We have this file, a section on Docker in the toplevel README, a toplevel README.docker.md, several dockerfiles in src/tools/docker and in there even more README documents.. and Dockerfiles reported as broken seems like a pretty regular thing. I personally don't use Docker at all, but it seems to me that we should be able to do better. As you clearly use it more than me, what is your take on this? Also, does removing this file require any documentation changes to either of these READMEs?

If we aren't maintaining those docker files, we should delete all of them (together with mentions of them)

**Comment by Eulerizeit** [comment]
>>If we aren't maintaining those docker files, we should delete all of them (together with mentions of them)
>
>I don't disagree with you @d, but I'd prefer if we maintained them. That being said, I'm not volunteering to do that so I can only extend my wishes here.

From my perspective, we need the ability to allow people who are developing software that is supposed to work on Greenplum to easily be able to test with Greenplum. I think @schubert was trying to figure something out wrt a partners program. Maybe he can chime in.

**Comment by danielgustafsson** [comment]
> You are correct that there are several references to various Docker images throughout the source code. Looking over the places you mentioned, all of the remaining references seem to point at either `src/tools/docker` or the Greenplum Release Engineering maintained `pivotaldata/centos7-build` image. Removing this Dockerfile is the first in a long sequence of steps to clean up the Docker bits in the source code.
> 
> Ultimately, it would be great if we had one open-source image (preferably Ubuntu) that new contributors could use to get started building and testing GPDB. To help prevent code-rot, we should have a CI pipeline that ensures this image can always build OSS GPDB. 

+1

> There may be many special-purpose Pivotal images as well but those don't have to live in this repo.

Yeah, they shouldn't live in this repo.

**Comment by lavjain** [comment]
Hello, I have been maintaining the dockerfile under src/tools/docker and we use it as base image for our PXF development.

**Pull request merged**
