### PR TITLE
gpload add params: FILL MISSING FIELDS

### PR DESCRIPTION
**Pull request by GGPPY**
Gpload add params: FILL MISSING FIELDS, fix unrecognized key: fill_missing_fields.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@GGPPY Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4989)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4989) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@GGPPY Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4989)!

**Comment by adam8157** [comment]
LGTM

@pf-qiu @lij55 do you like this?

**Comment by danielgustafsson** [comment]
@lij55 have you had time to look at this?

**Comment by lij55** [comment]
We will do it soom.

**Comment by danielgustafsson** [comment]
> On 31 Aug 2018, at 12:00, Jasper Li <notifications@github.com> wrote:
> 
> We will do it soom.

Great, thanks!

**Comment by fanfuxiaoran** [comment]
Test cases to test `fill_missing_fields` can work successfully should be added in   gpMgmt/bin/gpload_test/gpload2 .

1)Add test cases in the gpload2.
2)Export PGPORT and MASTER_DATA_DIRECTORY
3) ./TEST.py to run the all test cases of gpload.

**Comment by lij55** [comment]
Hi @GGPPY , Could you please add test cases as @fanfuxiaoran mentioned?
Feel free to ask if you have any questions.

**Comment by schubert** [comment]
@lij55 @pf-qiu @BrianPivotal - close this out if this isn't getting tests? Or merge?

**Comment by pf-qiu** [comment]
We are closing this right now. Feel free to reopen it when tests are ready.

**Pull request closed without merging**
