### PR TITLE
Remove Codegen wholesale from GPDB master 

### PR DESCRIPTION
**Pull request by sambitesh**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Thanks, that's great, one less thing to conflict on, as we start the 9.0 merge!

**Comment by hsyuan** [comment]
Should we squash this before merging? @hlinnaka

**Comment by ashwinstar** [comment]
On Fri, Jan 12, 2018 at 1:47 PM, Haisheng Yuan <notifications@github.com>
wrote:

> Should we squash this before merging? @hlinnaka
> <https://github.com/hlinnaka>
>
I would vote for squashing.

**Comment by ivannovick** [comment]
very nice, much cleaner now

**Comment by d** [comment]
To be clear, the intent is to squash and merge if this PR gets approved. The separate commits was only there to help ourselves (and hopefully reviewers) track our journey.

Jesse (@d) and Melanie (@melanieplageman)

**Comment by danielgustafsson** [comment]
:+1:

**Comment by d** [comment]
Will rebase again to resolve merge conflict

**Comment by d** [comment]
Pushed in fa65063

**Comment by XLPE** [comment]
I  known codegen from old blog.
Why remove codegen wholesale? is it not good, or find a better way?  
@hsyuan  @sambitesh

**Pull request closed without merging**
