### PR TITLE
Retire gp_reject_internal_tcp_connection

### PR DESCRIPTION
**Pull request by soumyadeep2007**
We take a number of steps in cdbconn_doConnectStart() to force QD ->
entry DB QE communication to be over Unix Domain Sockets. It is more
performant over TCP/IP, since it is on the same host. Also, since
4b3360292e4c332933faa554ad2d606f37d82cb7, these connections are
considered as authenticated, bypassing the usual pg_hba authentication
procedure (see internal_client_authentication()).

However, if PGHOST/PGHOSTADDR are set in the postmaster environment,
TCP/IP connections are still used instead of Unix Domain Sockets. It is
actually hard to enforce UDSes here as conninfo_add_defaults() would
sprinkle in the value from the environment, if present. Setting the
value of PGHOST to the socket dir (/tmp by default) is also hard, as the
unix_socket_directories GUC is plural, and we would need to actually
read the postmaster.pid file. Too much trouble and not performant.

Till now, the gp_reject_internal_tcp_connection GUC, on by default,
would force authentication of these internal QD -> entry DB TCP/IP
connections via regular HBA, possibly leading to issues such as:

postgres=> select * from foo, pg_sleep(0);
ERROR:  failed to acquire resources on one or more segments
DETAIL:  fe_sendauth: no password supplied

In this case, the current user is one for which password based
authentication has been set up in
$COORDINATOR_DATA_DIRECTORY/pg_hba.conf

To be more friendly to these situations, mark this GUC as defunct. So,
if any TCP/IP connections are created for QD -> entry DB QE, they will
be considered authenticated by default, and bypass HBA.

### CODE REVIEW

**Review by huansong — APPROVED** [review]
LGTM!

The GUC indeed seems completely useless currently. I guess the original code where we force UNIX socket when rejecting internal tcp connection was lost. As [this old support ticket says](https://community.pivotal.io/s/article/Error-Failed-to-acquire-resources-on-one-or-more-segments-in-Pivotal-Greenplum?language=en_US):
> Ideally, the UNIX domain socket should be used instead of a TCP connection, that is why the default value for the parameter gp_reject_internal_tcp_connection is "on". Due to a change made recently in the code, the UNIX domain is not chosen.

**Comment by soumyadeep2007** [comment]
> LGTM!
> 
> The GUC indeed seems completely useless currently. I guess the original code where we force UNIX socket when rejecting internal tcp connection was lost. As [this old support ticket says](https://community.pivotal.io/s/article/Error-Failed-to-acquire-resources-on-one-or-more-segments-in-Pivotal-Greenplum?language=en_US):
> 
> > Ideally, the UNIX domain socket should be used instead of a TCP connection, that is why the default value for the parameter gp_reject_internal_tcp_connection is "on". Due to a change made recently in the code, the UNIX domain is not chosen.

For the record, we do try to choose UDS over TCP/IP: See how we empty out host and hostaddr in cdbconn_doConnectStart. But that can get overriden later if the env variables are set:
conninfo_add_defaults (fe-connect.c)
    conninfo_array_parse (fe-connect.c)(2 usages)
        PQconnectStartParams (fe-connect.c)(2 usages)
            cdbconn_doConnectStart (cdbconn.c)

**Comment by huansong** [comment]
> we do try to choose UDS over TCP/IP: See how we empty out host and hostaddr in cdbconn_doConnectStart

That happens before authentication right? Would rejecting tcp authentication lead to we re-connect through domain socket in any way? (still thinking why the GUC existed in the first place)

**Comment by soumyadeep2007** [comment]
> That happens before authentication right? Would rejecting tcp authentication lead to we re-connect through domain socket in any way? (still thinking why the GUC existed in the first place)

Yes that happens when we are building connection options, before the server receives the connection and enters the authentication workflow. No re-connection was ever done. The GUC was present because we had a way to force authentication **for QD->entryDB QE connections over UDS (using ident)**, but there was no way to do so **for QD->entryDB QE connections over TCP/IP (using ident)**. So, the GUC was an **indirect** way to enforce that these connections are authenticated. (I don't know why it was deemed important to authenticate these connections, but not other QD->QE connections)

However, that ident auth was removed by https://github.com/greenplum-db/gpdb/commit/4b3360292e4c332933faa554ad2d606f37d82cb7#diff-f7b3586e5625122376793d34b3ca05b199c0d34ef808b3fed72bf8d981a8b3afL571-L589. Assuming that was okay, then this change is okay as well.

**Comment by huansong** [comment]
> The GUC was present because we had a way to force authentication for QD->entryDB QE connections over UDS (using ident), but there was no way to do so for QD->entryDB QE connections over TCP/IP (using ident). So, the GUC was an indirect way to enforce that these connections are authenticated.

I see. I was confused by the statement in the article I pasted earlier. Agreed that the GUC is to enforce auth. Thanks for digging!

**Pull request merged**
