### PR TITLE
CTE Merge: Port CTE planner update from Postgres

### PR DESCRIPTION
**Pull request by hsyuan**
This commit ports the planner changes from the initial CTE commits in Postgres (44d5be0).

With this patch, we now generate InitPlan and CteScan instead of ShareInputScan for CTE queries. But this only works for non-cross slice CTEs. If the CTE definition is referenced by CteScan in different slices, it will error out saying "cross-slice CTE is not supported". 

This partial commit is based on the following commit: https://github.com/hsyuan/postgres/commit/f1751869405f3de174a4106909e5d2beda096dd3
Note: This PR is intended to merge with branch cte_merge.

Signed-off-by: Karthikeyan Rajaraman
Signed-off-by: Shreedhar A Hardikar

### CODE REVIEW

**Comment by fengttt** [comment]
Does this mean some queries that used to work now will error out?

**Comment by hsyuan** [comment]
Yes.

**Comment by fengttt** [comment]
and what is the plan on how to communicate the bad news to customer?

**Comment by fengttt** [comment]
be more  precise, the work is far from complete, and I don't see how this
can be part of master, therefore 5.0.  sounds like should go into its own
branch and merge to 5.1 or 6.0 when it is ready.

**Comment by hsyuan** [comment]
Yes, I agree, that is why in the PR, it is said "Note: This PR is intended
to merge with branch cte_merge."
We are not going to merge this PR into master, because it is far from
complete.

~ ~ ~
Haisheng Yuan

**Comment by fengttt** [comment]
ah, I see.   cool.   thanks.

**Pull request merged**
