### PR TITLE
[CI] Rename check_[[ test_os ]] job to gpmgmt_unit_tests_[[ os_type ]].

### PR DESCRIPTION
**Pull request by higuoxing**
The job check_centos[1] is running gpmgmt's unit test. It's hard to tell the test suite from its name 'check_centos'. This helps rename it to `gpmgmt_unit_tests_[[ os_type ]]`

[1] https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_main/jobs/check_centos/builds/616

Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-rename-check-centos-rocky8

### CODE REVIEW

**Comment by shrakesh** [comment]
prod pipeline: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_main/jobs/check_centos/builds/616
still showing check_centos, to reflect the changes is it required to retrigger after the pr changes merge?

**Comment by higuoxing** [comment]
> prod pipeline: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_main/jobs/check_centos/builds/616 still showing check_centos, to reflect the changes is it required to retrigger after the pr changes merge?

Yeah, the prod pipelines need to re-fly after this PR being merged.

**Review by shrakesh — APPROVED** [review]
LGTM +1

**Review by piyushc01 — APPROVED** [review]
looks good to me

**Comment by shrakesh** [comment]
@higuoxing After approval I realized we can remove gpmgmt, the reasoning behind this is that all the utilities are under gpmgmt so no need to specify explicitly.  
gpmgmt_unit_tests_rocky8 -> unit_tests_rocky8

**Comment by higuoxing** [comment]
> @higuoxing After approval I realized we can remove gpmgmt, the reasoning behind this is that all the utilities are under gpmgmt so no need to specify explicitly. gpmgmt_unit_tests_rocky8 -> unit_tests_rocky8

Ok!

**Comment by shrakesh** [comment]
@higuoxing  cm team has internally done the voting for the name, and we have agreed to have the name "unit_tests_gpmgmt_rocky8" This is also consistent with unit_tests_gporca_rocky8 in icw jobs.

**Comment by higuoxing** [comment]
Prod pipelines are updated correspondingly. Thank you @shrakesh !

**Pull request merged**
