### PR TITLE
Port gpmapreduce tests from TINC to ICW

### PR DESCRIPTION
**Pull request by danielgustafsson**
TINC had a lot of gpmapredue tests which weren't connected to any build or pipeline, resurrect (some of) these by porting over to the mapred suite in ICW.

This is by no means a direct copy of the existing TINC testsuites, but instead a partial port of the tests that made sense to bring over. A lot of the tests were highly overlapping, some completely broken, some were testing functionality ICW already had tests for and others plain uninteresting.

Even though not all the new tests have dynamic content, they are all placed in `mapred/` as `.source` files to keep it simple. There is few enough files that the overhead is negligible and spending more time on gpmapreduce to fix that didn't seem all too exciting. Some of the TINC tests were also rewritten to use different datafiles to minimize the number of datafiles pulled over.

### CODE REVIEW

**Comment by ivannovick** [comment]
cool and thank you for keeping gpmapreduce alive :)

**Comment by hlinnaka** [comment]
typo in commit message: s/gpmapredue/gpmapreduce/. Looks good on a quick glance, but this makes my eyes just glaze over.

**Comment by cjcjameson** [comment]
@larham I see that you found some python typos with https://github.com/greenplum-db/gpdb/pull/1820/files#diff-151b4e494b41865c6dea65e6a3538dbd but the file you are changing in that pull request is deleted as part of this commit: https://github.com/greenplum-db/gpdb/pull/1825/files#diff-151b4e494b41865c6dea65e6a3538dbd

**Comment by danielgustafsson** [comment]
The ICW failure in the pipeline is easily explained by my tired eyes missing some `@abs_srcdir@` replacements in a `.source` file. I will fixup these in the morning once refreshed by coffee.

@ivannovick looking forward to that gpmapreduce sticker.. =)

**Comment by danielgustafsson** [comment]
Pushed to master after a green PR pipeline run, thanks for review!

**Pull request closed without merging**
