### PR TITLE
Enable GPDB to backup/restore with Netbackup client 7.7

### PR DESCRIPTION
**Pull request by khuddlefish**
Pulls netbackup 7.7 libraries from artifactory and adds new job to concourse pipeline

Authors: Karen Huddleston and Chris Hajas

### CODE REVIEW

**Comment by ivannovick** [comment]
CooL!

**Comment by professor** [comment]
This looks good to me

**Comment by Chibin** [comment]
👍

**Comment by dyozie** [comment]
What is the full list of NetBackup versions that we support with 5.0 now?  (See [System Requirements](http://docs-pivotal-gpdb-staging.cfapps.io/500Alpha/admin_guide/managing/backup-veritas.html#topic_lk5_s1z_3p) for what we currently doc.)  I'm assuming we can at least remove all mention of 7.1 since it was previously deprecated.

**Comment by khuddlefish** [comment]
@dyozie Versions of NetBackup prior to 7.7 are all end of support now. I believe we are only supporting 7.7 currently, but will soon support 8.0 as well.

**Comment by dyozie** [comment]
Thanks @khuddlefish - We'll update the GPDB 5.0 docs to make it 7.7-only for now.

**Pull request merged**
