### PR TITLE
gpcloud: support proxy

### PR DESCRIPTION
**Pull request by fanfuxiaoran**
Add an option of proxy in the configuration.
Set proxy for cURL, http, https, socks4, socks4a, socks5 and socks5h are
supported.

Signed-off-by: Xiaoran Wang <xiwang@pivotal.io>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@fanfuxiaoran Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2778)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2778) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@fanfuxiaoran Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2778)!

**Comment by lij55** [comment]
What's the behavior if there is environment http_proxy and https_proxy?

**Comment by adam8157** [comment]
Use env variables if config file doesn't say anything.

BTW, what env variables are supported by cURL: https://github.com/curl/curl/blob/c98e97e9c32b7c55d9002860655bdd7fb5eefd66/lib/url.c#L4963

**Pull request merged**
