### PR TITLE
 LDAP bind credentials are leaked to log on failed login attempt 6X 

### PR DESCRIPTION
**Pull request by CharlieTTXX**
When an LDAP user attempts to login to the GPDB database with bad credentials, the below message is "leaked" to the log. This includes the LDAP server address, bind user (distinguished name), and bind password.
Something like this:

> 2021-11-23 19:43:46.528056 UTC,"ajones2","ajones2",p12654,th-1991804800,"127.0.0.1","53756",2021-11-23 19:43:42 UTC,0,con17,,seg-1,,,,sx1,"LOG","00000","LDAP login failed for user ""uid=ajones2,ou=people,dc=dc1,dc=nebula,dc=local"" on server ""192.168.1.82"": Invalid credentials",,,,,,,0,,"auth.c",2384,
> 
> 2021-11-23 19:43:46.528139 UTC,"ajones2","ajones2",p12654,th-1991804800,"127.0.0.1","53756",2021-11-23 19:43:42 UTC,0,con17,,seg-1,,,,sx1,"FATAL","28000","LDAP authentication failed for user ""ajones2""","Connection matched pg_hba.conf line 92: ""host all ajones2 0.0.0.0/0 ldap ldapserver=192.168.1.82 ldapbasedn=""ou=people,dc=dc1,dc=nebula,dc=local"" ldapbinddn=""cn=admin,dc=dc1,dc=nebula,dc=local"" ldapbindpasswd=""SuperSecretPassword"" ldapsearchattribute=""uid"" """,,,,,,0,,"auth.c",318,

The reason is when we connect database by LDAP, if authentication failed LDAP server will return some user personal privacy like passwd, ID address etc.., so we need to hide these privacy detail to database user and avoid them existing in pg_log file.

In this case, we don't need to add regression test here. Firstly, it is security issue only happed in LDAP, and will not cause other problems in database kernel. Secondly, Adding some regressions cases to test leaking infoomation details is also a hard work.

### CODE REVIEW

**Comment by adam8157** [comment]
This is the 6X version of https://github.com/greenplum-db/gpdb/pull/13831

**Comment by zhaorui20005** [comment]
The error logs returned to psql did not reveal much information.
The log messages are for debug purpose which are stored in pg_log, and the origin infos like user `ldapbindpasswd` 
 are stored in pg_hba.conf under $MASTER_DATA_DIRECTORY. These two files have the same ACL and same owner. 
So I wonder if this pr is really needed? Does this complained from any issue?

**Comment by CharlieTTXX** [comment]
> The error logs returned to psql did not reveal much information. The log messages are for debug purpose which are stored in pg_log, and the origin infos like user `ldapbindpasswd` are stored in pg_hba.conf under $MASTER_DATA_DIRECTORY. These two files have the same ACL and same owner. So I wonder if this pr is really needed? Does this complained from any issue?
The problem is they don't want us to reveal any LDAP user details int pg_log. In order to fix it,  we could just block LDAP infos in psql. The original problem is here (https://www.pivotaltracker.com/story/show/182697899)

**Comment by zhaorui20005** [comment]
> > The error logs returned to psql did not reveal much information. The log messages are for debug purpose which are stored in pg_log, and the origin infos like user `ldapbindpasswd` are stored in pg_hba.conf under $MASTER_DATA_DIRECTORY. These two files have the same ACL and same owner. So I wonder if this pr is really needed? Does this complained from any issue?
> > The problem is they don't want us to reveal any LDAP user details int pg_log. In order to fix it,  we could just block LDAP infos in psql. The original problem is here (https://www.pivotaltracker.com/story/show/182697899)

OK, the modification looks fine to me. I just saw the files under pg_log have more strict access control than pg_hba.conf which contains the origin password. So maybe we could find a way to hide the password in pg_hba.conf in the future.

**Review by zhaorui20005 — APPROVED** [review]

**Pull request merged**
