### PR TITLE
Remove superfluous tests on built-in functions.

### PR DESCRIPTION
**Pull request by hlinnaka**
These tests executed various built-in functions, in different contexts
like in a FROM clause, or in a subquery. We have similar tests for
functions with different attributes in the main test suite's
'qp_functions_in_*' tests. The fact that these are built-in functions
doesn't make any difference to planning, so remove these tests as
redundant.

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
How much time does this save when running the tests?

In general: +1, looks good.

**Comment by vraghavan78** [comment]
Will look at it later today. Please hold of on merging this

**Comment by hlinnaka** [comment]
On 03/02/2017 12:22 PM, Andreas Scherbaum wrote:
> How much time does this save when running the tests?

About 50 seconds, the way they're run in TINC. They would run a lot 
faster, if moved to a single file in the main regression suite, though.

- Heikki

**Comment by hlinnaka** [comment]
On 03/03/2017 12:32 AM, Venkatesh Raghavan wrote:
> vraghavan78 requested changes on this pull request.
>
> -1. We need function property tests for Orca. The team can take a look at it once we ship Alpha. We may be able to re-write this.

 From a planning point of view, what do these tests using built-in 
functions cover, that the bespoken function property tests in 
'qp_functions_in_*' tests (formerly known as FunctionPropertyTestCase.* 
in TINC) don't cover?

- Heikki

**Comment by vraghavan78** [comment]
I cannot answer your question right now because I do not know what it does not cover. 

I know that we added the functional property tests are crucial to catch if Orca is doing the function property derivation. We need time to look at this, we do not have the bandwidth for the next week.  We can leave this PR open for now.

**Comment by ashwinstar** [comment]
@vraghavan78 any traction on this PR ?

**Comment by ascherbaum-pivotal** [comment]
@vraghavan78 What is still open in this PR?

**Comment by hlinnaka** [comment]
This has been sitting in a limbo for long enough. I made an executive decision, and pushed.

@vraghavan78, I'm done here, but if you still think there was something worth salvaging here, please extract those parts as regular tests in the installcheck-world suite.

**Pull request merged**
