### PR TITLE
gpinitstandby: add tablespace test

### PR DESCRIPTION
**Pull request by kalensk**
This is the first in a series of tests to verify tablespaces work with all our utilities. This is also an experiment in learning more about draft PRs!

### CODE REVIEW

**Comment by BaiShaoqi** [comment]
Wow, first step add such test case in behave test. I used to think of this kind of work, but was scared to give up, because gpMgmt is magical to me.

The test runs ok , and the code you add is also ok.

**Comment by ashwinstar** [comment]
Would be always helpful to clearly mention why PR is in draft (or WIP) and what is expected from fellow members on it.

**Comment by jchampio** [comment]
@ashwinstar I think in this case we explicitly have *no* expectations. If anyone would like to review as we go, that's awesome; otherwise we will eventually hit **Ready for review** and open it up to the regular PR process.

**Comment by berlin-ab** [comment]
What's the status of this PR?

**Comment by kalensk** [comment]
It is actively being worked on, and was side-tracked until PR #7287 was implemented. It is currently blocked until https://github.com/greenplum-db/gpdb/pull/7287 is merged.

**Comment by jchampio** [comment]
Now that we have #7287, this approach is changing fairly significantly, so we'll go ahead and close this.

**Pull request closed without merging**
