### PR TITLE
update the typo of commands in the README

### PR DESCRIPTION
**Pull request by ever4Keny**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ever4Keny Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4779)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4779) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by ashwinstar** [comment]
Thank You, merged.

**Comment by pivotal-issuemaster** [comment]
@ever4Keny Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=4779)!

**Comment by ever4Keny** [comment]
Signed @ashwinstar . Sorry I'm new here

**Comment by Eulerizeit** [comment]
No problem.  Thank you for contributing

Rob

**Pull request merged**
