### PR TITLE
Migrating gpdb-docs source into gpdb repo

### PR DESCRIPTION
**Pull request by dyozie**
This PR moves the full end-user docs source into the gpdb docs repo under:

/doc/book
/doc/README.md
/doc/src/dita

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dyozie Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1574)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1574) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dyozie Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1574)!

**Comment by hlinnaka** [comment]
Note that there's a directory calls "docs" in the repo already, so with this, we'll have both "doc" and "docs". That seems confusing. How about "gpdb-docs" ?

**Comment by danielgustafsson** [comment]
Great to see this go in! I do agree with @hlinnaka that we should probably differentiate the directory name a bit more from upstream, gpdb-docs sounds good to me.

**Comment by dyozie** [comment]
Actually, the existing directory is "doc" (see https://github.com/greenplum-db/gpdb/tree/master/doc/src/sgml) - my intention was to add the new source to that existing directory as best I could.

If we do want to differentiate between the existing doc book that's in the repo, I guess it should be `gpdb-doc` at the top-level?

Let me know - I'm fine either way.

**Comment by hlinnaka** [comment]
On 01/18/2017 09:27 PM, David Yozie wrote:
> Actually, the existing directory is "doc" (see
> https://github.com/greenplum-db/gpdb/tree/master/doc/src/sgml) - my
> intention was to add the new source to that existing directory as
> best I could.

Ah, sorry.

> If we do want to differentiate between the existing doc book that's
> in the repo, I guess it should be `gpdb-doc` at the top-level?
>
> Let me know - I'm fine either way.

I think a top-level "gpdb-doc" would be better. All the PostgreSQL docs 
are in doc/src, so there's it wouldn't be too difficult to tell apart 
the upstream docs and GPDB docs either way, but nevertheless a 
completely separate "gpdb-doc" would make it even more clear.

- Heikki

**Comment by dyozie** [comment]
Ok - this PR now puts all the new content under a top-level /gpdb-doc directory.  Feel free to merge it in or let me know if more changes are needed.  Thanks!

**Comment by hlinnaka** [comment]
What's the purpose of gpdb-doc/dita/ref_guide/system_catalogs/system_catalogs.zip? At a quick glance, it seems contain the same .xml files as are in gpdb-doc/dita/ref_guide/system_catalogs/

**Comment by hlinnaka** [comment]
gpdb-doc/dita/ref_guide/config_params/#guc_category-list.xml# seems like a leftover file that should be removed

**Comment by hlinnaka** [comment]
We can tweak all this after commit, of course, but I'd like to get rid of completely pointless files before pushing, and see if we can somehow compress or eliminate other large files, because they will be remembered in the git history forever, and will add bulk to the repository site for anyone who git clone's the repository in the future. Not a huge deal, but it's a now-or-never chance to avoid that baggage.

**Comment by dyozie** [comment]
I agree - will remove this and check for any other obvious baggage.

**Comment by hlinnaka** [comment]
Thanks! A few more large files caught my eye:

* There are a bunch of Microsoft Visio files in gpdb-doc/dita/graphics/source_files. Is that a file format we want to continue using for these? LibreOffice can open them, but it's not a very open format. Also, the files are quite large. I suspect some of them are also not used, as they don't have a corresponding .png file in gpdb-doc/dita/graphics/. Any way to shrink or change the file format to something more compact but still usable? Would be good to give that some thought.

* There are a bunch of screenshots as BMP files in dita/client_tool_guides/*/windows/images/. They would be much smaller as PNG files, without any loss.

**Comment by dyozie** [comment]
Both visio and graffle formats are source file formats for various graphics. They won't necessarily have a corresponding .png or .bmp format filename, because a single visio or graffle file might contain several diagrams.  Right now we don't have any plans to move away from those source formats.

Converted the BMP files to PNG.

**Comment by dyozie** [comment]
@hlinnaka - should I wait for someone else to merge this PR, or is it ok to do that myself at this point?

**Comment by danielgustafsson** [comment]
Personally I think this is ready to go in, albeit rebased and squashed on top of master without the merge commit (as we aren't keeping the past docs repo commit history it's not actually a merge). If you want assistance with pushing the rebase then let us know and we can fix that.

**Comment by hlinnaka** [comment]
On 01/24/2017 01:27 AM, David Yozie wrote:
> @hlinnaka - should I wait for someone else to merge this PR, or is it ok to do that myself at this point?

Feel free to push it yourself. Make sure to rebase once more just before 
pushing, to avoid creating a merge commit. And "git push --dry-run" is 
always a good idea before pushing for real, to see what's actually going 
to happen ;-)

There's a typo in the commit message, addign -> adding.

- Heikki

**Pull request merged**
