### PR TITLE
Fix uninitialized variable passed down in UDP handling

### PR DESCRIPTION
**Pull request by atris**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Why is that needed? The sendAck function doesn't  look at that field.

(This is a rhetorical question; I know you're fixing things that Coverity complains about. That'd be worth mentioning in a comment or the commit message)

**Comment by atris** [comment]
sendAck does look into that field, when DEBUG5 is enabled.

**Comment by hlinnaka** [comment]
Ah, I see! +1 in that case

**Comment by danielgustafsson** [comment]
Agreed, :+1:

**Comment by atris** [comment]
Merged,thanks.

**Comment by yydzero** [comment]
Per GPDB's merge practice, we don't recommend to click the 'Merge' button provided by github UI.  Instead we use command line to cherry pick or ff merge. More info https://github.com/greenplum-db/greenplum-db.github.io/wiki/Merging-Pull-Requests

**Comment by hlinnaka** [comment]
On 04/03/16 01:57, Yandong Yao wrote:
> Per GPDB's merge practice, we don't recommend to click the 'Merge'
> button provided by github UI.  Instead we use command line to cherry
> pick or ff merge. More info
> https://github.com/greenplum-db/greenplum-db.github.io/wiki/Merging-Pull-Requests

He didn't, that commit was a-okay.

- Heikki

**Comment by yydzero** [comment]
Oh, that is great, misunderstood the merge icon.  thanks for pointing out this.

**Pull request merged**
