### PR TITLE
Restore DISTINCT-qualified window aggregates in ORCA

### PR DESCRIPTION
**Pull request by x4m**
Aggregates were disabled by 386d54232, but a lot of fixes were already
applied, so maybe it's time to exercise CI against DQWA.
May be related to #12641.

### CODE REVIEW

**Comment by x4m** [comment]
Can someone with access to Concourse CI tell me please what went wrong there? Just copy the failed tests...

**Comment by kainwen** [comment]
@x4m 
`olap_window_seq` and `statement_mem_for_windowagg` under orca.

**Comment by kainwen** [comment]
Hi, pipeline fails at:

ORCA:  `olap_window_seq`

planner: `statement_mem_for_windowagg`

**Comment by reshke** [comment]
Many thanks kainwen!
Is there any way to look in tests by ourselves? In 7x branch concourse-ci is open for pr author...

**Comment by ashwinstar** [comment]
Seems the PR is not ready as producing wrong result with ORCA (see Chris comment above). Please feel free to re-open or start with fresh version when ready.

**Pull request closed without merging**
