### PR TITLE
improve error message when $GPHOME is not set

### LINKED ISSUE #524: gpinitsystem --help should work without setting $GPHOME
Right now, the gpinitsystem help option (--help) requires $GPHOME to be set in order to print out the help.

The help should be displayed without setting or requiring any environment variables.

### PR DESCRIPTION
**Pull request by andreasscherbaum**
Along the way, fix trailing tabs and split a long error
message into two lines.

This will fix #524

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
New output from a test installation:

ads@diamond:~/postgresql/buildfarm/install/2016-04-07_184846_master$ ./bin/gpinitsystem --help
[FATAL]:-GPHOME environment variable is required to run GPDB but could not be found.
Please set it by sourcing the  greenplum_path.sh  in your GPDB installation directory.
Example: ''. /usr/local/gpdb/greenplum_path.sh''

**Comment by ascherbaum-pivotal** [comment]
Clean Pulse run for this PR:
http://pulse-releng.greenplum.com/browse/projects/ascherbaum-GPDB-master-opt-l1/builds/69306/

**Comment by danielgustafsson** [comment]
LGTM

**Comment by hlinnaka** [comment]
Looks good to me.

**Comment by kuien** [comment]
LGTM

**Comment by ascherbaum-pivotal** [comment]
Pushed
f0ebf87644a91f4139f9f712c70c1e112d8ba69e

**Pull request closed without merging**
