### PR TITLE
Fixing PL/Java regression tests

### PR DESCRIPTION
**Pull request by 0x0FFF**
Fixing PL/Java regression tests to work properly. Old version didn't work at all and even didn't have "expected" results. This patch moves regression testing into "tests" directory with a separate makefile referred from the main one for "test" scenario. Tests passing
Had to change logging as "INFO" is always printed to the client and it contains timestamp, which makes pg_regress crazy because it cannot compare them in a right way

### CODE REVIEW

**Comment by hlinnaka** [comment]
How is this handled in the upstream? We should refrain from moving things around as that will make diffing and merging with upstream harder.

The comment says that this moves tests to "test" directory, but ISTM (without looking at the codebase, just the diff), that it adds new tests, without removing anything from the old location.

**Comment by davecramer** [comment]
Upstream has been completely refactored and AFAICT doesn't use pg_regress.

I think we should figure out how to bring upstream in completely and apply
our patches to it. This will involve adding Maven to the build tools however

Dave Cramer

**Comment by 0x0FFF** [comment]
@hlinnaka @davecramer I agree that moving to upstream is important. But I also think that we have to release some code now, and making release without regression tests running is not a good thing to do.
@hlinnaka This PR moves old regression tests SQL script `pljava.sql` into `tests` directory, splits it into two, adds expected output, corrects makefiles to handle this tests and corrects example class to get the right level of logging as pg_regress cannot parse PL/Java log messages and fails tests because of different timestamps in log lines

**Comment by ascherbaum-pivotal** [comment]
@0x0FFF @davecramer @hlinnaka How do we move forward with this patch? Wait until we completely merged upstream, or merge this in and work on merging upstream in a separate project?

**Comment by 0x0FFF** [comment]
@ascherbaum-pivotal @davecramer 
I think that the proper way of managing PL/Java would be to move it into the separate repository and merge it with upstream. Don't think that fixing the tests on top of the old version really makes much sense

**Comment by ascherbaum-pivotal** [comment]
@0x0FFF Which means this PR can be closed?

**Comment by 0x0FFF** [comment]
Yes, you can close it

On Tue, Mar 22, 2016 at 10:18 AM, Andreas Scherbaum <
notifications@github.com> wrote:

> @0x0FFF <https://github.com/0x0FFF> Which means this PR can be closed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/pull/473#issuecomment-199737011>
>



-- 
Best regards,
Alexey Grishchenko

**Comment by ascherbaum-pivotal** [comment]
Closed.

**Pull request closed without merging**
