### PR TITLE
ADBDEV-3108: Postmaster process may exhaust all signal slots under intensive connections pressure (6X)

### PR DESCRIPTION
**Pull request by RekGRpth**
Greenplum starts several background workers, including `sweeper process`. Such worker doesn't use `BGWORKER_BACKEND_DATABASE_CONNECTION` flag, which means `do_start_bgworker()` only calls `AssignPostmasterChildSlot()` instead of fully-fledged `assign_backendlist_entry()`. This, in turn, means new worker not added to `BackendList`, so `CountChildren()` not counts it.

The problem is `canAcceptConnections()` allows connection of new backend even `PMChildFlags` array is overflowed, which cause postmaster hang.

To reproduce a problem I wrote a small program
https://github.com/RekGRpth/pg_ddos
I run it on demo cluster with the following settings
```
gpconfig -c gp_debug_linger -v 10s -m 10s
```
using the following command
```
DDOS_COUNT=100 ./pg_ddos
```
Postmaster crashed after 10 seconds.

The solution is to port 7X logic. Processing background worker without taking into account `BGWORKER_BACKEND_DATABASE_CONNECTION` flag fixing the problem.

### CODE REVIEW

**Comment by kainwen** [comment]
Thanks a lot @RekGRpth 

> The solution is to port 7X logic. 

Not looking into the code yet, lazy question here: do 7X have or not have the issue?

If master branch also has the issue, we should open PR firstly to master and then backport.

**Comment by RekGRpth** [comment]
> Not looking into the code yet, lazy question here: do 7X have or not have the issue?

7X has not this issue

**Comment by fanfuxiaoran** [comment]
It seems that commit 8a02b3d732cf3ec13e089768bf9ce9abbdcc8a3e in postgres also fixed this issue, and removed some unused code. We may need to discuss if we should remove those unused codes too in gpdb.

**Comment by ashwinstar** [comment]
> It seems that commit [8a02b3d](https://github.com/greenplum-db/gpdb/commit/8a02b3d732cf3ec13e089768bf9ce9abbdcc8a3e) in postgres also fixed this issue, and removed some unused code. We may need to discuss if we should remove those unused codes too in gpdb.

yes we should just align with upstream here, no need to differ from it

**Comment by RekGRpth** [comment]
> It seems that commit [8a02b3d](https://github.com/greenplum-db/gpdb/commit/8a02b3d732cf3ec13e089768bf9ce9abbdcc8a3e) in postgres also fixed this issue, and removed some unused code. We may need to discuss if we should remove those unused codes too in gpdb.

postgres 9.4 has not this commit, only 9.5 and above

**Comment by fanfuxiaoran** [comment]
LGTM!

**Review by fanfuxiaoran — APPROVED** [review]

**Comment by kainwen** [comment]
@RekGRpth Thanks a lot for your contribution.

We are going to register this to internal ship-it meeting, do you need to clean up commits? Like, rebase and squash them into 1 single commit and reword the commit message. Or you have better idea?

**Comment by RekGRpth** [comment]
> @RekGRpth Thanks a lot for your contribution.
> 
> We are going to register this to internal ship-it meeting, do you need to clean up commits? Like, rebase and squash them into 1 single commit and reword the commit message. Or you have better idea?

I don't know about commit message, because I solved one problem (postmaster process may exhaust all signal slots under intensive connections pressure) while in original commit https://github.com/greenplum-db/gpdb/commit/8a02b3d732cf3ec13e089768bf9ce9abbdcc8a3e another problem (allow notifications to bgworkers without database connections) was solved by same changes.

**Comment by kainwen** [comment]
> > @RekGRpth Thanks a lot for your contribution.
> > We are going to register this to internal ship-it meeting, do you need to clean up commits? Like, rebase and squash them into 1 single commit and reword the commit message. Or you have better idea?
> 
> I don't know about commit message, because I solved one problem (postmaster process may exhaust all signal slots under intensive connections pressure) while in original commit [8a02b3d](https://github.com/greenplum-db/gpdb/commit/8a02b3d732cf3ec13e089768bf9ce9abbdcc8a3e) another problem (allow notifications to bgworkers without database connections) was solved by same changes.

OK, then I decide to rebase and commit this to include 2 commits in 6X_STABLE. Thanks!

**Comment by fanfuxiaoran** [comment]
> > @RekGRpth Thanks a lot for your contribution.
> > We are going to register this to internal ship-it meeting, do you need to clean up commits? Like, rebase and squash them into 1 single commit and reword the commit message. Or you have better idea?
> 
> I don't know about commit message, because I solved one problem (postmaster process may exhaust all signal slots under intensive connections pressure) while in original commit [8a02b3d](https://github.com/greenplum-db/gpdb/commit/8a02b3d732cf3ec13e089768bf9ce9abbdcc8a3e) another problem (allow notifications to bgworkers without database connections) was solved by same changes.

This pr's diff is actually the same as the diff of cherry-picking commit  [8a02b3d](https://github.com/greenplum-db/gpdb/commit/8a02b3d732cf3ec13e089768bf9ce9abbdcc8a3e) from gpdb7. The commit 8a02b3d is originally used to solve bgworkers notification issues, but it can fix the problem reported in this pr as well: `Postmaster process may exhaust all signal slots under intensive connections pressure`. 
I agree to rebase and squash the commits in this pr into one.  In my opinion, the commit message should be the same as the commit 8a02b3d.

**Comment by fanfuxiaoran** [comment]
Merged it.  Thanks for your contribution! @RekGRpth

**Pull request merged**
