### PR TITLE
Enable immediate response to SIGTERM when hanging at recv.

### PR DESCRIPTION
**Pull request by eurekaka**
This addresses the problem that we cannot terminate QD by pg_terminate_backend()
if someone issues 'COPY tbl FROM stdin' and then leaves forever.

### CODE REVIEW

**Comment by ivannovick** [comment]
@hlinnaka can you help review this, i think its something you may understand well.  Thx!

**Comment by hlinnaka** [comment]
I don't see anything immediately wrong with this (except that the comment where DoingCommandRead is set seems a bit misleading now), but this scares the hell out of me. We went through big changes to the way signals are handled, and e.g. removed ImmediateInterruptOK altogether, in PostgreSQL 9.5. Those changes were started by a patch that IIRC was similar to this. I'd suggest that you read the threads on pgsql-hackers related to that to get a better understanding of the issue. Only then decide if this really is safe, and if the race conditions this still has are acceptable. (For example, pg_terminate_backend() would still not kill a backend if the signal arrives just before you enter the recv() call.)

**Comment by eurekaka** [comment]
Sure, I would go through the pgsql-hackers threads.
By the way, here is a snippet of function ProcessClientReadInterrupt from PostgreSQL master branch, which is called in secure_read:
```
void
ProcessClientReadInterrupt(bool blocked)
{
	int			save_errno = errno;

	if (DoingCommandRead)
	{
		/* Check for general interrupts that arrived while reading */
		CHECK_FOR_INTERRUPTS();

		/* Process sinval catchup interrupts that happened while reading */
		if (catchupInterruptPending)
			ProcessCatchupInterrupt();

		/* Process sinval catchup interrupts that happened while reading */
		if (notifyInterruptPending)
			ProcessNotifyInterrupt();
	}
	else if (ProcDiePending && blocked)
	{
		/*
		 * We're dying. It's safe (and sane) to handle that now.
		 */
		CHECK_FOR_INTERRUPTS();
	}

	errno = save_errno;
}
```
This means, even when DoingCommandRead is not true, it is still safe to die here in secure_read. The difference between this and my fix is that we are going to probably interrupt the recv() call in the middle, and I think that should be fine. Anyway, I would check the pgsql-hackers threads to see if there is anything missed.

Another thing is, for the race condition example you mentioned,
>Only then decide if this really is safe, and if the race conditions this still has are acceptable. (For example, pg_terminate_backend() would still not kill a backend if the signal arrives just before you enter the recv() call.)

I think it can still kill the backend in this case, since we have set ImmediateInterruptOK to be true before entering recv() call, and in the handler function die() it would call ProcessInterrupts() to exit. Am I missing anything here? thanks

Kenan

**Comment by hlinnaka** [comment]
On 03/12/15 19:12, Kenan Yao wrote:
> Sure, I would go through the pgsql-hackers threads.
> By the way, here is a snippet of function ProcessClientReadInterrupt from PostgreSQL master branch, which is called in secure_read:
> ```
> void
> ProcessClientReadInterrupt(bool blocked)
> {
> 	int			save_errno = errno;
>
> 	if (DoingCommandRead)
> 	{
> 		/* Check for general interrupts that arrived while reading */
> 		CHECK_FOR_INTERRUPTS();
>
> 		/* Process sinval catchup interrupts that happened while reading */
> 		if (catchupInterruptPending)
> 			ProcessCatchupInterrupt();
>
> 		/* Process sinval catchup interrupts that happened while reading */
> 		if (notifyInterruptPending)
> 			ProcessNotifyInterrupt();
> 	}
> 	else if (ProcDiePending && blocked)
> 	{
> 		/*
> 		 * We're dying. It's safe (and sane) to handle that now.
> 		 */
> 		CHECK_FOR_INTERRUPTS();
> 	}
>
> 	errno = save_errno;
> }
> ```
> This means, even when DoingCommandRead is not true, it is still safe to die here in secure_read. The difference between this and my fix is that we are going to probably interrupt the recv() call in the middle, and I think that should be fine. Anyway, I would check the pgsql-hackers threads to see if there is anything missed.

Note that there are tons more signal handling changes in PostgreSQL 
master. ImmediateInterruptOK doesn't exist anymore, the client socket is 
always used in non-blocking mode, and sleeping to wait for client input 
is no longer done inside OpenSSL code. You can't draw much conclusions 
about the safety of the proposed PR by looking at the PostgreSQL master 
code. But do read the pgsql-hackers discussions that lead to those changes.

>> Another thing is, for the race condition example you mentioned,
>> Only then decide if this really is safe, and if the race conditions
>> this still has are acceptable. (For example, pg_terminate_backend()
>> would still not kill a backend if the signal arrives just before
>> you enter the recv() call.)
>
> I think it can still kill the backend in this case, since we have set
> ImmediateInterruptOK to be true before entering recv() call, and in
> the handler function die() it would call ProcessInterrupts() to exit.

Ah yeah, you're right.

- Heikki

**Comment by hlinnaka** [comment]
Nothing seems to be happening to this, so closing.

**Comment by eurekaka** [comment]
Hmm, I was going through the discussion of this issue in pgsql-hackers
list, while then interrupted by a resource queue escalation, so I turned
into overhauling the resource queue locking code until now. Would get back
to this later.

On Thu, Jan 7, 2016 at 4:04 AM, Heikki Linnakangas <notifications@github.com

**Pull request closed without merging**
