### PR TITLE
Fix AO/CO stats restoration.

### PR DESCRIPTION
**Pull request by jimmyyih**
Previously, when performing an incremental restore, tuple counts
on the master for all AO/CO tables would be updated, including
those AO/CO tables that already existed in the target database.
These counts would still be updated regardless of which tables
were restored, or whether any of the restored tables were AO/CO
tables.

AO/CO statistics are now updated only for those AO/CO tables that
are part of the incremental restore.

Authors: Jimmy Yih and James McAtamney

### CODE REVIEW

**Comment by jimmyyih** [comment]
Thanks Heikki, I have added the escaping logic.

**Comment by jmcatamney** [comment]
Pushed into master: https://github.com/greenplum-db/gpdb/commit/f61f24c5c78865b3b7a92cff7ee9af64659a7e30

**Comment by jimmyyih** [comment]
Reopen to fix unit tests.

**Comment by jimmyyih** [comment]
Unit tests fixed:
https://github.com/greenplum-db/gpdb/commit/de6b68f737de627c41850d766e023cb734c6e988

**Pull request closed without merging**
