### PR TITLE
6X only: Raise error when affecting tuple moved into another segment

### PR DESCRIPTION
**Pull request by asimrp**
Split update (updating a distribution key column) in Greenplum is
implemented by delete followed by insert.  This is similar to an
update to partition key column in upstream PostgreSQL, which is
handled by commit f16241bef7cc.  This patch cherry-picks relevant
parts of that commit.  The idea is to distinguish a tuple deleted as
part of split update from a regular deleted tuple.  Concurrent
attempts to update or delete such a tuple need to be aware that the
update chain for this tuple cannot be traced because the updated tuple
no longer resides in the same heap table (it's moved to another
segment).

Main difference between the upstream commit and this patch is the
tuple header change is not recorded in WAL.  Mirrors see this as
regular heap delete during replay and crash recovery would also replay
it as regular heap delete.  That is, the tuple header change is
treated like a hint bit change.  Tuple masking logic used by replica
check and WAL consistency checks is updated to mask the tuple header
change.  We think this is OK in Greenplum 6 because hot standby does
not work here.

Note that moving tuples from partition to another partition is
prohibited in Greenplum 6X.  That's why we can repurpose the trick from
upstream for split-update.

Co-authored-by: Zhenghua Lyu <kainwen@gmail.com>

### CODE REVIEW

**Comment by asimrp** [comment]
Discussion: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/kET4SJ1AHBA/gauiHO2WAwAJ

**Comment by hlinnaka** [comment]
> Note that moving tuples from partition to another partition is
prohibited in Greenplum 6X. That's why we can repurpose the trick from
upstream for split-update.

As we merge with PostgreSQL v12, we'll get the upstream partitioning code, which does allow updating tuples from one partition to another. I believe that's OK, and we can continue to use the same magic ctid for tuples that have been moved across partitions and for tuples moved across segments. Or do you see a problem with that? If we want to distinguish between the two cases -  for error messages maybe - we could have a separate magic ctid value for tuples moved across segments.

Either way, the ctid only matters on tuples that have an update in progress, so there's no backwards-compatibility problem even if we change the values later. So we don't need to have an answer to that right now.

**Comment by xiong-gang** [comment]
Looks good to me, thanks.

**Comment by schubert** [comment]
Hold on this. We may not want to merge this - even if this fixes wrong results, if this creates incompatible  data files and eliminates the ability to downgrade which isn't good. Needs further discussion.

**Comment by asimrp** [comment]
I went through all the uses of `HeapTupleHeaderIndicatesMovedPartitions`, just to be sure, and I'm convinced that this patch is not going to break backwards compatibility.  Verified that using a basic test - perform split update using this patch and then binary swap to 6X_STABLE and select from the updated table.

Regarding the problem on master, when we get the commit as part of ongoing merge, we need not distinguish between movement of tuples across partitions and across segments.  If we have to, I agree that a new magic value can be used by choosing a different value for offset number.

**Comment by asimrp** [comment]
@schubert there is [consensus](https://groups.google.com/a/greenplum.org/d/topic/gpdb-dev/kET4SJ1AHBA/discussion) that backward compatibility is not affected by this PR.  Would you like to give a go ahead to merging this PR?

**Comment by asimrp** [comment]
Hmm, PR pipeline shows a tripped assertion.
```
(Thread-40) Host: 695c4359-3f8a-40bc-67d6-fd11704ab8c3, Port: 6002, Database: regression
Primary Data Directory Location: /tmp/build/d62a0504/gpdb_src/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0
Mirror Data Directory Location: /tmp/build/d62a0504/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0
returncode: (2), cmd: (PGOPTIONS='-c gp_session_role=utility' psql -h 695c4359-3f8a-40bc-67d6-fd11704ab8c3 -p 6002 -c "select * from gp_replica_check('/tmp/build/d62a0504/gpdb_src/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0', '/tmp/build/d62a0504/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0', 'heap, sequence, ao')" regression), output: (FATAL:  Unexpected internal error (heapam.c:9384)
DETAIL:  FailedAssertion("!(((bool) (((const void*)(&(page_htup)->t_ctid) != ((void *)0)) && ((&(page_htup)->t_ctid)->ip_posid != 0))))", File: "heapam.c", Line: 9384)
HINT:  Process 120645 will wait for gp_debug_linger=120 seconds before termination
```

**Comment by asimrp** [comment]
It was the assertion inside `heap_mask()`.  Easy to fix - perform the masking of ctid for moved partitions case only if the ctid is valid.  The PR pipeline should be happy now.

**Comment by asimrp** [comment]
PR pipeline indicates `create_memory_accounting_tables` isolation2 test failed due to this error on all segments: 
```
dx4,x27363,sx1,"ERROR","XX000","relation 204837 deleted while still in use (relcache.c:2304)",,,,,,"CREATE TABLE lineitem
```
On the segment, the OID 204837 that was assigned to `lineitem` table, was also assigned to `t1` table that was created by the last command of the previous test `upgrade_numsegments`.  And this test executes `create temp table t1 ...` in utility mode on segments.  See the psql output from seg0 in utility mode:
```SQL
isolation2test=# set gp_select_invisible to on;
SET
isolation2test=# select xmin,xmax,* from pg_type where typrelid = 204837;
 xmin  | xmax  | typname  | typnamespace | typowner | typlen | typbyval | typtype | typcategory | typispreferred | typisdefined | typdelim | typrelid | typelem | typarray | typinput  | typoutput  | typreceive
  |   typsend   | typmodin | typmodout | typanalyze | typalign | typstorage | typnotnull | typbasetype | typtypmod | typndims | typcollation | typdefaultbin | typdefault | typacl 
-------+-------+----------+--------------+----------+--------+----------+---------+-------------+----------------+--------------+----------+----------+---------+----------+-----------+------------+-----------
--+-------------+----------+-----------+------------+----------+------------+------------+-------------+-----------+----------+--------------+---------------+------------+--------
 27986 | 27987 | t1       |       204835 |       10 |     -1 | f        | c       | C           | f              | t            | ,        |   204837 |       0 |   204838 | record_in | record_out | record_rec
v | record_send | -        | -         | -          | d        | x          | f          |           0 |        -1 |        0 |            0 |               |            | 
 27988 |     0 | lineitem |         2200 |       10 |     -1 | f        | c       | C           | f              | t            | ,        |   204837 |       0 |   204838 | record_in | record_out | record_rec
v | record_send | -        | -         | -          | d        | x          | f          |           0 |        -1 |        0 |            0 |               |            | 
(2 rows)
```
There were no invisible tuples in `pg_class` and `pg_attribute`.

The prime suspect is OID assignment logic.  Does utility mode OID assignment cause the QD's choice of OID to go wrong sometimes?  I'm trying to reproduce this with a smaller set of commands in my local environment.

**Comment by asimrp** [comment]
The isolation2 failure is unrelated to the change, it can happen on 6X_STABLE pipeline as well.  Let's track it elsewhere.

I've merge this PR as 64b8664b193f136e3437088d7547927358efac67

**Pull request closed without merging**
