### PR TITLE
Use gp_command_count for gpfdist command ID

### LINKED ISSUE #10976: gpfdist shouldn't return 0 rows on the second `select` on exteranl table after `prepare`.
### Step to reproduce the behavior

```sql
shardikar=# set plan_cache_mode = 'force_generic_plan';
SET
Time: 11.593 ms
shardikar=# set optimizer = off;
SET
Time: 0.604 ms
shardikar=#
shardikar=# prepare foo(int) as select $1 from output_ext;
PREPARE
Time: 1.003 ms
shardikar=# begin;
BEGIN
Time: 0.164 ms
shardikar=# execute foo(1);
 ?column?
----------
        1
(1 row)

Time: 110.520 ms
shardikar=# execute foo(1);
 ?column?
----------
(0 rows)

Time: 6.548 ms
shardikar=# explain execute foo(1);
                                      QUERY PLAN
--------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..11000.00 rows=1000000 width=0)
   ->  External Scan on output_ext  (cost=0.00..11000.00 rows=333334 width=0)
 Optimizer: Postgres query optimizer
(3 rows)

Time: 0.979 ms
```

It shouldn't return 0 rows on the second run of foo.

### PR DESCRIPTION
**Pull request by beeender**
gpfdist intended to use `commnd-id`+`transaction-id`+`scan-number` to
mark a gpfdist session. The scan-number was a process-static var which
would be increased when creating the plan. The `command-id` was set to
`QEDtxContextInfo.curcid` which is for debugging purpose only and NOT
changed as expected.
This approach has a problem with PREPARE/EXECUTE. When executing a
prepared statement, the gpdb may use the cached plan to execute. In this
case, gpfdist thinks the query is for the same gpfdist session since the
scan-number doesn't change (no new plan is created). Thus, gpfdist won't
reset the file offset and will give the wrong results. This is a 100%
reproducible issue on gpdb5 & gpdb6. For gpdb7, due to the cost
calculation change in 93abe741cd6 , the problem still existed but not
always happened.

- In the gpfdist, `X-GP-SN` was commented as session id (see comments:
  X-GP-SN - session ID), but it was set with scan-number in the gpdb.
  The real `X-GP-SESSION-ID` had never been used in the code. To
  maintain the compatibility, keep the gpfdist as it is and fix the
  comment.
- The `X-GP-CID` won't use the debug purpose `QEDtxContextInfo.curcid`
  anymore, `gp_command_count` is used as a better alternative -- it
  changes for every query including the `EXECUTE` statement.
- Added some cases to gpfdist. Those cases may not fail on gpdb7 even
  without this commit due to the cost calculation change. But they would
  fail on gpdb5 & gpdb6.

The problem was found with fix de9b0e2 and 78024fb (#10971 & #10984). When
backport this commit, those changes can be removed as well.

### CODE REVIEW

**Comment by hardikar** [comment]
Thanks for digging into this and coming up with a fix. I'm curious about one, what happens if there are two external scans within the same query, such as in the case of a self-join of an external table? Wouldn't you need a separate scan-id for each of them?

```
CREATE READABLE EXTERNAL TABLE output_ext (
relid integer,
exists_missing varchar(200),
segids varchar(200)
)
LOCATION ('gpfdist://$host:$ip/output.dat')
FORMAT 'TEXT' (DELIMITER '|')
;

SELECT * from output_ext e1, output_ext e2 where e1.relid = e1.relid;
```

**Comment by pf-qiu** [comment]
Do we need to remove "X-GP-SN" references in gpfdist.c also?
What happens when old gpfdist serving new gpdb and vice versa?

**Comment by beeender** [comment]
@hardikar You are absolutely right. The scan number should be kept. I reverted the changes and use the initial idea of `gp_command_count`. And some more tests are added.

@pf-qiu I modified the comments in the gpfdist and keep the `X-GP-SESSION` as it is -- it may still be useful for our debugging. So, still, no code changes on the gpfdist side.

The PR message has been updated accordingly.

**Review by lij55 — APPROVED** [review]
Great! thanks!

**Review by hardikar — APPROVED** [review]
LGTM! Thanks for the fix!

**Pull request merged**
