### PR TITLE
Add a new WaitEventIPC for the dtx recovery progress.

### PR DESCRIPTION
**Pull request by paul-guo-**
Remove a related FIXME.

### CODE REVIEW

**Review by asimrp — APPROVED** [review]
With this PR, the dtx recovery background process's wait reason will be shown as "DtxRecovery" in pg_stat_activity view, while the process is waiting.  :+1:

**Comment by maksm90** [comment]
Hi @asimrp , @paul-guo- ! Thanks for the patch.

>  the dtx recovery background process's wait reason will be shown as "DtxRecovery" in pg_stat_activity view, while the process is waiting

Is this type of event (as well as other GPDB-specific ones) reflected anywhere in documentation?

**Comment by paul-guo-** [comment]
> Hi @asimrp , @paul-guo- ! Thanks for the patch.
> 
> > the dtx recovery background process's wait reason will be shown as "DtxRecovery" in pg_stat_activity view, while the process is waiting
> 
> Is this type of event (as well as other GPDB-specific ones) reflected anywhere in documentation?

Checked upstream code, those are documented in doc/src/sgml/monitoring.sgml, but in Greenplum the file is gone for unknown reason. Maybe the guys who worked on PG12 merge could answer this question.

**Comment by asimrp** [comment]
> Is this type of event (as well as other GPDB-specific ones) reflected anywhere in documentation?

The wait_event_type is a new addition in Greenplum 7 as compared to Greenplum 6.  The documentation will be updated in due course.  The answer to your question, @maksm90, is therefore, yes.  Am I right, @dyozie @lisakowen?

**Pull request merged**
