### PR TITLE
LDAP bind credentials are leaked to log on failed login attempt

### PR DESCRIPTION
**Pull request by CharlieTTXX**
When an LDAP user attempts to login to the GPDB database with bad credentials, the below message is "leaked" to the log.  This includes the LDAP server address, bind user (distinguished name), and bind password. 
Something like this:

> 2021-11-23 19:43:46.528056 UTC,"ajones2","ajones2",p12654,th-1991804800,"127.0.0.1","53756",2021-11-23 19:43:42 UTC,0,con17,,seg-1,,,,sx1,"LOG","00000","LDAP login failed for user ""uid=ajones2,ou=people,dc=dc1,dc=nebula,dc=local"" on server ""192.168.1.82"": Invalid credentials",,,,,,,0,,"auth.c",2384,
> 
> 2021-11-23 19:43:46.528139 UTC,"ajones2","ajones2",p12654,th-1991804800,"127.0.0.1","53756",2021-11-23 19:43:42 UTC,0,con17,,seg-1,,,,sx1,"FATAL","28000","LDAP authentication failed for user ""ajones2""","Connection matched pg_hba.conf line 92: ""host     all     ajones2 0.0.0.0/0       ldap ldapserver=192.168.1.82 ldapbasedn=""ou=people,dc=dc1,dc=nebula,dc=local"" ldapbinddn=""cn=admin,dc=dc1,dc=nebula,dc=local"" ldapbindpasswd=""SuperSecretPassword"" ldapsearchattribute=""uid"" """,,,,,,0,,"auth.c",318, 

The reason is when we connect database by LDAP, if authentication failed LDAP server will return some user personal privacy like passwd, ID address etc.., so we need to hide these privacy detail to database user and avoid them existing in pg_log file.

In this case, we don't need to add regression test here. Firstly, it is security issue only happed in LDAP, and will not cause other problems in database kernel. Secondly, Adding some regressions cases to test leaking infoomation details is also a hard work.

### CODE REVIEW

**Review by adam8157 — APPROVED** [review]
Perhaps `auth_method` could be checked before `psprintf()`, not a big deal.

**Comment by CharlieTTXX** [comment]
> Perhaps `auth_method` could be checked before `psprintf()`, not a big deal.

**Comment by CharlieTTXX** [comment]
> Perhaps `auth_method` could be checked before `psprintf()`, not a big deal.
Good suggestion, but I think It's the good way for code readability

**Comment by khuddlefish** [comment]
Do we have any concerns about missing valuable debugging information by dropping the log here? I agree that not printing passwords is good. Are there cases we might worry about where a user has an issue that could be diagnosed with the log, but the log information they need to solve their problem is missing?

**Comment by CharlieTTXX** [comment]
> Do we have any concerns about missing valuable debugging information by dropping the log here? I agree that not printing passwords is good. Are there cases we might worry about where a user has an issue that could be diagnosed with the log, but the log information they need to solve their problem is missing?
Thanks for your comments. Actually upstream guys have discussed your concerns, they want  add permission check for pg_log, in other words, people who have LDAP permission could check pg_log when LDAP connect failed. So maybe we don't need to show anything in pg_log, if LADP failed people who have permission could check LDAP server for more details, and we also have LDAP address in pg_hba.conf.

**Pull request merged**
