### PR TITLE
Vagrantfile and files for Ubuntu

### PR DESCRIPTION
**Pull request by Robot144Robotovitz**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Robot144Robotovitz Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10939)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10939) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gfphoenix78** [comment]
@Robot144Robotovitz Thank you for your PR, please sign the Contributor License Agreement first.

**Comment by pivotal-issuemaster** [comment]
@Robot144Robotovitz Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10939)!

**Comment by ashwinstar** [comment]
We had files in past for Vagrant and were later deleted from repo, simple because if there is no way to keep them in sync with code changes and mechanism to go out of sync, no point having in repo the code. If that situation can be improved there would be interest else I doubt.

**Comment by Robot144Robotovitz** [comment]
Vagrant files for CentOS and Debian are in master:
https://github.com/greenplum-db/gpdb/tree/master/src/tools/vagrant
Since Ubuntu is also a widely-used distribution, I decided to add it too.
It might help someone with a quick start.

**Comment by ashwinstar** [comment]
Commit via c1552c1b741471edd25628352138976e19af4c0c

**Pull request closed without merging**
