### PR TITLE
Update branding on sample config

### PR DESCRIPTION
**Pull request by ivannovick**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ivannovick Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2821)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2821) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by ivannovick** [comment]
@danielgustafsson can you help review please?

**Comment by pivotal-issuemaster** [comment]
@ivannovick Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=2821)!

**Comment by danielgustafsson** [comment]
Pushed to master with the commit amended to have the same fix in `gp_init_config` in Tinc.

**Pull request closed without merging**
