### PR TITLE
[6X] backport ssl cert reload patch

### PR DESCRIPTION
**Pull request by shalamovivan**
backport patch from https://github.com/postgres/postgres/commit/de41869b64d57160f58852eab20a27f248188135

### CODE REVIEW

**Comment by ashwinstar** [comment]
I am guessing you are able to look at the travis failures. The concourse CI failed with (blindly pasting, I didn't check the reason for the same.

```
--- \/tmp\/build\/d62a0504\/gpdb_src\/src\/test\/regress\/expected\/gp_connections\.out	2022-02-10 13:29:56.554943527 +0000
+++ \/tmp\/build\/d62a0504\/gpdb_src\/src\/test\/regress\/results\/gp_connections\.out	2022-02-10 13:29:56.558943856 +0000
@@ -29,10 +29,9 @@
 -- below query will fork an entry db on master, it will connect via [local],
 -- but as it is an internal connection it should still be allowed
 select * from t1_of_user_disallowed_via_local, pg_sleep(0);
- c1 | pg_sleep 
-----+----------
-(0 rows)
-
+ERROR:  failed to acquire resources on one or more segments
+DETAIL:  FATAL:  pg_hba.conf rejects connection for host "[local]", user "user_disallowed_via_local", database "postgres", SSL off
+ (entry db 10.254.1.58:6000)
 -- cleanup settings if any
 \! sed -i '/user_disallowed_via_local/d' $MASTER_DATA_DIRECTORY/pg_hba.conf;
 --

```

**Comment by lij55** [comment]
I have some concern about whether the GUC name and the structure of Port changing would break ABI and compabitility.

**Comment by reshke** [comment]
hi Jasper Li! thanks for review!
As far as i understands GUC name should break ABI, because it was not changes, isn`t it? the only changes around guc is enum flag, indicating in which situation (sighup, restart) these variables can be changed. Am i wrong?

**Comment by zhaorui20005** [comment]
The indent of gpdb is TAB, try to use TAB instead of "    " so that the real changed lines are more clear.

**Comment by zhaorui20005** [comment]
Thank you for your contribution. There are some conflicts on the two files: `src/backend/libpq/auth.c` and `src/test/ssl/ServerSetup.pm` and other unrelated ident changes.  Would you please fix that and rebase on the 6X_STABLE branch so that we could start further reviews. @shalamovivan shalamovivan

**Comment by ashwinstar** [comment]
@shalamovivan please can you rebase the PR to the latest 6X_STABLE, resolve conflicts reported in a couple of files then we can take this to the finish line. Thank You!

**Comment by shalamovivan** [comment]
OK. I will do it when I have more time.  суббота, 05 ноября 2022г., 00:50 +05:00 от Ashwin Agrawal  ***@***.*** :

***@***.*** please can you rebase the PR to the latest 6X_STABLE, resolve conflicts reported in a couple of files then we can take this to the finish line. Thank You!

**Comment by ashwinstar** [comment]
Tried to squash commits within the PR, those also have conflicts (not straightforward to resolve at quick glance). Resolving the conflicts with refresh to 6X_STABLE should be easy task. Given the code is not in ready shape and not quick work to get it to that state. Closing the PR for now, when ready with all conflicts resolved and in working condition with latest 6X_STABLE can take it forward.

**Pull request closed without merging**
