### PR TITLE
Merge pg_hint_plan source tree into GPDB

### PR DESCRIPTION
**Pull request by dgkimura**
The purpose for merging pg_hint_plan into GPDB branch is to streamline ORCA
plan hints development.

ORCA usage of pg_hint_plan is more coupled to the extension than PLANNER. 
Updating pg_hint_plan code won't coerce ORCA to generate a specific plan. That's 
because ORCA only uses pg_hint_plan to parse a query tree into hints that are
passed into ORCA optimizer. That suggests that ORCA hint tests should run in
GPDB branch since that's where the code is that affects them.

The added benefit of merging into GPDB branch is that most developers will not 
have to manage synchronizing GPDB and pg_hint_plan versions. And that also
simplifies CI testing around plan hints in ORCA.

This merge commit includes all pg_hint_plan commits until dfb7d34 (PG12)

Following steps were used to create this merge commit under gpcontrib:

    $ git remote add pg_hint_plan_remote git@github.com:ossc-db/pg_hint_plan.git
    $ git fetch pg_hint_plan_remote
    $ git subtree add -P gpcontrib/pg_hint_plan pg_hint_plan_remote PG12

No other changes are included in this pull-request.

### CODE REVIEW

**Comment by chrishajas** [comment]
To clarify, this doesn't include any changes that may be needed to get this working with the GPDB planner right? This is just the initial commit with the existing code?

**Comment by dgkimura** [comment]
On Tue, Jan 9, 2024 at 2:37 PM Chris Hajas wrote:
> To clarify, this doesn't include any changes that may be needed to get this working with the GPDB planner right? This is just the initial commit with the existing code?

Correct.  I was afraid I'd be making those commits unreviewable if I included them here.  So, I had planned to open separate a PR   after the initial code gets merged.

**Comment by dgkimura** [comment]
@ashwinstar - do you have any thoughts or concerns about adding pg_hint_plan in GPDB branch?  My motive is that this feels easier for ORCA development on plan hints than having to maintain a separate repository.

**Review by chrishajas — APPROVED** [review]
Looks good! Excited to get this in

**Review by gpopt — APPROVED** [review]
+1

**Pull request merged**
