### PR TITLE
Adding implicit cast implementation in GPDB 5x

### PR DESCRIPTION
**Pull request by ivannovick**
Implicit casting feature was removed from GPDB 5x
during the postgres merge. This commit allows to users
the ability to re-enable this feature for backward
compatibility when upgrading from 4.3.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Rather than having a .sql file in the distribution itself, I'd rather see these commands in the documentation. The documentation page should instruct to:

1. Modify the queries to work without the casts. It is very likely that the casts are hiding application bugs, in which case adding explicit casts to the query is the proper response.

2. If a query cannot be modified, figure out which cast it needs, and only re-create that particular cast. Not all of them.

**Comment by d** [comment]
-1

1. This resurrects the worst feature of Postgres 8.2: (almost) everything is implicitly coercible to text
1. The user should *not* be adding anything to `pg_catalog`, because
    1. `pg_catalog` is special during name lookup: it's always consulted, regardless of whether it is part of `search_path`
    1. `pg_dump`, `gp_dump`, `gpsd`, and `minirepro` will *not* dump objects (casts and functions) from `pg_catalog`, which means that a user will _think_ they are providing a repro when a query is working funny, but other members of the community will have great difficulty reproducing the issue

**Comment by dhanashreek89** [comment]
This work around has a known side effect, it breaks the concatenation operator:
```
CREATE TABLE test AS SELECT generate_series(1,2) as a;

SELECT a, 'value = ' || a FROM test;
ERROR:  operator is not unique: unknown || integer
LINE 1: SELECT a, 'value = ' || a FROM test;
                             ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```

which can be fixed by adding an explicit cast: `SELECT a, 'value = ' || a::text FROM test;`

Instead of adding these implicit casts in the code , It would be better if it's either documented as a work-around (as in here: http://engineering.pivotal.io/post/gpdb_merge_with_postgresql_8.3/) or let the application handle it by creating only the required casts.

**Comment by lij55** [comment]
Another work around is to overload the operator that is used by old SQL.  However, any workaround has its side effect and We had a long discussion about this topic with China PDE team. 
It seems we have to provide concrete work around for concrete issue of customer. 
I can't find a perfect solution about this issue except rewriting old SQL.

**Comment by Eulerizeit** [comment]
@oakbarrett this is something that probably needs to be included in backup and restore if it isn't already. Regardless of how we chose to implement it.

**Comment by khuddlefish** [comment]
@Eulerizeit We do not back up casts in the pg_catalog schema because we assume they are not created by the user. We don't have any other good way to determine if they belong to the user or system. I don't think we should back these casts up.

**Comment by hlinnaka** [comment]
On 02/03/18 03:33, Karen Huddleston wrote:
> @Eulerizeit We do not back up casts in the pg_catalog schema because
> we assume they are not created by the user.

Casts do not belong to any particular schema.

> We don't have any other good way to determine if they belong to the
> user or system. I don't think we should back these casts up. >

Would be weird not to, IMHO. pg_dump dumps all casts with OID >= 
FirstNormalObjectId, unless they belong to an extension. Same rule it 
uses for other objects that don't belong to any particular schema.

- Heikki

**Comment by khuddlefish** [comment]
@hlinnaka I was thinking we looked at the functions to determine where the cast resides, but I might be wrong. It is possible we would already back these casts up with our utility. If pg_dump handles it and we don't yet, we can investigate a way to find these casts if they do end up getting added to the database.

**Comment by hlinnaka** [comment]
On 02/03/18 08:56, Karen Huddleston wrote:
> @hlinnaka I was thinking we looked at the functions to determine where the cast resides, but I might be wrong.
A cast doesn't necessarily have a function associated with it.

- Heikki

**Comment by ivannovick** [comment]
We are leaning to a documentation enhancement that describes the behavior and all possible work arounds on the user side as well the side effects of the same.  Thanx for review all, i will close this

**Comment by chrishajas** [comment]
@hlinnaka It doesn't seem that pg_dump is dumping user-created functions that reside in the pg_catalog schema such as:
```
CREATE FUNCTION pg_catalog.text(integer) RETURNS text STRICT IMMUTABLE LANGUAGE SQL AS 'SELECT textin(int4out($1));';
```
as of 8.4.
Even explicitly dumping the pg_catalog schema with `pg_dump -n` doesn't include this statement.

**Comment by hlinnaka** [comment]
On 03/03/18 06:44, Chris Hajas wrote:
> @hlinnaka It doesn't seem that pg_dump is dumping user-created functions that reside in the pg_catalog schema such as:
> ```
> CREATE FUNCTION pg_catalog.text(integer) RETURNS text STRICT IMMUTABLE LANGUAGE SQL AS 'SELECT textin(int4out($1));';
> ```
> as of 8.4.
> Even explicitly dumping the pg_catalog schema with `pg_dump -n` doesn't include this statement.

Oh, ok.

Looking at the code, the logic is to not dump casts, if both source and 
target datatypes and the cast function reside in the pg_catalog schema. 
So you could create the functions in a different schema, to include them 
in the dump.

(See also 
https://www.endpoint.com/blog/2015/02/10/postgres-custom-casts-and-pgdump)

- Heikki

**Pull request closed without merging**
