### PR TITLE
Reorganize Concourse Pipeline: isolate pulse jobs by team

### PR DESCRIPTION
**Pull request by cjcjameson**
This helps when forking the pipeline to demonstrate a particular pulse job's green-ness before merging; you only have to pause the gatekeeper jobs, not every single one.

Pipeline to demonstrate the visual effect of the change: http://gpdb.ci.pivotalci.info/teams/dev/pipelines/pipeline_reorganization_pulse_team_isolation_1795

The paused jobs in the pipeline are highlighting the gatekeepers we added.

### CODE REVIEW

**Comment by hlinnaka** [comment]
-1. Everyone is responsible for keeping all the test suites green. And we don't foresee adding more test suites any time soon. On the contrary, everyone is busy rewriting the existing tests into the installcheck-world.

**Comment by cjcjameson** [comment]
Hi Heikki, here's our dilemma: we have test suites which are considered necessary to go green before merging, but are too long-running to be part of the PR pipeline. As such, I need a way to demonstrate that the tests pertaining to my area of development are passing to other committers.

It is expensive and taxing on the infrastructure if these forked pipelines for pull-requests run all the long-running tests of other teams. As such, we usually pause those Concourse jobs that we deem not pertinent to the main effect of our pull request's change. If there would be cross-cutting effects that would make other team's tests go red, we trust and rely on the master CI pipeline to catch those for us and we would react.

These are often test suites which are long-running and on the legacy pulse infrastructure for decently good reasons when you consider the history of what testing mechanisms were available. Be assured that we'd like to get these into ICW, and we've evaluated options to make the testing more lightweight, but we're just not there yet. I know that many teams are eagerly looking into migrating existing tests into ICW, but my guess is that 60-70% will make it; others will still linger for longer than we would like. Like in #1787, I'm guessing there are also a few more skeletons that will come falling out of the closet as we clean house.

This change makes it easier to see and measure each team's progress towards the ideal of getting tests into ICW. It will be inspiring to teams when their gatekeeper job is not needed at all!

We have an alternative approach coming up soon in an additional pull request which proposes a different re-organization that still addresses our teams' pains and needs. Please look out for that and help us evaluate the trade-offs!

**Comment by cjcjameson** [comment]
Please refer to #1797 for a different change to the pipeline, in the same pursuit and spirit. These two pull requests are not immediately mergeable, but the ideas behind each could be implemented together. Let us know if you have thoughts on that.

**Comment by ashwinstar** [comment]
-1 from me too for this. Shouldn't have exposure based on team's on main pipeline. Actually based on my discussions with @Eulerizeit we should even loose out CS_ MU_ from job names. They should reflect only product areas like FTS, BackUp, Replication, etc..

This PR is based on assumption which is very loosely held. As for some of my fix I run subset of CS jobs and some QP ones or many times small subset of CS jobs. So, Individual / team needs maybe have to be incorporated in some other way not visually visible. Plus, need lot more flexibility. Like one rough idea could be having flexibility baked into pipeline code through configurable `trigger` flag for each job and way to turn on/off through secrets file instead of pausing the jobs for forked pipeline, main having not change and trigger set to true for all.

**Comment by adam8157** [comment]
-1 from me too, better not to separate them by team, it should not be that team's responsibility to keep tasks green.

**Comment by khuddlefish** [comment]
I like the idea of having gatekeepers for certain tests. They don't necessarily have to be by team, but maybe by category instead. Often during development, we end up running just a few tests much more frequently than others because our code only touches those areas. We also don't want to overload the system by triggering many long-running, resource-heavy tests if it unlikely our changes will affect them at all. Because of that, having an easy way to pause the other tests during development would be really helpful for us.

Probably pushing this in as-is is not the best idea, but I like the general idea and would like to see something similar :)

**Comment by Eulerizeit** [comment]
If the tests are included as part of ICW there is no reason to not just run
just that part of ICW.

I guess I feel like there is a problem here that you are trying to solve
and the comments are missing the point.

-- Rob

**Comment by Chibin** [comment]
I like the idea of pausing a category of jobs and it looks like people's main concern is that they don't want specific teams to be responsible for specific tests. 
Trying to think of a way to address this issue... I think all of the long runs in parallel with ICW can help prevent team test ownership (as mentioned on the other PR). 

There still need a way to pause unrelated tests during development cycle when forking the master pipeline.  Jumping on to Ashwin's idea with my crazy idea, would it be possible to create a job prior to everything that will pause everything except the jobs you want to run? Then people can just pass a -l option when doing a fly set.

**Comment by ashwinstar** [comment]
Can we close this out.

**Comment by cjcjameson** [comment]
Yes we can close this out, however, I want to have more discussions with @khuddlefish and @jmcatamney about how to provide functionality for product-area-focused pipelines.

**Comment by khuddlefish** [comment]
@Eulerizeit Basically the trouble is that our team can't easily work with the master pipeline file when creating development pipelines because there are so many tests that aren't relevant to what we're working on that we don't want to repeatedly run. We've been forking the pipeline file and using our own version of it primarily, but it has a tendency to get out of sync with the main one. We're looking for a way to adapt the main pipeline file a bit so that we can use the same file for our development pipelines without having to manually pause a lot of jobs.

**Pull request closed without merging**
