### PR TITLE
Do not create motion when it's not allowed in cdbpath_motion_for_join().

### PR DESCRIPTION
**Pull request by paul-guo-**

### CODE REVIEW

**Comment by pengzhout** [comment]
Can you provide a test to demonstrate it?

**Comment by paul-guo-** [comment]
@pengzhout  This was found when debugging an planner issue during pg 9.4  stable merge. This impacts the planner test cases however I did not see a failure or panic due to this. Probably some wrong paths are deleted later in some code check. I'll try to find a test case to cover this. Anyway this change should be reasonable, right?

**Comment by pengzhout** [comment]
Yes, it is probably hard to make a test, so please go ahead, inceptioned the code, it looks reasonable. LGTM.

**Comment by paul-guo-** [comment]
Thanks for the review.

**Pull request merged**
