### PR TITLE
Move popen_with_stderr to separate file

### PR DESCRIPTION
**Pull request by pf-qiu**
popen_with_stderr() was introduced in execute external table, to
extract stderr from external program. It's later adopted by COPY
command too, replacing OpenPipeStream() from upstream.
    
Currently popen_with_stderr() is used both by external table and
COPY command. As we are going to move external table related code
to extension, we need to move this function to a place where both
have access.

### CODE REVIEW

**Comment by JunfengYang** [comment]
How about putting these functions into a new file so we don't have too many diffs with upstream?

**Review by adam8157 — COMMENTED** [review]
The `src/backend/access/external/url_*` or even the whole `src/backend/access/external/` will be moved out as an extension?

If so, LGTM.

**Comment by pf-qiu** [comment]
> How about putting these functions into a new file so we don't have too many diffs with upstream?

Any suggestion for a suitable location?

**Comment by JunfengYang** [comment]
> Any suggestion for a suitable location?

Maybe the same location as fd.c `src/backend/storage/file/`.

**Comment by pf-qiu** [comment]
> Maybe the same location as fd.c `src/backend/storage/file/`.

Fixed.

**Review by JunfengYang — APPROVED** [review]
+1

**Comment by d** [comment]
In hindsight, this patch created a compilation error on macOS, as can be seen in Travis CI.

**Pull request merged**
