### PR TITLE
Updated scripts to include icg to run on planner and orca [#130117989]

### PR DESCRIPTION
**Pull request by bhuvnesh2703**
As of the now the icg tests scripts only handles running the test with optimizer on. Include the flag to run tests with legacy planner.

### CODE REVIEW

**Comment by bhuvnesh2703** [comment]
@vraghavan78 @oarap @hsyuan - FYR

**Comment by hsyuan** [comment]
Can you make your profile public?

**Comment by hsyuan** [comment]
+1

**Comment by d** [comment]
LGTM. Let's ship it.

At some point we should redo how we run tests because

0. building GPDB doesn't really depend on whether we want "orca mode" or "planner mode". We always (and we should always) link with ORCA
0. codegen on/off and planner/orca are orthogonal, right now they are mixed in one bag

Leslie and Jesse (@lescha and @d)

**Pull request merged**
