### PR TITLE
Avoid infinite loop on error.

### PR DESCRIPTION
**Pull request by hlinnaka**
While hacking, I ran into the "Expected a CREATE for file-system object
name" error. But instead of printing the error, it got into an infinite
loop. smgrSortDeletesList() elog(ERROR)'d out of the function, while it
was in the middle of putting the linked list back together, leaving
pendingDeletes list corrupt, with a loop. AbortTransaction() processing
called smgrIsPendingFileSysWork(), which traversed the list, and it got
stuck in the loop.

To avoid that, don't leave the list in an invalid state on error. I don't
know why I ran into the error in the first place, but that's a different
story.

### CODE REVIEW

**Comment by ashwinstar** [comment]
Seems really tricky to validate the change without test case / scenario for it. Understand what currently exists to ERROR is not correct but just to issue WARNING and move will be any better or more needs to be done like completely skipping the invalid entries than keeping both of them, is the question test would help answer. As most likely it may PANIC later down in processing seeing the incorrect state in persistent.

**Comment by hlinnaka** [comment]
On 10/05/16 21:45, Ashwin Agrawal wrote:
> Seems really tricky to validate the change without test case /
> scenario for it.

Yeah. I encountered this situation while working on the 8.3 merge 
branch. It's a "shouldn't happen" situation to begin with, so you can't 
build a test case for it easily.

> Understand what currently exists to ERROR is not
> correct but just to issue WARNING and move will be any better or more
> needs to be done like completely skipping the invalid entries than
> keeping both of them, is the question test would help answer. As most
> likely it may PANIC later down in processing seeing the incorrect
> state in persistent.

I did test this patch when with the data directory I had that ran into 
this ERROR, and it allowed the system to proceed. But it did indeed fail 
at some completely different ERROR elsewhere.

Looking at the code, it's not clear to me why it's safe to assume that 
if there are two entries in the list for the same relation, it must be a 
CREATE+DROP pair. It feels intuitive, but is there really no 
circumstances where you could have e.g DROP+CREATE, or some weird 
subtransactions case, where that wouldn't hold.

In any case, it seems fairly safe to turn it into a WARNING, because 
collapsing the CREATE+DROP pairs is just an optimization. Isn't it? And 
leaving the list in an invalid state is definitely not a good idea. We 
could alternatively rearrange the loop so that it would e.g. restore all 
the next-pointers first, and do the collapsing in a separate loop, so 
that you could safely elog(ERROR) there.

- Heikki

**Comment by ashwinstar** [comment]
On Tue, May 10, 2016 at 2:10 PM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 10/05/16 21:45, Ashwin Agrawal wrote:
> > Seems really tricky to validate the change without test case /
> > scenario for it.
>
> Yeah. I encountered this situation while working on the 8.3 merge
> branch. It's a "shouldn't happen" situation to begin with, so you can't
> build a test case for it easily.
>

Agree, seems super remote case. Surprised you hit it.


>
> > Understand what currently exists to ERROR is not
> > correct but just to issue WARNING and move will be any better or more
> > needs to be done like completely skipping the invalid entries than
> > keeping both of them, is the question test would help answer. As most
> > likely it may PANIC later down in processing seeing the incorrect
> > state in persistent.
>
> I did test this patch when with the data directory I had that ran into
> this ERROR, and it allowed the system to proceed. But it did indeed fail
> at some completely different ERROR elsewhere.
>
> Looking at the code, it's not clear to me why it's safe to assume that
> if there are two entries in the list for the same relation, it must be a
> CREATE+DROP pair. It feels intuitive, but is there really no
> circumstances where you could have e.g DROP+CREATE, or some weird
> subtransactions case, where that wouldn't hold.
>

Looking at the check its comparing relfilenode and more stuff to make sure
they are same.
So, doubt it would pass for any other scenario except same transaction
create-drop and if any case exists then persistent table functionality
would get broken as well.


> In any case, it seems fairly safe to turn it into a WARNING, because
> collapsing the CREATE+DROP pairs is just an optimization. Isn't it?


Don't think its for optimization. It seems to be making decision based on
what operation to perform for filesystem object based on if its same
transaction create-drop.
As same entry in pending list will end-up modifying the same entry in
persistent table, it may not find it in correct state it needs to make the
modifications.

And
> leaving the list in an invalid state is definitely not a good idea. We
> could alternatively rearrange the loop so that it would e.g. restore all
> the next-pointers first, and do the collapsing in a separate loop, so
> that you could safely elog(ERROR) there.
>

Doesn't sound would make things any better than current situation and seems
more work.
Seems we do not have way to validate the after effects once we get into
this situation, but this is definitely making it better than what exists
today.
If possibly we can find in future if encountered again what got us here, we
can add more better handling for the same.

**Comment by hlinnaka** [comment]
I took that as a +1, and pushed. Thanks!

**Pull request closed without merging**
