### PR TITLE
Add syscache for gp_distribution_policy and pg_resgroup

### PR DESCRIPTION
**Pull request by pengzhout**
This should make the access to those two tables a little bit faster.

### CODE REVIEW

**Comment by pengzhout** [comment]
@hlinnaka WLM and GPCC team have some concern about the performance of accessing pg_resgroup catalog for their new features and we also found that GpPolicyFetch() and get_parts()/rel_is_partitioned() take an obvious part of the time for simple queries in pg_bench test. 

The result shows that the performance is only slightly improved by gp_distributed_policy and pg_resgroup. But for pg_partition and pg_partition_rule, the explain performance on a table with 40+ subpartition can be 10% faster for a single concurrency and can be 120% faster for 50 concurrencies (40 cores on hosts, I think the result will not be such dramatic if we merge the optimization of LWLock from upstream). 

the optimization for pg_partition_rule and pg_partition_rule are not finished yet because some frequently accessed columns of them are not designed uniquely, I'm still working on it.

**Comment by ashwinstar** [comment]
@pengzhout seems all good here, lets get this in ?

**Comment by pengzhout** [comment]
merged, thanks

**Comment by dsharp-pivotal** [comment]
Can this be cherry-picked to 5X_STABLE?

- @amilkh and d#

**Comment by amilkh** [comment]
Thanks!!

Once you do that, it will speed up considerably our extension code which
calls those RG Oid<->Name conversion functions in the critical path of
every transaction!


We'll look for the commit on 5X_STABLE tomorrow morning, but feel free to
put link to it here if you want.

2018年4月18日(水) 午後8:19 Simon Gao <notifications@github.com>:

**Comment by amilkh** [comment]
@gaos1 any update? We can't find the commit on 5X_STABLE.

@ozbasarir

**Pull request merged**
