### PR TITLE
Remove pgbouncer from gpdb repo

### PR DESCRIPTION
**Pull request by fanfuxiaoran**
Pgbouncer is in a repo which was forked from upstream:
 https://github.com/greenplum-db/pgbouncer . 
This repo maintaines GPDB specific changes.
In GPDB repo, Pgbouncer is used as a submodule now:
```
submodule "gpAux/extensions/pgbouncer/source"]	
	path = gpAux/extensions/pgbouncer/source	
	url = https://github.com/greenplum-db/pgbouncer.git	
	branch = pgbouncer_1_8_1
```
We remove pgbouncer submodule from GPDB in this pr,
and plan to release it separately.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ashwinstar** [comment]
LGTM. So, what's the plan (using it from separate repo?, are there any GPDB specific changes which need to maintained?), stating all those logistics would be good.

**Comment by fanfuxiaoran** [comment]
> using it from separate repo? are there any GPDB specific changes which need to maintained?

Yes, pgbouncer is already in a separate repo which was forked from upstream: https://github.com/greenplum-db/pgbouncer .  This repo maintaines GPDB specific changes. 

In GPDB repo, Pgbouncer is used as a submodule:
```
submodule "gpAux/extensions/pgbouncer/source"]	
	path = gpAux/extensions/pgbouncer/source	
	url = https://github.com/greenplum-db/pgbouncer.git	
	branch = pgbouncer_1_8_1
```

So, to remove pgbouncer from GPDB,  we don't have to do anything more, just remove the pgbouncer submodule, and
release it separately.

**Comment by pf-qiu** [comment]
Do we plan to include pgbouncer in gpdb release package? Seems there are still some document references.

**Comment by fanfuxiaoran** [comment]
> Do we plan to include pgbouncer in gpdb release package? Seems there are still some document references.

That's a good question.  pgbouncer is planned to be released with gpdb. But I'm not sure if its document should be left in gpdb .

@lij55  Should we keep the pgbouncer doc in gpdb repo?  Or we put both pgbouncer bin and its document into the gpdb package when we release it? Personally, I prefer the second one.

Another question, In the NOTICE file, there is something about pgbouncer license, should we move the related content to the pgbouncer repo, and add it to the gpdb repo when releasing it?

**Comment by lij55** [comment]
Hi @dyozie , do you think whether we need to keep the pgbouncer doc in Greenplum repo or not?

We will build pgbouncer independently for gp7 and later and it won't depend on any Greenplum components any more. 
We won't deprecate it but move it to another repo. Another reason is that pgbouncer can support all greenplum version and it is hard to upgrade it for GP5 now because it is feature frozen. A separated pgbouncer repo can help to keep up with latest features for user for all Greenplum versions.

**Comment by fanfuxiaoran** [comment]
In this pr , we remove all things of pgbouncer except pgbouncer doc. We just leave pgbouncer doc as pgbouncer binary package will be released with greenplum.

**Comment by ashwinstar** [comment]
> In this pr , we remove all things of pgbouncer except pgbouncer doc. We just leave pgbouncer doc as pgbouncer binary package will be released with greenplum.

I don't think the documentation should be kept with no code in this repository. Work with Docs team to find the solution for it. But seems super odd to keep the docs here.

**Comment by fanfuxiaoran** [comment]
> > In this pr , we remove all things of pgbouncer except pgbouncer doc. We just leave pgbouncer doc as pgbouncer binary package will be released with greenplum.
> 
> I don't think the documentation should be kept with no code in this repository. Work with Docs team to find the solution for it. But seems super odd to keep the docs here.

Agree. I have removed all pgbouncer related doc in the lastest commit.

**Review by beeender — APPROVED** [review]
Hope our doc team is happy about this. @dyozie

**Comment by dyozie** [comment]
@lij55 do you know how this will be packaged separately for open source and proprietary releases - rpm or something else?

**Comment by lij55** [comment]
Hi @dyozie , 
I think it will be RPM for RHEL and deb for Ubuntu.

**Pull request merged**
