### PR TITLE
gphdfs limit fix with altering process close/cleanup behavior

### PR DESCRIPTION
**Pull request by shivzone**
Limit queries can attempt to close the process handle well before underlying operation completes. 
Currently the existing implementation of the pclose function, apart from closing the data and error pipes, also attempts to read from forked process stderr and invokes a waitpid on the process which are both blocking calls. 
In case of accessing an external table via gphdfs protocol due to the above behavior, queries with a LIMIT clause can suspend the current process until the HdfsReader completes and the resources are freed. We are introducing another version of pclose (pclose_without_stderr), which can be used for scenarios when the executor doesn't need to fail on an error from forked process at this stage, and hence doesn't have to suspend execution until the completion of the child process.
(thanks to @Quikling for the above fix)

### CODE REVIEW

**Comment by shivzone** [comment]
@lij55 @sshin-pivotal

**Comment by yydzero** [comment]
Would be great if add some tests.

**Comment by shivzone** [comment]
@yydzero we didn't add any new tests as the existing regression tests exhaustively test the LIMIT functionality. The change that will be user visible will only be the performance improvement which only a performance test will expose.

**Comment by yydzero** [comment]
Make sense, thanks @shivzone

**Pull request closed without merging**
