### PR TITLE
Move copy interrupt test from Tinc to ICW

### PR DESCRIPTION
**Pull request by danielgustafsson**
Since GPDB has a lot of downstream code in the COPY codepath, testing that we are still able to interrupt a COPY in progress is of interest. Move the Tinc test to ICW and in the process make it actually test the interruption by adding enough data into the testpath that it will be able to hit before the copy is done. The original coding only added 100 rows to be copied which always finishes well before the interrupt fault injection manages to run.

### CODE REVIEW

**Comment by ashwinstar** [comment]
@danielgustafsson Still trying to understand why increasing the number of rows in needed ? With fault injection the test should be very deterministic to trigger the fault and ideally shouldn't depend on amount of rows being copied if fault injector is paced at right place. Does fault injector count rows and only trigger interrupt after certain number ?

**Comment by danielgustafsson** [comment]
> On 03 Nov 2017, at 19:59, Ashwin Agrawal <notifications@github.com> wrote:
> 
> @danielgustafsson Still trying to understand why increasing the number of rows in needed ? With fault injection the test should be very deterministic to trigger the fault and ideally shouldn't depend on amount of rows being copied if fault injector is paced at right place. Does fault injector count rows and only trigger interrupt after certain number ?

My (quite possibly flawed) thinking is that it’s timing related with copying 100 rows being done very very quickly. At least I never got it to fire before all 100 were copied but when running a larger copy it fires before it finishes.

**Comment by ashwinstar** [comment]
On Fri, Nov 3, 2017 at 12:12 PM, Daniel Gustafsson <notifications@github.com
> wrote:

>
> > On 03 Nov 2017, at 19:59, Ashwin Agrawal <notifications@github.com>
> wrote:
> >
> > @danielgustafsson Still trying to understand why increasing the number
> of rows in needed ? With fault injection the test should be very
> deterministic to trigger the fault and ideally shouldn't depend on amount
> of rows being copied if fault injector is paced at right place. Does fault
> injector count rows and only trigger interrupt after certain number ?
>
> My (quite possibly flawed) thinking is that it’s timing related with
> copying 100 rows being done very very quickly. At least I never got it to
> fire before all 100 were copied but when running a larger copy it fires
> before it finishes.
>

We mostly then should look into where fault injector is and how it fires
else it can becomes flaky test soonish depending on where or how its run.

**Comment by danielgustafsson** [comment]
> On 03 Nov 2017, at 20:36, Ashwin Agrawal <notifications@github.com> wrote:

> We mostly then should look into where fault injector is and how it fires
> else it can becomes flaky test soonish depending on where or how its run.

While I don’t think there is risk of this being flaky there are no guarantees of course. I mainly tried to stay out of rabbitholes for once and instead altered the test. I do agree that diving into the fault injector to figure out when it will run wrt the copy progress is vital though, I’ll see about rabbitholing it a little.

**Comment by hlinnaka** [comment]
Pushed, thanks!

**Comment by ashwinstar** [comment]
So, we didn't investigated the timing issue ?

**Comment by hlinnaka** [comment]
On 11/06/2017 08:17 PM, Ashwin Agrawal wrote:
> So, we didn't investigated the timing issue ?

No. Sorry. It would be good to investigate, but it's not a new issue. 
I'd rather get the tests out of TINC now, and investigate pre-existing 
issues as a separate task. The new test is at least closer to testing 
what was intended, in any case.

- Heikki

**Comment by danielgustafsson** [comment]
> On 06 Nov 2017, at 19:25, Heikki Linnakangas <notifications@github.com> wrote:
> 
> On 11/06/2017 08:17 PM, Ashwin Agrawal wrote:
> > So, we didn't investigated the timing issue ?
> 
> No. Sorry. It would be good to investigate, but it's not a new issue. 
> I'd rather get the tests out of TINC now, and investigate pre-existing 
> issues as a separate task. The new test is at least closer to testing 
> what was intended, in any case.

There is a story added to do this separately.

**Pull request merged**
