### PR TITLE
Revert some unnecessary cosmetic changes, compared to upstream

### PR DESCRIPTION
**Pull request by hlinnaka**
This reduces our diff footprint, which will reduce the number of merge conflicts we'll get when we start merging with upstream.

### CODE REVIEW

**Comment by asimrp** [comment]
Do you use `pgindent` to fix indentation such as in `parsenodes.h`?

**Comment by hlinnaka** [comment]
Sometimes. Often, if it's a single function, I just fix it manually and use "git diff REL8_2_0" to verify that it matches upstream. For larger blocks I use pgindent.

**Comment by ashwinstar** [comment]
Can we run pgindent and fix it in one shot ?
Plus contributors and committers need to make sure not to introduce more
but is it good idea to automate to run it at commit time to avoid having
more issues introduced ?

**Comment by hlinnaka** [comment]
On 11/10/2015 09:08 PM, Ashwin Agrawal wrote:
> Can we run pgindent and fix it in one shot ?

Yeah, that would be one approach. There are some drawbacks:

* It would have to be done with the exact same version of pgindent that 
was used in the upstream. There have been small changes in the rules 
over the years.
* Not all the code is all the time correctly indented in the upstream, 
either. Running pgindent on such code would in fact create a difference 
where there wasn't one before. If merging a later upstream pgindent run 
would bring the code to the same result again, you probably wouldn't get 
a merge conflict, but I wouldn't count on it.
* There are some code blocks in GPDB that are intentionally not 
"correctly" indented, to minimize the diff against upstream. The typical 
case is when a large chunk of upstream code is put inside an if-block in 
GPDB: you might want to avoid re-intending the code that's now inside 
the if-block, so patches to that code will not cause a merge conflict.
* Re-indenting all the gpdb code would cause conflicts to anyone 
currently working on patches. (this would be a one-off inconvenience 
though, and it would be nice to re-indent all the gpdb code for 
aesthetic grounds anyway.)

Overall, I don't think it's worth it to just run pgindent over 
everything in one go. There actually isn't that much of these whitespace 
differences left anyway, I've already cleaned up the worst offenders.

It would be nice to run pgindent on all of src/backend/cdb at some point 
though, just to make it look better.

> Plus contributors and committers need to make sure not to introduce more
> but is it good idea to automate to run it at commit time to avoid having
> more issues introduced ?

Same problems apply to any automation. But I highly recommend installing 
pgindent on your laptop, so that you can easily run it on any new code 
before committing. Also, pay attention to the diff vs. upstream. Before 
pushing, do a "git diff REL8_2_0 <file>" on any files you've modified, 
to check that you haven't introduced any unnecessary differences.

- Heikki

**Comment by hlinnaka** [comment]
pushed, thanks for the review!

**Comment by tangp3** [comment]
+1 for pgindent on all of src/backend/cdb.

**Pull request closed without merging**
