### PR TITLE
Implement PXF Foreign Data Wrapper

### PR DESCRIPTION
**Pull request by oliverralbertini**
This PR introduces a FDW implementation that can connect Greenplum with external data via the PXF service.

Currently this FDW can leverage Greenplum's parallel processing for reading data from external sources, but is limited to writing data to the external source on master only.

Unlike with external tables, PXF <-> Greenplum wire format is only CSV, this FDW does not use the old GreenplumWritable binary format.

COPY:

We externalized `BeginCopy()` in `src/backend/commands/copy.c`.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Please expand the description of this PR a bit.

**Comment by oliverralbertini** [comment]
> Please expand the description of this PR a bit.

We will expand the description shortly. Currently we are making some code adjustments to support both 6X_STABLE and master (previous work was based on 6X_STABLE).

**Comment by hlinnaka** [comment]
Cool! With this, we can remove `contrib/pxf`, right?

Why is the change to BeginCopy() required? Can you use BeginCopyFrom() instead? That's already exposed, and used e.g. by the file_fdw.

**Comment by oliverralbertini** [comment]
> Cool! With this, we can remove `contrib/pxf`, right?

I'm glad there is shared excitement about FDW. We plan to remove the PXF external table code from `gpcontrib/pxf` in an upcoming PR :)

> Why is the change to BeginCopy() required? Can you use BeginCopyFrom() instead? That's already exposed, and used e.g. by the file_fdw.

`BeginCopyFrom()` is useful for read operations (and we use it in `pxf_fdw.c`).

We needed a COPY function for write operations, and after discussing with @gkokolatos, @danielgustafsson, and @frankgh we decided to externalize `BeginCopy()`.

**Comment by hlinnaka** [comment]
> I'm glad there is shared excitement about FDW. We plan to remove the PXF external table code from gpcontrib/pxf in an upcoming PR :)

I'd really like to see that happen in the same PR. We need to have the upgrade path figured out, and I'm afraid if we add the FDW first and leave removing the old stuff until later, we'll never get around to actually remove the old stuff, and then we'll be on the hook to maintain both.

**Comment by hlinnaka** [comment]
This should probably be in `gpcontrib/` rather than `contrib/`.

**Comment by hlinnaka** [comment]
I tried to test this, copying the commands from the regression tests. It seems the regression tests only exercise the CREATE commands, they don't actually try to fetch or modify any data using the FDW, so I tried this:
```
postgres=# create extension pxf_fdw;
CREATE EXTENSION
postgres=# CREATE FOREIGN DATA WRAPPER pxf_fdw_test_pxf_fdw
    HANDLER pxf_fdw_handler
    VALIDATOR pxf_fdw_validator
    OPTIONS ( protocol 'pxf_fdw_test', mpp_execute 'all segments' );
CREATE FOREIGN DATA WRAPPER
postgres=# CREATE SERVER pxf_fdw_test_server
postgres-#     FOREIGN DATA WRAPPER pxf_fdw_test_pxf_fdw;
CREATE SERVER
postgres=# CREATE USER MAPPING FOR heikki
    SERVER pxf_fdw_test_server;
CREATE USER MAPPING
postgres=# CREATE FOREIGN TABLE pxf_fdw_test_table_with_delim (id int, name text)
postgres-#     SERVER pxf_fdw_test_server
postgres-#     OPTIONS ( resource '/path/to/resource', delimiter '|' );
CREATE FOREIGN TABLE
postgres=# select * from pxf_fdw_test_table_with_delim;
ERROR:  remote component error (500) from '127.0.0.1:5888':  Type  Exception Report   Message  pxf_fdw_test is not defined in pxf-profiles.xml   Description  The server encountered an unexpected condition that prevented it from fulfilling the request.   Exception   org.greenplum.pxf.service.profile.ProfileConfException: pxf_fdw_test is not defined in pxf-profiles.xml (libchurl.c:946)
```
What is `pxf-profiles.xml`? I couldn't find any documentation for that in this PR nor in the PXF repository. How do you test this?

**Comment by frankgh** [comment]
Here's the documentation about profiles: https://gpdb.docs.pivotal.io/6-3/pxf/sdk/deploy_profile.html

PXF has some native profiles, but you can create your custom profile.

For documentation about pxf_fdw, please take a look at this:
https://github.com/greenplum-db/pxf/blob/pxf-fdw-d/PXF_FDW.md

**Comment by hlinnaka** [comment]
On 28/01/2020 18:17, Francisco Guerrero wrote:
> Here's the documentation about profiles: 
> https://gpdb.docs.pivotal.io/6-3/pxf/sdk/deploy_profile.html
> 
> PXF has some native profiles, but you can create your custom profile.

I tried creating a pxf-profiles.xml file, next to the 
"pxf-profiles-default.xml" file that "make install" created, and 
restarted. That didn't work, selecting from the foreign table still 
complained about missing profile. I then copy-pasted the custom profile 
to the pxf-profiles-default.xml file, and that fixed that issue.

Next error:

ERROR:  remote component error (500) from '127.0.0.1:5888':  Type 
Exception Report   Message  Class 
org.greenplum.pxf.example.demo.DemoFragmenter is not found   Description 
  The server encountered an unexpected condition that prevented it from 
fulfilling the request.   Exception   java.lang.RuntimeException: Class 
org.greenplum.pxf.example.demo.DemoFragmenter is not found (libchurl.c:946)

I can see DemoFragmenter.class in the PXF build dir, in 
./server/pxf-api/build/classes/java/main/org/greenplum/pxf/api/examples/DemoFragmenter.class. 
Do I need to manually copy the class files somewhere? Where?

The "CREATE EXTENSION pxf_fdw" command created a bunch of built-in FDW 
objects, for different protocols. I also tried using the build-in 
"file_pxf_fdw", but I got the same error about missing profile entry, 
for profile named "localfile". Is "localfile" supposed to be included in 
the default profiles file? If not, what is the correct way to set that up?

> For documentation about pxf_fdw, please take a look at this:
> https://github.com/greenplum-db/pxf/blob/pxf-fdw-d/PXF_FDW.md

Oh, thanks, that's useful! That file probably should be included  in 
this PR. Or is that going to merged into the PXF master branch?

- Heikki

**Comment by frankgh** [comment]
I did the following:

1. create a file in `/tmp/a.txt`
```
1|heikki
2|francisco
```

2. edit `$PXF_CONF/conf/pxf-profiles.xml` and added this profile:
```
    <profile>
        <name>localfile</name>
        <description>test accessing profiles</description>
        <plugins>
            <fragmenter>org.greenplum.pxf.plugins.hdfs.HdfsDataFragmenter</fragmenter>
            <accessor>org.greenplum.pxf.plugins.hdfs.LineBreakAccessor</accessor>
            <resolver>org.greenplum.pxf.plugins.hdfs.StringPassResolver</resolver>
        </plugins>
	<protocol>localfile</protocol>
    </profile>
```

3. Restart pxf:
```
pxf restart
```

4. test it:
```
psql
# create extension pxf_fdw;
# CREATE FOREIGN DATA WRAPPER pxf_fdw_test_pxf_fdw
HANDLER pxf_fdw_handler
    VALIDATOR pxf_fdw_validator
    OPTIONS ( protocol 'localfile' , mpp_execute 'all segments' );
# CREATE SERVER pxf_fdw_test_server
FOREIGN DATA WRAPPER pxf_fdw_test_pxf_fdw;
# CREATE USER MAPPING FOR <YOUR_USER>
SERVER pxf_fdw_test_server;
# CREATE FOREIGN TABLE pxf_fdw_test_table_with_delim (id int, name text)
SERVER pxf_fdw_test_server
OPTIONS ( resource '/tmp/a.txt', delimiter '|');
# select * from pxf_fdw_test_table_with_delim ;
```

Let me know if this is useful.

**Comment by hlinnaka** [comment]
Thanks, now I got it working!

I think the next step is to figure out the upgrade path. How are we going to map the CREATE EXTERNAL TABLE command for a PXF table into this new FDW?

**Comment by oliverralbertini** [comment]
@hlinnaka Thanks for trying it out. We have in the pxf repo (https://github.com/greenplum-db/pxf) integration tests that exercise `pxf_fdw`. It's located here: https://github.com/greenplum-db/pxf/tree/master/regression.

To run these tests one needs external data sources like HDFS or S3 set up, but here is our pipeline for running these tests: https://ud.ci.gpdb.pivotal.io/teams/main/pipelines/pg_regress.

Currently it's just a small series of smoke tests that exercise reading/writing to external sources, but we are hoping to expand this soon.

**Comment by hlinnaka** [comment]
I was surprised to see this being merged already. What is the upgrade path from the old implementation to the new FDW_based one? The mapping of the CREATE EXTERNAL TABLE command, so that it would create a corresponding foreign table instead has not been implemented, and we haven't really even discussed how to do it. Or are we just going to document a manual procedure where you drop the old tables before upgrade, and create new ones with CREATE FOREIGN TABLE after upgrade?

**Comment by hlinnaka** [comment]
BTW, why is the PXF FDW (and the PXF external protocol before this PR) even in the GPDB repository? It's tightly coupled with PXF, but only interacts with GPDB through the stable FDW API. Wouldn't it make more sense to have it in the PXF repository?

**Comment by vraghavan78** [comment]
@hlinnaka talked with both @bharath1028, @Eulerizeit and the upgrade team about this. The conclusion was to not do it piece meal and rather do it when all the teams touching external table code to have a unified way to upgrade. Inevitably some one has to pickup that work, until the end state is known it does not make sense to do it. the PXF folks just wanted to put the first chip on the board when merging this work.

**Comment by vraghavan78** [comment]
@hlinnaka we are considering PXF FDW out of GPDB code. We are currently having the conversation @edespino @kmacoskey and targeting it for mid-March.

**Comment by Eulerizeit** [comment]
> @hlinnaka talked with both @bharath1028, @Eulerizeit and the upgrade team about this. The conclusion was to not do it piece meal and rather do it when all the teams touching external table code to have a unified way to upgrade. Inevitably some one has to pickup that work, until the end state is known it does not make sense to do it. the PXF folks just wanted to put the first chip on the board when merging this work.

Going to also add @brianlugongyu and @lij55 to this comment.  I think that is all of the users of the External Table API

**Pull request merged**
