### PR TITLE
Fix distributed transaction id issue

### PR DESCRIPTION
**Pull request by xiong-gang**
Previously, we generate a distributed transaction id and assign it to
'TMGXACT->gxid' later when the distributed transaction needs the two-phase
commit. This will cause invalid distributed snapshot sometimes. We need to make
the bump and set atomic. See the comments in currentDtxActivateTwoPhase().

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by xiong-gang** [comment]
backport PR #8826 to 6X_STABLE

**Comment by frankgh** [comment]
@denalex @oliverralbertini this may impact PXF. @xiong-gang when are you planning to merge this? Can we hold off on merging until we have a workaround for PXF?

**Comment by ashwinstar** [comment]
I am not 100% sure but feel we started seeing this failure for master branch after this change was committed to master.

```
--- /tmp/build/e18b2f02/gpdb_src/src/test/isolation/expected/heap-repeatable-read-vacuum-freeze.out    2019-11-27 16:51:55.196333541 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/isolation/results/heap-repeatable-read-vacuum-freeze.out    2019-11-27 16:51:55.208333539 +0000
@@ -153,16 +153,16 @@
 FrozenXid      InvalidXid     7              7              
 FrozenXid      InvalidXid     8              8              
 FrozenXid      InvalidXid     9              9              
-NormalXid      InvalidXid     10             10             
-NormalXid      InvalidXid     11             11             
 NormalXid      InvalidXid     12             12             
-NormalXid      InvalidXid     13             13             
-NormalXid      InvalidXid     14             14             
 NormalXid      InvalidXid     15             15             
 NormalXid      InvalidXid     16             16             
-NormalXid      InvalidXid     17             17             
 NormalXid      InvalidXid     18             18             
 NormalXid      InvalidXid     19             19             
+NormalXid      InvalidXid                                   
+NormalXid      InvalidXid                                   
+NormalXid      InvalidXid                                   
+NormalXid      InvalidXid                                   
+NormalXid      InvalidXid                                   
 step s1vacuumfreeze: VACUUM heaptest;
 step s2select: 

     SELECT * from show_heaptest_content ORDER BY i;
```

So, would highly recommend we RCA that test failure first and see if it relates to this change or not. Only post that we should commit this to 6X_STABLE.

**Comment by xiong-gang** [comment]
> @denalex @oliverralbertini this may impact PXF. @xiong-gang when are you planning to merge this? Can we hold off on merging until we have a workaround for PXF?

Sure

**Comment by xiong-gang** [comment]
> I am not 100% sure but feel we started seeing this failure for master branch after this change was committed to master.
> 
> ```
> --- /tmp/build/e18b2f02/gpdb_src/src/test/isolation/expected/heap-repeatable-read-vacuum-freeze.out    2019-11-27 16:51:55.196333541 +0000
> +++ /tmp/build/e18b2f02/gpdb_src/src/test/isolation/results/heap-repeatable-read-vacuum-freeze.out    2019-11-27 16:51:55.208333539 +0000
> @@ -153,16 +153,16 @@
>  FrozenXid      InvalidXid     7              7              
>  FrozenXid      InvalidXid     8              8              
>  FrozenXid      InvalidXid     9              9              
> -NormalXid      InvalidXid     10             10             
> -NormalXid      InvalidXid     11             11             
>  NormalXid      InvalidXid     12             12             
> -NormalXid      InvalidXid     13             13             
> -NormalXid      InvalidXid     14             14             
>  NormalXid      InvalidXid     15             15             
>  NormalXid      InvalidXid     16             16             
> -NormalXid      InvalidXid     17             17             
>  NormalXid      InvalidXid     18             18             
>  NormalXid      InvalidXid     19             19             
> +NormalXid      InvalidXid                                   
> +NormalXid      InvalidXid                                   
> +NormalXid      InvalidXid                                   
> +NormalXid      InvalidXid                                   
> +NormalXid      InvalidXid                                   
>  step s1vacuumfreeze: VACUUM heaptest;
>  step s2select: 
> 
>      SELECT * from show_heaptest_content ORDER BY i;
> ```
> 
> So, would highly recommend we RCA that test failure first and see if it relates to this change or not. Only post that we should commit this to 6X_STABLE.

I am going to investigate it first. Thanks.

**Comment by xiong-gang** [comment]
> > I am not 100% sure but feel we started seeing this failure for master branch after this change was committed to master.
> > ```
> > --- /tmp/build/e18b2f02/gpdb_src/src/test/isolation/expected/heap-repeatable-read-vacuum-freeze.out    2019-11-27 16:51:55.196333541 +0000
> > +++ /tmp/build/e18b2f02/gpdb_src/src/test/isolation/results/heap-repeatable-read-vacuum-freeze.out    2019-11-27 16:51:55.208333539 +0000
> > @@ -153,16 +153,16 @@
> >  FrozenXid      InvalidXid     7              7              
> >  FrozenXid      InvalidXid     8              8              
> >  FrozenXid      InvalidXid     9              9              
> > -NormalXid      InvalidXid     10             10             
> > -NormalXid      InvalidXid     11             11             
> >  NormalXid      InvalidXid     12             12             
> > -NormalXid      InvalidXid     13             13             
> > -NormalXid      InvalidXid     14             14             
> >  NormalXid      InvalidXid     15             15             
> >  NormalXid      InvalidXid     16             16             
> > -NormalXid      InvalidXid     17             17             
> >  NormalXid      InvalidXid     18             18             
> >  NormalXid      InvalidXid     19             19             
> > +NormalXid      InvalidXid                                   
> > +NormalXid      InvalidXid                                   
> > +NormalXid      InvalidXid                                   
> > +NormalXid      InvalidXid                                   
> > +NormalXid      InvalidXid                                   
> >  step s1vacuumfreeze: VACUUM heaptest;
> >  step s2select: 
> > 
> >      SELECT * from show_heaptest_content ORDER BY i;
> > ```
> > 
> > 
> > So, would highly recommend we RCA that test failure first and see if it relates to this change or not. Only post that we should commit this to 6X_STABLE.
> 
> I am going to investigate it first. Thanks.

Fix it in #9178

**Comment by gaos1** [comment]
@frankgh @vraghavan78 please let us know when you have a workaround so that Gang can move forward to merge this PR.

**Comment by frankgh** [comment]
@gaos1 we have a workaround. Please feel free to merge this PR

**Pull request merged**
