### PR TITLE
docs: Remove documentation for gpdetective and deprecated utils

### PR DESCRIPTION
**Pull request by danielgustafsson**
gpdetective was removed in 4.3.5, so it seems about time to also remove the documentation for it (which was unreachable due to the app being marked deprecated).

### CODE REVIEW

**Comment by lisakowen** [comment]
thanks for noticing this.  might also want to remove the gpdetective reference in gpdb-doc/dita/utility_guide/admin_utilities/util_ref.xml.

**Comment by danielgustafsson** [comment]
> thanks for noticing this. might also want to remove the gpdetective reference in gpdb-doc/dita/utility_guide/admin_utilities/util_ref.xml.

Since there are quite a few utils there marked "deprecated", this being one of them, I thought it was the plan to keep them there? If not, is there a strategy for when to remove from the list?

**Comment by lisakowen** [comment]
i think that when we mark a utility as deprecated, it is still available in that release and may be removed in a future release.  i think we should definitely remove references to utilities that are not included/shipped in the greenplum rpm.  i do not know the history of gpdetective, but it doesn't appear to be in 6.0.0.beta3.  @dyozie

**Comment by danielgustafsson** [comment]
>  i do not know the history of gpdetective, but it doesn't appear to be in 6.0.0.beta3. @dyozie

It was removed in 4.3.5.1 on May 1st 2015, so it's been gone for a good four years.

**Comment by lisakowen** [comment]
@dyozie - do you agree that we should remove references to utilities that are not included in the RPM?   like gpdetective?

**Comment by dyozie** [comment]
Yes, for sure!

**Comment by danielgustafsson** [comment]
I've updated the PR with a commit that removes the deprecated utils (date of removal is in the commit message), and amended the gpdetective commit with removing the reference too.

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review!

**Pull request closed without merging**
