### PR TITLE
Fix the TimeoutId ABI breakage

### PR DESCRIPTION
**Pull request by adam8157**
7.0 reserved the [10, 20) as user-defined IDs, to not break the ABI, we
have to reserve the same and extend the MAX_TIMEOUTS.

This commit also introduces a new flag GP_ABI_BUMP_FIXME, to mark
all the ABI compromises.

Ref: efedbc21fca3f3b171e9f7aa4180ab55566d7956

### CODE REVIEW

**Review by zxuejing — APPROVED** [review]

**Review by higuoxing — APPROVED** [review]
Compared the ABI against the `tag:7.0.0` using the `abi-dumper` and `abi-compliance-checker`. LGTM!

```
Total binary compatibility problems: 0, warnings: 0
Total source compatibility problems: 0, warnings: 0
```

**Comment by adam8157** [comment]
I don't know if `abi-dumper` and `abi-compliance-checker` are smart enough to get this workaround idea :)

Thanks for the review, merging.

**Comment by higuoxing** [comment]
> I don't know if `abi-dumper` and `abi-compliance-checker` are smart enough to get this workaround idea :)

You're correct. These tools are not smart enough to detect this ABI breaking change. :unamused:

**Comment by adam8157** [comment]
> > This commit also introduces a new flag GP_ABI_BUMP_FIXME, to mark
> > all the ABI compromises.
> 
> I don't understand what this is introduced for? Please can you explain more. Do not like FIXME aspect to be introduced in code. What remains to be fixed, lets discuss and fix it instead of labeling it as FIXME.

I introduced the label to mark the ABI workarounds, which could be fixed (revert this PR's change to the `timout.h` for example) but not workaround-ed once we are fine to have an ABI break, for like branching for Greenplum 8.

`FIXME` is a bit too serious I agree.

**Pull request merged**
