### PR TITLE
Revert deletion of separate_qautils_files_for_rc

### PR DESCRIPTION
**Pull request by bmdoil**
The task is being used in the 5X_release pipeline.

Authored-by: Brent Doil <bdoil@vmware.com>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bmdoil Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10948)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10948) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by bmdoil** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@bmdoil This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by pivotal-issuemaster** [comment]
@bmdoil Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10948)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10948) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bmdoil Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=10948)!

**Review by xinzweb — APPROVED** [review]
+1

**Pull request merged**
