### PR TITLE
Gang leak

### PR DESCRIPTION
**Pull request by foyzur**
As part of stability improvement effort, we have been working to detect leaking memory in GPDB sessions. We found that GangContext leaks 576 bytes per gang destruction, including idle session cleanup, which happens every 18 seconds in release build (by default).

In this PR we are resetting the GangContext whenever we destroy the writer and the reader gangs. This fixes the above described 576 bytes leaks per destruction.

### CODE REVIEW

**Comment by foyzur** [comment]
@yydzero @xiong-gang QX team is not an expert of dispatch. This is our best effort fix. Please add appropriate reviewers to see if this fix would work.

**Comment by xiong-gang** [comment]
+1
@foyzur 
Most memory are destroyed when a gang get destroyed, except some static variables in the context: cdb_component_dbs: not used actually
allocatedReaderGangsN, allocatedReaderGangs1, availableReaderGangsN, availableReaderGangs1, primaryWriterGang: as all gangs are destroyed, they should be NULL as well.

So i guess it's ok to reset the memory context after destroy all gangs. 
Actually, i am recently refactoring the gang management code, do you have any tools/method to detect the memory leak that i can run after my change?

**Comment by foyzur** [comment]
@xiong-gang we wrote a tool to detect memory leaks in our hack day project. This integrates with memory accounting and memory contexts. The idea is:

1. At the end of a transaction, we look into the rollover account balance (a memory account that tracks the changing ownership for the allocations for which owners are no longer alive) and check how much the balance is increasing.

2. If the balance of the rollover increases enough, we consider that a leak. We then start walking the allocation lists of the "dangling" allocations that are now owned by rollover and check the "generation" of allocations, that says "did we see the same location allocating memory repeated in last "N" generation, without bothering to free it?" In such cases we declare it as a leak.

The tool is still in very much experimental phase, but that's how we detected this leak. I can send you my private branch later, but please don't expect a polished product.

**Comment by gcaragea** [comment]
Thanks for the discussion @foyzur @xiong-gang 
Looks good +1

**Comment by foyzur** [comment]
6tf

**Comment by xiong-gang** [comment]
Sweet!

**Pull request closed without merging**
