### PR TITLE
Remove quote_identifier in function list_join()

### PR DESCRIPTION
**Pull request by hyongtao-db**
Long log:

This commit can fix the bug reported in #16753 

### Error
Without this commit, the last column name `time` and its name in FDW options `"time"` are different, shown as below, which leads to this error `column ""time"" of relation "test_quote_ext" does not exist`. 
``` sql
gpadmin=# \d test_quote_ext
                       Foreign table "public.test_quote_ext"
 Column  |           Type           | Collation | Nullable | Default | FDW options 
---------+--------------------------+-----------+----------+---------+-------------
 id      | bigint                   |           |          |         | 
 item    | text                     |           |          |         | 
 price   | integer                  |           |          |         | 
 segment | integer                  |           |          |         | 
 time    | timestamp with time zone |           |          |         | 
FDW options: (format 'csv', delimiter ',', "null" '', escape '"', quote '"', 
force_quote 'id,item,price,segment,"time"', 
location_uris 'gpfdist://@hostname@:7070/gpfdist2/test_quote.csv', 
execute_on 'ALL_SEGMENTS', log_errors 'disable', 
encoding 'UTF8', is_writable 'true')
Distributed by: (id)
```

### Analyse
`quote_identifier()` will call `ScanKeywordLookup()`, which scans keywords in the file `kwlist.h`. Of course, `time` is a keyword, so becomes `"time"` after `quote_identifier()` in the function `list_join()`. Now, the same column has different names. So it will hit `if (attnum == InvalidAttrNumber)` and error out at function `CopyGetAttnums()` in `copy.c`.

### Solution
The solution is simple, remove `quote_identifier()` in function `list_join()` to keep the column name with keywords unchanged.

Bug catcher: Wenkang Zhang <zwenkang@vmware.com> and Rui Wang <ruiw2@vmware.com>

### CODE REVIEW

**Comment by hyongtao-db** [comment]
dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-hyongtao-rocky9

**Review by avamingli — APPROVED** [review]
Nice catch and LGTM.
It seems  no reason `quote_identifier` must be used here.

Does readable external table have the issue when  its OPTIONS has keywords? Add a case would be nicer.

**Comment by hyongtao-db** [comment]
@avamingli Hi Mingli, thanks for your review. I will add a test case about the readable external table.
BTW, I just listened to your tech talk about MPP parallel hash join. Awesome work.

**Review by avamingli — APPROVED** [review]

**Review by zhaorui20005 — APPROVED** [review]
LGTM. Thanks for the contribution.

**Comment by khuddlefish** [comment]
@hyongtao-db I'm a little worried that quote_identifier was there for a reason like supporting special characters. Do we have tests that cover special characters cases to confirm that behavior still works?

**Comment by hyongtao-db** [comment]
> @hyongtao-db I'm a little worried that quote_identifier was there for a reason like supporting special characters. Do we have tests that cover special character cases to confirm that behavior still works?

OK, thanks. I will take a look. And I think the column name has several limitations, shown as below. What kind of special characters do you think might be wrong?

```
gpadmin=# create table t1 ('c1' int, 'c2' text, c3 bigint);
ERROR:  syntax error at or near "'c1'"
```

```
gpadmin=# create table t2 ("c1" int, "c2" text, c3 bigint); --work same as create table t2 (c1 int, c2 text, c3 bigint);
CREATE TABLE
gpadmin=# \d t2
                 Table "public.t2"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 c1     | integer |           |          |
 c2     | text    |           |          |
 c3     | bigint  |           |          |
Distributed by: (c1)
```

```
gpadmin=# create table t3 (c\"1 int, c\"\"2 text, c3 bigint);
invalid command \"1
```

**Comment by khuddlefish** [comment]
Mostly things like quotes themselves. Like ` or " inside of a column name. Do we support `create table t1 ("c'1" int, 'c2' text, c3 bigint);`? I'm a little unclear on what the current restrictions are.

**Comment by hyongtao-db** [comment]
Hi @khuddlefish ,
Thank you for your attention.
There are some restrictions about column names about `quote` in PG. But I did not find a doc about the details of it.
So I do the test manually.
``` SQL
test=# create table test1 ('c1' int);
ERROR:  syntax error at or near "'c1'"
LINE 1: create table test1 ('c1' int);
                            ^
test=# create table test2 (c''1 int);
ERROR:  syntax error at or near "''"
LINE 1: create table test2 (c''1 int);
                             ^
test=# create table test3 ("c1" int);
CREATE TABLE
test=# create table test4 ("c'1" int);
CREATE TABLE
test=# create table test5 ("c""1" int);
CREATE TABLE
test=# create table test6 ("c''1" int);
CREATE TABLE
test=# create table test7 ("c'""'1" int);
CREATE TABLE
```

Table test3/test4/test5/test6/test7 can work with this commit.

I think the column name in FDW options should be consistent with the column name when creating the table. 
I also totally understand your concern. But could you please give me a counter-example?

**Comment by hyongtao-db** [comment]
How about keeping this commit in 7X, but don't cherry-pick to 6X.
Until the user triggers the error?

**Comment by kainwen** [comment]
> How about keeping this commit in 7X, but don't cherry-pick to 6X. Until the user triggers the error?

Seems reasonable.

**Comment by hyongtao-db** [comment]
Thanks Zhenghua.

**Pull request merged**
