### PR TITLE
Publish GPDB 6 release candidate artifacts to GCS

### PR DESCRIPTION
**Pull request by benchristel**
As part of our push to move artifacts to Google Cloud Storage with a new organizational scheme, we're migrating GPDB 6 release candidates to GCS.

This is a backward-compatible change: artifacts will still be pushed to S3. However, those artifacts should be considered deprecated. We will remove them in a future PR.

### CODE REVIEW

**Comment by dsharp-pivotal** [comment]
greenplum for kubernetes team will not be affected by this PR, since we are only using 5X artifacts for Ubuntu.

**Comment by lavjain** [comment]
Unmanaged data team approves this change. However, we will migrate to the new naming convention sometime in the future.

**Comment by chrishajas** [comment]
This shouldn't affect orca.

**Comment by njayaram2** [comment]
We have created a chore to handle the changes to be made by AA team.
Description of the chore:
---
gp-releng team moves bin_gpdb_centos{6,7}_rc to use gcs instead of s3.
But our pipelines still use the s3 artifacts:
```
concourse/pipelines/madlib_gpdb6_pipeline.yml
765:    versioned_file: release_candidates/bin_gpdb_centos6/gpdb6/debug/bin_gpdb.tar.gz

concourse/pipelines/postgis_pipeline_gpdb6.yml
257:    versioned_file: release_candidates/bin_gpdb_centos6/gpdb6/debug/bin_gpdb.tar.gz
```

With this story, we should:
1. make our pipelines use gcs artifacts
2. possibly rename bin_gpdb_centos{6,7} resources to bin_gpdb_centos{6,7}_rc to be more accurate
3. update scripts to use new filename (it used to be bin_gpdb.tar.gz but has changed), we could make use `server-*` glob

**Pull request merged**
