### PR TITLE
Remove unnecessary includes in ORCA translator code

### PR DESCRIPTION
**Pull request by hlinnaka**

### CODE REVIEW

**Comment by vraghavan78** [comment]
@hlinnaka I think these are the functions that the funcs.cpp that where moved to contrib.

**Comment by hlinnaka** [comment]
Oh, bummer..

Would be good to fix the regression tests that are (now) in contrib/orca_debug. If we had that hooked into the pipeline, I would've noticed that they're broken. (Yeah, in this case I should've realized it anyway since I just moved them the other day, but still..)

I'll just clean up the #includes then..

**Comment by vraghavan78** [comment]
Can you update the title to state remove unwanted header files?

**Comment by hlinnaka** [comment]
Ok, pushed the #include cleanup part. Thanks!

**Pull request merged**
