### PR TITLE
Some autoconf cleanups

### PR DESCRIPTION
**Pull request by danielgustafsson**
These are a few small cleanups I ran across during my ongoing work to better adapt our autoconf setup. A summary of these patches is:

* Removing deprecated options from `Makefile.global` and fixing an incorrect one
* Tidying up output printing for both configuration and `--help`
* Properly forcing library checks for EMC Connect and DD Boost to avoid compilation failure later on in case someone enables without having the dependencies installed (since I have neither installed this is based on the `-lfoo` commands issued in the Makefiles). Also updates the `pg_config.h` file to reflect these settings.

### CODE REVIEW

**Comment by hlinnaka** [comment]
+1. Note that the changes to --disable-integer-datetimes and --enable-coverage will need to be reverted again once we merge f7ef575fb72cf5f9e0a6fb530e52c4ff13588f12, in 8.4. It's probably still worth changing them in the meanwhile.

**Comment by hlinnaka** [comment]
Looks good as far as this goes.

As followup cleanup: If you build with --enable-ddboost, you also need ddp_api.h header file, so would be nice to check for that too.

**Comment by danielgustafsson** [comment]
Nice catch, added the check for `ddp_api.h` as well.

**Comment by danielgustafsson** [comment]
Merged, thanks for review.

**Pull request closed without merging**
