### PR TITLE
Move "concourse" directory to new "mgmt" directory

### PR DESCRIPTION
**Pull request by andreasscherbaum**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@andreasscherbaum Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1406)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1406) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by d** [comment]
-1.
This is pointless.

**Comment by cjcjameson** [comment]
I definitely agree that we should push `concourse` as a directory down from being a top level directory. It's an implementation selection for how we build and test our code (collectively and mostly on master; less-so locally). But we might ever have other tools and systems that help as well. For example, the Pivotal team @bhuvnesh2703 @Chibin might involve or include some configuration  for another system, Pulse, very soon: #1404 

Can all y'all coordinate on a better directory organization for both PRs? I propose that `pulse` and `concourse` live as siblings under a top-level directory called `ci`: "continuous integration"

**Comment by bhuvnesh2703** [comment]
+1 to directory change. Will structure it as:
├── ci
│   ├── concourse
│   └── pulse

**Comment by ashwinstar** [comment]
+1 to that layout Bhuvnesh.

**Comment by hlinnaka** [comment]
@andreasscherbaum, what's the point of this change? I don't see any reason for the churn.

@bhuvnesh2703: We're getting rid of pulse, right? I sure hope we're not going to get any more pulse stuff into the repository. Which makes the proposed "ci" directory quite pointless.

**Comment by bhuvnesh2703** [comment]
@hlinnaka In future, may be we will phase out pulse. However, for now and several more months, i believe we will be using pulse. I think, before even removing pulse and shifting all the testing to concourse, we should ensure that concourse provides us with reliable infrastructure atleast for the bare minimum product building and icg/b testing. Though, thats more of company decision.

And once we move pulse, we will be doing enough refactoring and may be can remove the pulse directory that time. Atleast for now, its pulse, so plan to use it that way.

Either way "ci" directory will still be acting as a top level directory and anything required to run the test suites on product can fit as a subdirectory under ci.

**Comment by Eulerizeit** [comment]
Maybe these conversations ought to be had in the gpdb-dev email list instead of in a PR. If there is consensus then moving things around according to consensus is fine, otherwise it looks like we are just capriciously moving stuff around.

**Comment by andreasscherbaum** [comment]
We had this discussion on the mailinglist already, and "mgmt" is what we settled with.

The point of moving "concourse" to a subdirectory is to allow for other tools as well, Pulse was mentioned and I have a bunch of Ansible scripts as well. If we chose "ci" over management, we need yet another subdirectory for all the other tools like Puppet, Salt, Ansible and such. Maybe we can have:
|-- mgmt
|   ├-- ci
|   └-- Ansible
...

Yet another goal is to clean up gpMgmt, but I rather not touch this one right now.

**Comment by cjcjameson** [comment]
I don't recall seeing the mailing list discussion, but indeed, various tools don't quite fall into Continuous Integration.

**Comment by andreasscherbaum** [comment]
Subject: "Restructure deployment tools"
Subject: "Restructure management and deployment tools"

I see that we had 2 discussions.

**Comment by davecramer** [comment]
Is this testable on concourse as a pr? It appears to be failing in it's current incarnation

**Comment by ascherbaum-pivotal** [comment]
The failing test is the missing CLA - @schubert promised to look into this.
This PR is not actually tested by any of our tests.

**Comment by schubert** [comment]
@andreasscherbaum I don't have access to re-add a historical CLA now. Can you just re-click through on the CLA? https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1406

**Comment by andreasscherbaum** [comment]
@schubert Yeah, I tried that a few times. I also sent the email with the PDF again, a few days ago. Nothing so far.

**Comment by schubert** [comment]
@andreasscherbaum try the manual sync link - https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1406 failing that, summon @rwinch to maybe take a look because at that point I have no idea, it's a black box to us.

**Comment by andreasscherbaum** [comment]
I did that as well :-(

@rwinch Can you please have a look why the bot is not picking up my CLA?

**Comment by pivotal-issuemaster** [comment]
@andreasscherbaum Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1406)!

**Comment by rwinch** [comment]
It appears we got this sorted out. The links that @andreasscherbaum clicked on all took him to the sync page. When we tried to reproduce this, we were unable to (i.e. the sign links take to the sign CLA page as expected). What this does point out is that it would be nice if it were more obvious that the sync does not do anything unless the user has actually signed the CLA. I created https://github.com/pivotalsoftware/pivotal-cla/issues/148 to address this

**Comment by schubert** [comment]
If we are not going to rename the directory can we close this out? The last discussion was 6 months ago but it did not seem to come to any conclusion. @andreasscherbaum since renaming actually breaks a lot of things, it'll need agreement and coordination with many devs. Pick this back up on the mailing list if you'd like.

I'd -1 calling it "mgmt" for 2 reasons:

1. It's confusing with existing "gpMgmt" so that should get dealt with first.
2. "concourse" while I'd rather see named just "ci" since ci is a generalized concept and many of the scripts in it are generic to any CI system (e.g. whats in in concourse/scripts).
3. "mgmt" could imply product/cluster management and we should not conflate actual product code subdirectories with build-only related things.
4. We also have "gpAux/releng" which has related things so it might make sense to move all of that under "ci".

"build" and "release" are also confusing connotations because those are often used to indicate build artifact or intermediate output directories.

**Pull request closed without merging**
