### PR TITLE
Greenplum's node instance must listen on IPV4 address

### PR DESCRIPTION
**Pull request by dreamedcheng**
When starting the cluster, there is a potential that a segment listen on a IPV4 address failed, but succeed on IPV6 address, so the segment could start as normal. However,  gang creation will use the IPV4 address from `gp_segment_configuration`, which results in normal MPP execution and other cluster wide services like FTS, GDD and DTX recover process couldn't work normally, and after the startup the FTS will mark this segment down. For the case initialize a new cluster, the cluster will hang in DTX recovery phase.

For the coordinator, if it listens on IPV6 address instead of IVP4 address, some python maintainace utility tools may can't work, this is because some of them will use `DbURL` to connect the cluster, where the hostname it use is IPV4.

So we'd better let the postmaster exit during the start process when it can't listen on IPV4 address.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by Aegeaner** [comment]
In theory, the addresses from `gp_segment_configuration` can be IPv6.

**Comment by dreamedcheng** [comment]
> In theory, the addresses from `gp_segment_configuration` can be IPv6.

OK，then maybe we need a GUC or something eslse to tell the postmaster, which type of address `gp_segment_configuration` is using.

**Comment by adam8157** [comment]
Thanks for the proposal. Which Python maintenance utility tools were you referring to?

To me, there are two issues to confirm or implement:
1, Greenplum and its utilities could run and be maintained in a pure IPv6 environment, this is supposed to be a must.
2, in a hybrid network environment, some users want to force the Greenplum only running on IPv4 or IPv6.

**Comment by dreamedcheng** [comment]
> Which Python maintenance utility tools were you referring to?

After a careful check, `DbURL` may connect cluster by using `hostname` in `gp_segment_configuration` or local socket. Not only IPV4 or IPV6.





> Have you tried using the IPv6-only hostnames to initialize the Greenplum cluster?

I tried initialize a cluster by only using IPV6, it seems work normally. 

So for the issue I mentioned above, we may need GUC to tell postmaster chich address `gp_segment_configuration` is using. If the cluster can't listen on the address successfully, we should throw an error in advance.

**Comment by adam8157** [comment]
> > Which Python maintenance utility tools were you referring to?
> 
> After a careful check, `DbURL` may connect cluster by using `hostname` in `gp_segment_configuration` or local socket. Not only IPV4 or IPV6.
> 
> > Have you tried using the IPv6-only hostnames to initialize the Greenplum cluster?
> 
> I tried initialize a cluster by only using IPV6, it seems work normally.

Great.

> So for the issue I mentioned above, we may need a GUC to tell postmaster which address `gp_segment_configuration` is using. If the cluster can't listen on the address successfully, we should throw an error in advance.

I don't think so, if you want to have an IPv4-only cluster, just use IPv4-only hostnames to initialize the cluster. Instead, if the hostname maps to both IPv4 and IPv6 addresses, it implies that connecting to any address would be acceptable.

**Comment by dreamedcheng** [comment]
> Instead, if the hostname maps to both IPv4 and IPv6 addresses, it implies that connecting to any address would be acceptable

But for now, `gp_segment_configuration` only stores one kind address, if it stores IPV4 address but some node bind IPV4 failed, the problem I mentioned in this PR appeared.

**Comment by adam8157** [comment]
> But for now, `gp_segment_configuration` only stores one kind address, if it stores IPV4 address but some node bind IPV4 failed but succeed on IPV6, the problem I mentioned in this PR appears.

Oh, have you did some related modifications? `gp_segment_configuration` only stores hostnames, for instance:

```
gpadmin=# select * from gp_segment_configuration ;
 dbid | content | role | preferred_role | mode | status | port  | hostname | address |                    datadir
------+---------+------+----------------+------+--------+-------+----------+---------+------------------------------------------------
    1 |      -1 | p    | p              | n    | u      | 15432 | buggy    | buggy   | /home/gpadmin/greenplum-db-data/gpseg-1
    2 |       0 | p    | p              | n    | u      | 40000 | buggy    | buggy   | /home/gpadmin/greenplum-db-data/primary/gpseg0
    3 |       1 | p    | p              | n    | u      | 40001 | buggy    | buggy   | /home/gpadmin/greenplum-db-data/primary/gpseg1
    4 |       2 | p    | p              | n    | u      | 40002 | buggy    | buggy   | /home/gpadmin/greenplum-db-data/primary/gpseg2
(4 rows)
```

**Comment by dreamedcheng** [comment]
> `gp_segment_configuration` could only store hostnames,
```
Behind this `hostname`, it corresponds a IPV4 address or a IPV6 address (specified by `/etc/hosts`), can't be both of them.
 dbid | content | role | preferred_role | mode | status | port |  hostname  |  address   
------+---------+------+----------------+------+--------+------+------------+------------
    1 |      -1 | p    | p              | n    | u      | 7000 | localhost6 | localhost6
    3 |       1 | p    | p              | s    | u      | 7003 | localhost6 | localhost6
    6 |       1 | m    | m              | s    | u      | 7006 | localhost6 | localhost6
    4 |       2 | p    | p              | s    | u      | 7004 | localhost6 | localhost6
    7 |       2 | m    | m              | s    | u      | 7007 | localhost6 | localhost6
    8 |      -1 | m    | m              | s    | u      | 7001 | localhost6 | localhost6
    2 |       0 | p    | p              | s    | u      | 7002 | localhost6 | localhost6
    5 |       0 | m    | m              | s    | u      | 7005 | localhost6 | localhost6
(8 rows)
```
image

As we can see from  the above snaphot, when `ping localhost6` it pings the local IPV6 (`::1`) address.

**Comment by adam8157** [comment]
It actually could have both as below, and I thought you had both.

```
# /etc/hosts
::1 localhost
127.0.0.1 localhost
```

Since you had only the IPv6 hostname and address, why did it fall back to IPv4? I'm confused.

**Comment by dreamedcheng** [comment]
> Since you had only the IPv6 hostname and address, why did it try IPv4 and fail? I'm confused.

My environment has both IPV4 and IPV6 address, but one of segment's IPV4 port was occupied by another APP, so when I initialize the cluster, the new cluster will hang in dtx recovery. `gp_segment_configuration`'s hostname is a IPV4 address.

So my point is is `gp_segment_configuration` is set to a IPv4 address, we must let all node bind on IPv4 address success, or  throw an error in advance to avoid the hang.

**Comment by adam8157** [comment]
> So my point is when `gp_segment_configuration` is set to a IPv4 address, we must let all node bind on IPv4 address success, or throw an error in advance to avoid the hang.

Ah, I got your point, and likewise if `gp_segment_configuration` is set to an IPv6 address, we must let the node bind on IPv6 addresses, or throw an error.

This PR assumes that IPv4 is necessary and does not address IPv6, it needs more work, right? Achieving a complete solution might be challenging since Greenplum has no `gp_segment_configuration` on the segments.

I would suggest closing this and raising another PR or an issue.

```
$ PGOPTIONS='-c gp_role=utility' psql -p 40001
psql (12.12)
Type "help" for help.

gpadmin=# select * from gp_segment_configuration;
 dbid | content | role | preferred_role | mode | status | port | hostname | address | datadir
------+---------+------+----------------+------+--------+------+----------+---------+---------
(0 rows)
```

**Comment by dreamedcheng** [comment]
> This PR assumes that IPv4 is necessary and does not address IPv6, it needs more work, right?

Yes.

And I think that a possible way to solve it is to introduce a GUC, to tell all node what kind of IP address that `gp_segment_configuration` is used when initializing the cluster.

**Comment by dreamedcheng** [comment]
I noticed that a new PR is raised to solve this issue, closing this one.

**Pull request closed without merging**
