### PR TITLE
Upgrade docker Open JDK to 1.8

### PR DESCRIPTION
**Pull request by lavjain**

### CODE REVIEW

**Comment by Eulerizeit** [comment]
This seems to have broken MADlib on 5.x.  Actually commit d66f396d9b which seems to be this.

@fmcquillan99 @jingyimei

**Comment by jingyimei** [comment]
@Eulerizeit Thanks to let us know. We will look into this very soon.

**Comment by lavjain** [comment]
@jinyimei @fmcquillan99 @Eulerizeit Please let me know which test is breaking so I can take a look.

**Comment by jingyimei** [comment]
@lavjain We already pushed fix for this.

**Pull request merged**
