### PR TITLE
Allow setting direct dispatch info if predicate on  gp_segment_id for…

### PR DESCRIPTION
**Pull request by QingMa-gp**
Backport **https://github.com/greenplum-db/gpdb/pull/10690** from master branch. 

… planner.

This commit implements the same feature for planner as the PR
https://github.com/greenplum-db/gpdb/pull/10679.

This commit does not implement the group-by feature in PR 10679.
The following commit message is almost the same as PR 10679.

This approach special cases gp_segment_id enough to include the column
as a distributed column constraint. It also updates direct dispatch info
to be aware of gp_segment_id which represents the raw value of the
segment where the data resides. This is different than other columns
which hash the datum value to decide where the data resides.

After this change the following DDL shows Gather Motion from 2 segments
on a 3 segment demo cluster.

```
CREATE TABLE t(a int, b int) DISTRIBUTED BY (a);
EXPLAIN SELECT gp_segment_id, * FROM t WHERE gp_segment_id=1 or gp_segment_id=2;
                                    QUERY PLAN
-----------------------------------------------------------------------------------
 Gather Motion 2:1  (slice1; segments: 2)
   ->  Seq Scan on t
         Filter: ((gp_segment_id = 1) OR (gp_segment_id = 2))
 Optimizer: Postgres query optimizer
(4 rows)
```

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ashwinstar** [comment]
This issue helps to bring planner functionality which was shipped for orca. In general, that's helpful for the master branch. For the STABLE branch would love to know if really compelling reason exists to do this if ORCA already supports it. Are there cases where fallback to planner will happen and this fix will come into play?

@bradfordb-vmware given you had opened the github issue #13202 originally would like to seek your input if the use cases you were looking for are fulfilled by ORCA fix or there are cases where planner kicks-in and having same fixed for planner will help you/team?

This would help us to decide if really commit this to STABLE or leave it out for GPDB6.

**Comment by bradfordb-vmware** [comment]
@ashwinstar I believe parallel retrieve cursors are only supported by planner.

**Comment by ashwinstar** [comment]
> @ashwinstar I believe parallel retrieve cursors are only supported by planner.

Okay, if this in context with parallel retrieve cursors then seems fine. I missed the connection.

**Comment by QingMa-gp** [comment]
Thanks for your review.

**Pull request merged**
