### PR TITLE
Fix hstore

### PR DESCRIPTION
**Pull request by hlinnaka**
This fixes a couple of bugs that were causing crashes with hstore, and adjusts regression test output to match what you get on Greenplum. The hstore regression tests now pass.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@Eulerizeit, this doesn't change the makefile, so 'hstore' still won't get compiled with the standard build. Want me to change that too?

**Comment by Eulerizeit** [comment]
Let me look and see if we need to wrap anything else from contrib in and we
can do it all at once.

Rob

**Comment by hlinnaka** [comment]
Ok, added a commit to also hook hstore into the standard make targets, so that it's built and installed, and regression tests are run, by default.

**Comment by Eulerizeit** [comment]
@mkiyama @dyozie This is a new feature in 5.0

**Comment by dyozie** [comment]
Thanks the heads up - I'll create an area in the reference docs where we can start porting over the /contrib docs from postgres.

**Comment by ivannovick** [comment]
So HSTORE works in GPDB 5?  That would be AWESOME!

**Comment by Eulerizeit** [comment]
Ivan,

It will the next release.

**Comment by dyozie** [comment]
Do we know what other contrib modules are going to be available in the next
release?  And by "next release" I'm assuming we're talking about the
proposed GA tag due the end of this week.

**Comment by Eulerizeit** [comment]
@dyozie to my knowledge this is the only one. There are a few others being discussed but I don't know if any action is being taken on any of them.

**Comment by hlinnaka** [comment]
On 08/28/2017 07:35 PM, Robert Eckhardt wrote:
> @dyozie to my knowledge this is the only one. There are a few others being discussed but I don't know if any action is being taken on any of them.

Looking at the makefile, these are the ones we build and install:

         $(MAKE) -C contrib/xlogdump $@
         $(MAKE) -C contrib/changetrackingdump $@
         $(MAKE) -C contrib/formatter $@
         $(MAKE) -C contrib/formatter_fixedwidth $@
         $(MAKE) -C contrib/fuzzystrmatch $@
         $(MAKE) -C contrib/extprotocol $@
         $(MAKE) -C contrib/dblink $@
         $(MAKE) -C contrib/gp_sparse_vector $@
         $(MAKE) -C contrib/gp_distribution_policy $@
         $(MAKE) -C contrib/gp_inject_fault $@
         $(MAKE) -C contrib/gp_internal_tools $@
         $(MAKE) -C contrib/gp_cancel_query $@
         $(MAKE) -C contrib/indexscan $@
         $(MAKE) -C contrib/pg_upgrade_support $@
         $(MAKE) -C contrib/pg_upgrade $@
         $(MAKE) -C contrib/pgcrypto $@

(and now hstore is being added to that)

Of those, "dblink", "pgcrypto", "fuzzystrmatch", and "hstore" are 
PostgreSQL contrib modules. The rest are GPDB additions.

I'm not 100% if there's some additional list or filter on what actually 
gets packaged into the installers, though.

- Heikki

**Comment by dyozie** [comment]
Thanks - of those postgres modules you mention we already cover
fuzzstrmatch, dblink, and of course pgcrypto.

Would be great to get some insight into the other modules.  I know many of
them are covered in documentation, but hopefully things like pg_upgrade*
aren't being built in just yet...

**Comment by dyozie** [comment]
FYI - docs addition is in https://github.com/greenplum-db/gpdb/pull/3081

**Pull request merged**
