### PR TITLE
Remove filespaces. (for walreplication branch)

### PR DESCRIPTION
**Pull request by hlinnaka**
Remove the concept of filespaces, revert tablespaces to work the same as
in upstream.

There is some leftovers in management tools. I don't know how to test all
that, and I was afraid of touching things I can't run. Also, we may need
to create replacements for some of those things on top of tablespaces, to
make the management of tablespaces easier, and it might be easier to modify
the existing tools than write them from scratch. (Yeah, you could always
look at the git history, but still.)

Per the discussion on gpdb-dev mailing list, the plan is to cherry-pick
commit 16d8e594ac from PostgreSQL 9.2, to make it possible to have a
different path for a tablespace in the primary and its mirror. But that's
not included in this commit yet.

TODO: Make temp_tablespaces work.
TODO: Make pg_dump do something sensible, when dumping from a GPDB 5 cluster
that uses filespaces. Same with pg_upgrade.

Discussion: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/sON4lraPEqg/v3lkM587BAAJ

### CODE REVIEW

**Comment by hlinnaka** [comment]
There are a few remaining issues with this commit worth noting:

* temp_tablespaces doesn't work yet. It was introduced in 8.3, but we were not able to merge it properly during the 8.3 merge, because all the filespace stuff was in the way. Once filespaces are gone, we'll need to fix that.

* ALTER TABLE SET TABLESPACE, on an AO table, to move an AO table from one tablespace to another, is broken on the walreplication branch. The code to do it is commented out, with a WALREP_FIXME comment. There are apparently no regression tests for that in installcheck-world, because it's green. We'll need to fix that, and add some tests for it.

This commit doesn't do anything about those things. I think it's best to deal with them after `walreplication` has been merged into `master`, simply because that commit to merge it is going to enormous anyway. Better to deal with issues like these separately afterwards, where possible.

**Comment by Eulerizeit** [comment]
@hlinnaka The 2 things that need to be added, in addition to your comments are:
1. prepend of the segment name in order to support multiple segments per host. 
1. a catalog table, as discussed by Scott in the email thread.

**Comment by hlinnaka** [comment]
On 02/01/18 20:23, Robert Eckhardt wrote:
> @hlinnaka The 2 things that need to be added, in addition to your comments are:
> 1. prepend of the segment name in order to support multiple segments per host.

Added this, and pushed to the walreplication branch.

> 2. a catalog table, as discussed by Scott in the email thread.

I did not implement this as such. However, the gp_segment_configuration 
table now contains "datadir" column. That points to the location of the 
main data directory. There is nothing to store the paths to tablespaces 
on different nodes. The assumption is that the path to a tablespace is 
the same on every node. (If you have multiple segments on a single host, 
they won't clash with each other because of 1.)

Some of the tools need to be taught how to deal with tablespaces. For 
example, when you create a new mirror, with a new dbid, pg_basebackup 
doesn't know about the convention that the dbid is included in the path. 
I added a WALREP_FIXME comment about that one, but there are probably 
other similar cases. We'll find out about them as we add tests.

- Heikki

**Comment by Eulerizeit** [comment]
@hlinnaka Should this be closed? I believe you pushed this already.

**Comment by hlinnaka** [comment]
Yep, pushed already, closing.

**Pull request closed without merging**
