### PR TITLE
Remove check for NOT NULLable column from ORCA translation of INSERT values.

### PR DESCRIPTION
**Pull request by hlinnaka**
When creating an ORCA plan for "INSERT ... (<col list>) VALUES (<values>)"
statement, the ORCA translator performed NULL checks for any columns not
listed in the column list. Nothing wrong with that per se, but we needed
to keep the error messages in sync, or we'd get regression test failures
caused by different messages. To simplify that, remove the check from
ORCA translator, and rely on the execution time check.

We bumped into this while working on the 9.3 merge, because 9.3 added
DETAIL to the error message in executor:

```
postgres=# create table notnulls (a text NOT NULL, b text NOT NULL);
CREATE TABLE
postgres=# insert into notnulls (a) values ('x');
ERROR:  null value in column "b" violates not-null constraint
postgres=# insert into notnulls (a,b) values ('x', NULL);
ERROR:  null value in column "b" violates not-null constraint  (seg2 127.0.0.1:40002 pid=26547)
DETAIL:  Failing row contains (x, null).
```

Doing this now will avoid that inconsistency in the merge.

One little difference with this is that EXPLAIN on an insert like above
now works, and you only get the error when you try to execute it. Before,
with ORCA, even EXPLAIN would throw the error.

### CODE REVIEW

**Comment by d** [comment]
> the query is correct, albeit doomed to fail

The cost of execution is higher in Greenplum (than Postgres, given the cost of dispatch and multi-slice plans), especially in the context of a query that's supposed to fail.

I'm not opposed to minimizing the difference, I was definitely tripped by this during 9.2 merge. But I can see the merits of this.

**Comment by d** [comment]
What happens if the `NOT NULL` constraint is not written using the special `NOT NULL` syntax, but in a `CHECK (a IS NOT NULL)` constraint? Wouldn't ORCA still trip that?

**Comment by vraghavan78** [comment]
@hlinnaka why not change the message to match it with the one generated by the executor?

**Comment by hlinnaka** [comment]
On 20/09/18 23:42, Jesse Zhang wrote:
> What happens if the |NOT NULL| constraint is not written using the 
> special |NOT NULL| syntax, but in a |CHECK (a IS NOT NULL)| constraint? 
> Wouldn't ORCA still trip that?
No, ORCA doesn't do these plan-times checks for CHECK constraints. The 
NOT NULL column, where that column was omitted from the column list, was 
the only exception AFAICS.

- Heikki

**Comment by hlinnaka** [comment]
On 20/09/18 23:52, Venkatesh Raghavan wrote:
> @hlinnaka <https://github.com/hlinnaka> why not change the message to 
> match it with the one generated by the executor?
That would be more work. We'd need to construct the "Failing row 
contains" error detail row, similarly to what 
ExecBuildSlotValueDescription() does. And we would need to keep the 
messages in sync in the future, too. Removing code is easier than adding 
more.

- Heikki

**Comment by hlinnaka** [comment]
Pushed, thanks for the reviews!

**Pull request merged**
