### PR TITLE
Default gp_external_enable_filter_pushdown GUC to true and fixes to handle both planner & orca qualifiers

### PR DESCRIPTION
**Pull request by denalex**
Co-authored-by: Shivram Mani <smani@pivotal.io>
Co-authored-by: Alex Denissov <adenissov@pivotal.io>

### CODE REVIEW

**Comment by denalex** [comment]
@hlinnaka -- thanks for the review, we figured this problem already in our tests, updated the default value in the config array in an additional commit, please take a quick look.

**Comment by hlinnaka** [comment]
Better now.

Please also update the default value in the docs, in gpdb-doc/dita/ref_guide/config_params/guc-list.xml.

**Comment by shivzone** [comment]
@leskin-in -- we want to make predicate pushdown a default feature of Greenplum, so this PR enables that. Additionally, now ORCA will optimize queries with external tables, but the structure of the qualifiers that it sends is different from that of planner and causes parsing failures for PXF serialization logic as it was written. So we had to change the way we add extra AND operators between quals at the root level that are usually omitted by the planner (and not ORCA).

Can you please test PXF JDBC predicate pushdown with this logic to make sure there are no corner cases that are not accounted for ? Please let us know so that we can commit this PR. No changes on PXF side are required.

**Comment by leskin-in** [comment]
@shivzone I'll do it ASAP.

**Comment by leskin-in** [comment]
A set of tests was conducted on Oracle, PostgreSQL and MSSQL external databases. The pushdown on GPDB with default planner works the same way as before the new fixes.

**Pull request merged**
