### PR TITLE
First part of error reporting cleanup

### PR DESCRIPTION
**Pull request by danielgustafsson**
The Greenplum specific error handling via `ereport()`/`elog()` calls was in need of a unification effort as some parts of the code was using a different messaging style to others (and to upstream). This aims at bringing many of the GPDB error calls in line with the upstream error message writing guidelines and thus make the user experience of Greenplum more consistent.

The main contributions of this patch are:

* `errmsg()` messages shall start with a lowercase letter, and not end with a period. `errhint()` and `errdetail()` shall be complete sentences starting with capital letter and ending with a period. This attempts to fix this on as many `ereport()` calls as possible, with too detailed `errmsg()` content broken up into details and hints where possible.

* Reindent `ereport()` calls to be more consistent with the common style used in upstream and most parts of Greenplum:
```C
	ereport(ERROR,
			(errcode(<CODE>),
			 errmsg("short message describing error"),
			 errhint("Longer message as a complete sentence.")));
```
* Avoid breaking messages due to long lines since it makes grepping for error messages harder when debugging. This is also the de facto standard in upstream code.

* Convert a few internal error `ereport()` calls to `elog()`. There are no doubt more that can be converted, but the low hanging fruit has been dealt with. Also convert a few `elog()` calls which are user facing to `ereport()`.

* Update the testfiles to match the new messages.

Spelling and wording is mostly left for a follow-up commit, as this was getting big enough as it was. The most obvious cases have been handled but there is work left to be done here.

This PR will no doubt run red in the pipeline as I'm sure I've missed to update expected test output, but I will shamelessly offload running ICW over and over to find these to the PR pipeline.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
It should be noted that I skipped over the table distribution NOTICEs since they are so prevalent in the test files. I do want to fix those as well but in a separate PR.

**Comment by Eulerizeit** [comment]
On Fri, Nov 30, 2018, 9:47 AM Ivan Novick <notifications@github.com wrote:

> @danielgustafsson <https://github.com/danielgustafsson> one thing i
> wanted to do if possible for GP6 is remove the EMAIL and SNMP log alert
> functionality from the code completely. Do you know how hard that would be
> from a coding perspective? From user perspective IMO we should not have
> this as it is divergent from PostgreSQL engine and we have outer DB tools
> that can do alerting. Whats your thoughts on this?
>
For the next few months Daniel is going to be focused on recursive CTEs.

Rob

**Comment by ashwinstar** [comment]
>> Convert a few internal error ereport() calls to elog(). There are no doubt more that can be converted, but the low hanging fruit has been dealt with. Also convert a few elog() calls which are user facing to ereport().

Okay, but not to thrilled with that change. As discussed previously on some other PR as well for ERROR and above its fine to use elog for internal messages. But its always efficient to use ereport for debug levels, so in those terms becomes fuzzy mix. So, ideally new usage of elog() should be completely avoided and `ereport()` should be defacto used everywhere. Again upstream didn't do good job as complete removing the `elog()` interface, so even if it exists the usage should be minimized.

**Comment by ashwinstar** [comment]
On Fri, Nov 30, 2018 at 10:25 AM Jacob Champion <notifications@github.com>
wrote:

> So, ideally new usage of elog() should be completely avoided and ereport()
> should be defacto used everywhere.
>
> I don't think that's an appropriate blanket statement -- from upstream
> <https://www.postgresql.org/docs/11/error-message-reporting.html>:
>
> Therefore, elog should be used only for internal errors and low-level
> debug logging. Any message that is likely to be of interest to ordinary
> users should go through ereport. Nonetheless, there are enough internal
> “cannot happen” error checks in the system that elog is still widely used;
> it is preferred for those messages for its notational simplicity.
>
> I.e. these "something is seriously broken" cases are exactly what we need
> to be using elog() for.
>
Documentation seems to talk more from the perspective of end-result it
would have between the two and not from the internal working/implementation
of the two.

The elog and ereport code differ as ereport does upfront checking based on
LOG_LEVEL if should perform any further processing of parsing further
arguments/buffer allocations/function calls.
Whereas elog irrespective of LOG_LEVEL might waste a lot of time on
preparing to log the message which we never end up logging (DEBUG levels).

This simple example proofs/clarifies it.
========================
> char* TestFunction(void)
> {
> static char buffer[200];
>
> elog(INFO, "I am in TestFunction");
>
> return buffer;
> }
>
> elog(DEBUG5, "%s", TestFunction()); <<==== This calls the TestFunction
whenever this statement is encountered irrespective of LOG_LEVEL. Might not
log what we pass though later based on LOG_LEVEL check.

> ereport(DEBUG5,
> (errcode(ERRCODE_GP_INTERNAL_ERROR),
> errmsg("%s ",
> TestFunction())));  <<========= This calls the TestFunction only if
LOG_LEVEL is equal or lower than DEBUG5, else does not perform anything. NO
function call / string processing etc..
========================

The link (http://archives.postgresql.org/pgsql-hackers/2003-04/msg00796.php)
justifies that ereport was optimized in postrgres from its initial version
to skip the rest of the work completely if message will not be displayed.
The difference comes based on the way macro is defined for the two.
For ereport, errstart is called at top level first (not inside any wrapper
function) and only based on its result errfinish is called whereas for elog
a wrapper function is executed inside which errstart and errfinish are
called. Hence, any functions used in arguments are evaluated.

Based on that using elog() for debug messages is extra work in production
system, which if ereport() is used gets avoided. Unless debug messages are
guarded with GUCs to avoid calls to them.

Thoughts?

**Comment by danielgustafsson** [comment]
I think `elog()` should be used more or less exclusively for `ERROR` and higher, which is where it makes perfect sense to use it. `DEBUGX` should use `ereport()` for the very reason that Ashwin points out. Inspecting the (very long) diff shows that's exactly what I've done.

That being said, what I'd prefer doing is to *remove* a crapton of all the GPDB added `DEBUGx` messages as they in parts have been sprinkled like there's no tomorrow.. but I wonder how we can quantify which of them makes sense to keep?

**Comment by danielgustafsson** [comment]
> @danielgustafsson one thing i wanted to do if possible for GP6 is remove the EMAIL and SNMP log alert functionality from the code completely. Do you know how hard that would be from a coding perspective?

See PR #6384 which implements this.

**Comment by danielgustafsson** [comment]
Pushed a rebase on top of todays master

**Comment by danielgustafsson** [comment]
Pushed to master following a green PR run, thanks for review all!

**Pull request closed without merging**
