### PR TITLE
Add minirepro to let user dump minimal set of DDL and statistics for a given query

### PR DESCRIPTION
**Pull request by hsyuan**
As a Database User, I should be able to  dump the DDL and Statistics Information for a given query so I don't have to  dump a large GPDB file.

GIVEN I am a Database User
WHEN I run ```minirepro database-name -q sql-file-name -f output-file-name```
THEN I should get the DDL and statistics info for the tables and views accessed in that query

### CODE REVIEW

**Comment by yydzero** [comment]
Will this tool work if without ORCA? If not, better to add some comment or error message.

**Comment by hsyuan** [comment]
@yydzero Sure, I will add error out messages.

**Comment by hlinnaka** [comment]
I don't see any reason why this should depend on ORCA. All the functions that the server-side function calls are plain Postgres/GPDB functions.

**Comment by entong** [comment]
Agreed on the dependency of Orca. This could be a useful tool even if gpdb is not compiled with Orca. @hlinnaka , any idea where we can put the dumpQuery utility function? It's not very 'built-in' so we probably won't put it in pg_proc. There are some utility functions in gp_toolkit schema, which are loaded from a library during startup. Is that ok?

**Comment by hlinnaka** [comment]
On 10/12/15 20:43, Entong Shen wrote:
> Agreed on the dependency of Orca. This could be a useful tool even if
> gpdb is not compiled with Orca. @hlinnaka , any idea where we can put
> the dumpQuery utility function? It's not very 'built-in' so we
> probably won't put it in pg_proc. There are some utility functions in
> gp_toolkit schema, which are loaded from a library during startup. Is
> that ok?

Works for me.

- Heikki

**Comment by entong** [comment]
Looks good after the revision. Great work Haisheng!

**Comment by hlinnaka** [comment]
I think my last comments got lost when you rebased, so I'm copying it back here:

On 19/12/15 00:43, Haisheng Yuan wrote:
> Actually I wrote another branch exactly the same with your idea that let
> the server function return the relation OIDs. But considering that dumping
> the query object is a well defined functionality and by preserving the
> intact query it enables a lot of possibilities that can be handled by
> external tools.

The pretty-printed output format isn't all that well-defined. In 
practice, it hasn't changed for ages, but it shouldn't really be 
considered a stable API to write applications against. Moreover, if I'm 
reading this code correctly, it's not really parsing the format the way 
it's supposed to be parsed, but it's relying on the whitespace being 
arranged in a particular way.

> I agree that adding it as a backend function would avoid the extra .so and
> such. The reason we took that approach is that we want to back port it to
> 4.3 branch to support enterprise customers. By putting it in an so file,
> enterprise customer can start benefiting from this tool without a catalog
> upgrade. They only need to load the UDF after they do a minor version
> upgrade (i.e. binary swap).

Let's do what makes the most sense, for 5.0, and figure out what to do 
with the back-branch separately.

If you want to keep the code between 4.3 and 5.0 as close as possible, 
we could add the function into the server in 4.3 too, without creating 
the catalog entry for it. The minirepro tool could then run the CREATE 
FUNCTION before calling it, if the catalog entry doesn't exist yet. Or 
you could use the CREATE VIEW trick.

Hmm, one more idea on how to implement this without any specific backend 
support: Begin a transaction, run EXPLAIN on the query, and query 
pg_locks to see which relations have been locked for the transaction. 
Those relations are the ones that you need to dump. That actually seems 
pretty simple.

**Pull request closed without merging**
