### PR TITLE
remove parallel StreamBitmap scan FIXME

### PR DESCRIPTION
**Pull request by SmartKeyerror**
Thanks for working with @haolinw, Greenplum will not support parallel scan recently, so we can change
all the FIXME about parallel StreamBitmap scan to TODO tag, since it bases on the parallel scan.

No more tests need, this PR just change comments.

### CODE REVIEW

**Comment by haolinw** [comment]
I'm wondering is that OK to resolve this series of parallel-scan-aware fixmes (also including parallel bitmap heap scan and parallel index building) like this by simply removing GPDB_12_MERGE_FIXME keyword for do-not-plan-to-support in GPDB,
or keep FIXME there but mark it as something like feature-not-required for not counting into FIXME to do list ?
cc @ashwinstar and @kainwen

**Comment by SmartKeyerror** [comment]
> I'm wondering is that OK to resolve this series of parallel-scan-aware fixmes (also including parallel bitmap heap scan and parallel index building) like this by simply removing GPDB_12_MERGE_FIXME keyword for do-not-plan-to-support in GPDB, or keep FIXME there but mark it as something like feature-not-required for not counting into FIXME to do list ? cc @ashwinstar and @kainwen

In my opinion, I'm inclined to remove GPDB_12_MERGE_FIXME keyword for do-not-plan-to-support in GPDB, and keep this feature to another TODO-List.

**Comment by wenwangBJ** [comment]
Suggest to change GPDB_12_MERGE_FIXME  to GPDB_12_MERGE_TODO. Marked it as an another keyword of unsupported feature in the code for easy management and identification.

**Comment by SmartKeyerror** [comment]
As @wenwangBJ recommended, change GPDB_12_MERGE_FIXME to GPDB_12_MERGE_TODO.

**Review by interma — APPROVED** [review]
LGTM

**Comment by ashwinstar** [comment]
Sorry, for being late to respond. I feel having `FEATURE` word would be helpful for future. So, what do you all thing about `GPDB_12_MERGE_FEATURE_TODO` or better align with `ERRCODE_FEATURE_NOT_SUPPORTED` `GPDB_12_MERGE_FEATURE_NOT_SUPPORTED`

**Comment by wenwangBJ** [comment]
Thanks, new marked is a better explain for the unsupported feature in the code.

In order to unify the keyword, and easier to search for them later, so we can change the "GPDB_12_MERGE_FIXME" to "GPDB_12_MERGE_FEATURE_TODO" align with "GPDB_12_MERGE_FEATURE_NOT_SUPPORTED".

**Review by haolinw — APPROVED** [review]

**Pull request merged**
