### PR TITLE
Allow user to set num segs, max connects in gpdemo

### PR DESCRIPTION
**Pull request by amilkh**
--$DEFAULT_QD_MAX_CONNECT---
Can be set as an environment variable before calling make cluster.
Default value is 25.
We added this to allow setting it to 250 for TINC tests.

---$NUM_PRIMARY_MIRROR_PAIRS---
Can be set as an environment variable before calling make cluster.

gpdemo by default creates 3 primaries and 3 mirrors.  With this
change, users can set the environment variable
$NUM_PRIMARY_MIRROR_PAIRS to another value such as 2 to make gpdemo
create 2 primaries and 2 mirrors instead.

----
This is the tests we have done:
1. Run make cluster in normal operation and validate clusterConfigFile, stdout of segment ports
2. Run `NUM_PRIMARY_MIRROR_PAIRS=2 make cluster` and validate clusterConfigFile, stdout of segment ports

### CODE REVIEW

**Comment by amilkh** [comment]
@andreasscherbaum, @Chibin, @jimmyyih any ideas?

**Comment by asimrp** [comment]
+1

**Comment by ascherbaum-pivotal** [comment]
+1

**Comment by amilkh** [comment]
Merged to master:
91ca59147137b60c61b133b513d2feef05c1f100

**Pull request closed without merging**
