### PR TITLE
Add function for throwing ereport-like errors from gpopt code.

### PR DESCRIPTION
**Pull request by hlinnaka**
This allows us to have the exact same error message and hint for errors,
as what the traditional planner produces. That makes testing easier, as
you don't need to have a different expected output file for ORCA and
non-ORCA. And allows for more structured errors anyway.

Use the new function for the case of trying to read from a WRITABLE
external table. There was no test for that previously. While we're at it,
re-word the error message and change the error code to follow the Postgres
error message style guide.

### CODE REVIEW

**Comment by ashwinstar** [comment]
Not a review due to lack go knowledge in this area, but definitely big +1 for making the error message consistent so as to get us closer to have same answer files for orca and with orca.

**Comment by hlinnaka** [comment]
On 03/06/2017 08:25 PM, Ashwin Agrawal wrote:
> Not a review due to lack go knowledge in this area, but definitely
> big +1 for making the error message consistent so as to get us closer
> to have same answer files for orca and with orca.

Yeah. I tried to go further, so that we could have the same message also 
for NOT NULL and CHECK constraints. Currently you get:

ERROR:  null value in column "id" violates not-null constraint  (seg1 
127.0.0.1:40001 pid=31309)

vs

ERROR:  One or more assertions failed  (seg1 127.0.0.1:40001 pid=31309)
DETAIL:  Not null constraint for column id of table foo was violated

Unfortunately, that was more complicated. Those error messages are 
constructed deep in bowels of ORCA. I looked at adding fields to 
CException class, for the table and constraint names, so that we could 
re-construct the error message we actually want in the translator code, 
but it's a bit more work than I'm willing to pick up right now. That 
would be really nice, though, there are a lot of those error message 
differences in the regression suite.

- Heikki

**Comment by hlinnaka** [comment]
On 03/06/2017 10:31 PM, Heikki Linnakangas wrote:
> On 03/06/2017 08:25 PM, Ashwin Agrawal wrote:
>> Not a review due to lack go knowledge in this area, but definitely
>> big +1 for making the error message consistent so as to get us closer
>> to have same answer files for orca and with orca.
>
> Yeah. I tried to go further, so that we could have the same message also
> for NOT NULL and CHECK constraints. Currently you get:
>
> ERROR:  null value in column "id" violates not-null constraint  (seg1
> 127.0.0.1:40001 pid=31309)
>
> vs
>
> ERROR:  One or more assertions failed  (seg1 127.0.0.1:40001 pid=31309)
> DETAIL:  Not null constraint for column id of table foo was violated
>
> Unfortunately, that was more complicated. Those error messages are
> constructed deep in bowels of ORCA. I looked at adding fields to
> CException class, for the table and constraint names, so that we could
> re-construct the error message we actually want in the translator code,
> but it's a bit more work than I'm willing to pick up right now. That
> would be really nice, though, there are a lot of those error message
> differences in the regression suite.

Oh, I forgot what my main thought with this was. Adding gpdb-dev, as 
this is more a general discussion:

Actually, it's not clear to me why ORCA bothers to add those Assert 
nodes for NOT NULL and CHECK constraints in the first place. The 
executor is prepared to check, and does for the Postgres planner, we've 
just disabled that for ORCA because ORCA puts those checks in the plan 
itself as Assert nodes. But I don't see the advantage of doing it 
differently for ORCA.

So, why don't we modify ORCA to not insert those Assert nodes, and let 
the executor enforce the constraints on INSERT/UPDATE, like it does in 
Postgres and like it does when ORCA is not used? That would fix the 
error message issue, too.

- Heikki

**Comment by vraghavan78** [comment]
@hlinnaka I can try to get the doc that explains the intent of why we added an assert node. Removing the assert node will be a more extensive change inside Orca. Let me get back to u on this one.

**Comment by hlinnaka** [comment]
Pushed. Let's continue the discussion on why ORCA adds Assert nodes for constraints on gpdb-dev.

**Pull request merged**
