### PR TITLE
Revert ic-proxy: enable ic-proxy in gpdb packages

### PR DESCRIPTION
**Pull request by tylarb**
The libuv source is in the build container, rather thank in a gcp
bucket. This commit reverts the logic of installing from a gcp bucket
and instead uses the libuv available in the build container image.

Co-authored-by: Tyler Ramer <tramer@vmware.com>
Co-authored-by: Kris Macoskey <kmacoskey@vmware.com>
Co-authored-by: Jamie McAtamney <jmcatamney@vmware.com>

### CODE REVIEW

**Comment by tylarb** [comment]
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-libuv_corrections

**Comment by kmacoskey** [comment]
It's possible to change where libuv is included inside the Docker image if that would help with the compiler search path.

**Comment by pivotal-ning-yu** [comment]
> It's possible to change where libuv is included inside the Docker image if that would help with the compiler search path.

That will be great.  It would make things easier to put libuv under the standard path: `/usr/local/include` for headers, a distribution-specific path for libs like `/usr/lib64` for centos & sles, `/usr/lib/x86_64-linux-gnu` for ubuntu.

Another approach is to keep that commit, but copy libuv 1.38 from the gcp prod bucket to dev bucket, currently there is only libuv 1.18 in the dev bucket.

**Comment by tylarb** [comment]
For now, I'll solve this by installing from the `/usr/local/` location to the distro appropriate destination in the build image, keeping both the "install_libuv" and "include_libuv" bash helper functions.

**Pull request merged**
