### PR TITLE
Fix building on OSX. Do not force compling strlcpy.c or strlcat.c

### PR DESCRIPTION
**Pull request by davecramer**

### CODE REVIEW

**Comment by film42** [comment]
I'm not sure if we can generally rule these out, though it would be nice if we could. Much cleaner than my approach.

This still doesn't solve the `error: "SSE4.2 instruction set not enabled"` problem.

My WIP: https://github.com/greenplum-db/gpdb/pull/18

**Comment by davecramer** [comment]
@film42 In general I think we can look to the PostgreSQL project of which GPDB is a descendant. Looking at their make files they do not force building these. As for SSE 4.2, again I think it would be prudent to look at how PostgreSQL is dealing with this.

**Comment by film42** [comment]
@davecramer That's a good point. I think it's a good idea to keep this a descendant of PostgreSQL, but I don't see that explicitly written anywhere. I think communication about the direction of GPDB could be a little clearer.

**Comment by hlinnaka** [comment]
Looks good to me. The SSE thing is indeed an orthogonal problem.

Yeah, it's definitely an important goal to keep the diff between upstream PostgreSQL and Greenplum as small as possible. So whenever there are multiple possible ways of doing X, and PostgreSQL also does X, we should always pick the way PostgreSQL does it. That will make merging with later PostgreSQL releases easier.

**Comment by edespino** [comment]
@davecramer, we have build breakages as a result of this change.  Here is an example of the linking error:

```
ccache gcc -O3 -funroll-loops -fargument-noalias-global -fno-omit-frame-pointer -g -finline-limit=1800 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-but-set-variable -Wno-address -I/data/royc/tools/curl/7.44.0/dist/rhel5_x86_64/include pg_config.o  -L../../../src/port -L../../../src/port -L/data/pulse2-agent/agents/agent1/work/GPDB-master-opt-l1/rhel5_x86_64/src/gpAux/ext/rhel5_x86_64/lib -Wl,--as-needed -Wl,-rpath,'/data/pulse2-agent/agents/agent1/work/GPDB-master-opt-l1/rhel5_x86_64/src/gpAux/greenplum-db-devel/lib',--enable-new-dtags -lpgport -lxml2 -lpam -lrt -lgssapi_krb5 -lcrypt -ldl -lm -L/data/royc/tools/curl/7.44.0/dist/rhel5_x86_64/lib -o pg_config
../../../src/port/libpgport.a(exec.o): In function `resolve_symlinks':
/data/pulse2-agent/agents/agent1/work/GPDB-master-opt-l1/rhel5_x86_64/src/src/port/exec.c:348: undefined reference to `strlcpy'
../../../src/port/libpgport.a(path.o): In function `get_home_path':
/data/pulse2-agent/agents/agent1/work/GPDB-master-opt-l1/rhel5_x86_64/src/src/port/path.c:673: undefined reference to `strlcpy'
../../../src/port/libpgport.a(path.o): In function `join_path_components':
/data/pulse2-agent/agents/agent1/work/GPDB-master-opt-l1/rhel5_x86_64/src/src/port/path.c:206: undefined reference to `strlcpy'
../../../src/port/libpgport.a(path.o): In function `make_relative_path':
/data/pulse2-agent/agents/agent1/work/GPDB-master-opt-l1/rhel5_x86_64/src/src/port/path.c:532: undefined reference to `strlcpy'
/data/pulse2-agent/agents/agent1/work/GPDB-master-opt-l1/rhel5_x86_64/src/src/port/path.c:552: undefined reference to `strlcpy'
../../../src/port/libpgport.a(path.o):/data/pulse2-agent/agents/agent1/work/GPDB-master-opt-l1/rhel5_x86_64/src/src/port/path.c:532: more undefined references to `strlcpy' follow
collect2: ld returned 1 exit status
```

**Pull request closed without merging**
