### PR TITLE
Revert SignalSomeChildren function back to Postgres 9.2 functionality

### PR DESCRIPTION
**Pull request by jimmyyih**
Currently, the walsender process is not properly stopped during
gpstop. The SignalSomeChildren function was changed in the Postgres
8.3 merge in commit 20ac0be199f07f75025311538cf15cd96ffe2108. It was
previously at a Postgres 9.2 state to support sending signals to
walsender as a part of our master and standby master replication.

Without this revert, there is a 2 minute delay before the postmaster sends a SIGQUIT to the walsender:
```
20170111:14:43:49:099551 gpstop:Jimmy:jyih-[INFO]:-Commencing Master instance shutdown with mode=fast
20170111:14:43:49:099551 gpstop:Jimmy:jyih-[INFO]:-Master segment instance directory=/dir
20170111:14:45:50:099551 gpstop:Jimmy:jyih-[INFO]:-Failed to shutdown master with pg_ctl.
20170111:14:45:50:099551 gpstop:Jimmy:jyih-[INFO]:-Sending SIGQUIT signal...
```

### CODE REVIEW

**Comment by jimmyyih** [comment]
@danielgustafsson

**Comment by ashwinstar** [comment]
LGTM

**Comment by asimrp** [comment]
Nice catch, but I'm not able to understand how this function is used.  No call to `SignalSomeChildren()` should result in walsender being signaled, if I'm reading this correctly.

**Comment by jimmyyih** [comment]
@asimrp, sorry I merged without answering your question.  I believe the `SignalSomeChildren()` call happens in `StateMachineTransition_ShutdownBackends()`:
```
#define SignalChildren(sig)         SignalSomeChildren(sig, BACKEND_TYPE_ALL)
#define SignalAutovacWorkers(sig)   SignalSomeChildren(sig, BACKEND_TYPE_AUTOVAC)

/*
 * Possible types of a backend. These are OR-able request flag bits
 * for SignalSomeChildren() and CountChildren().
 */
#define BACKEND_TYPE_NORMAL     0x0001  /* normal backend */
#define BACKEND_TYPE_AUTOVAC    0x0002  /* autovacuum worker process */
#define BACKEND_TYPE_WALSND     0x0004  /* walsender process */
#define BACKEND_TYPE_ALL        0x0007  /* OR of all the above */

/*
 * Called to transition to PM_CHILD_STOP_WAIT_BACKENDS : waiting for all backends to finish
 */
static void
StateMachineTransition_ShutdownBackends(void)
{
    if (Shutdown == FastShutdown)
    {
        /* shut down all backends, including autovac workers */
        SignalChildren(SIGTERM);
    }
    else
    {
        /* only autovacuum workers are told to shut down immediately */
        SignalAutovacWorkers(SIGTERM);
    }

    /* and the autovac launcher too */
    signal_child_if_up(AutoVacPID, SIGTERM);

    /* and the wal writer too */
    signal_child_if_up(WalWriterPID, SIGTERM);

    signal_filerep_to_shutdown(SegmentStateShutdownFilerepBackends);
}
```

**Comment by asimrp** [comment]
No problem, @jimmyyih, I am only trying to understand how this works.  Both the calls in `StateMachineTransition_ShutdownBackends()` should not result in a signal to walsender, unless I'm missing something.

**Pull request merged**
