### PR TITLE
Code cleanup of Subquery Scan

### PR DESCRIPTION
**Pull request by DevChattopadhyay**
In 7X ORCA, subquery scan is not used. Only the classes for DXL , parsing of DXL
and translation of DXL to planned statement is present in the code. This came
in with the initial Orca code (back in 2013) and hasn't been touched since.
None of the logic beyond translation was ever implemented. This PR cleans up
the code for subquery scan.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by dgkimura — COMMENTED** [review]
Nice find!  In order to help justify the removal, I think it would be good to explain how it was used previously and when/why that changed.

**Review by gpopt — APPROVED** [review]
+1

**Review by chrishajas — COMMENTED** [review]
I see `#include "naucrates/dxl/operators/CDXLPhysicalSubqueryScan.h"` in `libnaucrates/include/naucrates/dxl/operators/dxlops.h` still

**Comment by chrishajas** [comment]
> Nice find! In order to help justify the removal, I think it would be good to explain how it was used previously and when/why that changed.

I did some archeology, and this came in with the initial Orca code (back in 2013) and hasn't been touched since. None of the logic beyond translation was ever implemented.

**Comment by dgkimura** [comment]
On Fri, Dec 22, 2023 at 9:51 AM Chris Hajas wrote:
> I see #include "naucrates/dxl/operators/CDXLPhysicalSubqueryScan.h" in libnaucrates/include/naucrates/dxl/operators/dxlops.h still

Looks like that file was deleted in commit 292644d8a32542ed3bad99776b596f0a8bb66218?

**Review by dgkimura — APPROVED** [review]
I suggest to add Chris' archeology notes in the commit message.

**Comment by chrishajas** [comment]
> On Fri, Dec 22, 2023 at 9:51 AM Chris Hajas wrote:
> 
> > I see #include "naucrates/dxl/operators/CDXLPhysicalSubqueryScan.h" in libnaucrates/include/naucrates/dxl/operators/dxlops.h still
> 
> Looks like that file was deleted in commit [292644d](https://github.com/greenplum-db/gpdb/commit/292644d8a32542ed3bad99776b596f0a8bb66218)?

Ah, you're right, I was looking under the 6X branch

**Review by chrishajas — APPROVED** [review]

**Comment by DevChattopadhyay** [comment]
Thanks for the reviews!

**Pull request merged**
