### PR TITLE
Remove 'onerow' field, it's not really needed.

### PR DESCRIPTION
**Pull request by hlinnaka**
The 'onerow' field was used in create_nestloop_path(), to skip creating a
Materialize node on the inner side, if the outer path was guaranteed to
return only one row. However, the similar logic in create_nestloop_plan()
didn't pay attention to the 'onerow' field, and went ahead and created the
Materialize node, anyway.

A second place where 'onerow' was used, was in setting the row count
estimates for subqueries and table functions. That seems redundant: if the
cost estimator can detect the single-row case, it already sets the
estimate for the base relation to 1 row, and that should be propagated up
to the subquery's cost estimate as usual.

I went down this rabbit hole, by looking at the 'num_leading_eq' variable
first. It was used to detect the case that a unique index guarantees that
the relation can return only a single row. It treated "x IS NULL" the same
as "x = <const>", but that is not correct: a unique index can contain
multiple NULL values. So if the query contained an indexable IS NULL qual,
we might incorrectly set the 'onerow' flag. I constructed this test case
for it:

create table foo (id int4);
create table bar (id int4, x int4, unique (id, x));
insert into foo select g from generate_series(1, 100000) g;
insert into bar values (null, 1), (null, 2);
set enable_hashjoin=off;
set enable_nestloop=on;
set enable_seqscan=off;
explain (costs off) select * from bar left join foo on foo.id = bar.x
where bar.id is null and bar.x=1;

I verified with a debugger that 'onerow' is set on the 'bar' relation,
and we incorrectly skip inserting the Materialize node on the inner side
in create_nestloop_path(). However, as you can see from the plan below,
you still get a Materialize node there, because it's still added later, in
create_nestloop_plan():

                          QUERY PLAN
---------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)
   ->  Nested Loop Left Join
         Join Filter: (foo.id = bar.x)
         ->  Index Only Scan using bar_id_x_key on bar
               Index Cond: ((id IS NULL) AND (x = 1))
         ->  Materialize
               ->  Broadcast Motion 1:3  (slice1; segments: 1)
                     ->  Seq Scan on foo
                           Filter: (id = 1)
 Optimizer: legacy query optimizer
(10 rows)

Given that we are inserting the Materialize node in
create_nestloop_plan() stage anyway, it's pointless to try avoiding it
in the create_nestloop_path() stage. I considered ripping out the
code in create_nestloop_path() altogether, and relying on
create_nestloop_plan() to do it in all cases. But it seems marginally
better to include it in the Path already, because otherwise the cost of
the extra Materialize node is not included in the Path's cost estimate.

As a concept, it's not a bad idea to prove that a relation can only
return single row, and use that fact in optimization. There is some
code like that in never versions of PostgreSQL, to try to prove a
relation as unique, and use that to remove unnecessary left joins, and
to reduce semijoins to inner joins. We'll get eventually when we merge
with upstream.

### CODE REVIEW

**Comment by BaiShaoqi** [comment]
Very very interesting! Great explanation and description is easy to understand

**Comment by paul-guo-** [comment]
It is possible to move the materialize add logic from create_nestloop_plan() to create_nestloop_path()? Is it possible to check the original onerow patch from gpdb commit history to see the potential benefit? If the improvement is not significant for just rare cases, it seems to be ok to remove that.

**Comment by hlinnaka** [comment]
On 29/12/2018 04:57, Paul Guo wrote:> It is possible to move the materialize add logic from 
> create_nestloop_plan() to create_nestloop_path()? Is it possible to 
> check the original onerow patch from gpdb commit history to see the 
> potential benefit? If the improvement is not significant for just rare 
> cases, it seems to be ok to remove that.

No, can't always do it in create_nestloop_path(). I don't fully understand why, but there's a comment create_nestloop_plan() that tries to explain it:

```
 * MPP-1459: subqueries are resolved after our deadlock checks in
 * pathnode.c; so we have to check here to make sure that we catch all
 * motion deadlocks.
```

I tried commenting out the code in create_nestloop_plan(), to verify if that is indeed still needed. This query in the 'join' regression test started failing:

```
regression=# set enable_hashjoin=off;
SET
regression=# set enable_nestloop=on;
SET
regression=# explain select a.f1, b.f1, t.thousand, t.tenthous from
  tenk1 t,
  (select sum(f1)+1 as f1 from int4_tbl i4a) a,
  (select sum(f1) as f1 from int4_tbl i4b) b
where b.f1 = t.thousand and a.f1 = b.f1 and (a.f1+b.f1+999) = t.tenthous;
                                                                                       QUERY PLAN                                                                                        
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice5; segments: 3)  (cost=2.31..303.08 rows=4 width=24)
   ->  Nested Loop  (cost=2.31..303.08 rows=2 width=24)
         ->  Broadcast Motion 1:3  (slice2; segments: 1)  (cost=1.07..1.14 rows=3 width=8)
               ->  Aggregate  (cost=1.07..1.08 rows=1 width=8)
                     ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=1.01..1.06 rows=1 width=8)
                           ->  Aggregate  (cost=1.01..1.02 rows=1 width=8)
                                 ->  Seq Scan on int4_tbl i4b  (cost=0.00..1.01 rows=1 width=4)
         ->  Materialize  (cost=1.24..301.78 rows=2 width=16)
               ->  Nested Loop  (cost=1.24..301.76 rows=2 width=16)
                     Join Filter: ((pg_catalog.sum((sum(i4b.f1)))) = ((pg_catalog.sum((sum(i4a.f1))) + 1)))
                     ->  Broadcast Motion 1:3  (slice4; segments: 1)  (cost=1.07..1.14 rows=3 width=8)
                           ->  Aggregate  (cost=1.07..1.09 rows=1 width=8)
                                 ->  Gather Motion 3:1  (slice3; segments: 3)  (cost=1.01..1.06 rows=1 width=8)
                                       ->  Aggregate  (cost=1.01..1.02 rows=1 width=8)
                                             ->  Seq Scan on int4_tbl i4a  (cost=0.00..1.01 rows=1 width=4)
                     ->  Index Only Scan using tenk1_thous_tenthous on tenk1 t  (cost=0.17..100.19 rows=1 width=8)
                           Index Cond: ((thousand = (pg_catalog.sum((sum(i4b.f1))))) AND (tenthous = ((((pg_catalog.sum((sum(i4a.f1))) + 1)) + (pg_catalog.sum((sum(i4b.f1))))) + 999)))
 Optimizer: legacy query optimizer
(18 rows)

regression=#  select a.f1, b.f1, t.thousand, t.tenthous from
  tenk1 t,
  (select sum(f1)+1 as f1 from int4_tbl i4a) a,
  (select sum(f1) as f1 from int4_tbl i4b) b
where b.f1 = t.thousand and a.f1 = b.f1 and (a.f1+b.f1+999) = t.tenthous;
ERROR:  illegal rescan of motion node: invalid plan (nodeMotion.c:1596)  (seg0 slice5 127.0.0.1:40000 pid=15103) (nodeMotion.c:1596)
HINT:  Likely caused by bad NL-join, try setting enable_nestloop to off
```

**Comment by hlinnaka** [comment]
This is failing in the `join` regression test, because it changed the plan chosen for one query. It's a pre-existing bug, though, you get the same error without this PR, with a slightly modified version of the query. Opened issue https://github.com/greenplum-db/gpdb/issues/6769 for that.

**Comment by berlin-ab** [comment]
Marking this as a `work-in-progress` as there is more work to be done. Correct me if I'm wrong.

**Comment by hlinnaka** [comment]
I'm going to revisit this after https://github.com/greenplum-db/gpdb/pull/6776 has been merged.

**Comment by berlin-ab** [comment]
Looks like #6776 was merged. Let's pick this up again.

**Comment by berlin-ab** [comment]
Looks like we can pick this back up again.

**Comment by ashwinstar** [comment]
> As a concept, it's not a bad idea to prove that a relation can only
return single row, and use that fact in optimization. There is some
code like that in never versions of PostgreSQL, to try to prove a
relation as unique, and use that to remove unnecessary left joins, and
to reduce semijoins to inner joins. We'll get eventually when we merge
with upstream.

Just putting this back on your radar @hlinnaka, as we will be caught with
upstream and seems this 'onerow' field still exists. Something to finally finish out
and land (maybe after PostgreSQL 12 merge branch lands) on master.

**Comment by hlinnaka** [comment]
Rebased this now. There were some test failures earlier, but now that we have the v12 merge, and commit f4d4835844a24f3b1056dbc97dabd0b81312786f, I believe this is now ready.

**Comment by ashwinstar** [comment]
LGTM :+1:  Thanks for rebase and finally we will have this PR merged.
Once PR pipeline signals green, get it in.

**Comment by ashwinstar** [comment]
Closing this as newer rebase version of the same is created https://github.com/greenplum-db/gpdb/pull/12055

**Pull request closed without merging**
