### PR TITLE
[PRE-ARM-REGRESSION-TEST]Add arm regression test badge into README

### PR DESCRIPTION
**Pull request by bzhaoopenstack**
I have setup a periodic task in openlab env for gpdb.
It runs installcheck-world per UTC12:00 every day.

we can check the status with link https://status.openlabtesting.org/builds/builds?project=greenplum-db%2Fgpdb&job_name=gpdb-installcheck-world-tests-on-arm64
And get the necessary log in each build.
Also that build definition could be changed anytime. You guys can tell me the changes you want. Thanks

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by hlinnaka** [comment]
Nice, thanks for working on this!

Is the source code for the ansible scripts etc. available somewhere? I guess it doesn't do much, just "make; make installcheck-world", but still.

**Comment by bzhaoopenstack** [comment]
Yeah. @hlinnaka 
The ansible script is in https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/gpdb-installcheck-world-tests-on-arm64/run.yaml . The current status is that I skip or fix the issue by myself, I'm pushing the fix in the upstream just like I post the PRs in greenplum. And right now, the job test on the lastest master branch, and I find the CIs hit errors after 2020/3/26, seems the new changes in upstream bring some errors in the lastest tests on arm.

For the ansible definition, you can help to suggest what I need to do.

Thanks.

**Comment by bzhaoopenstack** [comment]
@hlinnaka @danielgustafsson 
Hi guys, the periodic CI job from openlab has been stable for a week. How about consider to make it work on Greenplum repo?

I build the job run 1 time per day, at UTC 12. Please see the link below:

https://status.openlabtesting.org/builds/builds?project=greenplum-db%2Fgpdb&job_name=gpdb-installcheck-world-tests-on-arm64

**Comment by Eulerizeit** [comment]
@bo zhaobo <bzhaojyathousandy@gmail.com> to refresh my memory, the idea is
to have the ARM tests running alongside the current Travis and concourse
jobs, with every PR created?

@Yu Yang <myang@pivotal.io> @Michael Schubert <mschubert@pivotal.io> FYI

**Comment by bzhaoopenstack** [comment]
@Eulerizeit 
We plan to enable ARM CI with 2 steps.

1. First to enable a periodic ARM test job to run regression test. And make it stable for a while. Then bring a badgt into REAMME.md to show the test status for let more contributor could see the test on ARM. Then we can confident to know that would be worth to enable the ARM CI for each PRs.
2. Second to enable the PR trigger ARM CI using exsting travis CI(first choice) or openlab(secondary choice). The reason about introduce openlab here again is that we're not confident about travis ARM resources, as travis ARM CI is in test state.

So right now, we are in 1st step.

**Comment by bzhaoopenstack** [comment]
@all  Hi guys, how about your idea?

**Comment by bzhaoopenstack** [comment]
@hlinnaka @Eulerizeit Hi guys, are you around? This PR is hang for half a month. Could you please see this more? Then we can go forward. Thanks

**Comment by hlinnaka** [comment]
Ok, let's get this in. I squashed the two commits in this PR, and pushed. The badge is now visible at https://github.com/greenplum-db/gpdb/.

Thank you,@bzhaoopenstack!

**Pull request closed without merging**
