### PR TITLE
Remove unused 'gp_interconnect_hash_multiplier' GUC

### PR DESCRIPTION
**Pull request by hlinnaka**
It was made unused by commit 8eed421738b11c28a973eea9498c33c6c2361760

### CODE REVIEW

**Comment by hlinnaka** [comment]
@pengzhout: This is actually more of a question or discussion starter. Commit 8eed421738b11c28a973eea9498c33c6c2361760 removed the use of the GUC, but I wonder if that was intentional. I agree with removing the setting, but the new size of the hash table, 16 elements, seems pretty small. The old formula was gp_interconnect_hash_multiplier * numsegments., or 16 at a minimum. With the default gp_interconnect_hash_multiplier = 2, the old formula gave a much bigger hash table for large clusters. Is the smaller hash table enough? Perhaps we should bump the constant size from 16 to, say, 256?

**Comment by pengzhout** [comment]
>  Is the smaller hash table enough? Perhaps we should bump the constant size from 16 to, say, 256?

Yes, definitely wrong to set it to 16 directly, forgot to replace GpIdentify.numsegments to getgpsegmentCount() in this place. I think we need to bring this GUC and math logic back.

**Comment by hlinnaka** [comment]
On 13 February 2019 05:52:44 EET, Tang Pengzhou <notifications@github.com> wrote:
>>  Is the smaller hash table enough? Perhaps we should bump the
>constant size from 16 to, say, 256?
>
>Yes, definitely wrong to set it to 16 directly, forgot to replace
>GpIdentify.numsegments to getgpsegmentCount() in this place. I think we
>need to bring this GUC and math logic back. 

I'm not fond of the GUC actually. If we just hardcode the size to be 2*getgpsegmentCount(), I think that's enough. I can't imagine that a user could tune the setting better than a simple hardcoded formula would.

Looking at the hash function used, there isn't much entropy, so I don't think using a much larger hash table is actually helpful. And making it smaller would save only miniscule amounts of memory.

- Heikki

**Comment by pengzhout** [comment]
> I'm not fond of the GUC actually. If we just hardcode the size to be 2*getgpsegmentCount(), I think that's enough. I can't imagine that a user could tune the setting better than a simple hardcoded formula would. Looking at the hash function used, there isn't much entropy, so I don't think using a much larger hash table is actually helpful. And making it smaller would save only miniscule amounts of memory. - Heikki

That's should be enough and checked the git history, it is original added for UDP interconnect (removed) to tunnel performance, and for UDPIFC interconnect, it doesn't take effect unless you reload the configuration or restart.

**Comment by berlin-ab** [comment]
@hlinnaka Is this something that we definitely want in for 6?

**Comment by hlinnaka** [comment]
yeah, we need to do something. As things stand, we have a GUC that does nothing.

**Comment by berlin-ab** [comment]
This change looks good. Let's move it forward.

**Comment by danielgustafsson** [comment]
:+1: on removing this and instead hardcode to `2 * getgpsegmentCount()`.

**Comment by pengzhout** [comment]
@hlinnaka do you mind if I pick this up and push it to master and 6X_STABLE?

**Comment by hlinnaka** [comment]
On 24/05/2019 04:03, Tang Pengzhou wrote:
> @hlinnaka <https://github.com/hlinnaka> do you mind if I pick this up 
> and push it to master and 6X_STABLE?

Go ahead, thank you!

- Heikki

**Pull request merged**
