### PR TITLE
Remove deprecated S3 resources for server RCs

### PR DESCRIPTION
**Pull request by bradfordboyle**
Release candidates for server and clients are stored in GCS and the S3
resources were deprecated four months ago. The S3 resources were left in
the pipeline to give downstream consumers an opportunity to update their
CI pipelines to use the new GCS resources. This commit finalizes the
deprecation of the S3 resources.

Authored-by: Bradford D. Boyle <bboyle@pivotal.io>

### CODE REVIEW

**Comment by bradfordboyle** [comment]
This will also be backported to 6X_STABLE.

**Comment by amilkh** [comment]
So, `bin_gpdb_centos{6,7}_rc_s3` will be removed and `bin_gpdb_centos{6,7}_rc` (gcs) will remain!

**Comment by amilkh** [comment]
Also looks like nobody else is using these at least as what I have privileges: https://github.com/search?q=bin_gpdb_centos6_rc_s3+OR+bin_gpdb_centos7_rc_s3&type=Code

Maybe good to wait until Monday to merge this :X

**Comment by frankgh** [comment]
does this affect icw_green artifacts? or are we still promoting artifacts to icw_green on s3?

**Comment by amilkh** [comment]
@frankgh good catch! Looks like this PR does not affect bin_gpdb_centos6_icw_green, but I think that can be a separate PR.
https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE?groups=ICW

**Comment by frankgh** [comment]
@amilkh I was asking because our pipelines still rely on icw_green artifacts. So if there are plans to remove pushing artifacts to icw_green, then we need to done some work on our end

**Comment by amilkh** [comment]
@frankgh not in this PR, we will contact you if we have plans to remove `bin_gpdb_centos6_icw_green`.

**Pull request merged**
