### PR TITLE
Make authdie use proc_exit and check if one is already in progress.

### PR DESCRIPTION
**Pull request by jimmyyih**
This fixes a deadlock scenario in filerep postmaster reset. We
encountered a situation in our testing where injecting PANIC on
primary to force a postmaster reset would cause the mirror to hang
while waiting for a child backend process to exit. The child backend
process sends a message to the postmaster to start terminating its
child processes and then runs proc_exit. The postmaster will then
start sending exit signals to its child processes. In rare cases, the
child backend process described here can encounter a deadlock where
authdie from SIGQUIT is called before its natural proc_exit finishes.

Example backtrace of the deadlock:
```
#0  0x0000003c1e8f82ce in __lll_lock_wait_private () from /lib64/libc.so.6
#1  0x0000003c1e87d0a0 in _L_lock_5189 () from /lib64/libc.so.6
#2  0x0000003c1e8789fb in _int_free () from /lib64/libc.so.6
#3  0x0000003c1e835e55 in exit () from /lib64/libc.so.6
#4  0x000000000082291e in authdie ()
#5  <signal handler called>
#6  0x0000003c1e878a08 in _int_free () from /lib64/libc.so.6
#7  0x0000003c1e835e55 in exit () from /lib64/libc.so.6
#8  0x000000000080987f in proc_exit ()
#9  0x00000000007ca0c7 in ServerLoop () at postmaster.c:6584
#10 0x00000000007cb702 in PostmasterMain () at postmaster.c:1523
#11 0x0000000000703297 in main () at main.c:206
```

### CODE REVIEW

**Comment by hlinnaka** [comment]
This desperately needs a comment explaining why this is different from the upstream. This code has moved around and changed slightly in more recent PostgreSQL versions, but it's still essentially the same. On Postgres master branch, the signal handler is called startup_die() rather than authdie(), and it calls proc_exit(1) rather than exit(1), but it's basically still the same. Can you reproduce this on PostgreSQL? You shouldn't need replication for this, just send a SIGQUIT to the backend process during authentication, when the backend is just about to exit anyway. Might need to insert some delays in suitable spots, or just try to race it it for long enough to hit it. A reproducable test case would be nice anyway.

Looking at the stack trace, it seems like the process is deadlocking with itself, because the signal arrives while it's in the glibc free() function, and free() isn't re-entrant. I don't see anything here about processes waiting for each other, it's just one process locking itself up.

The free() call happens inside exit(), so I guess exit() is also not re-entrant, and should not be called from a signal handler.

**Comment by ashwinstar** [comment]
On Jan 31, 2017, at 11:36 PM, Heikki Linnakangas <notifications@github.com>
wrote:

This desperately needs a comment explaining why this is different from the
upstream. This code has moved around and changed slightly in more recent
PostgreSQL versions, but it's still essentially the same. On Postgres
master branch, the signal handler is called startup_die() rather than
authdie(), and it calls proc_exit(1) rather than exit(1), but it's
basically still the same. Can you reproduce this on PostgreSQL? You
shouldn't need replication for this, just send a SIGQUIT to the backend
process during authentication, when the backend is just about to exit
anyway. Might need to insert some delays in suitable spots, or just try to
race it it for long enough to hit it. A reproducable test case would be
nice anyway.

Looking at the stack trace, it seems like the process is deadlocking with
itself, because the signal arrives while it's in the glibc free() function,
and free() isn't re-entrant. I don't see anything here about processes
waiting for each other, it's just one process locking itself up.

The free() call happens inside exit(), so I guess exit() is also not
re-entrant, and should not be called from a signal handler.

Yes its self deadlock case. exit() is not re-entrant. We had faced similar
deadlock earlier in quickdie() where we changed to call _exit instead which
is signal safe.

We also feel Postgres should face same issue as were surprised to see
proc_exit being called from signal handler plus with no protection for
re-entry.

**Comment by hlinnaka** [comment]
On 02/01/2017 09:49 AM, Ashwin Agrawal wrote:
> On Jan 31, 2017, at 11:36 PM, Heikki Linnakangas <notifications@github.com>
> wrote:
>
> Yes its self deadlock case. exit() is not re-entrant. We had faced similar
> deadlock earlier in quickdie() where we changed to call _exit instead which
> is signal safe.
>
> We also feel Postgres should face same issue as were surprised to see
> proc_exit being called from signal handler plus with no protection for
> re-entry.

Ok, the big question here is why is Postgres not suffering from these 
issues, then? Please try to come up with a repro for that, in PostgreSQL.

One data point is that Postgres is single-threaded, so glibc probably 
isn't using those mutexes at all, and so cannot lock up like in this 
case. But then you might have corrupted memory structures instead, I'd 
assume. So to reproduce this in PostgreSQL, perhaps put add some dummy 
pthread calls somewhere, to force glibc to go into multi-threaded mode.

- Heikki

**Comment by ashwinstar** [comment]
> On Jan 31, 2017, at 11:57 PM, Heikki Linnakangas <notifications@github.com> wrote:
>
> On 02/01/2017 09:49 AM, Ashwin Agrawal wrote:
> > On Jan 31, 2017, at 11:36 PM, Heikki Linnakangas <notifications@github.com>
> > wrote:
> >
> > Yes its self deadlock case. exit() is not re-entrant. We had faced similar
> > deadlock earlier in quickdie() where we changed to call _exit instead which
> > is signal safe.
> >
> > We also feel Postgres should face same issue as were surprised to see
> > proc_exit being called from signal handler plus with no protection for
> > re-entry.
>
> Ok, the big question here is why is Postgres not suffering from these
> issues, then? Please try to come up with a repro for that, in PostgreSQL.
>
> One data point is that Postgres is single-threaded, so glibc probably
> isn't using those mutexes at all, and so cannot lock up like in this
> case. But then you might have corrupted memory structures instead, I'd
> assume. So to reproduce this in PostgreSQL, perhaps put add some dummy
> pthread calls somewhere, to force glibc to go into multi-threaded mode.
>
Sure. Just a data-point similar code exist for 4.3 as well but we
never saw the issue there as well, master its hitting pretty
frequently some how.

**Comment by ashwinstar** [comment]
👍 Lets add comment explaining and get this in as hits very frequently due to our usage of peer reset process for mirroring receiving the signal and exit()'s. So, probability of hitting the same is extremely high for GPDB because of the same.

@jimmyyih is continuing to follow-up separately to attempt repro the same for Postgres.

**Comment by jimmyyih** [comment]
@hlinnaka, this self-deadlock window is reproducible in latest Postgres.  Here's the stacktrace:
```
#0  startup_die (postgres_signal_arg=0) at postmaster.c:5090
#1  <signal handler called>
#2  proc_exit_prepare (code=0) at ipc.c:158
#3  0x00000000007c4135 in proc_exit (code=0) at ipc.c:102
#4  0x000000000076b736 in BackendInitialize (port=0x2c13740) at postmaster.c:4207
#5  0x000000000076b190 in BackendStartup (port=0x2c13740) at postmaster.c:3979
#6  0x0000000000767ad3 in ServerLoop () at postmaster.c:1722
#7  0x00000000007671df in PostmasterMain (argc=3, argv=0x2bebad0) at postmaster.c:1330
#8  0x00000000006b5df6 in main (argc=3, argv=0x2bebad0) at main.c:228
```

I got the stacktrace by doing the following:
1. gdb attach to postmaster and run `set follow-fork child` and `break postmaster.c:4206`(right after ProcessStartupPacket) and continue
2. In another terminal, open a psql session which should trigger the gdb follow
3. In the gdb session, `set status=1` and step into proc_exit()
4. In another terminal, `kill -s QUIT <child pid>` to send SIGQUIT to the child process
5. In the gdb session, step to process the signal into `startup_die()` and run `bt`

The scenario seems pretty rare for a SIGQUIT to happen after a bad ProcessStartupPacket... and having both exits collide is probably even more rare but the window seems to be there.  I'm going to edit the comment to be more descriptive of this issue and then probably merge this pull request in for GPDB5 since it's intermittently (1 out of 10 runs) hanging some of our TINC tests.  Should I follow up on postgres-hackers for the above repro?

**Comment by jimmyyih** [comment]
Updated authdie comment and commit message to be more descriptive of the issue.

**Comment by asimrp** [comment]
Good find, Jimmy.  Instead of manually sending SIGQUIT to the backend process in step 4, if you shutdown postgres `pg_ctl stop -M immediate`, it should result in the same behavior.

**Comment by hlinnaka** [comment]
On 02/02/2017 02:40 AM, Jimmy Yih wrote:
> @hlinnaka, this self-deadlock window is reproducible in latest
> Postgres.

Cool!

> Should I follow up on postgres-hackers for the above repro?

Yeah, please do.

I'm not sure that proc_exit(1) is the only problem here, BTW. The signal 
might arrive in the middle of a palloc(), for example.

- Heikki

**Comment by ashwinstar** [comment]
> On Feb 1, 2017, at 11:21 PM, Heikki Linnakangas <notifications@github.com> wrote:
>
> On 02/02/2017 02:40 AM, Jimmy Yih wrote:
> > @hlinnaka, this self-deadlock window is reproducible in latest
> > Postgres.
>
> Cool!
>
> > Should I follow up on postgres-hackers for the above repro?
>
> Yeah, please do.
>
> I'm not sure that proc_exit(1) is the only problem here, BTW. The signal
> might arrive in the middle of a palloc(), for example.
Agree, is it better to just call then _exit() here similar to quickdie?

**Pull request merged**
