### PR TITLE
Use a penalty cost to implement enable_* planner GUCs, like in upstream.

### PR DESCRIPTION
**Pull request by hlinnaka**
Instead of completely disabling the generation of Paths with disabled
plan types, add a high penalty to their cost estimates, like in the
upstream. This reduces our diff vs. upstream, making future merges more
straightforward.
    
Discussion: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/Az2cDcqf73g/_tY6Yv1kBgAJ

### CODE REVIEW

**Comment by hlinnaka** [comment]
The third commit is the focus of this PR. The first two are required, but I have opened separate PRs about them already (#4475 and #4461)

**Comment by xinzweb** [comment]
Thanks a lot @ashwinstar. @vraghavan78 is there any way to get priority on this PR and resolve it? Feel free to put a `ToDo` tag to exclude it from PR reminder https://greenplum.slack.com/messages/C9NHTUWUB. Thanks.

**Comment by dhanashreek89** [comment]
I have added this to the internal list of PRs to be reviewed such that we get to this; hence I will mark this as `ToDo`.

**Comment by xinzweb** [comment]
Thanks a lot @dhanashreek89

**Comment by ashwinstar** [comment]
Closing this as #5230 re-based version has been created.

**Pull request closed without merging**
