### PR TITLE
 Add citext extension and test cases.

### PR DESCRIPTION
**Pull request by JunfengYang**
And the citext extension and it's test cases. 
We need to support this module in GPDB 5, to help with some TeraData offload opportunities.

### CODE REVIEW

**Comment by hlinnaka** [comment]
From which version of PostgreSQL did you cherry-pick this? Did you have to make any changes compared to upstream version?

**Comment by danielgustafsson** [comment]
This PR is against 5X_STABLE, it would need to go into master first and then into 5X_STABLE to keep them from diverging.

**Comment by JunfengYang** [comment]
It's base on postgres REL9_1_STABLE.
Only remove the call of PG_GET_COLLATION(), cause it's not exists in GPDB.

**Comment by JunfengYang** [comment]
Close this PR and make it go into master first.

**Pull request closed without merging**
