### PR TITLE
pg_upgrade: add support func to check views using removed operators

### PR DESCRIPTION
**Pull request by kyeap-vmware**
Views that use deprecated operators will cause upgrade to fail. This happens during metadata restore on the target cluster because pg_restore will error trying to create a view using types that do not exist anymore. This is not ideal as we could be many hours into upgrade before a view using a deprecated operator causes pg_upgrade to fail. In order to detect views with deprecated operators. A query_tree_walker is used to walk the nodes of all views. Each node is then checked to see if is an operator. If it is, we then check if the oid of the operator matches one that is not present in GPDB7.

Due to the limitations of the query walker being a function that only returns a bool, we can only tell if a deprecated operator exists in a view. We do not have an easy way to tell users how many or which deprecated operators are present in the view.

Method used to find operators that are no longer present on 7x

on 7x
```
create temp table seven_op as (select n.nspname || '.' || o.oprname as oprname, o.oprcode::text as oprcode from pg_operator o join pg_namespace n on o.oprnamespace=n.oid order by oprcode);
copy seven_op TO '/tmp/7x_depreciated_operators.csv' WITH CSV;
```

on 6x
```
create temp table six_op as (select n.nspname || '.' || o.oprname as oprname, o.oprcode::text as oprcode from pg_operator o join pg_namespace n on o.oprnamespace=n.oid order by oprcode);
create temp table seven_op (a text, b text);
copy seven_op FROM '/tmp/7x_depreciated_operators.csv' WITH CSV;

select * from six_op EXCEPT select * from seven_op order by 2, 1;
    oprname     |    oprcode
----------------+----------------
 pg_catalog.=   | abstimeeq
 pg_catalog.>=  | abstimege
 pg_catalog.>   | abstimegt
 pg_catalog.<=  | abstimele
 pg_catalog.<   | abstimelt
 pg_catalog.<>  | abstimene
 pg_catalog.=   | int2vectoreq
 pg_catalog.<?> | intinterval
 pg_catalog.<#> | mktinterval
 pg_catalog.=   | reltimeeq
 pg_catalog.>=  | reltimege
 pg_catalog.>   | reltimegt
 pg_catalog.<=  | reltimele
 pg_catalog.<   | reltimelt
 pg_catalog.<>  | reltimene
 pg_catalog.-   | timemi
 pg_catalog.+   | timepl
 pg_catalog.<<  | tintervalct
 pg_catalog.=   | tintervaleq
 pg_catalog.>=  | tintervalge
 pg_catalog.>   | tintervalgt
 pg_catalog.<=  | tintervalle
 pg_catalog.#=  | tintervalleneq
 pg_catalog.#>= | tintervallenge
 pg_catalog.#>  | tintervallengt
 pg_catalog.#<= | tintervallenle
 pg_catalog.#<  | tintervallenlt
 pg_catalog.#<> | tintervallenne
 pg_catalog.<   | tintervallt
 pg_catalog.<>  | tintervalne
 pg_catalog.&&  | tintervalov
 pg_catalog.~=  | tintervalsame
 pg_catalog.|   | tintervalstart
(33 rows)
```

### CODE REVIEW

**Comment by bmdoil** [comment]
Let's start calling these checks what they are, views using **removed** operators/types/columns etc. I'll make the updates for internal stories etc.

The following types have been removed in 7
```
pg_catalog._reltime
pg_catalog.reltime
pg_catalog.smgr
pg_catalog._tinterval
pg_catalog.tinterval
pg_catalog._abstime
pg_catalog.abstime
```
The check for removed types will cover the removed operators for those types, so we should only need this check to identify removed operators for types that exist both in 6 and 7.

That list should be:
```
pg_catalog.=   | int2vectoreq
pg_catalog.<?> | intinterval
pg_catalog.<#> | mktinterval
pg_catalog.-   | timemi
pg_catalog.+   | timepl
```
Something else to consider, how might we walk all the views in a database and perform all required checks for each view before moving to the next? 

It would require some code refactoring but we should at least think about into this before committing changes to 6X_STABLE. It's pretty costly and wasteful to walk all the views N times for N different checks, as we've seen in large clusters.

**Comment by kyeap-vmware** [comment]
> Something else to consider, how might we walk all the views in a database and perform all required checks for each view before moving to the next?

I have a few thoughts on this with some possible solutions.
1. Combine all the view checks. We only have to walk the views once. This is easy to implement by adding more fail conditions in check_node_deprecated_operators_walker. The downside is users will only know which views are using a removed relation. We won't be able to provide information on if a removed type, operator, procedure, or function was used. Check would be...
`Checking for views using removed types, operators, procedures, and functions`
2. Combine all view checks and record removed relations directly in the support function on 6X. Location to write affected views is passed into the support function. 6x will require the use of globals variables, changing the function signature of `query_tree_walker` and `check_node_deprecated_operators_walker` is not viable. We'll be able record the view and the removed relation directly in the walker.
3. parallelize the view checks in 7x like we did in 6x. Achieves the same speedup as long as the cpu cycles are there. Also will not show which removed relation got flagged. 



> The check for removed types will cover the removed operators for those types, so we should only need this check to identify removed operators for types that exist both in 6 and 7.

I agree with your analysis here. I expect all operators against removed types would be caught by type check, but there could be merit in being redundant and exhaustive. Walking a query seems to be the high cost, checking more operators would be relatively low cost and may cover edge cases we don't realize.

**Comment by bmdoil** [comment]
> I have a few thoughts on this with some possible solutions.

Discussed offline, a refactor could provide some performance gains, but testing shows disabling the `track_counts` GUC before running the view checks results in a large performance improvement, several orders of magnitude, when walking the views. 

`track_counts` can be set at session level, so for the view checks we can turn it off and get a massive speedup and I see no value in enabling it for these queries. 

If we're looking to squeeze more performance later on in the development cycle, we can revisit the refactor discussion, but I think disabling this GUC during the pg_upgrade checks is good enough.

Also discussed offline, let's limit this PR to only the removed operators for types that still exist in 7, along with `s/deprecated/removed/g` in this and the related PRs, then LGTM.

**Review by bmdoil — APPROVED** [review]
LGTM, can you clarify in the commit message/PR description that `int2vectoreq` is the only operator that needs to be checked? 

Reword the last part to something like

```
There will also be another check to look for views using removed types.
Of the operators removed from GP6 to GP7, only `int2vectoreq` is not associated with a removed type. The removed type check will handle all other removed operators.
The removed types check will implicitly flag all removed associated operators. The following types are removed. reltime, smgr, tinterval, abstime.

To further clarify, the operators noted below are also removed because their inputs are of
removed types. I'm mentioning them here because it is not so obvious that we are assuming they are also not needed.

pg_catalog.<?> | intinterval | checks if an abstime is contained in a tinterval
pg_catalog.<#> | mktinterval | converts two abstimes into a tinvertal
pg_catalog.-   | timemi      | abstime - relative time
pg_catalog.+   | timepl      | abstime + relative time
```

**Pull request merged**
