### PR TITLE
Remove a couple of unnecessary dependencies from build scripts.

### PR DESCRIPTION
**Pull request by hlinnaka**

### CODE REVIEW

**Comment by jimmyyih** [comment]
The pg8000 python module is used in our internal Pivotal Greenplum test environment (very legacy stuff here).  I'll let @kaknikhil  know to remove the dependency in our internal testing so we can finally remove pg8000 from the Greenplum source code.

**Comment by hlinnaka** [comment]
@kaknikhil, @jimmyyih, any news on this?

**Comment by jimmyyih** [comment]
I saw @kaknikhil and @Chibin discussing about it a couple days ago.  Other than that, I'm not too sure.

**Comment by hlinnaka** [comment]
@kaknikhil, @Chibin, any progress on this?

**Comment by Chibin** [comment]
Took a look... and it looks like it's not being used. Our internal Pivotal Greenplum test environment uses its own pg8000.

**Comment by hlinnaka** [comment]
Pushed, thanks for checking @Chibin!

**Pull request merged**
