### PR TITLE
Porting queries on derived table into ICG

### PR DESCRIPTION
**Pull request by vraghavan78**
@xinzweb @oarap @hsyuan @hlinnaka @danielgustafsson please take a look at these tests. It does increase the testing time with optimizer=on because of a lot of short running queries.

### CODE REVIEW

**Comment by xinzweb** [comment]
Do you know how much time we increased in this case with optimizer=on and optimizer=off?

**Comment by xinzweb** [comment]
+1

**Comment by vraghavan78** [comment]
1m with Planner and 6 with Optimizer. All short running queries.

**Comment by oarap** [comment]
+1

**Comment by danielgustafsson** [comment]
Skimming over the diff it seems fine, :+1:.

For the future maintenance of all these tests (not blocking this commit), is there documentation somewhere on what the different queries are testing for?

**Comment by hsyuan** [comment]
+1

**Comment by vraghavan78** [comment]
@danielgustafsson unfortunately, the QA did not add comments, and there are 8000+ sql files so no documentation available at this point.

**Comment by danielgustafsson** [comment]
Lovely =). We'll just have to add the documentation as we go along and hit a regression in one of the queries involved. The important part is getting them in and subjecting the code to the tests. Thanks for all the hard work on this!

**Comment by vraghavan78** [comment]
Thanks folks!

**Pull request closed without merging**
