### PR TITLE
Move cdbfast tests (gpfdist) to ICW

### PR DESCRIPTION
**Pull request by HaozhouWang**
More tests in cdbfast are now moved to ICW under gpfdist folder

Signed-off-by: Yuan Zhao <yuzhao@pivotal.io>

### CODE REVIEW

**Comment by hlinnaka** [comment]
I don't see the point of these tests. We have other tests for sorting and spilling, and there is no connection between external tables and sorting. The external table does the same thing whether or not you sort it afterwards.

**Comment by HaozhouWang** [comment]
Hi Heikki,

Thank you for your review. This test case was added due to a gpfdist bug, so I think this test case is useful for gpfdist test.

**Comment by hlinnaka** [comment]
What was the bug? (Please add a comment to explain.)

**Comment by HaozhouWang** [comment]
Thanks for your review. We updated the commit message.
This test case in cdbfast is to cover a greenplum/gpfidst bug, but the details of this bug have gone. We think it is better to move it from cdbfast to ICW to keep the coverage of gpfidst test.

**Pull request merged**
