### PR TITLE
Make resource queues object addressable

### LINKED ISSUE #5027: Comment on resource queue fails
### Greenplum version or build
PostgreSQL 9.1beta2 (Greenplum Database 6.0.0-alpha.0+dev.7177.g958a672a74 build dev-oss) on x86_64-apple-darwin17.5.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.1), 64-bit compiled on May 21 2018 09:59:11

### OS version and uname -a
Repros on Mac and Centos

### Expected behavior
Comment succeeds (last known working commit was 09b07657655d1b330c392c80cceb00fd0a21fd46), a day before the 9.1 merge.
### Actual behavior
`ERROR:  unrecognized objtype: 35 (objectaddress.c:237)`

### Step to reproduce the behavior

```
CREATE RESOURCE QUEUE rsq WITH (ACTIVE_STATEMENTS=7);
COMMENT ON RESOURCE QUEUE rsq IS 'This is a resource queue comment.';
```
Returns:
```
ERROR:  unrecognized objtype: 35 (objectaddress.c:237)
```
Stack trace:
```
1    0x1061af1e3 postgres errstart + 0x303
2    0x1061b2aed postgres elog_finish + 0xcd
3    0x105e370a2 postgres get_object_address + 0x992
4    0x105eaf738 postgres CommentObject + 0x68
5    0x1060a38ce postgres PortalRunUtility + 0xae
6    0x1060a2ee4 postgres PortalRunMulti + 0x1f4
7    0x1060a2748 postgres PortalRun + 0x1c8
8    0x1060a0e4d postgres exec_simple_query + 0x6cd
9    0x10609e11e postgres PostgresMain + 0x2a6e
10   0x10604500b postgres PostmasterMain + 0x221b
11   0x105f9cf7c postgres main + 0x37c
12   0x7fff6f43b015 libdyld.dylib start + 0x1
13   0xa 0x0000000a (in postgres)
```
This was found on the gpbackup integration pipeline, but we should add a test to ICW.

### PR DESCRIPTION
**Pull request by danielgustafsson**
In order to be able to set comments on resource queues, they must be object addressable, so fix by implementing. Also add a small test for commenting on a resource queue.

This fixes #5027

### CODE REVIEW

**Comment by chrishajas** [comment]
Resource queues are cluster-wide objects, so I think the comment should be populated in pg_shdescription (https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/comment.c#L122)

**Comment by danielgustafsson** [comment]
You are right @chrishajas, I've updated the PR with this as well as a tiny test and some minor cleanups.

**Comment by chrishajas** [comment]
Functionality works! Thanks! 

This also seems to enable comments on resource groups, which didn't work before. The COMMENT syntax doc may need to be updated for that.

**Comment by danielgustafsson** [comment]
Pushed to master, thanks for review.

**Pull request closed without merging**
