### PR TITLE
Fix flaky test case in create_index

### PR DESCRIPTION
**Pull request by hpbee**
A test case in create_index is still failing,
even after commit 50b7996999951d8e85cc4194a22ce7e92e6b44d3. 
The test case and faulty plan that can be seen sometimes: 
```
bhari=# EXPLAIN (COSTS OFF) SELECT * FROM polygon_tbl WHERE f1 ~ '((1,1),(2,2),(2,1))'::polygon ORDER BY (poly_center(f1))[0];
                               QUERY PLAN
-------------------------------------------------------------------------
 Result
   ->  Sort
         Sort Key: ((poly_center(f1))[0])
         ->  Result
               ->  Gather Motion 3:1  (slice1; segments: 3)
                     ->  Seq Scan on polygon_tbl
                           Filter: (f1 ~ '((1,1),(2,2),(2,1))'::polygon)
 Optimizer: GPORCA
(8 rows)
```
Faultiness can be reproduced only about 1 in 5 times, if case is run using pg_regress along with other tests.

If the queries are picked from test cases and run seperately, faultiness could not be reproduced.
But if we remove the ANALYZE on table, we can see the faulty plan.

FIX:
By moving the ANALYZE command after all the insert queries of the table, it could be observed that the faulty plan is not occurring.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by 24nishant — COMMENTED** [review]
1. Can you please share the effect of moving 'Analyze' Command below the two 'Insert commands. Eg from the memo, how costing changed with this ?
2. Also can you please compare the results without Analyze vs with Analyze.

**Review by pobbatihari — APPROVED** [review]
LGTM

**Comment by hpbee** [comment]
> 1. Can you please share the effect of moving 'Analyze' Command below the two 'Insert commands. Eg from the memo, how costing changed with this ?

Effect of moving the analyze command below the two inserts:
- Before moving, rows are being estimated for the root group at 2.000000.
- After moving, rows are being estimated at 2.800000.

> 2. Also can you please compare the results without Analyze vs with Analyze.

Without analyze, rows are being estimated for the root group at 1.000000 when I ran the commands locally and the wrong plan is being generated.

**Review by 24nishant — APPROVED** [review]
Paired with @hpbee to check the query plans/memo differences in different scenarios. 
**The fix looks good to me.**

**Pull request merged**
