### PR TITLE
Remove Codegen wholesale from GPDB  5X_STABLE

### PR DESCRIPTION
**Pull request by sambitesh**

### CODE REVIEW

**Comment by hsyuan** [comment]
The pipeline is red. Can you take a look? I can't load the concourse page.

**Comment by danielgustafsson** [comment]
What is the rationale for backporting the removal of codegen? Seems to be an invasive change on a stable branch with litle gain here.

**Comment by d** [comment]
@hsyuan seems to be an unrelated issue where ubuntu build was broken due to conan upgrade. I'll rebase in 5 minutes

**Comment by d** [comment]
Conan runs happily. I'm babysitting the build

**Comment by Eulerizeit** [comment]
@vraghavan78 can Daniel get an answer to his question?

**Comment by hsyuan** [comment]
@danielgustafsson it will be easy to maintain 2 branches with less divergence, especially for the pipeline, as well as ease our work to port or cherry-pick commits from master branch.

**Comment by danielgustafsson** [comment]
> On 16 Jan 2018, at 20:40, Haisheng Yuan <notifications@github.com> wrote:
> 
> @danielgustafsson it will be easy to maintain 2 branches with less divergence, especially for the pipeline, as well as ease our work to port or cherry-pick commits from master branch.

I wouldn’t expect the presence of codegen to cause any issues in backporting, and with it being turned off by default the pipeline would be unchanged, no? It just seems odd to remove a very large feature, even one not turned on by default, in a stable branch minor release without a deprecation notice. 

It’s not a hill for me though, so if removal is the concensus then I won’t put up a fight, just seems odd given the very low benefit.

**Comment by d** [comment]
Daniel, the rationale has been that codegen is a feature we didn't ship, do not continuously test (not just "turned off by default"), and we as a community are *not committed* to maintain and support -- not in any commercial releases, but not even as an open source project. I hope this answer provides some clarity to our incentives.

**Comment by danielgustafsson** [comment]
> On 17 Jan 2018, at 16:38, Jesse Zhang <notifications@github.com> wrote:
> Daniel, the rationale has been that codegen is a feature we didn't ship, do not continuously test (not just "turned off by default"), and we as a community are not committed to maintain and support -- not in any commercial releases, but not even as an open source project. I hope this answer provides some clarity to our incentives.
> 
Well, we did ship it and included instructions on how to build it in the main README, but I understand your rationale. Anyway, as I said, I’m not objecting. Thanks for clarifying

**Pull request merged**
