### PR TITLE
Misc regress cleanup

### PR DESCRIPTION
**Pull request by hlinnaka**
Miscellaneous cleanup for regression tests, for things that caught my eye while working on other stuff.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@pengzhout, since you're hacking around the bugbuster suite too, can you have a quick look at this, please?

**Comment by pengzhout** [comment]
@hlinnaka can you help to remove world test cases in this PR

**Comment by hlinnaka** [comment]
On 11/10/2016 08:17 AM, Tang Pengzhou wrote:
> @hlinnaka can you help to remove world test cases in this PR

The tables created by the 'bugbuster/world' test case seem to be used by 
the 'bugbuster/with_clause' test that runs after it. Looking at 
'bugbuster/with_clause', I think all or most of those tests are 
redundant with the 'qp_with_clause', in the main regression suite. My 
advice would be to go through the test queries in 
'bugbuster/with_clause' to verify that they exist in 'qp_with_clause' 
already, and remove them. After you get rid of 'bugbuster/with_clause', 
you can remove 'bugbuster/world' too.

- Heikki

**Comment by hlinnaka** [comment]
Ok, I confirmed that all the queries in 'bugbuster/with_clause' are in qp_with_clause already, so I removed that and 'world' as well.

**Pull request merged**
