### PR TITLE
Improving Vagrant script for automatic GPDB build and installation

### PR DESCRIPTION
**Pull request by 0x0FFF**
Vagrant script was improved to include additional GPDB dependencies, and now is capable of automatic build and installation of the GPDB. Script also creates "gpadmin" user with default password "changeme", utilizes separate host-only network to make it work regardless of the host internet connection. Script automatically configures OS settings to run GPDB, installs it and starts it

### CODE REVIEW

**Comment by davecramer** [comment]
second attempt at vagrant up after vagrant halt results in 

Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` gpdb /gpdb
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` gpdb /gpdb

The error output from the last command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device

**Comment by 0x0FFF** [comment]
@davecramer, the issue is related to the command "yum update" that updates the kernel, which breaks VirtualBox Guest Additions, thus you are no longer able to mount the shared drives. But the process of updating the VirtualBox Guest Additions depends on the version of VirtualBox used, so the simple solution would be just to remove the "yum update" from the setup script - this step is not mandatory as you're running the latest version of CentOS either way (and instead of "yum update" later you can just replace the box)

**Comment by danielgustafsson** [comment]
The previous version of the documentation provided a tutorial for setting upp GPDB, this is information I think we should preserve but perhaps on the wiki rather than in the Vagrant documentation? Unless anyone objects I consider this a mental TODO to port the documentation there when/if this PR is merged.

I haven't had the time to try out the script enough to comment, will try to get some time for that over the weekend.

**Comment by davecramer** [comment]
Agreed that it doesn't belong, however my mental TODO's are pretty much
destined to end up in the bin (not making any comment on yours).
I'd prefer that we update a README somewhere on the site *before* accepting
this PR

Dave Cramer

**Comment by 0x0FFF** [comment]
In my opinion GPDP installation steps are pretty well defined in GPDB Installation Guide, but of course we can duplicate them to the wiki. GPDB build steps description again should not be part of the Vagrant readme, but rather a separate piece of information. But both Installation Guide and Build Guide might have links to the scripts I added as a possible implementation of this (like `vagrant-build.sh` is a way to build GPDB, `vagrant-condigure-os.sh` is the way to tune OS, `vagrant-install-inner.sh` is the option to install)

**Comment by davecramer** [comment]
I tend to agree, +1 on the PR

**Comment by danielgustafsson** [comment]
:+1: on merging this, the previous information can easily be pulled from Git history when editing the wiki next. Please send an email to -dev when merging to give a heads up about the changes for anyone using the existing Vagrant files.

**Comment by davecramer** [comment]
Closed via https://github.com/greenplum-db/gpdb/commit/45887dd32ddc302ca57a1c311fe649327a561bce

**Pull request closed without merging**
