### PR TITLE
gpstate -e: Remove progress for killed recoverseg (#13412)

### PR DESCRIPTION
**Pull request by ravoorsh**
* Problem Statement:
When gprecoverseg is running gpstate -e command displays status of the recovered segments. if the user kills the gprecoverseg process then gpstate -e continues to report the status of the old gprecoverseg.

Root Cause
gpstate -e command checks if the recovery_progress_file exists or not before displaying the gprecoverseg progress.
Since the recovery_progress_file is not removed when the gprecoverseg is forcefully killed, gpstate -e will continue to display the progress.

Fix:
To fix this issue, gpstate -e code is modified to verify if ~/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/gprecoverseg.lock exists before reporting the gprecoverseg progress. Since the user is aware that the lock file should be removed if gprecoverseg process is killed, the double check ensures that gpstate -e does not report the progress of the old killed gprecoverseg.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by ravoorsh** [comment]
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-ravoorsh_gpstate_6xstable -- 6x pipleline is green...
Merging changes from master to 6x...please take a look.

**Comment by ashwinstar** [comment]
- So, in situations where gprecoverseg fails or exits due to SSH timeout lets say but `pg_basebackup` or `pg_rewind` continues to run in background, `gpstate -e` is not able to provide the progress reporting today, correct?
- Till lock file is not removed `gpstate -e` will continue to report (incorrect) progress even with this PR?
- Apart from user killing gprecoverseg what are other reasons for lockfile to be left behind? Are all gprecoverseg failures sure including failures due to SSH timeout cleans the lock file?
- User will delete the lockfile *only* when to trigger new gprecoverseg not before that, so till then will see incorrect result and if anyways user is removing lock file to trigger new gprecoverseg then will delete the lock file and trigger gprecoverseg so new progress will be reported hence not sure what this PR is really helping

Would be better outcome instead of basing the solution just on presence of lockfile, as lockfile has PID checking if that PID is running and is `gprecoverseg` process then show the progress else not. Can refer to `CreateLockFile()` how for `postmaster.pid` checking is done for process postgres is running.

And once this PID file checking logic is coded it can be used for re-trigger of gprecoverseg where code can auto check and delete the file and let retrigger of gprecoverseg go through instead of asking user to do the checking manually and failing the command once and requiring to re-trigger.

**Comment by divyeshddv** [comment]
> * So, in situations where gprecoverseg fails or exits due to SSH timeout lets say but `pg_basebackup` or `pg_rewind` continues to run in background, `gpstate -e` is not able to provide the progress reporting today, correct?

Correct, we require the main gprecoverseg process to read from each segment's progress reporting.

>* Till lock file is not removed gpstate -e will continue to report (incorrect) progress even with this PR?

Yes

>* Apart from user killing gprecoverseg what are other reasons for lockfile to be left behind? Are all gprecoverseg failures sure including failures due to SSH timeout cleans the lock file?

Only `kill -9` on main process will leave the lock file behind. Every other failure/kill will clean up the lock file

>* User will delete the lockfile only when to trigger new gprecoverseg not before that, so till then will see incorrect result and if anyways user is removing lock file to trigger new gprecoverseg then will delete the lock file and trigger gprecoverseg so new progress will be reported hence not sure what this PR is really helping

For this story, we assumed that the user would remove the lock file immediately after every time they do a `kill -9`. Perhaps we can add a docs note to do that as expected/best practice

>* Would be better outcome instead of basing the solution just on presence of lockfile, as lockfile has PID checking if that PID is running and is gprecoverseg process then show the progress else not. Can refer to CreateLockFile() how for postmaster.pid checking is done for process postgres is running.

Agree. This would be better, and also cover the `kill -9` case.

**Comment by ashwinstar** [comment]
> For this story, we assumed that the user would remove the lock file immediately after every time they do a kill -9. Perhaps we can add a docs note to do that as expected/best practice

I think that assumption is incorrect. Plus, even if documented hardly anyone would read/follow it unless impact is felt from it. Only known impact is not able to run gprecoverseg next time hence when one faces the problem, action will be taken on it, which is on next gprecoverseg trigger.

**Comment by ashwinstar** [comment]
I am closing this PR. Let's first work on main branch PR https://github.com/greenplum-db/gpdb/pull/13606, finalize and commit the same, then can backport it to 6X_STABLE. No point in keeping this PR open till then as nothing will be done for this.

**Pull request closed without merging**
