### PR TITLE
Change select.select to select.poll in gpsubprocess

### LINKED ISSUE #6176: Limited number of primary segments on one machine
## Summary
Greenplum database does not allow to run more than 44 primary segments simultaneously on one machine.

## Description
Hereinafter, the term "machine" denotes an operating system environment. All GPDB segments are considered to belong to one GPDB cluster.

Current implementation of `gpMgmt/bin/gppylib/gpsubprocess.py` limits the number of segments running on one machine at the same time.

Part of `gpsegstart` output:
```
[ERROR]:-filedescriptor out of range in select()
Traceback (most recent call last):
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 711, in run
    self.exec_context.execute(self)
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 436, in execute
    (rc, stdout_value, stderr_value) = self.proc.communicate2(input=self.stdin)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 67, in communicate2
    self._read_files(timeout,output,error)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 122, in _read_files
    (rset,wset,eset) = self.__select(readList,writeList, errorList, timeout)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 216, in __select
    return select.select(iwtd, owtd, ewtd, timeout)
ValueError: filedescriptor out of range in select()
```

In this example, 90 segments were launched on one machine. This requires  (4005) connections to be opened on the same machine for GPDB segments to communicate, while `select.select()` call supports no more than 1024 file descriptors.

 (946) is maximum possible number of connections that can be served by `select.select()`, which means 44 is the limit on the number of GPDB primary segments on one machine.

## Proposed solution
Change [`select.select()`](https://docs.python.org/2/library/select.html#select.select) to [`select.poll()`](https://docs.python.org/2/library/select.html#select.poll) call. This allows an unlimited number of primary segments to be run simultaneously on one machine.

### PR DESCRIPTION
**Pull request by leskin-in**
This closes #6176 .

In `gpMgmt/bin/gppylib/gpsubprocess.py`, change [`select.select()`](https://docs.python.org/2/library/select.html#select.select) to [`select.poll()`](https://docs.python.org/2/library/select.html#select.poll) call.

This removes the limit on number of primary segments that could be run on one machine. The patch was tested against the case #6176, and it fixes the described error.

### CODE REVIEW

**Comment by Eulerizeit** [comment]
strictly out of curiosity, what is the use case for more than 44 primaries on a host?

**Comment by ivannovick** [comment]
@skahler-pivotal can you review this?

**Comment by ashwinstar** [comment]
If this is only thing blocking us and opens it up from supporting that usecase as well :+1: for the change.

**Comment by jchampio** [comment]
I already responded to the [original issue](https://github.com/greenplum-db/gpdb/issues/6176), but for this PR implementation in particular, keep in mind that [`poll()` is not guaranteed to be available on all platforms](https://docs.python.org/2/library/select.html#select.poll). The built-in Python that ships on macOS, for instance:
```
→ /usr/bin/python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import select
>>> select.poll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'poll'
```
Since we ship our own Python for now, we might decide that this isn't an issue, but I know we've been trying to move away from vendored Python in general.

**Comment by skahler-pivotal** [comment]
if we are talking about moving to something that may only have specific platform support, should we look at using epoll() ?

**Comment by leskin-in** [comment]
@jchampio ,
Thank you for useful comments! Taking into consideration https://github.com/greenplum-db/gpdb/pull/6177#issuecomment-439989034 and https://github.com/greenplum-db/gpdb/issues/6176#issuecomment-442159094, I propose to close this PR and switch to a solution with capped thread pool size.

A possible implementation is https://github.com/greenplum-db/gpdb/pull/6413.

**Comment by jchampio** [comment]
@leskin-in Sounds good! Closing in favor of #6413.

**Pull request closed without merging**
