### PR TITLE
gpexpand: provide UDF to query the status

### PR DESCRIPTION
**Pull request by pivotal-ning-yu**
A UDF gp_expand_get_status() is defined to query the gpexpand status.

The status is determined from gpexpand status file and schema tables.
The output contains three columns: code, status and detail.

- code: an integer code of the status.
  - 0: expansion is not in progress;
  - 1xx: the initialization phase;
  - 2xx: the redistribution phase;
- status: the status name in text;
- detail: the detail name in text;

Both status and detail are loaded from the gpexpand status file and
schema tables, they are not always meaningful.  When we only care about
whether gpexpand is in progress we could simply query like this:

    SELECT code > 0 as expansion FROM gp_expand_get_status();

During redistribution phase the progress is displayed as detail, but
only when queried with the right database.

Also introduced a new status file for gpexpand phase2, it is used as the
only indication for phase2.  Its content is the name of the database of
the gpexpand schema tables.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Pass `make installcheck`

### CODE REVIEW

**Comment by hlinnaka** [comment]
Why? What is the problem this solves?

**Comment by pivotal-mike** [comment]
> Why? What is the problem this solves?

Basically we are committed to delivering the new gpexpand for GPDB 6.  Given the amount of work and how contentious this process has been we are landing the minimum catalog changes needed so that we can move forward with GPDB 6 and still retain the ability to deliver an improved gpexpand during the GPDB 6 release.

Due to the lack of developer consensus on this we need to break the logjam.

**Comment by hlinnaka** [comment]
On 14 February 2019 19:23:29 EET, Michael Roth <notifications@github.com> wrote:
>> Why? What is the problem this solves?
>
>Basically we are committed to delivering the new gpexpand for GPDB 6. 
>Given the amount of work and how contentious this process has been we
>are landing the minimum catalog changes needed so that we can move
>forward with GPDB 6 and still retain the ability to deliver an improved
>gpexpand during the GPDB 6 release.

What ability for improvement does this provide?

- Heikki

**Comment by pivotal-mike** [comment]
Specifically this allows utilities to later detect where in the expand
process we are so that they can take or prevent actions that might result
in problems.

**Comment by hlinnaka** [comment]
> Specifically this allows utilities to later detect where in the expand process we are so that they can take or prevent actions that might result in problems.

Is there a live bug in that area currently, or? Which utilities need to know about this?

**Comment by pivotal-mike** [comment]
No - this is feature work.  For context see
https://github.com/greenplum-db/gpdb/pull/6726.  The intent is to land this
work in GPDB 6 post beta.  To avoid catalog changes we have requested
developers open this PR now to unblock things.

**Comment by hlinnaka** [comment]
> No - this is feature work.

What is the feature?

> For context see #6726. The intent is to land this work in GPDB 6 post beta. To avoid catalog changes we have requested developers open this PR now to unblock things.

Looking at #6726, there were calls to the new function in a few programs. If that's all this is for, let's bite the bullet and include those calls in this PR, so that this can be reviewed as whole, rather than add dead code that might or might not be useful in the future.

@dkrieger-pvtl raised some concerns at #6726 about the new state files. Those were legitimate concerns. I'm worried that this will add more state that can go out of sync if something goes wrong.

**Comment by pivotal-ning-yu** [comment]
Hi @hlinnaka @pivotal-mike , thanks for your discussions, we had a team discussion about this topic and want to propose a simplified plan B:

1. give up on providing a C api
2. do not introduce a new phase2 status file
3. only provide a python api to check the status
4. the python api scans all the dbs to find the phase2 status schema, as what gpexpand does
5. for components in C or other languages that are interested in the gpexpand status, they should find their own ways to do the check

Do you think this is acceptable?  Please let me know your ideas, thanks in advance.

**Comment by hlinnaka** [comment]
I had a quick chat off-list with Simon Gao. He confirmed the user-visible features that we're currently missing on master, that this PR will enable:

> The missing user-visible gpexpand features are: 
> 1) don't allow gpconfig/gppkg/gpcheckcat to run in gpexpand phase 1
> 2) show gpexpand phase 1 & 2 detail message when run "gpstate -x" 

The checks (1) are exactly the checks that were discussed earlier as part of PR #6726, commit https://github.com/greenplum-db/gpdb/pull/6726/commits/e45c051eca0be168a1cdd8c221afca343efc39dd. That was a small patch, and since those are must-have before GPDB 6, and we have the code already, let's include that in this PR, rather than trying to do it in two pieces.

(2) is new. I don't know what that's going to look like, but presumably it's going to also be a very small patch, once we have the required backend functions to get the state. So I'd recommend including that in the same PR as well. That way, the PR will cover all the new functionality that is required for GPDB 6, and we don't need to guess whether we have everything we'll need later.

**Comment by hlinnaka** [comment]
> Hi @hlinnaka @pivotal-mike , thanks for your discussions, we had a team discussion about this topic and want to propose a simplified plan B:
> 
>     1. give up on providing a C api
> 
>     2. do not introduce a new phase2 status file
> 
>     3. only provide a python api to check the status
> 
>     4. the python api scans all the dbs to find the phase2 status schema, as what gpexpand does
> 
>     5. for components in C or other languages that are interested in the gpexpand status, they should find their own ways to do the check
> 
> 
> Do you think this is acceptable? Please let me know your ideas, thanks in advance.

Ok, sounds good, if that covers the needs of the new features. Is that lightweight enough for gpstate?

BTW, instead of allowing the user to specify the database for the `gpexpand` schema, could we just always create it in the `postgres` database? That would simplify things.

**Comment by pivotal-ning-yu** [comment]
On Fri, Feb 15, 2019 at 5:46 PM Heikki Linnakangas <notifications@github.com>
wrote:

> Hi @hlinnaka <https://github.com/hlinnaka> @pivotal-mike
> <https://github.com/pivotal-mike> , thanks for your discussions, we had a
> team discussion about this topic and want to propose a simplified plan B:
>
> 1. give up on providing a C api
>
> 2. do not introduce a new phase2 status file
>
> 3. only provide a python api to check the status
>
> 4. the python api scans all the dbs to find the phase2 status schema, as what gpexpand does
>
> 5. for components in C or other languages that are interested in the gpexpand status, they should find their own ways to do the check
>
> Do you think this is acceptable? Please let me know your ideas, thanks in
> advance.
>
> Ok, sounds good, if that covers the needs of the new features. Is that
> lightweight enough for gpstate?
>
gpexpand status is not checked and displayed in gpstate by default, it's
only displayed with a newly added argument `-x`, we suppose the user will
not use this argument most of the time.

> BTW, instead of allowing the user to specify the database for the gpexpand
> schema, could we just always create it in the postgres database? That
> would simplify things.
>
This sounds reasonable, however I'm not sure whether there are other
considerations by the design of gpexpand for current behavior.  Will
permission be a problem?  Or will the postgres db be dropped?  Anyway I can
come out a prototype PR for further discussions.

**Comment by pivotal-ning-yu** [comment]
https://github.com/greenplum-db/gpdb/pull/7013 is opened to provide the python api, please move discussions to that one.

Close current one w/o merging, thanks for all the suggestions.

**Pull request closed without merging**
