### PR TITLE
merge passwordcheck plugin from pg

### PR DESCRIPTION
**Pull request by weinan003**
commit: c742b795ddce852975c513a04c29966420937553(pg)

### CODE REVIEW

**Comment by hlinnaka** [comment]
We'll get this as part of the PostgreSQL 9.0 merge. Which should happen before GPDB6 release, anywayI don't see a reason to cherry-pick it now.

**Comment by lij55** [comment]
Thanks, Heikki. When will the merge of this feature happen?

**Comment by hlinnaka** [comment]
On 10/31/2017 09:53 AM, Jasper Li wrote:
> Thanks, Heikki. When will the merge of this feature happen?

Sometime in spring, if all goes well. The plan is to catch up to 9.1 for 
the GPDB6 release, which is expected to happen around September 2018.

- Heikki

**Comment by ivannovick** [comment]
Hi guys, i have a big new client that expressed interest in this ontop of GPDB 5.x in early 2018.  If the merge is not creating a total mess, it would be a huge positive impact to backport to this onto GPDB 5 to support the client.

**Comment by lij55** [comment]
As there is a customer wait for this feature, we will merge it and backport it to GPDB5 if the PR itself is correct so that we don't need to keep an eye on this all the time.
Is it acceptable? @hlinnaka  @Eulerizeit

**Pull request merged**
