### PR TITLE
Fix leaking hash tables when inserting into AO tables

### PR DESCRIPTION
**Pull request by Smyatkin-Maxim**
Fixes https://github.com/greenplum-db/gpdb/issues/14348

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Review by interma — APPROVED** [review]
LGTM

**Comment by interma** [comment]
@Smyatkin-Maxim your PR looks good.
Just to confirm: is it the RCA of https://github.com/greenplum-db/gpdb/issues/14348? Did you use the `pgbench` of 14348 to verify this PR?
Thanks.

**Comment by Smyatkin-Maxim** [comment]
> @Smyatkin-Maxim your PR looks good. Just to confirm: is it the RCA of #14348? Did you use the `pgbench` of 14348 to verify this PR? Thanks.

Yes, the leak in pgbench goes away with this PR on my env.

**Comment by kainwen** [comment]
@Smyatkin-Maxim Hi, thanks so much for your contribution.
We are going to push this.

1. Would you please help add more comments in commit message? 
2. if possible, would you please share how you locate this leak so that other developers can learn.

Thanks again.

**Review by QingMa-gp — APPROVED** [review]
Code change LGTM, thanks for your contribution.

**Pull request merged**
