### PR TITLE
Move remaining GPDB modules to gpcontrib

### PR DESCRIPTION
**Pull request by danielgustafsson**
During the previous effort to separate out the Greenplum specific modules from contrib/ into gpcontrib/, a few modules were left in contrib/. This moves formatter, formatter_fixedwidth, extprotocol and indexscan over vanilla without any changes apart from required changes to the build infrastructure.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Unless there are objections soon, I will merge this to master.

**Comment by danielgustafsson** [comment]
Rebased on top of HEAD for a refreshed CI run

**Comment by berlin-ab** [comment]
Looks like the build passed. Let's merge.

**Comment by danielgustafsson** [comment]
I've changed my mind on this, and will close at least until we GA.. this will cause pointless cherry-pick conflicts in backporting for very little gain.

**Pull request closed without merging**
