### PR TITLE
Remove pg_appendonly_alter_column catalog table.

### PR DESCRIPTION
**Pull request by asubramanya**
This table is not used anywhere in the code.

### CODE REVIEW

**Comment by ivannovick** [comment]
NICE!!!! love it

**Comment by hlinnaka** [comment]
Yep, amazing that there's a whole catalog table being unused :-)

**Comment by ashwinstar** [comment]
Looks good. Just would have to regenerate the JSON file after rebasing from latest master.

**Comment by asimrp** [comment]
Looks good, thanks!

**Comment by asubramanya** [comment]
Thanks everyone for the review. Pushed to master.

**Pull request closed without merging**
