### PR TITLE
gpstop: use correct postmaster.pid file line number for ipcrm

### PR DESCRIPTION
**Pull request by ashwinstar**
postmaster.pid file format changed and postmaster status is recorded
on last line. CleanSharedMem() was coded with expectation last line
will always be shared memory key, no more holds true due to it.

Modifing logic to explicit look at line 7 of postmaster.pid file for
shared memory key to make it robust against future enhacements.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by kalensk** [comment]
Implementation looks good. I'm wondering if the existing tests in [test_unit_unix.py](https://github.com/greenplum-db/gpdb/blob/6645278cab7075922ac3016af770c8cd3e8e7716/gpMgmt/bin/gppylib/operations/test/unit/test_unit_unix.py#L13) still pass or need to be updated? I tried pulling the branch to attempt to run the test_unit_unix.py tests, but ran into some environment issues or not knowing how best to run the unit tests with python3...maybe someone can help.

```
 python3 -m unittest discover --verbose -s ./gppylib/ -p "test_unit_unix.py"

ImportError: Failed to import test module: db.test
Traceback (most recent call last):
  File "/Users/kkrempely/workspace/gpdb7/gpMgmt/bin/gppylib/db/dbconn.py", line 14, in <module>
    import pgdb
ModuleNotFoundError: No module named 'pgdb'

...
```

**Comment by ashwinstar** [comment]
I did run `make check` and `gpstop` behave tests and they had passed for me.

for `No module named 'pgdb'`, mostly you would have to do `pip3 install pygresql`

**Review by kalensk — APPROVED** [review]

**Comment by hlinnaka** [comment]
Why does gpstop call ipcrm in the first place? If Postgres is stopped gracefully, it will clean up shared memory at shutdown. If it's stopped ungracefully, it will clean up the shared memory on next restart. Also, starting with PostgreSQL 9.4 (i.e. GPDB 6), the system uses only a tiny amount of System V shared memory, so even if it's leaked, it is unlikely to become a problem.

**Review by asimrp — COMMENTED** [review]
@hlinnaka I was wondering why System V shared memory usage was reduced and what alternative is adopted.  The alternative is mmap and the reason for the switch and more details can be found in this commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=b0fc0df9364d2d2d17c0162cf3b8b59f6cb09f67.

Subsequently, the System V shared memory was found useful on platforms such as AIX and BSDs and the GUC `shared_memory_type` was introduced: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=f1bebef60ec8f557324cd3bfc1671da1318de968

Does it make sense to keep the logic to remove System V shared memory segments?

**Comment by ashwinstar** [comment]
Thanks @hlinnaka and @asimrp I feel deleting the logic instead of fixing it seems better. Given `PGSharedMemoryCreate()` for "Dead Postgres segments pertinent to this DataDir are recycled if found", I feel no need to really have this logic. GPDB7 has quite bit of development cycle remaining and if developers (where we unclean shutdown very often) feel need for this on any platform we can bring it back. Currently, I see no need for it and `gpstop` unit and behave tests passed fine with this PR.

**Pull request merged**
