### PR TITLE
Enable dblink in GPDB

### PR DESCRIPTION
**Pull request by HaozhouWang**
dblink is a bulit-in module of postgresql, this patch enable it in GPDB.

1. Enable compiling dblink with GPDB
2. Update and enable dblink test cases

Known issue:

1. The following functions are not supported by GPDB and disabled temporarily
   due to GPDB behavior changed.
   dblink_send_query()
   dblink_is_busy()
   dblink_get_result()

2. Anonymous connection and connection by name are not supported in a nested statement with
   both write and read. E.g.
   INSERT INTO tblname SELECT * FROM dblink(['connName'],'SELECT * FROM otherdb.tblname') as tbl;
   Currently, only connection with connection string is supported in such statements.

Signed-off-by: Peifeng Qiu <pqiu@pivotal.io>
Signed-off-by: Yuan Zhao <yuzhao@pivotal.io>
Signed-off-by: Jianxia Chen <jchen@pivotal.io>

### CODE REVIEW

**Comment by lij55** [comment]
Hi @davecramer ,
external tables should be more than that.

**Comment by adam8157** [comment]
Please give blow steps a try? It should work I suppose

1, revert "Add dblink.sql for installcheck-world test in Concourse"

2, add a dependency of installcheck, which copies `$GPHOME/share/postgresql/contrib/dblink.sq`l to `contrib/dblink` directory

3, try `make installcheck`

**Comment by HaozhouWang** [comment]
Thanks for your review. Updated.

**Comment by HaozhouWang** [comment]
Thanks review, merged.

**Pull request merged**
