### PR TITLE
Remove tests on default_storage_parameters GUC in different contexts.

### PR DESCRIPTION
**Pull request by hlinnaka**
It's a GUC, like any other. Testing that it's set correctly in every
possible context, when set to a user, when set on a database, etc., seems
excessive.

Also, if by some freak incident the GUC is set incorrectly, the
consequences are not very serious. The table just gets created with wrong
parameters, but it's still a valid table, and if you look at it with e.g.
\d, you will see the options actually used.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@asimrp, @ashwinstar, your thoughts on this? It's just a GUC... Parsing default_storage_parameters is more complicated than most GUCs, but that doesn't affect the hierarchy of where the current value comes from (local SET, per-user setting, per-database setting, or postgresql.conf). It's a judgment call, but I think these tests are pretty worthless. Removing them should reduce the runtime of the cs-storage test suite by about 4 minutes.

**Comment by danielgustafsson** [comment]
Skimming through this enormous patch, I fail to be excited about the tests in there. My $0.02 is :+1: on this.

**Comment by ashwinstar** [comment]
I am yet to look into the tests completely but I do not think the tests should be fully removed.

Other GUC don't have the tests or something wrong with this GUC is not resulting in DUDL (data unavailable or data loss) doesn't mean it should not be tested. Any divergence from expected behavior is a BUG and not good experience. There were issues seen in field with this GUC causing incorrect table type to be created on master and some segment Or parsing of it having issues Or I think the way precedence needs to be given to GUC vs defaults vs create table time values had few issues.
Other GUCs don't have validation is again not good rational to lose out test for this GUC. I think these tests were written while coding the feature as part of TDD mostly. So, definitely not in favor to loose them out completely.

If there is any redundancy or optimizations which can be done sure but not out right removal. Also, since now we are using this GUC generate tests (parametrization of AO tests) its becomes extremely more important for it to function correctly else invalidates those tests as well.

**Comment by hlinnaka** [comment]
On 02/22/2017 06:18 PM, Ashwin Agrawal wrote:
> I am yet to look into the tests completely but I do not think the
> tests should be fully removed.
>
> Other GUC don't have the tests or something wrong with this GUC is
> not resulting in DUDL (data unavailable or data loss) doesn't mean it
> should not be tested. Any divergence from expected behavior is a BUG
> and not good experience.

Sure, that wasn't my primary argument. My primary argument was that it's 
hard to see how the GUC would behave differently, when it's set from the 
postgresql.conf file, or directly with SET. Testing the "hierarchy" of 
setting GUCs might be useful, for any and all GUCs, but testing all the 
different combinations of gp_default_storage_parameter options, not so much.

> There were issues seen in field with this GUC causing incorrect table
> type to be created on master and some segment Or parsing of it having
> issues Or I think the way precedence needs to be given to GUC vs
> defaults vs create table time values had few issues. Other GUCs don't
> have validation is again not good rational to lose out test for this
> GUC. I think these tests were written while coding the feature as
> part of TDD mostly. So, definitely not in favor to loose them out
> completely.

Differences between the master and segment ought to be caught by 
gpcheckcat, so I'm not too worried about that.

But fair enough, if you feel like these are worth keeping, I'll leave 
them alone, and let someone else deal with them later.

- Heikki

**Comment by hlinnaka** [comment]
In PostgreSQL 9.0, the way the per-database and per-role settings are stored in the catalogs was changed, to support settings that are per-role, in a specific database. `pg_database.datconfig` and `pg_authid.rolconfig` columns are gone, the settings are now stored in the new `pg_db_role_setting` table.

As a result, many of these TINC tests will stop working, as they queries pg_database.datconfig, to verify that a setting took effect. We can fix them, of course, but I'm reluctant to spend the time, as I still think these tests are pretty worthless to begin with. Hence, I'm re-opening this PR. @ashwinstar, now that some time has passed, and in order to keep these tests working we'd actually need to spend some hours to fix them, how would you feel about removing them now?

**Comment by hlinnaka** [comment]
I failed to mention it in the discussion a year ago, but we have some test coverage for these things in the main regression test suite already, in the `dsp` test. It doesn't test all the different combinations of different storage options in different contexts, but I think it's good enough. For example, it does test setting the GUC with ALTER DATABASE, and connecting to that database, and also overriding that with a SET command.

**Comment by ashwinstar** [comment]
@hlinnaka  Now that I look into the tests in detail, yes sounds good candidate for removal.

Please add coverage for these is ICW `dsp.sql` instead as seems missing
- Setting the gp_default_storage_options with --masteronly or -m option is not supported
- Setting different seg and master value is expected to fail
- `gpconfig -s gp_default_storage_options` show show current settings
- CTAS
- Add/split/exchange partition to a partition table after the gp_default_operations changed with GUC value

**Comment by ashwinstar** [comment]
Adding the missing coverage in PR https://github.com/greenplum-db/gpdb/pull/4519. So, this PR can be merged.

**Comment by ashwinstar** [comment]
@hlinnaka I merged this in.

**Comment by hlinnaka** [comment]
On 09/02/18 02:49, Ashwin Agrawal wrote:
> Adding the missing coverage in PR https://github.com/greenplum-db/gpdb/pull/4519. So, this PR can be merged.

Wonderful, thanks Ashwin!

- Heikki

**Pull request merged**
