### PR TITLE
Renaming code_generator to codegen_utils

### PR DESCRIPTION
**Pull request by karthijrk**
In this pull request, we are just renaming existing code_generator --> codegen_utils or CodeGenerator -> CodegenUtils. CodeGenerator class manages runtime code generation for a single LLVM module but doesn't do actual code generation. In order to make the name closer to its semantics, we are renaming it to CodegenUtils.

@hardikar @armenatzoglou @gcaragea  Please take a look when you get chance.

### CODE REVIEW

**Comment by armenatzoglou** [comment]
LGTM +1.

**Comment by hardikar** [comment]
LGTM

**Comment by gcaragea** [comment]
New naming makes more sense, thanks. 
+1

**Comment by karthijrk** [comment]
Thanks all for the review and this is pushed to master

**Pull request closed without merging**
