### PR TITLE
External tables refactoring

### PR DESCRIPTION
**Pull request by hlinnaka**
This refactors the way external tables are handled throughout the backend code, to make external tables look and feel more like foreign tables internally. This includes the small change to catalog representation that I proposed as a separate PR the other day in https://github.com/greenplum-db/gpdb/pull/9431. It makes sense to consider that as part of this bigger PR so I closed that in favor of this one.

What this does *not* do:
- Does not change user-visible behaviour, except for minor differences in EXPLAIN, error messages, psql output etc. See test output changes for examples.
- Does not change the way external tables are pg_dumped. The CREATE EXTERNAL TABLE syntax is still used.
- Does not modify the existing external table API. This is purely moving stuff around in the core. The external protocol API unchanged, but now the backend code accesses it mostly through an internal "shim" FDW.
- Does not modify any existing external protocols to use the FDW APIs. They all work through the shim FDW that calls into the external tables API.

Please look at the the commit messages for more details.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@gkokolatos, this is followup work per the discussion in https://github.com/greenplum-db/gpdb/pull/9431. I was able to remove most of the `rel_is_external_table()` calls in the planner and executor with these changes. It was easier than I thought, so let's just do it.

With this PR, the `pg_exttable` catalog still exists, and is still used to hold the properties of an external table. Per our discussion on slack, we should refactor that away too, so that the properties would be stored as options on the foreign table instead, in `pg_foreign_table.ftoptions`. Feel free to pick up that work if you're interested.

**Comment by lij55** [comment]
Thanks, @hlinnaka .

**Comment by JunfengYang** [comment]
I think some of the options should belong to the foreign server for example `LOCATION`. 
Currently, it seems the special foreign server is pre-created for all external tables and not interact with external table fdw routines. 

I'm not sure the discussion details you had. From my point of view.
How about creating a foreign server for each external table and once remove the `pg_exttable` catalog,
use a view to extract external table information from the foreign table and foreign server catalog.

**Comment by hlinnaka** [comment]
> I think some of the options should belong to the foreign server for example `LOCATION`.
> Currently, it seems the special foreign server is pre-created for all external tables and not interact with external table fdw routines.
> 
> I'm not sure the discussion details you had. From my point of view.
> How about creating a foreign server for each external table and once remove the `pg_exttable` catalog,
> use a view to extract external table information from the foreign table and foreign server catalog.

I totally agree. However, this is a big refactoring overall, so I wanted to do it in smaller steps. That's why I'd like to do it as a separate PR after this one.

I'm not sure what exactly it should look like yet. I think we should have separate FDW for different kinds of external tables. One for EXECUTE type, another for PXF, and so on. I'm not sure how the options should be split between foreign server and table objects, as current external tables don't have the "server" level. Might be different for different FDWs, too.

**Comment by hlinnaka** [comment]
There's one failure in the regression tests, caused by different behaviour when you have an external table as a partition of a partitioned table, and some of the rows don't match the partition's constraints. See discussion: https://groups.google.com/a/greenplum.org/forum/#!msg/gpdb-dev/v-ZTreV0ud4/gZutaKYNDQAJ

**Comment by hlinnaka** [comment]
Pushed a bunch of fixes, for little FIXMEs, pg_dump compatibility of older server versions, and misc other little things.

I added back the checking of CHECK constraints. So the behaviour of that is now the same as in 'master'. I'm still of the opinion that we should rip it out, but now that discussion doesn't need to hold back this PR.

**Comment by lij55** [comment]
> I added back the checking of CHECK constraints. So the behaviour of that is now the same as in 'master'. I'm still of the opinion that we should rip it out, but now that discussion doesn't need to hold back this PR.

Thanks, Heikki!

**Comment by hlinnaka** [comment]
@huiliang-liu please take a look at the little change to gpload here. I'm pretty sure it's correct, but maybe you remember why the query is what it is.

**Comment by hlinnaka** [comment]
This passes the regression tests now.

Everyone seems to be on board with this on the high-level, so I have pushed this, in the interest of getting this into 'master' before we cut the iteration branch for the merging with PostgreSQL v12. It's not nice to have a large patch like this pending through the merge, as it will surely bitrot, and this patch lets us avoid a few merge conflicts. (I'm sure new big patches will appear while we're working on the merge, but that's unavoidable.)

But please do still review this!

**Comment by huiliang-liu** [comment]
> @huiliang-liu please take a look at the little change to gpload here. I'm pretty sure it's correct, but maybe you remember why the query is what it is.

It looks OK for me. Thank you @hlinnaka 
There is something wrong for windows client job in pipeline, we will fix it soon

**Pull request merged**
