### PR TITLE
pg_upgrade: dump REINDEX instructions after upgrade from GPDB4

### PR DESCRIPTION
**Pull request by jchampio**
GPDB5 changed relation indexes on disk, and so they are all invalidated when upgrading from 4. Rather than expecting the user to know what to do after that mass-invalidation, write a script to perform a `REINDEX SYSTEM`/`DATABASE` for every `db_name` we have, and point the user to it.

### CODE REVIEW

**Comment by jchampio** [comment]
Re-rolled on top of the lastest `gpdb/master` to pick up the 9.x merge changes to pg_upgrade. Also removed `REINDEX SYSTEM` -- it performs a subset of what `REINDEX DATABASE` is going to do anyway, which I missed in my initial revision.

**Comment by jchampio** [comment]
> Until the user runs it, will the upgraded system performance be enough to make it usable?

I don't have any data on that, but I do know that some pieces of the DB are simply unusable until they are reindexed (toast tables come to mind).

> Does it make sense, instead, to reindex catalog tables in all databases before handing over the upgraded system to the user?

I think it makes sense, but not as an "instead" -- UX decisions belong to gpupgrade, IMHO, and I expect that gpupgrade will run the post-processing scripts that pg_upgrade dumps.

**Comment by jchampio** [comment]
@danielgustafsson Thanks for the review!

> The REINDEX requirement needs to be documented somewhere

Is `doc/src/sgml/pgupgrade.sgml` a good place for that, or did you have something else in mind?

**Comment by mkiyama** [comment]
FYI - I created a tracker doc story for the reindex requirement after upgrade.
#159115025

**Comment by jchampio** [comment]
Thanks @mkiyama!

**Pull request merged**
