### PR TITLE
Add Dockerfile for compiling and running GPDB on centos6 and centos7

### PR DESCRIPTION
**Pull request by lavjain**
Supports building GPDB without GPORCA

Run command:
```
docker build -t gpdb-dev:centos6 centos6
docker run --rm -w /home/build/gpdb -v ~/git/gpdb:/home/build/gpdb -it gpdb-dev:centos6

docker build -t gpdb-dev:centos7 centos7
docker run --rm -w /home/build/gpdb -v ~/git/gpdb:/home/build/gpdb -it gpdb-dev:centos7
```

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Since this removes and replaces the existing Dockerfiles, this PR needs to be amended with what the difference is in implementation and support is. I'm not saying it's wrong to replace them (I don't know enough Docker for that), but there needs to be more information for the reviewers.

**Comment by d** [comment]
Have you tried using `pivotaldata/centos-gpdb-dev:6` and friends?

**Comment by danielgustafsson** [comment]
> On 18 Oct 2017, at 02:31, Jesse Zhang <notifications@github.com> wrote:
> 
> Have you tried using pivotaldata/centos-gpdb-dev:6 and friends?

I know the existing files are problematic to the point of not working, that however doesn’t change the fact that it’s a good idea to be explicit around why something is replaced since not everyone reading this PR might know that.

**Comment by cjcjameson** [comment]
There was a thread that just started on the dev mailing list: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/8Q5oX4N6vzc/Z4Z-41XFBAAJ

Can you please coordinate with @amilkh and others to come to an awesome solution that works across both your desired usages of Docker?

**Comment by amilkh** [comment]
@cjcjameson thanks for linking us here!

We have created two new PRs:
https://github.com/greenplum-db/gpdb/pull/3588
https://github.com/greenplum-db/gpdb/pull/3589

**Comment by lavjain** [comment]
@d @amilkh @danielgustafsson @cjcjameson 
The docker image concourse is using (i.e. pivotaldata/centos-gpdb-dev:7) is a private image that resides inside Pivotal-DataFabric. The end users don't have any way to customize it to their needs. 

Moreover,the resulting image for pivotaldata/centos-gpdb-dev:7 is 3.5GB in size. The docker image for centos7 in this PR is 750MB (400% improvement), while docker image for centos6 is 1.2GB (300% improvement). Please consider all the network bandwidth as well as time savings when downloading these Docker containers.

**Comment by lavjain** [comment]
Here are the errors when we use the existing Dockerfile for building an image:
```
Building wheels for collected packages: psutil, pynacl, pycparser
  Running setup.py bdist_wheel for psutil: started
  Running setup.py bdist_wheel for psutil: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9bpGiI/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpk5vd3spip-wheel- --python-tag cp26:
  Failed building wheel for psutil
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-9bpGiI/psutil/setup.py", line 353, in <module>
      main()
    File "/tmp/pip-build-9bpGiI/psutil/setup.py", line 349, in main
      setup(**kwargs)
    File "/usr/lib64/python2.6/distutils/core.py", line 138, in setup
      ok = dist.parse_command_line()
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 442, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib64/python2.6/distutils/dist.py", line 460, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 756, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib64/python2.6/distutils/dist.py", line 518, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 576, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
    File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2409, in load
      return self.resolve()
    File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/usr/lib/python2.6/site-packages/wheel/bdist_wheel.py", line 407
      ignore=lambda x, y: {'PKG-INFO', 'requires.txt', 'SOURCES.txt',
                                     ^
  SyntaxError: invalid syntax

  ----------------------------------------
  Running setup.py clean for psutil
  Running setup.py bdist_wheel for pynacl: started
  Running setup.py bdist_wheel for pynacl: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9bpGiI/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpGpw0bNpip-wheel- --python-tag cp26:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-9bpGiI/pynacl/setup.py", line 232, in <module>
      "Programming Language :: Python :: 3.6",
    File "/usr/lib64/python2.6/distutils/core.py", line 138, in setup
      ok = dist.parse_command_line()
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 442, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib64/python2.6/distutils/dist.py", line 460, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 756, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib64/python2.6/distutils/dist.py", line 518, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 576, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
    File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2409, in load
      return self.resolve()
    File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/usr/lib/python2.6/site-packages/wheel/bdist_wheel.py", line 407
      ignore=lambda x, y: {'PKG-INFO', 'requires.txt', 'SOURCES.txt',
                                     ^
  SyntaxError: invalid syntax

  ----------------------------------------
  Failed building wheel for pynacl
  Running setup.py clean for pynacl
  Running setup.py bdist_wheel for pycparser: started
  Running setup.py bdist_wheel for pycparser: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9bpGiI/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpnuDc3Lpip-wheel- --python-tag cp26:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-9bpGiI/pycparser/setup.py", line 54, in <module>
      cmdclass={'install': install, 'sdist': sdist},
    File "/usr/lib64/python2.6/distutils/core.py", line 138, in setup
      ok = dist.parse_command_line()
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 442, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib64/python2.6/distutils/dist.py", line 460, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 756, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib64/python2.6/distutils/dist.py", line 518, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 576, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
    File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2409, in load
      return self.resolve()
    File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/usr/lib/python2.6/site-packages/wheel/bdist_wheel.py", line 407
      ignore=lambda x, y: {'PKG-INFO', 'requires.txt', 'SOURCES.txt',
                                     ^
  SyntaxError: invalid syntax

  ----------------------------------------
  Failed building wheel for pycparser
```

**Comment by lavjain** [comment]
Adding @divyabhargov @pivotal-mike @schubert @edespino

**Comment by lavjain** [comment]
Updating my comment from above, here are the actual sizes:
```
pivotaldata/centos-gpdb-dev   7-gcc6.2-llvm3.7    3eae63c76f3c        7 weeks ago         3.63GB
pivotaldata/centos-gpdb-dev   6-gcc6.2-llvm3.7    9f69ed25c923        7 weeks ago         3.54GB
pivotaldata/centos-gpdb-dev   7                   4099709b2658        7 weeks ago         1.78GB
pivotaldata/centos-gpdb-dev   6                   24f711a4437d        7 weeks ago         2.23GB
.
gpdb-dev          centos7             b3c47fdc351f        3 days ago          742MB
gpdb-dev          centos6             74f1186e6fcb        3 days ago       1.25GB
```
The

**Comment by danielgustafsson** [comment]
> On 20 Oct 2017, at 18:40, Lav Jain <notifications@github.com> wrote:
> 
> @d @amilkh @danielgustafsson @cjcjameson
> The docker image concourse is using (i.e. pivotaldata/centos-gpdb-dev:7) is a private image that resides inside Pivotal-DataFabric. The end users don't have any way to customize it to their needs.
> 
> Moreover,the resulting image for pivotaldata/centos-gpdb-dev:7 is 3.5GB in size. The docker image for centos7 in this PR is 750MB (400% improvement), while docker image for centos6 is 1.2GB (300% improvement). Please consider all the network bandwidth as well as time savings when downloading these Docker containers.

Thanks for clarifying!

**Comment by amilkh** [comment]
> The docker image concourse is using (i.e. pivotaldata/centos-gpdb-dev:7) is a private image that resides inside Pivotal-DataFabric. The end users don't have any way to customize it to their needs.
Good point, Lav. Perhaps we can make the Dockerfile for that image public to resolve your concern? I'm sure it has many of the same steps as the Dockerfile you are proposing in this PR and perhaps we can merge any extra magic sauce you've added ;)
https://hub.docker.com/r/pivotaldata/centos-gpdb-dev/tags/

@divyabhargov

**Comment by lavjain** [comment]
Pushed to master and 5X_STABLE

**Comment by d** [comment]
> The docker image concourse is using (i.e. pivotaldata/centos-gpdb-dev:7) is a private image

Not true. That docker image repository has been public since May

**Comment by amilkh** [comment]
Yeah, but I think the Dockerfile for generating it is private?

One good point of this PR is that it publicizes a Dockerfile which makes the dependencies more explicit. Although, this could also be solved by updating the README.CentOS.md or making the Dockerfiles used for `centos-gpdb-dev:7` public.

**Pull request merged**
