### PR TITLE
Remove redundant tests between bfv_legacy and qp_misc_rio

### PR DESCRIPTION
**Pull request by hlinnaka**
Most of the test cases in bfv_legacy and qp_misc_rio test files are identical. @karthijrk, @xinzweb, you added these tests about one month apart from each other. Did we accidentally port the same test twice? Can you have a look at this PR, please?

This greatly reduces the time spent on these tests. In addition to removing duplicates, I changed the auto-ANALYZE tests to load fewer rows into the test table (was 10 million, now only half a million).

### CODE REVIEW

**Comment by vraghavan78** [comment]
@hlinnaka I think there may have been duplicates in the original cdbfast/tinc tests. We will take a look. Thanks @hlinnaka for fixing this.

**Comment by karthijrk** [comment]
Thanks @hlinnaka  for looking into this. LGTM 👍

**Comment by vraghavan78** [comment]
+1

**Comment by hlinnaka** [comment]
Pushed, thanks

**Pull request closed without merging**
