### PR TITLE
Running 'make clean' does not remove objects under bin/gpcheckcloud

### PR DESCRIPTION
**Pull request by lavjain**

### CODE REVIEW

**Comment by lavjain** [comment]
Implemented suggestions.

**Comment by lavjain** [comment]
Make clean did not work out, so reverted the change.

**Comment by danielgustafsson** [comment]
Huh? What was the error?

**Comment by lavjain** [comment]
It went in a infinite loop
```
Makefile:58: warning: overriding recipe for target `clean'
../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
rm -f gpcloud.so   libgpcloud.a
make[8]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
Makefile:58: warning: overriding recipe for target `clean'
../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
rm -f gpcloud.so   libgpcloud.a
make[9]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
Makefile:58: warning: overriding recipe for target `clean'
../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
rm -f gpcloud.so   libgpcloud.a
make[10]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
Makefile:58: warning: overriding recipe for target `clean'
../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
rm -f gpcloud.so   libgpcloud.a
make[11]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
Makefile:58: warning: overriding recipe for target `clean'
../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
rm -f gpcloud.so   libgpcloud.a
make[12]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
Makefile:58: warning: overriding recipe for target `clean'
../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
rm -f gpcloud.so   libgpcloud.a
make[13]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
Makefile:58: warning: overriding recipe for target `clean'
../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
rm -f gpcloud.so   libgpcloud.a
make[14]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
Makefile:58: warning: overriding recipe for target `clean'
../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
rm -f gpcloud.so   libgpcloud.a
```

**Comment by danielgustafsson** [comment]
> On 27 Sep 2017, at 00:45, Lav Jain <notifications@github.com> wrote:
> 
> It went in a infinite loop
> 
> Makefile:58: warning: overriding recipe for target `clean'
> ../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
> rm -f gpcloud.so   libgpcloud.a
> make[8]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
> Makefile:58: warning: overriding recipe for target `clean'
> ../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
> rm -f gpcloud.so   libgpcloud.a
> make[9]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
> Makefile:58: warning: overriding recipe for target `clean'
> ../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
> rm -f gpcloud.so   libgpcloud.a
> make[10]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
> Makefile:58: warning: overriding recipe for target `clean'
> ../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
> rm -f gpcloud.so   libgpcloud.a
> make[11]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
> Makefile:58: warning: overriding recipe for target `clean'
> ../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
> rm -f gpcloud.so   libgpcloud.a
> make[12]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
> Makefile:58: warning: overriding recipe for target `clean'
> ../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
> rm -f gpcloud.so   libgpcloud.a
> make[13]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
> Makefile:58: warning: overriding recipe for target `clean'
> ../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
> rm -f gpcloud.so   libgpcloud.a
> make[14]: Entering directory `/home/build/gpdb/gpAux/extensions/gpcloud'
> Makefile:58: warning: overriding recipe for target `clean'
> ../../../src/makefiles/pgxs.mk:210: warning: ignoring old recipe for target `clean'
> rm -f gpcloud.so   libgpcloud.a

A-ha, of course. Since gpcloud is using PGXS the clean target is already defined (and working). In order to clean the files that cleanall does, simply define them as EXTRA_CLEAN and they will be removed on just "make clean”. See contrib/intarray/package/Makefile for an example.

**Comment by lavjain** [comment]
But clean does not clean up any gpcloud object files. It is still a bug because when I switch between docker and OSX, I have to manually clean up those files.

**Comment by danielgustafsson** [comment]
> On 27 Sep 2017, at 01:11, Lav Jain <notifications@github.com> wrote:
> 
> But clean does not clean up any gpcloud object files. It is still a bug because when I switch between docker and OSX, I have to manually clean up those files.

The additional files to be handled by “make clean” are configured by defining them in the EXTRA_CLEAN variable, that will automatically include them in cleaning (see src/makefiles/pgxs.mk for details).

That being said, PGXS doesn’t support projects with lots of SUBDIRs and gpcloud is full of them, so I guess adding cleanall as a prereq to clean is the way to go after all. 

Making gpcloud conform to PGXS would’ve nicer but thats scopecreeping this a bit too far. Sorry for leading you on a goose-chase

**Comment by lavjain** [comment]
Thanks, Daniel! Should I revert to the solution in the original commit i.e. cleanall if gpcloud?

**Comment by danielgustafsson** [comment]
> On 27 Sep 2017, at 19:07, Lav Jain <notifications@github.com> wrote:
> 
> Thanks, Daniel! Should I revert to the solution in the original commit i.e. cleanall if gpcloud?

Yeah, as much as I dislike not having uniform targets in the tree I think your original suggestion is the way forward here (and that suggestion is not making the uniform-target situation worse so that’s no fault of this PR).

**Pull request merged**
