### PR TITLE
Add make clean command for postgres_fdw.

### PR DESCRIPTION
**Pull request by zhaorui20005**
Add make clean command for postgres_fdw.
This commit is supplement for the last commit e7ea88e6ada4dc3fa281bb37b8eee4094d5e7386.

### CODE REVIEW

**Review by jingwen-yang-yjw — APPROVED** [review]

**Comment by hyongtao-db** [comment]
Thank you. 
Is there still test failures of postgre_fdw now? 
Could you please add some comment about why we enable make clean in commit log.

**Comment by zhaorui20005** [comment]
> Thank you. Is there still test failures of postgre_fdw now? Could you please add some comment about why we enable make clean in commit log.

No failure testing cases by now.

**Comment by zhaorui20005** [comment]
Actually, this PR is a supplement for the last commit https://github.com/greenplum-db/gpdb/commit/e7ea88e6ada4dc3fa281bb37b8eee4094d5e7386

**Review by hyongtao-db — APPROVED** [review]
Looks good.

**Pull request merged**
