### PR TITLE
Moved S3 gtest to gpAux/extensions and update gtest framework.

### PR DESCRIPTION
**Pull request by hardikar**
Gtest is a testing framework that can be used by multiple modules and not only by the gps3ext module. With this in mind, we propose to move the gtest sources to gpAux/extensions/ where other libraries can link to it. Since we intend for this framework to be used in other places within GPDB, we ported the entire gtest framework in. We also updated gps3ext makefiles to use the correct gtest directory.

Testing:
./configure and make works correctly and builds GPDB.
cd gpAux/extensions/gps3ext && make && make -f Makefile.test compiles and runs correctly.

Authors: Nikos Armenatzoglou and Shreedhar Hardikar.

### CODE REVIEW

**Comment by armenatzoglou** [comment]
@lij55 @foyzur Please take a look when you have time.

**Comment by hlinnaka** [comment]
Why? 

On 16 March 2016 23:54:13 EET, Shreedhar Hardikar <notifications@github.com> wrote:
>Gtest is a testing framework that can be used by multiple modules and
>not only by the gps3ext module. With this in mind, we propose to move
>the gtest sources to gpAux/extensions/ where other libraries can link
>to it. Since we intend for this framework to be used in other places
>within GPDB, we ported the entire gtest framework in. We also updated
>gps3ext makefiles to use the correct gtest directory.
>
>Testing:
>./configure and make works correctly and builds GPDB.
>cd gpAux/extensions/gps3ext && make && make -f Makefile.test compiles
>and runs correctly.
>
>Authors: Nikos Armenatzoglou and Shreedhar Hardikar.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/greenplum-db/gpdb/pull/536
>
>-- Commit Summary --
>
>  * Moved S3 gtest to gpAux/extensions and update gtest framework.
>
>-- File Changes --
>
>    M gpAux/extensions/gps3ext/Makefile.test (2)
>D
>gpAux/extensions/gps3ext/gtest/include/gtest/internal/custom/gtest-port.h
>(69)
>D
>gpAux/extensions/gps3ext/gtest/include/gtest/internal/custom/gtest-printers.h
>(0)
>D
>gpAux/extensions/gps3ext/gtest/include/gtest/internal/gtest-port-arch.h
>(93)
>    D gpAux/extensions/gps3ext/gtest/src/gtest-all.cc (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest-death-test.cc (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest-filepath.cc (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest-internal-inl.h (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest-port.cc (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest-printers.cc (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest-test-part.cc (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest-typed-test.cc (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest.cc (0)
>    D gpAux/extensions/gps3ext/gtest/src/gtest_main.cc (0)
>    A gpAux/extensions/gtest/CHANGES (157)
>    A gpAux/extensions/gtest/CMakeLists.txt (252)
>    A gpAux/extensions/gtest/CONTRIBUTORS (37)
>    A gpAux/extensions/gtest/LICENSE (28)
>    A gpAux/extensions/gtest/Makefile.am (306)
>    A gpAux/extensions/gtest/README (435)
>    A gpAux/extensions/gtest/build-aux/.keep (0)
>    A gpAux/extensions/gtest/cmake/internal_utils.cmake (227)
>    A gpAux/extensions/gtest/codegear/gtest.cbproj (138)
>    A gpAux/extensions/gtest/codegear/gtest.groupproj (54)
>    R gpAux/extensions/gtest/codegear/gtest_all.cc (79)
>    A gpAux/extensions/gtest/codegear/gtest_link.cc (40)
>    A gpAux/extensions/gtest/codegear/gtest_main.cbproj (82)
>    A gpAux/extensions/gtest/codegear/gtest_unittest.cbproj (88)
>    A gpAux/extensions/gtest/configure.ac (68)
>    R gpAux/extensions/gtest/include/gtest/gtest-death-test.h (0)
>    R gpAux/extensions/gtest/include/gtest/gtest-message.h (0)
>    R gpAux/extensions/gtest/include/gtest/gtest-param-test.h (47)
>    R gpAux/extensions/gtest/include/gtest/gtest-param-test.h.pump (47)
>    R gpAux/extensions/gtest/include/gtest/gtest-printers.h (244)
>    R gpAux/extensions/gtest/include/gtest/gtest-spi.h (0)
>    R gpAux/extensions/gtest/include/gtest/gtest-test-part.h (0)
>    R gpAux/extensions/gtest/include/gtest/gtest-typed-test.h (8)
>    R gpAux/extensions/gtest/include/gtest/gtest.h (211)
>    R gpAux/extensions/gtest/include/gtest/gtest_pred_impl.h (0)
>    R gpAux/extensions/gtest/include/gtest/gtest_prod.h (0)
>R
>gpAux/extensions/gtest/include/gtest/internal/gtest-death-test-internal.h
>(0)
>   R gpAux/extensions/gtest/include/gtest/internal/gtest-filepath.h (0)
> R gpAux/extensions/gtest/include/gtest/internal/gtest-internal.h (192)
>R gpAux/extensions/gtest/include/gtest/internal/gtest-linked_ptr.h (14)
>R
>gpAux/extensions/gtest/include/gtest/internal/gtest-param-util-generated.h
>(83)
>R
>gpAux/extensions/gtest/include/gtest/internal/gtest-param-util-generated.h.pump
>(29)
>R gpAux/extensions/gtest/include/gtest/internal/gtest-param-util.h
>(152)
>    R gpAux/extensions/gtest/include/gtest/internal/gtest-port.h (967)
>    R gpAux/extensions/gtest/include/gtest/internal/gtest-string.h (0)
>    R gpAux/extensions/gtest/include/gtest/internal/gtest-tuple.h (8)
> R gpAux/extensions/gtest/include/gtest/internal/gtest-tuple.h.pump (8)
>  R gpAux/extensions/gtest/include/gtest/internal/gtest-type-util.h (0)
>R gpAux/extensions/gtest/include/gtest/internal/gtest-type-util.h.pump
>(0)
>    A gpAux/extensions/gtest/m4/acx_pthread.m4 (363)
>    A gpAux/extensions/gtest/m4/gtest.m4 (74)
>    A gpAux/extensions/gtest/make/Makefile (82)
>    A gpAux/extensions/gtest/msvc/gtest-md.sln (45)
>    A gpAux/extensions/gtest/msvc/gtest.sln (45)
>    A gpAux/extensions/gtest/samples/prime_tables.h (123)
>    A gpAux/extensions/gtest/samples/sample1.cc (68)
>    A gpAux/extensions/gtest/samples/sample1.h (43)
>    A gpAux/extensions/gtest/samples/sample10_unittest.cc (144)
>    A gpAux/extensions/gtest/samples/sample1_unittest.cc (153)
>    A gpAux/extensions/gtest/samples/sample2.cc (56)
>    A gpAux/extensions/gtest/samples/sample2.h (85)
>    A gpAux/extensions/gtest/samples/sample2_unittest.cc (109)
>    A gpAux/extensions/gtest/samples/sample3-inl.h (172)
>    A gpAux/extensions/gtest/samples/sample3_unittest.cc (151)
>    A gpAux/extensions/gtest/samples/sample4.cc (46)
>    A gpAux/extensions/gtest/samples/sample4.h (53)
>    A gpAux/extensions/gtest/samples/sample4_unittest.cc (45)
>    A gpAux/extensions/gtest/samples/sample5_unittest.cc (199)
>    A gpAux/extensions/gtest/samples/sample6_unittest.cc (224)
>    A gpAux/extensions/gtest/samples/sample7_unittest.cc (130)
>    A gpAux/extensions/gtest/samples/sample8_unittest.cc (173)
>    A gpAux/extensions/gtest/samples/sample9_unittest.cc (160)
>    A gpAux/extensions/gtest/scripts/fuse_gtest_files.py (250)
>    A gpAux/extensions/gtest/scripts/gen_gtest_pred_impl.py (730)
>    A gpAux/extensions/gtest/scripts/gtest-config.in (274)
>    A gpAux/extensions/gtest/scripts/pump.py (0)
>    A gpAux/extensions/gtest/scripts/test/Makefile (0)
>    A gpAux/extensions/gtest/scripts/upload.py (0)
>    A gpAux/extensions/gtest/scripts/upload_gtest.py (0)
>    A gpAux/extensions/gtest/src/gtest-all.cc (0)
>    A gpAux/extensions/gtest/src/gtest-death-test.cc (0)
>    A gpAux/extensions/gtest/src/gtest-filepath.cc (0)
>    A gpAux/extensions/gtest/src/gtest-internal-inl.h (0)
>    A gpAux/extensions/gtest/src/gtest-port.cc (0)
>    A gpAux/extensions/gtest/src/gtest-printers.cc (0)
>    A gpAux/extensions/gtest/src/gtest-test-part.cc (0)
>    A gpAux/extensions/gtest/src/gtest-typed-test.cc (0)
>    A gpAux/extensions/gtest/src/gtest.cc (0)
>    A gpAux/extensions/gtest/src/gtest_main.cc (0)
>    A gpAux/extensions/gtest/test/gtest-death-test_ex_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-death-test_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-filepath_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-linked_ptr_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-listener_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-message_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-options_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-param-test2_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-param-test_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-param-test_test.h (0)
>    A gpAux/extensions/gtest/test/gtest-port_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-printers_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-test-part_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-tuple_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-typed-test2_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-typed-test_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest-typed-test_test.h (0)
>    A gpAux/extensions/gtest/test/gtest-unittest-api_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest_all_test.cc (0)
>   A gpAux/extensions/gtest/test/gtest_break_on_failure_unittest.py (0)
>  A gpAux/extensions/gtest/test/gtest_break_on_failure_unittest_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_catch_exceptions_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_catch_exceptions_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_color_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_color_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_env_var_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_env_var_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_environment_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest_filter_unittest.py (0)
>    A gpAux/extensions/gtest/test/gtest_filter_unittest_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_help_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_help_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_list_tests_unittest.py (0)
>    A gpAux/extensions/gtest/test/gtest_list_tests_unittest_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_main_unittest.cc (0)
>    A gpAux/extensions/gtest/test/gtest_no_test_unittest.cc (0)
>    A gpAux/extensions/gtest/test/gtest_output_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_output_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_output_test_golden_lin.txt (0)
>    A gpAux/extensions/gtest/test/gtest_pred_impl_unittest.cc (0)
>    A gpAux/extensions/gtest/test/gtest_premature_exit_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest_prod_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest_repeat_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest_shuffle_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_shuffle_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_sole_header_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest_stress_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest_test_utils.py (0)
>    A gpAux/extensions/gtest/test/gtest_throw_on_failure_ex_test.cc (0)
>    A gpAux/extensions/gtest/test/gtest_throw_on_failure_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_throw_on_failure_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_uninitialized_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_uninitialized_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_unittest.cc (0)
>    A gpAux/extensions/gtest/test/gtest_xml_outfile1_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_xml_outfile2_test_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_xml_outfiles_test.py (0)
>    A gpAux/extensions/gtest/test/gtest_xml_output_unittest.py (0)
>    A gpAux/extensions/gtest/test/gtest_xml_output_unittest_.cc (0)
>    A gpAux/extensions/gtest/test/gtest_xml_test_utils.py (0)
>    A gpAux/extensions/gtest/test/production.cc (0)
>    A gpAux/extensions/gtest/test/production.h (0)
>    A gpAux/extensions/gtest/xcode/Config/DebugProject.xcconfig (0)
>    A gpAux/extensions/gtest/xcode/Config/FrameworkTarget.xcconfig (0)
>    A gpAux/extensions/gtest/xcode/Config/General.xcconfig (0)
>    A gpAux/extensions/gtest/xcode/Config/ReleaseProject.xcconfig (0)
> A gpAux/extensions/gtest/xcode/Config/StaticLibraryTarget.xcconfig (0)
>    A gpAux/extensions/gtest/xcode/Config/TestTarget.xcconfig (0)
>    A gpAux/extensions/gtest/xcode/Resources/Info.plist (0)
>  A gpAux/extensions/gtest/xcode/Samples/FrameworkSample/Info.plist (0)
>A
>gpAux/extensions/gtest/xcode/Samples/FrameworkSample/WidgetFramework.xcodeproj/project.pbxproj
>(0)
> A gpAux/extensions/gtest/xcode/Samples/FrameworkSample/runtests.sh (0)
>   A gpAux/extensions/gtest/xcode/Samples/FrameworkSample/widget.cc (0)
>    A gpAux/extensions/gtest/xcode/Samples/FrameworkSample/widget.h (0)
>A gpAux/extensions/gtest/xcode/Samples/FrameworkSample/widget_test.cc
>(0)
>    A gpAux/extensions/gtest/xcode/Scripts/runtests.sh (0)
>    A gpAux/extensions/gtest/xcode/Scripts/versiongenerate.py (0)
>    A gpAux/extensions/gtest/xcode/gtest.xcodeproj/project.pbxproj (0)
>
>-- Patch Links --
>
>https://github.com/greenplum-db/gpdb/pull/536.patch
>https://github.com/greenplum-db/gpdb/pull/536.diff
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/536

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lij55** [comment]
Hi @hardikar , 

Thanks for this PR.
Could you please introduce a little more about the components that  require gtest?
Because usage of C++ is sensitive in GPDB/Postgres, we still can't make final decision about these S3 related codes.

**Comment by armenatzoglou** [comment]
@hlinnaka @lij55 We (query execution team) are currently working on adding support for code generation in GPDB. This will use a set of utility functions around LLVM and CLANG written in C++ and tested using gtest framework. We observed that gps3ext uses gtest framework already. We do not want to have multiple instances of gtest in the code, so we move the existing gtest framework into a more suitable location.

**Comment by gcaragea** [comment]
Looks good to me. Having a generic testing framework inside a specific component doesn't sound quite right. 

+1 for moving it to a more share-able location.

**Comment by foyzur** [comment]
LGTM. Agree with @gcaragea. gtest is a fantastic testing framework, and we will have plenty of use going forward. Keeping it in an appropriately shared location makes sense.

**Comment by lij55** [comment]
It is great to share common infrastructures of course.  However, I have some questions about this modification.
There are changes about the source code of gtest. Does it mean you use different gtest version? why?
Which g++ version it need?

**Comment by hlinnaka** [comment]
We already have cmockery, pg_regress, and Behave. Later, we will inherit isolationtester and TAP tests from the upstream.

What does gtest do that the existong frameworks cannot do? If it's a nicer replacement e.g. for cmockery,  is there a plan to rewrite the existing cmockery tests using gtest?

If it can achieve things that the existing frameworks cannot, that's OK, but I don't want to introduce a whole new framework just because "it's good".

- Heikki

On 17 March 2016 20:25:41 EET, Nikos Armenatzoglou <notifications@github.com> wrote:
>@hlinnaka @lij55 We (query execution team) are currently working on
>adding support for code generation in GPDB. This will use a set of
>utility functions around LLVM and CLANG written in C++ and tested using
>gtest framework. We observed that gps3ext uses gtest framework already.
>We do not want to have multiple instances of gtest in the code, so we
>move the existing gtest framework into a more suitable location.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/greenplum-db/gpdb/pull/536#issuecomment-198017936

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by armenatzoglou** [comment]
@lij55 Correct, this is gtest version 1.7.0 and it builds on CentOS 7 with g++ 4.8.5 and also on Mac Yosemite with clang-602.0.53. All gps3ext tests compile and run correctly, except for those that are unable to connect to a server.

**Comment by armenatzoglou** [comment]
@hlinnaka We understand your concerns, but with this PR we do not introduce gtest, we simply move it in the source tree. gps3ext already uses it. Also, currently the only framework in GPDB available for unittesting c++ code is gtest.

**Comment by vraghavan78** [comment]
+1

**Comment by hardikar** [comment]
Pushed with commit 9da8075c29ecb6e318b7c8815a950071564700b4

**Comment by hlinnaka** [comment]
On 18/03/16 19:57, Nikos Armenatzoglou wrote:
> @hlinnaka We understand your concerns, but with this PR we do not
> introduce gtest, we simply move it in the source tree. gps3ext
> already uses it. Also, currently the only framework in GPDB available
> for unittesting c++ code is gtest.

The use of Gtest even in gps3ext was controversial, and the whole module 
will need to be rewritten at some point anyway.

I don't like the proliferation of test frameworks. We have many of them 
already. Again, if it can somehow facilitate testing things that cannot 
be tested with the existing frameworks, then we probably need it. But 
gtest is a big library, adding a dependency to it needs more explanation 
than this. What is it that you want to do with it?

- Heikki

**Comment by danielgustafsson** [comment]
Since we now are the maintainers of this vendored code I would like to see the maintenance plan for how to deal with it and our local modifications to it.

**Comment by armenatzoglou** [comment]
On Sat, Mar 19, 2016 at 12:30 AM, Heikki Linnakangas <
notifications@github.com> wrote:

> On 18/03/16 19:57, Nikos Armenatzoglou wrote:
> > @hlinnaka We understand your concerns, but with this PR we do not
> > introduce gtest, we simply move it in the source tree. gps3ext
> > already uses it. Also, currently the only framework in GPDB available
> > for unittesting c++ code is gtest.
>
> The use of Gtest even in gps3ext was controversial, and the whole module
> will need to be rewritten at some point anyway.
>
> I don't like the proliferation of test frameworks. We have many of them
> already. Again, if it can somehow facilitate testing things that cannot
> be tested with the existing frameworks, then we probably need it. But
> gtest is a big library, adding a dependency to it needs more explanation
> than this. What is it that you want to do with it?
>
> - Heikki
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/pull/536#issuecomment-198652806>
>
As we have already described in the OSS Codegen GPDB Proposal
<https://docs.google.com/document/d/1MPyfvRWwnFREgriTwS2hkk_WHbvrTOW3gAtva_2epJ0/edit#heading=h.zadz5ppw5gmc>,
we will use a set of utility functions around LLVM and CLANG written in
C++. Currently, core of GPDB does not contain any testing framework for c++
code. However, gps3ext extension uses gtest, which is a testing framework
for C++ code. Due to this reason and the fact that all of the codegen
utility tests are written using this framework (please see PR:
https://github.com/greenplum-db/gpdb/pull/549), we want to use gtest.

To avoid checking-in gtest's code into GPDB, we will investigate adding it
as an external Cmake project, which fetches sources from the internet and
compile them as third-party dependencies in GPDB. This is a good approach
that helps us to be more flexible and do not need to maintain any external
code.

**Comment by hlinnaka** [comment]
On 21/03/16 20:19, Nikos Armenatzoglou wrote:
> As we have already described in the OSS Codegen GPDB Proposal
> <https://docs.google.com/document/d/1MPyfvRWwnFREgriTwS2hkk_WHbvrTOW3gAtva_2epJ0/edit#heading=h.zadz5ppw5gmc>,
> we will use a set of utility functions around LLVM and CLANG written in
> C++. Currently, core of GPDB does not contain any testing framework for c++
> code. However, gps3ext extension uses gtest, which is a testing framework
> for C++ code. Due to this reason and the fact that all of the codegen
> utility tests are written using this framework (please see PR:
> https://github.com/greenplum-db/gpdb/pull/549), we want to use gtest.

Let's put this on hold for now, until we see what the API of the codegen 
module will look like. The entry functions into codegen will be callable 
from C (because they will be called from C code from elsewhere in the 
backend), and I would assume that the API encapsulates the functionality 
in a way that's straightforward to write automated tests for. And 
because the API is callable from C, it should be straightforward to 
write the tests for it using cmockery. And presumably the structure 
inside the module is simple enough that there isn't need to write 
separate unit tests for sub-units within the module. But this is a lot 
of speculation, I might well be missing something, so let's just wait 
and see what the API of the codegen module will look like.

- Heikki

**Comment by armenatzoglou** [comment]
We understand your concerns. As I mentioned above, we will investigate if
it is possible to add gtest as an external Cmake project, which fetches
sources from the internet and compile them as third-party dependencies in
GPDB. This will address your concerns regarding maintainability.

**Comment by gcaragea** [comment]
On Mon, Mar 21, 2016 at 11:26 AM, Heikki Linnakangas <
notifications@github.com> wrote:

>
> Let's put this on hold for now, until we see what the API of the codegen
> module will look like. The entry functions into codegen will be callable
> from C (because they will be called from C code from elsewhere in the
> backend), and I would assume that the API encapsulates the functionality
> in a way that's straightforward to write automated tests for. And
> because the API is callable from C, it should be straightforward to
> write the tests for it using cmockery. And presumably the structure
> inside the module is simple enough that there isn't need to write
> separate unit tests for sub-units within the module. But this is a lot
> of speculation, I might well be missing something, so let's just wait
> and see what the API of the codegen module will look like.
>

At Pivotal, one fundamental practice that we follow is Test Driven
Development (TDD), which is different than what Postgres does. That means
the tests must be written before writing the code. This is exactly what we
did in the Codegen utils pull request, if you look at the commit history.

In order to do TDD, we must have the right tool that allows us to write
tests from day 1. If we wait until we have full integration with GPDB, this
means we can go for a long time until we are able to test. That is why we
need additional frameworks, such as Gtest.

We should be mindful of how many frameworks we bring in, I think we can all
agree on that. But a complete ban is very unproductive, and against the TDD
principle, as well as not having the right tool for the right job.

**Comment by danielgustafsson** [comment]
In my opinion there are absolutely no bans on adding dependencies/tools but rather: If a new tool or dependency is added (especially when duplicating functionality), why isn't the existing tool good enough/sufficient and how do we migrate the use of the existing tool to the new tool to over time minimize the complexity and footprint. Having the right tools for the job is essential, we just want to avoid having (too) many tools for the same job at once.

**Comment by vraghavan78** [comment]
I agree with @gcaragea completely banning frameworks and utilities needed for a functionality before a complete end-to-end prototype does not foster incremental innovation. This will only lead to long living private branches which open other can of worms.

As long, new work does not hinder upstream merges too much we should march on with confidence but with mindfulness!

**Comment by hlinnaka** [comment]
On 21/03/16 22:19, Venkatesh Raghavan wrote:
> I agree with @gcaragea completely banning frameworks and utilities
> needed for a functionality before a complete end-to-end prototype
> does not foster incremental innovation. This will only lead to long
> living private branches which open other can of worms.
>
> As long, new work does not hinder upstream merges too much we should
> march on with confidence but with mindfulness!

Please just focus on getting the slot_deform_tuple() prototype working. 
Once we reach that first milestone, and we'll be a lot wiser.

- Heikki

**Comment by hlinnaka** [comment]
Wait, what, you pushed this already!? There were objections and discussion was on-going!

**Comment by yydzero** [comment]
My two cents:

1) gtest is better library than existing cmockery for TDD
2) gtest is a 3rd party dependency, it is better to not include its source
code in GPDB repo.

On Tue, Mar 22, 2016 at 3:18 PM, Heikki Linnakangas <
notifications@github.com> wrote:

> Wait, what, you pushed this already!? There were objections and discussion
> was on-going!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/pull/536#issuecomment-199673413>
>



-- 
Best Regards,
Yandong

**Pull request closed without merging**
