### PR TITLE
[6X] gpcheckcat: Improvements to aoseg vpinfo check

### PR DESCRIPTION
**Pull request by soumyadeep2007**
This is a partial backport of #15211 (don't need the second commit, see Ashwin's explanation below). There were minor conflicts, please refer to the commit message for more information.

6X dev pipeline with gpcheckcat box: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_checkcat_attrib

### CODE REVIEW

**Comment by ashwinstar** [comment]
6X don't need second commit "gpcheckcat: Improvements to aoseg vpinfo check" right? As 6x doesn't use frozen inserts and hence vpinfo stays in sync with pg_class.

**Comment by soumyadeep2007** [comment]
>6X don't need second commit "gpcheckcat: Improvements to aoseg vpinfo check" right? As 6x doesn't use frozen inserts and hence vpinfo stays in sync with pg_class.

I think you mean ` gpcheckcat: Avoid false positives in vpinfo check`. Yes you are right. I'll get rid of it.

**Review by divyeshddv — APPROVED** [review]
LGTM

**Review by ashwinstar — APPROVED** [review]
Yes :+1:

**Pull request merged**
