### PR TITLE
Fix lwlock double-acquire in checkpointer

### PR DESCRIPTION
**Pull request by dh-cloud**
In function SaveSlotToPath, the lwlock io_in_progress_lock will
never be released if something wrong.

It causes bad things, e.g. 6X BRANCH:
| If no space left in disk which are exhausted **temporarily** by
| some query, the checkpointer process may occur PANIC in its
| future cycle:
|
|   elog(PANIC, "Waiting on lock already held!"); -- lwlock.c

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by dh-cloud** [comment]
6x:

```
2020-10-10 08:07:51.989255,,,p11747,th-450070400,,,,0,,,seg355,,,,,"LOG","53100","could not create file ""pg_replslot/internal_wal_replication_slot/state.tmp"": No space left on device",,,,,,,0,,"slot.c",1085


2020-10-10 09:20:51.140285,,,p11747,th-450070400,,,,0,,,seg355,,,,,"PANIC","XX000","Waiting on lock already held!",,,,,,,0,,"lwlock.c",668,"Stack trace:
1    0xc5f69c postgres errstart (elog.c:557)
2    0xc62385 postgres elog_finish (elog.c:1729)
3    0xad7499 postgres LWLockAcquire (lwlock.c:668)
4    0xa9e0b3 postgres CheckPointReplicationSlots (slot.c:1072)
5    0x77863f postgres CreateCheckPoint (xlog.c:9177)
6    0xa5672d postgres CheckpointerMain (checkpointer.c:523)
7    0x7c063e postgres AuxiliaryProcessMain (bootstrap.c:442)
8    0xa62b95 postgres <symbol not found> (postmaster.c:5822)
9    0xa63d45 postgres <symbol not found> (postmaster.c:3233)
10   0x7fcfe35fb5f0 libpthread.so.0 <symbol not found> + 0xe35fb5f0
11   0x7fcfe2dfb933 libc.so.6 __select + 0x13
12   0x6bf77d postgres <symbol not found> (postmaster.c:1884)
13   0xa66663 postgres PostmasterMain (postmaster.c:1513)
14   0x6c664b postgres main (discriminator 1)
15   0x7fcfe2d28505 libc.so.6 __libc_start_main + 0xf5
16   0x6d26bf postgres <symbol not found> + 0x6d26bf
" 
```

coredump:
```
(gdb) 
#0  0x00007fcfe2d3c337 in raise () from /lib64/libc.so.6
#1  0x00007fcfe2d3da28 in abort () from /lib64/libc.so.6
#2  0x0000000000c60858 in errfinish (dummy=dummy@entry=0) at elog.c:763
#3  0x0000000000c624c6 in elog_finish (elevel=elevel@entry=22, fmt=fmt@entry=0x1226c6d "Waiting on lock already held!") at elog.c:1749
#4  0x0000000000ad7499 in LWLockAcquireCommon (val=0, valptr=0x0, mode=LW_EXCLUSIVE, l=0x7fcf4b84ed40) at lwlock.c:668
#5  LWLockAcquire (l=0x7fcf4b84ed40, mode=mode@entry=LW_EXCLUSIVE) at lwlock.c:510
#6  0x0000000000a9e0b3 in SaveSlotToPath (elevel=15, dir=0x7fff3d5878c0 "pg_replslot/internal_wal_replication_slot", slot=0x7fcfd61d3108) at slot.c:1069
#7  CheckPointReplicationSlots () at slot.c:917
#8  0x000000000077863f in CheckPointGuts (flags=288, checkPointRedo=134822587840) at xlog.c:9177
#9  CreateCheckPoint (flags=flags@entry=288) at xlog.c:8902
#10 0x0000000000a5672d in CheckpointerMain () at checkpointer.c:523
#11 0x00000000007c063e in AuxiliaryProcessMain (argc=argc@entry=2, argv=argv@entry=0x7fff3d588810) at bootstrap.c:442
#12 0x0000000000a62b95 in StartChildProcess (type=CheckpointerProcess) at postmaster.c:5822
#13 0x0000000000a63d45 in reaper (postgres_signal_arg=<optimized out>) at postmaster.c:3233
#14 <signal handler called>
#15 0x00007fcfe2dfb933 in __select_nocancel () from /lib64/libc.so.6
#16 0x00000000006bf77d in ServerLoop () at postmaster.c:1882
#17 0x0000000000a66663 in PostmasterMain (argc=argc@entry=5, argv=argv@entry=0x2f04fd0) at postmaster.c:1508
#18 0x00000000006c664b in main (argc=5, argv=0x2f04fd0) at main.c:245
```

**Comment by asimrp** [comment]
I would recommend merging this patch into 6X_STABLE only.  We will get this change in master branch when merging REL_12_STABLE from upstream, specifically the two commits:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=49bf81536e242f079bfbce6e8f95f53f18207dd5
and 
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=a9d9bdd3ad21a73b481911f22279e004679d172e

**Comment by asimrp** [comment]
Good catch and thanks for the fix, @dh-cloud!

**Comment by dh-cloud** [comment]
> I would recommend merging this patch into 6X_STABLE only. We will get this change in master branch when merging REL_12_STABLE from upstream, specifically the two commits:
> https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=49bf81536e242f079bfbce6e8f95f53f18207dd5
> and
> https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=a9d9bdd3ad21a73b481911f22279e004679d172e

Thanks, I simply checked GP master branch(12beta already), forgot to check the latest PG upstream.

Who is to PR the patch to 6X?

**Comment by kainwen** [comment]
> > I would recommend merging this patch into 6X_STABLE only. We will get this change in master branch when merging REL_12_STABLE from upstream, specifically the two commits:
> > https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=49bf81536e242f079bfbce6e8f95f53f18207dd5
> > and
> > https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=a9d9bdd3ad21a73b481911f22279e004679d172e
> 
> Thanks, I simply checked GP master branch(12beta already), forgot to check the latest PG upstream.
> 
> Who is to PR the patch to 6X?

You can open a pr to 6X. Thanks.

**Comment by ashwinstar** [comment]
Just a recommendation, instead of taking this patch to 6X_STABLE, cherry-pick the upstream commits to 6X_STABLE. Thanks for reporting the issue.

**Comment by dh-cloud** [comment]
> Just a recommendation, instead of taking this patch to 6X_STABLE, cherry-pick the upstream commits to 6X_STABLE. Thanks for reporting the issue.

Thanks, done #11030

**Comment by ashwinstar** [comment]
Closing this one as planning to get it via merge to PostgreSQL 12 STABLE for current development branch.

**Pull request closed without merging**
