### PR TITLE
Fix external table CR as end of line issue

### PR DESCRIPTION
**Pull request by HaozhouWang**
This commit fix issue #1621. Current external table implementation
only recognize LF as line end. If table is created with CR as line
end then no data can be selected because whole data is never
split into lines.

Signed-off-by: Peifeng Qiu <pqiu@pivotal.io>

### CODE REVIEW

**Comment by hlinnaka** [comment]
What about EOL_CRLF? Is that handled correctly?

**Comment by HaozhouWang** [comment]
Yes, the EOL_CRLF can be handled correctly now.

**Comment by hlinnaka** [comment]
Are you sure? I don't see any handling of EOL_CRLF here. I suspect we're treating EOL_CRLF case the same as EOL_LF, but that's not correct. If there's a stray LF on a row, which is not a CR+LF, we must not split the input on that.

**Comment by HaozhouWang** [comment]
Thanks Heikki!
Yep, it is not correct to treat CRLF as LF and could be an issue for gpfdist. 
We will investigate this issue and add test cases to cover this issue.

**Comment by adam8157** [comment]
Please take care the subject and commit message of "Add gpfdist test"

**Comment by HaozhouWang** [comment]
@hlinnaka could you please help us review this PR?
Thanks in advance!

**Comment by adam8157** [comment]
LGTM

**Comment by andreasscherbaum** [comment]
This comes with 113kB and 346kB diff for the tests - is it necessary to expand the tests by tens of thousands of lines? Or can the functionality be tested in a few dozen lines?

**Comment by HaozhouWang** [comment]
Hi Andreas,

Yes, these two files are used for gpfidst tests. The gpfidst will load the files as 32KB blocks (minimum), and it needs several blocks to trigger this bug. They are the minimum size of files we tested that can reproduce this bug of gpfdist.

Regards,
Haozhou

**Pull request merged**
