### PR TITLE
Backfill isolation2 test for commit 0417465a744

### PR DESCRIPTION
**Pull request by dgkimura**
I verified that undoing commit 0417465a744 will cause this new testcase to
hang.

### CODE REVIEW

**Comment by pobbatihari** [comment]
Hi @dgkimura,

I appreciate the inclusion of the isolation2 testcase to address the deadlock scenario. Could we also consider adding a testcase for dynamic sequential scan? Additionally, I would like to confirm if dynamic index-only scan is being covered by another PR.

**Comment by dgkimura** [comment]
On Tuesday, July 18, 2023 8:45 PM Hari krishna wrote:
> Could we also consider adding a testcase for dynamic sequential scan?

Yeah, make sense.  Fixed up the commit and added testcase

> Additionally, I would like to confirm if dynamic index-only scan is being covered by another PR.

Added this one here as well.  It's labeled as ORCA_FEATURE_NOT_SUPPORTED because the feature hasn't been merged yet.

**Review by chrishajas — APPROVED** [review]

**Comment by pobbatihari** [comment]
[NIT]-- Transaction 2: processed on segment 1, blocked on all other segments (waiting on transaction 1)
With the current code changes:
-- Transaction2: will be blocked at coordinator, until Transaction1 release the lock on coordinator on particular partition.

**Review by pobbatihari — APPROVED** [review]
LGTM

**Comment by dgkimura** [comment]
Merged. Thanks for the reviews

**Pull request merged**
