### PR TITLE
fix possible deadlocks between catalog update and FTS

### PR DESCRIPTION
**Pull request by Stolb27**
This problem partially fixed in #8012
However, these changes do not take into account the lock mode of nested functions
for gp_add_segment_mirror (add_segment_config, add_segment_config_entry,
get_availableDbId). This functions still require AccessExclusiveLock mode.
Catalog changes are proccess in single transaction for ALL segments so this mode
will be held until transaction commit. So we may get deadlock if we will be restore
multiple segments for cluster with large persistent tables, which will require updating
the catalog more than 30 * 2 (DISPATCH_WAIT_TIMEOUT_MSEC) seconds.

In general, any update catalog operations requiring dispatch may cause deadlock with FTS.
So fixed gp_add_master_standby too.

gp_add_segment does not dispatch, but is performed in one transaction with the update
of the mode and status of the segment, which require dispatching

6X and master not affected by this problem because not use dispatch for catalog changes
(https://github.com/greenplum-db/gpdb/issues/8032#issuecomment-506644559).

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by Stolb27** [comment]
Hello!
I locked gp_persistent_relation_node on last primary with failed mirror in utility mode before gprecoverseg try to update catalog, waited for FTS probe started from dispatch check, released lock. Deadlock appeared without fix. With fix gprecoverseg continued his work after lock release.
We need kill mirror, wait for FTS detect mirror down, inject 1 minute sleep in gp_add_segment_persistent_entries and run gprecoverseg with full recovery to test this case more properly.
Can you advice which kind of test will let me implement this scenary as autotest?

**Comment by asimrp** [comment]
Taking another look, I realized that the existing fts_deadlock.source covers all the cases being fixed here.  Thank you for writing that test, but it looks much more complex that what we already have.  My vote is to keep the existing test and merge this fix in.

**Comment by Stolb27** [comment]
Thanks! But existing test not verify needed case at all. **fts_deadlock.source** verifies that the FTS service will be able to read gp_segment_configuration locked in ExclusiveLock mode. But the locks used by the gprecoverseg remain unverified. Maybe use another test kind?

**Comment by darthunix** [comment]
@asimrp I vote to remove current tests and replace them with the new ones. Current tests don't catch deadlock problem we fix, but the new ones - do.

**Comment by asimrp** [comment]
Locks acquired by gprecoverseg do affect concurrently running backends such as FTS that try to modify the same table, namely gp_segment_configuration.  This is no different from any two concurrently running backends affecting each other by holding locks and releasing them.

What we are concerned here is the deadlock between gprecoverseg and FTS.  The key piece to that deadlock is the link that completes the wait cycle - gprecoverseg must wait for FTS to probe the segments.  The fts_deadlock.source validates this link.

**Comment by asimrp** [comment]
It is true that current test doesn't cover the problem fully but the problem cannot be covered without a contrived test, susceptible to CI idiosyncrasies.  That's why a simpler test is is appealing here but I don't feel too strongly about it.

**Comment by asimrp** [comment]
Thank you for the contribution, @Stolb27.  If you feel strongly about the test, please feel free to raise another PR, this patch only contained the code change and I merged it.

**Comment by asimrp** [comment]
And the ubuntu compile job in the CI has failed for completely unrelated reason: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/5X_STABLE/jobs/compile_gpdb_ubuntu16/builds/107

**Comment by asimrp** [comment]
That ubuntu compile failure has been resolved, thanks to @BaiShaoqi and @baotingfang.  There is one more unrelated failure https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/5X_STABLE/jobs/icw_planner_ubuntu16/builds/103

```diff
======================================================================
 DIFF FILE: ../gpdb_src/src/test/isolation2/regression.diffs
----------------------------------------------------------------------
*** ./expected/uao/drop_while_vacuum_row.out	Wed Apr 29 12:10:04 2020
--- ./results/uao/drop_while_vacuum_row.out	Wed Apr 29 12:10:04 2020
***************
*** 17,23 ****
  (1 row)
  1>: DROP TABLE ao;  <waiting ...>
  2: VACUUM ao;
! VACUUM
  1<:  <... completed>
  DROP
  1: SELECT COUNT(*) FROM ao;
--- 17,23 ----
  (1 row)
  1>: DROP TABLE ao;  <waiting ...>
  2: VACUUM ao;
! ERROR:  relation "ao" does not exist
  1<:  <... completed>
  DROP
  1: SELECT COUNT(*) FROM ao;
```

**Pull request merged**
