### PR TITLE
Fix incorrect proisstrict settings on json functions

### LINKED ISSUE #2369: invalid JSON query terminates all connections
Very excited to see 9.3 JSON support here! Certain bad JSON queries bring down our whole system, though, which makes the feature more dangerous than it is useful for us.

```
gpadmin=# select version();
                                                                                       version                                                                
                       
--------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------
 PostgreSQL  (Greenplum Database 5.0.0-alpha+eea17dd build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18) compiled o
n May  4 2017 00:51:04
(1 row)

gpadmin=# select '[{"a":1}]'::json->0;
 ?column? 
----------
 {"a":1}
(1 row)

gpadmin=# select '[{"a":1}]'::json->0->'a';
 ?column? 
----------
 1
(1 row)

gpadmin=# select '[{"a":1}]'::json->0->'b';
 ?column? 
----------
 
(1 row)

gpadmin=# select '[{"a":1}]'::json->1->'a';
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>
```

Master log:
```
2017-05-04 05:30:08.294033 UTC,"gpadmin","gpadmin",p18585,th560986048,"[local]",,2017-05-04 05:29:14 UTC,0,con16,cmd8,seg-1,,dx17,,sx1,"LOG","00000","statement: select '[{""a"":1}]'::json->1->'b';",,,,,,"select '[{""a"":1}]'::json->1->'b';",0,,"postgres.c",1623,
2017-05-04 05:30:08.294114 UTC,,,p18585,th0,,,2017-05-04 05:29:14 UTC,0,con16,cmd8,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,
2017-05-04 05:30:08.490421 UTC,,,p17968,th560986048,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 18585) was terminated by signal 11: Segmentation fault ",,,,,,,0,,"postmaster.c",5578,
2017-05-04 05:30:08.490443 UTC,,,p17968,th560986048,,,,0,,,seg-1,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",5257,
```

Thoughts?

### PR DESCRIPTION
**Pull request by danielgustafsson**
Commit c79f51a1b4 incorrectly set proisstrict to false on some of the json functions which indeed are strict. Fix by updating the pg_proc entries. This fixes #2369.

This will require a catversion bump which might be problematic while in alpha? ping @pivotal-mike

### CODE REVIEW

**Comment by ivannovick** [comment]
thx @danielgustafsson

**Comment by Eulerizeit** [comment]
@schubert @pivotal-mike @ivannovick 

Given there is broken functionality I feel like we should push this in.

**Comment by hlinnaka** [comment]
Yeah, we need to fix this.

There is a choice, on whether we want to bump the catversion for this, forcing everyone to dump & restore, or keep catversion the same, so that old clusters continue to work, except that this bug will not be fixed for them.

**Comment by schubert** [comment]
@ivannovick's call - we didn't want to do this now that we are alpha although if we're going to do it, this is a pretty good reason to do so. shouldn't affect many people at this point so I'd rather now than later.

**Comment by hsyuan** [comment]
If we decide to push this in, can we add this query `select '[{"a":1}]'::json->1->'a';` into ICG test?

**Comment by danielgustafsson** [comment]
@hsyuan if we do a catversion bump we should add a test for it yes. If not we'll add the test once we open the tree for 6.0.

**Comment by hlinnaka** [comment]
On 05/05/2017 01:03 AM, Daniel Gustafsson wrote:
> @hsyuan if we do a catversion bump we should add a test for it yes.
> If not we'll add the test once we open the tree for 6.0.

Assuming we will fix the entries in pg_proc.h in any case, we can add 
the test for it in any case, too.

- Heikki

**Comment by danielgustafsson** [comment]
> On 05 May 2017, at 07:42, Heikki Linnakangas <notifications@github.com> wrote:
> 
> On 05/05/2017 01:03 AM, Daniel Gustafsson wrote:
> > @hsyuan if we do a catversion bump we should add a test for it yes.
> > If not we'll add the test once we open the tree for 6.0.
> 
> Assuming we will fix the entries in pg_proc.h in any case, we can add 
> the test for it in any case, too.

Good point, I’ll add it to this PR.

**Comment by professor** [comment]
I like to use these situations as learning opportunities for myself and the organization. 

a) How did we discover this issue?  
b) What could we have done differently in the past to the detect this issue before we froze the catalog?  

In looking at pg_proc.h on 8.4 and 9.6 this appears to be declarative code. Normally, I would not expect declarative code to be unit tested, just manually inspected. However, this code seems very important. Further complicating this, it looks like the data structure has changed between versions making upgrading more error prone. 

Just curious, Todd

**Comment by ivannovick** [comment]
I would rather fix it and force people to dump restore, given we are still in alpha and found the issue.  In beta I would be more hesitant and after GA we can't do it

**Comment by schubert** [comment]
Agreed.

**Pull request merged**
