### PR TITLE
Remove unnecessary code during hash agg cleanup

### PR DESCRIPTION
**Pull request by foyzur**
We noticed that during destroy_agg_hash_table we unnecessarily memset buckets and bloom filters (not going to exist shortly after that) and reset group_bug memory pool (the pool would get deleted completely shortly after that). We remove such unnecessary code as they can be quite expensive redundant operation for a very large hash table.

We also free spill_set explicitly as we were cleaning up the contents of spill_set but not the spill_set itself.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@foyzur Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1403)!

[Click here](https://cla.pivotal.io/sync/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1403) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@foyzur Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/greenplum?repositoryId=greenplum-db/gpdb&pullRequestId=1403)!

**Comment by Eulerizeit** [comment]
I was just asking about this, this is awesome.

**Comment by foyzur** [comment]
Thanks guys for the fast review!

**Pull request merged**
