### PR TITLE
Fix the uninitialized variable Coverity issue [#115720705]

### PR DESCRIPTION
**Pull request by xinzweb**

### CODE REVIEW

**Comment by vraghavan78** [comment]
+1

**Comment by oarap** [comment]
+1

**Comment by hlinnaka** [comment]
CdbPathLocus has no "partkey" field..

**Comment by xinzweb** [comment]
@hlinnaka, you are right. I found that also when I tried to locally compile. Seems like this patch doesn't directly apply on master. Let me reconfirm. Thanks.

**Comment by xinzweb** [comment]
@hlinnaka Adjust the patch based on the different structure of `CdbPathLocus`. Just initialize the entire structure to 0 or NULL pointers.

**Pull request merged**
